### ISSUE TITLE
Populate GamePhysics Source Fields

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1005]
As in #997, the Source fields of GamePhysics need to be populated with citations in the examples, but first, they need to be populated in caseStudies, as they are missing there.

**Comment by JacquesCarette** [comment]
@smiths is this still something that should be done? If so, it might be a nice one to do while waiting for things to compile, etc.

**Comment by smiths** [comment]
I think we can close this issue.  We should populate the source fields for game physics, but I think the problems with the game physics case study are deeper than just adding a few citations.  The revision of game physics is captured in the list of tasks given in:
https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/Planning/PotGradStdProj
