### ISSUE TITLE
Look at failure due to maxOrder

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1009]
See details in check-in 80cfb788f7.

**Comment by JacquesCarette** [comment]
I think this issue is 'obsolete', in that enough things might have changed that it is just no longer relevant, but I'm not sure. @bmaclach any idea? [I'm asking because the back-end code has changed a lot, and this failure is related to the 'design' of GlassBR; "I don't know" is an acceptable answer...]

**Comment by bmaclach** [comment]
It looks to be related to MIS generation, which we don't do anymore, and a search for `maxOrder` in the code base turns up empty, so it does seem obsolete.
