### ISSUE TITLE
Update GlassBR to include Jmin and Jmax from manual version

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1010]
GlassBR was modified in the manual version to include Jmin and Jmax symbolic constants.

https://github.com/smiths/caseStudies/commit/a53b1be89fc33aff2e3faaaa133583c3d7c3e7cc

The same changes should be made to the Drasil version.

**Comment by JacquesCarette** [comment]
@smiths I'm not quite sure what to do with this one. It feels like it ought to be quite straightforward (and so we should just assign it and have it resolved), but I'm not entirely sure.

**Comment by smiths** [comment]
I've verified that this change was never made.   I'm not sure why it wasn't assigned to anyone previously.  It should be straightforward to fix.  It only involves defining 2 constants (Jmin and Jmax) and adding a data constraint.  That change should propagate nicely to the generated code.

This seems like something we could assign to the summer students.  I'll add this to the list of issues that we identified for them to work on.

**Comment by muhammadaliog3** [comment]
In order for the J constraint to appear in the outputs table I will also have to change several lines in the stable version of glassbr. Is that okay?

**Comment by smiths** [comment]
Yes, updating stable is part of the process.  The stable version is wrong in this case, so it needs to be edited.  You shouldn't change it manually.  You should generate stable (using Drasil) and use the generated stable as the new version.

**Comment by JacquesCarette** [comment]
You should still do a visual check of the new version, to make sure it does make sense to do that change. What I mean is that, even though we want to include Jmin and Jmax, it is possible that a small mistake happened while doing that, and a visual check of the results will catch it. It's part of the QA pass of updating stable from the generated stable.
