### ISSUE TITLE
secBuildMISGen (MIS generation) Workflow

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#1011]
- [x] Introduction

- [ ] Notation
    - [ ] Data Type Table
        From Case Studies:
![image](https://user-images.githubusercontent.com/35268928/44805339-ebd4ce80-ab91-11e8-99dc-89b74d0d058b.png)

- [x] Module Hierarchy

- [x] References

**Modules**
- [ ] Control
    - [x] Uses
    - [ ] Syntax
        - [ ] Exported Constants
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] State Variables
        - [ ] Access Routine Semantics
- - -
- [ ] Input
    - [x] Uses
    - [ ] Syntax
    - [ ] Semantics
        - [ ] Enviroment Variables
        - [ ] State Variables
        - [ ] Assumptions
        - [ ] Access Routine Semantics
    - [ ] Considerations
- - -
- [ ] LoadASTM
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] Enviroment Variables
        - [x] State Variables
        - [x] State Invariant
        - [ ] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] Calc
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [x] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] GlassTypeADT
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [x] Exported Types (Is done however its placement is incorrect, should go under Syntax)
        From Generated:
![image](https://user-images.githubusercontent.com/35268928/44806650-871b7300-ab95-11e8-894f-8a4c4f9a6630.png)
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] ThicknessADT
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [x] Exported Types (*)
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] FunctADT
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [x] Exported Types (*)
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
    - [ ] Considerations
- - -
- [ ] ContoursADT
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [x] Exported Types (*)
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] SeqSerivces
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [x] State Variables
        - [x] State Invariant
        - [ ] Assumptions
        - [ ] Access Routine Semantics
- - -
- [ ] Output
    - [x] Uses
    - [ ] Syntax
        - [x] Exported Constants
        - [ ] Exported Access Programs
    - [ ] Semantics
        - [ ] Enviroment Variables
        - [x] State Variables
        - [x] State Invariant
        - [x] Assumptions
        - [ ] Access Routine Semantics
- - -
- [x] Constants
    - [x] Uses
    - [x] Syntax
        - [x] Exported Constants
        - [x] Exported Types
        - [x] Exported Access Programs
    - [x] Semantics
        - [x] State Variables
        - [x] State Invariant
- - -
- [x] Hardware

**Comment by smiths** [comment]
Thank you @elwazana.  This information is very helpful.

**Comment by JacquesCarette** [comment]
This one feels obsolete too, in that we don't try to generate MIS at the moment, right? Perhaps an 'icebox' category? Or even move to the wiki and close?

**Comment by balacij** [comment]
I like the idea of moving this to the wiki, but I'm just not quite sure what we would move to the wiki? The list alone doesn't really give me anything to move that I think newcomers could read and make sense of. I'm going to close the ticket considering we don't do anything with MIS generation. I imagine we would naturally come across whatever was discussed here when someone is trying to generate the MIS.
