### ISSUE TITLE
Enhance Document to include Chapters, Parts, etc.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#1019]
Currently our documents only support sections and subsections, but there are a few other partitioning schemes that we should also include (ex. Chapters, Parts). I think this would be a good addition when we get to larger recipes.

I've made some notes in the Document.hs file as of commit 47bd13d1eb7a938a59eb9fc174d57de3d833c4f7.

**Comment by balacij** [comment]
I think this issue will naturally re-appear when we have a specific use-case for it. Until we have a north star, I don't think anyone will be motivated to work on this issue. So, another one should be opened when we have a specific need.
