### ISSUE TITLE
Traceability Matrix Design

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#1020]
I have posted a version of generating the matrix 452c165b8adf7a7ff32e39f5503fd2dd4d69b37c. But it basically follows the old way of making the matrix. I still need a manual way to combine a ref title with a string name like `DD1` and etc. And the core algorithm to mark `X` where there exists a referencing relation is by giving the `String` and match this `String` with title's string and decide whether there is an empty block or a `X`.

The new changes just goes through the 'RefbyMap' and uses the UID and labels to find the corresponding `String` in the manually generated map. Using string matching to fill the table marks.

The reason I still use the old methods because `String` like `DD1` looks like the currently good thing to make comparisons between table titles and actually relations. `Sentence` does not have `Eq` interface, so if only using the sentences made from labels to be the title, it would be hard to compare and indicates which block should be filled.

If you think it is necessary to fully make it automatic, we may need a technique to generate enumerated names for each chunk. What do you think of the current version of generating? @JacquesCarette

**Comment by JacquesCarette** [comment]
See my comments in that check-in.

We should not be comparing Strings at all for this. It should all be based on `UID`s for the comparisons and linking, and on `Label` (especially `shortname` and the like) for making up what gets printed.

**Comment by halonazhao** [comment]
Ok. Can you take a look at the new check-ins on `TraceTable` branch? I changed to use labels and the `RefbyMap` directly. The downside is that if directly do this from `RefbyMap`, the matrix will only show that the chunks which have referencing relations.

**Comment by JacquesCarette** [comment]
I looked at the code, but I didn't see that higher-level downside. Can you point me to something specific?

**Comment by halonazhao** [comment]
Say if DD1 has neither been referenced or referencing others, DD1 will not be showing in the matrix.

**Comment by halonazhao** [comment]
Does the `it is used` mean that DD1 exists in the document but not considering referenced or referencing? If that is the case, I didn't do anything to check whether an instance of any chunk exists.
What I did for the traceability matrix is just fill the contents in `RefByTable` into the final traceability table. And the `RefByTable` is a map only recording the instances who are in a `RefBy`, no matter it is referenced or referencing others. So if an instance of the chunk is neither referenced or referencing others, it will not exist in both `RefbyTable`  and the final 'Traceability Matrix'.

In case we have misunderstanding here, I will put a result here:
![screen shot 2018-10-16 at 15 05 25](https://user-images.githubusercontent.com/28347043/47040737-f9034800-d154-11e8-8518-6717d2bcd2e2.png)

Another problem is that if automatically generating the matrix, the `String name` like `DD1 , DD2..` will not be appended to the actual reference chunk. Is that ok?

**Comment by smiths** [comment]
There might be a subtle edge case I'm not thinking of, but my first thought is that if DD1 is not used, then there is a mistake in the documentation.  If it isn't used, then it shouldn't show up in the traceability matrix, but we should somehow be given a warning that it isn't used.  This would give the author a chance to improve their documentation.  

This is one of the reasons why I am so excited about the traceability matrix.  Previously we have relied on the author to document the relations, but they had no way of checking for completeness.  With the traceability matrix they will have an automatic check.  😄

**Comment by halonazhao** [comment]
Just want to clarify another problem that keep all reference dependencies in one matrix is ok? Or like case study [SWHS case](https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf), there are three smaller tables indicating the problem. These are two choices and I think by determine label's type, different tables can be generated easily. But the problem is still that we may want to have a standard rule for all case studies. @smiths

**Comment by smiths** [comment]
One big matrix is fine for now.  It will be difficult to practically display, but that is a problem we can deal with later.  Generating the complete view of the information is the first step.  Displaying that information so that it fits legibly on an 8.5 x 11 page is likely to remain outside of the scope of your project.

**Comment by halonazhao** [comment]
I guess the problem about determing whether a chunk like `DD1` being used or not is actually a problem not only related to the `TraceyMatrix`. 

Since when it goes to collect the references, it actually went through the DDs, IMs and so on who for sure exist in the document. So the index of the `TraceMap :: uid [Label]` do not have to be queried whether it is not used. 

But the problem might occure at the list of `labels` in the `TraceMap`. Say a `DD1` has a `label(DD1L)` defined, but DD1 is not actually used in this document. In this situation, if there is another chunk directly using `makeRefFromLabel` to reference the `label(DD1L)` of DD1. The `ref link` will still show in doc withou causing any error, but it is not a valid link because it doesn't trace back to the actual DD1 because DD1 is not used.

So overall they problem is that we need a technique to give errors or warnings when a `Label` of a `Chunk` is to be made the reference, the `chunk` of this `Label` should be guranteed used in the document. Did I understand this right?

**Comment by smiths** [comment]
@halonazhao, I'm not sure we are discussing the same thing.  What I am suggesting is that in a correct document, DD1 should be used by something, or DD1 shouldn't be in the document.  (I don't think that constraint is met by our current case studies.)  Every DD would have a label and there would be at least one occurrence of another chunk referencing this label.

I'm not sure how we have a situation where there is a label for DD1, but DD1 is not in the document.  Is that possible?

**Comment by JacquesCarette** [comment]
I agree, I think we are not all discussing the same thing. Or at least, we are not quite understanding each other on all points. I am convinced that there is an issue here, but I am currently lost as to what it actually is!

**Comment by halonazhao** [comment]
Dr. @smiths 
Can I give your question another try? Do you mean that my technique is designed to check whether the manual one is correct? But what I did is to automatically generate that matrix instead of checking a generated matrix. I think once `drasil` is run, if the technique to generate that matrix is correct, then the matrix must be right. We can not have two solid facts. We can do either go through document(which is the solid fact) and generate the matrix or read a manual matrix(a solid fact) to check whether the document contains all the reference relations. Do you mean this?

I was talking the orphan Label in `Drasil`. So we were not talking the same thing for sure : )

**Comment by halonazhao** [comment]
@JacquesCarette Can you confirm the design of making references? Since I changed the structure in my branch and you improved them in master, they made a big difference, now I feel it's too hard to merge master into. So can you confirm how exactly we should do about here? You merged `mkFrmLabel` and `makeRef` to `makeRefS` which may only make sense based on `master` version.
Since mine design extended the `Ref` with `UID` and this `UID` I regulated it to be `Label's` UID.`HasUID` this constraint prevents to combine two functions. 
https://github.com/JacquesCarette/Drasil/blob/81a88e1165722ed8b8318ab63c89d7407f5c6037/code/drasil-lang/Language/Drasil/Reference.hs#L326-L349

**Comment by JacquesCarette** [comment]
I will comment on this, soon. Very useful summary.  Luckily you can proceed with your plan (as per other issue) without waiting for a full resolution on this.

**Comment by JacquesCarette** [comment]
[Not sure why they are not rendered either].  In any case, what we really want is to remove the *ref functions to no longer have those hard-coded letters. What to 'print' there should be obtained via some kind of program (embedded as a data-structure) that is interpreted at printing-time.  And the prefix letter (if that's the format we want) should be obtained from the 'concept domain' of the thing we are referring to.

In other words, when a `Ref` is being created by a call to some "make-a-reference" function on a **chunk**, it should embed a "printing command sequence" with the right information. That information is available from the chunk (or ought to be). That way the printer will not need to know about various concepts (i.e. what `RefType` is currently for).  So that we can, in time, delete `RefType` entirely.

I think that dealing with ALUR is the most complex part of getting this done.

However, to migrate to this new mechanism, I am fairly sure we'll need to first add a `RefNew` constructor to `Sentence` with the alternate information. Then we can add new make-reference combinators that generate `RefNew` instead. Then we can replace every use of (say) `Req` when making a `Label` with `Dummy`, so that we can plainly see when `Req` is no longer used at all. [It still is!  This is why it has not been deleted, it would break things if I did].  Eventually, we should be able to remove `RefType` from `Label` entirely, once every constructor uses `Dummy`.

**Comment by halonazhao** [comment]
Ok. Should the first thing be adding the ConceptDomains to those referable chunks, which indicates the `RefType`? Because currently, some referable chunks do not implement `concept domain` class yet, like DataDefinition and so on.
In term of this process, should we have more `common concepts` for these chunks? And this may need the support from #1042 too. @JacquesCarette

**Comment by JacquesCarette** [comment]
First question: yes. (And we'll need to fix `DataDefinition` if that's the case)

Second question: I think so. But I think we need to decide this on a case-by-case basis. We should only add what we need.

**Comment by halonazhao** [comment]
This issue can be closed now. Problem solved in https://github.com/JacquesCarette/Drasil/pull/1072.
