### ISSUE TITLE
[Design] DocLang Construction Consistency

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1023]
Background
==========
As it exists currently, drasil-docLang implements "lists of chunks" in several different ways.

The three ways in which chunks are "added" to the docLang are as follows:
1. Implicitly
	This is used to describe assumptions in the docLang. Take its encoding in GlassBR:
	```haskell
	Assumptions,
	```
2. (For Tables, Configurable) List of Chunks
	This is used for most subsections of `SCSProg`:  `TMs`, `GDs`, and `IMs`. The data is a list of chunks. In GlassBR:
	```haskell
	IMs ... [probOfBreak, calofCapacity, calofDemand] ...,
	```
3. List of `Contents`
	This is used for `FReqsSub`, `LCsProg`, and `UCsProg`. An example in GlassBR:
	```haskell
	FReqsSub funcReqsList,
	```

Problem
=======
Encoding chunks into the docLang take form in different ways. Encodings derived from `ConceptInstance` may be encoded as either 1 (assumptions) or 3 (LUR) currently. Moreover, methods 2 and 3 are syntactically close but require different types.

Proposed Solution
=================
Due to `ConceptInstance`s being "tagged" with a domain, 1 does not make sense as it is not flexible in its current state. Ideally a solution for docLang constructs which rely on `ConceptInstance`s is to take an argument specifying the domain to "pull from" and possibly a function which will transform `ConceptInstance` to `[Contents]`. A (GADT) signature such as:
```haskell
SomeNewConstructor :: ConceptChunk -> ([ConceptInstance] -> [Contents]) -> SCS...
```
The evaluation of this constructor would take the `ConceptChunk`, or perhaps more generally `Concept`, retrieve all chunks from a DB (either `ChunkDB` or `ReferenceDB`) and pass them to the function to create the body of the section. As far as I understand, all chunks of a given domain, say requirements (assuming no separate section for FR/NFR), should exist in a database and it would always be the case where all of these in a given domain should be used in a section. Phrased another way: there should be no case where a `ConceptInstance` of the requirements domain would *need* exist in a database and not be included in the requirements section? @JacquesCarette @smiths

An example of this used in GlassBR could be:
```haskell
FReqsSub funcReqDom mkEnumSimpleD
```
versus the existing
```haskell
FReqsSub funcReqsList
```

The advantages over the existing implementation:
1. Consistency: The docLang receives the contents of all chunks which belong to the (say, `funcReq`) domain. It also brings `ConceptInstance` section constructors into alignment with the constructors in `SCSProg` which tend to specify the chunks rather than `[Contents]`.
2. More Abstract: By giving the docLang the "original" chunks and not just `Contents` the docLang is able to do *more* with the information. It preserves more information longer.
3. Customization: By providing a function to docLang to "serialize" the chunks to `Contents`, it allows customization over the existing `Assumptions` constructor (1 in Background).
4. Flexibility: By providing a serialization function rather than several built-ins allows for more flexibility in cases where a one-off odd representation may be needed while providing a basic useful function `mkEnumSimpleD` and its building blocks to lower the barrier to further customization and providing less work for the (current) "common case".

Alternatives
============
1. Move to simple constructors similar to how `Assumptions` works currently.
	The disadvantage of this is `ConceptInstance` domains would need to be "baked" in at the docLang level.
2. Use `[Contents]` as LUR currently do. 
	The disadvantage of this is information is lost earlier in the transformation process which may be useful.
3. Specify an arbitrary list of `ConceptInstance`.
	In its current state, this has the disadvantage of requiring the chunks to be added to a database and the constructor. While this can easily be consistent through assigning the same list to both, it still has the option of _not_ being consistent and is really "duplicating" the data.

**Comment by smiths** [comment]
@Mornix, I'm not sure I understand your question: 

"[T]here should be no case where a ConceptInstance of the requirements domain would need exist in a database and not be included in the requirements section? "

If I understand correctly, it seems to me there would be times when a ConceptInstance would exist, but not be included in the requirements section.  We are aiming for reuse, so ConceptInstances can be used across projects.  Maybe it is the database part I'm missing.  If each project has a separate database, then I could see your statement being true.  If the database is shared between projects, I don't think it is true.  

I don't understand the intricacies of the coding, so I very well could be missing the point.  😄

**Comment by Mornix** [comment]
My apologizes, 

"Maybe it is the database part I'm missing. If each project has a separate database, then I could see your statement being true" is more what I was getting at.

In terms of the relation of NoPCM and SWHS, NoPCM uses `ConceptInstance`s such as those making up the likely and unlikely change from SWHS. Which is expected because as you said: reuse.

Each example currently has an individual `ChunkDB` and `ReferenceDB`, which are the database(s) I was referring to (and probably not super clear about). Is it the case that each example will have its own `ChunkDB` and `ReferenceDB` or is that something else which could be reused?

**Comment by smiths** [comment]
@Mornix, what is in each examples ChunkDB and ReferenceDB?  My first thought is that everything is up for potential reuse.  Even if we aren't reusing things between our case studies, we could probably imagine reusing most things, especially when we think about each example as a family of related examples.

**Comment by Mornix** [comment]
Closing. Work completed with merge of #1668.
