### ISSUE TITLE
A Decision is Needed to build Reference Relation Map

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#1056]
As we need enough information to be stored in `Reference Relation Map`, I have two proposals of designing the Map.

The first would be:
Building an automatically generated all references referring table. When we go through the whole document structure which is `DocDesc` here. No matter we are going to use this chunk as a reference or not, we generate a reference for it and store all the references in the 'Reference Relation Map'. So in this case, I would design the TraceMap and RefbyMap as following:
*********************************************************************************
RefRelaMap = map [UID] [reference] --- this is an every reference table
TraceMap = map [UID] [UID] -- this would be the collection of a chunk references a list of references
RefbyMap = map [UID] [UID] -- the invert map version of TraceMap
Every UID in `TraceMap` and `RefbyMap` can be referred in `RefRelaMap` to have a real `reference` type.
**********************************OR**********************************
RefRelaMap = map [ShortName] [reference]
TraceMap = map [ShortName] [ShortName] 
RefbyMap = map [ShortName] [ShortName]
In this case, I think the UID in Reference is no longer needed.

I have an impression that I proposed this design when we tried to get rid of the cyclic importing issue. But I don't remember why we said this is not good design.

*********************************************************************************
The second would be:
eveythingMap = map [UID] [Chunks] --- this table would record all the chunks
TraceMap = map [UID] [UID] ----- This collection would be straightforward since the UID help use get back to Chunk and we can make reference whenever we need
RefbyMap = map [UID] [UID]

So overall, we need a complete references map or a complete map, otherwise, seems that we cannot have enough information for forwards and backward reference.

Thanks for the help @JacquesCarette

**Comment by JacquesCarette** [comment]
I don't know what problem you're trying to fix, so I cannot evaluate your design!

Two things:
1. I do think these maps should go from `UID` (and not`[UID]` or `[ShortName]`) to 'something'
2. It is usually not a good idea to go to `Chunk` (or `[Chunk]`) as that doesn't give enough information, i.e. we don't know the type of the result.

Please document the exact problem you are trying to sovle.

**Comment by halonazhao** [comment]
When I tried to store say some references(Ref1, Ref2, Ref3) for `DD1`, those references were either collected by their Chunks' `UID`s or collected as the whole `Reference2` type which means having refAdd, ShortName, RefProg. 

So the `traceMap = map [DD1's uid] [UIDs of the Chunks to References]`
or `traceMap = map [DD1's uid] [References at Ref2 type]`

After inverting `traceMap` to `refByMap`, it will be a `map [Reference] [UID]`. The second parameter `UID` here cannot be made to a `Reference` since `UID` is not enough to build the reference.
So the design I proposed before is to build a DB, we can use `UID` to get enough information to actually build a reference. Is this clear enough now? @JacquesCarette

**Comment by halonazhao** [comment]
So far, Assumptions, DDs, IMs, TMs and GDs were added into the DB. But for Requirements and likely changes, the first thing about them is that they are all at `ConceptInstance` type, so they have to be put into the same map right? We don't manually classify them to different maps I guess. 

The second thing is that based on the current `DocumentLanguage`, https://github.com/JacquesCarette/Drasil/blob/4ba6cf5938d56f14831de22adf824e11bd29d628/code/drasil-docLang/Drasil/DocumentLanguage.hs#L196-L208.
So they were broken to be used instead of being a whole `conceptInstance` piece to be used. So auto collecting of the chunks' themselves is currently impossible. So is that ok I manually put `constanceInstance` into DB and then do the references related? @JacquesCarette 
Thanks.

**Comment by JacquesCarette** [comment]
Correct, they have to be put into the same map. Then we can filter it (by domain).

I don't quite understand the second thing.  At the `DocumentLanguage` level, it isn't quite so bad if the knowledge about functional/non-functional requirements is know (at least for now).  So I am not quite sure what is broken?

**Comment by halonazhao** [comment]
As you can see from the code I posted before, `ConceptInstance` is wrapped to `Contents` to be used. So we won't collect all `conceptInstance` by traversing the `DocDesc`. The broken means the `conceptInstance` 's information is used by (^. definition) and other small piece of information from it.

**Comment by JacquesCarette** [comment]
Wrapped to `Contents, or 'rendered' to `Contents`? If the latter, then yes, that's a problem, as it means that too much information has been deleted, even in the `DocDesc`.  So yes, I see that for `FReqsSub`, it looks like things are prematurely rendered. So yes, that should be changed.

**Comment by halonazhao** [comment]
So make them to directly take '[ConceptInstance]' and try to render the '[conceptInstance]' right on the way to make Document right? I will try to do some changes and if there is anything going wrong please correct me. @JacquesCarette

**Comment by halonazhao** [comment]
I made an experiment on `LikelyChange` section at https://github.com/JacquesCarette/Drasil/commit/da1ba0630844ea7ef73b6e5f2937027e4fc3d5a8. Is this what we want? If it has the basic idea, then the problem would only show up at GlassBR's `requirement` section. 
https://github.com/JacquesCarette/Drasil/blob/7f54389872973a354eaeff45cf3fd609f0572e15/code/drasil-example/Drasil/GlassBR/Requirements.hs#L37-L61
This problem here is that the sentence in `ConceptInstance` doesn't have the full description, instead, the sentence got more decoration when it is wrapped/rendered(?) to `content` to be used.

All those extra decorations are for the listing things in one single item.
![screen shot 2018-12-03 at 18 38 37](https://user-images.githubusercontent.com/28347043/49408558-c7f1cd80-f72a-11e8-86ff-431766d0a6ba.png)


So as long as we can make sure all sentences for `requirements` and `changes` are wrapped into `ConceptInstance`, then the experimental changes would work.

**Comment by JacquesCarette** [comment]
So I think you later found the problem with this and fixed it?  Otherwise it does seem like this is the right way to go.

**Comment by balacij** [comment]
Ok, so, there are 3 maps built out in this ticket:
* a "what UIDs does this UID refer/'rely' on?" map (e.g., TraceMap)
* a "what UIDs rely on this UID?" map (e.g., RefByMap)
* a "give me the reference chunk for this UID" map (e.g., RefRelaMap)

With #2873 's prototype, I removed `TraceMap` entirely and made it a property for each valid "chunk type" that it should expose what UIDs it refers/relies on. Thus, we look to a specific chunks references to see what it refers to. It's an identical featureset.

Additionally, I re-built the `RefByMap` as well, similarly (e.g., `Map UID [UID]`, unfortunately this one still seems like it's a "generic operation" that needs everything to be untyped).

Finally, the third one is (and should be) external to Drasils ChunkDB, `Reference` is heavily tied to documents, so it is a chunk type. In other words, it's covered by the same prototype. However, `Reference`s would need to have a different UID from the actual chunk they refer to (but, you can always create another reference from the referred thing on-the-fly as needed).

Hence, I think we can close this ticket in favour of #2873 ?

**Comment by JacquesCarette** [comment]
Yes, I think this can be closed in favour of that one.
