### ISSUE TITLE
Implement in Drasil the Changes to the Manual Case Studies Necessary to Break the Cyclic Import Problems

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1057]
@halonazhao, as discussed in today's (Nov 23rd) meeting, please implement the parts of the manual case studies into Drasil that are necessary to break the cyclic import problems.  You summarized the import problems are summarized in #1029.  I believe that the updates to the manual case studies have now removed the problems, but those changes need to be propagated to Drasil.  We estimated today that there will be about 10 instances where you need to make changes.  The manual versions for the case studies have other changes, but you do not need to worry about those.

The required changes are in the manual case study branches that we discussed.  If you have any questions, please assign @smiths an issue.

@vajihehm, I know you were planning on making these changes, but the requested modifications are on the critical path for @halonazhao work.  We don't want to put you in this position.  You can proceed with making your own  updates to the GlassBR SRS.  This can be done in parallel (in your own branch) with the Yuzhi's work.

**Comment by vajihehm** [comment]
@smith Ok, thank you Dr.Smith. I will make changes on my own branch.

**Comment by JacquesCarette** [comment]
@smiths The structural parts of this are all done. We're no longer updating the manual case studies. But the last comment makes me worry that there might still be some missing data in Drasil?

**Comment by smiths** [comment]
@JacquesCarette, I think we are fine to close this issue.  The GlassBR example is functioning well.  I'm not aware of any outstanding problems.
