### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Table of Units

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1058]
Issue #523 has far too much going on to keep track of all of the details.  This issue (and several others) highlights one specific difference between Stable and Manual.

- SWHS
    - Table of Units
        - Different order of displayed symbols (Trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41620738-a2d56f14-73d8-11e8-846f-26233a33ed88.png)
Manual:
![image](https://user-images.githubusercontent.com/35268928/41620782-bfd208a2-73d8-11e8-86bd-01ea3850af40.png)

**Comment by smiths** [comment]
The table of units are still displayed in a different orders in the two documents, but this is not considered to be  a problem.  The order in the generated code (stable) is actually better because the entries are sorted.  (I believe they are sorted alphabetically.)  The manual version could be changed to match stable, but there isn't really any overwhelming reason to take the time to make this change.

Since there is nothing to do as a consequence of this, I'll close the issue.

**Comment by JacquesCarette** [comment]
Right - Stable is sorted alphabetically by 'symbol'.

**Comment by smiths** [comment]
Great!  Stable is better than the manual version.  This is a simple, but very real, advantage of the generative approach.  Nobody is going to want to manually sort (and maintain the sort for) a table of units or symbols or whatever.
