### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: R (Aspect Ratio)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1061]
Issue #523 has far too much going on to keep track of all of the details. This issue (and several others) highlights one specific difference between Stable and Manual.

In the manual version for Drasil we use the aspect ratio R, but it is missing from the stable (Drasil) version.

Manual:
![image](https://user-images.githubusercontent.com/35268928/41620979-5a9e9c10-73d9-11e8-810b-ebca7cbac6de.png)

The aspect ratio (R) was discussed in smiths/caseStudies#26. Changes were made to the manual version, but not propagated to Drasil. The LaTex for adding R was given in commit smiths/swhs@f68dc8e.  @vajihehm, Drasil needs to be modified to reflect these changes.

This requested change is related to updating the Drasil version of the SRS, so it can count as part of the make-up assignment for the MIS assignment in CAS 741.

**Comment by smiths** [comment]
@samm82, can you also have a look at this issue.  We realized that we needed to add aspect ratio in a discussion given at:

https://github.com/smiths/caseStudies/issues/26

You might need to add a data definition for R (aspect ratio).

**Comment by samm82** [comment]
I'm going to track all questions here instead of https://github.com/smiths/caseStudies/issues/26.

@smiths
1) What are the values of _R<sub>max</sub>_ and _R<sub>min</sub>_?
2) Should the manual be updated for the new data definition or are we not maintaining it anymore? (I know we're not maintaining the caseStudies repo, but I'm not sure about swhs.)

**Comment by samm82** [comment]
3) Should I call it AR for consistency with GlassBR (and so R isn't used for Requirements and Aspect Ratio), and if so, (related to (2)) above, should I update manual as well? @smiths

**Comment by smiths** [comment]
@samm82, we shouldn't have to worry about consistency of symbols between examples.  This is too high a bar.  There will be more concepts than symbols.  Having said that, you can make this change.  Since we are able to have consistency in this case, we might as well.  😄 

With respect to minimum and maximum aspect ratios, I suggest 0.01 to 100.  I don't have any special reason for those numbers, other than my common sense understanding that a very tall and narrow tank, or a short and wide tank, wouldn't not easily fit beside someone's home.

**Comment by samm82** [comment]
Should I update the manual SWHS repo?

**Comment by smiths** [comment]
No, you don't need to update the manual SWHS.  We should focus our efforts on the Drasil version now.

**Comment by samm82** [comment]
Should the constraint be captured in the Input Data Constraints, or in a note of the DD? I don't think the Input Data Constraints makes sense, since it isn't an input, but if the constraint is captured in the DD, the DD itself is never used, which makes me wonder how necessary it is. @smiths

**Comment by smiths** [comment]
The concept of aspect ratio was added so that the relationship between L and D could be constrained.  It is associated with the input constraint on L and D.   As mentioned above, you should have a look at https://github.com/smiths/caseStudies/issues/26.  The values of Rmin and Rmax do not come through on the input R (which as you said, isn't an input); they come through on the constraints for L and D.  The easiest thing to do might be to have one of L or D specified and the ratio used a constraint for the other.
