### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Blurb introducing IMs

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1062]
Issue #523 has far too much going on to keep track of all of the details. This issue (and several others) highlights one specific difference between Stable and Manual.
- IMs
        - Missing information paragraph (non-trivial)
Stable:
Manual:
![image](https://user-images.githubusercontent.com/35268928/41621082-a8619844-73d9-11e8-8cfe-1696849fbc24.png)

The above paragraph of information is not in the stable (Drasil).  In the manual version it appears as text as the final paragraph of the introductory blurb for the Instance Models section.

**Comment by smiths** [comment]
@samm82, it looks like the text has been updated.  Can you please verify and then we can close this issue.

**Comment by samm82** [comment]
Can confirm this change has been made.

**Comment by smiths** [comment]
Great!
