### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Missing Information in IM1

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1064]
Issue #523 has far too much going on to keep track of all of the details. This issue (and several others) highlights one specific difference between Stable and Manual.

**1.** Assumptions associated with the input and output of IM1
Stable:
![image](https://user-images.githubusercontent.com/35268928/41621222-17f4069c-73da-11e8-9f96-550cf8c47143.png)
Manual:
![image](https://user-images.githubusercontent.com/35268928/41621276-2ef96f3a-73da-11e8-9984-597c54618e80.png)

**2.** Description is missing associated assumptions and constraints 
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41621363-68dda45a-73da-11e8-8d63-930a8c5fa166.png)
Manual:
![image](https://user-images.githubusercontent.com/35268928/41621395-81b16c8c-73da-11e8-9b2e-0ffbf8c81fa9.png)

**Comment by smiths** [comment]
Since the time when #523 was created some progress has been made.  A notes field has been added to the chunks to capture the missing information.
<img width="1145" alt="notesim1" src="https://user-images.githubusercontent.com/1422000/49107733-80fc6780-f254-11e8-8fa1-2ab7235193a5.png">
This is an improvement, but unfortunately the note doesn't capture the information entirely correctly.  Some fields have also been added, like input constraints and output constraints, that capture some of the information.  However, when there is an explanation or reference to another chunk, this information has to be included in the notes field.

The note should contain the following bulleted list (ideally displayed as a bulleted list for ease of reading/verifying):
- T_P is defined by (IM: eBalanceOnPCM).
- The input constraint Tinit ≤ T_C comes from (A: Charging-Tank-No-Temp-Discharge).
- tau_W is calculated from DD3 (DD3 is the number in the manual version, the reference is currently wrong in the stable version).
- eta is a calculated from DD4 (DD4 is the number in the manual version, the reference is currently missing in the stable version).
- the initial conditions for the ODE Equation are T_w(0) = T_p(0) = T_init, following A12 (this number comes from the original manual documentation.  The new name for the assumption will have to be looked up)
- The ODE Equation applies as long as the water is in liquid form, 0 < T_W < 100 (°C) where 0 (°C) and 100 (°C) are the melting and boiling point temperatures of water, respectively (A: Water-Always-Liquid, A: Atmospheric-Pressure-Tank).

**Comment by smiths** [comment]
@vajihehm, for you to close this issue, you will need to update the Notes field in Drasil to follow the bullet list given above.  We'll include this issue as part of your replacement for the MIS assignment.

**Comment by samm82** [comment]
Right now, the notes field is of type `[Sentence]` but is pretty much always just used as one `Sentence` wrapped in a list. Should this be changed to `Contents` to allow for the bulleted list, or should it be updated (across all examples) to display the list as a bulleted list (which I think is the route to go)? @smiths  @JacquesCarette

**Comment by samm82** [comment]
As in #1484, the DDs for tau_W and eta don't exist in Drasil.

**Comment by samm82** [comment]
Passing in a `[Sentence]` produces a list, but not a bulleted one. Should there be a separate issue to enforce bulleted lists in the Notes section? @smiths

**Comment by JacquesCarette** [comment]
Not sure on `[Sentence]` -> `Contents`, mostly because I'm not sure how semantic `Contents` really is.

We should not 'enforce' bulleted lists, but find a way to say that any given list is ordered or not, which would then render according to some 'style'.

**Comment by samm82** [comment]
I personally think the current output (on the swhsIMs branch) is acceptable, since it captures the meaning and still remains easy to follow.
