### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Missing Information in Derivation

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1066]
Issue #523 has far too much going on to keep track of all of the details. This issue (and several others) highlights one specific difference between Stable and Manual.

- Missing information about associated assumptions and DDs in the derivation (non-trivial)
Stable:
![image](https://user-images.githubusercontent.com/35268928/41621454-b05ccbbc-73da-11e8-9d8d-738f79897db0.png)
Manual:
![image](https://user-images.githubusercontent.com/35268928/41621478-c1dccc84-73da-11e8-86d2-c4407cfcd49c.png)

@vajihehm, please improve the text under "Derivation of the Energy Balance on Water" to match the text in the manual Case Study version:

https://github.com/smiths/caseStudies/blob/glass_revisions/CaseStudies/glass/docs/SRS/glassbr_srs.pdf

As for the other issues, we can consider this part of the make up for the missing MIS assignment.

**Comment by smiths** [comment]
@samm82 can you please fix the Drasil version of SWHS to match the manual version.  I was just looking at SWHS through the new continuous deploy web-page of @Mornix and I noticed that this had never been done.  Very handy to have such a quick and easy way to look at the examples!  As I'm sure everyone knows, I don't like to lose information and we are in danger of losing information as we discontinue maintaining both the manual and the Drasil versions.

I will be assigning several similar issues for updating SWHS.  If you already have enough to do, I'm sure @danscime wouldn't mind some extra work.  :smile:

**Comment by samm82** [comment]
Is it OK if "heating coil" (in Drasil) is written instead of "coil" (as in caseStudies)? @smiths

**Comment by smiths** [comment]
Yes @samm82, writing "heating coil" in place of "coil" would be fine.
