### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Add definitions for tau_w and eta

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1067]
Issue #523 has far too much going on to keep track of all of the details. This issue (and several others) highlights one specific difference between Stable and Manual.

- Glitch (trivial)
Stable: 
![image](https://user-images.githubusercontent.com/35268928/41621555-fb199dec-73da-11e8-83d3-130f0bf1f7c4.png)
Manual:
![image](https://user-images.githubusercontent.com/35268928/41621574-1128ea2a-73db-11e8-904d-956d70d2125f.png)

This glitch is no longer relevant because we have moved the definitions of tau_w and eta to their own data definitions.  However, the stable (Drasil) version does not match the manual version in terms of these data definitions.  @vajihehm, you will need to create these new data definitions in Drasil and reference them in the notes field, as described in #1066.

**Comment by danscime** [comment]
tau_w and eta were said to have been added as Data Definitions, as mentioned in #817.
They do not appear to be on the master version of stable or Drasil.
Do they still need to be added?

**Comment by JacquesCarette** [comment]
As far as I know, yes, they do. Might already be there in a branch - @vajihehm should let us know the state of this.

**Comment by smiths** [comment]
@danscime solved this with #1070.
