### ISSUE TITLE
SWHS: Difference b/w Stable and Manual: Add definitions for tau_P^S and tau_P^L

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1070]
Issue #1069 highlighted that tau_P^S and tau_P^L need to be added as data definitions.  This was done in the manual version at:

https://github.com/smiths/swhs/commit/6bf8ec052868e7a90d803a75b5dfcef1d48c9f3a

These changes need to be propagated to stable (Drasil)

**Comment by danscime** [comment]
Beginning to add these via e6cbbf93146c693ed5246e4b71eee5915db5bb90

**Comment by danscime** [comment]
Added tau_P^S via b6cea7057368d20e2b46420867c86ec2a5a3ffc0

**Comment by danscime** [comment]
Added tau_P^L via df8733d2d4e935f3ba5d87b2226a1593d67ba344.
Original PR #1253.
These data definitions ended up being added in #1257.
I believe this issue can be closed.
