### ISSUE TITLE
SSP Chunk Completion

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#1074]
Currently, SSP case in drasil is at a stage where there are some missing chunks like some instances of DataDefinitons and others compared to Manual version. These chunks needed to be gradually brought back, which means manually created and added. Also, all the chunks currently exist in Drasil do not have any cyclic importing issue and as the manual version was rearranged obeying the hierarchy, even in the future more chunks will be added in, there should not be any cyclic importing issue as well.

Since @bmaclach is working on SSP case, he is going to take over the SSP case completion task.

**Comment by bmaclach** [comment]
All of the chunks from the manual version of SSP have been ported over to Drasil (#1081, #1097, #1098, #1102, #1111) without introducing any cyclic imports, so this issue can be closed.
