### ISSUE TITLE
NoPCM IM reference Inconsistency

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1082]
The functional requirements in the generated SRS for NoPCM contains a reference to IM:eBalanceOnPCM. Checking with the NoPCM SRS in the CaseStudies repo, shows this reference is not there. Is it safe to assume this mention of PCM in NoPCM is a mistake and may be corrected (removed)?

PS. Clicking the reference in the generated document goes nowhere.

Drasil NoPCM:
===
<img width="832" alt="screen shot 2018-12-23 at 2 43 52 am" src="https://user-images.githubusercontent.com/1929800/50381737-96e72780-065c-11e9-8c7d-80d475d91297.png">

CaseStudies NoPCM:
===
<img width="589" alt="screen shot 2018-12-23 at 2 43 17 am" src="https://user-images.githubusercontent.com/1929800/50381736-83d45780-065c-11e9-9b45-fa99e7f29e60.png">

**Comment by Mornix** [comment]
Piggybacking on this issue for a followup:

One of the instance models (IM:heatEInWtr) refers to a theory model (TM:sensHtE) which is another dead link. This appears to be a missing theory model (or at the very least an issue), rather than an inconsistency between CaseStudies and Drasil as the CaseStudies has a missing reference there as well. I've attached screenshots of the relevant portion of the document.

Drasil NoPCM:
===
<img width="850" alt="screen shot 2018-12-23 at 3 00 49 am" src="https://user-images.githubusercontent.com/1929800/50381839-f5150a00-065e-11e9-8d21-e68876e48363.png">

CaseStudies NoPCM:
===
<img width="767" alt="screen shot 2018-12-23 at 3 01 55 am" src="https://user-images.githubusercontent.com/1929800/50381843-1d046d80-065f-11e9-8327-673d23a5982c.png">

**Comment by Mornix** [comment]
Piggybacking on this issue (again) for some more inconsistencies/"translation" errors in NoPCM.

These four inconsistencies all relate to assumptions within NoPCM relating to two specific chunks referencing assumptions which aren't existent.

# GD2
## Relevant Assumptions
### CaseStudies
<img width="759" alt="screen shot 2019-01-11 at 2 17 26 pm" src="https://user-images.githubusercontent.com/1929800/51055789-f460fb00-15ae-11e9-9014-7e94f443e314.png">

### Drasil
<img width="1071" alt="screen shot 2019-01-11 at 2 17 40 pm" src="https://user-images.githubusercontent.com/1929800/51055808-0478da80-15af-11e9-8aa6-b9665ac92643.png">

## Problem
The derivation of GD2 in the Drasil version refers to two assumptions which are not present in NoPCM. This appears to be a typo/translation error as both A4 and A5 (the last two assumptions in the screenshots posted). Not to mention the Drasil references refer to PCM.

### CaseStudies
<img width="781" alt="screen shot 2019-01-11 at 2 17 58 pm" src="https://user-images.githubusercontent.com/1929800/51056197-30489000-15b0-11e9-978a-4e4a01c25b21.png">

### Drasil
<img width="1144" alt="screen shot 2019-01-11 at 2 18 13 pm" src="https://user-images.githubusercontent.com/1929800/51056209-40606f80-15b0-11e9-9065-37c6446fea64.png">

# IM1
It appears the Drasil version of NoPCM makes reference to a non-existent assumption ( Law-Convective-Cooling-Water-PCM). This one I wasn't able to completely match up with CaseStudies as it looks like there has been a partial divergence, at least in organization of the information. I've included (what I believe) are the relevant parts of IM1 below.

### CaseStudies
<img width="768" alt="screen shot 2019-01-11 at 3 41 05 pm" src="https://user-images.githubusercontent.com/1929800/51059008-b9fc5b80-15b8-11e9-82e7-bafbc8a7eec7.png">

### Drasil
<img width="1143" alt="screen shot 2019-01-11 at 3 51 47 pm" src="https://user-images.githubusercontent.com/1929800/51059046-d7c9c080-15b8-11e9-97f4-e07cf55fcf9c.png">

**Comment by smiths** [comment]
The original issue with IM: eBalanceOnPCM is definitely a bug.  It should be removed from the noPCM example.

I'll have a look at the piggybacked issues soon.  (By the way, I prefer separate issues.   I think I would have closed the original issue sooner if there was only the one issue to read about.  The piggyback issues could have been written as separate issues with a link to the original issue if necessary.)

**Comment by smiths** [comment]
@Mornix, I looked into the missing theoretical model (sensible heat energy).  It definitely is a mistake that this was deleted when transitioning from SWHS to noPCM.  I have added this theoretical model back in:

https://github.com/smiths/caseStudies/commit/a63f3f38cf9947f0b27939001c9cdd1bd076dcf7

The diff should show you what needs to be changed in the Drasil version.  Can you please make the updates?

Something interesting, which we should discuss with @JacquesCarette, I had to modify (simplify) the theoretical model for sensible heating because there is no phase change in noPCM.  Some day it would be nice to automatically modify the sensible heating model if there is an assumption that there will be no phase changes.

**Comment by smiths** [comment]
For the problem with the assumptions in GD2 being incorrect, you are right.  The derivation should reference Density-Water-Constant-over-Volume and Specific-Heat-Energy-Constant-over-Volume.  I think this will fix the problem with the assumptions not tracing to "GD2."

**Comment by smiths** [comment]
For the Drasil version of IM1 the only assumption that should be invoked in the Notes field is Water-Always-Liquid.

**Comment by smiths** [comment]
@Mornix, because all of these issues were combined, I'm not 100% certain that I addressed all of your questions.  If there is something missing, can you please create a new issue with your question/concern.

Thank you for your careful consideration of the example.  @JacquesCarette, this is another datapoint that shows that as we improve our automation we catch more errors/omissions.  😄

**Comment by JacquesCarette** [comment]
Regarding simplifying theoretical models: yes, this is definitely where Drasil should start interacting with MathScheme. Definitely the right long-term path.

@Mornix I definitely agree with @smiths that all of these should have been done as separate issues.
