### ISSUE TITLE
bug of building specific examples (gamephys_diff) in Drasil

### ISSUE THREAD

**Issue by vajihehm** [JacquesCarette/Drasil#1088]
@JacquesCarette I executed the examples separately, so when I execute the 'make gamephys_diff ' it generate artifacts for other examples as well. However,  building of other examples works fine. Is that a bug ?

**Comment by JacquesCarette** [comment]
That appears to be a weakness in the Makefile. There must be something wrong in the dependencies.

**Comment by vajihehm** [comment]
Thanks. I will glance the Makefile or other related files to solve the bug.

**Comment by Mornix** [comment]
Closing. The merge of #1109 fixes this.
