### ISSUE TITLE
Write access required?

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1093]
@JacquesCarette, trying to push a remote branch, I get this error, don't think I have write access.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/43192745/51524192-819c1f00-1dfb-11e9-8a07-f7b800f48a21.png">

**Comment by smiths** [comment]
Hello @oluowoj.  The Drasil repo is set up differently than the Case Study repo.  You are correct that you do not have write access.  You should instead create a pull request.

**Comment by oluowoj** [comment]
@smith,  I will need to do a git push of my new branch with the changes before I create a pull request, right?  The new branch is currently not on Drasil.

**Comment by smiths** [comment]
No, you don't need write access to the repo to create a pull request.  I don't know the specifics, of how to do it, but I know it is often done this way.

**Comment by oluowoj** [comment]
Thanks accepted
