### ISSUE TITLE
HLint for Builds

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1117]
So I ran `hlint` over master. (On macOS `hlint` is available through Homebrew)

Here is the output of the "types of errors" gathered with: `hlint . | grep \\./ | cut -d : -f 4,5 | sort | uniq`:

```
 Error: Parse error
 Suggestion: Avoid lambda
 Suggestion: Avoid lambda using `infix`
 Suggestion: Fuse concatMap/map
 Suggestion: Fuse foldr/map
 Suggestion: Move brackets to avoid $
 Suggestion: Reduce duplication
 Suggestion: Redundant $
 Suggestion: Redundant bracket
 Suggestion: Use 
 Suggestion: Use <$>
 Suggestion: Use String
 Suggestion: Use camelCase
 Suggestion: Use const
 Suggestion: Use foldr
 Suggestion: Use fromMaybe
 Suggestion: Use guards
 Suggestion: Use infix
 Suggestion: Use intercalate
 Suggestion: Use lambda-case
 Suggestion: Use list comprehension
 Suggestion: Use list literal
 Suggestion: Use list literal pattern
 Suggestion: Use map once
 Suggestion: Use newtype instead of data
 Suggestion: Use null
 Suggestion: Use record patterns
 Suggestion: Use section
 Suggestion: Use uncurry
 Warning: Avoid lambda
 Warning: Eta reduce
 Warning: Evaluate
 Warning: Redundant bracket
 Warning: Redundant do
 Warning: Redundant fromInteger
 Warning: Redundant lambda
 Warning: Redundant return
 Warning: Unused LANGUAGE pragma
 Warning: Use all
 Warning: Use and
 Warning: Use any
 Warning: Use catMaybes
 Warning: Use concat
 Warning: Use concatMap
 Warning: Use fewer imports
 Warning: Use fromMaybe
 Warning: Use fst
 Warning: Use map
 Warning: Use mapM
 Warning: Use notElem
 Warning: Use or
 Warning: Use replicate
 Warning: Use sum
 Warning: Use traverse
```

The parse error mentioned is:
```
./drasil-code/Language/Drasil/CodeSpec.hs:32:31: Error: Parse error
Found:
    data CodeSpec where
  >   CodeSpec :: CommonIdea a => {
      program :: a,
      inputs :: [Input],
```

Which seems like a false positive. (@JacquesCarette?)

I think most of the categories are useful. I think the camelCase one (which is useful for conformity, but probably tedious at the moment.)
I would include the uncut output to hlint (in total it's roughly 23k lines, 3.5k hints) but it exceeds GitHub's character limit (65k).

**Comment by smiths** [comment]
Thank you @Mornix.  Very helpful!  Over time we should go through each of these warnings and suggestions and decide which ones best suit our style.  We'll need to see examples of the "offending" code too.  I haven't written enough Haskell code to have  strong opinion, but I'm sure @JacquesCarette will know his preference.  😄 I know with flake8 one can write a configuration file that explicitly modifies the checks to the local style preference.  If we can do something like that with HLint, we could configure it to only report the warnings that we are actually concerned about.

Maybe during our next "all hands" meeting we can look at a few examples and decide some style preferences.  We could add this information to the Contributor's Guide and start asking developers to style check before pushing to the repo.  The next step would be to automate running HLint with our continuous integration.

**Comment by Mornix** [comment]
HLint allows us to generate a configuration that ignores current warnings/hints which could be a good opportunity to integrate it into Travis and prevent new lint “issues” from being introduced. We could add an item to the miscellaneous tasks .txt to “Remove a suppressed lint warning and fix all the instances pointed to by HLint” as a way to fix-up existing suggestions.

**Comment by smiths** [comment]
Thanks for the information @Mornix.  Glad to hear that HLint allows a configuration file.  I like your idea because it would allow us to gradually address the backlog of issues, while still improving the style of code going forward.

**Comment by JacquesCarette** [comment]
I think I'd like to see, for each class of warning/suggestion, how many occurrences there are.  For those with <5 (or even <10), we should probably just fix them. Then we can work on the rest incrementally.

**Comment by Mornix** [comment]
Enumerated with `hlint . | grep \\./ | cut -d : -f 4- | sort | uniq -c`
```
   4  Error: Parse error
  10  Suggestion: Avoid lambda
  10  Suggestion: Avoid lambda using `infix`
   5  Suggestion: Fuse concatMap/map
   8  Suggestion: Fuse foldr/map
 111  Suggestion: Move brackets to avoid $
   1  Suggestion: Reduce duplication
 115  Suggestion: Redundant $
1907  Suggestion: Redundant bracket
  27  Suggestion: Use :
   3  Suggestion: Use <$>
   2  Suggestion: Use String
 462  Suggestion: Use camelCase
  27  Suggestion: Use const
   1  Suggestion: Use foldr
   2  Suggestion: Use fromMaybe
   4  Suggestion: Use guards
   9  Suggestion: Use infix
   2  Suggestion: Use intercalate
   2  Suggestion: Use lambda-case
   6  Suggestion: Use list comprehension
  23  Suggestion: Use list literal
  14  Suggestion: Use list literal pattern
   5  Suggestion: Use map once
  16  Suggestion: Use newtype instead of data
   3  Suggestion: Use null
  33  Suggestion: Use record patterns
  14  Suggestion: Use section
   4  Suggestion: Use uncurry
   4  Warning: Avoid lambda
 138  Warning: Eta reduce
   1  Warning: Evaluate
 225  Warning: Redundant bracket
   1  Warning: Redundant do
   4  Warning: Redundant fromInteger
  14  Warning: Redundant lambda
   1  Warning: Redundant return
   1  Warning: Unused LANGUAGE pragma
   1  Warning: Use all
   1  Warning: Use and
   2  Warning: Use any
   1  Warning: Use catMaybes
   2  Warning: Use concat
   9  Warning: Use concatMap
   5  Warning: Use fewer imports
   5  Warning: Use fromMaybe
   1  Warning: Use fst
   4  Warning: Use map
   6  Warning: Use mapM
   1  Warning: Use notElem
   1  Warning: Use or
   2  Warning: Use replicate
   1  Warning: Use sum
   1  Warning: Use traverse
```

I also looked into the `Parse Error` false positives, and it seems like the parsing library HLint is using has diverged from GHC, however the author of HLint has mentioned plans to switch to using the GHC API for parsing instead.

**Comment by JacquesCarette** [comment]
Great, thanks.  This makes it quite clear that there's a bunch of suggestions/warnings that will be easy to deal with, and some that will be a slow ongoing change.

**Comment by Mornix** [comment]
With the merge of #1147 the remaining suggestions (and their counts) are:
```
   4  Error: Parse error                      (+ 0)
 110  Suggestion: Move brackets to avoid $    (- 1)
 118  Suggestion: Redundant $                 (+ 3)
1890  Suggestion: Redundant bracket           (-17)
 463  Suggestion: Use camelCase               (+ 1)
 140  Warning: Eta reduce                     (+ 2)
 199  Warning: Redundant bracket              (-26)
```

**Comment by JacquesCarette** [comment]
That's great!  You do seem to have dealt with the ones we want to do in one go, and the rest really are something that can be done over time.

**Comment by Mornix** [comment]
Completed (within reason -- see existing suppressions in .hlint.yaml in the code folder) with #1147. Closing.
