### ISSUE TITLE
Case of explicit grouping in SSP

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1120]
In addition to the cases discussed in #457, shown below is another case in SSP where there should be some explicit grouping, but this is currently not possible. The terms at index _i_ should be grouped together, as should the terms at index _i_-1.

https://github.com/JacquesCarette/Drasil/blob/cf88cd145d497a719629922c6790caa4125fa0e7/code/drasil-example/Drasil/SSP/DataDefs.hs#L184-L187

**Comment by JacquesCarette** [comment]
For previous cases like this, what we had done was to de-inline things, and to give a name to `(inxi slopeHght) - (inxi slipHght)` and `(inxiM1 slopeHght) - (inxiM1 slipHght)` which then gives a 'grouping' as a side-effect.  For the previous cases, it made sense. The feature we then wanted was a way to indicate that some of these definitions should be inlined when possible [and that act would likely introduce parentheses]. That part is not implemented.

**Comment by bmaclach** [comment]
I did see those previous cases in SSP. I didn't do them here because each de-inlining results in a new DD and new symbols, and the presence of those DDs and symbols really confused me until I found issue #457 which explains them. Anyway, I think I can do the same thing for this case. In the future when we implement the inlining, I think we would want to make sure that the "intermediate" symbols don't show up as DDs or symbols in the table of symbols.

**Comment by JacquesCarette** [comment]
In theory, we already have partial infrastructure for that -- there is stuff regarding `Scope` of variables for this.  The representation part is done, but it is not used, so there is no solid processing code to go with it.

**Comment by JacquesCarette** [comment]
Let's make a new issue, but refer back to this one for context.

**Comment by bmaclach** [comment]
Issue #1154 created, closing this issue as the new intermediate symbols for this case of explicit grouping have been merged in with PR #1140.
