### ISSUE TITLE
No indentation on span tag

### ISSUE THREAD

**Issue by deviprasad135** [JacquesCarette/Drasil#1121]
Hello  Dr@JacquesCarette ,
I have pushed the changes for fixing indentation in HTML (931e84e).  I have changed  the smaller tgas into one line such as th and header tags. But the div and the span tag in-side the the em tag are not getting indented as they are not recognised by the em tag. They are indenting separately but not along with the em tag. 
![capture](https://user-images.githubusercontent.com/30101689/53113172-f2c01680-350e-11e9-9af0-512ab1a88456.PNG) No indent on span tag

![captureee](https://user-images.githubusercontent.com/30101689/53113475-a923fb80-350f-11e9-874a-29e998dd1859.PNG) Applying indentation on span tag

**Comment by JacquesCarette** [comment]
I have commented on that check-in.  The reason you're having trouble is that you're not using the pretty-printing combinators correctly!  See the comments.  You'll need to redo your design.  Then this bug will become a non-issue.

**Comment by deviprasad135** [comment]
Hello Dr. @JacquesCarette, please review the changes in 1a67f73 whether the indentation is correctly applied on HTML tags.

**Comment by deviprasad135** [comment]
Hello Dr. @JacquesCarette, please review the code in 99e0fdf.

**Comment by deviprasad135** [comment]
Hello Dr. @JacquesCarette, I have fixed the over indent in Tex printer and applied the indentation correctly. Please review the code in 0863b30

**Comment by JacquesCarette** [comment]
99e0fdf reviewed, see comments on that commit.

**Comment by JacquesCarette** [comment]
Sorry, I had the version numbers backwards - but now both have been reviewed and commented on.

Of course, once the fixes are done, I'll need to see the new HTML output, to see if it's good.

Also, with your newfound skills with the pretty-printer, you should also fix some of the over-indenting the TeX printer!

**Comment by deviprasad135** [comment]
I have already fixed the over indentation in TeX printer.

**Comment by JacquesCarette** [comment]
Has the over-indentation in the TeX printer been made into a separate PR that can be merged in sooner rather than later?

**Comment by deviprasad135** [comment]
Yes, it is done on a separate branch and can be merged in sooner.
