### ISSUE TITLE
Every word of an expanded form of an acronym should not always be capitalized

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1125]
Currently when we show an acronym along with its expanded form, as in the Table of Abbreviations and Acronyms or the first time the acronym is used in the text, we capitalize every word in the expanded form. However, if a word is not included in the acronym, it should not be capitalized. For example, SSP is an acronym for "Slope Stability analysis Program" but when we introduce this acronym it gets printed as "Slope Stability Analysis Program (SSP)".

**Comment by bmaclach** [comment]
I just discovered that there are "proper nouns" in Drasil which allow the programmer to define capitalization themselves. Would it be correct to use that in this case?

**Comment by JacquesCarette** [comment]
Yes, you need to use the mechanism in Drasil to define the 'right' kind of capitalization for your phrase.

**Comment by JacquesCarette** [comment]
Close this when you've found something that 'works'.  Note that, in general, you should assign an issue to someone. That person may re-assign it, but at least someone will nominally be in charge.

**Comment by bmaclach** [comment]
Will do, thanks. I ended up using the "proper noun" mechanism I mentioned, which worked and makes sense because SSP is a proper noun. I'll close the issue.
