### ISSUE TITLE
Scope of Project

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1134]
See the discussion in PR #1110 .  The DocLang implements a "Scope of the Project" 'section', but apparently it is not (no longer?) part of our template.  So should it be removed from docLang too?

**Comment by smiths** [comment]
Hello Jacques.  Yes, the Scope of Project should be removed from docLang.  It snuck in when one student in the past added a new section to the standard (manual) SRS template.  I should have caught it sooner, but I didn't.  :-(  
We are reaching a point where the purpose of each SRS section is becoming clear and Scope of Project doesn't add anything.  I believe the rule that we should apply to the sections is that the same information is never repeated in the SRS.  Similar information can be covered, if it is introduced with a different level of abstraction, but literal repetition makes no sense.  The Scope of Project section is the same as the Scope of Requirements section.

**Comment by JacquesCarette** [comment]
So I changed the assignee to @Mornix since the next step is to remove it from docLang.
