### ISSUE TITLE
GlassBR SRS broken due to references to interpolation

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1139]
(Follows from #1135) As of PR #1138, the GlassBR SRS will break because some code-specific symbols are referenced in DDs. As an example, here's one of the DDs from after the PR:
![image](https://user-images.githubusercontent.com/18634568/53510997-4b525f00-3a8d-11e9-871a-8c8680c4ea14.png)

And here is what the same DD looked like before the PR:
![image](https://user-images.githubusercontent.com/18634568/53510929-1f36de00-3a8d-11e9-8444-e17a7c12a2a9.png)

There is no symbol for the interpolation function, so the Equation looks wrong and the Description has an incomplete sentence.

**Comment by bmaclach** [comment]
With regards to the blank symbol, the reason this happens is because `interpZ` is a `Func`, which is a type for implementation-stage functions. We have a function, `asExpr`, which converts `Func` to `Expr`. It does so by creating a `QuantityDict` using a function `implVar` shown below.
https://github.com/JacquesCarette/Drasil/blob/fbb293e00046f0e1d1000aba676316882548bab3/code/drasil-lang/Language/Drasil/Chunk/Quantity.hs#L43-L49
You can see that the `QuantityDict`'s symbol is set to `Empty` if it is used in the Equational Stage. Thus, the blank symbol when it is used in the Data Definitions for the SRS.

@JacquesCarette As a short-term solution, so that we can at least make the LaTeX compile and merge #1138, would it be acceptable for me to write an alternate function to `asExpr`, say `asExpr'`, which creates a stage-independent variable, and then use that alternate function in these cases where we are currently getting a blank symbol?

**Comment by smiths** [comment]
I have reassigned this issue to @JacquesCarette because the discussion has moved toward a short-term Drasil code solution.  @bmaclach's solution sounds good to me, but there might be consequences that I'm not aware of.

**Comment by JacquesCarette** [comment]
So why is `interpZ` in there at all?  I thought that we filtered out `Implementation`-only symbols from the symbol table. At least, that's what we should do!  In other words, `interpZ` should not show up in the table of symbols at all. 

In other words, it feels like somehow the DD for `J` is insufficiently thought through. Certainly the pre-PR DD seemed wrong too: defining `J` in terms of `J` is quite circular! I think what we need is to be able to declare some abstract function (in this case, `interpZ`) that will be assumed exist but have no specification (?), and will be provided at implementation-time. Or something like that.

**Comment by bmaclach** [comment]
We do filter out `Implementation`-only symbols from the Table of Symbols (we do this by setting their symbols to `Empty` and then filtering out empty symbols) but we don't filter them out for the `SymbolTable`. If we did, then Drasil probably would have complained when we tried to use one here (which is probably what we want).

**Comment by JacquesCarette** [comment]
Thanks for the clarification. Yes, that seems right. The bigger problem of the DD for `J` remains though.

**Comment by bmaclach** [comment]
I agree that the DD for `J` is a problem. Is your proposed solution, to have symbols for abstract functions that exist at the `Equational` stage but are not specified until the `Implementation` stage, something we want to implement immediately? Or should I go ahead with my proposed short-term solution for the sake of getting working generated GlassBR code, with the plan to fix it and implement the correct solution later?

**Comment by smiths** [comment]
My "vote" is  to go with the short-term solution to get things working.  The bridge between requirements, design and implementation is a bigger conversation.  It is definitely a conversation that we need to have, but it would be nice to be working from a base that works.

**Comment by JacquesCarette** [comment]
We need to implement 'something' immediately to get things working. Getting the DD for `J` right is likely too much work - but we need some kind of hack that will enable the documents to be generated (and compile) as well as to generate code that works.  So we might need to have some kind of hack processing of 'abstract' DDs. In the longer term, we'll need to change DDs in the same way I changed InstanceModels in another branch (https://github.com/JacquesCarette/Drasil/blob/8d22f45dc2ab2589159687b3900538d7303ede7b/code/drasil-lang/Language/Drasil/Chunk/InstanceModel.hs#L41) to have more information.

**Comment by bmaclach** [comment]
The short-term fix to the GlassBR SRS has been merged with #1138. The need for a better, long-term solution is documented in #1166, so I'll close this issue.
