### ISSUE TITLE
Spencer Fixme Fixes

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1150]
I should probably fix my the fixmes assigned to me, but @bmaclach will get it done quicker than me.  😄 @bmaclach, I'll explain the new data definitions below.  Can you please enter this information into Drasil in the correct format.  @bmaclach, if you have any questions, or suggested improvements, please let me know.

#### SpencerFixme1Please

Label: Sum of interslice normal forces
Symbol: $F_x^G$
Units: N
Equation: $F_x^G = G_i + G_{i-1}$
Description: $F_x^G$ is the sum of the interslice normal forces (N)
G is the interslice normal force (N)
i is the index (Unitless)
Source: empty
RefBy: will need to be populated by the equations that use $F_x^G$

#### SpencerFixme2Please

Label: Sum of interslice normal water force
Symbol: $F_x^H$
Units: N
Equation: $F_x^H = H_i + H_{i-1}$
Description: $F_x^H$ is the sum of the interslice normal water forces (N)
H is the interslice water force (N)
i is the index (Unitless)
Source: empty
RefBy: will need to be populated by the equations that use $F_x^H$

#### SpencerFixme3Please

Label: Height of right slide of a slice
Symbol: $h^R$
Units: N
Equation: $h^R = y_{\text{slope}, i} - y_{\text{slip}, i}$
Description: $h^R$ is the height of the right slide of a slice (m)
y_{\text{slope}} is the slope y-ordinate (m)
i is the index (Unitless)
y_{\text{slip}} is the y-ordinate of the surface (m)
Source: empty
RefBy: will need to be populated by the equations that use $h^R$

#### SpencerFixme4Please

Label: Height of left slide of a slice
Symbol: $h^L$
Units: N
Equation: $h^L = y_{\text{slope}, i-1} - y_{\text{slip}, i-1}$
Description: $h^L$ is the height of the right slide of a slice (m)
y_{\text{slope}} is the slope y-ordinate (m)
i is the index (Unitless)
y_{\text{slip}} is the y-ordinate of the surface (m)
Source: empty
RefBy: will need to be populated by the equations that use $h^L$

**Comment by bmaclach** [comment]
@smiths A couple things to clarify:

For the 2nd one, did you intend for the label to include the word "normal"? I ask because elsewhere in the SRS we simply call H "interslice water force".

For the 3rd and 4th ones, should the label say "Height of right **side** of a slice" instead of "Height of left **slide** of a slice"?

**Comment by smiths** [comment]
Thank you for the comments @bmaclach.  I did intend for the word normal to be in the new DD, since it is a normal force.  Water force seems like an odd term.  However, let us change what I wrote to water force, to be consistent with the other parts of the document.

Your corrections to the 3rd and 4th ones are also correct.  Thanks!

**Comment by bmaclach** [comment]
Okay @smiths. We can always change the "interslice water force" to be "interslice normal water force" if that's a better name, too.

**Comment by smiths** [comment]
I'm cautious about making too many changes at once, but I do prefer interslice normal water force, if you can make the change without confusion.

**Comment by bmaclach** [comment]
It should be a simple one line change. I'll go ahead and do it.

**Comment by bmaclach** [comment]
These fixes were merged with PR #1152, so this issue can be closed.
