### ISSUE TITLE
symbols in Theoretical Models in GlassBR

### ISSUE THREAD

**Issue by vajihehm** [JacquesCarette/Drasil#1158]
@smiths Just to confirm, according to that I must add the new symbols including "Pfail, Ptolerable, capacity, load" to the table of symbols and you have mentioned "The capacity for SSP is expressed as shear stress. In another problem it might be tolerable torque". I had a chat with @bmaclach though and he told me "T2" is the one that will also be used in SSP. So, I don' t know If they are something general enough to be used in different examples then it should probably be global. @JacquesCarette  should I add them in glabal unitals in code\drasil-data\Data\Drasil\Quantities?

![1](https://user-images.githubusercontent.com/42664092/54325630-a893f780-45d9-11e9-889c-a7f034a9648d.PNG)
![2](https://user-images.githubusercontent.com/42664092/54325631-a893f780-45d9-11e9-8849-1eac928c429c.PNG)
![3](https://user-images.githubusercontent.com/42664092/54325632-a893f780-45d9-11e9-9c89-8a18fa11cbf0.PNG)

**Comment by smiths** [comment]
@vajihehm, let us keep this issue local to GlassBR.  Don't worry about generalizing to something that can be used in other examples at the moment.  @bmaclach is also modifying ssp.  Making too many changes at the same time is just going to cause confusion.  Once you are done and @bmaclach is done, we can consider whether to generalize.

**Comment by smiths** [comment]
We can close this issue, since we  have determined that at this time we won't aim to be too general.  We'll get GlassBR working first.
