### ISSUE TITLE
Standardize period use in ConceptChunk descriptions

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1160]
There does not seem to be a standard convention for whether or not descriptions of `ConceptChunks` should end in a period. Currently, throughout Drasil, some do and some do not. This leads to inconsistencies in rendered documents. As an example, the "Terminology and Definitions" section is built from a list of `ConceptChunks`, so some entries in the list will end in a period and some will not.

I would recommend standardizing this by not including the period at the end of these descriptions. This is because `UnitalChunks` do seem to have the convention of not including periods, and since some of them are built from existing `ConceptChunks`, there would be more inconsistencies if all `ConceptChunks` had periods.

**Comment by smiths** [comment]
@JacquesCarette might be aware of something that I am not, but this sound like a good idea to me.

**Comment by JacquesCarette** [comment]
I agree. 

Certainly, whenever we have something that we expect to be a phrase, it should never have a period. When something is expected to be a complete sentence, then I think that should have a period. Anything that is expected to go into a list should be a phrase, without periods.

This seems to be information about "how to record knowledge", which I think is going to be part of @oluowoj 's work. @oluowoj maybe you can start a page on the Wiki about this?
