### ISSUE TITLE
[Design] Whacking Many Moles

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1164]
# Whacking Many Moles with a Large Mallet
### Spotting the First Mole
Tiny (HGHC) contains a reference to an instance models section, yet does not have an instance models section.

drasil-docLang generates a templated introduction for the system specific description (SSD) section by taking `Section`s (a `Document`-level concept) and referencing them. One of the `Section`s needed for the templated introduction is the instance models' `Section`. `mkSolChSpec` is where this intro is concretely constructed. The instance models `Section` used is `inModSec`, which is a hack. 
https://github.com/JacquesCarette/Drasil/blob/17df24aa82ad721d2390daeda720292708872ad5/code/drasil-docLang/Drasil/DocumentLanguage.hs#L438-L441
https://github.com/JacquesCarette/Drasil/blob/17df24aa82ad721d2390daeda720292708872ad5/code/drasil-docLang/Drasil/DocumentLanguage.hs#L469

The `Section` is a hardcoded stub which “just happens” to have the correct reference label as the "real" instance models `Section`. Under the definition of `inModSec` exists the comment:
https://github.com/JacquesCarette/Drasil/blob/17df24aa82ad721d2390daeda720292708872ad5/code/drasil-docLang/Drasil/DocumentLanguage.hs#L470-L473

The existing implementation brings two problems:
1. We don’t know if an instance models section exists at all.
2. We lose consistency by using the hardcoded stub even _if_ we know whether the section exists or not.

The comment under the definition of `inModeSec` is partially accurate; a walk over `SCSProg` would be nice, but it only addresses the first problem. A walk doesn’t provide any added consistency.

Looking at the tables in `ChunkDB`, you may notice there is a table with a list of `Section`s in the `Document`. You may be wondering: “but we know the reference of the instance models' `Section`, why not get it from that list?” You would be correct, the table does exist, and it does contain the `Section` (and `Ref`erence), however we “can’t” discern which `Section` belongs to the Instance Models. I mean, we can, but not in a nice way, so that rules out that option.

### More Moles Appear
By starting to look at a solution (our mallet) as a walk over `DocDesc`, let’s survey the state of affairs and how to implement a pass over the document language.

Yuhzi has done awesome work on implementing `DocDesc` passes for consistency purposes. Much of the work she’s done for the actual walks resides in ExtractDocDesc.hs in the docLang folder. The implementations algorithmically are very similar — which is great! This similarity means that it is flexible and might be worth looking at how the passes are similar. 

As input to the passes (overall) is the `DocDesc`. The output varies, but are structurally similar: `[Expr]`, `[Sentence]`, or `[CI]`. 
https://github.com/JacquesCarette/Drasil/blob/21a41d9b45d76f2a9b4da276f6ee1d61ac2112ea/code/drasil-docLang/Drasil/ExtractDocDesc.hs#L8-L9
https://github.com/JacquesCarette/Drasil/blob/21a41d9b45d76f2a9b4da276f6ee1d61ac2112ea/code/drasil-docLang/Drasil/ExtractDocDesc.hs#L152-L153
https://github.com/JacquesCarette/Drasil/blob/21a41d9b45d76f2a9b4da276f6ee1d61ac2112ea/code/drasil-docLang/Drasil/ExtractDocDesc.hs#L376-L377

The way I’m interpreting these passes are they are essentially folds! We are folding the document (as a `DocDesc`) to `[a]`. The existing passes are closer to the specific instance of `foldMap`, `concatMap`.

Implementing a new pass to extract something (in the abstract sense) would require writing a series of functions to walk to the interested area, and pull that information out. That’s a lot of repeated busy work that would be nice to not be required to repeat. As an example, let’s assume the consistency issue for the instance model section isn’t present — a pass to extract this bit of information would largely walk the tree to SCSProg, pattern match on `IMs`, return a bool and the fold would be `(||)`. Written in pseudo-Haskell, the piece of interest is: 
```haskell
 getIM :: SCSSub -> Bool
getIM IM@{} = True 
getIM _     = False
```

Where the invocation of this operation would be ideally called like 
```haskell
hasIM = fold (||) False getIMFromDocLang
```

Continuing to look at the current implementation, most of the traceability matrix generation occurs in docLang, however many walks extracting elements from `DocDesc` to fill tables in `ChunkDB` occur in each example. It would be nice to lift this into the `DocDesc` proper making the “end-user” interface and effort to get an example consistent and running more convenient. (Gaining this benefit likely requires some additional work in making `DocDesc` interface more consistent and allowing for a “partial” `ChunkDB` which the `DocDesc` would “complete,” so this seems like a long-term idea rather than an immediate thing).

Another "limitation" exists in `DocDesc`. The `Assumptions` constructor in `DocDesc`, is a constant –– which is good! docLang, in the transformation from `DocDesc` to `Document`, expands the constant constructor using the contents of `ChunkDB.` The process immediately transforms each `ConceptInstance` into a `Contents`. It would be nice to explicitly "lay out" (structurally in a datatype, not document-wise) these `ConceptInstance`s and have an opportunity to use the metadata present from the `ConceptInstance`s before they are transformed in a lossy way to a `Document` concept.

### Taking Stock of the Moles
What are the issues?
1. Perform introspection on `DocDesc`
2. Lack of consistency for `Ref`erences to `Section`s referenced before creation
3. Repetitive “boilerplate” when creating a `DocDesc` pass
4. Information lost too soon when processing `DocDesc`
5. `DocDesc` as a “user-facing” concept and `DocDesc` as an “information trove” used for transformation have competing goals

## “We’re Going to Need a Bigger Mallet”
The ideal solution to this problem: addresses the current deficiencies, aims to be flexible enough to make outstanding issues trivial-ish, and may be a starting point for future intermediaries between generation stages.

The crux of this solution relies on a new intermediary datatype: `ExtendedDocDesc` (EDD). 

### The Case for the EDD
The EDD is (at present –– conceptually) very similar to `DocDesc` with some differences in certain places. One place where `DocDesc` and EDD would differ is EDD’s `Assumptions` constructor would have a list of `ConceptInstance`s as a contained value for easy data extraction. Another difference, instead of `Section` reference addresses residing as hardcoded arguments:
https://github.com/JacquesCarette/Drasil/blob/21a41d9b45d76f2a9b4da276f6ee1d61ac2112ea/code/drasil-docLang/Drasil/DocLang/SRS.hs#L68-L72
they would reside as arguments to certain constructors of EDD. Already, this description of EDD addresses point 2, 4, 5. 

From a transformation perspective, EDD sits between `DocDesc` and `Document`.

As for points 1 and 3:

EDD (and an ancillary structure) will either implement `Foldable` typeclass or implement a function which is similar to `fold`. This should give the pass framework an interface similar to the above-mentioned desired interface.

A pseudo-Haskell representation of this combined structure for passes is:
```haskell
newtype EDDPass a = P (ExtendedDocDesc, Ancillary a)

runPass :: EDDPass a -> a
runPass f (d, a) = foldr f (a ^. default) $ map subPass d
where subPass (SSDSec s) = foldr f (maybe (a ^. default) (\x -> x s) $ a ^. ssdFunc) $ subsubPass ...
```

As for 3, this is where the power of EDD (and the ancillary structure) is introduced. Instead of needing to provide the functional boilerplate of traversing many of the nodes and having many pattern matches with nothing returned, the idea is the ancillary structure is a record datatype where all fields form the general form ```Maybe (<DocLang sub-structure> -> a)```. Evidence of this portion of the design can be seen in the previous code snippet. `a` is the ancillary structure which `ssdFunc` is one of the fields having type `Maybe (SSDSec -> a)`. The `default` field is similar to the idea of `mempty` in the `Monoid` typeclass.

The `Ancillary` structure thus forms a general “pluggable” record where only areas of interest need functions described. The uninteresting areas can be `Nothing` and the general combining aspect is automated away as a fold. The record structure and “hidden” folding infrastructure would allow for realization of `getIMs` as described in “More Moles Appear.”

A design involving the EDD could make implementing #1018 much more approachable and “cleaner.” By adding a constant data constructor to `DocDesc`, say `TableOfContents`, the EDD would not expand this constructor. As part of the process translating an EDD to `Document`, the EDD would be walked and the Table of Contents would be built by a single pass.

To compliment this work done with the EDD, comes the ability to (hopefully) conveniently lift the repetitive operations performed in each example to extract certain items from the `DocDesc` and instead automate that in the `DocDesc` itself, similar to the high-level example given for `TableOfContents`.

Some of the disadvantages of this design include the amount of things that need to be done to complete it. Although at no point should this break stable, or even affect the example implementations, there are a lot of different parts. A disadvantage of the actual implementation means that some of the transformations from the `DocDesc` to the EDD could be effectively the identity and be seen as “pointless.” A limitation of this design is passes may only read (and thus not manipulate) the EDD which makes this implementation only appropriate during the EDD to `Document` transformation stage. 

### A Smaller Mallet
Instead of implementing all aspects of this proposal, instead implement just EDD (not the proposed passes framework). This would bring the expressiveness and ease to add additional `DocDesc` passes without requiring moving as much existing code around. The benefit of this option is it won’t take as much time to implement, as well as gaining some of the periphery benefits mentioned here. 

### That Rock, Over There
At the root of this current issue (i.e. don’t reference/mention the instance models section if it doesn’t exist), the infrastructure is there to do perform a quick fix without touching much code at all. The fix is unsatisfying and at some point investing in a proper mallet would be a good choice. The consistency issue mentioned at the very beginning in "Spotting the First Mole" is not addressed, but the referencing issue is.

### Not Playing the Game, Yet
If perhaps none of these suggested designs and alternatives seem correct, I’m open to exploring other avenues for solving the root problem.

## Conclusion
Taking a look at the initial mole (referencing the IM section when one isn’t present), and surveying the underlying state of the `DocDesc` and existing passes led to this large design proposal aiming to address issues, both blatant and perceived, in the existing  implementation. 

The core of the design is an `ExtendedDocDesc` which is more verbose than `DocDesc` but also not “exposed” to examples — examples would still use `DocDesc`. In addition the EDD includes a `fold`ing-like idea to reduce the amount of work required to implement a pass. Finally an auxiliary structure is used to capture the mapping function for a given sub-structure of the EDD to further reduce the effort required and the verbosity in specifying passes.

Two concrete alternatives have been suggested which scales back the scope of the proposal and narrows the number of “moles” addressed. The first alternative is a direct subset of what the full proposal suggests. The second is a “quick-fix” with limited changes to the area of interest.

Like always, all feedback is welcome.

**Comment by Mornix** [comment]
Brief update:
@JacquesCarette suggested using smart constructors as a likely replacement for the EDD and using multiplates as the foldable-like typeclass/library.

**Comment by JacquesCarette** [comment]
And I think that the follow-up discussion on #1631 is also quite relevant.

**Comment by Mornix** [comment]
Work completed with the merge of #1668. Closing.
