### ISSUE TITLE
NoPCM CodeGen; Bad Code

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1179]
Generating code for NoPCM results in an invalid line being generated. This line is present regardless of the structure (ie. different from #1177) and is present only in the code generated from NoPCM. 
In `Control.py`, `func_get_input` —  defined in `InputFormat.py` — is called without the `InputFormat` prefix (or alternately having the import be `from InputFormat import func_get_input` in the Python output). 

One notable bit I've observed is the `otherwise` branch in `fApp`'s `doit` is being taken which would result in this behaviour of the omitted "prefix" (`InputFormat.`).

https://github.com/JacquesCarette/Drasil/blob/fff755edfbf71a8650fe6cbbda128ff3a37757d0/code/drasil-code/Language/Drasil/Code/Imperative/Import.hs#L376-L385

This again comes back to `eMap` in `CodeSpec` generated from:
https://github.com/JacquesCarette/Drasil/blob/fff755edfbf71a8650fe6cbbda128ff3a37757d0/code/drasil-code/Language/Drasil/CodeSpec.hs#L231-L240

Why it is only affecting NoPCM and not GlassBR, I'm not entirely certain.

**Comment by JacquesCarette** [comment]
I believe I understand this one, so there's that ;)
