### ISSUE TITLE
Unit mismatch issue in GlassBR

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1186]
One of the issues with the generated GlassBR code is that interpolation fails when attempting to calculate `J`. The reason it fails is because all of the calculations assume units of Pa, but `q` actually has units of kPa, so it is off by 1000 times and out of bounds for the interpolation. The reason `q` has units of kPa is because it is interpolated from "TSD.txt", which I'm guessing has values in kPa units.

In the past, we had hardcoded unit conversions, but we intentionally removed such unit conversions (see issues #358, #948).

Would the desired solution here then be to fix our "TSD.txt" to have units in Pa?

**Comment by smiths** [comment]
@bmaclach, I think the easiest solution is what you are proposing.  We could add a requirement that q be input in one unit and converted to the other.  We don't have a requirement for that right now, and adding it seems to add an unnecessary complication.  We can assume that the file is in the units of Pa.

**Comment by JacquesCarette** [comment]
I agree with the short-term fix. But yes, our "data description language" ought to be able to define the units that the external data is in, and we should be able to generate conversion code to work in whatever internal units we want to use.

This might even be related to the 4-variable model, in the general case.

**Comment by bmaclach** [comment]
The TSD.txt has been updated as of merge of PR #1190. Closing issue.
