### ISSUE TITLE
DD references IM in SSP

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1199]
There are some DDs in the SSP example that arise as part of the derivation of an IM. Thus, in the manual version, we reference the derivation of the IM in the DD, shown below. 
![image](https://user-images.githubusercontent.com/18634568/56147534-7b3ebe80-5f76-11e9-8ef6-c018778fd4c9.png)

We can't do this in Drasil because it would create a cyclic reference (IMs should reference DDs, not the other way around, see discussion in #1029).

Would the solution here be to write the derivation again for the DD? That would lead to some duplicated code. Or can we just not provide any information regarding derivation in the DD (i.e. just leave out the sentence shown in the above screenshot)? Since the IM will appear in the RefBy field for the DD, the reader may know to check there for more information even if we don't tell them to.

**Comment by smiths** [comment]
@bmaclach, we should just remove the forward reference to the IM.  After all, the IM doesn't actually derive the DD; it just uses it.  The DD is simply the resistive shear without interslice normal and shear forces.  It is derived by summing the shear forces.  I believe that when the IM was originally derived, the deriver noticed that this collection of terms should have a name, and that the collection of terms had meaning.  We are just summarizing this name and meaning in a DD.
