### ISSUE TITLE
SSP should probably say y coordinate, not y ordinate

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1202]
The first author of the SRS for SSP liked the terminology ordinate.  I remember requesting it be replaced with coordinate, but this only partially happened.  It isn't a major concern, but I keep seeing y ordinate when I look at the documentation.  At some point, I think the uses of ordinate should be replaced with coordinate.

In my research, the term ordinate is an alternate name of the y axis:
https://en.wikipedia.org/wiki/Abscissa_and_ordinate
Unless we are going to talk about the abscissa for the x axis, we should be consistent, and just remove reference to ordinate in the documentation.

If ordinate means the y axis, then saying y ordinate is also redundant.

**Comment by bmaclach** [comment]
As of the merge of #1222, all instances of "ordinate" have been replaced by "coordinate". Closing issue.
