### ISSUE TITLE
arcsin, arccos, arctan in Expr

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1203]
Some equations in SSP require an inverse tangent function, which is currently not possible in Drasil. Can I go ahead and add `Arcsin`, `Arccos`, and `Arctan` to the `UFunc` data type?

**Comment by smiths** [comment]
This sounds like a good idea to me.  Please go ahead and add the new functions.

**Comment by JacquesCarette** [comment]
For the current design of `Expr`, this is the right thing. [For the long term, this is a sub-optimal design, as such information should be data, not code].

**Comment by bmaclach** [comment]
These new functions were merged in with #1204. Issue can be closed.
