### ISSUE TITLE
Case-study-specific paragraphs at start of Instance Models section

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1205]
In the manual SRS for SSP, this is the start of the Instance Models section:

![image](https://user-images.githubusercontent.com/18634568/56241463-ed410180-6063-11e9-86d3-2d72585bc008.png)

The first paragraph is generated automatically by Drasil for every case study. The following paragraphs are specific to SSP, but there is no way in Drasil to add these paragraphs to the IM section.

I checked the other manual case studies and the only other one with additional paragraphs like SSP has is SWHS.

Was it correct to include this information here in the manual version of SSP? If so, I assume we should add to Drasil the possibility of adding additional, case-study-specific paragraphs like these to the IM section?

**Comment by JacquesCarette** [comment]
To include (or not) such paragraphs is an exposition choice -- which @smiths should make. We can then change the `DocLang` to allow it, and that is quite easy to do.

**Comment by smiths** [comment]
@bmaclach, I definitely want to include the instance model introduction text for SSP.  For some cases, the IMs will need some overview comments to help orient the reader.  I think we should incorporate this into `DocLang`.  It is a shame that examples like this keep coming up, where we thought the Drasil version matched manual, but information was actually removed.  Thank you for noticing.

**Comment by bmaclach** [comment]
Thanks for the replies, reassigning this to myself to change the `DocLang` and add the paragraphs for SSP. I can also add the paragraph for SWHS while I'm at it.

**Comment by smiths** [comment]
Sounds good!

**Comment by bmaclach** [comment]
This is done for SSP (#1240) and SWHS (#1248). As I mentioned before, the other case studies do not have any additional paragraphs for their Instance Models intro. However, I think that they probably should? At least, the sentence describing how the IMs map to the goal statements seems like the kind of sentence that we would want in all examples. Do you agree @smiths?

**Comment by smiths** [comment]
Yes, @bmaclach, I agree.  Please proceed with propagating this to the other examples.

**Comment by bmaclach** [comment]
With the merges of #1208, #1232, #1240, #1248, #1274, #1291, and #1315, this is complete. Closing issue.
