### ISSUE TITLE
Some RefBy fields have duplicate references

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1206]
I noticed while updating SSP that sometimes Refby fields list the same references multiple times:
![image](https://user-images.githubusercontent.com/18634568/56247888-4c0e7700-6074-11e9-8143-e11f8581f16e.png)

In this case, the listed IMs each reference this GD multiple times in their definitions, and these duplicate references are not being filtered out any time before rendering the RefBy field.

**Comment by JacquesCarette** [comment]
Yep, must be a `nub` missing somewhere. I'll likely start digging into the code again in May.

**Comment by smiths** [comment]
Good catch @bmaclach.

**Comment by Awurama-N** [comment]
@JacquesCarette please could you elaborate a bit on what you meant by a missing `nub` somewhere? so i could look in the right places to fix this bug.

**Comment by JacquesCarette** [comment]
`nub` is a [standard Haskell function](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-List.html#g:20) which removes duplicate elements from a list.

**Comment by JacquesCarette** [comment]
It quite likely has. It would still be worth looking if it is accidentally fixed or if someone put in a call to `nub` somewhere appropriate.

**Comment by balacij** [comment]
Nice, thank you @hrzhuang. We can re-open this if we find another case.
