### ISSUE TITLE
SSP IM2 Input/Output constraints make no sense

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1209]
Here is SSP's IM2 from Drasil:
![image](https://user-images.githubusercontent.com/18634568/56302920-d4d6f280-6108-11e9-9580-29b80f095765.png)

I'm very confused about the input constraint and output constraint. F<sub>x</sub><sup>G</sup> is one of the cases where we had to create a separate DD as a hack to get explicit grouping. For reference, here is the definition of F<sub>x</sub><sup>G</sup>:
![image](https://user-images.githubusercontent.com/18634568/56303104-35662f80-6109-11e9-9b19-078964437203.png)

So I thought maybe the constraint was supposed to be saying that the interslice normal force is increasing across the slope? But the interslice normal force is neither an input or an output of this IM. And besides, I don't think that's a valid constraint anyways.

Looking in the git history, this is the first version of these constraints, so that was a dead end.

@smiths Do you have any idea what information these constraints were intended to convey? If not, should we just remove them?

**Comment by smiths** [comment]
@bmaclach, this doesn't make any sense to me either.  Yes, I think you should remove this.  I don't see any corresponding constraint in the manual version, so we are not losing information by removing this.  Besides that, it really doesn't make any sense.  F_G is not an input or an output and the constraint doesn't mean anything.

You mentioned that this is the first version of these constraints.  How did they get into SSP?  Was this something I told you to add at some point?

**Comment by bmaclach** [comment]
@smiths No, you never told me to add them. I don't know why they were added, but they first showed up in this big PR (#870) which seems to be where the `InstanceModel` type was first implemented.

**Comment by smiths** [comment]
We could look at blame to see who added this, but I'm not sure it is worth following up further.  It is nonsense and we should just delete it.  :smile:

**Comment by bmaclach** [comment]
I agree. I'll go ahead and delete it. I'll close this issue since my question has been answered.

**Comment by smiths** [comment]
Thanks @bmaclach.

**Comment by JacquesCarette** [comment]
If "output constraints" don't make any sense (in general), we should also remove the feature! I understand that they don't in this case, I am explicitly asking the 'in general' question here.

**Comment by smiths** [comment]
@JacquesCarette, output constraints often do make sense.  They provide us with characteristics of correct solutions.  For instance, probability is constrained to lie between 0 and 1.  For conserved quantities (mass, momentum, energy, etc), we know that the solution must satisfy the conservation equation.  I could think of many more examples.  They won't always be in the simple form of bounding the output.  They are more likely to consist of a more complex relationship for an output and potentially between outputs.

**Comment by bmaclach** [comment]
I was confused when I saw in Drasil that Instance Models had fields for Input Constraints and Output Constraints. That information is already given in the Data Constraints section, so including it within an Instance Model seems redundant. Unless those fields are intended for a different type of constraint then the ones we show in the Data Constraints section?

**Comment by smiths** [comment]
@bmaclach, the input and output constraint fields in the instance models are a recent addition.  They aren't in the manual versions.  I'm not sure who added them to the Drasil generated IMs.  It is redundant information, but that doesn't particularly bother me, since we are generating the documentation.  In the future we can change the template to match the needs of the audience.

**Comment by JacquesCarette** [comment]
As an aside, I prefer to think of the constraints like those for probabilities to be *type* information (which we don't currently have, so need to encode in another way), while conservation laws are invariants. But output constraints will do just fine for now.
