### ISSUE TITLE
Goal Statements are not Referable

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1215]
The instance model intro text for SSP and SWHS, discussed in #1205, contains references to individual goal statements, but in Drasil each Goal Statement is simply a `Sentence` and is not `Referable`. The entire list of goal statements is `Referable`, but without being able to refer to individual goal statements we cannot say how each IM addresses a particular goal.

**Comment by JacquesCarette** [comment]
Yep, that should be fixed.  This basically means that Goals are not 'important' enough as a unit of knowledge in Drasil, and that needs fixed.

**Comment by Mornix** [comment]
Goal statements previously existed in drasil-lang but a bisect shows it was removed roughly six months ago. A comment at the top of the file mentioned `Goal` chunks should be moved to DocLang instead. The content captured by the old `Goal` chunk should be easily adapted to `ConceptInstance`.

**Comment by bmaclach** [comment]
So what you're saying is I can create `ConceptInstance`s from my goal `Sentence`s, since `ConceptInstance` is `Referable`? If that's right, I can take ownership of this since I need it for #1205 and it shouldn't be too hard.

**Comment by JacquesCarette** [comment]
Yes, that is indeed what he's saying.

**Comment by bmaclach** [comment]
This is done for SSP (#1232) and SWHS (#1248). The other case studies do not reference goal statements anywhere in the SRS but I would think we should make their goal statements `ConceptInstance`s anyway for consistency and in case we need to reference the goal statements in the future (and if my latest comment on #1205 is correct, then we will definitely need `Referable` goal statements for all examples).

**Comment by JacquesCarette** [comment]
Agreed.

**Comment by smiths** [comment]
Also agreed.  😄

**Comment by bmaclach** [comment]
Remaining to be done:
- [ ] gamephys
- [ ] glassbr
- [ ] nopcm

**Comment by bmaclach** [comment]
With the merges of #1232, #1240, #1248, #1274, #1291, and #1315, this is complete. Closing issue.
