### ISSUE TITLE
Traceability matrices are backwards according to the corresponding text

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1218]
The text introducing the traceability matrices says:

"Every time a component is changed, the items in the column of that component that are marked with an "X" should be modified as well."

However, in the generated traceability matrix, if item 1 depends on item 2, then an "X" appears in the column for item 1 and the row for item 2. Thus, we are saying that if an item changes, its dependencies may also need to change, when I think what we really want to say that if an item changes, the items that depend on that item may also need to change.

The super simple fix here is to change the word "column" to "row". But if for some reason it is important to have the matrix structured so that you have to look down a column to find the other items that may need to change, we will need to change the way we build the matrix.

Note that this bug is common between all examples.

**Comment by smiths** [comment]
@bmaclach, I'm all for your simple fix.  There is no reason for looking down a column instead of across a row.  As far as I'm concerned, this is an arbitrary decision, so we should do the easiest thing and change the introductory text.

Good catch!

**Comment by bmaclach** [comment]
Fixed with #1219, closing issue.
