### ISSUE TITLE
In-text citation References are included in traceability matrix

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1231]
If a source is cited in-text (for example in an assumption, or in the Notes field of a definition or model) then the traceability matrix will include a row for that source, however the row label is blank, like below:

![image](https://user-images.githubusercontent.com/18634568/56764841-b65da080-6773-11e9-8456-ea6f758238bc.png)

I think that sources should not appear in the matrix, but even if I'm wrong about that there's still the bug where the row label is blank.

Note: Sources appearing in the "Source" field of a TM, GD, DD, or IM do not trigger this bug.

**Comment by Mornix** [comment]
I think I may know what the issue is. I should be able to tackle it in conjunction with #1164.
