### ISSUE TITLE
Design functions to extract subsets of traceability matrix

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1236]
Currently we can easily generate one traceability matrix containing all of the traceability information for a given case study. Having all of the information in one big matrix is not very readable. We want to be able to easily extract subsets of this matrix to build smaller, more focused matrices like the ones we see in the manual versions of the case studies. For example, we want a traceability matrix showing how different items trace to assumptions.

Some of the examples in Drasil do have these smaller matrices, but they are mostly hardcoded. Building these matrices should be automated instead.

See #1233 for the origins of this discussion.

**Comment by smiths** [comment]
Sounds good @bmaclach.

**Comment by Mornix** [comment]
Related to #1197, one of my thoughts to accommodate "views" of a traceability matrix (along with adding ordering to which section of items appear in what order is to add a "filter" of sorts to have the resulting API be something like:

```haskell
tt = generateTraceTable sysInfo

tt1 = viewOfTT [Assumptions] [DD, GD, IM, FR]
tt2 = ViewOfTT [TM, IM] [DD, GD, FR]
```
Which would create two views of the traceability table.
`tt1` which contains Assumptions as the columns and the lists of DDs, GDs, IMs, and FRs as the rows, and `tt2` which contains TMs and IMs as columns and DDs, Gds, and FRs as rows.

**Comment by JacquesCarette** [comment]
Exactly!  We need an " embedded programming language of views" for mapping between the data we have (which can be derived data, such as a traceability matrix) and obtain views on it.
