### ISSUE TITLE
Invalid option `--interleaved-output`

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1243]
Running `make` leads to an "Invalid option `--interleaved-output`" on my Windows 10 system and I'm not sure why. Commenting out the flag works for me (albeit more slowly 😬). Any ideas?

(Not sure who I should assign this issue to)

**Comment by bmaclach** [comment]
The same thing happened to me and a few others a while ago. I believe the fix was just to run `stack upgrade`.

**Comment by samm82** [comment]
Worked like a charm - thanks!

**Comment by Mornix** [comment]
To add to this for anyone searching in the future: `--interleaved-output` is available as of Stack 1.8.

**Comment by JacquesCarette** [comment]
Should the `Makefile` or the cabal file or *something* check that users have the appropriate versions of the underlying tools?
