### ISSUE TITLE
Hardcoding Greek letters in stable

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1247]
Right now, it seems that the Greek letters in stable are hardcoded as ASCII characters.

Example: τ instead of \tau

Should anything be changed?

**Comment by Mornix** [comment]
This was done about a year ago because GHC encodes `Char` as UTF-8 so it could be propagated to HTML and (some variants) of LaTeX unaltered. I believe the literal characters was a desirable change.

@JacquesCarette: Correct me if I’m wrong.

**Comment by JacquesCarette** [comment]
@Mornix is correct, this was done by design.
