### ISSUE TITLE
Correct HLint Suppressions

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1249]
#1117 evaluated HLint for use in Drasil and #1147 made use of HLint in Drasil. While #1147 took care of most of the issues, there were five outstanding classes of lints:
- (104) Move brackets to avoid $
- (140) Eta reduce
- (2194) Redundant bracket
- (133) Redundant $
- (488) Use camelCase
where the number indicates the number of instances the lint appears.

While #1117 mentions obtaining HLint on macOS, a "better" way to acquire HLint is using `cabal install hlint` which will install the latest version (important because newer versions address false-positive "Parse Error" lints). 

While there are a lot of individual lints to fix overall, the speed in which this issue addressed isn't important; there is no rush. There are really three separate "phases" to address this issue:
- [x] Eta reduce (#1262)
- [x] Use camelCase (#1468)
- [x] Move brackets to avoid $ (#1339, #1343, and #1357)
- [x] Redundant bracket (#1385, #1396, #1438, #1443)
- [x] Redundant $ (#1384)

To remove these suppressions, remove the associated line in the `.hlint.yaml` file in the `code` folder.

**Comment by samm82** [comment]
Just an FYI @danscime I'm fixing `off_the_shelf_solutions_2dlist` and friends in GamePhysics Body, so I'll just fix their camel casing issues, too.

**Comment by danscime** [comment]
Once #1468 and #1508 are both successfully merged, the `.hlint.yaml` file can be updated and this issue can be closed.

**Comment by JacquesCarette** [comment]
Both need one more merge, and they're ready to go.
