### ISSUE TITLE
HTML fraction formatting

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1251]
I have noticed at least 2 fractions are improperly formatted in the HTML output of the SWHS example. These fractions appear correctly in the Latex output, just not the HTML. Might be the same issue as #1067

Both occur in the notes sections of the first 2 instance models.

I have included an image showing an example fraction.

<img width="104" alt="Screen Shot 2019-05-02 at 10 52 37 AM" src="https://user-images.githubusercontent.com/28261339/57084769-e7d0f180-6cc8-11e9-8759-ac59b6769fa9.png">

**Comment by JacquesCarette** [comment]
I think those are due to well-meaning hacks in the HTML output. I thought all of it was supposed to use MathJax now, so that the old hacks with div and friends could be removed.

**Comment by danscime** [comment]
After some looking into, I believe these are cause when a fraction is put into a `<p class="paragraph">` section, and when there is text that follows the fraction:
<img width="673" alt="Screen Shot 2019-06-07 at 10 23 39 AM" src="https://user-images.githubusercontent.com/28261339/59111224-9a225700-890e-11e9-9032-549afcc70a39.png">

If we wrap the fraction in a `<div class="equation">` section, it renders nicely, but does not remain on the line with more text:
<img width="582" alt="Screen Shot 2019-06-07 at 10 25 26 AM" src="https://user-images.githubusercontent.com/28261339/59111261-ac03fa00-890e-11e9-845c-92336bde4957.png">

I have looked through .css files as well as the HTML files but still cannot seem to figure out a good solution.

MathJax will likely remove this hack (#479), but if we want to keep the option to choose how to render math, then this hack will need to be looked into.

**Comment by Mornix** [comment]
I took a quick look at the example you posted and the issue with why the equation preceding (DD: htFusion) is laying out flat is the entire equation is  placed in an `<em>` tag which alters the "bounds" forcing the equation to be laid out flat.
