### ISSUE TITLE
Removing glassTypeAbbrsStr

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1254]
While working on GlassBR Body.hs, I noticed a FIXME I thought I'd start to tackle:

https://github.com/JacquesCarette/Drasil/blob/2f41852e705ebf6bb0fff7f69348f15a1fdf5228/code/drasil-example/Drasil/GlassBR/Unitals.hs#L115-L123

I switched `glassConcepts :: [String]` to `glassConcepts :: [CI]`, which is fine, but I'm stuck on how to remove this. `displayConstrntsAsSet` and `DiscreteS` (which is commented out, but is called by `displayConstrntsAsSet`) both take `String`s. `Space` is defined as such:

```haskell
data Space =
    Integer
...
  | DiscreteI [Int]
  | DiscreteD [Double]
  | DiscreteS [String]
```

I'm not sure if I should make a new constructor (I think? Still not back in the groove of Haskell terminology 😂) called something like `DiscreteSen`, or transition `DiscreteS` to take a `[Sentence]`. GlassBR is the only example that uses these functions, so I think the transition to `Sentence` would be relatively straightforward, as well as circumventing the need to extract `String`s from `Sentence`s (although I'm not sure if there is already a mechanism for this). Thoughts? @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
`Space` is extremely "low" in the dependency graph of modules in basic Drasil. If you tried to make it depend on `Sentence`, you'd introduce all sorts of circular dependencies. This is definitely not the right fix. `DiscreteS`'s argument should definitely remain a `[String]`.

The FIXME might be diagnosing the problem incorrectly (it is still a problem). Needs more thinking. I'll come back to this, I want to finish a first pass on everything else first.

**Comment by samm82** [comment]
I was messing around (and have a potential solution by creating a `getAccStr`) and noticed `glassConcepts`, which is unused and a repetition of information from `glassType`.

https://github.com/JacquesCarette/Drasil/blob/193fe97f0d474dd888a29592a15dc96347cbc373/code/drasil-example/Drasil/GlassBR/Unitals.hs#L430-L431

https://github.com/JacquesCarette/Drasil/blob/193fe97f0d474dd888a29592a15dc96347cbc373/code/drasil-example/Drasil/GlassBR/Unitals.hs#L436-L437

Should we remove it, or use it to generate `glassType` (using `zip`). Using it will allow us to not have to use `snd` when getting the list of glass abbreviations, as I did in my previous commit, 193fe97f0.

**Comment by JacquesCarette** [comment]
The best way is actually to generate `glassConcepts` from `glassType` by mapping `snd`. `zip` is partial, which is bad.

**Comment by samm82** [comment]
`glassConcepts` isn't used at all in the example, however - should it be removed?

**Comment by JacquesCarette** [comment]
I wouldn't be surprised if we later discover that it *should* be used but isn't. In that there's probably something almost hard-coded that would be simplified by the use of this.  But, for now, it can be removed.

**Comment by smiths** [comment]
@JacquesCarette is correct.  `glassConcepts` are not part of the current input, because the problem is simplified, but it could be needed in the future.  Also, if we remove it, we are losing information.  We don't want to lose information.
