### ISSUE TITLE
Change "business tasks" to "tasks and behaviours"

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1256]
Noted in 75f2b88fa, the phrase "business tasks" in the requirements intro "jumps off the page... in a scientific context" and should be replaced with "tasks and behaviours".

**Comment by smiths** [comment]
@samm82, I would think the text that defines functional requirements wouldn't be reproduced in each case study.  Hopefully it is something we can change in one place and change it for all examples.  If that is not the case, we should think about changing our overall design.

**Comment by samm82** [comment]
When adding this function requirements intro (maybe I should have thought about this a little more) I copied and pasted it from overarching requirements intro, and removed what wasn't relevant, which ended up matching caseStudies. It would have to be changed at least in these two locations/generalized so that it doesn't have to be.

**Comment by smiths** [comment]
@samm82, any time you find yourself using copy and paste in Drasil, we should be looking for an opportunity for abstraction.  😄   

I'm not sure of the current status here.  Can this definition of functional requirements be written so that all of the cases studies are the same?  Is it possible to have the text written in one place and pulled into all of the examples?  If the text changes in the future, we would like to only have to change it in one place.  The definition of functional requirements should be knowledge that Drasil knows, although I don't think we have yet spent much time "teaching" it about software engineering concepts.

**Comment by samm82** [comment]
I thought of that as soon as I typed "copy and paste". 😬 I'll take a look into it later. 👌

**Comment by samm82** [comment]
@smiths When I updated the functional requirements intro, it was done in `drasil-docLang`, so this change propagated to all examples. The nonfunctional requirements sections across all examples are small enough that they don't have (or need) an intro. The way to generalize this I think would be to create the requirements intro from the functional and nonfunctional requirements intros, but since the nonfunctional requirements intro doesn't have one, this would be... interesting. Should I start by just building the requirements intro from the functional one and then adding the text from the nonfunctional (ie. `reqIntro = funcIntro + S "other info from nonFuncIntro"`), or should I created a nonfunctional intro for the future that will be unused for now? (Although, based on the conversation about `glassConcepts` in #1254, I think this is undesirable.)

Also, there is a difference between "This section..." from the reqIntro and "The following section..." from the funcIntro - which one is preferred?

**Comment by bmaclach** [comment]
Going to call out #1229 because I think it's relevant here. I changed the DocLang to format NFRs similarly to functional requirements (i.e. an intro sentence followed by a list of requirements). It just hasn't been propagated to the examples yet.

**Comment by samm82** [comment]
Good call - I completely forgot about that issue 😂 I'm going to close this issue, since it seems like a subset of #1229, and I'll work on the implementation over there.

**Comment by smiths** [comment]
I was going to search for the issue that @bmaclach mentioned as being related.  I'm glad that he beat me to it.  :smile:
