### ISSUE TITLE
Specifying Precision

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1258]
Work on branch `precision`

As mentioned in (#868), we need a way to specify precision of uncertainties (and other values?). I think the best approach would be to create a new type `Uncertainty` that takes a `Double` (uncertainty) and `Maybe Integer` (precision).

# TODO
- [ ] Move definition of `Uncertainty` to `Uncertainty.Core`
- [ ] Improve helper functions as per comment on f6c27135526836bb30e831439dba8b870cf9a739

**Comment by samm82** [comment]
Before, `UncertainChunk`s had a `Maybe Double` - should they have a `Maybe Uncertainty` instead, or should we enforce that `UncertainChunk`s need to have an uncertainty attached to them? @smiths @JacquesCarette

**Comment by samm82** [comment]
Just an update - the next step is implementing classes so that the uncertainty and precision can be accessed. I'm not sure the best way to do it, and not super comfortable with lenses and classes in Haskell yet, but I think that we might want `HasUncertainty` and `HasPrecision` classes for both `Uncertainty` and `UncertainChunk`. The only thing about this is that it seems weird that an `Uncertainty` would be a member of `HasUncertainty`. I'll get back to this on Monday, but any input is appreciated! @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
And 'oops', I forgot I was signed in as drasil-bot.

**Comment by samm82** [comment]
Yeah Dan and I were wondering if Drasil was getting some AI 😂

The reason I was implementing these classes was to implement `Lens`es for the different components (value and precision) of `Uncertainty`, but now I think simple accessors would be a better implementation (`getUncrt` and `getPrec`), and then use `HasUncertainty` for data types with an `Uncertainty`.

**Comment by JacquesCarette** [comment]
It's getting devOps, which is another buzz-word, but with actual contents.

You should implement some `Lens` related to this, and the accessors should be methods of the corresponding class.
