### ISSUE TITLE
What Should Stable Track?

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1259]
In #1239 @JacquesCarette mentions that the changes to the generated Makefiles should have required an update to stable. 

Currently stable tracks generated TeX, CSS, and HTML files with a specific name in a specific place. 

So the question really boils down to: What should stable track? All generated artifacts? Primary artifacts? (i.e. not Makefiles) or some specific combination?

**Comment by smiths** [comment]
@Mornix, my instinct is that stable should track all generated artifacts, including the makefiles.  I'm also thinking that once the code generator is working that we would track changes in the generated code too.  It seems to me that we don't want changes sneaking in that we aren't aware of and I don't know where to draw the line on things that are too trivial to worry about.  I feel like we should err on the side of caution.

**Comment by JacquesCarette** [comment]
Agree with @smiths . We also don't want new files appearing without us knowing.

**Comment by Mornix** [comment]
All artefacts are tracked as of #1266. Closing.
