### ISSUE TITLE
Merge Reference.hs and RefProg.hs

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1261]
Unless there's a specific reason for having separate modules (@smiths, @JacquesCarette?), I think we can merge the two modules into one Reference.hs. 

RefProg:
https://github.com/JacquesCarette/Drasil/blob/1184b84c48d0d3cdf336f2f3d83cce87b172266f/code/drasil-lang/Language/Drasil/RefProg.hs#L1-L20

Reference:
https://github.com/JacquesCarette/Drasil/blob/1184b84c48d0d3cdf336f2f3d83cce87b172266f/code/drasil-lang/Language/Drasil/Reference.hs#L1-L23

**Comment by smiths** [comment]
@samm82 I don't have an opinion on the proposed consolidation.  However, we shouldn't just be looking at the current code, but ways the files could change in the future.  Although `RefProg.hs` is small now, maybe it won't always be small?  I think we are better off thinking about the reason we have two separate files in the first place.  It could just be how the design grew, or there might be a rationale behind the division.  From a software engineering perspective, we should ask: What is the secret of each module?  If the secrets are different, we should keep the files separate.  If not, we can combine them.

**Comment by samm82** [comment]
I would be in favour of merging them, since `RefProg.hs` defines the `Reference` type, and `Reference.hs` defines its constructors. I'm not sure if these two secrets are discrete enough to separate, and we keep these together in similar modules throughout Drasil (eg. [NounPhrase](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-lang/Language/Drasil/NounPhrase.hs)). @smiths

**Comment by smiths** [comment]
That sounds like a good reason for merging @samm82.  If @JacquesCarette doesn't like it, he'll stop it with the pull request.  :smile:

**Comment by JacquesCarette** [comment]
A lot of this is a product of evolution.  Before we merge, we should take a look at the 'uses' graph (I should check those utilities in) to see if there is a structural reason these were kept separate.

**Comment by smiths** [comment]
Great point @JacquesCarette.  The last thing we want to do is go in circles with design decisions.  Splitting files, remerging them and later splitting them again would be a mistake.  We want to be sure that we are making decisions that we are reasonably sure will "stick" going forward.

**Comment by samm82** [comment]
Throughout `drasil-lang`, `Reference` (from `RefProg.hs`) is imported, and nothing from `Reference.hs` is used internally. Then, in `Drasil.hs`, `Reference` (from `RefProg.hs`) and some helper functions (from `Reference.hs`) are exported to be used by other modules. Since we can specify to only import `Reference` from the merged module, I don't think that this would cause any issues, and the merge would improve the encapsulation of `Reference`, so I think this merge is a good idea.

**Comment by JacquesCarette** [comment]
Let's look at it together in more detail tomorrow.

**Comment by JacquesCarette** [comment]
I think I ended up actually doing this. I'll have to look.

**Comment by Ant13731** [comment]
With the new Ref constructor (and hopefully new shortname version from #2489), I think there might be a lot of changes regarding this issue (to prevent import cycles), so I'll assign myself to this too.
