### ISSUE TITLE
Automate .cabal Version Bumping

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1263]
It would be a lot nicer if the .cabal version numbers of an updated package could be bumped automatically. I'm thinking we could write a script that we would run before making a PR; we could specify the size of the bump (so that we could bump from 0.1.60 to 0.2.0 if we wanted) - this might not be the best approach though, as it would still be semi-manual. @Mornix I'm assigning this to you as well since it seems up your alley, but feel free to focus on more important issues/reassign/unassign.

**Comment by Mornix** [comment]
This is definitely doable, but there is some non-trivial amount of effort involved to get it all set up. drasil-bot is capable of amending a PR with the required version bumps. To do that involves on absolutely settling on when a version should be bumped and parsing enough of the Haskell source and diffs to be able to understand what has changed to accurately update version numbers.

**Comment by JacquesCarette** [comment]
Not worth it.
