### ISSUE TITLE
Remove Section Prefixes/Import Qualified

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1267]
(from #708)

Section prefixes (like in the following) should be removed throughout the examples and relevant imports should be qualified to avoid naming conflicts.

# TODO

- [x] Chipmunk
- [x] GlassBR
- [x] NoPCM
- [x] SSP
- [x] SWHS
- [x] Tiny

https://github.com/JacquesCarette/Drasil/blob/1184b84c48d0d3cdf336f2f3d83cce87b172266f/code/drasil-example/Drasil/SSP/Body.hs#L156-L192

**Comment by danscime** [comment]
GlassBR as per #1406.

**Comment by danscime** [comment]
SWHS as per #1413.

**Comment by danscime** [comment]
NoPCM as per #1416.

**Comment by danscime** [comment]
Chipmunk / GamePhysics as per #1420.

**Comment by danscime** [comment]
SSP as per #1421.

**Comment by danscime** [comment]
Tiny / HGHC as per #1422.

This issue can be closed once the branches are all merged.
