### ISSUE TITLE
Update Contributor's Guide Wiki with additional PR guidelines

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1271]
Please update the Contributor's Guide Wiki to include the advice/instructions given by @JacquesCarette as a comment in:

https://github.com/JacquesCarette/Drasil/pull/1270#event-2321697655

This is good advice and I don't think we have currently captured it anywhere.

**Comment by danscime** [comment]
<img width="529" alt="Screen Shot 2019-05-06 at 3 13 14 PM" src="https://user-images.githubusercontent.com/28261339/57248877-85059000-7011-11e9-88a2-1faeb15f9fc5.png">

Updated. Can be found at:
https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide

**Comment by smiths** [comment]
Great!  Thank you @danscime.  If you notice any other advice that would help in the Contributor's Guide, don't hesitate to add it.  :smile:
