### ISSUE TITLE
Slash Discrepancy from Recent Merge

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1272]
When running `make` on `master` on Windows 10, I get this in my NoPCM log

```
diff --strip-trailing-cr --ignore-all-space -r -X ../.gitignore -x '*.txt' ./stable/nopcm/src/java/Makefile ./build/NoPCM/src/java/Makefile
18c18
< SWHS/Control.class: SWHS/Control.java SWHS/InputParameters.java SWHS/OutputFormat.java SWHS/Calculations.java SWHS/InputFormat.java
---
> SWHS/Control.class: SWHS\Control.java SWHS\InputParameters.java SWHS\OutputFormat.java SWHS\Calculations.java SWHS\InputFormat.java
```

and a similar output in my GlassBR log. I'm guess that the issue has to do with me being on Windows. Any help would be appreciated. (Feel free to reassign to whoever can help - I'm not sure who made this change.)

**Comment by bmaclach** [comment]
I had this issue typed out almost word-for-word and was about to open it. Thanks!

**Comment by Mornix** [comment]
I think this is from trying to be “correct” and using the `</>` operator to append to a path.

**Comment by JacquesCarette** [comment]
This is a problem you (@Mornix ) introduced, so I'll let you have a first crack at it!
