### ISSUE TITLE
Update HTML Wrap

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1299]
HTML wrap function will be updated in order to pretty print tags on the same lines as text, instead of using many lines, each with a separate tag or text.

Based on @deviprasad135's ```ind``` branch and my ```genWrap``` branch.

**Comment by danscime** [comment]
Renaming wrap to oldWrap via f7b4b4f5c87cb8fd67579dd52d3d045185f3762c

**Comment by danscime** [comment]
All changes that will need to be made eventually. Just for reference, this commit will not be used: c630ff2c02c7e14a6afd54dbd43b95e64190f065

**Comment by danscime** [comment]
Initial changes: 4c02e783625fa7c624d675d8b0a3b23db6e99906

Main changes are updating functions in HTML Helper.hs.
Minor changes in Print.hs.

These include refactoring naming of some functions that are to be updated.
Example: Having ```oldEm``` and ```em```.

For now we will keep both functions, and slowly use the new functions and delete the old.

**Comment by danscime** [comment]
First actual change that fixes some line breaks: b1d7aedf68dbe0c729b85171aaba17a7048f1c0e

**Comment by danscime** [comment]
HTML Print.hs is almost completely updated. One more change left, but need to figure it out.
https://github.com/JacquesCarette/Drasil/blob/c409d4ece9c96260364c8065caec601c8259b7df/code/drasil-printers/Language/Drasil/HTML/Print.hs#L69-L70

**Comment by danscime** [comment]
@JacquesCarette Do we want span tags to show up as in the red (all in one line) or the green (separate lines)?

<img width="747" alt="Screen Shot 2019-05-13 at 2 31 22 PM" src="https://user-images.githubusercontent.com/28261339/57645221-cfe05400-758b-11e9-81b0-8591168ee925.png">

**Comment by danscime** [comment]
@JacquesCarette same question as above but with ```div``` tags.

<img width="786" alt="Screen Shot 2019-05-13 at 2 42 24 PM" src="https://user-images.githubusercontent.com/28261339/57645917-5b0e1980-758d-11e9-8d66-3a3a73af369c.png">

**Comment by danscime** [comment]
HTML Helpers.hs ```div_tag``` to be updated.

https://github.com/JacquesCarette/Drasil/blob/74f54958495f84b03c2ddf2b80789ea0853b31e2/code/drasil-printers/Language/Drasil/HTML/Helpers.hs#L162-L163

**Comment by Mornix** [comment]
Semantically speaking `span` is an inline element and `div` is a block element. 

So from that I would say `span` should be “same line” and `div` “multiple lines,” however in your first example with the fraction, I like that one on multiple lines.

**Comment by JacquesCarette** [comment]
In general, I agree with @Mornix here. I prefer to have things 'all in one line' if they fit. But `span` should be less eager to spill over multiple lines, while `div` can be more eager.

**Comment by danscime** [comment]
I believe the way @deviprasad135 has it is that over a certain line length, things get split onto multiple lines. In one of his branches, he includes the option of changing the amount of spacing for indents, which will definitely alter a line's length.

If we were to remove indenting, most of these divs and spans would fit on one line.

**Comment by danscime** [comment]
@JacquesCarette I am currently working on the ```td``` tag. It looks like there will be thousands of line changes per file. Should I have separate commits, say one for each file? Or just keep everything in the same commit as they will have to do with the same change?

**Comment by JacquesCarette** [comment]
Either is fine. I guess separate commits is slightly easier to review.

**Comment by danscime** [comment]
One line change to use new wrap function for ```td``` in HTML Helpers.hs: 17c53bfeb46c4e427678cadd0aca48f6144af096

Massive commit updating SWHS stable based on this change: dc7b6d33681915746aa4157169d7bc4562584da3

Nearly 3000 additions and 8000 deletions. All just removing newlines.

**Comment by danscime** [comment]
Self reminder to remove these:

<img width="199" alt="Screen Shot 2019-05-16 at 2 32 04 PM" src="https://user-images.githubusercontent.com/28261339/57878165-707e8000-77e7-11e9-9202-75ad88e1ca13.png">

**Comment by danscime** [comment]
Reducing SSP HTML from 17000 lines to 8500 via change to ```td``` tag: b2470d2db4fb3a41ac8bc13a5634c9cc712369b0

**Comment by danscime** [comment]
Reducing GlassBR HTML from 7500 lines to 4000 via change to `td` tag: 221d05a092338fdb4636458a723575e0f7850ee5

**Comment by danscime** [comment]
Reducing NoPCM HTML from 5000 lines to 3000 via change to `td` tag: 40465f6717a93c7b37cedef3ba39e20097deca07

**Comment by danscime** [comment]
Reducing Tiny HTML via change to `td` tag: 05f67db87a1471f0cee1723f3742801d0cd7e95e

**Comment by danscime** [comment]
SSP reduction via `td` tag: 11c1f31601457d0f639a2445fa964fb96408961f

**Comment by danscime** [comment]
`td` tag fully updated. Big merge: 3d522446c9ff316b03753a8211b9f0f25e8ddc68.

Next step is to update the stables to match whitespace.

**Comment by JacquesCarette** [comment]
Cool.

**Comment by danscime** [comment]
Stable matches with whitespace as of a7929a8d0fd1476bd03133db945d4f92a0c59280.

Should be able to pass Travis build.

Next step to continue updating tags.

**Comment by danscime** [comment]
Removing oldWrap via 63d51199e65af6d059d68288ccbfb590b7a2302f.

I believe all necessary changes have been made and we are ready for a big PR.
@JacquesCarette @smiths @deviprasad135

**Comment by JacquesCarette** [comment]
Hurray!

**Comment by danscime** [comment]
Issue can now be closed?

**Comment by JacquesCarette** [comment]
Yes!  And all the stale branches that @deviprasad135 has on this should be deleted too.
