### ISSUE TITLE
Fill in Properties of Correct Solution

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1302]
As mentioned in #1276, at some point, the section "Properties of Correct Solution" should be filled in the following examples:

- [ ] SSP
- [ ] NoPCM
- [ ] GlassBR
- [ ] Chipmunk

**Comment by samm82** [comment]
@smiths Is this issue covered by #1624, or should this stay open in case we find more properties?

**Comment by smiths** [comment]
I think we can close this issue because we have #1624 (as you mentioned).  Each of the example should eventually get a thorough review from the physics perspective.  When that happens, additional properties may be added.
