### ISSUE TITLE
Update Contributor's Guide With Rename-refactor "Strategy"

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1303]
In issue #1299 you are using what seems to me to be a generic approach for updating the code when a change will involve touching many parts of the code and will have a significant effect on stable.  This is a pattern that has come up in the past, and it will come up again in the future.  Once you have a good idea of what you are doing, please write an addition to the contributor's guide for future students to use when they are faced with the same challenge.

**Comment by smiths** [comment]
Sounds good @danscime.  However, you haven't really captured the rename strategy that you used.  The case where a function needs to be replaced with a new refactored function will come up in the future.  We don't want to break all of the code, and we want to make sure that the change is made everywhere.  You should describe this problem in a generic way, and then give your steps.  The steps will be something like:

1. Rename the function everywhere it occurs.  The rename should incorporate something that makes it obviously short-term, like "Old."  Use search to make sure all instances are replaced.  This change is just a renaming.
2. Define the new version of the function.
3. Gradually replace the "Old" version with the refactored function.

There might be additional steps, but it seems to me that you did something like that.

**Comment by danscime** [comment]
I think I have captured this knowledge now. It must have slipped my mind before.

<img width="599" alt="Screen Shot 2019-05-14 at 11 14 24 AM" src="https://user-images.githubusercontent.com/28261339/57709662-7898bd00-7639-11e9-9806-ab61d45cda1c.png">

**Comment by smiths** [comment]
Sounds good.  We can close this issue, although if you think of anything to add to the Contributor's Guide, please go ahead and do so.
