### ISSUE TITLE
CI to Generate On-line Documentation and Examples?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1305]
@Mornix, how difficult would it be to automatically generate an on-line web-page that shows our Haddock documentation and our case study examples?  I've never done it, but my understanding is that part of the continuous integration script can keep a web-page up to date.  What I'm thinking is that we could make our web-page more impressive to external visitors if we had more information for them, without them having to install stack and run make.  We could post the following:

- our Haddock  documentation 
- our case studies

I'm thinking that it might be possible to put this material in the Wiki, or maybe there is another place for generated html?

We have discussed having a more impressive web-page in the past, and this seems to me to be a relatively easy way to take a step in that direction.  Since the generated documentation and case studies will always be up to date with master, they might even be a resource we use to quickly look something up.

If this is relatively easy to do, we might change the label for this issue from Question to Enhancement, but we'd need to see what @JacquesCarette thinks.

**Comment by JacquesCarette** [comment]
Sure seems like a good idea to me!

**Comment by Mornix** [comment]
I believe this should all be possible and shouldn’t require too much effort. CI currently builds all of these artifacts and throws them away at the end. I was thinking of hosting this sort of documentation with the master branch for the visual diff idea I’ve been playing with.

**Comment by smiths** [comment]
Thank you @Mornix.  That is the answer I was hoping for.  :smile:  I'm glad to see that @JacquesCarette is also behind this idea.  I'm going to change this question into an Enhancement.

**Comment by Mornix** [comment]
Completed with merge #1474. Followup is #1412.
