### ISSUE TITLE
Missing pi Symbol in SWHS/NoPCM FR2

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1308]
The squared has since been added, but the pi symbol in the following equation is missing in SWHS/NoPCM:

![image](https://user-images.githubusercontent.com/35857611/57538834-36107100-7317-11e9-90d1-a1bec2f5ab63.png)

In my previous attempts, I got an error similar to #1099.

_Migrated from #1281 and should wait for #1309_

**Comment by bmaclach** [comment]
@samm82 The fix to the error in #1099 is to add `pi_` to the chunkDB for SWHS. This should be possible now because `pi_` is a `DefinedQuantityDict` (assuming you are using the one imported from `Quantities.Math`). It should be enough to add `pi_` to `swhsSymbols`.
