### ISSUE TITLE
drasil-bot should untag a PR after the issue is resolved

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1313]
Maybe this isn't feasible, but I noticed my PR (#1286) got the CI:Stable tag because I forgot to update stable. After I fixed this and the build passed, the PR was still tagged. Would it be possible to have the bot remove the tag once the corresponding issue is fixed?

**Comment by Mornix** [comment]
It is definitely feasible and definitely did work. I realize I added a regression between closing my test PR and putting up the real PR. Sorry!

**Comment by Mornix** [comment]
Fixed with the merge of #1314. Closing.
