### ISSUE TITLE
Field not in SymbolMap error

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1323]
@bmaclach , any thoughts on how to resolve this. Could be as a result of all the ongoing changes in Drasil. When I run make, that's when I get this. 
I am currently looking into \Language\Drasil\ChunkDB but just thought I should run this by you.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/43192745/57639180-52154c00-757d-11e9-8562-cec06e59c2c4.png">

**Comment by oluowoj** [comment]
Error is based on this in ChunkDB.hs. Its not seeing momentOfInertiaA
<img width="530" alt="image" src="https://user-images.githubusercontent.com/43192745/57639478-0020f600-757e-11e9-81be-6f0ffbd3d717.png">

**Comment by bmaclach** [comment]
@oluowoj Those types of errors happen when you are trying to use a symbol that you haven't added to the database (ChunkDB). Is `momentOfInertiaA` a new unital that you created? If so, you probably just need to add it to the `everything` ChunkDB in the Body.hs for GamePhysics.

**Comment by oluowoj** [comment]
I did not add momentOfInertiaA at any point and I never got an error regarding this until now(I merged master, could that be?) I am trying to find where it is being used, probably I can comment out, but its not something I added, it might also be a typo but I am not sure

**Comment by bmaclach** [comment]
When I search the code base for momentOfInertiaA there are no matches. `momentOfInertia`, on the other hand, is used in many places. So it seems like a typo. Is it possible that you accidentally typed an A somewhere and did not notice? Can you search for momentOfInertiaA on your local version of the repository?

**Comment by oluowoj** [comment]
Will do. Thanks Brooks

**Comment by oluowoj** [comment]
No matches found in the code base in my locals

**Comment by bmaclach** [comment]
@oluowoj I checked out your branch to see if I could reproduce the error but I got different errors. Can you push your current version of the branch?

**Comment by oluowoj** [comment]
sure will do shortly and let you know

**Comment by oluowoj** [comment]
I just pushed to this branch (gamephy_SRS)

**Comment by smiths** [comment]
This discussion is great to see.  Thank you @oluowoj for creating the issue, and thank you @bmaclach for helping.  I'm optimistic that the two of you will sort out he problem soon.  I don't have anything to offer to help on that.  😄  My reason for stepping into the conversation is to highlight that there will be some kind of "debugging" or code writing "lesson learned" that comes out of this.  @oluowoj, I'm sure you are already doing this, but I suggest that you distill whatever we learn from this into a document for later use.  We don't know exactly how we are going to structure things going forward, but we do know that part of your project will be how to create and maintain projects in Drasil.

**Comment by oluowoj** [comment]
Yes I am making notes of all my findings and issues encountered and eventually will create a document from all my notes and can consolidate everyone's notes (if available) into one. 


@bmalach, I am merging master one more time, so another push in a few seconds.

**Comment by smiths** [comment]
Sounds good @oluowoj!

**Comment by bmaclach** [comment]
@oluowoj Okay thanks, I reproduced the issue. "momentOfInertiaA" is the UID for the `momtInert_A` `UnitalChunk`. It wasn't showing up in searches because "A" is appended to "momentOfInertia" through the `momtParam` function. Anyway, it looks like during your merge `momtInert_A` was accidentally removed from the list `cpUnits` (and thus also removed from the `ChunkDB`). Adding `momtInert_A` to `cpUnits` should fix the issue.

**Comment by JacquesCarette** [comment]
Was this done?

**Comment by dusear4la** [comment]
Yes, this was definitely completed.

**Comment by oluowoj** [comment]
Looks like its this PR #1439
