### ISSUE TITLE
Conflicts with a lot of field names after merge : Checking before manual resolution

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1325]
I tried to merge master with into one of my branches, I am getting a huge number of conflict mostly on the field names, I noticed that a lot of field names have been reformatted. See sample below: <img width="618" alt="image" src="https://user-images.githubusercontent.com/43192745/57649890-66fed900-7597-11e9-8c4f-301cf35f92aa.png">

@danscime @samm82, are you working on anything related to this change in gamephysics example?

**Comment by danscime** [comment]
So I was working on GamePhysics last week and all my changes have been merged. Currently I am not working in GamePhysics.

**Comment by samm82** [comment]
I split some code into the `drasil-database` package, so that explains the 
```haskell
import Database.Drasil (Block(Parallel))
``` 
in `master`

**Comment by oluowoj** [comment]
> So I was working on GamePhysics last week and all my changes have been merged. Currently I am not working in GamePhysics.

Thanks, were there any changes you made  that reformatted those parameter names in the screenshot?

**Comment by danscime** [comment]
@oluowoj Yes they were my changes that reformatted the names.

**Comment by oluowoj** [comment]
> @oluowoj Yes they were my changes that reformatted the names.

Thanks good to know, was this on purpose?
So going forward we should use the format  'VelA' rather than Vel_A as the naming convention(where applicable?

**Comment by danscime** [comment]
@oluowoj Yes on purpose, as part of the Hlint process to use camelCase instead of snake_case as per #1249.

**Comment by smiths** [comment]
@oluowoj,  you should read through the issues that were created while you were busy studying.  @danscime and @samm82 have been busy.  😄  I also recommend that you subscribe to all watches for this repo.  That way you'll have a better idea of how the code is evolving.

**Comment by oluowoj** [comment]
Thanks @danscime

**Comment by oluowoj** [comment]
closing issue.
