### ISSUE TITLE
Add derivation for base hydrostatic force and slice weight in SSP

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1332]
Derivations should be added for base hydrostatic force and slice weight in SSP, similar to what was done for #1277. These derivations will require references to General Definitions, so the DDs for base hydrostatic force and slice weight will also need to be switched to GDs. If this gets too messy, a new design may need to be discussed.

**Comment by bmaclach** [comment]
With #1345, #1380, and #1392 all merged, this is done.

**Comment by smiths** [comment]
Great!
