### ISSUE TITLE
Determine diff Args

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1344]
The Makefile currently uses the args `--ignore-all-space` and `--strip-trailing-cr` as part of its arguments on what to ignore when `diff`ing.  While I believe `--strip-trailing-cr` is needed to account for Windows/Unix line ending differences, I'm not convinced `--ignore-all-space` is necessary. But don't have a Windows build environment to test with.

On master can you `make` with the following combination of arguments for `diff` (`Makefile`, line 33 — leaving the other arguments present):
1. `--ignore-all-space`
2. `--strip-trailing-cr`
3. Neither
and let me know if the combinations produce any log "differences".

**Comment by samm82** [comment]
In the middle of a raunchy merge conflict but I'll take a look 👌

**Comment by JacquesCarette** [comment]
We could certainly try to remove `--ignore-all-space` and see the results. They definitely were needed at some point, but now I forget why!  [Bad documentation!]

**Comment by Mornix** [comment]
The commits where they were added:
* `--ignore-all-space` 10ed4df
* `--strip-trailing-cr` 8ddc246

It definitely seems like the former we can remove, but I want to be certain it doesn't cause any issues on Windows systems before I do it.

**Comment by samm82** [comment]
All combinations of these flags result in clean logs, so @Mornix I think you're good to remove these!
