### ISSUE TITLE
Workflow for MIS Generation Branch

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1348]
There is a stable (manual) version of the GlassBR MIS, and the built version does not match it quite yet. Should I save the stable version to my local machine, update stable of GlassBR MIS to match the built so that `make` runs clean, (so we can merge to master as soon as possible) and then work on fixing the broken MIS in smaller branches, or should I get the MIS to a point where it matches stable before we merge it in?

**Comment by smiths** [comment]
As you are probably gathering from my other comments, there isn't anything "sacred" about the GlassBR MIS document.  It is my first attempt to document the design of GlassBR following the Parnas approach, but it hasn't received much scrutiny.  I know @JacquesCarette is going to have some changes to propose for the MIS, or maybe even a very different approach.

Given this, let's do what is easiest.  If you like your version, and the differences are cosmetic, you can replace stable with your version of stable.

**Comment by samm82** [comment]
Right now, most of the differences are sections that are completely missing - I just thought getting this merged in would make future changes a lot easier, as they could be done a little bit at a time through separate PRs.

**Comment by smiths** [comment]
That sounds like a good plan to me.
