### ISSUE TITLE
Links in MIS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1350]
This might be easier said than done, but the manual version of the GlassBR MIS has links to the SRS, MG (which isn't generated yet), and the caseStudies repo for GlassBR. @smiths Since we're not maintaining the caseStudies version anymore, should there still be a link to it?

# TODO
## Intro
- [ ] SRS
- [ ] MG
- [ ] caseStudies Glass repo
## Module Hierarchy
- [ ] MG

**Comment by smiths** [comment]
The case study repo is still a good source of information, especially for those documents that don't yet exist in Drasil.  I think we should keep the links.
