### ISSUE TITLE
"Dehardcode" Example of Conditional Rule in MIS Notation Section

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1351]
The following example of a conditional rule:
![image](https://user-images.githubusercontent.com/35857611/57884553-df170a00-77f6-11e9-8fa4-a489aee6c0b4.png)
should be "dehardcoded" so that it displays as:
![image](https://user-images.githubusercontent.com/35857611/57884583-f524ca80-77f6-11e9-9669-df17ce1f52fa.png)

**Comment by smiths** [comment]
I agree.   Your new version looks much nicer.  😄
