### ISSUE TITLE
Improve Data Type Descriptions

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1353]
The "placeholder" descriptions for the data types (displayed in the MIS Notation Table) should be updated to match the manual:

EDIT: Natural numbers include zero

![image](https://user-images.githubusercontent.com/35857611/57885032-12a66400-77f8-11e9-9d80-c98c246eae90.png)

**Comment by smiths** [comment]
As we discussed in #1355, you don't have to worry about getting this information into Drasil.
