### ISSUE TITLE
"Data Type" vs. "Datum Type"

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1354]
@smiths The manual version of the Notation Table has "Data Type" for the header of the column that displays the data type, but in Drasil it has "Datum Type" (I tried to get it "Data Type" to no avail). Just to clarify, "Data Type" is preferred, correct?

**Comment by smiths** [comment]
As we discussed in #1355, we don't really want to devote too much time and effort to something that is likely to change.  I've never used the expression datum type, so I do prefer data type, but I don't think you need to stress over getting this perfect.  I actually like the idea of removing this table entirely.  I think we should keep things simple in the introduction and add more detail as we refine our approach to design documentation.
