### ISSUE TITLE
Strings: Primitive or Derived? (Notation Table)

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1355]
In the manual MIS Notation section, strings are listed as both primitive and derived data types, with two separate definitions:
![image](https://user-images.githubusercontent.com/35857611/57885268-8f394280-77f8-11e9-8076-d023d3b1d5cb.png)

I have two questions:
1) Which definition is preferred?
2) Are strings primitive or derived? (This is tricky since they are primitive in some languages and derived in others. Not sure what approach we should take in the MIS.)

**Comment by smiths** [comment]
As we discussed elsewhere, we don't want to get distracted by this right now.  The MIS that you are working on is a good starting point for discussion of our design documentation, but I'm sure it will change over time.  Devoting too much effort to the boiler plate introduction wording isn't a good use of our time.  Having an infrastructure in place where we can include the same text in every example is good, but the specific content of that text can wait until we have a firmer idea of the structure of the MIS.

Let us delete all of this, and replace it with references to Ghezzi et al, Hoffman and Strooper and Gries and Schneider.
