### ISSUE TITLE
Derivations should be able to contain Figures

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1356]
Currently a `Derivation` in Drasil is a synonym for a `[Sentence]`, so it can only contain things that can be expressed as `Sentence`. It is easy to imagine wanting a picture to help explain a derivation, but currently such a Figure could not appear in the `Derivation` and would instead need to appear elsewhere and then be referenced in the derivation, which is not ideal for readability.

**Comment by smiths** [comment]
Sounds good @bmaclach.  As we discussed yesterday, we don't need Figures in our derivations  yet, but at some point we will.  For instance, the derivation of the moment equilibrium in SSP that we have discussed would eventually benefit from a figure to show the locations of the forces, water table, coordinates, etc.

**Comment by JacquesCarette** [comment]
Derivation needs an actual design. Right now, as `[Sentence]`, it is basically opaque and unstructured. We don't want to straight-jacket things either, but still, a little more structure would be good!

**Comment by balacij** [comment]
Closed in favour of #968 -- this ticket is a 'problem' and #968 is a 'jump to the solution' -- we can/should repurpose that one.
