### ISSUE TITLE
DIFF doesn't ignore whitespace? What to do?

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1359]
Upon merging #1346 to my ```updatingHTMLwrap``` branch, some of my empty logs became full. Looking through the logs, I'm pretty sure all of the diffs are just due to the tabs and whitespace differences on each line.

But now, a lot of my changes with @deviprasad135 add indents to most of the lines. Wondering what I should do for now and the best course of action?

I know Devi had a branch that would let the user pick the amount of indenting. So maybe if that branch was updated and merged, we could set the indent size to 0 when building?

**Comment by danscime** [comment]
For now I can re-add the line:
```DIFF = diff --strip-trailing-cr --ignore-all-space -r -X ../.gitignore -x '*.txt'```
to the Makefile and continue to work.

But soon, we will need to figure this out.

**Comment by deviprasad135** [comment]
@danscime, you can change the indentation amount in the `indent` function which is in Helpers.hs file.

**Comment by danscime** [comment]
Changing ```indent``` function worked for a lot. Still some issues with some things shifting over when part of ```<div class="fraction">```` blocks.

<img width="354" alt="Screen Shot 2019-05-17 at 12 30 50 PM" src="https://user-images.githubusercontent.com/28261339/57942515-a41ce100-789f-11e9-943c-8d1281c03ee8.png">

I'm thinking to maybe use the old functions for now to revert these indent changes, and then, eventually, I can add these indents to keep 'blocks' together.

**Comment by danscime** [comment]
OR I might continue to ignore whitespace and edit stable based on my previous changes. Then once those are complete, I will edit the tabs. This will hopefully, keep commits decently organized.

**Comment by JacquesCarette** [comment]
The thing I'm wondering about, why are there tabs instead of spaces (or vice-versa)? 

Also, I think there's something weird going on with `div` and `span`, especially the ones with fractions. I think there's a hack in there, and it is contributing to these headaches.

Changing indent is not the right solution. The right solution first involves understanding what is the actual source of these symptoms!

**Comment by danscime** [comment]
1. So the indents are just 4 spaces that look like tabs, but they are indeed spaces. So no need to worry about tabs.

2. Devi was explaining to me that because we are now using the pretty printing library, the fractions and case equations work to line up their parts:

<img width="394" alt="Screen Shot 2019-05-17 at 1 46 04 PM" src="https://user-images.githubusercontent.com/28261339/57946374-25797100-78aa-11e9-9e5f-12e44f4d65fc.png">

Here, all of the parts line up with the initializer ```<div class="fraction">```.
It does look more organized and it does not seem to be a hack anymore (based on how he explained it and the examples we've came across).

3. Changing the indent number does not affect these indented `div` and `span` tags. The indent number affects new tags being created within a tag.

indent 0:
<img width="515" alt="Screen Shot 2019-05-17 at 1 49 58 PM" src="https://user-images.githubusercontent.com/28261339/57946669-e8fa4500-78aa-11e9-9dfe-98af01aa20b3.png">

indent 4:
<img width="580" alt="Screen Shot 2019-05-17 at 1 50 58 PM" src="https://user-images.githubusercontent.com/28261339/57946680-edbef900-78aa-11e9-8b20-1f3da1ab7a82.png">

**Comment by JacquesCarette** [comment]
So what are the outstanding issues then?

**Comment by danscime** [comment]
I believe we have figured them all out for now. This issue can be closed.
