### ISSUE TITLE
Terms from MIS added to SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1361]
Right now, there are symbols from the MIS that appear in the Table of Symbols of the SRS and should be removed, probably by having two separate symbolMaps - one for MIS and one for SRS.

@smiths I'm just confirming that this is the change that should be made. MIS-specific quantities (like MAX_ORDER or input file name variables) shouldn't be captured in the SRS.

**Comment by smiths** [comment]
@samm82 you are correct that MIS specific symbols should not be in the SRS.  I believe that this is a known issue.  I believe there is a reason related to the code generation that there are symbols in the SRS that are not used in the SRS.  We should definitely fix this.  I just don't know how big a fix is involved.  We should discuss the design with @JacquesCarette when we have a better idea of how we are going to bridge between the requirements and the design.

**Comment by samm82** [comment]
I'm pretty sure the fix came as a byproduct of splitting the MIS and SRS into separate files, but I've held off on working on the MIS until tomorrow. @smiths
