### ISSUE TITLE
File Structure of MIS/SRS in Examples

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1363]
Right now, the SRS and MIS are being "encoded" in Body.hs, which makes the code more difficult to deal with. Can this be split into SRS.hs and MIS.hs for better information hiding, or should it stay as Body.hs?

**Comment by JacquesCarette** [comment]
It can definitely be split.

**Comment by samm82** [comment]
I'm going to close #1360 until I do that, since it should help with merging into other branches.

**Comment by samm82** [comment]
Reopened #1360 @JacquesCarette

**Comment by smiths** [comment]
I agree with the split.  It is better to keep anything to do with the MIS.  It is likely to change significantly.  We can always refactor in the future, as we have done many times in the past.
