### ISSUE TITLE
New Function Data Type

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1366]
I'm not sure if this is too "hardcoded", but I'm thinking for the MIS we implement a `Function` datatype that takes a name (`Symbol`), list of inputs, an output, a list of exceptions, and list of `Transition`s. A `Transition` would take a (`HasSymbol`, `DefiningExpr` etc.) and an `Expr` (which would be its new value). This would allow us to display these functions in both the table (under Syntax) and in the Access Routine Semantics section.

Then, we'd build the functions in a Functions.hs module for the GlassBR example. Thoughts? @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
I can't tell. Basically, in the context of Drasil, I don't know what it is we're even trying to say in an MIS, so I can't judge the quality of the encoding.

**Comment by smiths** [comment]
@samm82 we really need to have a proper design discussion about the MIS information.  The MIS you are working from is a good representation of how we documented the design in 2AA4, but @JacquesCarette and @bmaclach have not had a chance to review it.  We have two problems to address:

1. How to tell Drasil the design decisions that bridge between the requirements to the code, such as the choice of interpolation algorithm in GlassBR
2. How to document the design for human readers

I think the MIS can potentially accomplish both of these, but we don't want to rush too far down this road.  I don't know the details but @JacquesCarette has some concerns.  Again, we need a proper discussion.

If it is "easy" to generate the existing MIS in Drasil, then the exercise of translating it to Drasil will help us understand some of the issues better.  If it is a difficult task, then it isn't worth your time  until we make sure we are on the same page.

You suggested that you were close to being able to generate the existing MIS, so I think you should finish it up.  However, don't put too much effort into doing things the "right" way.  Just get it working.  Hardcoding is fine.  If this is turning into a big job, then you should stop.

@JacquesCarette, maybe you me, @samm82 and @bmaclach can meet next week to discuss the design bridge?

**Comment by samm82** [comment]
I think it would be worthwhile to wait on the merge of #1360 until our discussion.

**Comment by JacquesCarette** [comment]
I might be able to squeeze in some time on Wednesday, even though I have a visitor around Tuesday-Wednesday.

**Comment by samm82** [comment]
Any time works for me 👍

**Comment by bmaclach** [comment]
My schedule is open as well (except for on Friday, but it seems like Friday's already out)

**Comment by samm82** [comment]
@smiths @JacquesCarette @bmaclach So what time on Wednesday (if that for sure works)?

**Comment by smiths** [comment]
I can meet tomorrow (Wednesday, May 22).  I would prefer after 12:30 pm, but I could meet at 11:00 am, if that is the only option.  I think this will depend on the availability of @JacquesCarette.

**Comment by JacquesCarette** [comment]
Afternoon works for me.

**Comment by smiths** [comment]
Great!  We'll meet tomorrow (Wednesday) afternoon.  We can firm up the time tomorrow.
