### ISSUE TITLE
Make error (Windows?)

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1367]
As of the merge of #1346, I get the following error when I run `make`:
```
$ make
/usr/bin/sh: C:/Program: No such file or directory
make: *** [check_stack] Error 127
```
I'm guessing the file path it's supposed to be looking for is `C:/Program Files/` but it's getting cut off at the space? Any thoughts @Mornix?

**Comment by Mornix** [comment]
Interesting. Nothing changed with `check_stack.sh` with `build_cleanup`. I'll look into it.

**Comment by Mornix** [comment]
Quick question: Line 80 of the `Makefile`, if you quote `$(SHELL)` so it looks like:
`	 @MIN_STACK_VER=$(MIN_STACK_VER) CACHED_MSV_FILE=$(CACHED_MSV_FILE) "$(SHELL)" $(SCRIPT_FOLDER)check_stack.sh` does that result in a different error?

**Comment by bmaclach** [comment]
That almost fixed it, it ran through almost the entire make process but then I got the same error at the end:

```
Copied executables to C:\Users\brook\AppData\Roaming\local\bin:
- chipmunkdocs.exe
- glassbr.exe
- nopcm.exe
- ssp.exe
- swhs.exe
- tiny.exe
cd build/Tiny && stack exec -- tiny
cd build/GlassBR && stack exec -- glassbr
cd build/NoPCM && stack exec -- nopcm
cd build/SWHS && stack exec -- swhs
cd build/SSP && stack exec -- ssp
cd build/Chipmunk && stack exec -- chipmunkdocs
diff -r -X ../.gitignore -x '*.txt' ./stable/tiny/ build/Tiny/ > logs/Tiny_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' ./stable/glassbr/ build/GlassBR/ > logs/GlassBR_log.log 2>&1
make: [glassbr_diff] Error 1 (ignored)
diff -r -X ../.gitignore -x '*.txt' ./stable/nopcm/ build/NoPCM/ > logs/NoPCM_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' ./stable/swhs/ build/SWHS/ > logs/SWHS_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' ./stable/ssp/ build/SSP/ > logs/SSP_log.log 2>&1
make: [ssp_diff] Error 1 (ignored)
diff -r -X ../.gitignore -x '*.txt' ./stable/gamephys/ build/Chipmunk/ > logs/Chipmunk_log.log 2>&1
----------------------------
Make complete, checking logs
----------------------------
/usr/bin/sh: C:/Program: No such file or directory
make: *** [test] Error 127
```

**Comment by Mornix** [comment]
There are 3-4 other `$(SHELL)` instances in the Makefile, I think the one on line 104 should be enough to get a regular build restored. I'll make the necessary changes here (including other places where I missed quotes 😓) and put up a proper PR.

**Comment by bmaclach** [comment]
Great, thanks for the quick response!

**Comment by vajihehm** [comment]
@Mornix as @bmaclach mentioned I also got this error and I can not do build locally. Should we fix it manually ?[ for double check: doing quote $(SHELL) in MakeFile ] , If yes we would not have conflict later?

![1](https://user-images.githubusercontent.com/42664092/57962951-a573fb00-78eb-11e9-9b79-8616894ee648.PNG)

**Comment by vajihehm** [comment]
@Mornix Although, I have successful build locally, I do not have successful build on Travis #1370 , would this issue be related to the Make File?

**Comment by Mornix** [comment]
@vajihehm Yup! Those same two changes @bmaclach made should suffice until #1368 is merged.

This issue isn’t responsible for build failures with #1370. It looks like some warnings were present and thus became errors in CI. It also looks like some files aren’t updated in stable.

**Comment by vajihehm** [comment]
@Mornix perfect thanks!

**Comment by Mornix** [comment]
This issue should be good to be closed if @bmaclach or @vajihehm can confirm with the latest changes to `master` building on Windows works again.

**Comment by vajihehm** [comment]
@Mornix You mean, should we undo the local changes on the MakeFile and get the MakeFIle from `master`?

**Comment by Mornix** [comment]
Yup.

**Comment by vajihehm** [comment]
@Mornix I have tested with the new changes and it works well. So you can close this issue.
