### ISSUE TITLE
some functions have been generated twice in the GlassBR in build src 

### ISSUE THREAD

**Issue by vajihehm** [JacquesCarette/Drasil#1377]
Par as #1370 errors in Travis,  some functions were being generated twice (e.g. in `Calculations.cpp `like `func_q` in `stable` and `func_is_safePb` in the `build` folder), should I change manually in the `stable` version? as neither `build` folder is correct nor `stable` folder. 

In the case `Calculations.cpp` I have changed it  in the stable folder, but I am not sure this approach would be correct as I think the correct source code must be generated in the build folder automatically, right?

**Comment by vajihehm** [comment]
I think this duplication is due to the theoretical models which are still the old ones in this branch, so these functions have been defined by both TM and IM in SRS in this branch. So I think I should change TM in this branch according to the #1304 as well.

**Comment by Mornix** [comment]
That sounds like the likely cause of the duplicated identifiers and functions in the generated code.

**Comment by bmaclach** [comment]
Agreed.

**Comment by JacquesCarette** [comment]
Yes, to fix this, you should change the example (i.e. the TM), not the output code.

**Comment by JacquesCarette** [comment]
As far as I can tell, this is long fixed.

**Comment by smiths** [comment]
Yes, I'm sure this has been fixed.  From a recent conversation with @bmaclach, I learned that the travis build compiles the generated code as a test.  If there were duplicate functions, the code would not successfully compile.  I also had a quick look at the generated code for GlassBR and I didn't see any duplicates.
