### ISSUE TITLE
Add this info to Contributor's Guide - Creating a new branch

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1379]
![image](https://user-images.githubusercontent.com/43192745/58098600-eb5ce780-7ba7-11e9-9435-1a4d4391ef30.png)

**Comment by smiths** [comment]
Looks good @oluowoj.

**Comment by oluowoj** [comment]
This has been added

**Comment by smiths** [comment]
@oluowoj, can you reproduce the changes, or point to the web-page, so that I can check your work.  I'm sure it is great, but for future inspection, it is great if we have traceability in our issues, especially when we close them.

**Comment by oluowoj** [comment]
Sure, I just created a branch and will push this as soon as I can

**Comment by smiths** [comment]
The Contributor's Guide is on the Wiki, so you shouldn't have to create a branch.  You can just edit the Wiki.

**Comment by oluowoj** [comment]
Oh I see. I will take a look and update with what I already documented.

**Comment by oluowoj** [comment]
https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide
<img width="646" alt="image" src="https://user-images.githubusercontent.com/43192745/58285239-6118ad00-7d7a-11e9-9246-bcbc23015760.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/43192745/58285291-755caa00-7d7a-11e9-9434-710a3b86ae85.png">

**Comment by oluowoj** [comment]
@smiths , I made a few updates, please see the link

**Comment by smiths** [comment]
Yes.  This is what I was hoping for.  Looks great!
