### ISSUE TITLE
dot: Command Not Found

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1386]
Running `make` since #1378 leads to this error on my machine:

```
stack install dotgen graphmod
Copying from C:\Users\samcr\Desktop\Summer Research\Drasil\code\.stack-work\install\fd843c69\bin\graphmod.exe to C:\Users\samcr\AppData\Roaming\local\bin\graphmod.exe

Copied executables to C:\Users\samcr\AppData\Roaming\local\bin:
- graphmod.exe
find "drasil-lang" -name '*.hs' -print | grep -v stack | xargs graphmod -q -p --no-cluster | dot -Tpdf > graphs/drasil-"lang".pdf
/bin/sh: dot: command not found
make: *** [lang_graph] Error 127
```

From what I've researched, it looks like its a PATH issue, but there isn't any "GraphViz" folders in "Program Files" or "Program Files (x86)", and I can't find the installation, so I'm not sure what to add to the PATH. I've installed `graphviz` in every way I could think of (using `cabal`, `stack`, `npm`, even `pip`) to no avail. I'm on Windows 10 using MinGW. Any ideas?

**Comment by Mornix** [comment]
Looks like graphviz is missing, there’s windows binaries [here](https://graphviz.gitlab.io/_pages/Download/Download_windows.html)

**Comment by samm82** [comment]
@Mornix Thanks! Installing through the .msi installed it in "Program Files (x86)" (as expected) and I was able to add it to the PATH with no problems! Just one quick question - in the graphs, do the colours of the nodes mean anything or is it just for the _A E S T H E T I C_?

**Comment by JacquesCarette** [comment]
The colours mean "in the same directory", and are picked by `graphmod` itself.
