### ISSUE TITLE
Blank Projectile SRS Template

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1391]
I have finally done it. I have an empty Drasil SRS template (added in aff8804fc78242a9d8f949af0cc60c92aa59ffcb)! The only non-general things are the title and author, which are basic enough that I didn't bother adding placeholder ones. @smiths @oluowoj @JacquesCarette @bmaclach There are three questions I have about this:
1) Where should this template be kept for future use?
2) When should this be merged into `master`? (if now, #1397)
3) Am I good to start incrementally building a Projectile SRS?

**Comment by JacquesCarette** [comment]
A working template is a good idea. I would create an new, empty project, called Template, for this (i.e. in drasil-examples). Merged asap. And I see no barrier to you incrementally building this SRS.

**Comment by samm82** [comment]
Thanks! I'll do that ASAP.

**Comment by smiths** [comment]
Yes, I like the idea of an empty template example.  That can be a starting point for future examples.
