### ISSUE TITLE
Passing Filename to GlassBR/Projectile Makefile

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1393]
I based the code for Projectile on the generated code from GlassBR, and I'm having an issue with the Makefile. I think it might be because I'm on Windows, but running `make run <inputFile>` returns an `IndexError: list index out of range` because the input file isn't being passed in as an argument:
```
$ make run inputFiles/hitInput.txt
python Control.py
```

instead of 
```
$ make run inputFiles/hitInput.txt
python Control.py inputFiles/hitInput.txt
```

This same error occurs when `make run`ning GlassBR. Is the Makefile broken or am I doing something wrong? (And are you guys the right people to ask? 😂)

https://github.com/JacquesCarette/Drasil/blob/3b53bc7a6b623fc9c0deb0528f4a3cad6044f61f/code/stable/glassbr/src/python/Makefile#L16-L21

**Comment by bmaclach** [comment]
You can pass the input file in to the `make run` command like so:

`make run RUNARGS=hitInput.txt`

That's how I've been running the Makefiles, at least.

**Comment by samm82** [comment]
Works for me - thanks!

**Comment by smiths** [comment]
Thanks for brining this up @samm82 and for the solution @bmaclach.  I learned something.  😄
