### ISSUE TITLE
Blank SRS Tex File Not Compiling due to symbDescription

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1394]
_Migrated from #1391_ The current blank SRS .tex file doesn't compile because the following lines:
```tex
\newlist{symbDescription}{description}{1}
\setlist[symbDescription]{noitemsep, topsep=0pt, parsep=0pt, partopsep=0pt}
```
require both of the following packages, which aren't included in the empty document:
```tex
\usepackage{enumitem}
\usepackage[backend=bibtex]{biblatex}
```

`symbDescription` should only be defined in the preamble when it's used, which is only used when there are `ConceptInstance`s present. (Unless @smiths, @JacquesCarette, or others have other ideas.)

**Comment by samm82** [comment]
Fixed in `projectile` branch - no PR yet.

**Comment by JacquesCarette** [comment]
This does seem like a straight bug that should be fixed. I'll take a look at your PR soon.
