### ISSUE TITLE
Projectile Code Review

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1395]
As I mentioned on the [Projectile wiki page](https://github.com/JacquesCarette/Drasil/wiki/Projectile-Example), I used the generated GlassBR code as a guide to develop source code for Projectile (found in the [src/](https://github.com/JacquesCarette/Drasil/tree/projectile/code/drasil-example/Drasil/Projectile/src) folder in Projectile). Let me know if there are any issues you find.

This was just a first pass, so in the future, (at least) the following will be variable:
- Input Format
- Output Format
- Units
- Planet (Gravitational Constant)
- Criteria for Hit

I think this is mostly a question for @smiths, but would automating the test cases (ie. with pytest) be a good idea at this point?

**Comment by bmaclach** [comment]
The code looks good to me. Note that what you have currently is great as one "version" of the code. When you say that, in the future, Input Format etc. will be variable, you should do that by writing an entirely new "version" of the program, rather than by updating your existing program. What we want is a family of similar programs. So you could write another "version" of the program where, for example, the output format is a graph, and yet another "version" where the user of the program decides at run time whether they want graph or textual output (thus changing the decision on output format from compile time to run time).

**Comment by JacquesCarette** [comment]
Most definitely adding test cases and automating them is good!  And I agree with all of @bmaclach 's comments as well.

**Comment by smiths** [comment]
I agree with @bmaclach and @JacquesCarette.  I definitely like the idea of automating test cases, but I don't think we currently have the infrastructure for that.  We should definitely aim for this though.  It would be great to have an example (even a small example) that does everything.  😄

**Comment by samm82** [comment]
Would the end result of this example involve building each variant of the program when running `make`, with each one being in the stable for Projectile, or would we choose a default to build with `make`, and passing in params would change the built variant (and the location to look for the corresponding stable version)?

**Comment by Mornix** [comment]
I would assume it would be similar to how SWHS and NoPCM are split at the moment. Where each variant would have its own “example” and respective stable and build folders so the entire SRS, ???, and code “chain” is specialized for the given variant. 

@smiths and @JacquesCarette may have a different idea as i wasn’t around for the SWHS, NoPCM “split” so I’m not sure if that was a conscious decision made to organize it that way.

**Comment by samm82** [comment]
@Mornix  Given that there will be a lot of different variants (ie. # of input formats * # of output formats * # number of planets * ... ) I don't think it's feasible to have a separate example for each one. If I'm correct, my idea of it is that passing in different parameters in the Main.hs file will generate different documents, with the specified variabilities selected.

**Comment by JacquesCarette** [comment]
We'll probably end up wanting to generate a (deterministic) 'sampling' of members from the family. Our infrastructure is most definitely not ready for that. But that's fine, we'll get there.

**Comment by JacquesCarette** [comment]
And these should be considered "members of a family" instead of semi-separate examples, like SWHS and NoPCM.

**Comment by smiths** [comment]
It is great that we are thinking about variabilities, but it is probably better to get one family member working first.

**Comment by samm82** [comment]
That was my thought process, too @smiths
