### ISSUE TITLE
FReqsSub Should take [ConceptInstance]?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1403]
_Related to #1023, as well as #1229 and its bunny trail of related issues._ (Not sure if there is already an issue specifically for this, but I couldn't find one.)

I was about to implement the Requirements for Projectile, but realized that it would probably make more sense to revise this code before adding another example that will break it.

https://github.com/JacquesCarette/Drasil/blob/8d0bbbea5633ce5c7a43f487757562ddca5d21b9/code/drasil-docLang/Drasil/DocumentLanguage.hs#L197-L199

Since `NonFReqsSub` was refactored to take a `[ConceptInstance]`, it makes sense that `FReqsSub` should be as well.

I don't want to step on anyone's toes, so @bmaclach, @Mornix, @JacquesCarette, @smiths, and/or anyone else feel free to let me know if this issue should be reassigned, pushed to later, or tackled now.

# TODO
- [x] GamePhysics
- [x] GlassBR
- [x] NoPCM
- [x] SSP
- [x] SWHS
- [x] Replace `FReqsSub` with `FReqsSub'`

_Closed with merge of #1461_

**Comment by smiths** [comment]
@samm82, your proposal makes sense to me, under the assumption that fixing FReqsSub will not take much time.  We don't want to introduce code that we know will eventually need to be changed, but we also don't want to get distracted from advancing on our complete projectile example.  😄

**Comment by samm82** [comment]
I'll put this on the back burner for now 😉

**Comment by samm82** [comment]
@smiths Would it be an acceptable compromise for me to create a new `FReqsSub'` that takes a `ConceptInstance` for adding the requirements to Projectile, then I (or someone else) can come back to this issue and finish the job?

**Comment by smiths** [comment]
@samm82 that sounds reasonable to me.

**Comment by samm82** [comment]
A note - `FReqsSub'` should be modified to also take a `[LabelledContent]` for the tables.
