### ISSUE TITLE
Move changes from gamephy_Impulse to new branch

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1404]
gamepy_impulse branch has issues with travis build because the branch was not created from a fresh master. The impulse derivative code works fine on my local and just need to be copied to a new branch to fix travis build errors.  I will assign this to @vajihehm, if this is okay with you @smiths.

**Comment by smiths** [comment]
In principle, I like the idea of distributing work to others, but I'm not sure of the rationale for assigning this to @vajihehm.  Given your expertise on the game physics example, doesn't this make more sense for you to assign to yourself @oluowoj?

**Comment by oluowoj** [comment]
well because she is free for now and the code is already done by me its just to copy to a new branch and build but that's okay, I will assign to myself and put on my to do list. Thanks
