### ISSUE TITLE
More meaningful names in SWHS GenDefs

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1409]
SWHS GenDefs.hs could use more meaningful names in its derivations and descriptions.

https://github.com/JacquesCarette/Drasil/blob/540f209ea7b8f994cd0eeb2efa1c8e47b0d8881d/code/drasil-example/Drasil/SWHS/GenDefs.hs#L122-L174

There's a good chance this is mentioned somewhere already, but I couldn't seem to find it.

**Comment by smiths** [comment]
@danscime I'm surprised that these bad names are still in the SWHS example.  Issue #708 was to address this, and that issue was closed.  I guess a few bad names slipped through.  We certainly do want to fix this.
