### ISSUE TITLE
"Continuous Deploy" Website

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1412]
As part of #1305, the easiest way to access this online documentation and examples is through a website which is generated as part of the CI deploy process.

I haven't yet completed the script to upload the generated fils and code onto a `gh-pages` branch, but I'm envisioning that part of the process is calling a static-site generator on a set of HTML templates and parameterizing them with the appropriate content such as example names, paths to the PDF and HTML versions of their SRS, a link to a directory of generated code (not sure how this should be formatted or if it should link to a GitHub file in the repo), packages, and package documentation to name a few.

As the last paragraph hinted I haven't worked out much of how to display this information or which static-site generator to use. I'm familiar with Python's [Jinja2](http://jinja.pocoo.org/docs/2.10/) templating, however haven't used common generators like [Pelican](https://docs.getpelican.com/en/stable/) (which seems more blog-oriented). From 30 seconds of searching I found a Haskell library which does static-site generation: "[Hakyll](https://github.com/jaspervdj/hakyll)" which I haven't looked into. 

The first thing to do with this is to find an appropriate static-site generator (or maybe just an HTML templating library is more appropriate for our use case?) I personally would like to stick with Python (since it's already part of CI), or Haskell, although @JacquesCarette may have some opinions on that.

Next step would be to figure out a page hierarchy (if any — although there likely will be) for navigation purposes. 

And the final step will be to make the web pages which point to the content. 

I'm going to make a quick list of artefacts which will be "pushed" to the website:
* List of packages (possibly with links to that "folder" on GitHub)
* Links to the generated Haddock documentation
* Examples (really their name since there are a few artefacts)
* Link to the SRS PDF
* Link to the HTML SRS
* Link to GitHub with any generated code? 

@smiths and @JacquesCarette might have some comments on what I've laid out or artefacts (more generally things) which should be part of the continuous deploy website.

**Comment by JacquesCarette** [comment]
I would lean towards trying Hakyll as a first go.

**Comment by smiths** [comment]
Thank you for creating this issue @Mornix.  It is a good starting point for sure.  I don't have much to add, just that we will want to be able to add other generated documents in the future, besides the SRS and the code.  For instance, there will be some kind of design documentation and possibly a verification plan and report.

**Comment by danscime** [comment]
Connected to  #1412

**Comment by Mornix** [comment]
Continuous Deploy is implemented with #1474. Closing.
