### ISSUE TITLE
Duplicate descriptions and equations in NoPCM

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1418]
Some descriptions and equations are created in both Body and GenDefs of NoPCM. They should only be created once and then referenced. I believe they should be created in GenDefs.hs.

Body:
https://github.com/JacquesCarette/Drasil/blob/26d7637b91be5509b1f744c50514a474fdcc79e9/code/drasil-example/Drasil/NoPCM/Body.hs#L412-L451

GenDefs:
https://github.com/JacquesCarette/Drasil/blob/26d7637b91be5509b1f744c50514a474fdcc79e9/code/drasil-example/Drasil/NoPCM/GenDefs.hs#L53-L101

**Comment by JacquesCarette** [comment]
Well spotted - and agreed!
