### ISSUE TITLE
Make no longer copies GlassBR .txt files to src folder

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1424]
As of #1346, the .txt files in datafiles/glassbr no longer get copied to the src folder for each language. The files are input.txt, TSD.txt, and SDF.txt. They should get copied into each of the 4 language directories in build/GlassBR/src. 

I see the rule for doing the copying is still there in the Makefile, and still works if I do `make glassbr_prog`, but I guess the rule is not getting triggered on a regular `make` command?

**Comment by Mornix** [comment]
I see the issue. Accidentally substituted the wrong variable. PR will be up in 20.

**Comment by Mornix** [comment]
It looks like I changed the `Makefile` to only copy the text files “just-in-time” for compilation. This is bad judgement on my part to remove it from the general `make` Since it leaves GlassBR’s code directories incomplete.
