### ISSUE TITLE
Add Physical System Description Section to Projectile

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1430]
This section includes a figure of the problem, which is:

![projDiagram](https://user-images.githubusercontent.com/35857611/58510690-4cb42600-8167-11e9-9ec1-e252605e73bf.png)

We might also want to add the positive directions (up and to the right) at some point.

**Comment by samm82** [comment]
How's this for a physical system diagram? @smiths @JacquesCarette @bmaclach 

![projDiagram](https://user-images.githubusercontent.com/35857611/58510690-4cb42600-8167-11e9-9ec1-e252605e73bf.png)

**Comment by JacquesCarette** [comment]
Looks good to me.

**Comment by bmaclach** [comment]
I agree, looks good.

**Comment by smiths** [comment]
Yes, looks good to me too.  We might also want to add the positive directions (up and to the right), but let us hold off on that.  I'd like to see how everything fits together before complicating your figure.
