### ISSUE TITLE
Consistency in Input Requirements Tables

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1440]
This came up in a roundabout way from #1390, but the input requirements table (if present in an example) should be made consistent and moved (to `docLang` - `Requirements.hs`)? I'm personally fond of GlassBR's representation. The differences are the headers and the order of the columns. Thoughts? @smiths @JacquesCarette 

![glassBR](https://user-images.githubusercontent.com/35857611/58582324-7d579680-821f-11e9-8057-83d9d94d14ba.png)
![ssp](https://user-images.githubusercontent.com/35857611/58582344-8ba5b280-821f-11e9-996a-cdcc9fa77dab.png)
![swhs](https://user-images.githubusercontent.com/35857611/58582359-93655700-821f-11e9-96f0-ace094af8bf6.png)

**Comment by smiths** [comment]
@samm82, I agree that consistency is important between our examples at this point.  In the long run, we should view the format of this table as part of a user's recipe.  Some might prefer or require a specific view of the information.  For now though, let us aim for consistency.

Would it be possible to present this information in the same way that it is presented in the table of symbols?  I believe for the table of symbols the order is Symbol, Description, Unit.  The table of symbols also has the nice formatting feature that it doesn't have a horizontal line between each row.  This really does look much nicer.  :smile:

**Comment by JacquesCarette** [comment]
I'm guessing that by making this all uniform will end up reducing the overall amount of code. A Good Thing.
