### ISSUE TITLE
NoPCM Inputs

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1450]
Some of the inputs to NoPCM aren't included in the inputs field of the `SystemInformation`. Specifically, `timeStep`, `rel_tol`, `abs_tol`, and `cons_tol` are inputs but are not included in the `SystemInformation` for NoPCM. Also, `tau` is mistakenly included as in input in DataDesc.hs instead of `timeStep`. This breaks the generated code.

**Comment by JacquesCarette** [comment]
There is surely a bigger lesson than just this issue to be learned from this.

**Comment by bmaclach** [comment]
@JacquesCarette That Drasil shouldn't allow conflicts between the stated inputs and the input file format definition?

In terms of a lesson related to forgetting to state some inputs, Drasil already throws an error if it can't figure out how it can get from input -> output based on the given inputs and definitions. I'm wondering why that error wasn't thrown here...

Okay I just investigated, and it's because none of the missing inputs are explicitly used in any of the equations for calculating the outputs. The absolute and relative tolerances and time step are passed to the ODE solver and `cons_tol` is used when verifying that the output follows the law of conservation of energy. Maybe we need to teach Drasil that if an ODE solver is being used, tolerances and step sizes are required, and if we are checking a property of a correct solution (like adherence to the law of conservation of energy, in this case), a tolerance is again required.

**Comment by JacquesCarette** [comment]
Yes, this kind of stuff.  Any argument passed to the ODE solver should be considered used, and so should be checked to make sure they are present. Same goes for checking a property, but the details matter, so that may be slightly trickier.

**Comment by bmaclach** [comment]
Issues #1497, #1499, and #1500 created for the improvements discussed above. This issue will be closed with the merge of #1496.
