### ISSUE TITLE
Code generation: derived_values always called with a parameter even if it takes none

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1451]
The call to derived_values in generated Control modules is hardcoded to call derived_values with the input parameters object as a parameter. However, if there are no derived values, then the function takes no parameters (and does nothing), so in this case the generated call to derived_values throws an error.

Some pontential fixes:
1. Modify generation of derived_values so that derived_values always take a parameter
2. Modify generation of the Control module to call derived_values with the correct parameters
3. Modify the code generation such that, if there are no derived values, the DerivedValues module and function do not get generated at all, nor does the call to derived_values in the Control module.

I lean towards option 3 unless we have a reason to generate a DerivedValues module even when it does nothing? @JacquesCarette @smiths

**Comment by smiths** [comment]
I agree on option 3.  The notion of DerivedValues is an organization convenience for the human beings.  We might choose to have modules that don't make this kind of distinction.

**Comment by JacquesCarette** [comment]
Definitely number 3. And we need to do it in such a way that this is a 'core feature' of the code generation -- when something that can be absent is indeed not there, there are no traces left of its presence in the generated code.

Note that the easiest way to achieve this is likely pre-GOOL.

**Comment by bmaclach** [comment]
There are a few steps that need to be done for this:
- Recognize when there are no derived values - This can be easily done because there is a `derivedInputs` field in our `CodeSpec` record. We simply check if the list is empty.
- If there are no derived values, do not generate a `derived_values` function or DerivedValues module.
- De-hardcode the dependency of the Control Module on the DerivedValues module. Only add this dependency if the DerivedValues module really exists.
- De-hardcode the call to `derived_values` in the Control Module. Only perform this call if there are derived values.
- If there are derived values, de-hardcode the parameters passed to the `derived_values` function when it is called. These should be determined dynamically.

And we want to do all of this in such a way that modules other than DerivedValues that are "optional" can be left out or added in easily - the only difference between derived values and other potentially absent functions/modules is the condition to check which determines whether or not the function/module should exist.

I've been thinking through this and I think our problems stem from the hard-coded hacks in our `modExportMap` and `modDepMap`:

https://github.com/JacquesCarette/Drasil/blob/a75925ca802f861e51edd5da480372d74b721f8f/code/drasil-code/Language/Drasil/CodeSpec.hs#L237-L243
https://github.com/JacquesCarette/Drasil/blob/a75925ca802f861e51edd5da480372d74b721f8f/code/drasil-code/Language/Drasil/CodeSpec.hs#L249-L258

For example, the existence of `derived_values` is hard-coded here, but we know that in some cases it should not exist. Why are these hacks necessary? Because we are trying to fully build these Maps prior to generating GOOL code, but at that point we don't have all of the information we need. So we hard-code some of it in. 

## De-hard-coding the module export map

__Option 1 - Fully build the map before generating any code, like we do now, but pass in all the information we need to minimize hard-coding__

The `CodeSpec` record already contains the list of `derivedInputs`, so it would be very easy to simply set up a condition where the `derived_values` function is only included in the export map if that list is not empty. 

But we would still need to de-hard-code the module to which the function belongs. To do this, we will need more information available when creating our `CodeSpec` record. Currently we do not pass in our `Choices` record to the function that creates our `CodeSpec` record. If we did pass in `Choices` (and I don't see anything stopping us from doing this), then we could determine to which module the `derived_values` function should belong. For example, given our current choice of either `AsClass` or `Loose` input structure (a decision that is captured in the Choices record), we could assign `derived_values` to either it's own module (if `AsClass` chosen) or to the `InputParameters` module (if `Loose` chosen).

The hope here would be that the `Choices` record, along with the `SystemInformation` gives us enough information to determine, before generating any code, which functions we will need to generate, and which modules each function belongs to.

When it comes time to generate the code, the complete module export map could be used as a guide to determine which functions to generate. For example, if `derived_values` is not in the module export map, it does not get generated.

A downside here is that the function name `derived_values` will still be hard-coded, if it exists. This doesn't seem like a big problem to me, but it's always something we could always add more flexibility down the road. 

__Option 2 - Build the export map in parallel with generating code for the modules__

This option would have our module export map grow as we generate more functions/modules. We start with modules at the bottom of the Uses hierarchy (we would need to know this hierarchy beforehand - that might present a problem, or it might not. For the types of software we currently generate, this hierarchy is rather consistent - Control is always at the top, Input always at the bottom, Calculations and Output in between). We build a module, and add each function/variable it exports to the export map. Then we move to the next module. If we work our way up the Uses hierarchy, each module should only reference functions/variables from other modules that have already been generated, and therefore are already captured in the module export map. 

The benefit to this option is that we don't need to pass in `Choices` when creating our `codeSpec`, we only pass it in to the code generator itself (which is already what we do anyway). 

A main difference between option 2 and option 1 is that option 1 creates the module export map first, which then dictates which code gets generated, whereas option 2 generates the code for a function first, and then adds that function to the module export map.

## De-hard-coding the module dependency map

My proposal for this is simply to remove the module dependency map altogether. If we have a working, complete module export map, then any time a module uses a function/variable that exists in the export map, we could add the module containing that function/variable to a list storing the dependencies of the module we are generating, then just pass that list in to the GOOL function for generating a module. Other modules don't care about the dependencies of other modules, so there's no reason to store such a map in our `CodeSpec` record.

## De-hard-coding the call to derived_values

When we are generating the Control module, we will check to see if `derived_values` exists in the `modExportMap` (this will again mean "derived_values" must be locked in as the name for a function for calculating derived values, if it exists). If it does not (which will only happen if there are no derived values) we don't generate the call. If it does, then we call the function.

## De-hard-coding the parameters of the call

What we call "derived values" are values that can be immediately calculated from inputs and constants, so we would expect this function to only take inputs or constants as parameters. So we can check the definition for each derived value. If the definition refers to an input, we pass in the inputs object. Or, in the case where we've made the decision that the inputs are not bundled in an object, we pass in the specific inputs that are required. If the derived value definition makes reference to a constant, we pass in the constant. Or, if we've made the decision that all constants are inlined, we don't need to pass in anything for the constants.

Thoughts/feedback? @JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
First: `CodeSpec` was built "to make things work", and contains many hacks. So this is not surprising.

On the choices: definitely option 1. I think we'll (eventually) be able to not hardcode so much, but let's do that incrementally.

For now, I see no problem with just removing the dependency map. We'll eventually want to be able to generate it, but that can happen when things have settled.

Rather than having a fixed `Control` module, I think wrapping things in `Maybe` and then using `maybeToList` will scale better than if-then-else logic.

De-hard-coding the parameters of the call seems good as is.

**Comment by smiths** [comment]
I don't have anything to add about our steps forward, but I do want to point out that I really like the way you @bmaclach laid out the options (https://github.com/JacquesCarette/Drasil/issues/1451#issuecomment-499989429).  I'm sure you are already doing this @bmaclach, but you should keep track of explanations like this; they will be invaluable when you are writing up your thesis.
