### ISSUE TITLE
NoPCM Code Generation: Input_constraints broken

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1452]
Constrained unitals in NoPCM reference other unitals for their bounds. For example, a constraint for `tank_length` is `Bounded (Inc, sy tank_length_min) (Inc, sy tank_length_max)`. Since `tank_length_min` and `tank_length_max` are not passed to `SystemInformation` in any way, code generation does not know about them and the generated code for the InputConstraints module does not work. 

I think it makes sense to pass these (and all the other `min` and `max` unitals in NoPCM used for constraints) to the constants field of the `SystemInformation`. This would fix the generated code.

**Comment by JacquesCarette** [comment]
Definitely! Even better would be if these were collected automatically.

**Comment by bmaclach** [comment]
Created #1504 for the automatic collection issue.
