### ISSUE TITLE
Variable names with Greek characters in generated code do not work in Java, C++

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1454]
In the generated code for NoPCM, the variable for the water density is called `ρ_W`. The use of a Greek character in a variable name causes errors in Java and C++.

Variable names for quantities with Greek letter symbols should spell out the greek letter to avoid these errors. For example, this variable should be called `rho_W`.

**Comment by Mornix** [comment]
C++ spec mentions that Unicode should be allowed in variable names. It looks like Clang and MSVC support UTF-8 identifiers, but GCC does not.

**Comment by JacquesCarette** [comment]
This is also why we have the feature that symbols can have 2 names, a specification-time name and a code-time name. I forget the details, but that's definitely the feature to use here.
