### ISSUE TITLE
Duplicated function in NoPCM generated code

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1455]
In the Calculations module for NoPCM generated code, the function for calculating q_C is generated twice, which causes errors in Java, C#, and C++. I think this is happening because the definition for q_C is included in `SystemInformation` in both the `datadefs` and `definitions` fields. It should only be included in one of them.

**Comment by JacquesCarette** [comment]
This also calls for a "sanity" check in Drasil somewhere, to make sure that fields that should be disjoint are, so that this doesn't re-occur.

**Comment by bmaclach** [comment]
Created #1506 for the "sanity" check.
