### ISSUE TITLE
Generated Figure Sizes

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1456]
When the specified width of a figure is 100%, it just displays the image normally, instead of scaling it by the size of the window. This results in some large images:

![L A R G E](https://user-images.githubusercontent.com/35857611/58586773-d4626900-8229-11e9-9dbb-a138303bc993.png)

@smiths mentioned "I definitely like it when the figures are scaled. It makes are generated documentation look much nicer and professional. I agree with the idea of having to specify the width. However, we want to avoid documentation generation details for the user, if at all possible.... Is there a way to automate the scaling, at least by default?"

I think a solution to this would be to create a 
```haskell
data WidthType = Actual | PercWidth Int
```
and one single `fig` constructor that would take a `WidthType`. Then, we could explicitly use the actual size of the image, or a specified percent width.

@smiths also mentioned that @Mornix might have something to say about this. Any thoughts?

_From #1410_

**Comment by Mornix** [comment]
I think this issue is more a regression. It worked previously (I believe). I took a look and it appears that the generated HTML was updated, but the companion CSS was not causing the CSS to no longer apply. Fixed in bd5f0b2
