### ISSUE TITLE
Section Name: Existing Solutions or Off The Shelf Solutions?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1457]
While working on making things more consistent, I noticed that sometimes the section is referred to as "Existing Solutions" and sometimes as "Off The Shelf Solutions". Which is preferred?

**Comment by smiths** [comment]
Thank you for your question @samm82.  When you see an inconsistency in the examples, a good place to look to resolve the inconsistency is to the original template.  (I mentioned the specific Smith/Lai/Khedri papers in a recent comment under #1428).  The original papers use "Off The Shelf Solutions."  I haven't checked, by my memory is that this section is inspired by the Volere template.  (I know we didn't invent it, but borrowed from existing best practices.)

There is nothing extra special about the first proposed template; it makes sense that changes should be made over time.  However, the changes should be made for a good reason.  I don't see any compelling reason to change the title of this section to "Existing Solutions."  I think this is a change that just slipped in, like the past use of use cases in GlassBR.

In retrospect, I should have emphasized to former students that they shouldn't change the template.  I also should have reviewed with this criteria in mind.  One of the nice things about Drasil is that people won't feel that they have the freedom to arbitrarily change the section headings.  😄 

Please go ahead and create an issue to fix this inconsistency in the examples.

**Comment by samm82** [comment]
Didn't even think to check the original 😬 Thanks!

**Comment by smiths** [comment]
Don't worry about not checking the original.  I haven't been in the habit of checking it either, and I wrote it.  😄
