### ISSUE TITLE
Uniform naming throughout examples

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1459]
Make naming of similar functions more consistent throughout examples.

Example:

https://github.com/JacquesCarette/Drasil/blob/f4e9058ccd4ab61a50e9d32966e7a51d06c717b4/code/drasil-example/Drasil/SSP/Body.hs#L95-L118

https://github.com/JacquesCarette/Drasil/blob/f4e9058ccd4ab61a50e9d32966e7a51d06c717b4/code/drasil-example/Drasil/HGHC/HGHC.hs#L29-L49

Naming of the system informations are not consistent.

**Comment by smiths** [comment]
Yes, consistency of naming conventions is desirable.  This isn't something that Hlint picks up because the first example isn't using camelCase?

**Comment by danscime** [comment]
Hlint picks it up and it is being fixed.

This issue more focuses on the fact that one module names its  System Information "si" and another module "thisSi".

**Comment by smiths** [comment]
Thanks @danscime.  I was focusing on the wrong difference.  😄  I like the simpler, shorter, name better, but my overriding preference is consistency.

**Comment by JacquesCarette** [comment]
I agree with @smiths .
