### ISSUE TITLE
Changes to take [ConceptInstance]

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1471]
I see that work has been started to make an `LCsSec'` constructor to take a `[ConceptInstance]`, and I couldn't find who was working on it. @smiths @JacquesCarette @Mornix Anyone know who was working on this, and can I continue the work on it?

Likely changes has been started, so I'll continue it, taking inspiration from the work I did on the FRs and NFRs, and I'll also do the unlikely changes.

**Comment by samm82** [comment]
Also, if this gets approved, should I create a new file in Sections in `docLang` called "Changes"?

**Comment by JacquesCarette** [comment]
I don't remember - I don't think this is being actively worked on.  Use 'git blame' maybe to see who wrote some of that code?

**Comment by samm82** [comment]
It looks like it was @Mornix who last worked on it, but unless he has any complaints, I think I'll start (continue) this.

**Comment by Mornix** [comment]
It predates me. The change I made was strictly for HLint. It looks like it was added as part of the traceability stuff Yuzhi did. But either way, going ahead with this is fine with me.

**Comment by samm82** [comment]
Yeah, I probably should've actually looked at what the change was - I just saw "Mornix" and figured the work seemed up your alley. 😁
