### ISSUE TITLE
Update SWHS Stable to Match Manual

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1472]
In looking at the web version of SWHS on the continuous deploy page (from @Mornix), I was surprised to see that several issues with stable were never fixed.  @samm82, can you please go through the manual version:

https://github.com/smiths/swhs/tree/master/docs/SRS

and look up the \wss comments.  The comments show as blue in the pdf file.  For each comment, please create an issue, with screen shots showing the problem.  I think this issue has hung around so long because attempts were made to tackle it with huge issues.  I would like this sorted out so that I can have confidence that the stable version hasn't lost information.  By breaking it into separate issues, we can make sure that a full discussion is had for any of the nontrivial differences.  For the trivial differences, we'll be able to close the issues quickly.

If you have any questions, please let me know.

**Comment by samm82** [comment]
Just to clarify, this is for instances where there is a difference in information, not arbitrary display differences, correct?

**Comment by samm82** [comment]
I'm also going to make a separate branch for minor typos/grammar, and I'll only make issues for the branch if you think I should (as each fix will be super small 😂).

**Comment by samm82** [comment]
I've opened a PR for the minor fixes (#1495) and split this issue into multiple, so I'm closing this issue.

**Comment by smiths** [comment]
Okay.
