### ISSUE TITLE
Printing helpers duplicated between packages

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1477]
The `drasil-code` and `drasil-printers` packages define some of the same helper functions for printing. Common helper functions should be pulled out and shared between the packages. Some examples are `oneTab` and `capitalize` in `drasil-code`:
https://github.com/JacquesCarette/Drasil/blob/eb57dc86cfdcfdc1616af7ba076e916fc600a958/code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs#L25-L26
https://github.com/JacquesCarette/Drasil/blob/eb57dc86cfdcfdc1616af7ba076e916fc600a958/code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs#L46-L48

And `indent` and `capitalize` in `drasil-printers`:
https://github.com/JacquesCarette/Drasil/blob/eb57dc86cfdcfdc1616af7ba076e916fc600a958/code/drasil-printers/Language/Drasil/Printing/Helpers.hs#L35-L37
https://github.com/JacquesCarette/Drasil/blob/eb57dc86cfdcfdc1616af7ba076e916fc600a958/code/drasil-printers/Language/Drasil/Printing/Helpers.hs#L51-L54

(The `capitalize` functions are slightly different but perhaps they don't need to be. Further investigation of where they are used is required.)

**Comment by JacquesCarette** [comment]
`drasil-utils` ? And possibly `Drasil.Utils.Document` and `Drasil.Utils.English` ?
