### ISSUE TITLE
SWHS: Missing Hat for Unit Outward Normal in GD Derivation

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1480]
In the derivation for the Simplified rate of change of temperature GD, **n** is called a unit vector, and in the manual it has the "hat":

![manual](https://user-images.githubusercontent.com/35857611/58901851-f5b2d180-86cf-11e9-87ed-5e542115b280.png)

but it doesn't in the stable:

![stable](https://user-images.githubusercontent.com/35857611/58901875-02cfc080-86d0-11e9-9e0c-dd4a17675780.png)

The hat denotes unit vector, so there should be a hat in Drasil, correct?

**Comment by JacquesCarette** [comment]
hat denotes vector, not unit vector, AFAIK. But in this case, n turns out to be a unit vector.

**Comment by samm82** [comment]
I thought bold denoted a vector? When defining a symbol in `Quantites.Physics` for Projectile, using `vec` makes it bold. @JacquesCarette

**Comment by smiths** [comment]
Yes, @samm82, we add the hat to show that a vector is a unit vector.  Bold means vector, while bold with a hat means unit vector.  (https://en.wikipedia.org/wiki/Unit_vector)  

If we can add the hat to Drasil, that would be great.

**Comment by samm82** [comment]
The hat is already in Drasil, so unless we care about updating the manual, this issue can be closed.

**Comment by smiths** [comment]
I thought stable was missing the hat?

**Comment by samm82** [comment]
Wow - I'm not sure what happened, but both stable and Drasil now have the hat. Sorry for this trainwreck of an issue 😂

**Comment by JacquesCarette** [comment]
My bad, I mis-remembered.
