### ISSUE TITLE
SWHS: Additional Information about Quantities in DD

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1483]
In manual, this the symbol description contain more information about the quantities than Drasil does:

![manual](https://user-images.githubusercontent.com/35857611/58902761-be452480-86d1-11e9-8e8e-2d0e2598b782.png)

Drasil:
![drasil](https://user-images.githubusercontent.com/35857611/58902809-e6cd1e80-86d1-11e9-9e63-cc2ebca8067b.png)

This could potentially be more difficult, since I'm guessing these descriptions come from the concepts defined in `drasil-data`, but should this additional information be added to Drasil?

**Comment by smiths** [comment]
@samm82, I suggest that we add a Note to this DD to capture the information that is lost with the generic definitions.  There isn't much information lost, but I think just giving the equation isn't enough to teach anyone what is going on.  For the note field, I suggest something like:

The specific latent heat of fusion (also known as the enthalpy of fusion) of a substance, is the heat energy required (Q) to change the state of a unit of the mass (m) of the substance from solid to liquid, at constant pressure.
