### ISSUE TITLE
SWHS: Missing DDs in Drasil

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1484]
The following DDs are present in manual but missing in Drasil. Should they be added? I think they are supposed to be present, since they are referred to, but the references point to different locations, since the DDs aren't defined.

![dds](https://user-images.githubusercontent.com/35857611/58903090-88ed0680-86d2-11e9-80f9-f1e9b5ac9ecd.png)

EDIT: As in the "RefBy" field, these will need to be referenced in IM1.

**Comment by smiths** [comment]
@danscime added tau_P^S and tau_P^L via #1070, but it does look like "plain" tau and eta have not been added.  I'm surprised that they were missed, but I just looked in stable and you are right that they aren't there.  Strange.  Glad you are going to update the documentation @samm82.
