### ISSUE TITLE
SWHS: Equalities in IM Constraints

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1487]
_Similar to #1485_
In the manual version, constraints are inclusive

![image](https://user-images.githubusercontent.com/35857611/58905743-77a6f880-86d8-11e9-9597-cac15b4774b5.png)

(The one exception is this constraint in IM2 and IM4): 
![image](https://user-images.githubusercontent.com/35857611/58905977-f69c3100-86d8-11e9-8997-f7077aebe49f.png)

While they are exclusive in Drasil:

![image](https://user-images.githubusercontent.com/35857611/58905718-6827af80-86d8-11e9-9fd3-1e12ea9cc233.png)

The manual version is correct and Drasil should be updated.

**Comment by smiths** [comment]
The manual version is correct in all instances.  I'm glad that you are catching these, but I'm disappointed in whoever first translated the work to Drasil.  There was definitely some inattention to detail.  :-(

**Comment by samm82** [comment]
Thank goodness that the manual version is correct 😂😂 I was afraid I was going to have to upload a picture of each instance and not confuse everyone involved!

**Comment by smiths** [comment]
I agree @samm82!  and I have no interest in reviewing each of these changes.  I reviewed them when the manual version was written.  For some reasons arbitrary changes were sometimes made in the translation to Drasil.
