### ISSUE TITLE
SWHS: Minor Diff in Properties of Correct Solution

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1492]
In the manual, the Props of Cor Sol section has a % and a reference to the requirement:

![manual](https://user-images.githubusercontent.com/35857611/58912030-2baf8000-86e7-11e9-9328-07680b64a43e.png)

but this isn't there in Drasil:

![drasil](https://user-images.githubusercontent.com/35857611/58912081-4c77d580-86e7-11e9-9efc-6ccb0b04857f.png)

EDIT: The percent sign is also missing in the related requirement.

**Comment by smiths** [comment]
Good catch!

**Comment by samm82** [comment]
Apparently the requirement is already there in the HTML, but isn't in the LaTeX, because the percent sign starts a comment 😂 I'll represent the value as 0.00001 instead of 0.001% for now until I figure out _C<sub>tol</sub>_.

**Comment by JacquesCarette** [comment]
Indeed - it's a special character that should never occur in `String`s destined for the latex printer. That would be another consistency check to do. Please add an issue for that.

**Comment by samm82** [comment]
Made in #1534
