### ISSUE TITLE
Disallow conflicts between inputs and input file format definition

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1497]
As mentioned in #1450, we had made a mistake in our definition of NoPCM's input file where it included a variable `tau` that wasn't actually an input, and was missing the actual input variable `timeStep`. This mistake went undetected for some time. 

Drasil should catch such conflicts between inputs and input files. This could be done by collecting the unitals used in the input file, comparing them to the inputs, and throwing an error if there is a difference. 

Another possibility is to prevent such mistakes from ever happening by reworking how we define input files. I am thinking that an input file format could be automatically generated based on some high-level choices and the known inputs (in the `SystemInformation`). Thus, the "user" of Drasil would not have to be responsible for ensuring all inputs from the `SystemInformation` are included in the input file, and it would be impossible for a non-input to make its way into the input file.

**Comment by smiths** [comment]
@bmaclach, the long term solution should definitely be the second thing you said.  Drasil should automatically know what inputs it needs.  The user could have freedom to specify the format of the files, or even more broadly, they could require command line input, or gui input.  However the inputs that are needed is already implicitly specified.  We shouldn't have to say it again.  

As an intermediate step toward full automation, can we use the information in the requirements?   I've made an effort (maybe not 100% successfully) to have each case study have a requirement that lists the required inputs.  (This requirement should also eventually be automatically deduced.)  :smile:  Can we use this requirement to generate code?

**Comment by bmaclach** [comment]
Your suggestion is actually not far off from what we already do. Currently the user defines a list of inputs which gets used to create the required inputs table for the requirement, and then also gets added to the `SystemInformation` which the code generator then uses. So the code generator doesn't use the requirement, but it gets the inputs from the same source as the requirement (at least, it should. I am not sure if all of the examples actually do it this way, though. I noticed that NoPCM had another, separate list of inputs which it used for the requirement, but I fixed it to use the same list everywhere in #1496).  

The missing piece is that the input list is not used to define the input file format.  The input file format is defined like this:
https://github.com/JacquesCarette/Drasil/blob/91d8bd66eff9ac4cddf59f7307d8cfe07ef6e797/code/drasil-example/Drasil/NoPCM/DataDesc.hs#L11-L39

Which seems too low-level to me. The downside to automating this, though, would be that the user doesn't control the order in which the inputs show up in the input file.

**Comment by smiths** [comment]
Thank you for the information @bmaclach.  If we automatically generated the format of the input file as an intermediate solution, I would like it better than the code you showed.  It looks like the format is one input per line.  We could pick the order the same as the order they are listed in the input table.

In the long run, we want to follow the program family approach.  The input format will be a variability.  How best to specify the format is something we haven't yet determined.

**Comment by bmaclach** [comment]
The input format for GlassBR is slightly different than one input per line:
https://github.com/JacquesCarette/Drasil/blob/7358f1f544e8a0c913e717ad4ebbb1751a4f9a23/code/drasil-example/Drasil/GlassBR/ModuleDefs.hs#L44-L58
However, I still like the idea of generating a one-input-per-line input file format as an intermediate solution. We will have to update the GlassBR input file to match that, but it will allow me to proceed with other tasks (like fixing the `Loose` input structure option #1453, which I believe is the last outstanding issue blocking NoPCM from compiling). So I'll proceed with that unless someone disagrees. @smiths @JacquesCarette

**Comment by smiths** [comment]
I agree with your plan @bmaclach.

**Comment by JacquesCarette** [comment]
Agreed.
