### ISSUE TITLE
Drasil should consider ODE solver parameters as required to get the output

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1499]
NoPCM and SWHS define quantities for absolute tolerance, relative tolerance, and time step. The purpose of these quantities is to pass them to an ODE solver. However, since they don't show up in any equations, Drasil would not recognize these as required inputs and thus would not throw an error if they were missing from the input list. Drasil should recognize that these ODE solver parameters are required inputs if an ODE solver is being used.

This is more something to keep in mind when teaching Drasil about ODEs (#473), not something that can really be fixed right now.

**Comment by smiths** [comment]
@bmaclach, what about using the requirements to get the inputs?  There is a requirement in the SRS for SWHS that lists the parameters you are mentioning.  The requirement is human generated, but it is one place where all of the information is given.  Maybe we can use that as a source of information, while we are waiting for Drasil's automation to check up?

**Comment by bmaclach** [comment]
@smiths Yes, that's how we are doing it now (or at least as of #1496). We have one `inputs` source, which is used for the requirement and everywhere else the input list is needed. This issue is more to address the possibility that the inputs were left out even in that one source.

**Comment by bmaclach** [comment]
Actually, #1496 updates NoPCM to have a single input list source, but SWHS still has separate lists. I'll create a different issue for that.

**Comment by JacquesCarette** [comment]
@bmaclach has your work on ODEs affected this in any way?

**Comment by bmaclach** [comment]
As of #2114, users need to construct `ODEInfo` objects including all of the parameters discussed in this issue. Our function that checks whether there is a path from inputs to outputs will now consider all expressions in `ODEInfo` objects, and if those expressions involve anything that is not known or cannot be computed, an error is thrown saying there is not a path from knowns to outputs. This can be closed.
