### ISSUE TITLE
SWHS conservation of energy tolerance treated as both an input and a constant

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1501]
SWHS lists C<sub>tol</sub> as a required input, defined as the "relative tolerance for conservation of energy".

However, in the requirement related to verifying that the output follows the law of conservation of energy, the tolerance is hardcoded as 0.001%.
![image](https://user-images.githubusercontent.com/18634568/58970078-b6938780-8786-11e9-81cc-4f6ad990d1e8.png)

The 0.001% is also hardcoded in the "Properties of Correct Solution" section. 

We should decide whether this is an input variable or a constant, and update the example accordingly. Even if it is a constant, I think it makes sense to still use the C<sub>tol</sub> symbol and then just add the value of that constant to the "Values of Auxiliary Constants" section?

**Comment by smiths** [comment]
@bmaclach good catch.  You are absolutely correct that the value 0.001% should not be hard-coded into the documentation.  I think we should make C_{tol} a constant, rather than an input.  When we get to thinking about program families, whether or not C_{tol} is compile time or run time could be a variability.

**Comment by bmaclach** [comment]
Closing this as it will be covered by @samm82 as part of #1494.

**Comment by samm82** [comment]
Should _A<sub>tol</sub>_ and _R<sub>tol</sub>_ also be constants (or variables in the future)? @bmaclach @smiths

**Comment by bmaclach** [comment]
@samm82 Those are the absolute and relative tolerances for the ODE solver. They need to be defined, but whether as an input or constant does not matter. I would lean towards keeping them as inputs just so that we don't need to change anything, but @smiths may have a different preference.

Note that there's been some discussion about how these should not be introduced until the design document (#1498), but for now, since we don't have a design document, I think we should keep them in the SRS.

**Comment by smiths** [comment]
I agree with @bmaclach.  The tolerances should be inputs, not constants.  We also should keep them in the SRS, because at the moment, we do not have any other options.  :smile:
