### ISSUE TITLE
All examples should have one source for inputs

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1502]
Some of the examples define their list of inputs in different places - usually one list of inputs to pass to the `SystemInformation` and another list to use in the functional requirement for accepting inputs. All examples should be updated such that the inputs list is only defined once, and is used everywhere it is needed.

- [x] GamePhys
- [x] GlassBR
- [x] NoPCM
- [x] SSP
- [x] SWHS

**Comment by smiths** [comment]
Good issue!

**Comment by bmaclach** [comment]
#1496, #1511, and #1540 close this issue.
