### ISSUE TITLE
Change HTML indent to 2 spaces

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1512]
I believe that at one point, we said that indent should use 2 spaces for stable just to display everything a bit more nicely. But the end goal is that the user can choose their amount of indent.

https://github.com/JacquesCarette/Drasil/blob/a75925ca802f861e51edd5da480372d74b721f8f/code/drasil-printers/Language/Drasil/HTML/Helpers.hs#L150-L151

**Comment by JacquesCarette** [comment]
Correct.

**Comment by danscime** [comment]
This indent size is now implemented.
