### ISSUE TITLE
What's in a Module?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1517]
Modules in GOOL are currently parameterized by:

- A `Label`
- A list of `Library`s for the other modules it uses, which need to be imported
- A list of `Statement`s
- A list of `Method`s
- A list of `Class`es

These all seem to make sense except for the list of `Statement`s. It seems like they were originally intended for variable declarations. Java and C# take the `Statement`s, convert them to `StateVar`s (and that seems really weird, like they shouldn't have been `Statement`s in the first place), and then throw them in a new `Class` along with the list of `Method`s (since, in these languages, everything needs to be in a class). Python just prints the `Statement`s as-is. C++  ignores them. The renderers for Lua, Objective C, and GOOL (which we haven't implemented yet in finally tagless) just ignore them.

I feel like we should just remove the `Statement` list from modules. I don't think we would lose any functionality, except perhaps the possibility of declaring variables outside of a class/function in Python, but I don't think that's a feature that is necessary (especially considering that right now Python is the only language that can do it out of the ones we render).

**Comment by JacquesCarette** [comment]
Agreed.
