### ISSUE TITLE
Store parameter data in State in the Reader during code generation

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1518]
With old GOOL, the name and type of a `Parameter` could be easily extracted from a `Parameter` by pattern matching. With finally tagless GOOL, we can't pattern match on a `Parameter` because it is really just a `Doc`. So in Imperative/Import.hs (the file responsible for generating GOOL code), whereas before we would pass around a list of `Parameter`s through all of the (Haskell) functions required to generate a (target language) function, we now pass through a list of `StateType`s (the parameter types) and a list of `Label`s (the parameter names) along with the list of `Parameter`s, so that all of the information is available to us when we need it. For example:

https://github.com/JacquesCarette/Drasil/blob/12602509222ab1662757a3026e7dbae9a1821137/code/drasil-code/Language/Drasil/Code/Imperative/Import.hs#L231-L240

`genInputDerived` passes them to `publicMethod` which passes them to `genMethodCall` which passes them to `loggedMethod`. This same flow happens in many places throughout the generator, just with a different starting point (for example, `genInputConstraints` instead of `genInputDerived`).

In reviewing this change, @JacquesCarette said "rather than passing more arguments, I'd stash them into the State in the Reader".

Each function we generate has a unique list of `Parameter`s, so we would have to have a different field in the `State` for each function we generate. Or maybe a Map of function names to Parameters, another map for parameter names, and another for parameter types? I'm not sure if I'm understanding this suggestion correctly, so I'm going to put the question label on here temporarily. @JacquesCarette I'm hoping you can expand on what you were hoping for here.

**Comment by JacquesCarette** [comment]
Hmm, I am not remembering the context of my comment well enough, so I am not able to expand on my comment with something more constructive. Can you link to where I made that comment?

**Comment by bmaclach** [comment]
@JacquesCarette It was an email conversation, so I can't link, but here are some direct quotes which should give the full picture:

From my original email:

"loggedMethod function was extracting stateType and Label from a parameter, can’t do that anymore so I had to get the state type and label from earlier and pass them through to the loggedMethod call... For sample code, look here:
https://github.com/bmaclach/Drasil/commit/87afc826f37608a1befe67c0be4117648253f324

All of this work was done in that commit, though there is also a little bit of "noise" not related to this specific topic. Specifically, look at the flow from genInputDerived -> publicMethod -> genMethodCall -> loggedMethod. Before, some Parameters were passed through all of these functions, and then StateTypes and Labels were extracted from them in loggedMethod. As I've mentioned before, with new GOOL we can't extract information from Docs. So I updated the code to get the StateTypes and Labels way back in genInputDerived, and pass those through all the other functions as needed."

And then your response was:

"At this level, all this code looks quite reasonable.  But rather than passing more arguments, I'd stash them into the State in the Reader. "

**Comment by JacquesCarette** [comment]
Yes, that is enough, thanks.

So I did mean that some of that information, i.e. those extra parameters, could be stored in the `State` in the `Reader` (but perhaps more easily inside key-value store supported by `Environment`).

**Comment by bmaclach** [comment]
So while working on #1451 I had to change our code for generating Parameters quite a bit and in the process I grouped Parameters with their name and type in a `ParamData` data structure, and then just passed that data structure around (replacing the 3 parameters described above with just one). Here's the work I did: https://github.com/JacquesCarette/Drasil/commit/0403ff1853a64272a214e45a8f15b696fac62a3e

Would you still prefer a Reader/Environment solution over this, @JacquesCarette? I looked at the `Environment` monad, and my worry is that all of the values (and all of the keys) need to be of the same type. If the plan was to replace our current `Reader`, that already presents a problem because our `State` record holds values of many different types. Unless you meant to keep the `Reader` but also make use of some `Environment`s within, where needed?

**Comment by JacquesCarette** [comment]
Nice!  In the long term, we'll probably want to re-examine this, but I think there is now no urgency. The current code is elegant enough to move on to other parts.

**Comment by bmaclach** [comment]
@JacquesCarette Are we okay to close this issue then, and open a new one if something comes up?

**Comment by JacquesCarette** [comment]
Yes.
