### ISSUE TITLE
Instances of GOOL typeclasses should implement Readers

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1519]
In early finally tagless GOOL conversations with @JacquesCarette, it was discussed that the long-term plan would probably be for the instances of the Symantics typeclasses to have Readers, but that it would be easiest to start with just `Doc`s in the short-term. So, currently, most of the instances just create `Doc`s. In cases where it was important to provide more information, tuples were used to tag on the additional data. Data types were introduced for some of these cases. For example, `Module`s in GOOL now are synonymous with `ModData`, which holds a `Doc` (the code for the module), a `Label` (the name of the module), and a `Bool` (whether it is the main module). 

When I first tagged Modules with their `Label` for their name, because I needed to know the name when writing the corresponding file for that module, @JacquesCarette's feedback was:
'This trick is correct but not scalable.  In general, we'll need more "context" information to be available.  So we ought to use a Reader, with a whole record's worth of stuff stashed away.'

I still have some questions about this. Your comment quoted above makes it sound like this Reader would change depending on the Module? (Because the `Label` to store would be different). But we wouldn't be able to update the Reader on the fly because my understanding of Readers is that the record they store can't be modified, only read. There's definitely something I'm "missing" here and I hope you can help fill the gap in my understanding, @JacquesCarette. I'll put a temporary question label on this.

**Comment by JacquesCarette** [comment]
`Reader`s can be changed locally: see `local` in http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Reader.html for example.  This is useful for having sub-computations run in a modified environment, but doesn't let you change it for future computations (unlike `State`).

Now that I think about it more deeply, it might be that http://hackage.haskell.org/package/hexpr-0.0.0.0/docs/Control-Monad-Environment.html might be even better.

**Comment by JacquesCarette** [comment]
@bmaclach I think this is now done, right?

**Comment by bmaclach** [comment]
We used `State` instead of `Reader`, but the "spirit" of this issue has been addressed. Closing.
