### ISSUE TITLE
conceptMap error

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1523]
@JacquesCarette, how can I resolve such an error?

Screenshot:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/43192745/59153357-64bc5d00-8a25-11e9-9973-2e77c6ba2758.png">

Error:
cd build/Chipmunk && stack exec -- chipmunkdocs
chipmunkdocs.EXE: Concept: chgInVelocity not found in ConceptMap
CallStack (from HasCallStack):
  error, called at .\Database\Drasil\ChunkDB.hs:93:24 in drasil-database-0.1.0-2iC68AnzSOl8H1jW4Hs9yn:Database.Drasil.ChunkDB
make: *** [gamephys_gen] Error 1

The error was called from here:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/43192745/59153386-19ef1500-8a26-11e9-9f30-e3202dc381de.png">
What file points to the UMap table?

**Comment by JacquesCarette** [comment]
This means that something is trying to use the `chgInVelocity` concept, but that chunk has never been put into the `ChunkDB` as a concept. Probably in the Game Physics `Body.hs`, however the concepts are gathered, it's missing that one.

**Comment by oluowoj** [comment]
ha, I see, I will take a look at Body.hs for this, thanks

**Comment by oluowoj** [comment]
Issue resolved, chgInVelocity was missing in unital.hs here:


<img width="676" alt="image" src="https://user-images.githubusercontent.com/43192745/59228489-f226bb00-8ba5-11e9-877d-5c5c3ce98da2.png">

**Comment by oluowoj** [comment]
closing ticket
