### ISSUE TITLE
Rename static

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1526]
Rename `static` as discussed in #1468.

**Comment by danscime** [comment]
Renaming via 8e38267be3d2be82775ed1cd9b4589d470122727.

@JacquesCarette Are these suitable names?

Also `dynamic` is a term that is used as well pretty much wherever `static` is used, so I think I should rename that as well in order to be consistent.

**Comment by danscime** [comment]
Renaming dynamic to dynamicRepr and Dynamic to DynamicCon via 584621ec6bfb970f029c81fffcc6f24db905ab35.

**Comment by JacquesCarette** [comment]
Do we need to rename `Static` ? We do need to rename `static` for sure.

adding `Repr` is ok (super ugly, but I can't think of anything better). I would prefer to not add `Con` if we can at all avoid it.

**Comment by danscime** [comment]
@Mornix would `Static` need to be renamed?

**Comment by Mornix** [comment]
Only lowercase `static` causes the false-positives with HLint.

**Comment by JacquesCarette** [comment]
Right - so let's just change that. And I've changed my mind: `static_` rather than `staticRepr` please.

**Comment by danscime** [comment]
I will delete my current branch and implement this via a new branch.

**Comment by danscime** [comment]
Should `dynamic` be changed to `dynamic_` for consistency?

**Comment by JacquesCarette** [comment]
yes.
