### ISSUE TITLE
Automate Check That All Chunks Are Used

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1541]
With the reorganized traceability matrix (#1537), I feel like we are close to automating an exciting check.  Almost every chunk (concept?) should be used somewhere, or else, it doesn't make sense that is is included in the documentation.  For instance, if we introduce an assumption, then this assumption should be invoked somewhere.  If it isn't invoked, why is it even in the documentation?  We are in the process of discussing this in the Projectile example.  The exception to this is the requirements.  Requirements use the other pieces of information, but they themselves aren't used in the SRS.  They are used by the design and by the implementation.

Besides wanting to know whether every chunk is used, we also want to know if there are any chunks that do not use any other chunks.  There will be some pieces of information, like some theory models, that might not depend on anything else, but most chunks should reference some other piece of information.

I could envision a day when the compilation would fail, or at least give a warning, if our relationship rules were violated, but we don't want to be too hasty.  Since we are still working out the expected relationship between all of the chunks, I would like to take the first step of just highlighting the potentially odd cases. 

It would be great to have a function (or functions) that takes in the traceability matrix information and returns two things:

- a list of all chunks that are not referenced by anything (I believe this corresponds to an empty column in the traceability table.)
- a list of all chunks that do not depend on anything (I believe this corresponds to an empty row in the traceability table.)

I might have got the row and column labels wrong above.  I haven't verified against the current shape of the traceability table.  The main point is that empty rows or columns are interesting, and it would be nice to identify them.  If we had this information for each example, we could look at each instance and decide whether the result is correct, or, more likely, how we forgot to link the information.

In my thinking an automated test l like this would again highlight the potential power of Drasil.  

I've assigned this issue to @Mornix, but if it is bigger than I think it is, @JacquesCarette can reassign it, or we can label it as a future enhancement.

**Comment by Mornix** [comment]
I think this is possible, but a little bit out from being a hard error. For example, with the new traceability matrices, I can see that GlassBR's glassType assumption is unused (at least as far as the SRS is concerned, however it is used the the codegen. I am open to flagging this as a "gen-time" warning as a current option.

Are requirements the only "roots" of traceability currently? (i.e. If we can't transitively reach a node starting from the requirements then it should be flagged.)

**Comment by JacquesCarette** [comment]
I think that's likely too big a feature to do just now. Sounds like the glassType assumption ought to be a 'design time' assumption, something which doesn't yet exist. Though it's nice that we're getting to the stage where we have to seriously think about that.

**Comment by smiths** [comment]
My goal with this issue isn't to report errors, just to gather information.  Empty columns or rows in the traceability matrix seem like clues of something, like a need for design time assumptions.  I think we can use all the clues we can get to figure out the best way to put our information together.  To start with, maybe we could just have a function to identify all of the assumptions that aren't used in the documentation?

**Comment by JacquesCarette** [comment]
:+1:

**Comment by Ant13731** [comment]
I think this issue can be closed from #2774.
