### ISSUE TITLE
Implement Choice for how to handle constants in generated code

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1560]
We should have a choice in our `Choices` record to capture how to handles constants in the generated code. Some potential options are:

- Inline all constants where they are used (this option is forced upon the code currently)
- Store constants with the input parameters
- Store constants in their own class/record
- Store constants in variables (unbundled, analogous to the `Unbundled` choice for inputs)

**Comment by JacquesCarette** [comment]
I would add
- Store constants in compiler-inlinable variables
Think `#define` in C, `final` in Java, etc.

**Comment by bmaclach** [comment]
@JacquesCarette Your suggestion can be combined with each of the latter 3 options in my original list, which makes me think there are actually 2 choices here. One choice for how to store constants (with the 4 options in the original issue post) and another choice for what type of variable (regular or compiler-inlinable) to use. The 2nd choice would just be ignored if the first choice is to inline constants.

Either that, or keep it as one choice and have 7 options (the 4 originally listed, plus 3 more by using compiler-inlinable variables with the 3 latter options in the original list). But then if we later think of another choice related to constants, these 7 choices could multiply again, which is why my preference would be to implement it as 2 separate choices.

**Comment by JacquesCarette** [comment]
Nice analysis - 2 separate choices it is!

**Comment by bmaclach** [comment]
The 2 choices have been implemented with #1851 and #1854. We don't use `#define` because we use the `const` keyword instead. If we want to be able to use `#define` let me know and I will create a separate issue for that. Closing this one.

**Comment by smiths** [comment]
I believe that `#define` is different from the `const` keyword.  The `#define` defines a macro.  I believe that the `#define` are preprocessed (by the preprocessor) to replace the macro symbol with the required text.  I don't believe there is an equivalent in every language.  I think C++ is the only language we are using that has a preprocessor?

Having said the above, I don't think we need `#define` at this time.  It seems like a distraction without much of a payoff.  However, I defer to the judgement of @JacquesCarette.

**Comment by bmaclach** [comment]
You are right that C++ is the only language with preprocessor macros out of those we generate.

**Comment by JacquesCarette** [comment]
These indeed mean different things - `#define` is really a meta-programming primitive. And I agree that this would be a distraction.
