### ISSUE TITLE
Rename "New" prefixed GOOL files

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1563]
The files for finally tagless GOOL are all prefixed with "New" (ex. NewLanguageRenderer.hs, NewJavaRenderer.hs, New.hs, etc.) and should be renamed.

I think it makes sense to just remove "New" from the name, but then the names would conflict with files from old GOOL. @JacquesCarette Is it okay to remove all of the files specific to old GOOL so that we can use their names for the new files?

**Comment by JacquesCarette** [comment]
Yes.
