### ISSUE TITLE
Typo in Chipmunk

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1568]
`describes` is mispelled in Chipmunk.

<img width="281" alt="Screen Shot 2019-06-17 at 10 39 43 AM" src="https://user-images.githubusercontent.com/28261339/59613083-42dd6d00-90ec-11e9-9d8d-5215937936ac.png">

**Comment by smiths** [comment]
Good catch @danscime.

**Comment by oluowoj** [comment]
@danscime , are you going to fix this? If not, you can assign it to me, I updated it in the branch I am currently working on.

**Comment by danscime** [comment]
@oluowoj sounds good!

**Comment by oluowoj** [comment]
fix in PR #1573
