### ISSUE TITLE
Fix Instance Model intro?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1569]
When reviewing the Projectile SRS, you mentioned as a note on the sentence
> It [referring to the IM section] uses concrete symbols defined in [DDs] to replace the abstract symbols in the models identified in [TMs] and [GDs].

That "this might not be exactly true." What should we do about this? @JacquesCarette might have some input.

**Comment by smiths** [comment]
Right now, I don't think we should do anything.  The relationship between IMs, DDs etc is an active line of inquiry this summer.  It started with our discussions with @bmaclach around SSP.  We shouldn't revise the text until we have determined what we are doing.  I'm optimistic that Projectile will help us understand the relationships between the "chunks."  At that point, we'll update our documentation to reflect our improved understanding.

**Comment by samm82** [comment]
Can this issue be closed then?

**Comment by smiths** [comment]
It is up to you whether to close this issue.  If your question was answered, then yes, you can close the issue.  😄 If you need further clarification, we can certainly keep the issue open.
