### ISSUE TITLE
Coordinate Systems Concepts

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1577]
The concepts `xAxis`, `xDir`, `yAxis`, and `yDir` should be added, so that "y-direction" displays as "*y*-direction". I think they should be added to `Concepts.Math`, and the concepts for cartesian and right-hand should probably be moved here as well from `Concepts.Physics`. Does this sound OK? @JacquesCarette @smiths

**Comment by smiths** [comment]
Yes, I agree that the concept of a coordinate system is a mathematical concept.   `Concepts.Math` sounds like the right home for this knowledge to me.

**Comment by samm82** [comment]
Should the new `rectilinear` concept from #1428 be moved as well? The ideas for 1D, 2D, and 3D are in `Concepts.Physics` currently; should they go too? @smiths

**Comment by smiths** [comment]
I would leave these concepts in `Concepts.Physics`.  That is where they come up.  We don't really say rectilinear outside of physics; the terminology would come up in a physics course.  Although math gives us different dimensions, they come up in mathematical modelling of physical systems, especially in the assumptions.

Of course arguments could be made for moving the concepts, but I have a feeling we'll be shuffling things around without a clear direction.  I think a time will come when we have a clear ontology that organizes our physics and mathematical knowledge.  Until then, we should classify the things that are obvious and make our best guesses on the others.  :smile:

**Comment by JacquesCarette** [comment]
Arguments can solidly be made that some concepts "belong to" multiple domains. This is why the domain information *inside* Drasil is actually a list!

So whenever there is a question as to a concept belongs in X or Y, best thing is to pick a "most reasonable home" Z, and then give it all those domains. A comment in the other domains might not be a bad idea too.

**Comment by samm82** [comment]
So should I added `mathematics` to the domains of `oneD`, `twoD`,  and `threeD`? @JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
My opinion is 'yes'.

**Comment by smiths** [comment]
@JacquesCarette that makes sense that a concept can belong to multiple domains.  I'm glad to hear that Drasil allows this.
