### ISSUE TITLE
Re-Enable Haddock Docs on CD

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1578]
Stack 2.1.1 is a large update to Stack that changes a lot of the internals. One of the (unfortunate) side-effects of the changes is Haddock (through Stack integration) uses absolute links as opposed to relative links (which Stack <2 uses).

Upon further inspection (`make docs haddockArgs="-v"`) it appears the command run immediately after the text line "Updating Haddock index for local packages in <path>", updates the index. The arguments passed into Haddock for this command include many `-i` (short for `--read-interface`) which determines which packages are available to index. Stack <2 provides relative links in this command while Stack 2.1.1 provides absolute links. 

Some possible courses of action to re-enable docs:
1. `sed` over the links in the generated index and strip absolute paths.
2. Manually run the command mentioned above with relative paths to generate a correct index.

**Comment by JacquesCarette** [comment]
As far as I can tell, this was [fixed in late September 2019](https://github.com/commercialhaskell/stack/issues/4971) in stack, which seems to mean it was fixed in stack 2.3.1.

**Comment by Mornix** [comment]
That looks like it should fix it! A local build on 2.3.1 looks like it does the trick. I notice you pushed code already to address it. If you run a build of master again (manually) that should trigger a deploy (now) and allow us to check.

**Comment by JacquesCarette** [comment]
Haddocks were successfully built in 3311342. Since I've also checked in something else, that build ought to trigger a deploy, if the previous one didn't already (it looked like it did).

**Comment by Mornix** [comment]
Haddocks have always successfully built. It was when they were deployed links would 404 because they were absolute and led to a path that didn't exist. 

Deploys are only triggered on a cron once daily, but I believe I added an "override" so a manually trigger build of master would do it too?

**Comment by JacquesCarette** [comment]
How do I run an "api" build?

**Comment by Mornix** [comment]
Try https://blog.travis-ci.com/2017-08-24-trigger-custom-build, going to the Travis build for that commit, and on the dropdown there should be "Trigger Build" or something along those lines.

**Comment by Mornix** [comment]
Fix verified with 43aedea4 to `gh-pages`. Closing.

**Comment by smiths** [comment]
Nice to see an almost year old issue closed.  :smile:
