### ISSUE TITLE
Unitalicized Vector Components

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1585]
In the derivations of Projectile's GD3 and GD4, the first vector's components aren't italicized (and should be), while the rest are: *This only occurs in the HTML.*

### GD3
![gd3](https://user-images.githubusercontent.com/35857611/59784366-3abe3280-9290-11e9-9ab8-f07aefe85543.png)

### GD4
![gd4](https://user-images.githubusercontent.com/35857611/59784393-4ad61200-9290-11e9-9737-6bb48d0d3062.png)

**Comment by smiths** [comment]
@samm82, the bug is only in the LaTeX version, right?  (The html is fine?)

**Comment by samm82** [comment]
It's the other way around - this only occurs in the HTML.

**Comment by smiths** [comment]
Thanks for the clarification @samm82.  The generated html looks better than I remember.  😄

**Comment by JacquesCarette** [comment]
This is very very weird. I doubt the bug is deep in the infrastructure, I would suspect something is being done weirdly in the example itself. But I could be wrong!

**Comment by samm82** [comment]
Fixed by @danscime in #1832.
