### ISSUE TITLE
Make GlassBR TMs More General

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1587]
From #1478, the description of the GlassBR TMs should be more abstract:

- [x] The word "structure" should be used instead of "glass"
- [x] The connection between the two TMs should be removed
- [x] Load should be generalized, instead of being the 3-second duration

The load TM should also potentially be reused from SSP.

**Comment by smiths** [comment]
Sounds good @samm82.  Your issue captures the points I was trying to make.
