### ISSUE TITLE
Add constants to Drasil-Data

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1592]
We currently do not have constant values stored in Drasil. This needs to be added

**Comment by bmaclach** [comment]
The way we handle constants in the examples currently is by constructing them with `mkQuantDef` which is a constructor for `QDefinition`s (I said in the meeting that it was a constructor for `DataDefinition`s -- I remembered that wrong).

`QDefinition`s are defined as:
https://github.com/JacquesCarette/Drasil/blob/5e3356ef40baaad3da39b593c51c95fc46cdaa57/code/drasil-lang/Language/Drasil/Chunk/Eq.hs#L20-L21
Which seems like basically what we want. The `Expr` for constants would simply be their value. (Thoughts @Mornix @JacquesCarette)?

**Comment by samm82** [comment]
I personally like this, so that we can define constants for percentages (as `Perc` is a constructor of `Expr`).

**Comment by JacquesCarette** [comment]
Yes, that is indeed what we want. Good!

**Comment by samm82** [comment]
Assuming you're still working on this @oluowoj, the gravitational constant (defined in `Projectile.Unitals`, I'm pretty sure) should be pulled out to `drasil-data`, and its definition updated to "the approximate acceleration due to gravity on Earth at sea level".

**Comment by JacquesCarette** [comment]
Any update on this? It seems this should have been done and closed.

**Comment by JacquesCarette** [comment]
Is this done @samm82, @bmaclach ? It looks like it is.

**Comment by bmaclach** [comment]
@samm82 and I added the constant value for pi to get projectile code generation working, but I think @oluowoj needed different constant values (gravitational constant, acceleration due to gravity) which are not yet done.

**Comment by JacquesCarette** [comment]
Indeed - but now we know how to do it, so let's hurry up and get it done, so that the oldest outstanding PR can be merged!

**Comment by oluowoj** [comment]
on it now.

**Comment by JacquesCarette** [comment]
@oluowoj has everything about this issue been dealt with?

**Comment by oluowoj** [comment]
Checking the SRS now, realized that g (gravitational acceleration) is missing from the table, that's the only item left for this to be completed.

**Comment by JacquesCarette** [comment]
Ok, thanks for checking and documenting.

**Comment by smiths** [comment]
The original issue was to add constants to Drasil-Data.  Hasn't that been done?  When I look at this file:

https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-data/Data/Drasil/Quantities/Physics.hs

I clearly see G and g are defined.  

In the projectile motion example g is defined in the value of auxiliary constants at the end of the document.

@oluowoj, do you mean that G is not in the table of auxiliary constants for the Game Physics case study?  You mention g, but as far as I know g is not used in the Game Physics example; we only introduce the concept of the universal gravitational law (using G).  Is the issue now to add this to G to Game Physics?  The value of G in the game physics example is listed under the Data Constraints table.  It isn't listed as an auxiliary constant.   Has this issue morphed into something else?  I'm afraid I don't know what needs to be done to close the current issue.

**Comment by oluowoj** [comment]
@ My previous response was specific to gamephysics and you are right, we do not need 'g' in the Data Constraits table, I now recall it was replaced with G.  This issue can be closed or I can close it, if no other concerns

**Comment by smiths** [comment]
Yes, I think we can close this issue.  The game physics case study still needs some attention to improve it, but this issue isn't the way to drive those changes.
