### ISSUE TITLE
SWHS: Issues with Latent Heat TM Equation

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1593]
After some discussion on #1478 and #1479, the equation for the Latent Heat TM seems questionable: 

![image](https://user-images.githubusercontent.com/35857611/59855631-55051880-9343-11e9-82bb-9d2d3f95b67e.png)

From @smiths, "the equation has to capture the addition of heat energy. We know how much heat energy is added because we know the rate of heat energy addition and the amount of time."

We need some way to capture the information that Q(0) = 0 for the integral, either by adding the capability to Drasil or by changing the equation. @JacquesCarette @smiths Thoughts?

**Comment by smiths** [comment]
Let us separate how things are done in Drasil from what the equation says from a physics point of view.  I agree that the equation needed to be improved with the additional cases, but now that you have added the cases (shown above), in what way is the equation now questionable?

**Comment by samm82** [comment]
I'm honestly not sure. The condition made sense to me since you would need it for the integration, but @JacquesCarette thought "that the equation [is] mathematically meaningless." My guess is that seeing everything here together will help clarify what is actually being asked. (Sorry @smiths - I tend to comment on the issue I'm working on when something comes up, assuming it will be a small fix, instead of creating a new one. 😬)

**Comment by samm82** [comment]
@smiths As discussed in the meeting, what should the new variable name be for the quantity dQ(τ)/dτ? Should it be defined somewhere else (it isn't defined anywhere in the document)?

It was also mentioned that the second case should be represented as a DE and not as an integral, but I'm not sure how that would result in a value of Q(t) for the expression.

**Comment by smiths** [comment]
@samm82, I've looked around and H seems to be used to represent DQ/Dt (https://en.wikipedia.org/wiki/Rate_of_heat_flow).  Let's use H, which is the rate of change of latent heat energy.  You will need to add a symbol for it.  In IM4 you would define H(t) to be qP(t)*Ap.  Solving the differential equation is how Qp(t) is found.

Q(t) is found by solving the differential equation dQ(t)/dt = H(t), with Q(0) = 0, if 0 < phi < 1.  For both the case of phi = 0 and phi = 1, dQ(t)/dt = 0.  That is, the latent heat energy will not change.

This also gives us a new property of a correct solution, if phi = 1, then we can verify that Qp(t) = Hf*mp.

**Comment by samm82** [comment]
I don't think H(t) should be defined in an IM since this TM would reference it, and TMs shouldn't reference IMs.

@smiths What if we make the `DEModel` dQ(t)/dt = H(t), with the initial condition Q(0) = 0, and then define H(t) as an `EquationalModel` as a case-by-case expression as above? The only problem with this is that the types of models are only defined for IMs - @JacquesCarette Was the intention to make TMs with these `ModelKinds` as well?

**Comment by JacquesCarette** [comment]
Yes, both IMs and TMs should support `ModelKind`s.

**Comment by smiths** [comment]
@samm82, I'm not saying that H(t) should be defined in its own IM.  IM4 (in the manual version) currently gives a value for dQp/dt.  Once we have H(t), this is the same as defining H(t).  The IM would reference the TM, not the other way around.  The TM is abstract.  It gives a function  H(t).  The IM refines the TM by giving a specific function for H(t).

**Comment by JacquesCarette** [comment]
So I've reread this issue, and I can't tell what remains to be done (if anything). @smiths ?

**Comment by smiths** [comment]
The original issue was a question.  I believe the question has been answered.  I'm not aware of any problems with the current version of SWHS that are outstanding.  Therefore, I'll close this issue.
