### ISSUE TITLE
Website - Different links for different file types

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1596]
As per @JacquesCarette's comments in #1527.

<img width="635" alt="Screen Shot 2019-06-21 at 11 10 10 AM" src="https://user-images.githubusercontent.com/28261339/59932512-556de400-9415-11e9-8754-67009f464970.png">

**Comment by danscime** [comment]
@Mornix I'm trying to figure out what's exactly going on here, especially what happens right after `field "url"`. I'm thinking if I can figure it out, I can make a `urlPDF` and a `urlHTML` and then name the example once but have 2 separate links to the different versions of the SRS.

<img width="719" alt="Screen Shot 2019-06-21 at 3 53 36 PM" src="https://user-images.githubusercontent.com/28261339/59947984-c1177780-943c-11e9-821e-e919d5e6d864.png">

**Comment by Mornix** [comment]
The `field “url”` line constructs a URL path from the `srsPath` function. All of the `itemBody`/`makeItem` wrapping and unwrapping are to get the value out lift it back into a `Compiler (Item a)`. The input to the `url` field (and all under the list field `srs`) is a tuple of the srs field of the `Example` type, and the whole example.

Let me know if anything is unclear or doesn’t make sense.

**Comment by danscime** [comment]
Still not entirely sure about how exactly the monads are manipulating things. But, after staring at the screen for a while, I actually found a MUCH easier fix in the `index.html` file.

Updated in: 0588ab3a67b30de4c33cf73022b612aac24f78ec

![Drasil](https://user-images.githubusercontent.com/28261339/60022829-927ae600-9662-11e9-9d2b-1f8f47675620.jpg)

**Comment by JacquesCarette** [comment]
Minor thing - can you not center the `Haskell Documentation` link?  And maybe add a tiny bit of documentation as to what that links to?

**Comment by danscime** [comment]
@Mornix could you help explain line 72 here. I'm thinking of having the file list the different subfolders under `src` in order to have links to the different generated languages.

https://github.com/JacquesCarette/Drasil/blob/47c335862d5bc6ad2f5c21b765bdc9da5417ffa7/code/scripts/deploy_stage.sh#L58-L75

**Comment by danscime** [comment]
@JacquesCarette for sure! That will be tracked updated and tracked via #1597.

**Comment by Mornix** [comment]
Line 72 calls the `deploy_code_path` folder target in the `Makefile` (as the `Makefile` knows more about the general path setup of Drasil). The `grep` and `cut` extract the `src` path for `$example` from what’s output by the `Makefile`. 

A likely good option is to store the result of the `cut` as a variable and combine it with the list of folders inside the returned directory.

**Comment by danscime** [comment]
By using these 3 lines and commenting out the old line, I can get my desired functionality.

<img width="900" alt="Screen Shot 2019-06-24 at 12 13 34 PM" src="https://user-images.githubusercontent.com/28261339/60034875-88b0ad00-9679-11e9-8176-4a8cf2e1f31e.png">

Which gives in the `src` file:

<img width="312" alt="Screen Shot 2019-06-24 at 12 13 14 PM" src="https://user-images.githubusercontent.com/28261339/60034905-9d8d4080-9679-11e9-8291-79a834ff2cea.png">

**Comment by Mornix** [comment]
You should be able to achieve exactly the same output by replacing `echo` in the line you commented out with:
`ls -d “$CUR_DIR”$(...)* > ...`

Which has the added benefit of avoiding location side-effects and hardcoded information.

**Comment by danscime** [comment]
I have tried these but none work.

`ls -d "$CUR_DIR"$(cd "$CUR_DIR" && "$MAKE" deploy_code_path | grep "$example_name" | cut -d"$DEPLOY_CODE_PATH_KV_SEP" -f 2-)* > "$EXAMPLE_DEST$example_name/src"`

`ls -d $(cd "$CUR_DIR" && "$MAKE" deploy_code_path | grep "$example_name" | cut -d"$DEPLOY_CODE_PATH_KV_SEP" -f 2-)* > "$EXAMPLE_DEST$example_name/src"`

`ls -d $("$MAKE" deploy_code_path | grep "$example_name" | cut -d"$DEPLOY_CODE_PATH_KV_SEP" -f 2-)* > "$EXAMPLE_DEST$example_name/src"

**Comment by Mornix** [comment]
Looking at what I wrote, is the line I suggested just printing the languages and not the prefix path? If so, I think some `xargs` should be able to correct that. However, I’m not great at writing `xargs` commands off the top of my head.

**Comment by danscime** [comment]
They all fail as a directory is not found. The first suggestion tries to get into the ...../code/code /.... folder which doesn't exist. Weird.

**Comment by Mornix** [comment]
Right. `deploy_code_path` gives a path relative to the repo root.

`ls -d “$(git rev-parse --show-toplevel)$(...)”* > ...`

**Comment by Mornix** [comment]
The rev-parse I just posted will definitely require some fixup with `xargs`.

**Comment by Mornix** [comment]
Worked out the command line: 
```bash
ls -d "$(git rev-parse --show-toplevel)/$(make deploy_code_path | grep "glassbr" | cut -d: -f2-)"*/ | rev | cut -d/ -f2 | rev | tr '\n' '\0' | xargs -0 printf "$(make deploy_code_path | grep "glassbr" | cut -d: -f2-)%s\n"
```
(Which you can run directly to verify the output is as expected.)

Where it could be abstracted to and placed in the script as:
```bash
REL_PATH=$(cd "$CUR_DIR" && "$MAKE" deploy_code_path | grep "$example_name" | cut -d"$DEPLOY_CODE_PATH_KV_SEP" -f 2-)
ls -d "$(git rev-parse --show-toplevel)/$REL_PATH"*/ | rev | cut -d/ -f2 | rev | tr '\n' '\0' | xargs -0 printf "$REL_PATH%s\n" > "$EXAMPLE_DEST$example_name/src" 
```

**Comment by danscime** [comment]
So for the I'm not entirely sure how to make the required functions.
I'm guessing I should use a list of tuples, where each tuple is `(path, language)`.
Just not sure how to implement.

<img width="736" alt="Screen Shot 2019-06-25 at 4 17 02 PM" src="https://user-images.githubusercontent.com/28261339/60130174-baeb0900-9764-11e9-93a0-671d01d8dfd1.png">

**Comment by danscime** [comment]
As of d77b0ec6f299c712d3bf60e5ecc9977ca5b5abea I have added different links for each generated language. The only problem now is that the "Generated Code" heading appears for each example.

![Drasil](https://user-images.githubusercontent.com/28261339/60210672-6a8aae80-982b-11e9-951c-78a748c8b2ed.jpg)

I think this is due to the `$if(src)$` not being taken into account as they are probably only used by `maybeField`. 

Two possible solutions I can think of right now:
- Make a separate `maybeField` that is used pretty much just like a boolean to see if there is existence of code.
- Make a `maybeListFieldFunction` that handles both the `if` and the `for` aspects of the field.

Not sure which would be more desired. Or maybe there is another solution I cannot think of.

**Comment by smiths** [comment]
@JacquesCarette may feel otherwise, but the empty generated code links don't bother me.  Eventually we will fill them in.  This gives us a reminder that we haven't done this yet.  It doesn't seem like something that we should stress over.

**Comment by danscime** [comment]
"Generated Code" section removed if no example does not have source code via db5ff516d1cbdfe5abe3fbafe8b0c2c928daa616
