### ISSUE TITLE
Website - Haskell Documentation

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1597]
Building off of #1527. Haskell Documentation should have a description in the intro to the webpage.

Haskell Documentation does not always appear on the webpage. Should it?
@Mornix is there a reason why we do not always have it appearing?

**Comment by Mornix** [comment]
It is currently disabled due to some Stack 2.1 changes which “break” the process we used to deploy that portion. You can still add the intro bit, but it won’t show up until we resolve the doc-deploy issue.

**Comment by danscime** [comment]
I am not sure how much we want to add, but this is my current idea to be added in the intro section:

The Haskell Documentation section contains the current documentation for the Drasil framework.

**Comment by danscime** [comment]
Also, I don't know if should be a description added at the beginning of the section as well.

**Comment by danscime** [comment]
Description and formatting updated via 61be95de879e4a77074ad17c8689daaf5251796b
