### ISSUE TITLE
Website - Link from main repo page

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1598]
Building from #1527.

@JacquesCarette @smiths @Mornix 

I believe there is a way of adding a github.io link to the top of the main repo page.
I have looked into it a bit, it seems like something you can only do with admin privileges.
Do we want this?

My summer stats course used this feature.
https://github.com/Muu24/Stats3Y3J_2019

<img width="871" alt="Screen Shot 2019-06-21 at 11 18 16 AM" src="https://user-images.githubusercontent.com/28261339/59933026-8995d480-9416-11e9-88ce-55e792feed5b.png">

**Comment by JacquesCarette** [comment]
Yes. we want this. If you can point me to the instructions on how to do it, I can.

**Comment by danscime** [comment]
It might actually be much easier than expected. I think you can choose to display any chosen link at the top of the repo.

On the main page if you have the edit button at the top right, there is an option for a link.

<img width="839" alt="Screen Shot 2019-06-21 at 1 58 26 PM" src="https://user-images.githubusercontent.com/28261339/59942171-f4eaa100-942c-11e9-881e-cdb68c2959a8.png">

**Comment by JacquesCarette** [comment]
Yes, I can do that [I checked].  But I don't really want to link to https://jacquescarette.github.io/Drasil/ right now, as it is quite ugly!  I'll do it as soon as things look nice.

**Comment by danscime** [comment]
Are we ready to add site link?

**Comment by JacquesCarette** [comment]
I think so!

**Comment by danscime** [comment]
Does not link properly, at least for me. Possibly not properly copied.

<img width="644" alt="Screen Shot 2019-07-09 at 4 30 14 PM" src="https://user-images.githubusercontent.com/28261339/60920791-09b99800-a267-11e9-9fe1-9971da99b47c.png">

**Comment by JacquesCarette** [comment]
Fixed -- trailing / was the problem.
