### ISSUE TITLE
Website - Introduction

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1599]
Building from #1527.

@smiths @oluowoj 

For the introduction to the site, we said we wanted a brief intro of what Drasil is.
Currently we do not have any sort of intro, we only have descriptions of the sections on the webpage.

**Comment by oluowoj** [comment]
Yes, I think we should have some sort of intro. Can you put something together and we can review and possibly edit?  Just some few start up lines for a start.

**Comment by danscime** [comment]
Some pieces from the main README file.

Drasil is a framework for generating all of the software artifacts from a stable knowledge base, focusing currently on scientific software. The main goals are to reduce knowledge duplication and improve traceability.

Drasil is used to generate all requisite software artifacts from a common knowledge-base using recipes written in a Domain-Specific Language (DSL). These recipes allow us to specify which pieces of knowledge should be used in which artifacts, how to transform them, and more.

**Comment by oluowoj** [comment]
Yes, I was going to suggest texts from the readme file, I think its a good start.

**Comment by danscime** [comment]
Updated via c6a3af270779b08a1516a28d27ac89110b1fa8f9.

My intro paragraph currently is:

Drasil is a framework for generating all of the software artifacts from a stable knowledge base, focusing currently on scientific software. The main goals are to reduce knowledge duplication and improve traceability. The atifacts are generated from a common knowledge-base using recipes written in a Domain-Specific Language (DSL). These recipes allow us to specify which pieces of knowledge should be used in which artifacts, how to transform them, and more.

**Comment by smiths** [comment]
@danscime, I like your intro text, but I think we can say more.  I wrote the following document (for another purpose) that I think you can borrow from.

[OutcomesAndBenefitsOfDrasil.txt](https://github.com/JacquesCarette/Drasil/files/3378867/OutcomesAndBenefitsOfDrasil.txt)

**Comment by peter-michalski** [comment]
From meeting #3038

I will review the Wiki for any items that should be added to the website.

Potential items:
- Information regarding getting started with Drasil
- What can, or could in the future be created with Drasil (generate specific artifacts/documents, code - in various languages)
- Regarding the future consider other artifacts listed in Olu's work
- Quantify number of artifacts that Drasil can produce (quantify other information?)
- Consider adding things that will encourage people to help develop Drasil (and use Drasil)
- Consider adding an introductory blurb that explains Drasil in plain language (Before the current into? Move current intro to another section? As an abstract?)

**Comment by smiths** [comment]
The original description of the issue doesn't really match the expanded scope of our discussion (in #3038).  Therefore, I'll close this issue and create a new one that includes the points listed by @peter-michalski.
