### ISSUE TITLE
Improve Symbol Decoration Infrastructure

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1605]
Drasil currently supports symbol decorations in the form of:
* Hat
* Prime
* Vector

This is a good start, but there are a few "hacks" which have propagated. One is `∆` which (in the current use cases) represents "difference of value". The symbol sorting algorithm considers this to be a decoration (albeit hardcoded) and strips it off when comparing. 

https://github.com/JacquesCarette/Drasil/blob/76913ecbd3ef11258b38294318fdfb6d81502585/code/drasil-lang/Language/Drasil/Symbol.hs#L56-L71

Similarly, `|| ||` is hardcoded in a few examples to indicate the "magnitude of some vector". (This one isn't hardcoded when symbol sorting and thus the magnitudes will always sort lower than the vectors and other symbols beginning with the same character).

It may be worth encoding these (and others I haven't noticed) as decoration within `Symbols` to make sorting more consistent and remove these hacks encoding semantic meaning through use of a literal symbol.

**Comment by JacquesCarette** [comment]
I agree. And we should revisit the Δ hack too. Maybe we should simply remove it?
