### ISSUE TITLE
Take advantage of Values holding type information in GOOL to simplify functions

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1611]
With the merge of #1610, `Value`s in GOOL are all `ValData`, so they hold type information accessible with the `valType` function:
https://github.com/JacquesCarette/Drasil/blob/54d6d290449ebca55966674255495cb2333fc25c/code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs#L59

Reading types from `Value`s should allow us to clean up many of the GOOL functions in Symantics.hs (and implemented in the different renderers in the LanguageRenderer directory). We should look over all of these functions and clean them up where we can.

If a function gets passed a `repr (StateType repr)` but also a `repr (Value repr)` which holds the needed type information, the `StateType` parameter can be removed and the type read from the `Value` instead. An example is `listSlice`, but there may be more:
https://github.com/JacquesCarette/Drasil/blob/47050c6081fc3a663b23b69fac0ee7c28679f839/code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs#L93-L95
Just ensure that any `StateType` parameter removed actually corresponds to the existing `Value` parameter passed to the function (this will have to be determined on a case-by-case basis by understanding how each parameter gets used)

If a function gets passed a `Label` and a `repr (StateType repr)` and both get passed to `var` in the function body to construct a `Value`, the two parameters can be replaced by a single `repr (Value repr)` parameter. An example is `get` but there may be more:
https://github.com/JacquesCarette/Drasil/blob/47050c6081fc3a663b23b69fac0ee7c28679f839/code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs#L291
https://github.com/JacquesCarette/Drasil/blob/47050c6081fc3a663b23b69fac0ee7c28679f839/code/drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/PythonRenderer.hs#L297

If there is a group of functions where each operates on a specific type, the group can be replaced by a single polymorphic function that pattern matches on the type and then performs the correct actions for that type. For example, `getIntInput`, `getFloatInput`, `getBoolInput`, `getCharInput`, and `getStringInput` can be replaced by a single `getInput` function.
https://github.com/JacquesCarette/Drasil/blob/47050c6081fc3a663b23b69fac0ee7c28679f839/code/drasil-code/Language/Drasil/Code/Imperative/Symantics.hs#L376-L380

**Comment by JacquesCarette** [comment]
This issue is not written in such a way so that people outside of you can understand it. And this matters, because if it turns out you can't quite finish implementing it, someone else will have to, but they won't be able to reconstruct the task!

**Comment by bmaclach** [comment]
@JacquesCarette I added more detail to the issue. There is some investigation required to determine which functions can be cleaned up, but I hope I've given enough information for someone else to identify those functions if need be.

**Comment by JacquesCarette** [comment]
Excellent, thanks - much clearer.
