### ISSUE TITLE
Add Hibbler Reference to Projectile SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1617]
Here is the textbook that we can use for the citations to Source in the SRS for Projectile.  Please create a bibtex entry for this book and add it to the SRS documentation.

https://www.amazon.ca/Engineering-Mechanics-Dynamics-Russell-Hibbeler/dp/0133915387

**Comment by samm82** [comment]
You mentioned that you'd want the page numbers to be referenced. Do you have a copy I could look through to find the page numbers? @smiths

**Comment by smiths** [comment]
Good idea.  I'll bring my copy of Hibbler to our meeting tomorrow (Thursday).
