### ISSUE TITLE
Remove Sentence from Scope

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1618]
The sentence you want to be removed from the scope is generated in each example. Should the equivalent sentence be removed in all examples as well, or should we look into this in more depth?

![image](https://user-images.githubusercontent.com/35857611/60127900-57aaa800-975f-11e9-8488-9ccf9d6d91f1.png)

**Comment by smiths** [comment]
@samm82, I think we should remove the text we are discussing in all of the examples.  I haven't got around to typing this up yet, but I have some rules that I'm formulating for the SRS document.  One of the rules is that we shouldn't repeat things at the same level of abstraction.  We can repeat things if each time it is said the knowledge is refined in some way.  The sentence in question just repeats the goal statement.  It really isn't part of the scope in a meaningful way.  Of course the scope of the software in every example is to solve the problem at hand, but it isn't adding any information to say this.

I view the scope section as an abstract view of the assumptions.  We highlight the overarching assumptions in the statement of scope.  Probably some of the examples don't currently view the scope section this way, but going forward I want eventually edit all of the examples to follow this guideline.

As a start, we should remove the redundant information.

**Comment by samm82** [comment]
Apparently, I missed something, and there is a way to remove this sentence from specific examples. Should I still go through and remove it from the others? (I'll go through and make sure no information would be lost.) @smiths

**Comment by samm82** [comment]
Also, the scope of requirements for GlassBR is "The scope of the requirements includes getting all input parameters related to the glass slab and also the parameters related to blast type. Given the appropriate inputs, GlassBR predicts whether a glass slab is safe or not." This doesn't seem like it captures what should be in the scope. What about "The scope of the requirements includes the analysis of glass breakage and safety," or something like that? @smiths

**Comment by smiths** [comment]
@samm82, let us just remove the scope "mistake" from the Projectile example.  We can worry about the other examples later.

With respect to GlassBR, the scope is to determine the safety of a glass slab under a blast loading following the ASTM standard.  (A citation to the standard would also be nice here.)

The abstract view of the requirements for GlassBR is to satisfy the standard.  GlassBR doesn't really make assumptions in the same way that the other examples do.  The purpose of the SRS for GlassBR is to "refine" the scope of following the standard to the specific details that come from the standard.

**Comment by samm82** [comment]
In the branch I was working on, I fixed all examples but GlassBR, so I think I'll just fix GlassBR too.

The scope section has the option to pass in a `Sentence` of the intended purpose, so the resulting sentence will be "Given the appropriate inputs, \<program name> \<intended purpose>." Should this option be deleted after this change? @smiths

**Comment by samm82** [comment]
Also, the scope template is "The scope of the requirements includes..." Should this be changed?

**Comment by smiths** [comment]
@samm82, I do not believe that we need the "Given the appropriate inputs, <program name> <intended purpose>" option any more.  This issue started with the observation that this isn't really a statement about the scope, but rather a restatement of the goal statement (the purpose of the software).  @JacquesCarette may feel differently though.

With respect to your last question, can you provide the full sentence.  It is difficult to judge how it will look without some examples.

**Comment by samm82** [comment]
Chipmunk:
> The scope of the requirements includes the physical simulation of 2D rigid bodies acted on by forces.

GlassBR (without changes mentioned above):
> The scope of the requirements includes getting all input parameters related to the glass slab and also the parameters related to blast type. Given the appropriate inputs, GlassBR predicts whether a glass slab is safe or not.

SSP:
> The scope of the requirements includes stability analysis of a two-dimensional (2D) soil mass, composed of a single homogeneous layer with constant material properties. The soil mass is assumed to extend infinitely in the third dimension. The analysis will be at an instant in time; factors that may change the soil properties over time will not be considered.

SWHS:
>The scope of the requirements includes thermal analysis of a single solar water heating tank incorporating PCM. This entire document is written assuming that the substances inside the solar water heating tank are water and PCM.

NoPCM:
> The scope of the requirements includes thermal analysis of a single solar water heating tank.

Projectile:
> The scope of the requirements includes the analysis of a two-dimensional (2D) projectile motion problem with constant acceleration.

**Comment by smiths** [comment]
Thank  you for the summary @samm82.  Very helpful.  I'm not going to do it now, but a review of these documents could improve the scope further.  They are definitely better, but some of the "high level" assumptions are missing in some cases.

I don't love the "The scope of the requirements .." introduction.  It does not flow well.  However, I do not have a better idea at this time.  We can leave it as it is for now.

**Comment by samm82** [comment]
Also, is "Standard Practice for Determining Load Resistance of Glass in Buildings" the relevant ASTM standard for the scope? @smiths

**Comment by samm82** [comment]
I also just realized that the scopes above are the changed versions on my branch, not the versions in master. Do you want those too?

**Comment by smiths** [comment]
> Also, is "Standard Practice for Determining Load Resistance of Glass in Buildings" the relevant ASTM standard for the scope? @smiths

Sounds good.

> I also just realized that the scopes above are the changed versions on my branch, not the versions in master. Do you want those too?

I think the plan is to replace the versions in the Master branch with your improved scope sections.  I don't think I need to see master right now.  When the PR happens, I'll see how the scope section is changed in stable.

**Comment by JacquesCarette** [comment]
So @smiths is right, I likely have opinions about this. But it doesn't seem to make sense (for me) to look at this in isolation, as this would likely increase rather than decrease overall consistency. I need to do a full pass on reviewing the document templates and offer opinions.
