### ISSUE TITLE
Reference ToS in Section Intro

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1619]
The Table of Symbols "Purpose" line should reference the table itself:

![image](https://user-images.githubusercontent.com/35857611/60131102-9abc4980-9766-11e9-82f3-fb6f1cd783ed.png)

**Comment by smiths** [comment]
One of the rules of writing (any book on technical writing will include this rule) is that every table and figure should be explicitly referenced by the text.  We aren't following that rule when we have a table called Table 1, but we never actually reference the table.
