### ISSUE TITLE
Update Physical System Diagram

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1620]
Add:
- the coordinate system
- the direction of gravity
- the offset

**Comment by samm82** [comment]
@smiths Currently, in the diagram, the projectile hits the target, so *p<sub>target</sub>* and *p<sub>land</sub>* (for all intents and purposes) are equal. Should I change the diagram to a case where the target isn't hit, so that these quantities (and *d<sub>offset</sub>*) can be made more clear? I think adding both *p<sub>target</sub>* and *p<sub>land</sub>* would clutter up the diagram, but they are both necessary to show *d<sub>offset</sub>*.

**Comment by smiths** [comment]
A picture really is the most effective way to communicate this information.  Any serious reviewer of the document would end up drawing their own picture, if we don't provide one.  I think you should do as you have suggested and add the additional symbols and dimensions to the figure.  I think it can be drawn in a such a way that it isn't cluttered, but if it is cluttered, then you could have two figures, each with half the information you are conveying.

**Comment by samm82** [comment]
How's this? @smiths 

![image](https://user-images.githubusercontent.com/35857611/60210477-f6e8a180-982a-11e9-99dc-8d6fb52c6755.png)

**Comment by smiths** [comment]
Yes, this looks great!
