### ISSUE TITLE
Improve Cartesian Coordinate System Definition

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1621]
@smiths you mentioned that the definition of a Cartesian coordinate system should be improved:

![image](https://user-images.githubusercontent.com/35857611/60131552-a65c4000-9767-11e9-8255-49515a7a3378.png)

I just used the definition already defined in Drasil, and it is the same definition as the one on Wikipedia. What information is missing?

**Comment by smiths** [comment]
The definition you gave is a subset of the definition on Wikipedia.  As I said in the comment, some key parts of the definition are missing.

https://en.wikipedia.org/wiki/Cartesian_coordinate_system

**Comment by samm82** [comment]
What additional information should be included? The definition of the axes and origin? If so, should they be talked about in the Cartesian coordinate system and defined in their own separate definition?

**Comment by smiths** [comment]
From the Wikipedia page:

A Cartesian coordinate system is a coordinate system that specifies each point uniquely in a plane by a set of numerical coordinates, which are the signed distances to the point from two fixed perpendicular oriented lines, measured in the same unit of length.

**Comment by samm82** [comment]
So should "coordinate" and "axis" have their own separate definitions?

**Comment by smiths** [comment]
No, just fix the definition of Cartesian coordinate system.
