### ISSUE TITLE
Constraint on Offset

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1623]
@smiths You mentioned that the shortest possible flight is one where *p<sub>land</sub>* = 0, but since the constraint on the angle is 0 < θ < π/2, this isn't the case. Should we change the constraint on the angle to allow for a shot straight up, or the rationale on the new offset constraint (ie. *p<sub>land</sub>* is always positive)?
![image](https://user-images.githubusercontent.com/35857611/60133536-8fb7e800-976b-11e9-9b64-f88d01cc0bd5.png)

**Comment by smiths** [comment]
You are correct that technically the projectile could never land at zero.  What I mean is that pland = 0 is a lower bound.  It definitely can't land to the left of the launcher.
