### ISSUE TITLE
Documentation for site.hs

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1632]
Eventually we should have some documentation / comments in `site.hs`.
In the future if someone new needs to take a look and figure out how to edit the website.

From my point of view, trying to figure out how it worked took quite a bit of time, and I'm still not great with some parts of it.

**Comment by smiths** [comment]
Yes!  We definitely need this kind of documentation.  Since you are now an expert, I'm going to assign this issue to you.  :-)

**Comment by danscime** [comment]
Documented via #1653
