### ISSUE TITLE
Icon for website

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1633]
Do we want an icon for our site?

I have made the change required for adding an icon in d429c515b16bf940a4b0e1632becb2c3d4bc2809 as a template.

<img width="261" alt="Screen Shot 2019-06-27 at 9 45 35 AM" src="https://user-images.githubusercontent.com/28261339/60271439-5ba20b80-98c0-11e9-91b3-bbf8608c8d50.png">

**Comment by smiths** [comment]
An Icon is a great idea.  I like the idea of using a D, but could we put the D in a "Viking" font?  Drasil comes from Yggdrasil, which is part of norse mythology.  I don't know how hard it would be to do, but I could imagine a tree icon.  That would be neat!

**Comment by danscime** [comment]
I could try designing something, we could discuss more in today's meeting.

That's a pretty neat fact I never knew about the project!

**Comment by smiths** [comment]
I'm not surprised that you don't know about the origin of the word Drasil, but that just further highlights that our web-page is inadequate.  Good thing we are working to improve it!

**Comment by danscime** [comment]
Created new icon in 5726c51091b112b3a4715dd3640a0da306e938e7.

![Icon](https://user-images.githubusercontent.com/28261339/60359115-122bec00-99a6-11e9-991c-1c2d24c814d4.png)

<img width="174" alt="Screen Shot 2019-06-28 at 1 10 31 PM" src="https://user-images.githubusercontent.com/28261339/60359148-24a62580-99a6-11e9-9b4b-14a210c668a8.png">

**Comment by smiths** [comment]
Neat!  That is a cool looking logo @danscime.  Well done.  I really like the top of the tree and the roots.  I do have a few suggestions though:

- the trunk gets wider as it goes up, which is the opposite of how most trees grow.  Could you make the trunk get narrower as it goes up
- the yellow of the D gets lost in the small version - could you make it a darker shade of yellow?

Could I also see the logo in grey scale?  I'm curious to see how much it relies on colour.

I think you band should definitely hire you to do their logo!  😄

**Comment by danscime** [comment]
<img width="139" alt="Screen Shot 2019-06-28 at 2 21 51 PM" src="https://user-images.githubusercontent.com/28261339/60362906-1bba5180-99b0-11e9-83ab-0aa28cbdc565.png">

Darker yellow.

I could try some other colours to see if they show up better.

**Comment by danscime** [comment]
<img width="562" alt="Screen Shot 2019-06-28 at 2 20 14 PM" src="https://user-images.githubusercontent.com/28261339/60363067-88355080-99b0-11e9-9727-8df6e7083f3d.png">

Fixed up trunk.

**Comment by smiths** [comment]
Yes, I like that trunk better.  The colour of the D doesn't seem quite right.  Can you try it in green?  (The same colour as the leaves.)  Can you also do a version without the D, just the tree.  To make the tree more balanced (without the D), can you shorten the trunk in that version?

Thanks!

**Comment by danscime** [comment]
Green D

<img width="125" alt="Screen Shot 2019-06-28 at 2 47 06 PM" src="https://user-images.githubusercontent.com/28261339/60364203-a2246280-99b3-11e9-8cd1-73175daf73ee.png">

<img width="628" alt="Icon" src="https://user-images.githubusercontent.com/28261339/60364210-a486bc80-99b3-11e9-98be-2eb8812047ae.png">

**Comment by danscime** [comment]
Tree alone, slightly shortened

<img width="701" alt="Screen Shot 2019-06-28 at 2 49 14 PM" src="https://user-images.githubusercontent.com/28261339/60364367-f3cced00-99b3-11e9-89c1-ac5af4b5847e.png">

**Comment by smiths** [comment]
I like the green!  I also like the tree without the D.  Can you shorten it even more?  I'd like to see what it would look like if the branches and the roots almost formed a circle.

I think we'll have to take these different options to the Drasil team and get additional feedback.  We can also provide more than one logo.  Probably the simplest one should be the one that shows up in the tab.

**Comment by danscime** [comment]
Even shorter, almost circular

<img width="680" alt="Screen Shot 2019-06-28 at 2 53 31 PM" src="https://user-images.githubusercontent.com/28261339/60364597-97b69880-99b4-11e9-8037-418e1181d4f9.png">

**Comment by smiths** [comment]
As always, I reserve the right to change my mind, but right now that is my favourite.  I don't have any further feedback; I'm happy!

I would wear a shirt with that logo on it!  :smile:

I like the version with the D too, but I like this one even better.

Well done!

**Comment by danscime** [comment]
I will make this the current version. The original `.ai` version is also in the repo so we can always edit and change as needed.

**Comment by smiths** [comment]
I got some feedback from my daughter.  Her favourite is the same as mine.  Her feedback was that we should put the roots in the shape of a D.  I can see what she is getting at, but I think that would be too busy.  It is the simplicity of your tree that appeals to me.  It is a clever idea to work the D in, but, in my mind, it isn't necessary.

Thanks @danscime.  Great that the pictures are under version control.

**Comment by danscime** [comment]
Looks pretty good on the browser

<img width="367" alt="Screen Shot 2019-06-28 at 3 13 36 PM" src="https://user-images.githubusercontent.com/28261339/60365662-583d7b80-99b7-11e9-93cf-f3596bbe23c7.png">

**Comment by smiths** [comment]
Yes!

**Comment by JacquesCarette** [comment]
As luck would have, I also prefer the latest one too! ;)

**Comment by smiths** [comment]
Glad we agree!
