### ISSUE TITLE
Improve Derivation Format

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1636]
Derivations in LaTeX should be formatted like they are in the HTML (as shown), with the fix made in both that the highlighted text should be bolded:

![gdefs](https://user-images.githubusercontent.com/35857611/60293782-f06f2e00-98ed-11e9-8278-f1f3b29bd1d4.png)

**Comment by smiths** [comment]
@samm82, please include a screen shot for this.  It is difficult to explain in words, but the picture will clarify the potential improvements in formatting that we could make.

**Comment by samm82** [comment]
I think for this, we would want to add a `Derivation` constructor for `LayoutObj`, but I'm not sure if that would be a good design decision. Currently, derivations are just being treated as `Paragraph`s, which means they are being generated as expected, and can't be customized to how we want them displayed.

**Comment by JacquesCarette** [comment]
`LayoutObj` is definitely the wrong place for adding a 'format' specialized to `Derivation`. What we need is to have a more 'semantic' `Derivation` data-structure that can be attached to DD, TM, IM and GD that gets rendered down to `LayoutObj`. We're not re-using the information in a derivation right now, but it is quite clear that, in the future, we will.

**Comment by samm82** [comment]
I've updated the `Derivation` type to take a `Sentence` (the heading) and a `[Sentence]` (the derivation), but I can't figure out how to use it to its full potential since derivations are compressed to `[Contents]` in `docLang`. The HTML is fine (and the desired spaces were added between chunks with no derivation), but the LaTeX is still missing proper spacing, and both versions don't have the heading bolded.

**Comment by samm82** [comment]
As of b57f6cd9c, the heading is bolded.

**Comment by samm82** [comment]
How's this in the LaTeX? @smiths 

![latex](https://user-images.githubusercontent.com/35857611/60609454-b095c400-9d8f-11e9-8b0c-4ac825aadd38.png)

**Comment by samm82** [comment]
And this for the HTML? @smiths 
![html](https://user-images.githubusercontent.com/35857611/60609859-99a3a180-9d90-11e9-9f7f-17b0f4c19b2c.png)

**Comment by smiths** [comment]
@samm82, the screenshots of the new formatting for detailed derivations definitely looks better.

@JacquesCarette pointed to a deeper issue that detailed derivations should be attached to the chunks that use them.  The Layout is separate from the information.  Do we need to create an issue that makes sure that we don't lose track of this future fix?

**Comment by samm82** [comment]
Probably? I'm not sure exactly how @JacquesCarette wants that done. Currently, the derivations are attached to the "chunk" (TM, DD, etc.), but not the "chunk" (as in the concept). I'd wait until @JacquesCarette's review

**Comment by smiths** [comment]
Sounds good @samm82.
