### ISSUE TITLE
Bold Table Headings in LaTeX

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1640]
The headings of the reference tables should be bold in LaTeX:

![image](https://user-images.githubusercontent.com/35857611/60296264-b56ff900-98f3-11e9-99e2-50334fb2b88b.png)

**Comment by smiths** [comment]
@samm82, this issue isn't descriptive enough for someone else to understand it.  Please add a screen shot of the table that doesn't have bold in the heading.  This will help us remember what we were talking about, especially if we don't get back to it right away.  It will also help others judge whether this is a real issue, or just a personal preference of @smiths.  😄

**Comment by JacquesCarette** [comment]
So that "should be bold" could be backed up by reference (even Wikipedia!) on style that recommends this, for example.

**Comment by smiths** [comment]
Yes, a reference that backs up our formatting would be great.  Eventually we want the formatting style to be a user selected variability.  My motive at the moment is just to make it easier to review these documents.  When the table of symbols spilled to a second page the header and the entry in the table were formatted in the exact same font.  This made it difficult to quickly determine whether the first entry in the table was the header or an entry.

@samm82, can you investigate the recommended style for tables in scientific writing.  I'm sure you will find resources that you can provide us with links to.

**Comment by samm82** [comment]
A lot of sources don't have the headers bolded, but [this one](https://dl.sciencesocieties.org/files/publications/style/chapter-05.pdf) does, and the example on page 5-3 resembles our Table of Symbols, etc. This, paired with the reasoning presented by @smiths, is more than enough to justify our use of bold headers. Should this information be kept somewhere? @smiths @JacquesCarette

**Comment by smiths** [comment]
@samm82, for now, I think the best place to have the rationale for this change is in this issue.  You have a link above to an "authoritative" source, and we have a rational argument in the comments above.  I can't think of another spot to record this at the moment.  Two things in the future that will give us a better solution:

1. Drasil in Drasil
2. Incorporation of rationale along with knowledge

On its own, I do not think bolding the headings of a table or not is an interesting enough variability to encode as a user's choice.   However, in the future, I could envision us having "plain" and "fancy" options.  Even better would be if we had options based on style guides, like the "Chicago" style, or "Harvard" style etc.  I think this would be too much of a tangent at the moment.  Getting code generation and design decisions working is more important, but if is nice to know that we could incorporate some documentation recipes.
