### ISSUE TITLE
Spacing of Symbols in Derivatives

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1641]
In both HTML and LaTeX, the spacing of the change in a variable (ie. *dt*) in derivatives should be fixed to match the display in integrals:

![image](https://user-images.githubusercontent.com/35857611/60295591-1ac2ea80-98f2-11e9-91be-06fd93dcd377.png)

**Comment by smiths** [comment]
@samm82, this issue isn't descriptive enough for someone else to understand it.  Please add a screen shot of the equation with the derivative that is too spaced out.  This will help us remember what we were talking about, especially if we don't get back to it right away.
