### ISSUE TITLE
Add Short Label to Information Presented for Each Chunk in HTML SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1643]
I would like it if each "major" chunk types (TM, GD, DD, IM) incorporated its short label into the information presented for each chunk.  When we reference the chunk a label is created that has a nice name, but we don't actually see this short label when we review the original definition of the chunk.  Consider the example of "Position vector as a function of time for 2D motion under constant acceleration":

![NoShortLabel](https://user-images.githubusercontent.com/1422000/60294381-3c6ea280-98ef-11e9-9273-12fe620ec50a.png)

In IM: calOfLandingTime, I can find out that the short name for this is GD: posVec, but there is nothing in the definition of the GD that actually tells me what short name will be used to reference it.  I noticed this issue when reviewing #1628.  The short names were used, but I had to deduce the short names from the long names to read and understand the issue.  We used to keep the short names (in the form of a number) in the manual versions of the case study.  This made it easy to look up a particular chunk.  It is now actually harder, even though the names are better.

I would like to see a new field for each chunk that just reproduces its short name.  (I can't remember if I should say name or label.)  We already have the short names available, so hopefully this isn't too difficult.  @JacquesCarette and @Mornix will likely have advice to offer.

**Comment by samm82** [comment]
In the LaTeX, this is done automatically:

![image](https://user-images.githubusercontent.com/35857611/60294772-23b2bc80-98f0-11e9-9605-2fe66ea3b86e.png)

Should I just add similar functionality to the HTML, where it is the first row of the table? @smiths

**Comment by smiths** [comment]
Yes, I meant in the html.  I like the way it works in the LaTeX, but sometimes I review documents from the html (especially when there is a big traceability matrix!).  They are difficult to read when they don't have a RefName explicitly given.  Was there a specific reason this functionality wasn't extended to the html version?  This might be a question for @JacquesCarette.  I know it would be an improvement from my perspective if the html behaved like the LaTeX version for this.

**Comment by JacquesCarette** [comment]
There's no reason that the HTML can't also have the RefName line. This is likely just an oversight.

**Comment by smiths** [comment]
Sounds good @JacquesCarette.  @samm82, can you please look into adding RefName to the html output.
