### ISSUE TITLE
Tiny Text

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#1649]
Tiny does not have an Instance Models section. 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1929800/60351893-bad15000-9994-11e9-844b-c652981b2fe5.png">

It does refer to it though. I've already made the text (and more importantly the non-existent reference) not show up on a local branch. However the SCS blurb is then empty because both sentences refer to IMs. What should the intro say (if anything) if there are no IMs? 

Same goes for the DDs intro.

**Comment by Mornix** [comment]
/ccing @smiths because I forgot to do that previously.

**Comment by smiths** [comment]
@Mornix we haven't yet determined the rules that make an SRS valid, but my instinct is that an SRS is not valid if it does not have any IMs.  The IMs are where the inputs and outputs are listed.  In my thinking, we can't generate code without IMs.  I know that we do generate code, but really the DDs are there to support the actual IMs.

My preferred fix would be to make tiny have instance models.  The DDs that it has could be changed to be IMs.  In that case the DD section should disappear.

Having said the above, there is still the problem that sections may reference sections that don't exist in their boilerplate introductions.  My first thought is that we should generate all of the introductory text as a "roadmap" of the sections that are included.  The text for the roadmap introductions could provide a generic definition for the sections, at least to start.  The knowledge for sections could consist of section definitions, the same as the knowledge for symbols and concepts have definitions.  Some potential definitions are:

Solution Characteristics Specification - The solution characteristics specification refines the general (abstract) problem to be solved by making decisions that lead to a specific (concrete) problem that can be solved.

Data Definitions - Data definitions provide supporting information for the other sections of the report.  Data definitions are used by other sections of the report to provide complete the information.

We should refine the above generic definitions, but that is a start.

**Comment by Mornix** [comment]
To clarify, @smiths, is the new boilerplate for SCS and DD to be applied to all examples, or any example (Tiny) missing an IM section (for now)?

**Comment by Mornix** [comment]
Bump @smiths

**Comment by smiths** [comment]
@Mornix, can we start with Tiny and see how it looks?  We can then decide whether to propagate to the other examples.  My thinking is that we probably will, but I don't want to rush into changing everything.  During our meeting tomorrow (Thursday), I would like to discuss the definitions for documentation concepts.  I don't know if we already do this, but it seems to me that it would make sense to have definitions for sections the same as we do for the concepts.

**Comment by balacij** [comment]
I'm going to close this in favour of #1415, but please feel free to re-open if you believe they're not similar enough.

(linking the ticket specifically so that we don't lose the information, but it should also re-occur as we work through #1415 eventually)
