### ISSUE TITLE
Projectile review

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1654]
Sam, can you add Projectile info to this page please?
https://github.com/JacquesCarette/Drasil

Sections:
- Building Specific examples
- Running the example(s)

**Comment by oluowoj** [comment]
@samm82, I see that you added the variabilities of speed, velocity and acceleration to physics.hs, is it so they can be reused by other examples in future?  In other examples we have some of the variabilities in Unitals. @JacquesCarette, ideally, what goes into Unitals.hs ?

**Comment by samm82** [comment]
Yes, I added the concepts of speed, distance, and some other quantities, because they are common enough that they would be reused. Concepts like velocity and acceleration were already defined in Physics.hs for this same reason.

**Comment by oluowoj** [comment]
Yeah that makes sense.

**Comment by oluowoj** [comment]
@smiths, are the information in data definition, general definition and theoretical model sections example driven? e.g can we have velocity as a data definition in one example and as a theoretical model or gen. definition in another example?

**Comment by smiths** [comment]
@oluowoj, yes, a concept can be a different classification in a different example.  Something like conservation of thermal energy is probably always going to be a theoretical model, but the other information moves around depending on the problem.  For instance, the definition of acceleration is a theoretical model in Projectile, but it could very well be a data definition in another example.  What matters is how it is used.  If it is refined from general to specific (abstract to concrete), then it is a theory, or maybe a general model, or instance model.  The data definitions are not refined, but they can be used.

**Comment by JacquesCarette** [comment]
What goes into an example's `Unitals.hs` should be those units that just specific to that example. Ideally, it should be empty! As we discover more opportunities for sharing, we should generalize.
