### ISSUE TITLE
Improve try-catch statements in GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1675]
Currently the `catch` portion of a GOOL try-catch declares a variable `exc` for the caught exception in Python, Java, and C#, but not in C++. That inconsistency is bad, but also our code generator never uses the `exc` variable, so the C# compiler complains (via warning) that a variable is declared but not used. 

I have 2 possible fixes:
1. Update `tryCatch` in GOOL to not catch the exception as a variable. So instead of `catch (Exception exc) { ... }` it would just generate `catch { ... }` (using C# as the example but it would act similarly for all languages)
2. Implement a `try` function in GOOL that generates a try-catch statement where the catch behaviour is not user-defined, but instead just automatically generated as a print of the string associated with the caught exception. So, in C#, it would generate `try { ... } catch (Exception exc) { Console.WriteLine(exc) }` (and similar for other languages)

My feeling is that GOOL should offer both options, but we should use option 1 in this case because we define some custom behaviour for the catch.

**Comment by smiths** [comment]
@bmaclach, I agree with your plan to have both options, and I agree that option 1 would be the choice for the current example you mentioned.  The default could be that the behaviour is not user defined (your second option), but there is an option to define the behaviour when needed.  In the Parnas style MIS the exceptions are usually just given as Exception names in the spec.  When I have students implement the MIS in class, they just generate an error message string, along the lines of what you described.  Automating this behaviour as the default seems reasonable.  @JacquesCarette might also have something thoughts on this.

**Comment by JacquesCarette** [comment]
@bmaclach I think you did end up needing more, and then implemented something - right?

**Comment by bmaclach** [comment]
I implemented option 1 (from the original issue description). A need for anything more hasn't yet been encountered. I left this issue open because something like option 2 hasn't been implemented, but maybe we should close it because there is not yet a need for it?

**Comment by JacquesCarette** [comment]
Right - no need, so this is done.
