### ISSUE TITLE
refdb to _refdb in SystemInformation.hs

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1683]
Is there any particular reason why the field is `refdb` instead of `_refdb`?
If not, I can make this change to make it consistent with the rest of the fields.

<img width="786" alt="Screen Shot 2019-07-09 at 4 48 26 PM" src="https://user-images.githubusercontent.com/28261339/60921822-6ae26b00-a269-11e9-908b-56d6993ead51.png">

**Comment by smiths** [comment]
@danscime, I don't know the answer to your question, but you should probably @ someone to get an answer.  It might slip through the cracks otherwise.  @bmaclach may know the answer to your question, or @JacquesCarette?

**Comment by JacquesCarette** [comment]
It is because we didn't want a lens for `refdb` (at some point in the past), either for name-clash reasons or for (obsolete) type reasons. Right now, I don't immediately see a reason not to.

**Comment by danscime** [comment]
This was changed in #1148, specifically 4dfc5870fd04cffab3f2fc2f06d03f1d98d5c514.
@Mornix any reason why the underscore was removed?

**Comment by JacquesCarette** [comment]
That work was really mine that @Mornix cherry-picked. I'm guessing there might have been a name conflict or something.  The point is that a `Setter` (part of `Lens`) is not needed, so why bother? But there's also no harm in having it.

**Comment by danscime** [comment]
@JacquesCarette so should I change it or leave as is?

**Comment by JacquesCarette** [comment]
If you have an active reason to change it, do so, otherwise leave it as is.

**Comment by danscime** [comment]
No active reason, I'll leave it and close the issue.
