### ISSUE TITLE
Consistent Example Names [Chipmunk vs. GamePhysics] [HGHC vs. Tiny]

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1684]
A consistency and design issue.
Throughout the project, there are inconsistencies when referring to Chipmunk/GamePhysics and HGHC/Tiny. I feel like one name should be chosen to be used for each example.

This would be especially useful for  when new users or visitors to our project see references to the examples.

I believe the name Tiny should not be used as it is not descriptive of the program.
I also think GamePhysics would be preferable to Chipmunk.

Thoughts?
@smiths @JacquesCarette

**Comment by oluowoj** [comment]
@danscime I will go for GamePhysics rather than Chipmunk

**Comment by JacquesCarette** [comment]
My preference is indeed for 'gamephysics' and 'hghc' as the standard names.

**Comment by smiths** [comment]
Thank you @danscime for working to improve the consistency.  I have the same preferences as @JacquesCarette.
