### ISSUE TITLE
Implement data structure for GOOL Methods

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1687]
The underlying data structure for methods in GOOL is currently `(Doc, Bool)` in most languages. This should be replaced with a new data structure that holds more information. Specifically, it should hold the list of `Parameter`s for the method. Then, all of the parameters to `docFunc` and `docInOutFunc` except for the `String`s can be replaced with a single `repr (Method repr)` parameter.

**Comment by JacquesCarette** [comment]
Generally, most data-structures that are currently pairs (or worse, a raw `Doc`) might need to be upgraded to records that contain more inspectable information. Making them records ought to mean that some new information can be added later without needing to change code, assuming accessors were used (and not pattern-matching).

**Comment by bmaclach** [comment]
@JacquesCarette For types that are currently just `Doc`, are you suggesting I preemptively change them to a record now (with only one field)? Or should I update each type to a record on an as-needed basis?

**Comment by JacquesCarette** [comment]
Probably as-needed, unless it is very predictable that it will acquire another field soon.
