### ISSUE TITLE
New Line Spacing in LaTeX

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1691]
From [this comment](https://github.com/JacquesCarette/Drasil/commit/a83be2573b7653c69d3bbf1c206d5cc113ad1f9a#commitcomment-34253060) on #1679, the LaTeX has trouble with new paragraphs, since there needs to be an empty line between two lines in the LaTeX for them for there to be a new line in the PDF. This was noticed in the Notes section first, but probably comes up in other places. Compare the following from the HTML and LaTeX:

![html](https://user-images.githubusercontent.com/35857611/61002629-f1fa1680-a32f-11e9-870c-792f858fbb04.png)

![latex](https://user-images.githubusercontent.com/35857611/61002693-181fb680-a330-11e9-9a20-7a08be67280d.png)

**Comment by JacquesCarette** [comment]
A solution here might be to see the notes as an itemized list where the item indicator is empty. If these are internally represented as paragraphs, then it might make sense to interleave \par inside such lists.
