### ISSUE TITLE
Rename DataDefs in SWHS

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1694]
Some DataDef variable names should be updated to not contain numbers.

<img width="412" alt="Screen Shot 2019-07-11 at 2 12 50 PM" src="https://user-images.githubusercontent.com/28261339/61074562-fed94180-a3e5-11e9-930c-c55eb1f3efbe.png">

**Comment by smiths** [comment]
I agree.  Good catch.
