### ISSUE TITLE
Add Projectile to SRC_EXAMPLES in Makefile

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1695]
In the `Makefile`, should projectile be added to `SRC_EXAMPLES`?
@bmaclach @samm82 @Mornix 

<img width="544" alt="Screen Shot 2019-07-11 at 3 21 12 PM" src="https://user-images.githubusercontent.com/28261339/61078880-a9099700-a3ef-11e9-8b38-fab3c246f3e8.png">

**Comment by bmaclach** [comment]
Yes. I think that's done on @samm82's branch for projectile code generation, but that hasn't been merged yet.

**Comment by samm82** [comment]
Can confirm 👍

**Comment by danscime** [comment]
@samm82 Can we close this?
