### ISSUE TITLE
Should Input Structure choice affect modularization?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1699]
Currently the `Bundled` vs. `Unbundled` choice not only determines whether we bundle the inputs, it also affects the modularization of the program:

- With `Bundled` chosen, there are separate modules for the InputParameters class, calculation of derived values, and input verification.
- With `Unbundled` chosen, the calculation of derived values and input verification are both in the "Input Parameters" module.

It seems to me like this should actually be two separate choices - one for whether the inputs should be stored in a class, and one for whether the input-related tasks should be all contained in a single module. Do you agree @smiths and @JacquesCarette?

Also, if the choice is made to combine them into a single module, shouldn't the function for reading the input also be part of that group? I'm guessing it was left out originally because the Input Format module was essentially hardcoded as a module previously, but with my recent changes to the generator it should be easy to put the input format reading function into a different module if we wanted.

**Comment by smiths** [comment]
@bmaclach, I agree with everything that you said:

- the modularization (input tasks separated between modules or not) is a separate choice
- yes, if everything is in one module, then the function for reading the input should also be in that group

Although I think this is a real variation point, I don't think it is a very interesting or practical one.  The version where everything is combined seems like the better design choice to me.  If we had a problem where verification was independent from input, then it might make sense to separate them, but every time we input numbers, we verify the numbers; it really is only one task - get the verified inputs.

If this is easy to do, and it sounds like most of the infrastructure is already in place, then we should do it.  I wouldn't prioritize this though, if it is going to be time consuming.

We should continue to brainstorm for variation points.  The variability of switching from file input to user provided input might be interesting.  For simpler programs, the option of a command line interface where the user types in the values is still something that is seen.

The variations you mention in our last meeting about file formats would be interesting too.  For instance, the parameters of variation could change the separator characters (comma and newline to something else).

**Comment by bmaclach** [comment]
@smiths You're right that the infrastructure is basically already there. This shouldn't be very time-consuming, so I think it's worth it to do.

I've just created #1716 for the choice about input formats.

**Comment by JacquesCarette** [comment]
Agree on all points.
