### ISSUE TITLE
Follow Getting Started Steps for MOOSE

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1702]
@danscime, so that you can keep busy, and do something interesting and useful, please follow the getting started steps for MOOSE and prepare a presentation for the group.  I would like to know how much overlap there is between MOOSE and Drasil.  I do not know much about Drasil, but down the road, I could see us generating MOOSE code.  We don't need anything fancy for the presentation, but you should keep notes on the steps you take and experiments you make, and on your impressions.

Since this work is tangential to Drasil, I suggest that you put it in the People folder (where there are currently folders for Dan and Steve).  I'm sure you wouldn't do this, but don't put the MOOSE code (or any necessary libraries) under version control.  Your experience and hints for installation though would be a great thing to include in the repo, so that others can learn from your experience.

If you have any questions, don't hesitate to ask.

**Comment by danscime** [comment]
https://mooseframework.org/

**Comment by smiths** [comment]
Yes, that is the link.  I meant to include that in the original message.  The getting started guide is at:

https://mooseframework.org/getting_started/index.html

**Comment by danscime** [comment]
After some troubleshooting and installations, I have been able to have Moose return a successful passing test.

I have also included my [installation notes and steps](https://github.com/JacquesCarette/Drasil/blob/mooseInit/People/DanScime/Notes/Moose%20Installation.txt).

<img width="571" alt="Screen Shot 2019-07-18 at 10 05 13 AM" src="https://user-images.githubusercontent.com/28261339/61464027-90dfcd80-a943-11e9-83c8-a87e33057303.png">

**Comment by smiths** [comment]
Great!  Thanks @danscime.  The installation instructions look good.  

The next step on this is to figure out the required input for a MOOSE program.  It seems like a family of PDE solvers, so ideally, it would be nice to figure out what the potential variabilities are.

**Comment by danscime** [comment]
Should this issue be closed for now?

**Comment by smiths** [comment]
Yes, we can open it again in the future.
