### ISSUE TITLE
Revisit Else Case in Cases

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1704]
As mentioned in #1664, the current fix for else cases in case statements might want to be revised.
The relevant proposals have been pasted below (I think I got all of it?)

>We could replace the last else if branch with else, or add a 4th else branch with some dummy return, or initialize a variable with some placeholder value, then assign to the variable in each branch of the if, then return the variable. I prefer the first option because it doesn't require any dummy or placeholder assignments, but it assumes that every Case Expr in Drasil is set up properly so that the last case is equivalent to an "else" statement.
@bmaclach 

> With respect to the case statements, the simplest solution is to add an else statement at the end that returns an error message.
@smiths 

>Completeness of piecewise-defined functions is a semantic property that can be arbitrarily hard to verify -- even though all the ones in our current examples are trivial. What this means is that we need to know a priori whether our "cases" are complete or not; when they are, we can generate code straightforwardly by dropping the last condition and using else. When they are not, or not marked complete, we should generate code with an extra else that throws an error.
@JacquesCarette

**Comment by bmaclach** [comment]
@JacquesCarette Based on your comment quoted above, should we add a parameter to the `Case` constructor for `Expr`? The parameter would be of the following type (which doesn't exist yet):
`data Completeness = Complete | Incomplete`
Then our code generator reads the type and does one of the two cases you've laid out above. If `Complete`, replace the last case with `else`. If `Incomplete`, add the `else` case with an error.

**Comment by JacquesCarette** [comment]
Yes, exactly.
