### ISSUE TITLE
Automatically Translate Unicode in Variable Names

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1705]
Instead of passing in an `Implementation` `Symbol`, we should be able to convert symbols with Unicode in them to their word forms (ie. "θ" -> "theta"). There would still be an implementation level symbol, but it would be automatically generated.

**Comment by samm82** [comment]
@Mornix you mentioned something along the lines of an existing library that automatically does this mapping - I haven't been able to find it yet. Do you know the name of it offhand?

**Comment by samm82** [comment]
I think I found it @Mornix

**Comment by smiths** [comment]
@samm82, why not provide the name of the library in your comment?  That way you can verify it with @Mornix, and the name is recorded for others that may read this thread in the future.  😄

**Comment by samm82** [comment]
Good idea! 😂 [unicode-names](http://hackage.haskell.org/package/unicode-names) is the package - I have yet to fully test it, but I think it might be what we're looking for.

**Comment by smiths** [comment]
Looks like the right package to me.

**Comment by Mornix** [comment]
Yup! That was the one I spotted yesterday. Would definitely want to blacklist the ASCII range and fixup the returned name to replace underscores and hyphens.

**Comment by samm82** [comment]
I'm fairly confident I'm on the right track! I'll tag you as a reviewer in the PR @Mornix if you'd be interested 😊

**Comment by samm82** [comment]
The branch is unicodeSymbolConvert, by the way

**Comment by Mornix** [comment]
I took another look at the library, the official unicode names are more descriptive than I was thinking. Still could be a reasonable way to "automate" conversion of selective ranges of unicode characters like Greek letters.

**Comment by samm82** [comment]
This specific code here deals with that, and it's working so far:

https://github.com/JacquesCarette/Drasil/blob/102284255e7c387ee01e5b71bbac02e70ddf8b6b/code/drasil-lang/Language/Drasil/Symbol.hs#L158-L160

**Comment by Mornix** [comment]
One issue I can foresee is 𝜃 and θ both return "theta". ϴ will return "symbol". Dealing with accents also adds some complications.

**Comment by samm82** [comment]
Do you think it would be acceptable to deal with those as they come up, or should I try to make this comprehensive? I'll take a look at it and see what I can do right off the bat.

**Comment by JacquesCarette** [comment]
Sorry that I didn't see this issue yesterday. As I commented on some commit, this is a very bad idea.

We need to have users explicitly choose the ASCII names for their symbols. They may choose to use a function we provide (such as `unicodeString` !) to do so, but it must be their choice. Otherwise this will lead to weird unpredictable behaviour. If `unicodeString` ever changes internally, this would have knock-on effects, and that is undesirable [to say the least].

And, as has already been pointed out, name collisions would also be a nightmare.

**Comment by samm82** [comment]
So what would a better solution be? Pass an option to the `dqd` constructor for how to handle the symbol? I think the options could be `Basic` (to automatically get the just the symbol name eg. "theta"), `Cap` (to automatically get the symbol name and capitalization eg. "small theta" or "capital theta") or `Custom` (to pass a custom symbol for the `Implementation` stage). Then the user would decide which option would glean the correct symbol name for the code. 

This still has the problem of not working for all symbols. Should I try to make `unicodeString` as comprehensive as possible or should I just leave it as an error for now so we can improve it as needed? I'm assuming at some point it should be complete, but I'm not sure if it would be worth the time right now.

**Comment by JacquesCarette** [comment]
Our symbols already support having completely different representations at specification-time versus implementation-time. That feature should be used.  Yes, some kind of convenience "builders" for common cases would be nice. No, these would not work for all cases, and in those cases, users would be expected to provide a proper functor that is staged.
