### ISSUE TITLE
Choices Table on Webpage for Examples 

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1711]
Discussed in #1630.
We want the webpage to easily display the choices for each example when generating code. The table will list all examples and their current choices found in their main.hs file.

Ex. GlassBR
<img width="292" alt="Screen Shot 2019-07-15 at 12 11 34 PM" src="https://user-images.githubusercontent.com/28261339/61231221-b5486980-a6f9-11e9-9177-bfa94c527a1a.png">

**Comment by JacquesCarette** [comment]
@bmaclach I think you've done this?

**Comment by bmaclach** [comment]
Yes. Choices tables are on the webpage. This can be closed.
