### ISSUE TITLE
Add descriptions for all parameters for generated doxygen comments

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1718]
Many of the doxygen comments for function parameters in generated code currently say "No description given", because these parameters don't come from quantities in Drasil and thus do not have descriptions associated with them. In general, not all variables in the generated code will correspond to a quantity in Drasil, so we need to implement a way to add descriptions to such variables that we can print in the doxygen comments.

**Comment by JacquesCarette** [comment]
Right - I guess these are "design introduced variables"? We should indeed be able to create these too. They should probably also be some kind of Quantity, just for a different stage.

**Comment by bmaclach** [comment]
Yes, these are "design introduced variables" like the `inParams` object for holding the input values if `Bundled` inputs are chosen.  For the variables which do have descriptions already, they are `CodeChunk`s, which are built from `QuantityDict`s.
https://github.com/JacquesCarette/Drasil/blob/9cd8f1c769f6374cbd8f41c2c790de5294afa078/code/drasil-code/Language/Drasil/Chunk/Code.hs#L66-L68
I'm thinking we should make `CodeChunk`s out of these "design introduced variables" too. Which means we will need to make `QuantityDict`s for them (and this goes with what you said about how they "should probably also be some kind of Quantity"). A `QuantityDict`'s symbol is parameterized by the `Stage`:
https://github.com/JacquesCarette/Drasil/blob/9cd8f1c769f6374cbd8f41c2c790de5294afa078/code/drasil-lang/Language/Drasil/Chunk/Quantity.hs#L16-L20
And we already have the `implVar` convenience function for creating an `Implementation` stage-only variable:
https://github.com/JacquesCarette/Drasil/blob/9cd8f1c769f6374cbd8f41c2c790de5294afa078/code/drasil-lang/Language/Drasil/Chunk/Quantity.hs#L43-L49
So it looks like we actually have the infrastructure we need for this already. The only issue I see popping up is that we don't have an appropriate `Space` for `inParams` (or any other record-type variable):
https://github.com/JacquesCarette/Drasil/blob/9cd8f1c769f6374cbd8f41c2c790de5294afa078/code/drasil-lang/Language/Drasil/Space.hs#L10-L22
Should we add another data constructor for `Space`? `Tuple [Space]`? @JacquesCarette

**Comment by JacquesCarette** [comment]
Hmm, that's almost right.

`Space` is really meant for modelling-time "types". A `CodeChunk` is, explicitly, at a different `Stage`. So it feels to me like `CodeChunk` ought to contain something **like** a `QuantityDict`, but not equal - in that the `Space` type (at least) should be changed to a `CodeType` (or some such) type.

Having said that, having a `Tuple` in both `Space` and `CodeType` makes a lot of sense.

**Comment by bmaclach** [comment]
So instead of `QuantityDict`, a `CodeChunk` should be built by something like this?:
```
data CodeQuantityDict = CQD { _id' :: IdeaDict 
                        , _typ' :: CodeType
                        , _symb' :: Symbol 
                        , _unit' :: Maybe UnitDefn 
                        } 
```
In addition to changing the type from `Space` to `CodeType`, I changed the symbol from `Stage -> Symbol` to `Symbol`, since this type should only be used in the `Implementation` stage.

**Comment by JacquesCarette** [comment]
I wouldn't necessarily go to `Symbol`, as we might add other stages, so would keep that as is. But otherwise yes.

**Comment by bmaclach** [comment]
@JacquesCarette I started working on this and encountered some more questions. Since `CodeQuantityDict` has a `CodeType` instead of a `Space`, I didn't write an instance of `HasSpace` for it. This meant I also can't write a `Quantity` instance for `CodeQuantityDict`, because `HasSpace` is a prerequisite for `Quantity`. It seems like the main consequence of this is that we won't be able to use the `codevar` function to make `CodeChunk`s from `CodeDefinition`s, because `codevar` takes a `Quantity`. We'll need to write a custom function for that transition, though it would be a very simple one. Does that sound okay to you?

Also, should I write `HasCodeType` and `CodeQuantity` classes and instances for `CodeQuantityDict`, analogous to `HasSpace` and `Quantity`? Since, after this issue is resolved, we will have 3 `Code`-related chunks (`CodeChunk` and `CodeDefinition`, which we have currently, and `CodeQuantityDict`, which will be added here), delegating the method for getting the `CodeType` to a typeclass seems useful. And having a `CodeQuantity` class will mean the custom function for going from `CodeDefinition` to `CodeChunk` can be more generic, and will work with more `Code`-related types we may add in the future.

**Comment by JacquesCarette** [comment]
I think the problem here is `codevar`, I'm not sure it should be constrained to `Quantity`.  Does it ever actually access `Space`? If not, then we should loosen those constraints to be exactly what is actually used.

Yes, we will want some classes 'around here'. But we should pause and design them properly.

Note that `Quantity` is just fine as a class, the problem is requiring a `Quantity` when you don't really mean it.

**Comment by bmaclach** [comment]
Here's `codevar`'s definition:
https://github.com/JacquesCarette/Drasil/blob/81e0cd86e65792ff4ffa1fc28bc6e908fa963ad5/code/drasil-code/Language/Drasil/Chunk/Code.hs#L100-L101
It creates a `QuantityDict` from a `Quantity` using `qw`, then creates a `CodeChunk` from that `QuantityDict`. With the introduction of `CodeQuantityDict`, this would change to:
```
codevar :: (Quantity c, MayHaveUnit c) => c -> CodeChunk
codevar c = CodeC (cqw c) Var
```
where `cqw` creates a `CodeQuantityDict` from a `Quantity`. The `Quantity` constraint is necessary because the `Space` of the `Quantity` needs to be accessed to translate it to a `CodeType` for the `CodeQuantityDict`.

For `CodeChunk`s that originate as `Quantity`s in Drasil, which is a common case, `codevar` is exactly what we need. But for `CodeChunk`s that originate as `CodeDefinition`, we would need something different.

Looking at this again, I'm wondering if `CodeChunk` and `CodeDefinition` should both belong to some new `Code`-related type class, and the functions that require `CodeChunk`s instead require a parameter constrained by that type class, such that we never need to go from `CodeDefinition` -> `CodeChunk`. It seems like `CodeDefinition` should be just an extension of `CodeChunk`. Their current definitions are:
https://github.com/JacquesCarette/Drasil/blob/81e0cd86e65792ff4ffa1fc28bc6e908fa963ad5/code/drasil-code/Language/Drasil/Chunk/Code.hs#L66-L68
https://github.com/JacquesCarette/Drasil/blob/81e0cd86e65792ff4ffa1fc28bc6e908fa963ad5/code/drasil-code/Language/Drasil/Chunk/Code.hs#L106-L109
But I'm suggesting `CodeDefinition` should instead be:
```
data CodeDefinition = CD { _cc :: CodeChunk
                         , _def :: Expr
                         }
```
Which makes it easy to imagine how `CodeChunk` and `CodeDefinition` would belong to similar type classes.

**Comment by JacquesCarette** [comment]
Perfect! I agree with this analysis and its conclusions.
