### ISSUE TITLE
Double Period in GamePhysics References

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1722]
Minor issue.
Double period should be removed.

<img width="751" alt="Screen Shot 2019-07-17 at 11 08 51 AM" src="https://user-images.githubusercontent.com/28261339/61387073-662e4000-a883-11e9-8390-83e5190120d3.png">

**Comment by JacquesCarette** [comment]
Two whole days and still not fixed!  [I'm a sucker for getting small things like this done right away]
