### ISSUE TITLE
Brainstorm and Classify Variabilities

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1739]
As a follow up to our last "all hands" meeting, @samm82, can you please search the literature and brainstorm for program family variabilities.  We are hoping to see as many potential variabilities, and their associated parameters of variation, as possible.  A classification system on top of the variabilities will help us organize them.

Your goal should be a document that summarizes the "best practices" for program family variabilities.  A set of tables showing the variabilities and their parameters of variation would be good.  Each table will be from a different related set of variabilities.  The parameters of variation are the potential values that the variabilities can take.  For instance, for a family of automobiles a variability could be colour and the parameters of variation could be {red, gree, blue}.

To get you started, you can look at my paper on program families in SC:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/git-svn/SciCompAndSoftEngPapers/Smith2006_VersionAsPublished.pdf

There are sample tables for variabilities for Input Assumptions, Calculation and Output.

This paper shows a family of material models (the variabilities are related to the requirements):

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/git-svn/SciCompAndSoftEngPapers/FamilyOfMaterialModels.pdf

**Comment by samm82** [comment]
This is what I have so far. Where should this be recorded?

### Variabilities for Input Assumptions

Allowed structure for velocity vector : {polar coordinates, Cartesian coordinates}
Source of input : {from a file, through the UI, passed in memory}
Encoding of input : {binary, text}
Unit system for input : {metric, imperial}
Labels of axes : {Cartesian, polar}

### Variabilities for Calculation

Check input? : Boolean
Exceptions generated? : Boolean
Gravity : {Mercury, Venus, Earth, Moon, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto}
Account for Air Resistance? : Boolean
Tolerance for Hit : R

### Variabilities for Output

Destination for output : {file, screen, memory}
Encoding of output : {binary, text}
Format of output : {message, offset, message and offset, Boolean}

**Comment by smiths** [comment]
This looks like a good start @samm82.  When I have something that I'm not sure where it should go in the repo, I put it in the Notes folder.  Let's put it there for now.
