### ISSUE TITLE
Improve Use of Symbol Printing Function in LaTeX and HTML

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1756]
`symbol`, defined in `TeX.Print` is only called when printing units, in the last line of `pUnit`.
https://github.com/JacquesCarette/Drasil/blob/81e0cd86e65792ff4ffa1fc28bc6e908fa963ad5/code/drasil-printers/Language/Drasil/TeX/Print.hs#L284-L301

The rest of the symbols are printed through `pExpr`, after being converted to the `Expr` type (defined in `Printing.AST`, not the `Expr` in `-lang`). This issue occurs in the HTML in the same way.

The two fixes I can see for this are below. Which do you prefer @JacquesCarette?
1) If we have a function that prints symbols from `Symbol` (defined in `-lang`), we should use it whenever we print symbols, instead of converting them to `Expr`s, which are a different type and should convey different information. (I'm leaning towards this one.)
2) Defining a new `Symbol` type in `-printers`, like what was done for the `-printers`-specific `Expr`, and update `symbol` to print from that. This seems like a redundant step to me, since the local `Symbol` would be defined the same way as the one in `-lang`, although I could be wrong.

**Comment by JacquesCarette** [comment]
The first thing to do would be to rename `symbol` to something involving `unit`...  perhaps `unitsymbols` ?

The second would be to make this issue self-contained. It's in reference to something else, but I've read so many different things, I can't remember which.

**Comment by samm82** [comment]
1) I think having a `unitSymbol` function is a good idea, but I think it should be kept separate from the main `symbol` function for rendering symbols. (I could be totally wrong, though.)

2) I'm not sure how to make this issue more self-contained than it already is. It came up in reference to another issue, but I think I including all the info needed to tackle this issue by itself. The problem is that `L.Symbol`s and `L.Expr`s are both being converted to `P.Expr` for printing (except for units) which doesn't seem right, since they semantically contain different information.

**Comment by JacquesCarette** [comment]
1. They are, and should be, different.
2. But once we're printing, semantics should make no difference at all. That units are done differently is weird. There is definitely an issue here, I'm still not quite sure what it is though.

**Comment by JacquesCarette** [comment]
Hmm, what's odd is that `Import` seems to pre-process most things, but not units.  Most everything else is rendered to the printing language there. It feels like the units code should indeed just move over.
