### ISSUE TITLE
(%%) vs. ($+$) in LaTeX Printers

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1758]
`(%%)` and `($+$)` are almost interchangeable, and I initially thought (and hoped) that they could be merged, but upon closer inspection, there is one key difference.

`(%%)` uses `mappend`, which uses `($$)` (as shown in the following code), which is _almost_ the same as `($+$)`, except it "overlaps" lines when applicable (see the [Text.PrettyPrint documentation](http://hackage.haskell.org/package/pretty-1.1.3.6/docs/Text-PrettyPrint.html) for more info). So in the cases that I tried, they matched up, but they wouldn't necessary be interchangeable in every case.

https://github.com/JacquesCarette/Drasil/blob/81e0cd86e65792ff4ffa1fc28bc6e908fa963ad5/code/drasil-printers/Language/Drasil/TeX/Monad.hs#L78-L89

However, in most cases where `(%%)` is used, the two lines start left justified, so they wouldn't overlap anyways. Should we decide to use one over the other, or is this now an issue not worth delving into?

**Comment by JacquesCarette** [comment]
I think both are valuable, but it's a bit of an art to decide which to use. I think this isn't worth delving into.
