### ISSUE TITLE
Generate Makefiles as part of Package

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1770]
Currently the generation of Makefiles for generated code happens outside of the context of a `Package`. Now that we have added the ability to generate different types of non-source code files as part of a `Package`, I think it makes sense to move the generation of the Makefiles into that context. This means adding a function for generating the Makefile as an auxiliary file in the `AuxiliarySym` typeclass. This should let us clean out some checks for specific languages in Imperative/Import.hs, specifically:
https://github.com/JacquesCarette/Drasil/blob/9e99ffe5895c4e04f3fb7faed2447dd3e3976c96/code/drasil-code/Language/Drasil/Code/Imperative/Import.hs#L191-L205
The `Runnable` and `BuildConfig` would instead come from class functions.

**Comment by JacquesCarette** [comment]
Excellent!
