### ISSUE TITLE
What to add to Doxygen comments for generated code?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1771]
It was mentioned at a previous meeting that the current Doxygen comments could be enhanced with more information. For parameters, the comments currently only show the "term" (ex. "probability of breakage"). Some ideas of things to add are:
- Showing units in the description for parameters with units (suggested by @Mornix during the meeting)
- Showing definitions of parameters
- Documenting return values
- Author for module-level comments
- Date for module-level comments

I like the idea of showing the units, and that should be quite easy to do. 

Showing definitions is trickier because not every parameter will even have a definition, and for some of those that do, showing the full definition could be overkill (as @smiths mentioned during the meeting, is the full definition of "temperature" really needed?). We could potentially make this configurable, allowing the user to choose a level of `Descriptiveness` for the comments.

Documenting the return values seems like something we would want, though there would be some work involved. We would need to be able to somehow detect whether a function defined in GOOL has a return value, and what the description of that value is. This would be doable for functions defined by their inputs and outputs in GOOL (defined using `inOutFunc`), but most of our functions are generated with the basic, lower-level `function` function. Would we want to instead generate all functions using `inOutFunc`, @JacquesCarette? If not, we could update the GOOL function for generating documented functions with a `Maybe String` parameter corresponding to the description of the return value (`Nothing` if there isn't a return value). This leaves it up to the "user" of GOOL to tell GOOL about the return value, rather than GOOL trying to deduce that information by itself.

Author information is captured in `SystemInformation` and could be passed along to the code generator if we wanted to include it.

For displaying the date, there seem to be some useful Haskell libraries for getting the current date (http://hackage.haskell.org/package/time-1.9.3/docs/Data-Time-Calendar.html and http://hackage.haskell.org/package/time-1.9.3/docs/Data-Time-Clock.html).

Which of the above ideas are worth pursuing? I can create more focused issues for any that we want to actually do. If anyone has other ideas for things to add to the Doxygen comments, those are welcome too.

**Comment by JacquesCarette** [comment]
Units is definitely a good idea, as is author and date.

For definitions, my first thought would be that this should be author-controlled. One ought to be able to 'tag' various bits (like parameters) with additional information, which can then be shown later.

For return values, I agree that detecting this automatically is too hard. Like for definitions on parameters, we should be able to tag the return values as such, and that's what should trigger additional documentation (or none, if some global option to be concise is chosen).

**Comment by bmaclach** [comment]
For the 'tagging', are you thinking this should happen at the GOOL-level? So the underlying records for parameters and values in GOOL would have additional fields for definitions and `isReturn`, respectively? Or were you thinking the tagging would happen "earlier" or "higher up" (i.e. before we start translating things to GOOL)?

**Comment by JacquesCarette** [comment]
I meant both: that tagging would happen pre-GOOL, and that GOOL-level structures would carry more fields, as appropriate.

**Comment by bmaclach** [comment]
#1779, #1783, #1784, #1781, #1782 created for the specific issues raised here. Closing this issue as the question has been answered.
