### ISSUE TITLE
Derivation for Impulse for Collision Response

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1773]
@smiths, working on the derivation for this in Drasil, this was your feedback on this DD, which I agree with.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/43192745/62151799-29c10200-b2cf-11e9-9797-a49fc4101629.png">

It refers to Chasles Theorem, I don't have too much information about the equation of this theorem even online, not sure if its valid to reference this in the derivation.

Reading Chris Hecker's publication(the paper you sent me a while back) on Collision response, impulse for collision response was derived from:

The velocity of an arbitrary point on a rotating and translating body which might be what the manual version refers to as Chasles Theorem:

<img width="150" alt="image" src="https://user-images.githubusercontent.com/43192745/62152394-76f1a380-b2d0-11e9-9400-da0b6e43c3fa.png">

The above equation also references:
Incoming and outgoing Center of Mass Velocities equations:
<img width="81" alt="image" src="https://user-images.githubusercontent.com/43192745/62152694-0b5c0600-b2d1-11e9-9b43-f36346bf09c6.png">

Should this be defined as a DD or TM, which is used to expand "Chasles theorem" or " velocity of an arbitrary point on a rotating and translating body" and then derive impulse(scalar)?
Hope you get my point? Let me know your thoughts.

**Comment by oluowoj** [comment]
@bmaclach, I need to use the variation of these parameters in Drasil:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/43192745/62160041-11f27980-b2e1-11e9-8713-4f739207ad4f.png">

I have already defined the above in Drasil and used for some definitions, but now I need each of these with a subscript f ( to represent the final of those parameters). Is it appropriate to define these as new parameters in unitals or maybe use "atomic" fxn for the subscript version of those parameters? What do you think?

**Comment by bmaclach** [comment]
@oluowoj I don't think you will need to use `Atomic` specifically, because there is a `sub` function for defining symbols with subscript. But yes, you will likely need to define each of these separately in Unitals.hs.

**Comment by oluowoj** [comment]
Yes, that makes sense thanks

**Comment by smiths** [comment]
@oluowoj, please keep one question per issue.  It makes it easier to keep the discussion focused.  :-)  For the classification of IMs, DDs, etc, please follow the guidelines that we have been testing.  Theoretical models are refined from something abstract to concrete.  The chunks that aren't refined, or transformed in anyway are the data definitions.

**Comment by oluowoj** [comment]
All questions are related to Impulse for Collision but I get your point. I will use a separate issue log for subsequent questions I have for @bmaclach.

**Comment by oluowoj** [comment]
@smith I will be adding this 2 equations as DDs. It will be referred by Impulse for Collision - DD
<img width="291" alt="image" src="https://user-images.githubusercontent.com/43192745/62239529-09627780-b3a3-11e9-8311-e87d3cf2ee9b.png">

Do you agree?

**Comment by smith** [comment]
> @smith I will be adding this 2 equations as DDs. It will be referred by Impulse for Collision - DD
> <img alt="image" width="291" src="https://user-images.githubusercontent.com/43192745/62239529-09627780-b3a3-11e9-8311-e87d3cf2ee9b.png">
> 
> Do you agree?

I think you're looking for @smiths :)

**Comment by smiths** [comment]
Aren't  these formulas derived from other information?  That means that they aren't data definitions.  I'm thinking that these would be part of an IM, not DDs.

**Comment by oluowoj** [comment]
Okay,  I see this should not a DD, it's derived from the equation of relative velocity in Collision(of 2 bodies). Those equations are part of the equation that makes up a Data Definition called Impulse for Collision. 

Actually I don't think Impulse for Collision should be a DD, the formula was derived from other information. Maybe this can be a GD? Is that right?


<img width="424" alt="image" src="https://user-images.githubusercontent.com/43192745/62318720-6f660200-b46a-11e9-9407-151c4937af8a.png">

**Comment by smiths** [comment]
Yes, impulse should not be a DD.  A GD makes sense.  The game physics example probably has other inconsistencies in the classification of the chunks.

**Comment by oluowoj** [comment]
Okay, I will look into #1372, this will be dependent on it.

**Comment by JacquesCarette** [comment]
What's the status of this?

**Comment by oluowoj** [comment]
This is completed in PR #1838.
