### ISSUE TITLE
Improve generated error messages for constraint violation

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1775]
As noted by @JacquesCarette in https://github.com/JacquesCarette/Drasil/pull/1762#issuecomment-516847723:

> the generated code has errors with just "constraint violated" in it; while better than no checking, we should definitely improve those error messages to be more informative! At the very minimum, the variable name should be mentioned. Better still would be the expected range and the value that violates it, and the name of the constraint from which this comes.

**Comment by bmaclach** [comment]
@JacquesCarette can you clarify what you mean by the "name" of the constraint? Currently constraints aren't associated with any sort of `Label` in Drasil. Should they be?

Everything else suggested here seems doable. There is a comment in the code about needing an `Expr -> String` function for printing constraints, but I don't think that's true. We already have functions for extracting `CodeChunk`s from an `Expr` (for example, the function `codevars`) and we can print names and values of `CodeChunk`s, so these can be used to print the bounds on a `Range` constraint.

**Comment by JacquesCarette** [comment]
Think of debugging: if such an error get thrown, how will you figure out the cause? And why does this quantity have that constraint? My comment was probably overly specific, my real comment is about debugging + traceability.
