### ISSUE TITLE
Add units to doxygen comments for parameters

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1779]
Doxygen comments for function parameters can be enhanced by adding the units, if applicable, in which the value of the parameter is expressed.

If we want to print units by their name (e.g. "Newton" for Newtons) then this can be done without needing to write any new functions.

If we want to print units by their symbols (e.g. "N" for Newtons), which I think would be our preference, we will need to write a `USymb -> String` function. We have similar functions in the HTML and LaTeX printers, so would the correct place for this function be in the drasil-printers subpackage? Perhaps as the start of a new "String" printer (I think we will soon need an `Expr -> String` function too, so there would be more to add to this printer than just one function, and our current `getStr :: ChunkDB -> Sentence -> String` function in drasil-code's Helpers.hs could also be moved there)? This would make drasil-code dependent on drasil-printers, is that okay? @JacquesCarette

**Comment by JacquesCarette** [comment]
I think we want a third pretty-printer, call it `plain` or `ASCII` or some such.  It would still print to a `Doc`, but try to format things in plain text.

One of the options that that printer should have, especially in some of its exported sub-functions, is a `Linear` option: i.e., print one one-line. That is the function you'd want to use here. (And a call to `render` to go from `Doc` to `String`).  That way if something can't be printed linearly, there's a hope for a decent error message with diagnostics as to the source of the problem.

**Comment by bmaclach** [comment]
Closed by #1792
