### ISSUE TITLE
Add definitions to doxygen comments for parameters

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1783]
This issue stems from #1771. We should be able to "tag" parameters with additional information (i.e. a definition) which can then be displayed as part of the Doxygen comment for that parameter in the generated code. Whether or not to include the definition in the comment could be subject to  a global option.

**Comment by bmaclach** [comment]
@JacquesCarette I still have questions about this one... 

Generated function parameters come from `Quantity`s (or `CodeQuantity`s) in Drasil. For the most part, "users" of Drasil don't interact with parameters directly, but they do interact with the `Quantity`s they come from. So if we want to tag parameters with more information, and if we want the author to control how that information gets tagged, the `Quantity`s need to contain 1. the information to tag and 2. information about whether or not it _should_ be tagged.

Part 1 is already done -- we have `DefinedQuantityDict`s that are tagged with additional information (i.e. the definition). 

Part 2 is where I have questions. I don't think we just want to tag every parameter that has a definition with the definition. We want the author to be able to decide on a per-parameter basis whether the definition is important enough to show in the doxygen comments. We could add an additional field to `DefinedQuantityDict` with some show/hide data type. But then for `DefinedQuantityDict`s in drasil-data, we'd need to decide on either show/hide ourselves, and then provide a function to switch between show/hide so the user can make their own decision?

This also reminds me of talk we've had about using characteristics of the intended reader to determine what information gets displayed, where we can assume that readers know a certain amount and not show definitions if they fall into the categories that the intended readers know.

**Comment by JacquesCarette** [comment]
Excellent analogy with "characteristics of the intended reader".  And yes, `DefinedQuantityDict` is indeed exactly one kind of 'tagged' `Quantity`. Though it is important to note that it's neither an arbitrary tag, nor a dynamically discoverable tag (we had those for a while, called them 'attributes', and they became a horrible mess).

I think we want to use the same process as with the rest of Drasil to move 'tags' from one stage to another: we do an explicit 'query' to populate the information. That way the choice of what to display becomes part of the recipe. And, to go along with the above analogy, the query could be "add all sufficiently interesting definitions". [Of course, we're far from that now, but we need to start providing infrastructure that will move us in that direction].

**Comment by smiths** [comment]
Great discussion!  As a starting point, I think the default for the doxygen comments should be to show all definitions.  That is what we do with the SRS.

**Comment by JacquesCarette** [comment]
Does #1826 close this issue?

**Comment by bmaclach** [comment]
As of #1826, we add definitions to Doxygen comments for all parameters that have definitions. I left this open because we want there to be some flexibility in terms of which definitions get printed, though that seems like part of a much larger design (related to using characteristics of the intended reader to determine what information is needed to be printed), so maybe this issue should be closed in favour of something more high-level or more focused.

**Comment by JacquesCarette** [comment]
Yes, it is better to close the issues when they are essentially done. If there is something 'focused' left-over, then please make an issue. We'll let the "more high-level" stuff arise on its own when the need comes up.

**Comment by bmaclach** [comment]
Opened #2115. Closing this issue.
