### ISSUE TITLE
Use Javadoc instead of Doxygen for generated Java code?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1794]
@JacquesCarette raised the question in #1789 of whether we want to use javadoc for Java code documentation instead of Doxygen.

My thinking is that we could treat this like we plan to do with external libraries (#394), and allow users to choose whether they want Doxygen or Javadoc (or rather, pass in an ordered list of their preferred choices).

**Comment by JacquesCarette** [comment]
I agree with your reasoning.

**Comment by smiths** [comment]
I agree.  We should also add the option of Pydoc in the future, using similar reasoning.  I don't think we should be in a hurry to generate Javadoc, or Pydoc.  Generating doxygen makes the point that we can generate documentation, adding more options adds more work, but without the same payoff.  As far as future enhancements go though, this is a good idea.

**Comment by JacquesCarette** [comment]
I'm thinking that we won't get to this anytime soon, so we should put it in the 'icebox' -- close the issue, but refer to it on the wiki.

**Comment by bmaclach** [comment]
Added to wiki, closing.
