### ISSUE TITLE
Less than, greater than - mathjax

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/Drasil#1819]
As brought up in #479.
It seems like using `\lt` and `\gt` work in the HTML but not in the Latex.

Trying to render the latex with a `\lt` results in "undefined control sequence".

<img width="499" alt="Screen Shot 2019-08-12 at 11 54 34 AM" src="https://user-images.githubusercontent.com/28261339/62878873-f97a5a00-bcf7-11e9-9610-3421423463bd.png">

@JacquesCarette any ideas why this is?
I haven't been able to figure out why yet. Google doesn't seem to know much.

**Comment by danscime** [comment]
Added via cd89d46c1c95a48d66c9d80d11acb9580022f4d5, 6441e6032af864c16b400b40e074751b3086b842, and dbe2d39b66406830953df84c9136a615aff27aa4.

**Comment by JacquesCarette** [comment]
Somewhat related: do we have
```latex
\usepackage[T1]{fontenc}
```
in our prelude?  We should.

**Comment by smiths** [comment]
I agree with @JacquesCarette about `fontenc`, but I had to look it up to see why I agreed.  😄 For others in the future that do not know the rationale, the following link discusses why `fontenc` is recommended:

https://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc

**Comment by danscime** [comment]
Currently none use this. I will add this to all examples.

**Comment by danscime** [comment]
We do use `fontspec` which to my understanding is for utf-8 encoding which gets used by LuaLatex.

**Comment by smiths** [comment]
Great!  Thanks for following up @danscime.

**Comment by danscime** [comment]
Would this overlap with `fontenc`? Should I still add `fontenc`? Or should I create a new issue of `fontenc` vs `fontspec`?

**Comment by smiths** [comment]
@danscime, I actually thought you wrote fontenc.  :-)  You could try google to see if the two interfere with each other?  My guess is that they are different and you can add fontenc.

**Comment by danscime** [comment]
Based on this [LuaLatex Guide](http://ctan.mirror.colo-serv.net/info/luatex/lualatex-doc/lualatex-doc.pdf#subsection.1.2) and this [Stack Exchange Post](https://tex.stackexchange.com/questions/470976/are-there-cases-where-fontenc-luatex-or-xetex-cause-problems),  apparently it is better to use `fontspec` (which we are currently using, and not to use `fontenc`.

**Comment by smiths** [comment]
Great research @danscime.  I agree that we should continue to use `fontspec` and not `fontenc`.

**Comment by JacquesCarette** [comment]
Indeed - and now we need to document that!  In the printer, where it outputs `fontspec`, there should be a mention of this [i.e. we're explicitly using just the one] and a link to this issue for further information.

**Comment by danscime** [comment]
Comments made in 6266a5ac722ed2f85d568f4bfb66bad993e7e1c6

**Comment by smiths** [comment]
@JacquesCarette, great suggestion to document this decision in the code.  I know I don't want to rely on my memory if this comes up again.  I don't have any specific suggestions right now, but we should definitely watch for opportunities to link to our design discussions.

**Comment by danscime** [comment]
Tracked in the mathJax PR #1832.
Updated in 4d8adb546291329921664fcb3e464cfab96f2d8e to use the `ensuremath` command.
