### ISSUE TITLE
GamePhysics: Center of Mass DD Reference in Translational Motion IM

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#1830]
While working on improving the Notes section in GamePhysics, there is a reference to the Center of Mass DD in the Translational Motion IM for no obvious reason and no explanation:
![drasil](https://user-images.githubusercontent.com/35857611/63054388-bbc13100-beb1-11e9-9804-fdf9ca8bc811.png)

The DD defines the position of the centre of mass, and there is no position in this formula. I took a look at the manual version, and noticed:
![caseStudies](https://user-images.githubusercontent.com/35857611/63054255-81579400-beb1-11e9-80ea-dde422a1bded.png)

The equation given isn't actually the output of the IM, but the solutions to it are. This will be best approached with the changes done in #1373 (as we can represent it as a `DEModel`), but for now, what should we do with the reference to the centre of mass DD reference? Should we just leave it there for now and deal with it later (with a FIXME explanation added), or should I remove it?

**Comment by smiths** [comment]
Good catch @samm82.  The Drasil version of GamePhysics is still one of our weaker examples.  :-(  It doesn't even match the manual version, which itself still needs work.  :-(  

For now, let us fix the Drasil version as best we can by updating the Notes field.  Please add something like the following to the notes:

The output of the IM will be the functions of position and velocity over time that satisfy the ODE for the acceleration, with the given initial conditions for position and velocity.  The motion is translational so the position and velocity functions are for the centre of mass (reference DD for Centre of Mass).
