### ISSUE TITLE
Using objVar to access static variables

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1855]
GOOL has the following function for accessing a variable from an object:
```
objVar :: repr (Variable repr) -> repr (Variable repr) -> repr (Variable repr)
```
The first `Variable` parameter is the object and the second is the variable being accessed.

In C#, a static variable cannot be accessed from an object and must instead be accessed from the type directly, so `objVar` will detect when a variable is static and generate the right code. But this seems wrong, because `objVar` is intended for accessing a variable from an object, but in this special case of accessing a static variable in C#, no object is actually being used. Our code generator even generates a `Constants` object that never gets used in C# for NoPCM.

I think accessing a variable from an object and accessing a variable from a type should be considered two entirely different operations, and GOOL should offer two different functions to reflect that. `objVar` would remain the same except it would throw an error if used on a static variable in C#. Then we'd add a new function:
```
classVar :: repr (StateType repr) -> repr (Variable repr) -> repr (Variable repr)
```
for accessing a variable from a type (which should always be a class, thus the name `classVar`). Our code generator can then use `classVar` instead of `objVar` when it's dealing with static variables (I've checked and confirmed that all 4 languages we generate allow accessing a static variable through a class without needing an object).

This seems like the best course of action to me, but I did think of some other options as well:
- Change nothing, but later we can remove the unused variable through code optimization 
- Have our generator check if the current language is C# and then not generate the unused object if so.
- Have our generator generate getters and setters for the `Constants` class, then use those getters and setters instead of using `objVar`. Using the getters and setters would always require an instance of the class, so the currently unused variable would now be used.

These options would all fix the unused variable problem, but the problem with `objVar` being used for something outside of its intended purpose remains, which is why I think they are subpar solutions.

**Comment by JacquesCarette** [comment]
I agree.

I've grown to dislike the idea of internally generating 'bad' code, and then get the optimizer to clean things up later. The optimizer still should exist and optimize, but relying on it to clean up bad code is not a good idea.  Same with special-coding the generator to a language. We need instead to understand the underlying semantic differences, and split things up appropriately, even if in most of our language, the different ways of saying things will lead to the same generated code.

Over the long range, `objVar` should take a 'proper' object as its first argument, which should be statically verifiable by the generator. But that requires more types, and we're not there yet.
