### ISSUE TITLE
Create GOOL subpackage

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1857]
Currently GOOL resides in the drasil-code subpackage, specifically in `drasil-code/Language/Drasil/Code/Imperative/GOOL/`. The drasil-code subpackage also contains our code generator. It would be nice if we could pull out GOOL into its own subpackage, as someone may theoretically want to use GOOL but not the rest of Drasil. The GOOL subpackage should not be dependent on any other drasil subpackages, except maybe drasil-utils.

**Comment by bmaclach** [comment]
@JacquesCarette I started looking into this and where we will run into problems is with GOOL's functions for writing auxiliary files. Writing the Makefile is dependent upon drasil-build and writing the sample input file is dependent on drasil-lang, drasil-database, drasil-code, and drasil-printers. 

Would it make sense to keep the part of GOOL that deals with auxiliary files separate (keep it in drasil-code), while moving the rest of GOOL to its own subpackage? The stuff in the subpackage would still be everything needed to generate code, just not any other files, so I personally think this would still be a useful separation.

**Comment by JacquesCarette** [comment]
Yes, it makes sense to separate those.
