### ISSUE TITLE
Objects whose state get modified should be passed as outputs to GOOL's inOutFunc

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1858]
We recently added `inOutFunc` to GOOL. `inOutFunc` generates code for a function based on a list of inputs, a list of outputs, and a list of things that are both input and output. Our generator uses `inOutFunc` to generate the function for reading inputs. The `InputParameters` object is passed as an input to `inOutFunc`, but we pass an empty list of outputs. I did it this way because I was thinking of outputs as things that the function returns, and since the function does not return the `InputParameters` object (it just modifies the state), I didn't think of it as an output.

Since then I've wondered if that was the right way of thinking, or if the `InputParameters` object should be considered an output since it undergoes a transformation. If so, we would need to update `inOutFunc` to check if each output is an object, and know not to return it if so.

**Comment by JacquesCarette** [comment]
Your new thinking is correct: state should be considered in/out. Anything modified is an output.
I think that if `InputParameters` is a stateful object, maybe it should be in the list that is both?

**Comment by bmaclach** [comment]
Yes, I agree `InputParameters` should be in the list that is both. I'll remove the question label from this issue, as it is now a task to be done.
