### ISSUE TITLE
Use target language's pi (etc.) instead of defining it from scratch

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1862]
Currently our code generator treats pi like any other constant, by defining a variable for it or in-lining its value (depending on the design `Choices` made). But most languages have already defined pi in a math library. We should use these instead of redefining pi (and similar for other meaningful, commonly used math constants). This is a simple case of using an external library. 

My thinking is to add a `pi` function to GOOL. `pi` would generate the code for the value of pi in each language. If the language has pi defined in a math library, then `pi` would generate the text (something like) `math.pi`. If not, `pi` would generate the text `3.14159...`. Our code generator would have to detect when pi is used in an `Expr`  and map that to GOOL's `pi`. It should also detect when pi is included in the list of constants in the `SystemInformation` and remove it, so that we don't create a variable for pi that would go unused.

At first I doubted this idea because it means we treat pi independently of the other constants. If a user has not chosen `Inline` for their `ConstantStructure`, we would be going against that by in-lining the value of pi for the languages that do not define pi in a math library. But upon further thinking, I think this is okay. For even in the case that a user has chosen `Inline`, would we not still want to use `math.pi` for the languages that offer it? It seems to make sense to treat pi (and its ilk) as something different than the example-specific constants which will always need to be defined in the code. 

We might even want to remove the need to add pi to the `constants` field of `SystemInformation` in the first place.

In terms of how to detect pi, what immediately comes to mind is to match against pi's UID, "pi". (In the meeting we talked about this being a matter of concept matching, but I think the UID is the thing we want to compare to achieve concept matching?)

Thoughts, @JacquesCarette?

**Comment by JacquesCarette** [comment]
I agree that the way to detect this is to match the UID "pi".
What I'm much less sure about is the mechanism proposed to get pi from the library. I really do think we need to think this through more carefully.

What comes to mind is that there will be concepts that we 1) define ourselves, and 2) also exist [and mean the same thing] in a language's library. We need a way to do some kind of "concept aligment" (the UID is one decent way to do this). But this should be done generically. And it should be done in each language by declaring an 'alignment' between the generic concept and the implementation provided by the language.  pi shouldn't be special in this way.

**Comment by bmaclach** [comment]
The code we want to generate for pi will be different in each language, so we need to specify what pi is in each language. A `pi` function in a GOOL typeclass is the natural way to do this, I think. I agree that we want to do this in a generic way, so I would propose having a map in our code generator of certain UIDs to GOOL functions. Pi would just be an entry in this map.

I hope that addresses your concerns? The map entries would be the declarations of the concept alignments. You said these should be declared "in each language" but I don't really understand that. Pi will always be pi, regardless of the language. The implementation of pi will be different for each language, which will be handled by the instance of the `pi` function in each language. But the matching of the concept of pi to pi in GOOL seems universal.

What I'm trying to avoid is having to do any sort of UID comparisons within GOOL, because we want to keep GOOL independent of Drasil. I want the matching to happen in Drasil's code generator, which influences the GOOL code we generate.

**Comment by JacquesCarette** [comment]
I completely agree about having the matching be in Drasil, not in GOOL.  And that, in GOOL, it can and should be done via a typeclass method.

pi is, however, still somewhat ambiguous even within mathematics -- see https://en.wikipedia.org/wiki/Pi_(disambiguation).  In SC, it's not, but we may as well plan for the future.

So we need something that maps `pi` as the GOOL-level concept to GOOL. What I am asking is, can this be data, or does it have to be code? I would prefer if it was data.

**Comment by bmaclach** [comment]
@JacquesCarette Ah, I think I'm finally understanding what you are getting at. I think we could do this at the data-level. We could tag our chunk types with a `Maybe Something` where the `Something` establishes a connection between that piece of data and the GOOL function for implementing it. I doubt the `Something` should literally be the GOOL function, since GOOL's types are so weird, but maybe the `Something` could be some enumerated data type we define for concepts that also exist in libraries, and then our generator would define a mapping from this data type to the actual GOOL functions? Whenever the generator uses a `Quantity`, it would check this new tag to see if that Quantity should be handled normally (if the tag is `Nothing`) or if it should map to a special GOOL function (if the tag is `Just`). We wouldn't even need to compare UIDs, then.

If that sounds good, a remaining question would be at which level of chunk we should introduce this new tag. We've been referring to it as an alignment of "concepts", so my initial thought was to add it at the `ConceptChunk` level, but the match to a GOOL implementation only seems useful with regards to a `Quantity` built on top of the `ConceptChunk`. So I think it makes the most sense to add it to `DefinedQuantityDict`s?

**Comment by JacquesCarette** [comment]
You have the general idea correct, but I don't like the implementation details.  Plus, I'm actually happy with `UID`-based lookup!

An alternate implementation would have a table (`Map` in Haskell, indexed by `UID`) of connections. In each slot, we'd have a list of potential connections (including 0); we could also have > 1. These would be ordered. It could be that the first one in the list conceptually fits but is otherwise ruled out for some other reason (perhaps because of a conflicting global choice), so then the next one can be tried, and so on.

So this would be more at the `drasil-gen` level (or so), and in the examples themselves, where you provide a set of concept matches.

**Comment by bmaclach** [comment]
@JacquesCarette Okay, makes sense, thanks. Would the values of this map be (a list of) a new enumerated data type for the different concepts that can be matched?

**Comment by JacquesCarette** [comment]
Start with such an implementation, yes. Then we can see if that's actually a good idea. [It's clearly not a bad idea! But it's also not clear if it's a *good* idea].

**Comment by bmaclach** [comment]
Just to add on - Another example of a dependency between variabilities that we already have is that if `Inline` is chosen for the constant structure, than the constant representation choice is ignored. I think that's the only other dependency we have so far.

**Comment by JacquesCarette** [comment]
I didn't realize that by merging #1938, this issue would get closed.  In any case, I agree with the choice, and also that we need to look at this more carefully.

I'm not a big fan of feature algebras - I think the dependency tracking mechanism they offer is not sophisticated enough to deal with realistic cases.  For example, I'm pretty sure the family of algorithms in my GE paper could not be handled properly with a feature algebra.

**Comment by bmaclach** [comment]
Created #1941 for further discussion about how to document program families.

**Comment by balacij** [comment]
I'm trying to understand `Choices` right now. Specifically, the `ConceptMatch` map, which was created as a result of this ticket.

I think this idea extends to other things, like `sin`. For example, for Java, I would like to use Apache's [FastMath](https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/util/FastMath.html) library for `sin`.

The current design only allows replacing very specific things enumerated in `data CodeConcept = Pi deriving Eq`. Are we intending to add to this enumeration? I'm not sure how large it could get.

**Comment by JacquesCarette** [comment]
Yes, this idea can absolutely be extended. And yes, the current implementation will not scale. Let's worry about the scaling when it is a live issue. In the mean time, let's add extensions as we actually need them, and re-design when that becomes untenable.
