### ISSUE TITLE
Recommend a suitable conference for our GOOL paper

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1864]
As discussed during our (@bmaclach, @JacquesCarette and myself) Aug 29, 2019 meeting, please suggest an appropriate conference for the GOOL paper that @bmaclach is working on.  I will create another issue for @bmaclach to start the paper.

**Comment by JacquesCarette** [comment]
PEPM 2020 - https://popl20.sigplan.org/home/pepm-2020. It's quite soon, but it's feasible.

**Comment by smiths** [comment]
Sounds good @JacquesCarette.  Soon is good for me, because then I can put it on my NSERC grant application.  :-)

**Comment by smiths** [comment]
@bmaclach, if it isn't already in the PEPM format, you should modify the tex file in the GOOL paper folder to match.  There will be a page limit and the format of a tex file can have a huge impact on how many pages.

**Comment by bmaclach** [comment]
Thanks for the heads up, @smiths. Updated format and added to PR #1872. In terms of page limit, from the PEPM website:

> Two kinds of submissions will be accepted: Regular Research Papers and Short Papers.

> Regular Research Papers should describe new results, and will be judged on originality, correctness, significance, and clarity. Regular research papers must not exceed 12 pages (excluding bibliography).

> Short Papers may include tool demonstrations and presentations of exciting if not fully polished research, and of interesting academic, industrial, and open-source applications that are new or unfamiliar. Short papers must not exceed 6 pages (excluding bibliography).

I'm not sure which category ours falls into, but I suspect it's just a matter of the perspective from which we write the paper...?

**Comment by JacquesCarette** [comment]
Let's go for full paper.

**Comment by smiths** [comment]
Agreed.
