### ISSUE TITLE
Factor out more common patterns in GOOL renderers

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1868]
As discussed in the meeting on Aug 29th, 2019, it would be nice to clean up the GOOL renderers more by factoring out more common code in advance of the GOOL paper, but we should be selective in which instances of code duplication we tackle.

We want to be able to quantify the "sharedness" of two renderers in GOOL, so any common code we factor out should be low hanging fruit that makes this quantity more impressive. For example, we want to maximize the number of instances of class functions that are just dispatches to the common functions in LanguageRenderer.hs.

**Comment by bmaclach** [comment]
@JacquesCarette I've started working on this. The following GOOL symantic function:
```
(#~) :: repr (Value repr) -> repr (Value repr)
```
Is defined in all 4 renderers the exact same way:
```
(#~) = liftA2 unExpr' negateOp
```
Is it worth it to factor out the pattern of `liftAx someFunction param1 param2 ...`? This sort of pattern is extremely common in GOOL.

The pro to doing this would mean the function definition would just be
```
(#~) = negateExpr
```
in all of the renderers, and then we could truly say that every renderer defines this function (and others like it) simply by dispatching to a common function. And then for the paper I could count up all functions with that property between Java and C# and use that as a metric of our re-use between the renderers.

The con to doing this is that there's actually a lot of tedious work that has to be done to make that change. Since `negateExpr` would have to be written in the context of the generic `repr`, we would need to add symantic functions to GOOL for accessing the `Doc` of a `UnaryOp`. And then if we are factoring out this pattern all throughout GOOL, we will need to write these `Doc` accessor functions for probably every one of GOOL's current types. And some of the "bigger" types will need accessors for more than just `Doc`.

An intermediate solution could be to not factor out the lifting, but still factor out the parameter passing, so the function would be defined like:
```
(#~) = fmap negateExpr
```
Then we wouldn't need to write all of the accessors, but we could still say that every renderer defines this function (and others like it) by dispatching to a common function _plus some lifting_. And then that would be the property I would use when counting up functions for our re-use metric. I'm leaning towards this option but want to know your thoughts.

**Comment by bmaclach** [comment]
@JacquesCarette Scratch my intermediate solution -- I wasn't thinking right. The operator parameter would need to be passed regardless, because it comes from a symantic function, so a common function written outside of the context of a `repr` wouldn't know what it was unless we pass it explicitly.  

So I guess the 2nd option is just to keep those functions the same as they are now, and then the metric could be all of the functions that lift a common function in both renderers.

**Comment by JacquesCarette** [comment]
I think what should happen is that
```haskell
(#~) :: repr (Value repr) -> repr (Value repr)
```
shouldn't be a class method at all, but a generic function.  At least for now.  It can always be made back into a class method if needed.

**Comment by JacquesCarette** [comment]
Given the two merged PRs, is this essentially done? @bmaclach  There might be more duplication, but that can be dealt with 'in the future'.

**Comment by bmaclach** [comment]
Yes, we've factored out a ton of code in the renderers and they are much cleaner now than they were when this issue was created. As @JacquesCarette there can likely be more done in the future, but I think we are in a good enough place to close this now.
