### ISSUE TITLE
Momentum not defined in Drasil

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1875]
@smiths, just realized we did not define momentum anywhere in Drasil.  I want to put that in Drasil now but lower case p is used up so not sure what symbol to use for it. Ideally p is used for momentum but position vector has taken the p. The only other option is uppercase P or maybe lowercase p and a subscript character. Let me know your thoughts.

**Comment by oluowoj** [comment]
Done in PR #1876

**Comment by JacquesCarette** [comment]
This is an interesting dilemma. We'd want to still be able to use `p` when it's available.  I'll file an issue.  But this one appears closed (since the question has been answered).
