### ISSUE TITLE
Use State monad in GOOL language renderers

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1880]
In the GOOL renderers, it makes sense to store some "extra" information to be used later on to generate better code. An example is storing a list of libraries that are used so that, at the module-level, GOOL can generate only those import statements that are actually needed. For examples like this one, the list would originate at the level of `Value`s, and accumulate as the renderer worked its way up to functions, classes, and finally the module. This accumulating/modifying behaviour can be cleanly implemented with the State monad. 

Note that, if possible, it would be best to do this in small pieces. So we should look for places where the State monad will be useful near the top of the hierarchy, so that we can implement the State monad only for those types near the top, and then slowly spread it down to the lower-levels (as opposed to the example given above where we would need to make everything from `Value`s all the way up to `Module`s use the State monad all at once).

This was discussed at the Sept. 12th, 2019 meeting.

**Comment by JacquesCarette** [comment]
This is done, right @bmaclach ?

**Comment by bmaclach** [comment]
Yes, we now use the `State` monad throughout GOOL. This can be closed.
