### ISSUE TITLE
(SWHS) problem description is too abstract 

### ISSUE THREAD

**Issue by deemaalomair1** [JacquesCarette/Drasil#1882]
@smiths I feel that section 4.1 Problem Description is too abstract. I suggest to add the following:
1. Why do you need to measure the water heat ? the main problem that makes measuring water's heat temperature is important. 
2. Measuring the water temperature will be over time to discover the change in heat level.

**Comment by smiths** [comment]
Thank you @deemaalomair1.  I can see where you are coming from, but I think you might not have realized that Section 4.1 has subsections.  The subsections are what make the problem description less abstract than the introductory blurb for the section.  The subsections give the terminology, definitions, physical system description and goal statements.

With respect to why to measure the heat level, this is essentially covered in the introduction to the SRS.
