### ISSUE TITLE
Projectile Case Study - SRS formatting issues (pdf)

### ISSUE THREAD

**Issue by peter-michalski** [JacquesCarette/Drasil#1883]
@smiths 

SRS formatting issues (pdf  document): 

1. Tables cutting off in Section 5: Traceability Matrices and Graphs

The following tables are being cut off in the pdf of the srs:
TraceMatAvsAll (page 26)
TraceMatRefvsRef (page 26)
TraceMatAllvsR (page 27)

2. Wrapped text is bleeding into the left margin in the following sections:

   3.1.3 Goal Statements (page 5)
   3.2.1 Assumptions (page 6)
   4.1 Functional Requirements (page 24 & 25)
   4.3 Non-Functional Requirements (page 25)

3. Text is wrapping into the footer on top of the page numbers on the following pages:
   18, 20, 22, 23

**Comment by smiths** [comment]
Thank you @peter-michalski.  The issue with the wrapped text is also noted in #1877.  The problems with the traceability matrices is also known.  A solution, using short mnemonics, instead of the full names, is given in #1539.  When that issue is closed, it should fix this issue.
