### ISSUE TITLE
Projectile Case Study SRS - g assumption

### ISSUE THREAD

**Issue by peter-michalski** [JacquesCarette/Drasil#1884]
@smiths 

Does gravitational acceleration need to be further specified in the assumption section to a lunch from Earths surface and at a specific location (at sea level, at the equator, at the poles, or specific gravity)? Or if not, does it need to be stated that the differences in the case study are negligible - similar to how neglectCurv negates the curvature of the earth? 

I see that 9.8 m/s^2 is indeed listed in Table 10: Auxiliary Constants, but does that fact - that this case study will negate the few % variance in gravitational pull across the Earths surface - also need to be stated in the assumption section?

**Comment by smiths** [comment]
This is a good point @peter-michalski.  I believe that the simplest solution is to add an assumption that g = 9.8 m/s^2.  That is what we did in this problem, but we didn't state the assumption.  We did the same thing in the GlassBR example for some physical constants (m and E, I believe), so there is precedent. 

Before making any changes, I'd like the opinion of @samm82.  If you aren't too busy with classes @samm82, could you give your opinion on the observation of @peter-michalski.  (@peter-michalski is a new graduate student that will be working on topics related (but not directly related) to Drasil.

**Comment by samm82** [comment]
I agree with the addition of the assumption "g = 9.8 m/s^2". This really should have been done when creating Projectile in the first place 😂

**Comment by smiths** [comment]
@samm82 glad to see we are on the same page.  😄  Thank you for your quick response.

@bmaclach, I'm sorry to make another request, but could you please add the assumption on the value of g (assuming that you agree with the rationale for creating this assumption).
