### ISSUE TITLE
HGHC Case Study SRS - Better to name the tables

### ISSUE THREAD

**Issue by best-zhang-zhi** [JacquesCarette/Drasil#1889]
@smiths 

In the Table of Units section, it mentioned the table 1 is Tab:ToU in the description part, but under the table, it's only appears "Table 1", it would be better to change "Table 1" to "Table 1: ToU", or even better, "Table 1: Table of Units", because it's not a long name, write it in full length would be more clearly. Same for the name of Table 2, it's better to name it "Table 2: ToS" or "Table 2: Table of Symbols".

**Comment by smiths** [comment]
@best-zhang-zhi, thank you for your observation.  My first thought was that this is a matter of taste.  Some would say that repeating Table of Units in a table in the section with the title Table of Units is getting redundant.  However, writing guidelines (like https://gradstudents.carleton.ca/2014/guidelines-using-figures-tables-scientific-engineering-thesis/) state that all figures and tables should have captions.

@bmaclach, can you please add captions to Tables 1 and 2 in all of the examples.  (I almost wonder if we should warn the writer of a document if their tables and figures do not have captions.)

**Comment by bmaclach** [comment]
@smiths I think the same argument applies to Table 3 (Abbreviations and Acronyms). Should I change that one as well while I'm at it?

**Comment by smiths** [comment]
Yes, that would be great.

**Comment by bmaclach** [comment]
With regards to throwing a warning if no caption is given, captions are currently required but each table has a `Bool` to determine whether or not to show the caption. We could throw a warning when the `Bool` is false (meaning "don't show the caption"), though it does make me wonder if we should provide this option at all. Having an option that will always cause a warning if used seems weird to me.

**Comment by smiths** [comment]
@bmaclach, I agree with your line of thinking.  If we agree with the writing best practices that all tables (and figures) should have a caption, then having an option to turn the caption off sounds like a mistake.  We are trying to emphasize maximum flexibility and configurability though, so maybe this is an option we want to keep?  I'd like the opinion of @JacquesCarette before we make a final decision on this one.

**Comment by JacquesCarette** [comment]
Definitely no warning, as that would make the option pointless. Deleting the option right now seems like a bad idea too, even though it's unclear if we really want it.  I'd just leave things as the now are.
