### ISSUE TITLE
Better format for units

### ISSUE THREAD

**Issue by caobo1994** [JacquesCarette/Drasil#1891]
In Presentation/PASC16/SRS.pdf, you use \frac{}{} in units. A more popular way replacing \frac{}{s^2} is to use expressions /s^2, or better, s^{-2}.

**Comment by smiths** [comment]
@caobo1994, the exercise for 741 is to review one of the requirements documents for one of the Drasil case studies.  You will find those examples in the following folder:

https://jacquescarette.github.io/Drasil/

The slides for PASC16 are not being reviewed.
