### ISSUE TITLE
Inconsistent phrases in 2. Introduction - SRS - all projects

### ISSUE THREAD

**Issue by Ao99** [JacquesCarette/Drasil#1892]
@smiths 

In all SRS documents, at the end of ‘2. Introduction’ and just before ‘2.1 Purpose of Document’:

We have these words ‘This section explains the purpose of this document, **the scope of the system**, the characteristics of the intended reader, and the organization of the document.’

However, 2.2 is ‘**Scope of Requirements**’. This inconsistency may cause some confusion. It might be better to choose the more appropriate one between the two, and use it at both of the two places.

**Comment by smiths** [comment]
Thank you @Ao99.  I agree with your assessment.  @bmaclach, can  you please change the phrase "the scope of the system" to "the scope of the requirements."  (@Ao99 found this inconsistency as part of an exercise being done by the 741 class.)

**Comment by bmaclach** [comment]
Closed by #1898.
