### ISSUE TITLE
Game Physics SRS - FIXME Refs left in text

### ISSUE THREAD

**Issue by sorainsm** [JacquesCarette/Drasil#1893]
@smiths seems like FIXME REF and FIXME notes have spilled into the document in the following places:

* General System Description > System Context > User Responsibilities
* General System Description > System Context > Game Physics Responsibilites
* Instance Models > Data Constraints

**Comment by smiths** [comment]
@oluowoj, please look into the occurrences of FIXME REF and FIXME in the Game Physics SRS.  (You can search the pdf or html documents to find all instances in question.  Are these notes related to fixing the Drasil code, or fixing the documentation?  Ideally, please fix the issues being highlighted by these notes.  If that isn't feasible at this time, please provide detail on what will be needed to close this issue.

**Comment by oluowoj** [comment]
Found 3 instances of these, I will look into them

**Comment by oluowoj** [comment]
FIXME text in the User responsibilities section has been updated with reference to the assemption section as shown below:

![image](https://user-images.githubusercontent.com/43192745/65286845-06684580-db0f-11e9-9bf4-cd03ccf34634.png)

See PR #1923

**Comment by oluowoj** [comment]
PR #1929 contains fix for FIXMEREF text for  General System Description > System Context > Game Physics Responsibilites

![image](https://user-images.githubusercontent.com/43192745/65744140-69387e80-e0c5-11e9-80f9-b911b4cebbe5.png)

**Comment by JacquesCarette** [comment]
@oluowoj does this mean this issue can be closed as everything is fixed?

**Comment by oluowoj** [comment]
I looked through the SRS, only one "FIXME" text left in Constraint Section. Its just a reference to the table below that section. I dont think this text is necessary here since it was already mentioned at the start of the paragraph (Table:InDataConstraints), but maybe @smiths wants to keep it this way, not sure.
![image](https://user-images.githubusercontent.com/43192745/82048779-3d353200-9683-11ea-9ad2-4f0929769b6d.png)

**Comment by smiths** [comment]
@oluowoj, I do not see any value in that FIXME.  Please remove it, and then we can close this issue.  :-)
