### ISSUE TITLE
Grammar errors & typos - SRS -SSP

### ISSUE THREAD

**Issue by Ao99** [JacquesCarette/Drasil#1900]
@smiths 

Some grammatical errors are listed as follows,

Page 3 - 1.2 Table of Symbols - '**values** with a subscript 𝑖 **implies** that the **value** will', should be 'values' with 'imply', or 'value' with 'implies'.

Page 7 - Shear Strength - 'The strength of **a material**', should be 'a kind of material'.

Page 25 - the last paragraph - '**becaused** they are assumed to be isotropic', should be 'because'

Page 63 - the upper page - 'by multiplying **boths** sides', should be 'both'

**Comment by smiths** [comment]
Great proof reading @Ao99, especially for a such a long document.  I do not agree with your opinion on the errors on Page 3 and 7, but you found real typos on Pages 25 and 63.

@bmaclach, can  you please fix the typos on Pages 25 and 63.

**Comment by bmaclach** [comment]
@smiths I'll fix pages 25 and 63. 

I actually agree with @Ao99 about the sentence on page 3, insofar as thinking it should change. At the very least, it _sounds_ wrong/unnatural to me. I would remove "values with" altogether, and change "implies" to "indicates", so the sentence would be "Throughout this document, a subscript i indicates that the value will be...". Do you agree with that @smiths?

**Comment by smiths** [comment]
@bmaclach, yes, I agree with your proposal to change the sentence to "Throughout this document, a subscript i indicates that the value will be...".
