### ISSUE TITLE
Missing an article in a sentence

### ISSUE THREAD

**Issue by sharyuwu** [JacquesCarette/Drasil#1903]
In the paper: Software Requirements Specification for Slope Stability
analysis Program in the Introduction paragraph, the sentence "Slope stability analysis is the assessment of the safety of a slope, identifying the surface most likely to **experience slip** and an index of its relative stability known as the factor of safety. " the word slip should be a noun here, so it might need to article 'a' between 'experience'  and 'slip'.

**Comment by smiths** [comment]
Thank you @sharyuwu.  I can see what you are getting at, but an article is not needed here.  I don't know the exact grammar rules, but slip is a potential "state" for the slope.  It is a noun in the same sense as "happiness."  You would be likely to experience happiness, not experience a happiness.  😄
