### ISSUE TITLE
Suggestion: Slope Stability analysis Program SRS

### ISSUE THREAD

**Issue by sharyuwu** [JacquesCarette/Drasil#1904]
In the paper: Software Requirements Specification for Slope Stability
analysis Program in the 3.1 System Context paragraph, when it tried to refer the graphic above like Fig:sysCtxDiag, I suggest making the first letter of its reference name as an uppercase like Fig: SysCtxDiag.

**Comment by smiths** [comment]
@sharyuwu, thank you for the suggestion, but this one is really just an issue of taste.  You aren't wrong, but it would be an arbitrary change.
Please try to come up with deeper comments when you review documents.  Does the example make sense to you?  If not, then maybe there is some information missing that should be included.  If you cannot find an issue, then you can ask a question about the distinction between different parts of the document instead.

**Comment by JacquesCarette** [comment]
@smiths is this still a live issue that we should do something about?

**Comment by smiths** [comment]
We can close this issue.
