### ISSUE TITLE
Acceleration due to gravity derivation

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#1909]
@smiths, looking at the derivation from the manual version:

![image](https://user-images.githubusercontent.com/43192745/65177055-f9225c80-da23-11e9-8643-ee5b45e5a8f9.png)

Not sure if this is absolutely right, as the end result is slightly different from the equation in the GD. The derivation should at least arrive at the equation in the  GD of acceleration due to gravity which is : 

![image](https://user-images.githubusercontent.com/43192745/65177184-371f8080-da24-11e9-84c2-e6b56c7112df.png)

 We can define the above for the x and y component (as shown in the derivation), however it seems that the manual version is not quite right but I just wanted you to take a look as well.
Let me know your thoughts, and then depending on what you think I can come up with an updated derivation, if need be.

**Comment by smiths** [comment]
@oluowoj, yes, I agree that the derivation is incorrect.  I seem to remember discussing this before, but I don't remember the details.  Regardless, the decomposition into the x and y components is incorrect.  The denominator should still be the norm of the r vector, not the norm of the x and y components.  Also, it is an unnecessary assumption to have the coordinate axes line up with the r vector.  (That will often be the case for convenience, but the GD has the right approach of not assuming this.)

The GD for acceleration is also not quite right.  The denominator should be the norm of r squared, not the vector r squared.  To get the correct GD, you take Equation 4 in the derivation and simply remove m from both sides of the equation.  We should completely remove the part where we decompose this into x and y components.  We should just leave it in vector form.

**Comment by oluowoj** [comment]
As per the equation of the GD,  I previously used equation 4 and removed the m on both sides. But then I updated it based on your review of seperate PR... that the equation did not match with the reference source given in the GD(or maybe I misread your message). Please see the link below for the reference source:

https://en.wikipedia.org/wiki/Gravitational_acceleration
 Equation of g  in the wiki link is different from the manual version:  
![image](https://user-images.githubusercontent.com/43192745/65268432-22ef8800-dae5-11e9-96d7-6aaa9be6c793.png)

Not sure which one to go by. Please advise.

**Comment by oluowoj** [comment]
Looking at your comments above, I will rewrite the equation and write the derivation.

**Comment by smiths** [comment]
@oluowoj, to save me some time, and to keep a complete record of the discussion, can you please also include a screen shot of your current version?  That way we can quickly compare the Wikipedia equation and yours.

**Comment by oluowoj** [comment]
sure will do

**Comment by oluowoj** [comment]
Here is an image with the wiki and manual version based definition of g:

![image](https://user-images.githubusercontent.com/43192745/65438499-977f3b00-ddf3-11e9-91bc-8c08d4da87f0.png)

**Comment by oluowoj** [comment]
@smith thanks for the info, could you please review the PR?

**Comment by JacquesCarette** [comment]
What PR was that? Does this mean this is now fixed @oluowoj ?

**Comment by oluowoj** [comment]
Yes fixed with PR #1828
