### ISSUE TITLE
Case study on GamePhysics

### ISSUE THREAD

**Issue by bigship** [JacquesCarette/Drasil#1912]
@smiths 
This is Colin Chen, I got a couple of thoughs about the GamePhysics SRS.

1.  **Coordinate system confusion**
On page 10, it says:
> The library uses a Cartesian coordinate system
> The axes are defined using right-handed coordinate system  

I think the two coordinate systems are very different, one is 2D oriented the other is 3D oriented. Is there any mis-understanding here ? 

2. **System constraints AND Data constraints**
There are no system constraints, but all the input data has a constraint due to the physical constraints. I think this will lead to inconsistency and contradiction.

3. **Lack of API specification**
This is a SRS document about game physics library. The direct user of such a library is the programmers who need to use it for game projects instead of the people who play the game. So lacking of the API spec doesn't sound good to me.

**Comment by smiths** [comment]
> @smiths
> This is Colin Chen, I got a couple of thoughs about the GamePhysics SRS.
> 
@bigship, in the future, please put your separate thoughts in separate issues.  It is a better approach for issue management.

> 1. **Coordinate system confusion**
>    On page 10, it says:
> 
> > The library uses a Cartesian coordinate system
> > The axes are defined using right-handed coordinate system
> 
> I think the two coordinate systems are very different, one is 2D oriented the other is 3D oriented. Is there any mis-understanding here ?
>
I believe you may have a misunderstanding about Cartesian coordinate systems.  You can have a Cartesian coordinate system in 3D space.
 
> 1. **System constraints AND Data constraints**
>    There are no system constraints, but all the input data has a constraint due to the physical constraints. I think this will lead to inconsistency and contradiction.

The system constraints are constraints on the design.  They are requirements that are related to design decisions.  The system constraints are the one place in the SRS where you are allowed to not be abstract.  The data constraints are still abstract.  They are not related to making design decisions at the requirements stage.  It is unfortunate that the same word is used with slightly different meanings, but I'm not aware of a different word that could do the same job properly.

> 2. **Lack of API specification**
>    This is a SRS document about game physics library. The direct user of such a library is the programmers who need to use it for game projects instead of the people who play the game. So lacking of the API spec doesn't sound good to me.

The API spec is related to the Module Interface Specification.  That is a different document.  We'll be discussing that in a few weeks.  The SRS is supposed to be abstract.  Making decisions about the interface is too concrete a decision for the requirements stage.
