### ISSUE TITLE
Detect and complain if the same symbol is used for two or more concepts within the same document

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#1916]
This issue came up during the discussion in #1901.

Symbols are routinely used for different meanings in science and engineering.  However, if the same symbol has more than one meaning in the same document, this is a problem.  Drasil should prevent the user from making this mistake by automatically detecting if a symbol is use for more than one purpose within the same document.

**Comment by smiths** [comment]
I'm sorry @muhammadaliog3, but I do not know the answer to your question.  Maybe you can find it by looking at the code documentation:

https://jacquescarette.github.io/Drasil/docs/index.html

Alternatively, this is likely a question that @JacquesCarette or @bmaclach could answer.

**Comment by JacquesCarette** [comment]
First, you should really investigate if that `Sentence` is crucial, i.e. if it is inevitable that the only information you have, when you're ready to throw that error, is a `Sentence`. Often, it is not, and then printing is simplified.

If it is, then there are various 'rendering' functions in `drasil-printer`. You'll need to use the `plain` printer.

If you tell us the context more precisely, we can direct you to the proper functions. Often, wishing to print a `Sentence` is actually a sign that you're not quite doing the right thing. [And sometimes, it's a design bug in Drasil.]

**Comment by muhammadaliog3** [comment]
I guess this is a good time to present my solution.
Say we have the the following rows in a symbols table
[(sigma, description_1),(sigma, description_2),(E, discription_3),(E, description_4)]
Here two variables have the conflicting symbol of sigma and 2 have conflicting symbol of E. 

I do not believe that in the error we should simply print "Duplicate symbols found", rather we should say "Duplicate symbols found. See the following descriptions: (description_1,description_2,description_3,description_4)".

These descriptions are stored as a list of sentences. I can fold the sentences into one sentence, but to print the error I still need to convert that one sentence to a string. This is the code by the way, the line with ----HERE------------ is where I print the error. 



```haskell
table :: (Quantity s, MayHaveUnit s) => Stage -> [s] -> (s -> Sentence) -> LabelledContent
table st ls f
    |noDuplicate = llcc symbTableRef $
      Table [atStart symbol_, atStart description, atStart' unit_]
      (mkTable [P . (`symbol` st), f, toSentence]
      $ filteredChunks)
      (titleize tOfSymb) True
    |otherwise = error . show $ S "Duplicate Symbols" +:+ foldlSentCol descDuplicates ---HERE-----------
    where 
        filteredChunks = filter (`hasStageSymbol`st) ls
        symbolsCol = map (P . (`symbol` st)) $ filteredChunks
        descCol    = map (f)                 $ filteredChunks
        symDescPair = zip symbolsCol descCol
        symDuplicates = nub $ intersect symbolsCol (nub symbolsCol)
        noDuplicate = symDuplicates == []
        descDuplicates = [snd x | x <- symDescPair, fst x `elem` symDuplicates]
```

**Comment by JacquesCarette** [comment]
That's a nice piece of Haskell.  I would prefer if the error was even more verbose & precise: it should give an error for each UID/symbol/description tuple that is duplicate.  So an error for `(sigma, description_1),(sigma, description_2)` and another for `(E, discription_3),(E, description_4)`.

**Comment by muhammadaliog3** [comment]
But to print those errors I would need to convert a sentence to a string. I still do not know how to do that.

**Comment by JacquesCarette** [comment]
Oh, because of the descriptions?  Ok, skip those. Just do the UIDs and symbols then.
