### ISSUE TITLE
Improve list printing in GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1940]
@JacquesCarette pointed out that the code we currently generate for printing lists in Java can be improved. Instead of generating a loop, it seems lists in Java can be printed simply by passing the list to the `System.out.print` function. This works even for nested lists, but not lists of objects. 

In C# and C++, the current loop can be simplified by using a for each loop instead. 

In C#, the loop can be removed entirely by calling `ForEach(Console.Write)` on the list variable, though this only works well if the list contains simple types (not lists or objects).

**Comment by bmaclach** [comment]
Now that I've actually worked on this, I don't think it is worth it to switch to using a for each loop for C# and C++. The reason we use a regular for loop is because we want to print commas after each list element, but not after the last one. If we use a for each loop, that means we have to either slice the list before printing it or declare and iterate a counter to check in the loop body so we know when we are at the last element. Using a regular for loop removes the need for either of those complications.

If you agree @JacquesCarette that what we currently generate in C# and C++ is good, then this issue can be closed once Java is fixed, with PR #1954.

**Comment by JacquesCarette** [comment]
I agree.

What we really ought to do is to define some combinator-like functions that we can emit in a "library" of GOOL support code when doing such things, and then call them.  This is just `intercalate` in Haskell, which really ought to exist in C++ and C# too.

**Comment by bmaclach** [comment]
With #1954 merged, the improvements have been made. Closing.
