### ISSUE TITLE
Refactor UnaryOp, BinaryOp

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#1944]
Those classes were also created because of syntax. They should be split into classes according to type (without typing information).  This will cause the 'inheritance graph' of the classes to change a fair bit.

The next step will be to actually merge the new classes into more semantics-driven classes (around arithmetic, boolean logic, etc).

**Comment by balacij** [comment]
I think this is more or less complete now @JacquesCarette. Should we be continuing in #2212 or do we want to branch into additional issues related to this one?

**Comment by JacquesCarette** [comment]
Yes, I think this one is complete. We should open new issues for tasks that move us ever closer to having typed `Expr`.

The next one is going to be to split some things out of `Expr` entirely. I would guess that the programming-oriented pieces are the ones that seem easiest to achieve.
