### ISSUE TITLE
Simplify C++ Pair instance by having GOOL functions take records as parameters

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1966]
Currently C++'s `Pair` instance has some very messy and unreadable method instances. Contributing to this is that the methods take many parameters. If we combined related parameters into records, this would simplify things. As an example, `inOutFunc` currently takes 6 parameters: a name, scope, permanence, input parameters, output parameters, parameters that are both. These could all be combined into a `FunctionInformation` record, and the 3 parameters about parameters (inputs, outputs, both) could be further combined into a `ParamCallingSeq` subrecord. This is just one example  -- there are probably many more in GOOL. @JacquesCarette's rule of thumb was that once a function has 3 or more parameters, we should seriously consider condensing them.

The new records would be parameterized by `repr` and show up directly in the signatures for GOOL's class methods (rather than being an underlying type that a type family instance resolves to).

**Comment by JacquesCarette** [comment]
I know you've made a lot of progress on this @bmaclach - should be considered fixed?

**Comment by bmaclach** [comment]
We did a lot to simplify the `Pair` instances. We didn't, however, implement records to do so as was suggested in this issue. Though I think the records would actually make the instances more complicated --- there would be fewer parameters overall, but we would need to write special helper functions for extracting information from the records. 

I'm happy to close this if you are, @JacquesCarette.
