### ISSUE TITLE
External Library implementation clarification

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1985]
I want to clarify some things about how I should implement external libraries.

We've talked about how we should be able to declare/define an external library on the Drasil side of things as data. So we have some kind of `ExternalLibrary` data type.

My very high-level thinking of this type is that it will essentially encode the API for any given library.

Is the idea then that when a user wants to use an external library, they will somehow be able to pair an `ExternalLibrary` with some parameters needed for the call, and then Drasil's generator will translate that into GOOL code for that call?

If that is right, then am I also right in thinking that we won't need to implement anything new in GOOL itself for this? Since GOOL already has methods for calling methods on objects and calling external functions.

If Drasil's generator is doing the job of translating an external library call into GOOL code using what's already available in GOOL, that means that either:
1. Every language feature used for the calls to ODE solvers that hasn't already been implemented in GOOL needs to be implemented, even if these features only exist in one of our target languages! (I've put together a list of these features, which I'll write another issue about).
2. We need to export some of GOOL's functions like `methodFromData` which are currently only used internally and allow us to hardcode things that are very language-specific which we don't want to add to GOOL.

Neither of these options seem good to me, which is why I think my high-level understanding of what we want to do may be off.

**Comment by JacquesCarette** [comment]
Correct on: `ExternalLibrary`, encoding of API, the pairing general idea.

It is entirely possible that there is nothing needed in GOOL to do this.   But I would be surprised.

The idea would be that:
1. the 'encoding of the API' could be a fairly complex language
2. the generation of the glue code could be fairly language-specific

The point is that you don't want the "language feature" used to call ODE solvers to be exposed, but rather the "conceptual idea". Some of the concepts used might instantiate to very different code.  The issue with your item 1 is likely that you're not abstracting enough.  I would not be surprised if a few internal GOOL functions needed to be exposed for this. Ideally, we'd expose them only to our own routines, but that might be difficult.

**Comment by bmaclach** [comment]
You are right -- when I started thinking about what these language features were doing conceptually, it became clear that for most of them, there were "equivalent" features in the other languages that could accomplish the same thing.

I've thus created #1987, #1988, #1989, #1990, #1991 for adding the features used by ODE solvers to GOOL. 

There's also #1992, which is the one feature where the concept really doesn't seem to be possible in at least one of the languages, so I'm not sure about that one. 

Anyway, my question has been answered so I'll close this issue.
