### ISSUE TITLE
Commonality analysis - External libraries vs. ODE-solving libraries

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1986]
We talked in the January 13th meeting about how I should look for commonalities and variabilities in the GOOL code I've written for interfacing with the 4 ODE solving libraries. This would then inform us for designing our type for defining external libraries.

I've started doing this, but I find that the observations I'm making are very specific to the fact that all of the libraries I'm looking at are ODE solvers. For example, a commonality is that they all require defining the ODE equation, and a variability is whether that definition is in the form of a function or a class.

Since our ultimate goal is to be able to define external libraries in general, not just ODE solvers, are those kinds of observations useful, or am I on the wrong track? These observations _seem_ important to me, but this approach doesn't seem like it will lead to good insights for a generic type for defining external libraries.

**Comment by smiths** [comment]
@bmaclach if your understanding is wrong, then I'm wrong too.  :-)  I thought you were doing a commonality analysis for ODE solvers, not for any external library.  I think our hope is that the strategy we use for ODE solvers can be generalized, but it feels too early to be more general.

**Comment by JacquesCarette** [comment]
I was thinking we were doing a commonality analysis where our input data was ODE solvers, but our eventual aim was general external libraries. So we won't find all features, we'll just find those that occur in ODE solvers.

Your example easily generalizes: when a complex input is needed by some external routines, sometimes the API to that is a function, sometimes it is a class.

I would say that what we want - within the scope of your work - is an external library analysis (and implementation) that is good enough to hand ODE solving and linear algebra libraries.

**Comment by bmaclach** [comment]
So I'll likely need to try to generalize my observations so they aren't so ODE-specific, like @JacquesCarette showed above. I think my question has been answered, so I'll close this issue.
