### ISSUE TITLE
Implement object initializers in GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1989]
The ODE solver for C# uses an object initializer, like this:

```
new Options {
  AbsoluteTolerance = inParams.absTol
  RelativeTolerance = inParams.relTol
}
```

Basically it allows you to construct an object but set some fields however you want. The above is equivalent to something like:

```
Options opts = new Options();
opts.AbsoluteTolerance = inParams.absTol
opts.RelativeTolerance = inParams.relTol
```

Not every language has object initializers (Java does, but I've read they should be avoided. C++ does, but only if the constructor was defined with an initializer list), but I think we can implement this in GOOL and just have the GOOL method map to the equivalent code shown above for languages without object initializers. 

We could alternatively get by without implementing this, and just use the equivalent way everywhere (calling the constructor normally, then setting fields in the next statements). But I think it's a simple pattern that wouldn't be too hard to implement, so we might as well do it.

**Comment by smiths** [comment]
I like the way you present this issue @bmaclach.  It is very clear, especially because you have included code snippets.  As far as priorities go, I think this issue could be down on the list.  Having object initializers would be a nice "extra" to have.

**Comment by JacquesCarette** [comment]
In some ways, this seems odd: shouldn't there instead be a constructor (in this case for `Options`) that passes in those fields to the object constructor?  This seems kind of not-very-OO to me.

The higher level functionality of being able to specify and use different constructors does make sense.  Of course, there might be a deeper reason for using features such as the above, i.e. it might be that it's the ODE solver itself that instantiates the object, so it can't call the right constructor.  So we need to dig deeper to understand why this is needed.

**Comment by bmaclach** [comment]
@JacquesCarette I think the idea behind this feature was for classes with many fields, it allows you to change a subset of those fields from the default constructor. Then you don't need a whole bunch of different constructors for each possible combination of fields.

It's not a case where the ODE solver is calling the constructor internally. We are calling the constructor, and we want the fields to be set based on the default constructor, with the exception of the 2 fields we specify in the object initializer.
