### ISSUE TITLE
Implement initializer list in GOOL

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1991]
The ODE solver in C++ requires an initializer list in a constructor definition. Initializer lists aren't available in our other target languages, and are really just an alternative way of writing assignment statements in a constructor. So I think that rather than implementing a GOOL method for initializer lists, the right way to do this is probably to have the C++ renderer automatically use an initializer list if a constructor body has direct assignments from parameters to state variables (with the help of `State`).

**Comment by smiths** [comment]
Your proposal makes sense to me @bmaclach.

**Comment by JacquesCarette** [comment]
I think 'reverse engineering' from the body is not a good idea - too fragile. Much better is the other way around where we can have the option of specifying some initializer (and, likewise, finalizers). If the language doesn't support it, it's easy to generate initialization code in the constructor.

Meta-design: we should do as little code analysis as possible. If some information is needed, we should explicitly put it in the representation, in an easy way to extract, instead.

**Comment by bmaclach** [comment]
So the PR that closed this did it the way I laid out in the original comment.

@JacquesCarette If I understand correctly, your suggestion would be something like adding a parameter to GOOL's `constructor` function, say a list of Variable-Value pairs, which are the initializers? Or to create a new function altogether?

I think what I would want to do is add the initializers as a parameter to `constructor`, and then provide smart constructors for 2 cases:
1. There are no initializers, so the initializer parameter can be left out
2. There are only initializers, so the constructor `Body` parameter can be left out.

Anyway, fixing this will mean undoing some of what I did in #1995, but I think I can at least keep the first couple commits, where I add `ValueState`, because I think that level of local state will be necessary elsewhere.

**Comment by JacquesCarette** [comment]
Adding a parameter to `constructor` (with smart constructors as you outline) seems like the best way to do it.
