### ISSUE TITLE
Implement calling object as a function in GOOL?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#1992]
The ODE solver in C++ requires overriding the `()` operator by defining a class method called "operator()". We can do this in GOOL already simply by using GOOL's existing methods to define a representation of a method called "operator()", but since this is a special kind of method I thought we might want to implement a dedicated GOOL method for it.

The potential problem is that some other languages don't allow overloading this operator. Python does, by implementing a `__call__` method. C# has operator overloading, but not for this "calling" operator. It seems like there's a way to do it, though, by inheriting from `DynamicObject` and overriding `TryInvoke` (https://stackoverflow.com/questions/4858733/does-c-sharp-support-a-call-method). Java does not support operator overrides, and I've been unable to find an equivalent way to do it.

So we can definitely get by without it, but I'm not sure if this is something we should implement. Thus, I'm putting a question label on this one.

**Comment by JacquesCarette** [comment]
I don't think we should implement this as a GOOL feature. It is too language-specific.  We can certainly use it in the generator.

We could consider adding another way to call methods though, which could then use this mechanism if available, and fall back to ordinary calls otherwise.  I guess what we first need to do is to analyse what this kind of code (like to ODE solver) is trying to achieve, and maybe provide that abstract functionality.

**Comment by bmaclach** [comment]
So we don't actually need to explicitly call an object in the code we generate. But we do need to override the "calling" operator in C++ because the ODE solver, internally, calls the object. So the part we need in GOOL is not the calling itself, but the definition of what happens when the object is called.

But since this is achievable already just by defining a function called "operator()", and is fairly language-specific as you point out, I'm leaning towards not implementing anything additional for this.

**Comment by JacquesCarette** [comment]
Sounds good.

**Comment by bmaclach** [comment]
Closing this as the question has been answered and no action needs to be taken.
