### ISSUE TITLE
Implement Named Arguments in GOOL?

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2008]
Named arguments are used in the call to Python's ODE solver, like this:
```
r.set_integrator('vode', method='bdf', atol=params.AbsTol, rtol=params.RelTol)
```
The `set_integrator` method has a variable-length parameter list, so it requires specifying the names of the parameters. I don't think there's an alternative way of doing this, so we somehow need to generate these using GOOL

Named arguments are supported in C# but not Java or C++.

We don't need to be able to define a function with variable-length parameter list, we just need to call one.

So I see two options:
1. Implement named arguments in GOOL. For Java and C++, we throw an error if this is used.
2. Don't implement named arguments in GOOL. Then we would have to export some of GOOL's internal functions to allow us to construct a `repr (Value repr)` by hardcoding the `Doc`. 

I'd vote for option 1. It's unfortunate the concept of named arguments aren't supported in two of our target languages, but it does seem to be fairly common in OO languages in general (see the non-exhaustive list of programming languages that support this on Wikipedia: https://en.wikipedia.org/wiki/Named_parameter)

**Comment by smiths** [comment]
I also vote for option 1.

**Comment by JacquesCarette** [comment]
I think option 1, but with a twist: we might want to declare, at the same time, positional and named information for arguments.  That way we can use the most convenient calling convention in the underlying language, when it makes sense.  This should allow us to throw errors less often.

**Comment by smiths** [comment]
The proposed twist sounds like a good idea to me.

**Comment by bmaclach** [comment]
Implementing the twist would require (I think) a new type for `Argument`s in GOOL (i.e. a `repr (Argument repr)`), where the underlying data structure would have fields for name and position. 

All of our current GOOL methods that take a `[repr (Value repr)]` to represent the list of arguments would need to change to take a `[repr (Argument repr)]`. 

My worry with this is that it complicates the by far most common case (indeed, the _only_ case we have encountered up until this need for named arguments popped up) where the arguments have no names and the position corresponds to the position in the list passed to the method. We could provide a constructor for converting a `[repr (Value repr)]` to a `[repr (Argument repr)]` for this most common case, by setting the name to `Nothing` and the position to the position in the list, so then the only "extra" work a user would need to do is call this constructor on their list.

And then the logic for determining when to use a named argument would just be "if the argument has a name, use it as a named argument"? And for position, we could write an `Ord` instance for the data structure representing an argument, and use that to sort the arguments before rendering?

Does this all sound okay?

**Comment by JacquesCarette** [comment]
Hmm, I think that this is messy. I would prefer to have different classes of calling conventions (i.e. `Positional`, `Named`, `MixedNamedPositional`), and then different methods for calling them. It would then be the caller's responsibility to use things properly, rather than the callee's job to disentangle the mess they were passed.  That way positional code wouldn't have to change at all.

An interesting side-effect would be that if you insist on using `Named` calling convention for a language that doesn't support it, then things won't compile. [That might require some changes to the class hierarchy, so might not be worth it]

**Comment by bmaclach** [comment]
Some clarification questions:

`Positional`, `Named, and `MixedNamedPositional` will be new classes in GOOL's hierarchy, each containing methods for calling a function with the corresponding argument convention? So our current functions like `funcApp` would not need to change, but would move to the `Positional` class? And then new methods like say `funcAppNamedArgs` would be defined for `Named` and similarly for `MixedNamedPositional`?

Not sure what you mean in your last sentence -- wouldn't we just throw an error when writing the instance for `funcAppNamedArgs`, for the languages that don't support it? Why would that require changing the class hierarchy?

**Comment by JacquesCarette** [comment]
I mean that we should just not implement the class at all for those languages that don't support it. So it means that the class would then not be required in the whole hierarchy.

**Comment by bmaclach** [comment]
Oh, right. That makes sense. Yes, that might pose problems since Drasil's generator is written in terms of a generic `repr`. We would need to constrain that `repr` to have an instance of `MixedNamePositional` so we could use named parameters when needed in Python, but then that would exclude Java and C++ as targets.

**Comment by JacquesCarette** [comment]
At compile-time, yes.  But that's probably overkill, for the purposes of your work.

**Comment by JacquesCarette** [comment]
So is this all implemented @bmaclach ?

**Comment by bmaclach** [comment]
As of #2022, function calls with named arguments have been added to GOOL. I didn't split them into different classes for the reasons given in my last comment, about the generic `repr` (now `r`) used in the generator, and how having some languages not implement some type classes would mess up these generic functions. There's still the option of splitting into multiple classes, as long as we implement the classes in all renderers (for Java and C++ the implementations for named argument calls would just throw errors).

I'll close this now, but feel free to re-open @JacquesCarette if you think we should split the functions up into different classes.
