### ISSUE TITLE
Automate table of design decisions on website

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2017]
The website shows a table of the design decisions made for each case study, as of #2015. For now, it is just hardcoded into `code/website/index.html`. We should instead build this table automatically so it is more maintainable.

(@smiths, I'm assigning this to you just so that someone has ownership of it. You can reassign as needed).

**Comment by smiths** [comment]
Thank you @bmaclach.  Yes, it makes sense to assign this to me for now.

**Comment by Ant13731** [comment]
While going through the recent website work, I realized that this can be closed since we just pull the information from the examples now.
