### ISSUE TITLE
Expr extensions needed for ExternalLibrary

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2025]
My big picture plan for external libraries is to define `ExternalLibrary`s which can be paired with `ExternalLibraryCall`s to generate the statements and additional classes needed for the call. These statements and classes will be represented by Drasil's existing AST for representing functions/classes, primarily the statement language `FuncStmt`. There are many reasons for doing this:
1. The functions for translating from `FuncStmt` to GOOL code are already defined
2. These functions are built into Drasil's generators, so they use the generator's `DrasilState` to generate correct code
3. By converting the `ExternalLibraryCall` to `FuncStmt` prior to generation, we can do some analysis to properly set the `DrasilState` `Reader` for generation (for example, adding the appropriate functions to the module export map and class export map). Again, we already do this analysis for other modules that are represented by `FuncStmt`, so the functions for doing this already exist.

The drawback to this is that `FuncStmt` relies on `Expr` as the representation for the values involved in the statements. So if we want to use `FuncStmt` as an intermediate representation between `ExternalLibrary`/`ExternalLibraryCall` and GOOL, every value needs to be expressible by `Expr`. 

This has already lead to problems in PR #2019, where I needed to represent a call to a constructor, so I added a `New` node to `Expr` to represent this. This is not ideal because it pollutes `Expr` with expressions that are only meaningful in code. My idea to make this less bad was to not export any smart constructors to this node or any other code-specific nodes I may need to add, so that a Drasil user would not use these nodes. 

The reason I'm writing an issue for this is to have a place for discussion, as well as to provide context for the issue that may not have been apparent just from looking at #2019. I'm also writing this issue because constructor calls are not the only type of expression needed for external libraries that aren't currently expressible in `Expr`. So I am putting together a list of needed but currently unexpressible expressions as I come across them while working on my external library implementation:
- Constructor calls
- Method calls (and object access in general)
- Named expressions
- Function-valued expressions

My thinking is that of those, only function-valued expressions are a mathematical concept that probably deserves a place in `Expr`. 

The alternative to avoid these problems would be to have `ExternalLibrary`/`ExternalLibraryCall` translated directly to GOOL, without using `FuncStmt` as an IR. This would require splitting `ExternalLibrary`s `Statement` node into many nodes, though this has already been mentioned as maybe the preferable option in https://github.com/JacquesCarette/Drasil/pull/2009#issuecomment-590068119. We would miss out on the advantages of `FuncStmt` enumerated above, leading to needing a lot more work on the generator and pre-generator for this, but if polluting `Expr` is out of the question, this may be the best bet.

And of course there may be some "perfect" solution I haven't thought of, that lets us still use `FuncStmt` but somehow avoiding the need to pollute `Expr`.

**Comment by JacquesCarette** [comment]
I'm going to paste in some comments I made in #2019 as they are directly relevant:

---

Because GOOL is supposed to be an OO framework, 'creating objects' is a natural concept that GOOL ought to have. That is happens to look like a function call is misleading, as that's not what it means. So the aim here is to find a way to map onto GOOL's 'create object' in the backend.

In this particular case, the objects being created are fairly special; not that they are ODE solvers, but that they are the creation of a 'process' that can be invoked later. 'process' is perhaps even not the right word, we should go further and borrow from good OO [yes, that exists] and call these 'actors', to which we can later send messages.

In the front-end, i.e. Drasil, I think what this means is that it would make sense to introduce at least new concepts, that of actor , actor creation and message (to an actor). Interestingly, you could keep the node New (with small changes in types) as above for actor creation! But its meaning would be quite different, and yet generate exactly the same code...

---

So that divides the unexpressible expressions above into different bins:
1. first two (constructors and methods) which are OO concepts
2. named expressions, which are structuring concepts (I think)
3. function-valued expressions, which are just plain missing

I think 'named expressions' belong to some kind of statement (or theory) language, above `Expr`.

**Comment by bmaclach** [comment]
Great news that we can conceptualize these to fit them in `Expr`!

So actor creation is to constructor calling what actor messaging is to method calling, right?

I've tried looking for more information about "actors" and "messages" but from what I see the "Actor model" is related to concurrency and is a separate paradigm from OO.

You mentioned that the `New :: Expr -> [Expr] -> Expr` constructor would need small changes in types, but I don't see why that would be. We still need a name for the actor-creator (represented by the first `Expr`) and a list of parameters for the creation (the `[Expr]`). I suppose the first `Expr` could be just a string, but that seems worse.

Also I probably should have given more details about named expressions. I need them to represent named arguments, so the "name" here is more like a chunk representing some thing that the expression is defining. Not sure if that changes how we would represent them. The problem with delegating them to a statement language is that a call is not a statement, but a value, and we may sometimes want to use it within another statement, to generate code like:
```
return some_func(x=1,y=2)
```

**Comment by JacquesCarette** [comment]
Right.

Yes, you're more likely to find (via the web) documentation linking actors to concurrency than to the original conception of OO (as in Simula 2 and Smalltalk).

I was definitely thinking `New :: Name -> [Expr] -> Expr`. Or `UID`.  Or even `ActorName`.  Not `Expr`.  

For named expressions, it sounds like you want a `UID` that is guaranteed (at creation time) to be associated with a chunk that has a number of fields "for sure".

**Comment by bmaclach** [comment]
I like the idea of using a `UID` as the parameter. In fact, `FCall` should probably also take a `UID` for the function instead of an `Expr`, right?

**Comment by JacquesCarette** [comment]
Yes - though you probably want the smart constructors to check that what you call is actually calleable (and the idea for `New`).

**Comment by bmaclach** [comment]
@JacquesCarette 
> For named expressions, it sounds like you want a `UID` that is guaranteed (at creation time) to be associated with a chunk that has a number of fields "for sure".

I am confused by this. What are the "fields" you're referring to? Name and defining expression? And would this be in regards to a new `Expr` node for named expressions? Since named expressions can only be used as arguments to a function/method call, I am thinking we could update our current `FCall` node (and probably `New` as well) to take an additional parameter, a `[(UID, Expr)]`, where the UIDs are for the chunks that represent the "names" of any named arguments. The reason I suggest passing the associated `Expr` in a pair with the UID is because the same function can be called multiple times with different expressions for the named argument, so the expression can't be built-in to the chunk representing that argument. But without understanding your comment, I could be way off track.

**Comment by JacquesCarette** [comment]
What I meant is embodied in https://github.com/JacquesCarette/Drasil/blob/e4e04f6d4dd95f6047a5c0efc98afde67010c8c6/code/drasil-lang/Language/Drasil/Expr/Math.hs#L153 i.e. that `C` in `Expr` cannot be built directly, only through `sy`, and it enforces that although we just store the `UID`, it must correspond to something that satisfies `HasSymbol`.

And I don't understand your comment about "same function can be called multiple times with different expressions for the named argument".

**Comment by bmaclach** [comment]
@JacquesCarette Let's say we have function `f` which must be called with named arguments `x` and `y`. So we can have `f(x=1,y=1)` or `f(x=4,y=5)` or any number of possible calls to `f` where the values of `x` and `y` are different. So if `x` and `y` are represented by chunks, those chunks cannot have the defining expressions for `x` and `y` built-in.

I understand now what you mean about enforcing the Chunk has certain fields. I don't think that changes how I would modify the `Expr` AST by adding a `[(UID, Expr)]` parameter to `FCall` etc. It just changes how I'd write the smart constructors. I think the only constraint I would need is `HasSymbol` in this case, just like with `sy`.

**Comment by JacquesCarette** [comment]
I was thinking that something like an `x` or `y` in the above should also belong to an `IsArgumentName` class, to try to capture some of the semantics that `x` and `y` are "labels" of some kind, not just arbitrary symbols.

**Comment by JacquesCarette** [comment]
It's my impression that the design for this is done, and that this is essentially implemented?

**Comment by bmaclach** [comment]
The outstanding part of this is adding function-values expressions which is waiting on a decision on #2014. But the original questions have been answered, which is why I assigned you, so I'll remove the question label and you from the assignees.

**Comment by JacquesCarette** [comment]
Now that #2014 has been decided, what's left?

**Comment by bmaclach** [comment]
This can be closed due to the various PRs linked throughout this issue. Note that I did not end up needing function-valued expressions (I used function-defining statements) instead, so those remain unimplemented.
