### ISSUE TITLE
Create some kind of Contributing page

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2050]
where we can list the open projects to work on.  For example:

1. Incorporate Pandoc into DocLang.

2. Scientific knowledge ontology.

3. Generation of test cases based on data constraints and properties of a correct solution

4. Add 3D Model of the Aorta to Drasil

5. Generate jupyter notebooks - probably starting with generating simple physics experiments

**Comment by smiths** [comment]
A potential projects page has been created at:

https://github.com/JacquesCarette/Drasil/wiki/Potential-Projects
