### ISSUE TITLE
Small questions regarding Haskell syntax

### ISSUE THREAD

**Issue by muhammadaliog3** [JacquesCarette/Drasil#2101]
Hello @JacquesCarette I wanted to know if my interpretation of the following is correct. 

1. The data map table does not include type synonyms.

2.  `instance (Pair p) => FileSym (p CppSrcCode CppHdrCode)`

the above line is interpreted as the datatype (Pair CppSrcCode CppHdrCode)  is an instance of FileSym.

3. `class HasUID s => Referable s where`
is interpreted as "the Referable class has a superclass of HasUID".

**Comment by JacquesCarette** [comment]
1. correct - unless, as you look through things, this appears to be a mistake
2. no, it is interpreted as "`p CppSrcCode CppHdrCode` is an instance of `FileSym` where p must satisfy the constraint `Pair p`
3. yes. Though I prefer to think of it as "interface `Referable` implies interface `HasUID`", i.e. if you see a `Referable`, you always also have a `HasUID`.  The superclass terminology works fine for single parameter classes (like these), but doesn't scale to multiparameter.
