### ISSUE TITLE
Need a consistent purpDoc function among examples

### ISSUE THREAD

**Issue by muhammadaliog3** [JacquesCarette/Drasil#2116]
### Context

While changing the purpose of the SWHS SRS example for [#1570](https://github.com/JacquesCarette/Drasil/issues/1570), I noted while every example intends to have a purpose, some examples have not implemented a purpose, and the examples that have a purpose each create there own purpose function.

### Problem:
There is no common function or methodology in creating the purpose section among the drasil examples. To promote software reuse we should have a common function/methodology for generating the purpose among Drasil examples. 

### The Facts

Note about Purpose section. All examples infact print out 2 paragraphs in the purpose section. However the second paragraph I found is always the same, and is hence probably automatically generated. Hence I will only be displaying code for the first paragraph which actually varies between examples. 

The following examples have not implemented a purpose yet: HGHC. 
The following examples share a purpDoc function already, hence output the same purpose: No_PCM and SWHS. 

**No_PCM and SWHS** 

Here is the function purpDoc:
```haskell
purpDoc :: Sentence -> CI -> Sentence
purpDoc spSent pro = foldlSent [S "The main", phrase purpose, S "of this",
  phrase document, S "is to describe the modelling of" +:+.
  spSent, S "The", plural goalStmt `sAnd` plural thModel,
  S "used in the", short pro, S "code are provided, with an emphasis",
  S "on explicitly identifying", plural assumption `sAnd` S "unambiguous" +:+.
  plural definition, S "This", phrase document,
  S "is intended to be used as a", phrase reference,
  S "to provide ad hoc access to all", phrase information,
  S "necessary to understand and verify the" +:+. phrase model, S "The",
  short Doc.srs, S "is abstract because the", plural content, S "say what",
  phrase problem, S "is being solved, but do not say how to solve it"]
```
The Latex text reads
"
The main purpose of this document is to describe the modelling of the solar water heating system incorporating PCM. The goal statements and theoretical models used in the SWHS code are provided, with an emphasis on explicitly identifying assumptions and unambiguous definitions. This document is intended to be used as a reference to provide ad hoc access to all information necessary to understand and verify the model. The SRS is abstract because the contents say what problem is being solved, but do not say how to solve it.
"
Note that as per issue #1570 that inspired this whole issue the function can be implemented with just the second parameter. 

The function ```purpDoc``` is called like ```purpDoc (phrase swhsPCM) progName```. 
```progName``` is according to the Concepts module 
```haskell 
progName    = commonIdeaWithDict "swhsName"   (nounPhrase "solar water heating system"
  "solar water heating systems") "SWHS" [materialEng]
```
This ```progName``` parameter of type CI will be a recurring parameter throughout the examples. 
While the ```swhsPCM``` is defined in the Concepts module as:
```haskell
swhsPCM :: CommonConcept
swhsPCM = dcc' "swhsPCM" (nounPhrase''
  (S "solar water heating systems" +:+ S "incorporating" +:+ short phsChgMtrl)
  (S "solar water heating systems" +:+ S "incorporating" +:+ short phsChgMtrl)
  CapFirst CapWords)
  "solar water heating systems incorporating phase change material"
  "SWHS"
```
Key points:
1. The purpose is implemented in one function called purpDoc
2. The function purpDoc takes two parameters, one of type sentence other of type CI.
3. The purpose could be implemented with just the second parameter, progName. 

**SSP**
Here is the code for the function.
```haskell 
purposeDoc :: (Idea a) => a -> Sentence
purposeDoc pname =
  foldlSent [S "The primary purpose of this", phrase document, S "is to",
  S "record the", plural requirement `sOf` short pname `andThe` plural model,
  S "that will be used to meet those" +:+. plural requirement, 
  atStart' goal `sC` plural assumption `sC` plural thModel `sC` 
  plural definition `sC` S "and other", phrase model, S "derivation",
  phrase information, S "are specified" `sC` S "allowing the reader to fully",
  S "understand" `sAnd` S "verify the", phrase purpose `sAnd` S "scientific",
  S "basis of" +:+. short pname, S "With the exception of", 
  plural systemConstraint, S "in", makeRef2S (SRS.sysCon [] []) `sC` S "this",
  short Doc.srs, S "will remain abstract, describing what", phrase problem,
  S "is being solved, but not how to solve it"] 
  --FIXME: Last sentence is also present in GlassBR, SWHS and NoPCM... pull out?
```
Here is what is printed in SRS Latex file: 
"
The primary purpose of this document is to record the requirements of SSP and the models that will be used to meet those requirements. Goals, assumptions, theoretical models, definitions, and other model derivation information are specified, allowing the reader to fully understand and verify the purpose and scientific basis of SSP. With the exception of system constraints in \hyperref[Sec:SysConstraints]{Section: System Constraints}, this SRS will remain abstract, describing what problem is being solved, but not how to solve it.
"
When ```purposeDoc``` is called it is called with parameter ```ssp``` which according to the Definitions module is a ```CI```. Here is its full definition:
``` haskell
ssp :: CI
ssp = commonIdeaWithDict "ssp" (pn' "Slope Stability analysis Program") "SSP"   [civilEng]
```
This CI or CommonIdea data type is a recurring parameter throught the example, usually occurring under the name ```progName```. 

Key points:
1. SSP is currently the best example we have.
2. Similar to GamePhysics and unlike SWHS and GlassBRl the ```purposeDoc``` is executed and stored in an intermediate variable. 
3. The purpose uses just one paramter, which is the what I suggested in my previous "fix" for the SWHS module in issue #1570 . 
4. As the designer communicates in the FIXME, the same sentence being used in all examples is not desirable. This will be kept in mind when designing a solution. 

**GlassBR**

Here is the function ```purpOfDocIntro ```. 
```haskell
purpOfDocIntro :: NamedChunk -> CI -> NamedChunk -> Sentence
purpOfDocIntro typeOf progName gvnVar = foldlSent [S "The main", phrase purpose,
  S "of this", phrase typeOf, S "is to predict whether a given", phrase gvnVar,
  S "is likely to resist a specified" +:+. phrase blast, S "The", plural Doc.goal
  `sAnd` plural thModel, S "used in the", short progName, phrase Doc.code,
  S "are provided" `sC` S "with an", phrase emphasis,
  S "on explicitly identifying", plural assumption `sAnd` S "unambiguous" +:+.
  plural definition, S "This", phrase typeOf, S "is intended to be used as a",
  phrase reference, S "to provide all", phrase information,
  S "necessary to understand" `sAnd` S "verify the" +:+. phrase analysis,
  S "The", short Doc.srs, S "is abstract because the", plural content, S "say what",
  phrase problem, S "is being solved" `sC` S "but not how to solve it"]
  --FIXME: Last sentence is also present in SSP, SWHS and NoPCM... pull out?
```
The latex reads
"
The main purpose of this document is to predict whether a given glass slab is likely to resist a specified blast. The goals and theoretical models used in the GlassBR code are provided, with an emphasis on explicitly identifying assumptions and unambiguous definitions. This document is intended to be used as a reference to provide all information necessary to understand and verify the analysis. The SRS is abstract because the contents say what problem is being solved, but not how to solve it.
"
The function is called with three arguements```purpOfDocIntro document glassBR glaSlab```. 

The first parameter in the function call ```document```. ```document``` is used in other examples but is not a parameter, precisely because it is a global variable. However I would not rush to eliminate this parameter, as it could be useful for distinguishing the HTML and SRS purpose. 
The second parameter is of type CI and can be considered similar to the progName in other examples. 
The third argument is the ```glaSlab``` and is of type NamedChunk. According to the concepts module this is a NamedChunk which has declaration ```data NamedChunk = NC {_uu :: UID, _np :: NP}```. After doing ```short glaSlab``` it translates to "glass slab". Luckily this is also a global variable so it could be removed.  

Key Points:
1. The purpose is implemented in one paragraph purpOfDocIntro with three parameters.
3. This is the first example where having MORE THAN 2 parameter may be desirable. 
4. Again as communicated by the FIXME purposes should be distinct. 

### GamePhysics
The code for generating the purpose:
```haskell
para1_purpose_of_document_intro :: Sentence
para1_purpose_of_document_intro = para1_purpose_of_document_param gamePhysics 
  document programDescription (plural game) (map plural detailsAndGoal)

programDescription :: Sentence
programDescription = foldlSent_ [phrase openSource, getAcc twoD, 
  phrase CP.rigidBody, phrase physLib]

para1_purpose_of_document_param :: (Idea a, NamedIdea b) => a -> b -> Sentence -> Sentence ->
  [Sentence] -> Sentence
para1_purpose_of_document_param progName typeOf progDescrip appOf listOf = foldlSent 
  [S "This", phrase typeOf, S "describes the modeling of an",
  progDescrip, S "used for" +:+. appOf, S "The", 
  foldlList Comma List listOf, S "used in", short progName, 
  S "are provided. This", phrase typeOf, 
  S "is intended to be used as a", phrase reference, 
  S "to provide all necessary", phrase information, 
  S "to understand and verify the", phrase model]
```
The latex text is: 
"
This document describes the modeling of an open source 2D rigid body physics library used for games. The theoretical models and goal statements used in Game Physics are provided. This document is intended to be used as a reference to provide all necessary information to understand and verify the model.
"
The purpose of the gamephysics is certainly more complex than other examples. It has 5 arguments. The first two are the ```typeOf``` for specifying the format (for the SRS it is document) and the progName which is common to nearly all examples. The next is the ```programDescrip``` sentence. However I fail to see the purpose of making this a parameter, perhaps it is temporary so as to evolve as the GamePhysics example progresses. The next parameter is appOf which when the function is called becomes ```game```, I could see this as becoming a global variable because it is used so often through the document. The last parameter is a list of Sentences to store the goal. 

Key Points:
1. The purpose for GamePhysics is implemented in a very distinct way, with more parameters, and intermediate variables./functions.  
2. There is a plausibility of eliminating some of the parameters. 
3. This example indicates that the purpose function needs to allow for significant degrees of freedom among the example, more specifically allow for MORE THEN 2 parameters. .

**Comment by muhammadaliog3** [comment]
If the above Problem Description was clear I will propose the only solution I can currently think of. 

Criteria for a solution
1. Promote reuse through similar purpose functions. 
2. Allow for each example to have varied purposes. 

Perhaps the best thing to do in this situation is to have a common function declaration but each example implement its own version of the declaration. A possible declaration could be: 

purposeOfDoc :: CI -> NamedChunk -> [Sentence] ->Sentence

The last, sentence list parameter, is used to store any extra parameters that a specific example needs. 

Of course, there is potential for even more common variables. This is because there are many variables that the purpose function uses that are global and are not included in the parameters of the function. However, this will take some more analyses on my part to find all the common parameters.

**Comment by JacquesCarette** [comment]
That is a thorough analysis - thank you. It makes me very confident that you understand the full problem, and thus that you are well-placed to design a solution.

However, I think your basic solution is, well, too basic.

But you also did not have all the information you needed in hand. To be precise:
1. the actual exact text of the 'purpose section' for any/all of our documents is not fixed. [In fact, that's what started all of this, #1570 documents a desire to improve it.]
2. each of those 'purpose section' has some specific information that needs to be communicated. That information (unlike the wording) needs to be there.

So you should go over your quite thorough analysis above, and extract, for each of the examples, the 'key information' that is communicated in each of the paragraphs. Analyse the commonalities and the variabilities.

Remember that some variabilities are 'structural': the name of the program changes for each example, but its information is the same, and it "fits", structurally, in the same place in a sentence. In other words, some sentences can be templates with holes for specific information to be plugged-in.

You're partway there with your proposal for `purposeOfDoc` above. Just dig a bit more.

BTW, you should never be idle. Best to have 3-4 issues "on the go" at any one time, so that if you're stuck (or waiting on us) for 1-2, you still have things to do.

**Comment by muhammadaliog3** [comment]
Having looked closer purposes of each of the 4 examples I came up with a bare-bone minimum paragraph that is compatible with any example. This bare-bone paragraph contains 4 sentences and requires just 3 parameters. I choose parameters so that arguments would already be defined within the concepts module of the examples or within the comments od the concept modules. 

paramter1 = purpose
     SWHS: "a Solar Water Heating System"
     SSP: "a Slope Stability Analysis Program"
     GlassBR: "a Glass Safety Analysis Program" 
     GamePhysics: " a Game Physics Library"

paramter2 = abbrv
     SWHS: "SWHS"
     SSP: "SSP"
     GlassBR: "GlassBR" 
     GamePhysics: " GamePhysics"

paramter2 = exceptions
     SWHS: None
     SSP: None
     GlassBR: None
     GamePhysics: ", with the exception of constraints"

"   _The primary purpose of this document is to describe Software for_ "+
     purpose + ".  _The goals and theoretical models used in the_" +abbrv +" _code are 
     provided, with an emphasis on explicitly identifying assumptions and unambiguous 
     definitions. This document is intended to be used as a reference to provide all information 
     necessary to understand and verify the analysis.  This SRS will remain abstract, describing what 
     problem is being solved, but not how to solve it_" + exception +"."

However the main problem with this example is that the purposes of each example will share too many common sentences. Another potential problem is that perhaps the purpose is too rigid, that is the function does not allow for the purpose to be customized for each example.

For that I offer 4 potential solutions:
1. Given that there are 4 sentences we can create another 4 sentences with different wordings. Then we pseudo-randomly pick 4 sentences from the 8 for each example. Pseudorandomness can be created off, for example, the 2nd letter of each abbrv. 

2. Allow for a 4th parameter, a list of sentences. This list of sentences can be appended after the 3rd sentence. 

3. perhaps the best solution is to allow for more parameters that can serve as sub-sentences. That is have default values for parameters that can be changed to anything else when the purpose function is called. For example, by default line 3 will end with "understand and verify the analysis" but can be changed to "attest the scientific basis". 

4. Do nothing, perhaps variability is not such as important criteria for the purpose function, hence just use the bare-bone function.

**Comment by smiths** [comment]
I like your analysis @muhammadaliog3.  It makes sense that this section should be similar between all of the examples, because the purpose of the document is the same in all cases.  This section is summarizing the purpose of an SRS document.  The purpose does not change between specific instances.  The knowledge about the document is another category of knowledge that Drasil keeps.  I don't think we currently have this, but we would like to record the knowledge of the purpose of all of the sections, as well as the purpose of the entire document.

Your proposed paragraph is good, but not quite right.  As I mentioned previously the SSP example is the closest to what we want.  The purpose of the document is not the same as the purpose of the software itself.  Most of the examples get this wrong. I suggest the following for your boilerplate:

"The primary purpose of this document is to record the requirements of_ " +
     prog_name + ".  _Goals, assumptions, theoretical models, definitions, and other model derivation information are specified, allowing the reader to fully understand and verify the purpose and scientific basis of_" + prog_name + ".  This document is intended to be used as a reference to provide all information necessary to understand the problem. With the exception of system constraints in Section: System Constraints, this SRS will remain abstract, describing what problem is being solved, but not how to solve it."

"This document will be used as a starting point for subsequent development phases, including writing the design specification and the software verification and validation plan. The design document will show how the requirements are to be realized, including decisions on the numerical algorithms and programming environment. The verification and validation plan will show the steps that will be used to increase confidence in the software documentation and the implementation. Although the SRS fits in a series of documents that follow the so-called waterfall model, the actual development process is not constrained in any way. Even when the waterfall model is not followed, as Parnas and Clements point out parnasClements1986, the most logical way to present the documentation is still to "fake" a rational design process."

I've parameterized the above by just one parameter, the program name (prog_name).  I'm not an expert on the DSLs in Drasil, but the program name is store somewhere.  I've removed the purpose, because that is the purpose of the software, not the purpose of the document.  The abbreviation you have used might be the program name, but not every program will have an abbreviation.  I removed the exception parameter and instead included the exception for all of them.  The exception is about software constraints, and those are handled the same in all of the examples.  It just happens that the authors of the original document sometimes deleted this information.  I would rather that it is included.

The drawback that you highlight, that all of the example will share too many common sentences, is not actually a drawback.  It is an advantage!  If the knowledge is the same in all of the examples, why shouldn't we use the same words.  If we find a mistake in the knowledge, we can then fix it once and fix all of the examples.  This is what we want!  :-)  Therefore, I like your 4th option.

A 2nd parameter that is worth considering is verbosity.  I feel like at some point we will make this a global variability for the entire document.  Even better, we have discussed customizing the knowledge in the document to the assumed background of the reader, but that is too big for right now.  The Purpose of the Document section maps nicely to a verbosity variability.  The "terse" version would just be the first paragraph.  The "verbose" version would be both the first and second paragraphs.

**Comment by JacquesCarette** [comment]
I have nothing to add to @smiths 's feedback - I agree with all of it.

One comment though: this is very valuable Drasil-in-Drasil information, i.e. the above is design information for Drasil. We should at the very least not forget this.

Suggestion:
1. create a DESIGN.md file in the same directory where the `purpDoc` function is written
2. drop a summary of the above information in it
3. make sure to also have a link to this issue in that file.

**Comment by muhammadaliog3** [comment]
So I think the  last decision is where do we define the function purpDoc. I don't think that it could be in the DocLang package, so should I just copy and paste the same function into each example.

**Comment by smiths** [comment]
@muhammadaliog3, I don't know the answer to your question, but I do know that @JacquesCarette will not suggest copy and paste.  A good heuristic for design is to always avoid copy and paste.  If you are using copy and paste, that is a clear sign that you are doing something wrong.  :-)

**Comment by JacquesCarette** [comment]
copy-paste is **definitely wrong**.  Why can't it be in `docLang` ?

**Comment by muhammadaliog3** [comment]
I am currently having trouble with a few design decision

1. Where should we define the purposeDoc function within the DocLang package? The best spot that I could find was in the [section directory](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-docLang/Drasil/Sections/Introduction.hs) or the [SRS directory](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-docLang/Drasil/DocLang/SRS.hs), but the sections directory looks more natural because it contains many sentences already. 

2. The verbosity for the document is not clear. A reminder that I need the verbosity parameter to control whether we output 2 paragraphs or one paragraph. There are 2 places where I could find mention of the verbosity parameter. The first was in the drasil-code package CodeSpec.hs , which is a) probably controls code verbosity hence probably not what we want and b) has not been implemented yet as evidenced by the comment is Main.hs. The second mention of verbosity is within the Body.hs is a variable stdFields which I think controls the document verbosity.
```haskell
stdFields :: Fields
stdFields = [DefiningEquation, Description Verbose IncludeUnits, Notes, Source, RefBy]
````
Is the stdFields what I should use for the verbosity of the purpose? 

3. Each example is currently not allowed to specify its purpose. Rather it can only specify the first sentence. The following module [Introduction.hs](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-docLang/Drasil/Sections/Introduction.hs)  (look to the purposeOfDoc function ) which actually generates the purpose section, turns that one sentence into a paragraph and then turns it into a section. Hence within the Body module of any given example, I have no control of the second paragraph. In order to have control of paragraphs within the Body module I would have to change how the purpose is generated, so that the  [Introduction.hs](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-docLang/Drasil/Sections/Introduction.hs) is no longer used as an intermediary and rather Body module generates the purpose section in its entirety. Is my analysis correct, because that would involve several more modules being changed.

**Comment by smiths** [comment]
@muhammadaliog3, I do not know the best answers for questions 1 and 3, but for verbosity, I  believe we need a new parameter.  We don't think the existing verbosity measures refer to the verbosity of the text.  One is for the code, as you said, and the other is for the length of the definitions (I believe).

**Comment by JacquesCarette** [comment]
Sorry that I've been so slow on answering these (I've got ~15 students sending me a variety of complex questions, so these sometimes pile up).

1. Section directory works.
2. You will probably need to extend a type (`Fields` or a sub-part) to add this new idea to it.
3. Yes, you will have to tweak that part of `purposeOfDoc` to be generalized.

Yes, this one change is larger than it at first looked. You might want to work on a few other things first, and then get back to this.

**Comment by muhammadaliog3** [comment]
I have created a sample solution, but currently I have only implemented the SWHS and NoPCM example. It can be found in the Issue-#2116 branch. It is quite a large change in the sense that it changed 1-2 lines on several modules

The general solution:
In accordance with our previous decisions, the Drasil/code/drasil-docLang/Drasil/Sections/Introduction.hs I have created a function called ```purpDoc```, that each example can import through the DocLang module. This function takes 2 parameters of ```CI``` and ```Verbosity```, and returns a list of either 1 or 2 sentences. Each sentence is interpreted as its own paragraph by the docLang module internally.  

The issues I am having:
1. To control the verbosity in the examples should I use the verbosity datatype defined in 
Drasil/code/drasil-code/Language/Drasil/Choices.hs or 
Drasil/code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs. In my branch I have used
Definition.hs. If we are to go with the Choices module can I add my own field for "purposeVerbosity" and make the choices as a parameter to purpDoc instead of ```Verbosity``` OR should I just let the examples manually enter ```Verbose``` or ```Quiet```. 
 
2. In order for the IPurpose to handle a list of Sentences instead of just a Sentence.
```haskell
data IntroSub where
  IPurpose :: Sentence -> IntroSub
```
to 
```haskell
data IntroSub where
  IPurpose :: [Sentence] -> IntroSub
```
This involved changed DLPlate and sentencePlate. What should I change them to?
I suggest no change to the DLplate data type. 
```haskell
instance Multiplate DLPlate where
  multiplate p = DLPlate ds res intro intro' stk stk' gs gs' ss ss' pd pd' sc
    rs rs' lcp ucp ts es acs aps where
    .....
    intro' (IPurpose s) = pure $ IPurpose s
    .....
```
to 
```haskell
    ......
    intro' (IPurpose s) = pure $ IPurpose s
    .....
```
And the following change to sentencePlate
```haskell
sentencePlate :: Monoid a => ([Sentence] -> a) -> DLPlate (Constant a)
sentencePlate f = appendPlate (secConPlate (f . concatMap getCon') $ f . concatMap getSec) $
  preorderFold $ purePlate {
    introSec = Constant . f <$> \(IntroProg s1 s2 _) -> [s1, s2],
    introSub = Constant . f <$> \case
     (IPurpose s) -> [s]
```
to 
```haskell
...
(IPurpose s) -> s
...
```

**Comment by JacquesCarette** [comment]
Answering the questions:
1. `Verbosity` as you have it seems to make sense
2. I think those changes to the plate code make sense. I don't think these plates go 'in' to sentences, it just finds them.

**Comment by muhammadaliog3** [comment]
@smiths 
I am not sure if this is an inconsistency or if it is just a grammar difference but all of the program names have different noun types, that is they are noun phrases or proper nouns.
```haskell

progName    = commonIdeaWithDict "swhsName"   (nounPhrase "solar water heating system"
  "solar water heating systems") "SWHS" [materialEng]

gamePhysics = commonIdeaWithDict "gamePhysics" (pn "game physics library") "Game Physics" [physics]

ssp = commonIdeaWithDict "ssp" (pn' "Slope Stability analysis Program") "SSP"   [civilEng]

glassBR       = commonIdeaWithDict "glassBR"       (pn "GlassBR")                           "GlassBR"  [idglass]

```

Should I make update the program names or should I just make my function robust to these differences?

**Comment by smiths** [comment]
@muhammadaliog3 this is interesting.  @JacquesCarette will know better than me, but I think changing the program names to be consistent will break the current examples in many places.  I believe (@JacquesCarette or @bmaclach can correct me) that the difference is related to capitalization.  The sentences that are generated will be capitalized incorrectly if you change these for consistency.  I think it would be best to do as you suggest and make your function robust enough to handle all cases.

**Comment by muhammadaliog3** [comment]
This is the previous comment, only to help @JacquesCarette gain context that is deleted
@smiths 
I am not sure if this is an inconsistency or if it is just a grammar difference but all of the program names have different noun types, that is they are noun phrases or proper nouns.
```haskell

progName    = commonIdeaWithDict "swhsName"   (nounPhrase "solar water heating system"
  "solar water heating systems") "SWHS" [materialEng]

gamePhysics = commonIdeaWithDict "gamePhysics" (pn "game physics library") "Game Physics" [physics]

ssp = commonIdeaWithDict "ssp" (pn' "Slope Stability analysis Program") "SSP"   [civilEng]

glassBR       = commonIdeaWithDict "glassBR"       (pn "GlassBR")                           "GlassBR"  [idglass]

```

Should I make update the program names or should I just make my function robust to these differences?

**Comment by muhammadaliog3** [comment]
The title case for the propernouns is the following, 
```
  titleCase n@ProperNoun {}  _ = phraseNP n
```
So as I understand propernouns are the same even when titleized/capitalized. I just wanted to make sure that this is grammatically correct @smiths.

**Comment by smiths** [comment]
Thank you @muhammadaliog3 for the information.  My memory might be false, but I believe there is a difference between capitalizing a title and capitalizing a word at the start of a sentence.

**Comment by JacquesCarette** [comment]
I think our grammar combinators for capitalization are generally correct. [We've spent quite a bit of time on them.]  So I don't think there are problems coming from there.

From the comments above, it does look like there might be some problems remaining, but from this issue, I don't quite "see" them. But perhaps I will when I look at the commits themselves.
