### ISSUE TITLE
Haddock Documentation?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2127]
@bmaclach, do you know what happened to the Haddock Documentation that used to be on the CI generated Drasil page:

https://jacquescarette.github.io/Drasil/

The introductory text still mentions the Haddock documentation, but I couldn't find a link.  I remember that it used to be there.

If you don't  know, maybe @JacquesCarette recalls?  I thought the automatically generated documentation was a useful thing to have, especially for people new to Drasil.

**Comment by bmaclach** [comment]
I'm not sure why it disappeared. I still see the code in `site.hs` and `index.html` for displaying this part of the webpage. I think its absence means that the path to the docs that we construct in `site.hs` is no longer correct, though I don't know why that would have changed.

**Comment by smiths** [comment]
Yes, it does seem odd for the Haskell documentation to no longer appear.

@Mornix, if you happen to be monitoring Drasil at some point, would you mind looking into this?  I have a feeling that it is a small thing that you would be able to diagnose and fix quickly.  If I'm wrong and it is a bigger issue, that would be good to know too.  :smile:

**Comment by JacquesCarette** [comment]
I don't know what happened. It used to be there. I'll also add myself as an assignee - but unlikely to get to look at it for a few weeks.

**Comment by Mornix** [comment]
I should be able to look at this again fairly soon. Docs were intentionally disabled (#1578) as a Stack upgrade caused a breakage with deploy. If this is still the case, I should be able to use `sed` or something similar to rewrite absolute links to relative for deploy.

**Comment by Mornix** [comment]
@JacquesCarette addressed this with 340638bad523d7c7c5e2335fd66569a9f1985c25. Closing.

**Comment by smiths** [comment]
This is great!  Thank you @Mornix and @JacquesCarette.
