### ISSUE TITLE
GOOL's &-- operator should generate code that uses decrement operator

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2148]
Currently, GOOL's `&--` operator (for updating a variable's value by subtracting 1) generates code that performs the subtraction and assignment separately. For example, the GOOL code:
`v &--`
generates something like:
`v = v - 1`.

I think that all of our current target languages (except Python) offer the decrement operator (--), so we should update the implementations of `&--` to use this, to generate code like:
`v--`

**Comment by Nathaniel-Hu** [comment]
For Python, can we use something like:
`v -= 1`
as the decrement operator?

**Comment by bmaclach** [comment]
@Nathaniel-Hu Yes, that's a good idea.

**Comment by bmaclach** [comment]
@Nathaniel-Hu To keep this issue independent from #2147, what you will want to do is use GOOL's `&-=` operator in the implementation for `&--` for Python. That way, if you do this issue before @muhammadaliog3 gets to #2147, the generated Python code will still be `v = v - 1`, but once #2147 is complete it will automatically change to `v -= 1`

**Comment by Nathaniel-Hu** [comment]
Alright then. Thanks for the heads up!
