### ISSUE TITLE
Contributor Test

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2161]
Now that you have almost completed #2136, the next task is to write a test for future contributors.  @JacquesCarette and I discussed approaches for training future developers and the idea we came up with was to start with a test.  @Nathaniel-Hu, please write a short test, consisting of multiple choice and short answer questions.  We'll use this test for future developers.

The test will be easier to write, and easier for @JacquesCarette and I to judge, if you include the answers.  You can create a branch for the test.  When we are done, we'll probably delete the branch, so that the answers aren't available for future developers.  :smile:

I'll attach LaTeX files that you can use as a starting point.  The files are from a previous undergrad test.  I haven't done anything to change the test to suit our current needs; I just deleted most of the questions.  You can remove most of the preamble.  We just need a title for the test.  (We could do the test with other software, but practicing with LaTeX would be useful (and fun!) for you.)

You will have to rename the first file to have the extension tex, and the second file to have the extension cls.  GitHub doesn't support those extensions, so I relabelled both files to have the extension txt.  :smile:

[PotentialContributorTest.txt](https://github.com/JacquesCarette/Drasil/files/4724969/PotentialContributorTest.txt)

[examtst.txt](https://github.com/JacquesCarette/Drasil/files/4724974/examtst.txt)

**Comment by Nathaniel-Hu** [comment]
@smiths, I'm unsure as to what content I should be including on the test. Should I (at least) be including the following?
- sample Haskell code (e.g. simple functions, class definitions, things from [this site](http://learnyouahaskell.com/chapters))
- items from the Contributor's/Quick Start Guides
- sample LaTeX code (from [LaTeX tutorials](https://www.latex-tutorial.com/tutorials/))
- basic git (e.g. commands, branching, etc.)

If I am missing anything or including anything unnecessary, please let me know.

**Comment by smiths** [comment]
@Nathaniel-Hu, I'm glad you asked your clarifying question before getting started.  At this time, I'm only thinking that the test question will be related to the Contributor's/Quick start guides, and the related basics of git, and issue tracking.

**Comment by Nathaniel-Hu** [comment]
@smiths and @JacquesCarette, I've created a sample Contributor's Test + Answers. It is almost complete, but I would like your feedback on it so far. Thanks!

https://github.com/JacquesCarette/Drasil/tree/Issue%232161/People/Nathaniel/Contributor's%20Test

**Comment by JacquesCarette** [comment]
I like the topics you chose. They are the ones that indeed should be understood.

I am, however, not a big fan of multiple choice questions / answers. I don't think you need to rewrite this though. I think you might want to simply add a "explain your answer" to each.

Multiple choice only tests quite shallow understanding - which is unfortunately the only thing that can be done when you're testing 200 students. When you are testing 1-5 students, you have the luxury of being able to gauge deeper understanding - and you want deeper understanding for working on the Drasil code base using the current tool suite.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette ok then, I will be sure to make those changes. Thanks for the feedback!

**Comment by smiths** [comment]
I agree with @JacquesCarette.  Good start on the test, and the right topic for questions.  My only additional suggestion is to remove the boilerplate at the beginning about student number, test instructions, etc.  We will definitely use this test in the future, but it will be administered on the honour of the people doing it; we won't be doing invigilated tests.

@JacquesCarette, I'm thinking that the "test" can be open resource.  I don't see any reason why the people taking it couldn't look up their answers.  Does that fit with your thinking?

**Comment by JacquesCarette** [comment]
Yes.

**Comment by Nathaniel-Hu** [comment]
@JacquesCarette and @smiths, I have made the changes and updated both the Contributor's Test and the Answers documents. Please review the changes, and let me know if there are any other changes that you would like me to make. 😄 

[Latest Commit](https://github.com/JacquesCarette/Drasil/commit/e426c5e0e2b9499b992bf3dffb9f74b9ed943316#diff-74688a64ce476540ea5214ff409c9181)

[Contributor's Test Folder](https://github.com/JacquesCarette/Drasil/tree/Issue%232161/People/Nathaniel/Contributor's%20Test)

**Comment by smiths** [comment]
Looks great @Nathaniel-Hu!  Good work.  Could you please just add a few more questions, based on the feedback from @muhammadaliog3 at:

https://github.com/JacquesCarette/Drasil/issues/2171#issuecomment-641252503

Specifically, @muhammadaliog3 mentions:

"... things like what is the difference between a remote branch and local branch, what is origin, how to reverse commits, what is head, which branch are you pulling from when you "git pull".''

**Comment by smiths** [comment]
Looks good @Nathaniel-Hu.  I made a few small comments as part of your last commit.  As an aside, when you name your branches, could you include a hint on what the branch is about.  The issue number is nice, but I don't remember the numbers and have to look it up each time.  If the name suggests what it is, then it will save me (and probably others) a step.

**Comment by Nathaniel-Hu** [comment]
@smiths and @JacquesCarette, are there any other changes you would recommend that I make to this test, or is it sufficient for now?

**Comment by smiths** [comment]
@Nathaniel-Hu, the test looks good.  I don't have any changes to suggest to the test.  However, I think we should stop maintaining two versions of the test - one with answers and one without.  We should just maintain the one with answers, since the testing template is written to either display answers or not (by setting a configuration parameter to `y` or `n`).  We should set the parameter to `n`, and commit the `n` version of the pdf.  For people in the future that do the test, they can do the test from the pdf version, and then look at the right answers in the original tex file.  They can even compile it with the flag set to `y`, if they want to, to see the answers in the pdf.

I'm sure we change questions, and add questions, in the future.  Having to maintain two almost identical files is a headache that we don't want.  Maintaining one version does mean that we are trusting future students to not "cheat," but this isn't actually a course related test.  The only person they would be cheating would be themselves.  :-)

The next question will be, where do we put the test in the repo.  I know we would like to link to it from the contributor's guide, but where to put the actual test is a question.  It isn't really Drasil related.

@JacquesCarette, do you think it would make sense to the put the test in the se4sc repo, instead of the Drasil repo?  We could put it in the SummerResearch folder, the UGStudents folder, or even the GradStudResources folder.

**Comment by JacquesCarette** [comment]
Test is good now.

In a sense, for a future Drasil, a test like this would be an interesting artifact to incorporate: it's a self-test for developers that embodies knowledge assumed in the construction of Drasil.  Having said that, whether it's here or in se4sc, I don't have a strong opinion either way.

**Comment by Nathaniel-Hu** [comment]
@smiths and @JacquesCarette,
I looked through the Contributor's Test, and while most questions are generic (related to using git and such), there are a few questions that are Drasil-specific. Would that affect where the Contributor's Test should/would be put?

**Comment by JacquesCarette** [comment]
I don't think that necessarily affects where it should be put, but it should probably mean that the test should be split into sections (by topic), so that some sections can be skipped.

**Comment by smiths** [comment]
@Nathaniel-Hu, let us put the Contributor's test on the Drasil site.  We will be sending new contributors to this test, so having Drasil as its home makes sense.  We will want a pointer to the contributors test on the Wiki, but we still want a home for the test that we can point to.

My suggestion is that we create a doc folder, and put the contributor's test inside a folder inside doc.  @oluowoj is working on documentation for using Drasil, so there will be other uses for the doc folder.

**Comment by Nathaniel-Hu** [comment]
@smiths, this `doc` folder is on the Drasil GitHub repo, correct? Also, has the `doc` folder been created, or should I created it on my branch, and push those changes to remote (and create a pull request)?

**Comment by smiths** [comment]
Yes, the doc folder would be on the Drasil GitHub.  The folder does not currently exist.  You will have to create it.

**Comment by Nathaniel-Hu** [comment]
Ok then, I will do that, and create a new pull request for it. After that, I will also create the pointer for it in the Wiki.

**Comment by smiths** [comment]
Great!

**Comment by Nathaniel-Hu** [comment]
I'll update the README file as well. Is there any specific description that you would like me to give the `doc` folder?

**Comment by smiths** [comment]
You can just describe it as documentation related to Drasil.

**Comment by Nathaniel-Hu** [comment]
Alright then, thanks.

**Comment by Nathaniel-Hu** [comment]
@smiths and @JacquesCarette,
Should I place the pointers to the Contributor's Test under the [Getting Started](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#getting-started) section of the wiki?

**Comment by smiths** [comment]
Yes.

**Comment by Nathaniel-Hu** [comment]
Quick question; is this test highly recommended or mandatory for new future contributors?

**Comment by Nathaniel-Hu** [comment]
Also, while I'm editing the Wiki (Contributor's Guide), should I also make these [changes](https://github.com/JacquesCarette/Drasil/issues/2171#issuecomment-661296981) as well?

**Comment by smiths** [comment]
@Nathaniel-Hu, you can just characterize the test as a test for new users to help determine where they should put their effort to improve the skills and knowledge they will need for working with the software development infrastructure around Drasil.

**Comment by Nathaniel-Hu** [comment]
Alright then. Thanks!

**Comment by Nathaniel-Hu** [comment]
I have added in the pointer and description points for the Contributor's Test under the [Getting Started](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#getting-started) section of the Contributor's Guide (in the Wiki).

**Comment by smiths** [comment]
Looks great @Nathaniel-Hu!
