### ISSUE TITLE
Pulling out libraries from this repo

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2183]
Right now Drasil shows as 93% C++, because of the libraries it uses. This is silly, we want to show up as a Haskell project, not a C++ project!

Solution: we should make a different repo that has these things in it.

**Comment by smiths** [comment]
Great idea @JacquesCarette.  We should make sure that your solution is as easy to use, or almost as easy to use, as the current implementation.  Right now someone outside our group can get our case study examples running without too much effort.  With a second repo there will be an additional step to clone that repo, but hopefully that is the only extra step.

**Comment by bmaclach** [comment]
The tricky part with moving them to a different repo is that we still need them to compile the code during Drasil's build (it's probably possible even with them in a different repo, but I don't know how).

I just opened a PR (#2184) which I think should make GitHub recognize this as a Haskell repo again, by having it ignore the external libraries for its statistics. We may want to just do that instead, or at least use it as a temporary fix until we figure out how to actually move the libraries out of this repo.

**Comment by JacquesCarette** [comment]
Thanks, I'll try that first.

**Comment by JacquesCarette** [comment]
And it worked - we're back to 83% Haskell.  This is probably good enough.
