### ISSUE TITLE
GlassBR's GTF should not be an integer

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#2203]
The GTF (Glass Type Factor) chunk in the GlassBR example currently has `Integer` as its `Space` because the values we use are integers, however there is no guarantee in general that a Glass Type Factor will be an integer, so this should be represented as a real number instead (see https://github.com/JacquesCarette/Drasil/commit/a40c9a32df0af722bc9a0b07cda9bdb584633856#commitcomment-40458483).

**Comment by smiths** [comment]
Thank you for creating this issue @bmaclach.  I believe this will be a quick one to fix.
@Nathaniel-Hu and @muhammadaliog3, if you are looking for a relatively quick issue to close, please go ahead and self-assign to this issue.

**Comment by muhammadaliog3** [comment]
I forgot to put the closes 2203 in the comments in the pr (I forgot cause I haven't made a PR in over a week). So I am manually closing this issue.

**Comment by smiths** [comment]
Sounds good.
