### ISSUE TITLE
Switch from using String in Data Table Generator

### ISSUE THREAD

**Issue by Nathaniel-Hu** [JacquesCarette/Drasil#2210]
Based upon [discussions](https://github.com/JacquesCarette/Drasil/issues/2095#issuecomment-647790570) in Issue #2095, the Data Table Generator will most likely move away from using the `String` type to another faster, more space-efficient type (likely the `ByteString` type). 

However, a re-investigation (as per @JacquesCarette's request) should likely take place to determine the best "state of the practice" before committing to a change. Maybe look among alternatives to find the best choice type.

~~Note: the current version of the Data Table Generator (in /scripts/) is currently contained in [this branch](https://github.com/JacquesCarette/Drasil/tree/Issue%23703_GenDataTable), and is awaiting merge approval in [this pull request](https://github.com/JacquesCarette/Drasil/pull/2208).~~
Note: pull request has been merged.

**Comment by balacij** [comment]
Closing in favour of #2606. As always, if anyone feels otherwise, please re-open.
