### ISSUE TITLE
Switch to using Real Parser to import Config settings

### ISSUE THREAD

**Issue by Nathaniel-Hu** [JacquesCarette/Drasil#2211]
Based on @JacquesCarette's [comment](https://github.com/JacquesCarette/Drasil/commit/8b38d6dc24bf8f4ae9261e2060a1f6eebd190212#r40456923), the optimal solution is to utilize a real parser to extract the settings imported from the configuration file (DTG_Config.txt) in DataTableGen.hs. This is because using a real parser would help to improve error messages.

See line 119 (in [DataTableGen.hs](https://github.com/JacquesCarette/Drasil/blob/Issue%23703_GenDataTable/code/scripts/DataTableGen.hs)) for the current "parser" used to extract the settings imported from the configuration file. 

~~Note: the current version of the Data Table Generator (in /scripts/) is currently contained in [this branch](https://github.com/JacquesCarette/Drasil/tree/Issue%23703_GenDataTable), and is awaiting merge approval in [this pull request](https://github.com/JacquesCarette/Drasil/pull/2208).~~
Note: pull request has been merged.

**Comment by balacij** [comment]
Closing in favour of #2209.
