### ISSUE TITLE
Create Drasil Installation Guide

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2214]
Create installation guide.

Format?
Where?

**Comment by smiths** [comment]
The installation guide will be linked to from the contributor's guide (wiki).  In #2161 we have discussed creating a doc folder in Drasil.  This would be a good place to document the installation guide.

**Comment by oluowoj** [comment]
Sure, I will keep this in mind

**Comment by oluowoj** [comment]
@smith, I have a feeling that students would rather prefer to use Windows than Linux especially those from sciences - could be a wrong assumption. So we can have instructions for both Linux and Windows users I guess

**Comment by smith** [comment]
@smiths ^

**Comment by smiths** [comment]
If we can have instructions for Windows and Linux, that would be great.  However, for practical reasons, we might just target instructions for Linux, and provide instructions for a Windows user on creating a virtual Linux box.  It is less work to support one OS, than it is to support two.  We'll figure out what plan is feasible once we start getting specific.

**Comment by oluowoj** [comment]
closing this since you were working on it @smiths
