### ISSUE TITLE
Create double pendulum example in Drasil

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2216]
-Add Double Pendulum example in Drasil. 
-Document all steps in details (reverse engineer)

**Comment by oluowoj** [comment]
So I started Double Pendulum example, added a new template and updated all required files to build. I have documented all the steps so far. After I am able to run it successfully, I will create a PR.

**Comment by oluowoj** [comment]
@smith when I am done with this PR, I will start looking at the physics.

**Comment by smith** [comment]
@smiths ^ :)

**Comment by smiths** [comment]
@oluowoj, my github id is smiths, smith is someone else (Nathan Smith, from Iowa).

**Comment by oluowoj** [comment]
> @smiths ^ :)

Oops, my bad

**Comment by oluowoj** [comment]
@JacquesCarette @Mornix  any thoughts on what could be missing here?
![image](https://user-images.githubusercontent.com/43192745/88321979-049e7e00-ccee-11ea-93bb-480249bb0b6d.png)

Looking @ ChunkDB.hs, the error  points to line 81 in the screen shot below, i found  line 89 also related to the term map. I am missing a piece of information somewhere but yet to figure it out

![image](https://user-images.githubusercontent.com/43192745/88322576-e7b67a80-ccee-11ea-9c80-ae30221248d2.png)

And just a quick background info, I am adding a new example Double Pendulum to Drasil and trying to run make to build the new project.

Or has anyone come across this error working in Drasil? @muhammadaliog3  @Nathaniel-Hu

**Comment by JacquesCarette** [comment]
The error comes from the fact that the 'dblpendulum' chunk appears somethere, but it isn't being added to the Term Map when you build the SRS.  Something is missing in your `Body.hs` file that actually grabs all your knowledge and inserts it in the right tables before you generate the SRS.

**Comment by oluowoj** [comment]
Yeah, I am taking a closer look.

**Comment by oluowoj** [comment]
> The error comes from the fact that the 'dblpendulum' chunk appears somethere, but it isn't being added to the Term Map when you build the SRS. Something is missing in your `Body.hs` file that actually grabs all your knowledge and inserts it in the right tables before you generate the SRS.

Thanks, found it

**Comment by oluowoj** [comment]
Plugging in the sections of the SRS would be a good one - Just leaving a note here for myself to remember to discuss. with @JacquesCarette

**Comment by oluowoj** [comment]
Instead of trying to create all blank sections in the SRS. I will start working on the assumptions and see how it goes.

**Comment by oluowoj** [comment]
Adding link for easy access

**Comment by oluowoj** [comment]
https://github.com/best-zhang-zhi/CAS741Project/blob/master/Double%20Pendulum/docs/SRS/SRS.pdf

**Comment by JacquesCarette** [comment]
As far as I can tell, this is essentially done.

**Comment by smiths** [comment]
Yes, we will no doubt review the example and make changes, but this issue is complete.
