### ISSUE TITLE
Which equation number corresponds to which equation block in the SSP factor of safety derivation?

### ISSUE THREAD

**Issue by muhammadaliog3** [JacquesCarette/Drasil#2228]
The problem in #1778 was basically referencing equations. This requires two things, one that the equation block itself should have a reference, and two that reference should appear in the paragraph blocks. Currently we only reference the equations in the paragraph blocks. My first attempt added references to the equation blocks in Drasil, but we still need to add references to equation blocks in the generated code. 

Because we currently "only reference the equations in the paragraph blocks" , I do not know what equations are being referred to what. For example in the factor of safety derivation there is a line "Substituting Equation (8) into Equation (4) yields Equation (10):" , well what is equation block is "equation 4", is it the 4th equation listed in the derivation? Same goes for equation 7. 

@bmaclach worked on ssp, perhaps he could tell us.

**Comment by smiths** [comment]
@muhammadaliog3 the answer to your question about the numbering of the specific equations in SSP is given in the manual version of the SRS for SSP:

https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/docs/SRS/SRS.pdf

In the manual LaTeX version of the document we used `\label` and `\ref` pairs for the cross referencing.  Compiling the LaTeX document updates the numbers that appear in the pdf file.

**Comment by JacquesCarette** [comment]
Closing as this issue represents a method of implementation that doesn't leverage the native LaTeX support of labelling.
