### ISSUE TITLE
Short makeRefs?

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/Drasil#223]
Is there a "short" makeRef instead of a full reference? Right now makeRef gives the full reference IE (Section 4.1.2)  instead of just being able to supply the sentence I want to use with the reference like GS1, or just give (4.1.2)?

**Comment by szymczdm** [comment]
With the addition of the "RefName" field (around commit a51a739315345f07a0a017cf) we are now able to make references using whatever identifier we prefer.
