### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2230]
We should use badges to show that our stuff works on CI.  A simple example of doing this is documented at https://github.com/yallop/haskell-frex/pull/4/files .  Very easy indeed.

**Comment by smiths** [comment]
Is the idea to replace our Travis CI with a GitHub Action?

**Comment by JacquesCarette** [comment]
Well, we'll probably want both, for different things. I'm still figuring it out.

**Comment by smiths** [comment]
Sounds good.  Where do badges come in?  Is the badge the notification on the main GitHub page that shows the build status?

**Comment by JacquesCarette** [comment]
Badge that the build is passing is now live. We can add more later.
