### ISSUE TITLE
Including the auto-generated Analysis in the Nightly Deployments/Travis Builds

### ISSUE THREAD

**Issue by Nathaniel-Hu** [JacquesCarette/Drasil#2231]
Based upon discussions with @smiths, a good addition to the Drasil framework nightly deployments would be the addition of the automatically-generated Data Table (merged in pull request #2208). By making this addition, the scripts to generate the Data Table would also automatically be run in the Travis Builds in future pull requests. This issue is related to/compliments Issue #2221.

Note for @smiths and @JacquesCarette: Would there ever be a case where the Data Table would be treated like a stable folder file, or will it be allowed to just change without needing to be compared to a stable version of the Data Table?

**Comment by smiths** [comment]
Thank you for creating the issue @Nathaniel-Hu.  No, I do not think we would consider any design stable, just like we don't consider the Haddock documentation stable.  We assume that when we make changes to the design and the documentation, we are making each better.  Your tool is just giving us a snapshot of the current design.

**Comment by JacquesCarette** [comment]
In theory 3aea095 does the deploy. Once it looks like it worked, I'll hook it in to the web page too.
