### ISSUE TITLE
Placeholder for screenshots

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2233]
![image](https://user-images.githubusercontent.com/43192745/91794769-dfa10300-ebe9-11ea-8263-99595241b1c9.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/91795033-85ed0880-ebea-11ea-8e57-6ba12d52e68f.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/91797297-33aee600-ebf0-11ea-9765-88287a7d7dc7.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/91799081-52af7700-ebf4-11ea-9747-4802f0566b22.png)
![image](https://user-images.githubusercontent.com/43192745/91802056-999f6b80-ebf8-11ea-81ba-d4af52da4dc9.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/91803746-1f231b80-ebf9-11ea-8031-559e3713a440.png)

**Comment by smiths** [comment]
@oluowoj, I was looking into VirtualBox earlier, since I plan on using it for both my grad class and next term's undergrad class.  I like the idea of screenshots, but I don't think we have time to be that detailed.  It is also more work to maintain, since the details change over time.  Since I need to do something related to this anyway, why don't you leave the details of setting up the VM to me.  You can spend your time on the Drasil specific instructions.

**Comment by oluowoj** [comment]
oh okay that's fine not a problem. I will work on the Drasil instructions

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/92034710-9f519a00-ed3b-11ea-8e7f-d549d8115ef6.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/92035146-46363600-ed3c-11ea-9c18-9b7ba5cb6901.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/92657417-c9b6d080-f2c2-11ea-9134-4d387aa2424a.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/93262907-fe1f0680-f772-11ea-902c-10c40269cd8a.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/93566683-68929b00-f95b-11ea-8dd1-cfec2648bf80.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/93569122-23706800-f95f-11ea-971b-6dde1d76fadc.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/93642331-eee6c580-f9cb-11ea-9f2d-ac057d1c576b.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/94777309-45bbaa00-0391-11eb-8db4-7783dc95cc92.png)

![image](https://user-images.githubusercontent.com/43192745/94777925-4acd2900-0392-11eb-8dbe-85caf641fd05.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95074164-13d17d00-06dc-11eb-959b-69b092ef2e94.png)

**Comment by JacquesCarette** [comment]
So what are all these 'placeholder screenshots' ?

**Comment by oluowoj** [comment]
They are just screenshots I am using in preparing the user guide

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95530513-0c47f780-09ac-11eb-88e5-de0765f747dc.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95663720-7d53f000-0b0f-11eb-9709-f2fa50be0341.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95665007-6ebf0600-0b1a-11eb-8bd1-e38fa4b39c39.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95665067-da08d800-0b1a-11eb-9f3d-d8d0a4a79a57.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95670996-f8dd8d80-0b5f-11eb-8a36-9961e48e0376.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/95671244-74403e80-0b62-11eb-9c03-168497ec0bfb.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96004090-f782be00-0e08-11eb-9543-2711d61fae18.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96008019-1e42f380-0e0d-11eb-8e1a-000bdd3d077e.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96009587-d2914980-0e0e-11eb-8efa-58ce51a10dda.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96509253-bdab2080-1229-11eb-9694-b8143b283528.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96709941-5f855700-1369-11eb-8f4b-982cb0e9635f.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96710181-b0954b00-1369-11eb-82e1-a5c305abc023.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96713509-b6d9f600-136e-11eb-9969-0788e46783a7.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96713775-1d5f1400-136f-11eb-8406-119c58d55f8b.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96713793-264fe580-136f-11eb-8f88-8d598436d193.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96744172-c23f1880-1392-11eb-99d7-bb78d7d4b951.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96745203-de8f8500-1393-11eb-9290-0b191ecab950.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96758236-84e38680-13a4-11eb-97b4-20f3df89af46.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/96764819-eeb15f80-13a7-11eb-8d44-05f81d93cb27.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99345924-6ff1fa00-2861-11eb-8e35-d2e593ba4a03.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99355236-ec8ed380-2875-11eb-89fd-717e547a9f65.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99359127-8f4a5080-287c-11eb-8ff6-5a818f1bc8a0.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99360082-0af8cd00-287e-11eb-9d38-09346ef7691b.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99361695-80659d00-2880-11eb-8565-4d3e30fc6c10.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99419150-c7c44b80-28c9-11eb-92f1-b9019c2bd97d.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99489800-88801400-2936-11eb-8100-33552260863b.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99490450-d9dcd300-2937-11eb-963d-f87d060f5711.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99496122-aef77c80-2941-11eb-85c1-7e6f6ea6d781.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99496416-3cd36780-2942-11eb-93b6-c71a898f69c2.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99736144-e8400180-2a93-11eb-8ce9-355882816d7f.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99736500-7a480a00-2a94-11eb-9188-8feb00435764.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99737037-82547980-2a95-11eb-8bd7-220a9d7d57e3.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99737287-03137580-2a96-11eb-839d-06fd29f36a61.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99795665-23751b80-2afa-11eb-87b7-223338c7a444.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99891880-9edee600-2c3c-11eb-8c52-3afae5a36551.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99891918-1e6cb500-2c3d-11eb-8cd4-faad951b5cf3.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99891950-8cb17780-2c3d-11eb-800b-cd17662bd4a3.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/99892032-6f30dd80-2c3e-11eb-8dc6-d05aaa8be2a1.png)

**Comment by oluowoj** [comment]
![image](https://user-images.githubusercontent.com/43192745/100122740-bd64fd00-2e47-11eb-8d9c-2ef696059cf0.png)

![image](https://user-images.githubusercontent.com/43192745/100122877-edac9b80-2e47-11eb-9d97-452ab990f641.png)

![image](https://user-images.githubusercontent.com/43192745/100123145-32d0cd80-2e48-11eb-9dcb-c3b3586867b5.png)
