### ISSUE TITLE
Posible Two-Dimensional abreviation typo in GamePhysics IM:transMot table.

### ISSUE THREAD

**Issue by gabrielasd** [JacquesCarette/Drasil#2241]
@smiths 
The label on IM:transMot table (page 33 of GamePhysics_SRS.pdf) reads "Force on the translational motion of a set of 2d rigid bodies".
Should it say "2D" instead?

**Comment by smiths** [comment]
Thank you @gabrielasd.  This is indeed a typo.  I've fixed the typo and issued a pull request.  I believe this issue will automatically be closed when the pull request is accepted.
