### ISSUE TITLE
Fix sentences mising left margin in GamePhysics SRS pdf

### ISSUE THREAD

**Issue by gabrielasd** [JacquesCarette/Drasil#2242]
@smiths 
In the Goal Statements subsection (page 9) the last two sentences don't have left margin.

**Comment by smiths** [comment]
Thank you @gabrielasd . The issue with the wrapped text is also noted in #1877. A solution, using short mnemonics, instead of the full names, is given in #1539. When that issue is closed, it should fix this issue.
