### ISSUE TITLE
Text Wrap Issue in Software Requirements Specification for GlassBR

### ISSUE THREAD

**Issue by liziscool** [JacquesCarette/Drasil#2245]
In Software Requirements Specification for GlassBR (https://jacquescarette.github.io/Drasil/examples/GlassBR/srs/GlassBR_SRS.pdf) on page 10 under section 5.1.3 the text wraps to the next line incorrectly.

**Comment by smiths** [comment]
Thank you @liziscool.  This is a known issue, as documented elsewhere, but you are correct that the labels are too long and do not wrap properly.
