### ISSUE TITLE
Text Exceeds Margins in Software Requirements Specification for GlassBR 

### ISSUE THREAD

**Issue by liziscool** [JacquesCarette/Drasil#2246]
@smiths 
in Software Requirements Specification for GlassBR (https://jacquescarette.github.io/Drasil/examples/GlassBR/srs/GlassBR_SRS.pdf) on page 36 for section 8 Unlikely Changes the text exceeds the margins of the page on the left

**Comment by smiths** [comment]
Thank you @liziscool.
