### ISSUE TITLE
Graphs Exceed Margin in  Software Requirements Specification for GlassBR 

### ISSUE THREAD

**Issue by liziscool** [JacquesCarette/Drasil#2247]
@smiths 
In Software Requirements Specification for GlassBR (https://jacquescarette.github.io/Drasil/examples/GlassBR/srs/GlassBR_SRS.pdf) on page 37 in section 9 Traceability Matrices and Graphs the graphs exceed the right margin of the page.

**Comment by smiths** [comment]
Thank you @liziscool.  This issue is a known one.  Until it is fixed, we can use the html file.  :-)
