### ISSUE TITLE
CAS 741 --Fall 2020-- - Issue Creating Exercise (1) - Tiago

### ISSUE THREAD

**Issue by machadotiagom** [JacquesCarette/Drasil#2249]
Hello @smiths 

Just trying to create an issue as part of the first task for the CAS 741 - Fall 2020

I did just a first reading on the Projectile SRS document (https://jacquescarette.github.io/Drasil/examples/Projectile/srs/Projectile_SRS.html).

I didn't read it looking for any sort of issue on the document if there exists one, but instead, I tried to pay attention to its structure itself. Was that what was expected for this task besides starting getting familiarity with the GitHub itself?

Tiago.

**Comment by smiths** [comment]
@machadotiagom, I was hoping that you would look for actual issues with the Projectile example.  If not an issue, a question would be fine.  I haven't looked at it yet, but I see that you have created another issue.  I'll have a look at that.  :smile:
