### ISSUE TITLE
A small typo in 'DD:Torque' notes in Game Physics

### ISSUE THREAD

**Issue by shinsid** [JacquesCarette/Drasil#2252]
@smiths 

![image](https://user-images.githubusercontent.com/12082585/94317132-a2fbc980-ff53-11ea-8e69-bc8fdd55865c.png)

Remove the repeated word 'the' in Notes.

**Comment by smiths** [comment]
@shinsid, yes, this is a mistake.  @tingyuw, can you please fix this problem within Drasil.  This is a good exercise to help you learn the workflow of pushing changes to Drasil.  You can see how little work is needed by looking at this pull request:

https://github.com/JacquesCarette/Drasil/pull/2244

To find where to make the fix, I suggest that you search through the Drasil code for "the the".  :smile:

**Comment by JacquesCarette** [comment]
I think that @Ant13731 has fixed this already?

**Comment by Ant13731** [comment]
Yes, I think this one got fixed from when I went over the pendulum stuff
