### ISSUE TITLE
A minor rephrasing in 'DD:chaslesThm' -> Notes might help

### ISSUE THREAD

**Issue by shinsid** [JacquesCarette/Drasil#2253]
@smiths 

![image](https://user-images.githubusercontent.com/12082585/94317241-df2f2a00-ff53-11ea-8071-87e6f47da1d4.png)

Instead of - 
The linear velocity vB ................ and the displacement vector between the origin and point B uOB.

more clear - 
The linear velocity vB ................ and the displacement vector, uOB, between the origin and point B.

**Comment by smiths** [comment]
Yes @shinsid, your wording is clearer.  However, rather than  make the change now, we'll postpone it until Game physics is revised.
