### ISSUE TITLE
CAS 741 --Fall 2020-- - Test issue (1) - Salah Hessien

### ISSUE THREAD

**Issue by salahhessien** [JacquesCarette/Drasil#2254]
Hello @smiths

I have read the Module Interface Specification for Projectile (https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-example/Drasil/Projectile/MIS/Projectile_MIS.pdf) as part of the first test issue for the CAS741 - Fall 2020.

I read the document for knowledge-seeking about MIS structure itself, not looking for any code issue.

Salah.

**Comment by smiths** [comment]
@salahhessien, it is good that you had a look at the MIS, but you are getting ahead of things.  :smile: At this point, I'd rather you review the requirements specification (SRS).  You can find the SRS for all of the examples at:

https://jacquescarette.github.io/Drasil/

This isn't really an issue.  I was hoping you would look at the documentation and point out a problem, or ask a question.
