### ISSUE TITLE
Redundancy in wording in GamePhysics_SRS.pdf

### ISSUE THREAD

**Issue by andreamclemeno** [JacquesCarette/Drasil#2257]
@smiths 
In the [Game Physics Library ](https://jacquescarette.github.io/Drasil/examples/GamePhysics/srs/GamePhysics_SRS.pdf) case study, the writer uses "external" and "outside" to describe the user as seen in the screenshot below as well as under heading _3.1 System Context_ on page 7 of the Game Physics SRS document. I think it would be better to say one or the other. For example: "A circle represents an entity outside the software, the user in this case." or "A circle represents an external entity from the software, the user in this case. "

Screenshot:
![image](https://user-images.githubusercontent.com/70977402/93551676-797fe400-f93c-11ea-9ac9-93ae2dd9d948.png)

**Comment by smiths** [comment]
@andreamclemeno, I agree with your proposed improvement.  It is an incremental improvement, but your sentences are better than what is currently written.  Of the two options you listed, I prefer: "A circle represents an external entity from the software, the user in this case."

Although this is not a high priority, this is a good issue for a future improvement.  The same sentence exists in other Drasil examples, so this change should be made across all relevant examples.  This is actually a good test for Drasil.  The change should be easy.  If it isn't, then this will provide some valuable feedback on the design of Drasil.
