### ISSUE TITLE
Parameter missing in Eq. at GamePhysics_SRS.pdf (CAS 741 assignment) 

### ISSUE THREAD

**Issue by shmouses** [JacquesCarette/Drasil#2258]
parameter missing in equations: 
                                           TM:NewtonSecLawRotMot 
                                           DD:torque
@smiths

**Comment by shmouses** [comment]
@smiths 
Dear Dr. Smiths, I was wondering to follow up on this initial issue that I posted at beginning of the semester as you have not yet closed it.
Regards,
Shayan

**Comment by smiths** [comment]
Yes, that would make sense for the equation that uses torque to reference the data definition for torque.  I will add this to the list of issues to look at when revising game physics.
