### ISSUE TITLE
Inaccuracy in TM:UniversalGravLaw table at GamePhysics_SRS.pdf (CAS 741 Assignment)

### ISSUE THREAD

**Issue by shmouses** [JacquesCarette/Drasil#2259]
The right side and left side of the eq. in TM:UniversalGravLaw have similar values but not similar dimensions. Using "=" sign can be considered inaccurate. It is better to mention the absolute values are equal.

@smiths

**Comment by shmouses** [comment]
@smiths 
Dear Dr. Smiths, I was wondering to follow up on this initial issue that I posted at beginning of the semester as you have not yet closed it.
Regards,
Shayan

**Comment by smiths** [comment]
I'm not sure what the problem is with the equation for TM:UniversalGravLaw.  The unit vector is expanded to be the distance vector divided by the magnitude of the distance vector.  This substitution will still maintain the equality.
