### ISSUE TITLE
Question on requirements classification

### ISSUE THREAD

**Issue by muralidn** [JacquesCarette/Drasil#2261]
@smiths 
From my experience in the Avionics industry, requirements are divided into 3 categories, 

- High-Level System requirements
- High-Level Software requirements/Low-level System requirements
- Low-Level Software requirements.

I believe the Goals Specification is the High-Level System requirements in the SRS context, and the rest of the document to be High-Level Software requirements. Which would mean the Module architecture is the Low-Level Software requirements. Is this assumption correct?

Please share your thoughts on this.

**Comment by muralidn** [comment]
After writing the SRS for my problem statement, I understood that. 

Problem Definition & Instance Model = High level system requirements
Requirements section in SRS = Low-level system/High-level software requirements.
MG  & MIS = Low-level software requirements. 

Closing the issue.

**Comment by smiths** [comment]
@muralidn, I like your characterization of the documents and the relationship to the terminology from the avionics industry.  I'm not sure that low-level system requirements are given in the SRS.  The goal of the SRS is to be abstract, so low-level details shouldn't really enter, except maybe through system constraints.
