### ISSUE TITLE
Data naming in Projectile

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#2262]
@smiths  
In the section data definition, we are defining the initial velocity in x-component, would it be better if we name the data 'velIX' instead of 'speedIX' because it actually has a direction? And we also label it as velocity.

![image](https://user-images.githubusercontent.com/47548045/93598970-6f390680-f98b-11ea-9496-5846368e281c.png)

**Comment by smiths** [comment]
Yes, this is a good point.  The inconsistencies for the use of speed and velocity is also discussed in issue #2260 

I will close this issue, since #2260 covers the same ground.
