### ISSUE TITLE
Grammatical Mistake in GamePhysics_SRS.pdf

### ISSUE THREAD

**Issue by andreamclemeno** [JacquesCarette/Drasil#2263]
@smiths 
According to the SRS Checklist, grammar mistakes should not be present in the SRS document. Under the GD:accelGravity in _4.2.3 General Definitions_ of the [Game Physics](https://jacquescarette.github.io/Drasil/examples/GamePhysics/srs/GamePhysics_SRS.pdf) case study, there should be a comma between the two parts of the sentence (between "other" and "it is convenient").
 
"If one of the masses is much larger than the other, it is convenient to define a gravitational field around the larger mass as shown above."

Screenshot:
![image](https://user-images.githubusercontent.com/70977402/93553933-0d07e380-f942-11ea-8e98-3ba08afe67bb.png)

**Comment by smiths** [comment]
Yes, you are correct @andreamclemeno.  This typo should be corrected.  I will leave this issue open, and label it to show that it will be an easy issue to close.

**Comment by balacij** [comment]
@Ant13731 Did you mean to close this ticket with #2389 ?

**Comment by Ant13731** [comment]
Yes, this should be resolved now.
