### ISSUE TITLE
Data definition

### ISSUE THREAD

**Issue by JohnErnsthausen** [JacquesCarette/Drasil#2268]
# Define Data Definition question for @smiths

"What is the difference between a Goal Statement and a Data Definition" was suggested as an issue topic.  I've looked into the lecture notes from L01 to L04. I see examples for "Goal Statement" . I see references to the words "Data Definition". What is the definition of "Data Definition"? 

__I don't see where to label this issue as a question__

**Comment by smiths** [comment]
@JohnErnsthausen, you have probably figured this out by now, but a data definition is where details are provided on the variables and equations that support the theoretical models, general definitions (if present) and the instance model.  The data definitions are not derived or refined.  They are information that is available for the other models to use.  For instance, if you have an equation that is written in terms of density, you might then have a data definition that defines density.

I'm sorry that the question label wasn't available.  When I suggested that option, I forgot that only project collaborators have access to labels.
