### ISSUE TITLE
CAS741 - Missing Definition

### ISSUE THREAD

**Issue by moalaa** [JacquesCarette/Drasil#2270]
Hello Dr. @smiths,

I think the definition of **DblPendulum** is missing as the rest of the case studies in [Drasil](https://jacquescarette.github.io/Drasil/) Web page.

**Comment by oluowoj** [comment]
hello @maolaa, DblPendulum is an ongoing project in Drasil. It is still in progress.

**Comment by smiths** [comment]
Since @oluowoj has addressed this question, we can close it.  :smile:
