### ISSUE TITLE
NoPCM documentation align issue

### ISSUE THREAD

**Issue by salahhessien** [JacquesCarette/Drasil#2272]
@smiths 

Looking into "https://jacquescarette.github.io/Drasil/examples/NoPCM/srs/NoPCM_SRS.pdf" document, it was hard for me to understand traceability matrices in pages 28-30. The tables do not show the components of each column clearly. It needs to be aligned.

Salah.

**Comment by smiths** [comment]
Thank you @salahhessien.  Yes, the LaTeX traceability matrices are hard to read.  This is a known problem in the Drasil generation with LaTeX.  In the short term, the "fix" is to look at html version.  :smile:
