### ISSUE TITLE
Adding pendulum project in Drasil

### ISSUE THREAD

**Issue by oluowoj** [JacquesCarette/Drasil#2274]
@smiths, you can take a peek at the instructions, which is not yet done. But I anyone can get started with it as I continue to update.

 The 1st few sections and can be used to start building the SRS. Before a new user could get through those, I would have made more progress.
See https://github.com/JacquesCarette/Drasil/wiki/Creating-Your-Project-in-Drasil

I am having a build issue but the pendulum  project can be found in blankTmplt repo.

**Comment by smiths** [comment]
The instructions look great to this point @oluowoj.  They appear to be very thorough.  Of course, I can't really tell if something is missing, but that is the beauty of having 3 students working on the Drasil project in 741.  The students will go through the instructions and let us know what is missing or confusing.  We can address any problems as they point them out.

One thing that I'd like you to add is a pointer to the instructions on building a virtual machine (https://gitlab.cas.mcmaster.ca/smiths/cas741/-/tree/master/Tools/VM_Instructions).  The students do not need to do their project with a VM, but the instructions also discuss forking the Drasil repo and enabling continuous integration.

The manual SRS is due on October 8.  The students will start using your instructions after this point.

**Comment by oluowoj** [comment]
I will add the above into the wiki page. I am still adding more info to the wiki page to ensure they have instructions to build the entire SRS. And yes, I think as the students use it, we will improve as they go along. I'm pretty sure they would have questions and if we are missing answers on the wiki page, we will update.

**Comment by smiths** [comment]
Sounds good @oluowoj.

**Comment by smiths** [comment]
@oluowoj, I think we can close this issue.  Your instructions were successfully used for CAS 741.  I'm sure we'll make tweaks in the future, but they look pretty good for our starting point.  We'll also use these instructions with future summer students, so that is another chance to test them.
