### ISSUE TITLE
User guide suggestion - Concepts.hs

### ISSUE THREAD

**Issue by muralidn** [JacquesCarette/Drasil#2276]
@oluowoj  @smiths 

This is more of a suggestion than an issue. In the following step, I think it is also worthwhile to mention the module in which type CI is found, that is `Language.Drasil`. 

![image](https://user-images.githubusercontent.com/71282513/98671346-1e85ce80-237a-11eb-9517-acf7661d2416.png)

**Comment by oluowoj** [comment]
Great thanks. I will update.

**Comment by smiths** [comment]
Thank you @muralidn.

**Comment by Ant13731** [comment]
I think this can be closed now (`CI` now has a link to the Haddock documentation, which tells the user the module/package it is defined in)
