### ISSUE TITLE
Drasil User's Guide - 'run make' ?

### ISSUE THREAD

**Issue by muralidn** [JacquesCarette/Drasil#2277]
@oluowoj @smiths 

Step 2 here suggests executing `run make`. Isn't it just `make `? Neither bash nor cygwin has the `run `command.

![image](https://user-images.githubusercontent.com/71282513/98672172-63f6cb80-237b-11eb-821c-9dcc7ea5e172.png)

**Comment by oluowoj** [comment]
yes, that was a typo

**Comment by smiths** [comment]
Thank you @muralidn for catching the typo.  Once you've fixed the typo @oluowoj, please close this issue.

**Comment by oluowoj** [comment]
typo fixed in commit ID 4afaec9
