### ISSUE TITLE
Drasil User's guide - build folder

### ISSUE THREAD

**Issue by muralidn** [JacquesCarette/Drasil#2278]
@oluowoj @smiths 

Contrary to what is mentioned in step 3, a folder for my project was not automatically created in ./build. I had to edit the Make file to include my project in the example projects,

![image](https://user-images.githubusercontent.com/71282513/98673078-d3b98600-237c-11eb-9d0a-7d03310bde6f.png)

This is could be related to #2277.  Perhaps I am missing a make argument.

**Comment by oluowoj** [comment]
The Manual has been updated. Thanks for the feedback
