### ISSUE TITLE
Modify generated code to pass common linters

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2282]
Without too much work (I think), we could add an option to the generators to generate code that will pass common linters.  This would be something we could "brag" about.  The current generated Python code generates many warning when it is run through flake8.  The warnings that would be the hardest to deal with are those related to variable names.  Our code names are based on the symbols in our SRS.  This means that they will sometimes violate the Pep8 rules.  We could either follow the Pep8 rules, or generate a config file for flake8 that lists the "offending" names as exceptions to the usual rules.

**Comment by balacij** [comment]
Closing in favour of #1973, which would start the exploratory work to resolve this. We might also consider tracking this in a project however... Let's talk about this tomorrow too.
