### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2287]
As per Dr. Carette:

> Nice. Though we really ought to do a bigger move: to github actions. Travis is throttling its free accounts a lot.

_Originally posted by @JacquesCarette in https://github.com/JacquesCarette/Drasil/issues/2286#issuecomment-749144058_

**Comment by balacij** [comment]
Related ticket: #2231

**Comment by balacij** [comment]
For future reference, https://github.com/haskell/actions might be helpful for building this out.

**Comment by balacij** [comment]
If it's alright, I can give this a go @JacquesCarette ?

**Comment by JacquesCarette** [comment]
Yes please.

**Comment by balacij** [comment]
For the rest of this ticket, we need to create a new Drasil workflow script that activates when a PR is accepted into the `master` branch. When it's activated, it will update the `gh-pages` branch to update the Drasil website.

**Comment by balacij** [comment]
With PR #2461, we'll have deploying to `gh-pages`, but I'll still have left the the CI labels and `pr_label_update.py` script out of use. Looking at a few PRs, it seems like it adds `CI: *` labels to PRs. Do we still want to do this @JacquesCarette? With GitHub Actions, they don't appear directly on the PRs but they appear on PRs if you click on the "Details" of the various checks.

**Comment by JacquesCarette** [comment]
Can you give me more details? I'm not really understanding that last comment of yours (the whole thing), making it hard to answer the question.

**Comment by balacij** [comment]
Ah, yes.

I think the `pr_label_update.py` script attaches these
![image](https://user-images.githubusercontent.com/1627302/118319777-3ecd4c00-b4c9-11eb-8436-6efdc9ad9b9c.png)
on PRs.

I'm not quite sure I fully understand what the labels are for, nor why the labels only appear on some and not others. If they're only showing what steps did/didn't pass, then I think we can access it alternatively through the action run notes that appear on PRs
![image](https://user-images.githubusercontent.com/1627302/118320141-cf0b9100-b4c9-11eb-8263-aced1247868a.png)

**Comment by JacquesCarette** [comment]
Indeed, that's what that script does. And yes, the labels only get attached when the build fails for those reasons, i.e. show what steps did not pass.  `drasil-bot` then removes those labels when the build passes those parts again. It's a fun feature, but not crucial.

**Comment by balacij** [comment]
Ah, okay, that's interesting. We'll probably need to do some investigation to see if we can easily make it compatible with GitHub Actions. That sounds like a great feature to have!

**Comment by balacij** [comment]
Looks like the deployment worked!

https://jacquescarette.github.io/Drasil/

https://github.com/JacquesCarette/Drasil/actions/runs/851004315

We should leave this ticket open until we've completely ported the `pr_label_update.py` script too.

**Comment by balacij** [comment]
Closing in favour of #2836
