### ISSUE TITLE
Haddock docs missing for some files

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2294]
For example, `Language.Drasil.URI.AST` does appear not have haddock documentation built.

Related: https://github.com/JacquesCarette/Drasil/pull/2293#discussion_r573059414

**Comment by balacij** [comment]
@JacquesCarette It appears that Haddock ignores files that are not explicitly in the "exposed-modules" of the Cabal build files. But since all of the "exports" of a library are generally inside of the main "Drasil.hs" file of each library where all of the exports get threaded through, the documentation is still there but not divided into the individual files from which they originated. Were you wanting it to be divided in the haddock documents? For example, "InstanceModel" appears in Theory.Drasil https://jacquescarette.github.io/Drasil/docs/drasil-theory-0.1.0/Theory-Drasil.html#t:InstanceModel but actually comes from Theory.Drasil.InstanceModel.

**Comment by JacquesCarette** [comment]
Hmm, that's a bit of a pain.  We kind of need 2 sets of documentation then, one external and one internal. Or something like that. Can you investigate what the recommended way to deal with such a situation is?  I don't mean exactly the solution I outline, but the general problem of documenting things not in `exposed-modules`.

**Comment by balacij** [comment]
I'll take a look!
