### ISSUE TITLE
Backporting ModelKinds from branch QDef-in-InstMod

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2296]

**Comment by balacij** [comment]
@JacquesCarette Hi, I just want to double check before I continue making changes. Do we want to change the first parameter of the [InstanceModel smart constructors](https://github.com/balacij/Drasil/blob/8421bdbb86b82056abfa1dab8dc420e50da41c97/code/drasil-theory/Theory/Drasil/InstanceModel.hs#L78) from RelationConcept to ModelKind?

**Comment by JacquesCarette** [comment]
Yes. [And yes, checking such things is the right thing to do]
