### ISSUE TITLE
2 unused files in drasil-code

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2298]
* [Language.Drasil.Code.AST](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/Language/Drasil/Code/AST.hs) <- This file also appears to have an error, relying on "EqChunk" in Objective data
* [Language.Drasil.Code.Imperative.Parsers.ConfigParser](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs) <- Also appears to have an unused/broken import of "import Language.Drasil.Code.Imperative.GOOL.LanguageRenderer (Options(..))"

**Comment by JacquesCarette** [comment]
Right. 
- `AST` is a very-dead attempt at a very high-level specification language for modules. It can be deleted.
- `Imperative.Parsers.ConfigParser` is less dead. In theory it is to parse an external configuration file for the `Configuration` type. This one should be resurrected, if possible.

**Comment by balacij** [comment]
@Awurama-N Would you mind deleting the `drasil-code/Language.Drasil.Code.AST` file that Dr. Carette mentioned here above?

We can then move `Imperative.Parsers.ConfigParser` to a new issue.

**Comment by Awurama-N** [comment]
Okay, just saw this. I have deleted the file and made a PR.
