### ISSUE TITLE
Update GlassBR SRS Introduction

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#2299]
The GlassBR SRS introduction reads poorly, so it would be nice to clean it up to read like a proper introduction. It assumes the reader already knows what the system is supposed to do / why it is there.

**Comment by balacij** [comment]
@szymczdm @smiths Do you have any concrete suggestions for something we can change it to?

From the [current website](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html#Sec:Intro):

> Software is helpful to efficiently and correctly predict the blast risk involved with the glass slab. The blast under consideration is any kind of man-made explosion. The software, herein called GlassBR, aims to predict the blast risk involved with the glass slab using an intuitive interface.

One issue: we don't generate something with an intuitive interface.

Also, I just noticed we're missing tables for input and output variables. Should we add that in too while we're at it?

**Comment by smiths** [comment]
@balacij, yes it is getting past time that we should close this issue.  It would be nice if all of our introductions followed a similar pattern.  This would make it easier for us to generate introductions.

<Motivation> <Purpose> <Examples> <Program Name>

For instance, for GlassBr this could be:

"Explosions in downtown areas are dangerous from the blast itself and also potentially from the secondary effect of falling glass.  Therefore, software is needed to predict whether a glass slab can withstand a blast under given conditions.  For example, we might wish to know whether a pane of glass fails from a gas main explosion from a small fertilizer truck bomb.  The program documented here is called GlassBR."

I've followed the same pattern as the Projectile example.  I have a suspicion that we can redo all or most of our examples following this pattern.  The motivation is unique to the introduction, but the purpose statement should (if possible) come from the same purpose statement we use elsewhere.  Eventually, we should be able to connect the example to the scope.  For projectile, the scope puts bounds on the velocity, which is highlighted by examples of sports, as opposed to ballistics.  For GlassBR, the explosions are big, but not huge.  The example highlights this.  (I think; I'm not an expert.)  We should be able to end the first paragraph by introducing the name of the software.

We don't have to codify the pattern for the introductions now, but I'd like the revised introduction to GlassBR to be something like the example I gave above, to make it easier to follow a pattern in the future.

Yes, adding the tables for inputs and outputs makes sense.

**Comment by NoahCardoso** [comment]
In regards to adding an input and output table I thought that glassbr already has these.
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/3a3858f5-d329-409f-b23d-ffb6eedaa003)
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/bbe3e8aa-962e-40bc-a435-a0da98d0e28a)

**Comment by balacij** [comment]
Yep, looks like I overlooked them, thank you for looking into them @NoahCardoso !
