### ISSUE TITLE
InstanceModel Labeling convention

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2305]
I was just wondering if there is a general naming convention for the labels of the instance models.

For example, in the Projectile example, landPosIM and timeIM are called ("calOfLandingDist", "Calculation of Landing Position") and ("calOfLandingTime", "Calculation of Landing Time"), respectively but no others seem to have this explicit "Calculation of X" naming.

I'm currently trying to convert them into the EquationalModels (as per #2303) but just running into small conflicts with the "Calculation of" stuff so I am wondering if they are even appropriate (related commit https://github.com/balacij/Drasil/commit/1f42242e29a7e18fb0754e5b50aeb64ef344766d )

**Comment by smiths** [comment]
@balacij, no there is currently no explicit naming convention for the labels.

**Comment by balacij** [comment]
@smiths Thank you! 

Do you have any opinion on these specific examples mentioned where they are of the form "Calculation of X"? I think it would be sufficient to label them as just the "X" (but I might be misunderstanding).

**Comment by JacquesCarette** [comment]
We will want to label many of these "Calculation of X", because there is a difference between X as the concept that exists, and a method for computing X. For example, there is, conceptually, a single X, but there might be multiple ways of computing it.  So we do want to have different labels.

[If my answer above is sufficient, please close this issue.]

**Comment by smiths** [comment]
I agree with @JacquesCarette.  I like the implied idea that we should have a consistent naming convention for our labels.  I'm not sure what the convention should be.  I think we would need to look at the knowledge that is currently labelled and try to deduce the patterns.

**Comment by balacij** [comment]
Sounds good.  Thank you!

I'll close this issue.
