### ISSUE TITLE
Building projectile lesson in Drasil

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#2307]
Here’s an overview of building the projectile lesson in Drasil.

First of all, I am going to handle the contents (like figures, headers, equations, etc.) the way how the SRS does, since there isn't much difference between them. The thing here is to print them like the user builds the notebook manually on the Jupyter platform. There is still room for improvement in how Drasil prints the Jupyter notebook at this point.  

The core thing would be how to separate and add markdown and code cells when we want to. The current SRS examples in Jupyter are printed in one huge cell which made it hard to maintain and edit. Since we need to hard code the information (like cell type and metadata) that is needed to build a cell, my current thought is to make it like a function. We can call that function when we want to add a new cell. There might be two ways of doing it, one is that we could add the contents of that cell directly in the function or just make it like a notification to the Drasil saying that we want to separate this information with a new cell.

Another thing is how to divide the contents into different modules. SRS has its pattern and structure, which means we can build it in the same way. We kind of separate the modules by sections. But for the projectile lesson or future application of the Jupyter notebook, the structure of the document won’t be the same. Currently, I might build it in one module since it is more straightforward (just like building on the Jupyter platform). So it would be like calling functions, adding the contents and sections in one Haskell file. But I’ll see if there is other good ways to divide it into different modules like the current examples do as the implementing process goes.

More implementing details will be considered later. The first step is adding the information of the projectile lesson in Drasil, also seeing what’s the best way to add and separate new cells.

**Comment by smiths** [comment]
@tingyuw, as we discussed in our last meeting, please build on your plan by determining your sequence of changes, and providing details on those changes.  We discussed the following steps:

1. Generate the separate sections of the SRS for Projectile as separate markdown cells.
2. Generate a cell with the calculation code for Projectile.  To start with skip the input and output generation.  The calculations should be almost the same as what is currently generated.
3. Manually write the input cells in the generated markdown to figure out exactly what we need to generate for input.  The original program took the input from a file, but the way that makes sense for a Jupyter notebook is to have code that hard-codes in the inputs.  The user can then change the hard-coded values to experiment with the notebook.
4. Reproduce the manually created input cells, as automatically generated cells.

**Comment by JacquesCarette** [comment]
I would add the following information to the mix: we need to understand what a 'cell' is typically used for. We need to understand the level of granularity used in typical Jupyter notebooks. Then we need to map that to how we do Drasil documents. That might require that new information be available in Drasil to do an appropriate 'chunking'.

**Comment by tingyuw** [comment]
To separate the sections of the SRS, I'm going to do it like the wrapper in HTML. The information needed to build the cell would be added at the beginning and the end of each section. 

And for the Projectile motion example, the markdown cells can be done in the same way as long as we decide how to separate them. But where and how to separate the contents automatically in future applications is an issue to think about. Identifying the headers might be a way. 

After finishing separating the SRS sections, I will start adding the information (both markdown contents and code) of the projectile motion in Drasil and reproduce it in Drasil. As Dr. Smith mentioned, the code will be added manually at first. And then we could see how to improve the code and make it more automatic.
