### ISSUE TITLE
Reviewing the assumptions in Projectile

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2314]
[These are in the order in the document]

1. twoDMotion: The projectile motion is two-dimensional (2D).
2. cartSyst: A Cartesian coordinate system is used (from A: neglectCurv)
3. yAxisGravity: The direction of the y-axis is directed opposite to gravity. 
4. launchOrigin: The launcher is coincident with the origin. 
5. targetXAxis: The target lies on the x-axis (from A: neglectCurv).
6. posXDirection: The positive x-direction is from the launcher to the target.
7. constAccel: The acceleration is constant (from A: accelXZero, A: accelYGravity, A: neglectDrag, and A: freeFlight).
8. accelXZero: The acceleration in the x-direction is zero. 
9. accelYGravity: The acceleration in the y-direction is the acceleration due to gravity (from A: yAxisGravity). 
10. neglectDrag: Air drag is neglected. 
11. pointMass: The size and shape of the projectile are negligible, so that it can be modelled as a point mass. 
12. freeFlight: The flight is free; there are no collisions during the trajectory of the projectile.
13. neglectCurv: The distance is small enough that the curvature of the Earth can be neglected. 
14. timeStartZero: Time starts at zero. 
15. gravAccelValue: The acceleration due to gravity is assumed to have the value provided in Section: Values of Auxiliary Constants.

First, assumptions 1, 2, 10, 13 are **meta** assumptions: they are assumptions that are *prior* to the theoretical model, which already has these 'baked in'. In a sense, these assumptions are 'meaningless' because they assume that there is an even more general model (which is not documented here at all) for which these assumptions would make sense. Note that all these assumptions do make sense in the most general setting - but that setting is not presented here at all.

Likewise, 3 is somewhat meta as well. It pre-supposes an orientation for diagrams, as well as an orientation for gravity.

Assumption 4 is a perfectly good modeling assumption. Same with 6, 8, 9, 14, 15.

Assumption 5 does not in fact follow from assumption 13 - it follows from assumption 13 plus 12 (free flight), and that the terrain goes along the x-axis too.

Assumption 7 is not really an assumption - it is, as the comments say, a derived truth. In the context of the model, what could be instead said is that "gravity is the **only** force acting on the projectile in positive time".

Assumption 11: this is a classical way to phrase things, but is still odd. A better way to go about this would say: the size (in all dimensions) of the projectile is much less than the precision we will use for considering a 'collision', and so can be considered to be 0. Or something like that.

Assumption 12 is actually quite fascinating: in some ways, it is an assumption about the geometry of the situation as well as a a priori assumption on the shape of a trajectory!  If trajectories were, for example, sinuisoidal instead of parabolic, this assumption would have a completely different meaning.

<hr/>

In my mind, we should have a single meta-assumption: that our theoretical models are adequate. So meta-assumptions should simply be removed. If these assumptions really *are* assumptions, then the theoretical model should be one in which the assumptions apply.

**Comment by smiths** [comment]
After a long time, I'm finally getting back to this issue.  :smile:  I just noticed this issue again and the timing is perfect.  Independent of this issue I've been looking at a "refined theories" version of Projectile.  In the efforts to build the new version of the SRS for Projectile I rediscovered the observations made above by @JacquesCarette.  We took different paths to get there, but I take it as a good sign that there is significant convergence in our viewpoints.

To address the problems with assumptions in the new version of the [SRS for Projectile](https://github.com/smiths/caseStudies/blob/master/CaseStudies/projectile/projectileSRS_RefinedTheories/Projectile_SRS.pdf), I introduced different kinds of "assumptions", as follows:

- scope decisions
- modelling decisions
- background theory assumptions
- helper theory assumptions
- generic theory assumptions
- specific theory assumptions
- rationale assumptions

I've started writing up definitions of these different categories of "assumptions", but I don't want to invest too much time until I'm sure that this is going in the right direction.  :smile:  I'm hoping to have a meeting with the Drasil group to discuss this in the new year.  For now, I'll just assume that the names give enough of a hint on what each category of assumption/decision refers to.

The assumptions 1, 2, 10 and 13 were referred to as **meta** assumptions by @JacquesCarette.  This was true in the old SRS, but in the new one, the more general context is given.  For instance for assumption 1 (twoDMotion), the original theories are presented in 3D.  These theories are refined to 2D.  Assumption 2 (cartSyst) is now called a modelling decision, not an assumption.  Assumption 10 (neglectDrag) is now a rationale assumption.  There is a connection here to the scope decision (another addition to the new SRS) that forces are not included in the model.  The rationale for not including forces is that air drag can be neglected.  Assumption 13 also becomes part of the rationale.

Assumption 3 (yAxisGravity) is now considered to be a modelling decision.  All of the decisions related to the coordinate system relative to the objects are modelling decisions.

It would have been easier to follow the advice of @JacquesCarette and remove the meta-assumptions, but when I revised the projectile SRS I felt like they couldn't be ignored.  In projectile motion it is a big decision to neglect forces.  This "lie of omission" should be recorded somewhere.  These decisions are made at the scope level.

The revised version of Projectile is in reasonable shape now, except I haven't bothered to make sure all of the traceability information within the document is correct.  Once we teach it to Drasil this kind of information will be easy to update, but it is tedious for a person to do it.  I also haven't completed the rationale section.  A simple way to finish it would be to say that the meta-assumptions are just given, and they don't need to be justified.  In some cases this is true, like when the theory is used to teach projectile motion.  However, it will be interesting to see how we could do better with this.  We should be able to quantify what input constraints are required to safely neglect the Earth's curvature.

The revised version of Projectile revises the assumptions, so I'm going to close this issue as addressed.  The conversation can now move to fixing the new version of Projectile.
