### ISSUE TITLE
Make all cabal/package.yaml files precise about dependencies

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2321]
All the packages currently listed used to be used by the large monolithic Drasil, but now the sub-packages have inherited huge pseudo-dependencies that are not real. These should be trimmed down to what is actually needed.  Plus quite a bit of refactoring has been done, so that some dependencies might be completely obsolete too.

**Comment by balacij** [comment]
Sounds good. I will update this list as I go along submitting PRs where needed:

- [ ] - `drasil-build`
- [ ] - `drasil-code`
- [ ] - `drasil-data`
- [ ] - `drasil-database`
- [ ] - `drasil-docLang`
- [ ] - `drasil-example`
- [ ] - `drasil-gen`
- [ ] - `drasil-gool`
- [ ] - `drasil-lang`
- [ ] - `drasil-metadata`
- [ ] - `drasil-printers`
- [ ] - `drasil-theory`
- [ ] - `drasil-utils`

**Comment by JacquesCarette** [comment]
The package minimums were all set when we were using straight cabal and not stack. So this is a holdover. I'm fine with removing them in favour of a minimum Stackage level.

**Comment by balacij** [comment]
I think we can close this ticket now that we've gone through all the packages (excluding the website, which was done separately in another ticket).
