### ISSUE TITLE
Removing inferName

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#233]
As mentioned in the comment of commit ccb55f3, inferName should be removed and replaced with a more semantic based approach.

Calls to `inferName` exist in:

- Language.Drasil.**Document**.hs has **4** matches
- Language.Drasil.**RefHelpers**.hs is where it's **defined**

**Comment by hmadej** [comment]
Language.Drasil.Document.hs:
- line 79 `refName (Section t _) = S "Sec:" :+: inferName t`
- line 83 `refName (Table _ _ l _)     = S "Table:" :+: inferName l`
- line 84 `refName (Figure l _)        = S "Figure:" :+: inferName l`
- line 93 `refName (Graph _ _ _ l)     = S "Figure:" :+: inferName l`

Language.Drasil.RefHelpers.hs:
- line 9 `inferName :: Sentence -> Sentence`
- line 10 `inferName (s1 :+: s2) = inferName s1 :+: inferName s2`
- line 11 `inferName (S s1)      = S $ intercalate ("") (firstFourLetters s1)`
- line 12 `inferName (F _ s)     = S [s]`
- line 13 `inferName (Ref _ _)   = EmptyS`
- line 15 `inferName _           = EmptyS -- Was Empty.`

**Comment by JacquesCarette** [comment]
If documents were somehow more self-describing, then we could derive names from these 'semantic' pieces.  The code above seems too ad-hoc and fragile.

**Comment by niazim3** [comment]
Stems from issue #35.

**Comment by szymczdm** [comment]
Removed as of commit a51a739315345f07a0a017cf
