### ISSUE TITLE
Move 2 references out of PDController/References

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2342]
`laplaceWiki` and `pidWiki` should be moved into Data.Drasil (see #2324) for a similar issue).

**Comment by Awurama-N** [comment]
after taking out the two references, there are warnings that "The type signature for ‘pidWiki’ lacks an accompanying binding", same for laplacewiki, would you like me to take it out of the citation as well.

**Comment by JacquesCarette** [comment]
The declarations of those two signatures should be moved along with the code. They belong together.  Did you just move ½ ?

**Comment by Awurama-N** [comment]
oh okay... 
Yes at first i just took out the references themselves and nothing else

**Comment by JacquesCarette** [comment]
If they are for something quite generic, yes. But not necessarily for everything - there's still a judgement call to make.
