### ISSUE TITLE
Instance Model Not Referenced in Organization Section Now

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/Drasil#235]
As of f02ae02760b5b68c623ef532e93840f29d0dd339 the Instance Model section is being automatically generated through `solChSpecF `but `orgSec` function needs the Instance Model as an input to create a reference to it. I don't think this can be solved until all the sections are automatically generated together to we can pass in this argument internally. For now, I have given the Solution Characteristics Specification as the variable to Organization.

**Comment by danscime** [comment]
Characteristics of Intended Reader is not able to reference user characteristics as well.

**Comment by njericha** [comment]
Found a solution-ish? 577d532139d66af294c5cf463e59d1ae1bc191f8 
I created a dummy section to pass as the input.

**Comment by JacquesCarette** [comment]
Ish.  I would prefer `Paragraph (S "(missing)")` rather than `EmptyS`.  Should probably make that `(missing)` be defined as a documentation concept, so that we can change what it says in one centralized place.

**Comment by njericha** [comment]
I can pass `(SRS.userChar [Paragraph $ S "..."] [])` to reference.

**Comment by JacquesCarette** [comment]
Good.  And just make that sentence be a documentation concept.  You can call it 'missing'.

**Comment by njericha** [comment]
db5409eab86bf8c44d4aa618277f66b96c763de9 done.

**Comment by njericha** [comment]
Just making a note that #28 used a "solution" to make separate files and then the particular theoretical model can be referenced if needed

**Comment by samm82** [comment]
@JacquesCarette as in #28, it looks like we now have this infrastructure.

**Comment by JacquesCarette** [comment]
Correct. I think it would make sense for @szymczdm to give it a whirl, as a test of the new infrastructure.

**Comment by szymczdm** [comment]
Just went to test this out and it looks like @niazim3 beat me to the punch (it's tested and working on NoPCM). I believe now it's just a case of updating the rest of the examples where necessary. For example, GlassBR apparently does not require a reference to the instance models section, though I believe that may be an oversight as we've updated the manual versions to include at least one instance model. @smiths can you confirm whether there should be a reference there or not?

**Comment by JacquesCarette** [comment]
Not quite. I was looking at issue #981 and it is 'stuck' on referencing the instance models section -- which is currently done as a hack. It relies on a `Label` having a `Referable` and a `HasLabel` instance, which is just plain wrong [and the code correctly says so].

So I would not consider this 'done' at all.

**Comment by szymczdm** [comment]
Okay, I'm a bit lost. #971 requires a bit of design to fix label-creation and referencing, and #981 depends on that, but at this point in time, this specific issue (creating a reference to the instance models section) is working through the use of our labels.

Are you saying `Label` should not be an instance of `HasLabel`, or `Label` should not be an instance of `Referable`, or that we need to wait on #981 (for `HasLabel` to be a constraint on things that are `Referable`) before we can consider this issue closed properly?

**Comment by JacquesCarette** [comment]
I am definitely saying that `Label` should not be an instance of `HasLabel`. It is also weird to make `Label` an instance of `Referable`: a `Label` is a mechanism by which you refer to something (like an equation, a section, etc). You could actually refer to a label (via another label!), but that is not likely to be a very useful feature.

So I am saying that the current issue is not fixed at all, because its implementation turns out to rely on a bunch of mis-features / hacks that all need to be fixed.

I noticed this problem while I was trying to fix #981.

**Comment by balacij** [comment]
The instance models section is now linked to from the Oganization section now. For example, [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html#Sec:DocOrg).
