### ISSUE TITLE
Explicit imports of Applicative, <$>, & Monad can be removed

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2355]
`Applicative`, <$>, & `Monad` have been in `base/Prelude` for all versions of GHC 8.* so I think we can comfortably remove their explicit imports without causing any incompatibility issues for 8.*+.

[As early as GHC 8.0.1's `base/Prelude` had Applicative and Monad](https://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#t:Applicative)
[Directory of GHC versions to base versions](https://wiki.haskell.org/Base_package)

**Comment by balacij** [comment]
@Ant13731 Hi Anthony, would you mind having a look at this ticket?

**Comment by Ant13731** [comment]
@balacij Sure!

**Comment by Ant13731** [comment]
Heyo, should I just remove any `import Data.Monoid`, `import Control.Monad`, and `import Control.Applicative` lines I find? @balacij

**Comment by balacij** [comment]
I'm not too sure about Data.Monoid, I don't think it's something we should be removing in this ticket. For the rest however, when you run `make clean` followed by a fresh `make`, the console will give you hints (highlighted in purple) about redundant imports. I think for some lines, they import things that aren't already in Prelude (in which case, you'll need to just remove the ones that are already in Prelude), and some lines are just not really necessary because they only import a single thing which is already in Prelude.

**Comment by Ant13731** [comment]
Ah okay thanks!
