### ISSUE TITLE
Receiving an error at stack exec part of the build

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2357]
@JacquesCarette @smiths, after working on issue #2347, I keep on receiving this error when running `make`. I'm not really sure what is wrong though. 
```diff --strip-trailing-cr -r -X ../.gitignore -x '*.txt' "stable/dblpendulum/" "build/DblPendulum"/ > "logs/DblPendulum_log.log" 2>&1
make: [Makefile:148: dblpendulum_diff] Error 1 (ignored)
cd "build/PDController" && stack exec -- "pdController" 
pdController.EXE: SRS/PDController_SRS.tex: commitBuffer: invalid argument (invalid character)
make: *** [Makefile:142: pdController_gen] Error 1```

**Comment by balacij** [comment]
Just out of curiosity, are you on Windows? If so, did you run `chcp.com 65001` when opening up  your Git Bash terminal?

From a quick google search, it looks like this is a utf8 encoding issue, and it seems that pdController is the only example that, in it's main function, doesn't immediately set the locale to utf8.

**Comment by Ant13731** [comment]
Ahhh my bad, I completely forgot. Thanks for your help!

**Comment by balacij** [comment]
No problem. I'm glad this worked out!
