### ISSUE TITLE
GitHub Actions "build on push" seems to occur too often

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2359]
It seems to cause issues in PRs where it requires a build being done twice for the same PR, and, optionally, commit on said PR. For example, at time of writing this issue, #2358 has 2 identical actions being run.

Is it alright if we remove it @JacquesCarette ?

(I created a PR if this is alright, so we can quickly get this ticket completed)

**Comment by JacquesCarette** [comment]
Build only after a PR has been reviewed is enough, I agree. But there also ought to be a way to trigger a build - I've seen others do this by having a keyword in the commit like [trigger-build] or something.

**Comment by balacij** [comment]
I believe that it would also be building with each commit pushed to the source branch of any/all open PR.

I've never seen a manual trigger done like that before, do you happen to have any examples? Looking at [github docs](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow), it seems we can add a manual button at least.

**Comment by JacquesCarette** [comment]
I think the main Agda repo has this. [It also has the opposite, a keyword to stop a build from happening]
