### ISSUE TITLE
Inserting a code snippet 

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2362]
I lined up the code for my assigned issue a while ago but i'm having a little trouble figuring out how to insert a snippet of code into my reply. could you please walk me through it.

**Comment by smiths** [comment]
@Awurama-N, if you want to write code in the text,  you can use the tick symbol (`) around the code: `code`.

For a longer block of code, you use three ticks (```), like this:

```
putting
the code
here
```

**Comment by Ant13731** [comment]
Just for extra clarification since I initially thought it was an apostrophe, the symbol is to the left of the 1 key and above the TAB key.

**Comment by Awurama-N** [comment]
Okay thank you!

**Comment by balacij** [comment]
@Ant13731 Yes, that's the backtick key on most full-size standard keyboards. Additionally, it's on the same key as tilde (~).

**Comment by Awurama-N** [comment]
thank you
