### ISSUE TITLE
QDef-in-InstMod branch

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2364]
Can it be deleted now? I think all of the information from it has been mined?

I know that not everything related to it has not been fixed, but that's not the same. If the branch will never be looked at, it should be deleted. [If it can be, go ahead and do it.]

**Comment by balacij** [comment]
Just quickly going through older tickets, I see #1373 gives a nice overview (thank you Mornix) of the changes. From comments + what we did, it seems 1-3 and 5 are good for now. Regarding point 4, it seems out of date and partially changed, but I should ask if you want anything from the existing branch first before deleting.

 ( We can also probably close #1373 with this ticket too. )

**Comment by JacquesCarette** [comment]
Thanks for finding that issue. I'm going to want to examine all the points it mentions carefully, to make sure they are indeed "good for now". Whatever might be missing, I'll make specific new issues. I'll try to get to that soon.

**Comment by JacquesCarette** [comment]
So `relToQD` still exists in `drasil-code`. That's a strong symptom that item 1 is not done. I don't want to make an issue for just that, as it's going to depend on too many other things.

**Comment by JacquesCarette** [comment]
I've deleted it, as it's been wrung dry of useful information.

**Comment by balacij** [comment]
Sorry, I was going to comment on this yesterday, but I was a bit slow. I just created 1 more PR for it -- #2596 .

Also, it looks like the branch is no longer listed, but the commits are still accessible, so I guess we never actually lose any data?

**Comment by JacquesCarette** [comment]
I deleted the branch. I think that if we do a deep enough 'garbage collect', the data might disappear too, I'm not sure. At least, any commit that is no longer referenced, would probably go away. I don't know if issues are considered roots when doing gc.
