### ISSUE TITLE
Adding manual Github Actions workflow triggers

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2366]
Following the example Dr. Carette found in Agda, we should create our own manual triggers via the actions tab, or through adding `[workflow-trigger]` to commit messages (and of course, we can change this trigger).

**Comment by smiths** [comment]
Sounds good @balacij.  If we "pull the trigger" on `workflow-trigger`, we should be sure to document this in the Contributor's Guide.

**Comment by balacij** [comment]
Ah, good point! I'll make sure to do that once #2367 is merged in. Thank you!
