### ISSUE TITLE
Importing Stack & VSCode Installation Docs from CS3FP3

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2375]
For CS3FP3 tutorials, I created some basic usage and installation docs that I think we could import into our Contributer's Guide (maybe Quick Start too?) and modify to include more Drasil-related information + Makefile information.

https://gitlab.cas.mcmaster.ca/carette/3fp3-w2021/-/blob/master/Tutorials/01/Tutorial_01_Installing_Stack_and_VSCode.md

**Comment by smiths** [comment]
@balacij, I think this is a great idea.  I looked over your instructions and they look really helpful.  Probably we want this content in its own wiki page that we can then link to at the appropriate place in the other documentation.

**Comment by balacij** [comment]
Thank you! I'll make it into a new Wiki page. I was also thinking of adding some basic things that we can later grow for LaTeX and Git Bash.

**Comment by balacij** [comment]
I started this on https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup

We can continue to grow it slowly. If anyone has any suggestions that can go in it, please feel free to contribute to it!

**Comment by smiths** [comment]
I've read over your instructions @balacij.  They look great!  This will be a very valuable resource for new Drasil developers, especially those with less coding experience.

The only thing I worry about is maintenance.  There are a couple of references to specific version of GHC and Stack.  I wonder if in the second reference to the Stack version (under the Pinning your Stack Version heading), we should replace the number with `<our current version of Stack>`, or something similar?

For keeping the other reference to GHC and Stack current, is there a spot in our Stack set-up where we can put a comment to remind whoever changes the numbers in the future that they should also update the installation documentation?

**Comment by balacij** [comment]
Thank you @smiths :smile: I hope it will be helpful!

That's a good point about the maintenance of versioning. There's also a few subtle versioning things like the version of the compilers required for running the various generated artifacts. Yep, we can do that. Would it be good to have a single Wiki page as well for carrying just information about the compiler versions we use + environment version? I don't know if that would be too much work though.

**Comment by smiths** [comment]
@balacij, my instinct is to not have a wiki with the compiler versions + environment versions.  That would be just one more place to maintain when a change needs to be made.  Whoever maintains the build system in the future should be able to find this information from the source files.  I'm assuming that it is reasonably easy information to find in our build scripts for someone that knows what they are doing.  If that is not the case, then I change my opinion about putting all of the information in one place.  :smile:

**Comment by balacij** [comment]
Sounds good. It's pretty obvious from the artifact files for the compiler versions, the environment versions would be in the main stack.yaml, so it should be fine. Thank you!

**Comment by balacij** [comment]
The scope of this ticket was started with the creation of the [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) page. Now that it's been reviewed, I think we can close this ticket and progressively work on it as we see fit.

**Comment by smiths** [comment]
Agreed.
