### ISSUE TITLE
Adjust .gitattributes again

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2378]
Our repo has now been classified as 77% C++ by linguist. This is because there are some sources from imported libraries that are huge, and that's what it is detecting. The `.gitattributes` file had been adjusted to deal with that, but this seems to have bit-rotted.

Could one of you investigate and fix please?

**Comment by balacij** [comment]
It looks like the .gitattributes file isn't actually being respected at all right now. I'm not _yet_ 100% sure why, but I suspect it's breaking down completely when it sees the `language-generated=true` line item (which I don't think is valid according to https://github.com/github/linguist/blob/master/docs/overrides.md ).

**Comment by Ant13731** [comment]
Do we want the `stable` code to be included? Could we use `liguist-detectable`?

**Comment by balacij** [comment]
It looks like the current gitattributes file isn't respected at all. Making some changes on my repo...

![image](https://user-images.githubusercontent.com/1627302/117340438-de0d9600-ae6e-11eb-9820-72c4b153cfaf.png)

By changing the `*`'s into `**`'s and removing the `=true` after `language-generated`, we get the above stats on my fork with the same configuration file: https://github.com/balacij/Drasil 

Any thoughts on this?

**Comment by JacquesCarette** [comment]
That's already much better.  

After much thinking, I don't want `stable` included: it's all generated stuff. I don't want to count that in our code repo.

**Comment by smiths** [comment]
I agree that we don't want to count `stable` in the language summary statistics.
