### ISSUE TITLE
Repeated words in DblPendulum

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2398]
Consider the following short bit of code in Unitals.hs:
https://github.com/JacquesCarette/Drasil/blob/dc6da83d0ddf6c04c98bc1fdb0f43f8a8f9c1a57/code/drasil-example/Drasil/DblPendulum/Unitals.hs#L47-L57
We see the English word "rod", which is an important concept in this example, typed out multiple times. This should not happen. This word corresponds to a concept, and should be obtained from that concept.

This issue should result in two actions:
- [x] fixing things about 'rod'
- [x] creation of an issue about all such repeated English. The issue should be a list of things to consider for abstraction from DblPendulum.

**Comment by Ant13731** [comment]
For the first part of this issue, should `rod` then become an explicit `NP` that then takes the `phraseNP` function to convert it to a `Sentence`? Or is there a better data type that can be used to carry more detail about the rod itself? If `rod` works as an `NP`, should the definition be under `Unitals.hs`?

**Comment by JacquesCarette** [comment]
`rod` should probably be an explicit concept, that will contain a noun-phrase, that will need `phrase` to get a `Sentence` out.

**Comment by JacquesCarette** [comment]
Yes, it's a similar problem. Take a look at other examples, to see where `NamedChunk` ends up being stored. Or at `Projectile` to see how it handles similar concepts.
