### ISSUE TITLE
CompoundPhrase Use in Concepts.Physics

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2404]
As I was working through the DblPendulum example, I found this:
![image](https://user-images.githubusercontent.com/69334555/117669859-59c05900-b175-11eb-847e-34135a2a6e66.png)
In the grand scheme of things, this is not that important, but I think the use of `compoundPhrase'` instead of `compoundPhrase` in the definition of `angAccel` in `Data.Drasil.Concepts.Physics` is causing the second word to be capitalized in the `dblpendulum` file. However, I am not sure if other files are relying on the capitalization of `compoundPhrase'` to work correctly. Here is the definition:
```Haskell
angAccel = dcc "angularAcceleration" (compoundPhrase' (angular ^. term) (acceleration ^. term))
  "the rate of change of angular velocity"
```
Would this be good for me to look into (once the other issues for dblpendulum are done)?

**Comment by smiths** [comment]
Yes, @Ant13731 this sounds like a good thing to look into.  I wonder if it would be helpful to do a brief write-up to distinguish all of the combinators for phrases.  @JacquesCarette might know of an existing summary, maybe through the haddock documentation, but I know that I still find it confusing every time it comes up.  :smile:  I don't really have confidence that we've used the combinators consistently in the different examples.  That seems like a good avenue for exploration to me.

**Comment by Ant13731** [comment]
Alright, thanks! I feel that even having all the combinator definitions in one spot could be helpful too. The Haddock documentation works well enough most of the time, but I have a bit of trouble trying to jump into the different constructor types (for concepts and sentences). For example, I really only found the `ofThe` constructor because of the duplicate "the"s in `dblpendulum`. Maybe even having a Drasil generated documentation of its language could help us incorporate it more reliably and improve generalization. This could be a decent continuation of issue #2399 as well.

**Comment by smiths** [comment]
Yes, having Drasil information in Drasil is our eventual goal.  We would like Drasil to generate its own documentation.  :smile:

**Comment by Ant13731** [comment]
For now, would it be a good idea to start a manual Latex document/glossary for the different combinators? Or would I be able to use the template files to make the documents within Drasil?

**Comment by JacquesCarette** [comment]
I think it would be worthwhile to try to following:
1. augment the current Haskell sources with good Haddock comments, so that Drasil's own documentation has good descriptions of its own combinators
2. make some kind of hand-written HTML meta-document that points to the generated docs as a kind of roadmap.

Doing it this way "by hand" may give us some insights as to how we'd want such things documented, as a prelude to seeing if it can be done in Drasil itself.

**Comment by smiths** [comment]
I like your proposal @JacquesCarette.  It is too soon for full automation, but doing the whole thing manually would be a maintenance problem.  This is a good practical compromise.

**Comment by Ant13731** [comment]
Since this issue has been separated into #2477 and #2481, I think this is okay to be closed
