### ISSUE TITLE
Error from using xPos and yPos in DblPendulum

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2411]
```cd "build/DblPendulum" && stack exec -- "dblpendulum" 
dblpendulum.EXE: Symbol: yPos not found in SymbolMap
CallStack (from HasCallStack):
  error, called at ./Database\Drasil\ChunkDB.hs:81:24 in drasil-database-0.1.1.0-1H2SDTZem9VDdavf3C6Z5k:Database.Drasil.ChunkDB
make: *** [Makefile:142: dblpendulum_gen] Error 1
```
When trying to use the `xPos` or `yPos` symbols in `dblpendulum`, I received the above error. However, switching those out with `ixPos` and `iyPos` seems to make the error go away.

**Comment by balacij** [comment]
Would adding `xPos` and `yPos` to the Unitals/unitalChunks list resolve this?

Disclaimer: I'm not entirely sure if this what _should_ be done. We'd likely need Dr. Carette or Dr. Smith to discuss if these should be added or not.

**Comment by Ant13731** [comment]
That worked! Thanks
