### ISSUE TITLE
Potential Abstraction of Words in Pendulum

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2424]
Referring to second part of #2398. I'm not sure if these all are good candidates for use in functions, but here is a general list I found @JacquesCarette. I didn't find very many nouns like `rod` that could be replaced with functions.

Because these words have some conceptual/mathematical meaning and are often seen in physics problems, these could even be generally defined as a `CI` or a `ConceptChunk`:
horizontal
vertical
component
arc length
motion

Zooming in on the pendulum example, these could be defined:
amplitude
simple harmonic motion

Other phrases that I think already exist but are still not being used fully in `dblpendulum`:
newton's second law of rotation
length
mass
angle

Some other words that I felt were not as important but could still be used:
origin
direction
positive
point

For common English phrases I found:
denotes the
with respect to
defined as

There were also quite a few linking words, but it'll probably do more harm than good to change those. Edit: I found a whole list of where those words are already defined, so as a note for me it is under `drasil-utils/Utils/Drasil/Misc.hs`. I might try incorporating these as well.

**Comment by Ant13731** [comment]
@JacquesCarette should the `denotes`, `wrt`, and `defnAs `combinators be Sentence-level or Concepts-level? I think that they are more English-based words rather than concept combinators but there's a case to be made about their conceptual and relational side. On this topic, should they have a type of `Sentence -> Sentence -> Sentence` or `(NamedIdea a, NamedIdea b) => a -> b -> someOtherType`? I feel like the first one would be more useful in `drasil-examples` but I'm not completely sure.

**Comment by JacquesCarette** [comment]
Let's start with Sentence level. I do think that, in time, these will acquire meaning, but we're not there yet.
