### ISSUE TITLE
Converting "Newton's law of universal gravitation" Theory Model

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2436]
Related to #2371 

While converting the following TheoryModel into "not an OthModel":

https://github.com/JacquesCarette/Drasil/blob/acf6d8dbd9632e14954e8e5027768edfd8ceb7d8/code/drasil-example/Drasil/GamePhysics/TMods.hs#L45-L60

and in the context of https://github.com/JacquesCarette/Drasil/pull/2426#issuecomment-838992397 , it seems inappropriate to naively convert the following TheoryModel into an EquationalModel because it contains 2 expressions for which it can use to calculate the `force`. However, if I'm not mistaken, if we want an EquationalModel to mean "something is calculated by this 1 formula", then I think we need to create a new kind of ModelKind to accommodate this.

Assuming I'm correct, would we potentially want some sort of "AnyEquationModel" (weird name, but we can probably figure something out that's better) that contains a list of QDefinitions, for which any can be used to calculate the thing in question?

**EDIT**: Alternatively, we could even just make "EquationalModels" just allow for this list of QDefinitions describe above, and create a smart constructor for all the existing models that currently have just 1 single related QDefinition.

**Comment by balacij** [comment]
I believe this is also related to discussion on https://github.com/JacquesCarette/Drasil/issues/1601

**Comment by JacquesCarette** [comment]
I agree with the reasoning.

We could indeed use an `NEList` of expressions (for the right hand sides) in `EquationalModels` to collapse the two together. But, let's not do that now. Using something from a list requires a choice, but in the 1 case, there is none - and from a design perspective, that's quite different.

I'm thinking `EquationalRealm`. We use `Realm` in a paper to mean a theory with multiple interfaces.  Let's start with that?

**Comment by balacij** [comment]
That sounds good to me. I'll try to get that going in a new issue/ticket.
