### ISSUE TITLE
Trouble Getting Latex to Compile

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2437]
I downloaded Miktex and tried copying and pasting the `stable` files into TeXworks. I have also set the package manager to automatically download any necessary packages. However, I get the following error:
```
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "LatinModernMath" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.

! Package fontspec Error: The font "LatinModernMath" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.20 \newcommand
              {\gt}{\ensuremath >}
? 
```

**Comment by smiths** [comment]
Hi @Ant13731.  I tried googling your error message, but no obvious hits came up.  One thing that does strike me as odd is that you mentioned copying and pasting files from stable.   You shouldn't have to copy and paste anything.  You should just open the tex file that already exists in stable and compile it.  There is a makefile in the folders with tex files in stable.  What happens when you run the make file?

**Comment by balacij** [comment]
I'm really surprised your MikTeX installation didn't automatically download and install the necessary packages.

When I run `make tex` on my VM just now, it automatically installs (with a few Window pop ups asking me for confirmation) packages:
![image](https://user-images.githubusercontent.com/1627302/117987908-e94a4100-b308-11eb-97dc-edc56b72ef2f.png)

(in particular, the `unicode-math` & [`lm-math` Latin Modern](https://ctan.org/pkg/lm-math?lang=en) packages are on the list that it downloads automatically)

Can you please try:
1. Open your MikTeX console
2. Manually check for updates
3. Update all necessary packages
4. Go to the "Packages" tab
5. Search for "lm-" and an `lm-math` item should pop up
6. Install `lm-math`
7. Close all open `git bash` terminals you have, and re-open them
8. `cd Drasil/code`
9. `make tex`

**Comment by Ant13731** [comment]
I downloaded the lm-math manually and it worked! Thanks! And thanks for the command too 😄

**Comment by balacij** [comment]
Nice! I'm glad you got it working now.

Perhaps we can try to add this into #2375 when I make the new wiki page for it, and link back from the [current LaTeX guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#latex) we have.
