### ISSUE TITLE
Some Concept Combinator Function Definitions Weird

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2441]
While I was looking through `Utils.Drasil`, I found that `andRT` uses a plural case for the second `NamedIdea` parameter when it should be singular. Also, according to the definition of `nounPhrase''`, the plural case for this is only taking singular phrases:
```Haskell
-- | Customizable `and_` combinator (takes two title case capitalization rules)
andRT :: (NamedIdea c, NamedIdea d) => 
  (c -> Sentence) -> (d -> Sentence) -> c -> d -> NP
andRT f1 f2 t1 t2 = nounPhrase''
  (phrase t1 `sAnd` plural t2) --here should be singular but uses plural
  (phrase t1 `sAnd` phrase t2) --and here should be plural but uses singular
  (Replace (atStart t1 `sAnd` phrase t2))
  (Replace (f1 t1 `sAnd` f2 t2))
```
I investigated a little more and found that switching those two around did not seem to break anything:
```Haskell
-- | Customizable `and_` combinator (takes two title case capitalization rules)
andRT :: (NamedIdea c, NamedIdea d) => 
  (c -> Sentence) -> (d -> Sentence) -> c -> d -> NP
andRT f1 f2 t1 t2 = nounPhrase''
  (phrase t1 `sAnd` phrase t2) --swapped
  (phrase t1 `sAnd` plural t2) --swapped
  (Replace (atStart t1 `sAnd` phrase t2))
  (Replace (f1 t1 `sAnd` f2 t2))
```
Should I leave it as the first way or change it to the second. I doubt `andRT` is using those cases of `NP` anyway, but it might've broken something not related to the documentation.

**Comment by Ant13731** [comment]
In addition, the type signature of `for` is:
```Haskell
for :: (NamedIdea c, NamedIdea d) => c -> d -> Sentence
```
but it may be better if it is changed to:
```Haskell
for :: (NamedIdea c, NamedIdea d) => c -> d -> NP
```
in order to match the rest of the functions listed in `Phrase.hs`

**Comment by Ant13731** [comment]
`compoundNC'` and `compountNCPlPl` are pretty much the same thing, but with a slightly more constrained type:
```Haskell
compoundNC' :: (NamedIdea a, NamedIdea b) => a -> b -> NamedChunk
compoundNC' t1 t2 = nc
  (t1 ^. uid ++ t2 ^. uid) (compoundPhrase'' D.pluralNP D.pluralNP (t1 ^. term) (t2 ^. term))

--Helper for compoundNCPlPl
compoundNC'' :: (NamedIdea a, NamedIdea b) => 
  (NP -> Sentence) -> (NP -> Sentence) -> a -> b -> NamedChunk
compoundNC'' f1 f2 t1 t2 = nc
  (t1 ^. uid ++ t2 ^. uid) (compoundPhrase'' f1 f2 (t1 ^. term) (t2 ^. term))

compoundNCPlPl :: NamedChunk -> NamedChunk -> NamedChunk
compoundNCPlPl = compoundNC'' D.pluralNP D.pluralNP
```
Should I change/remove one of these?

**Comment by JacquesCarette** [comment]
Go ahead and change the `andRT` are you describe. Same with `for`.  Go ahead and remove `compoundNCPlPl` in favour for `compoundNC'`.
