### ISSUE TITLE
`DD: angFrequency` & general DataDefn questions

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2451]
Considering [DblPendulum's DD: angFrequencyDD](https://jacquescarette.github.io/Drasil/examples/DblPendulum/srs/DblPendulum_SRS.html#DD:angFrequencyDD), it appears that the DataDefinition's QDefinition is currently an equation with a small derivation that just changes the way it's actual formula is rendered:

https://github.com/JacquesCarette/Drasil/blob/6dfdf9e54dc090210e0421e524d1bd36d7022cbd/code/drasil-example/Drasil/DblPendulum/DataDefs.hs#L71-L82

So, I have a few questions:
1. Do we need to plug ModelKinds into DataDefinitions?
2. The `cross` appearing in it's equation is ill-typed (`cross` is for vector cross product), so I think we'll need to change it somehow. Do we want to specifically have a variant of multiplication that's meant to be rendered slightly different? Do we have similar situations to this where we want to have different rendering styles of the same operations [potentially to the point where we should have "stronger differentiation in operations" rendering modes]? Should we perhaps just change it's equation to it's `2 * sy QM.pi_ / sy QP.period` component?
3. Should we move the single rearranging step to it's derivation?

**Comment by JacquesCarette** [comment]
1. I don't think so. `DataDefinition` is supposed to be pure definitions.
2. Yes, this is ill-typed. It looks like a hack to display. It's a silly equation, as the lhs and rhs are really the same!  If we strongly want different displays (which we have talked about in the past), we need to provide a real means to do so.  We should indeed change it to be just the last component.
3. This re-arrangement is so trivial, I don't think it's worth keeping. I would just remove it.

**Comment by balacij** [comment]
All of this sounds great. I'll make a PR. Thank you!
