### ISSUE TITLE
Should more concepts be put in data-drasil?

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2463]
examples:
transfer function
log file
input structure
control variable
frequency domain
inverse laplace transform
function in the time domain

**Comment by JacquesCarette** [comment]
Yes, they should - but not necessarily now. If they are used multiple times, then yes. Otherwise, let's wait, as finding good definitions is very hard.

**Comment by Awurama-N** [comment]
Okay
