### ISSUE TITLE
Commit work track under the people folder

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2478]
I think you mentioned we can create an issue to ask questions, so I am officially creating my first issue in Drasil.

I wonder to know which people folder should I commit to. I think @smiths mentioned there is an SE repo, ~~but I wasn't sure where it is~~ (in gitlab, there is se4sc folder, there is GradStudents folder ). There is also a people folder under the Drasil project, I think @JacquesCarette mentioned it in the meeting before the last one.

Another question would be should I have a branch add my local workings? I knew we can't directly commit to the master, so creating a branch seems to make sense.

**Comment by smiths** [comment]
@cd155, I think the easiest place for you to create your work is in the se4sc repo, in the folder for grad students:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/GradStudents

You don't need to worry about branches in the se4sc repo.  You can just push your work to master.

Once you start contributing to the Drasil code-base, you will use branches.
