### ISSUE TITLE
Moving fterms function out of drasil-data

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2483]
@JacquesCarette @smiths I found this function while looking through `Data.Drasil.Concepts.Documentation`:
```Haskell
-- FIXME: fterms is here instead of Utils because of cyclic import
-- | Apply a binary function to the terms of two named ideas, instead of to the named
-- ideas themselves. Ex. @fterms compoundPhrase t1 t2@ instead of
-- @compoundPhrase (t1 ^. term) (t2 ^. term)@
fterms :: (NamedIdea c, NamedIdea d) => (NP -> NP -> t) -> c -> d -> t
fterms f a b = f (a ^. term) (b ^. term)
```
I think this can now be moved to `Utils` because `Data.Drasil.Concepts.Documentation` already imports `Utils.Drasil` in the first place. This also would allow `fterms` to be used in `Data.Drasil.Concepts.Math` and `Data.Drasil.Concepts.Physics`

**Comment by JacquesCarette** [comment]
I did some cleanup a couple of months back to deal with bad imports, to pave the way to allow things such as this. So go ahead!
