### ISSUE TITLE
`section'` Function Behaviour

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2489]
@JacquesCarette, @smiths  This issue builds on top of a bunch of functions and I'm not completely sure what is going wrong, so I apologize in advance if there is any confusion here. I initially found this while trying to rename all the concept-level functions.
Under `Drasil.DocLang.SRS`, the helper function `section'` is defined as:
```Haskell
--function that sets the shortname of each section to be the reference address
section' :: Sentence -> [Contents] -> [Section] -> String -> Section
section' a b c d = section a b c (makeSecRef d (toString a))
  where
    toString :: Sentence -> String
    toString (S x) = x
    toString ((:+:) s1 s2) = toString s1 ++ toString s2
    toString _ = error "Term is not a string"
```
This is used in defining a reference such as this one:
```Haskell
propCorSol cs ss = section' (titleize' Doc.propOfCorSol) cs ss "CorSolProps"
```
This works well for the most part, but `toString` always returns the error case when I try to change `ofA`'s capitalization rules from using a `Replace Sentence` constructor to using `CapWords`
For reference, here is the current definition of `ofA`:
```Haskell
-- | Same as 'of__', except combining Sentence piece is "of a"
ofA :: (NamedIdea c, NamedIdea d) => c -> d -> NP
ofA t1 t2 = nounPhrase'' 
  (plural t1 +:+ S "of a" +:+ phrase t2)
  (plural t1 +:+ S "of a" +:+ phrase t2)
  (Replace (atStart' t1 +:+ S "of a" +:+ phrase t2))
  (Replace (titleize' t1 +:+ S "of a" +:+ titleize t2)) --Replacing this line with CapWords breaks the section' function above
```
I want to be able to change the last line to just `CapWords` in order to reduce any confusion in naming (and reuse combinators instead of making new ones), but I'm not sure if/how to go about solving it. The `titleize'` function used in `propCorSol` should be taking the plural case and then making every word capital in `Sentence` form, but right now it's only using what is given by the `Replace` constructor in `ofA`. Using `CapWords` with the singular `titleize` also calls the same error.

**Comment by JacquesCarette** [comment]
The problem is that `toString` is a horrible, horrible hack. It should be removed. The real bug is, why does `makeSecRef` need a String for its 2nd input?  We should investigate that first.  Then we can see about potential solutions.

**Comment by Ant13731** [comment]
I did a little more digging around `toString` and I found that the combinator itself is not the problem, it is that the terms of a combinator cant seem to pattern match without an explicit replacement for the title case. I'm guessing this means that `CapWords` is only applied when necessary as some kind of attachment or wrapper to the `Sentence`. I looked through the process of how `titleize` works, but the only thing I didn't really understand was the helper function `capString`.

**Comment by JacquesCarette** [comment]
As I said in the meeting this morning, the better solution will be to have `Sentence` be more refined.  There should be a subset of `Sentence` that is singled out as being something that makes sense for `makeSecRef` to take as input. Which means that indeed `Reference` needs to be modified so that some of those `String` can be a bit more complex.

**Comment by Ant13731** [comment]
Over the past week, I've been thinking a little about this issue and I may have two possible solutions.

Having a dedicated subset of `Sentence` for the purpose of being usable in the `Reference` type (and any other `String`/low level related purposes) might be nice as we could make it an instance of the show class. But in order to do that (with the current combinator setup), the terms would have to first be a part of the `Sentence` type before they could become this mediating type anyways. 
So I looked into how Drasil handles printing those terms and I found this:
```Haskell
lookupP :: ChunkDB -> UID -> Sentence
lookupP sm c = pluralNP $ termResolve sm c ^. term
```
which is used in the `spec` function. It converts a `Sentence` into a printable form (`Spec`) and also handles referencing a little bit differently. I know `toString` isn't that great in the first place, but I think it is really only used for referencing. Adding an additional pattern match to the definition of `toString` that could look up the `UIDs` in a `Database` (as `lookupP` does) could allow us to get rid of the need for duplicate "title case" combinators without much disturbance to the rest of Drasil. However, this doesn't really solve the problem of needing `toString` in the first place and will probably create more problems than it solves.

My second idea is to modify how the `ShortName` type works. The only reason that `section'` needs the `toString` function in the first place is because it calls `shortname'` on the first argument (which needs a `String` to work but is given a `Sentence`). Using a `Sentence`-like type for `ShortName` could work out better. I'm sure it'll break everything, but if it has an error checker to make sure its not being passed something that shouldn't be used as a short name (like `Expr`), I think it might be a cleaner solution. Along these lines, we could have a `DisplaySentence` type to using in making a reference (similar to how Expr is getting an overhaul) for things that don't really have significant meaning but need something more complex than a `String`. Possible constructors would be `DS String`, `DTerm Form LST NP` (where `Form` is either `Singular`, `Plural`, or `Short` and `LST` determines whether it should be used as all `Lowercase`, in a `Sentence`, or as a `Title`), and a concatenator constructor. This way, it can hold both `NounPhrases` and `Strings` which is what `Reference` wants in the first place.

I realize these are disorganized, but I just wanted to brainstorm some possible fixes. Let me know what you think.

**Comment by JacquesCarette** [comment]
So rather than changing `Sentence` (which might still be a good idea), I'm now thinking that the better change would be to have `Reference` not have `String` but `Sentence`s. I would probably change them one at a time (i.e. do a PR for each). Which to `String` to change into a `Sentence` first will be tricky.

Note that the "problem" with a solution in terms of `lookupP` is that this would mean that you'd need a `ChunkDB` available "at the right time". And that's going to fail, as a `ChunkDB` isn't really available until "much later". So that would fail.

I agree that changing `ShortName` should also be done. And this is where the subset of `Sentence` will come in, which is what you're essentially designing.   Looking at https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-lang/Language/Drasil/ShortName.hs it looks like just changing `String` to `Sentence` would fix 2 out of 3. The problem would then be moved to users of `getStringSN`.  Luckily, its use is `Utils.Drasil.Contents` is trivial to fix. The other uses in `Drasil.Printing.Import` should be fine, since if we're rendering, the `PrintingInformation` contains a `ChunkDB`.

Does that all make sense?

**Comment by Ant13731** [comment]
Yes, I think so. Should I start by just switching ShortName to take in a Sentence and see what breaks or try to make a subset of the sentence type first (and then apply to shortname)? As for Reference, should I just change one constructor (and everything that breaks) with one PR at a time?

**Comment by JacquesCarette** [comment]
Yes, start switching ShortName. I think that is the key step. Let's see how that goes first, then deal with Reference.

When things break in non-obvious ways, don't try to bulldoze your way through. Report back instead, as the correct fix might be quite subtle (for example, perhaps involving parts of the Drasil design that you have not seen yet).

**Comment by Ant13731** [comment]
I've run into a problem right off the bat, and I'm not really sure how best to solve it. If I want to change ShortName to take a Sentence, then Reference will need to import ShortName (which imports Sentence). However, Sentence uses Reference in its construction, so it needs to import Reference, making an import cycle. Would these now have to be defined in the same module/file?

**Comment by JacquesCarette** [comment]
`ShortName` would definitely need to import `Sentence`.  And indeed, `Classes.Core` uses `ShortName`, which is a problem, as that leads to a cycle.

I think that the first item to investigate is whether `HasShortName` needs to be in `Classes.Core`.  Could it be in `Classes`? Also, I do think that moving the definition of `ShortName` in to `Sentence` is reasonable, and will be needed.

I'm not sure which of those two to do first (moving `HasShortName`, moving `ShortName`), or if they are even independent. This is without changing `ShortName` to using `Sentence` at all, as that will introduce further complications (likely).  So you'll need to conduct further experiments.

**Comment by Ant13731** [comment]
There's another set of import cycles between `Sentence` and `Reference` as `ShortName` is a `Sentence` that is within the `Reference` type. `Sentence` then uses `Reference` for one of its constructors meaning that the `Sentence` and `RefProg` files would create an import cycle. Should the `Reference` data type then be defined in `Sentence` as well?

`HasShortName` works in `Classes`, as that file imports `Sentence` anyways.

After more trials, `Reference` itself needs the `HasShortName` class, so if it were in Sentence, that would create a cyclic import with `Classes`.

What if we could use `ShortName.hs` as a place for all these imports? I have an idea and I'll try it out now.

**Comment by Ant13731** [comment]
I just pushed to a new branch `shortNametoUseSentence` that contains all of the new imports. Both `Reference` and `ShortName` are now inside of `Sentence.hs`. Unfortunately, I couldn't find a way to allow `HasShortName` to remain in the `Classes.hs` file without creating import cycles or orphans, so the `Sentence.hs` file now contains a lot of stuff that isn't exactly Sentence-related. Let me know what you think.

**Comment by Ant13731** [comment]
I think the base issue here has been completed since `section'` no longer exists. There's still some stuff from here that should be fixed but I think that should be in another issue.
