### ISSUE TITLE
Investigating outdated Doclang Constructors (InTable)

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2505]
This is to investigate the removal of Doclang constructore `InTable`

(details in Issue #1602 )

**Comment by Awurama-N** [comment]
inTable is defined in Drasil.Sections.Requirements

inTable can only be found in Doclang and were it's defined.

```
inTable :: (Quantity i, MayHaveUnit i) => [i] -> LabelledContent
inTable i = mkInputPropsTable i (inReq EmptyS)

```
it is meant to “pass empty Sentence to make stub of inReq” (`inReq` can also be found in Doclang)

inReq uses inTable and is used in the  “Requirements.hs” file of GlassBR, NoPCM, and SWHS. And Body.hs file of the GlassBR and SWHS examples.

My conclusion for this would be that: even though inTable itself doesn’t show up in any of the examples, it seems to help `inReq` function and so shouldn’t be deleted.

**Comment by JacquesCarette** [comment]
Agreed.  Though that `EmptyS` in the call to `inReq` is suspicious - but that's a separate thing. This issue is closed.
