### ISSUE TITLE
Investigating outdated Doclang Constructors (ddRefDB)

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2507]
This is to investigate the removal of Doclang constructore ddRefDB

(details in Issue #1602 )

**Comment by Awurama-N** [comment]
The use of `ddRefDB ` can be found in Drasil.DocumentLanguage.RefHelpers

```
data ModelDB = MDB
             { tmRefDB :: RefMap TheoryModel
             , gdRefDB :: RefMap GenDefn
             , ddRefDB :: RefMap DataDefinition
             , imRefDB :: RefMap InstanceModel
             }
```
It seems like this is the only place it is actually directly used. But since it's connected to DataDefinitions it's not obsolete.

 I tested this by deleting `ddRefDB` to see the results and found that it led to errors with things having to do with `DataDefinitions`. 

The only other place this constructor appears is in the Doclang file.

@JacquesCarette

**Comment by Awurama-N** [comment]
My conclusion for this would be that the `ddRefDB` constructor should not be deleted.

**Comment by JacquesCarette** [comment]
Agreed.
