### ISSUE TITLE
Investigating outdated Doclang Constructors (getDocDesc)

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2508]
This is to investigate the removal of Doclang constructore getDocDesc

(details in Issue #1602 )

**Comment by Awurama-N** [comment]
`getDocDesc` is defined in Drasil.ExtractDocDesc

```
getDocDesc :: DocDesc -> [Sentence]
getDocDesc = fmGetDocDesc (sentencePlate id)

```

Aside Drasil.ExtractDocDesc & Doclang it can also be found used in Drasil.DocumentLanguage.

In Drasil.DocumentLanguage, `getDocDesc` is used in the definition other constructors, such as `extractUnits`.

```
extractUnits :: DocDesc -> ChunkDB -> [UnitDefn]
extractUnits dd cdb = collectUnits cdb $ ccss' (getDocDesc dd) (egetDocDesc dd) cdb
```
My conclusions for `getDocDesc` would be not to delete it, since it is used in defining other constructors even though `getDocDesc` itself isn't mentioned anywhere else.
@JacquesCarette

**Comment by JacquesCarette** [comment]
Agreed.
