### ISSUE TITLE
ODE definitions review

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2509]
Hi, @JacquesCarette and @smiths, there are some ODE definitions I found.  I looked at several textbooks which introduce differential equations. I retrieve some definitions that I think more likely to make sense. This file is located in [se4sc repo](https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/blob/git-svn/GradStudents/Don/ODE/Definition.ipynb). 
1 . Sorry for such a long file, I wonder for next time, is it better to list some of my work rather than all of them? 
2. The ODE definitions turn out different than the graph definitions that I used to work with. In the graph definition, I could imagine how each definition be represented in code. However, the ODE definition seems to be more abstract. I asked a question for myself, what is an equation? I couldn't really answer that because we do not compare numbers in this case. Both the left-hand side and right-hand side are mathematical expressions. This puzzled me for a while that "how to let Drasil know two sides are equal?".
3. Sometimes, textbooks use indirect descriptions to describe terminologies. For example, it said a first order differential equation can be rewritten in the form of `y' + p(t)y = f(t)`. If `f(t) = 0`, it is homogeneous. It happened not just in one textbook. Personally, I feel it is not a good definition because it describes an intermediate rather than the object itself. It uses the intermediate as criteria rather than describe the object directly. I am not quite sure whether this type of definition can be accepted.

### Basic Knowledge
- Equations: the relation between two mathematical statements
- Derivative: a function describe the rate of change in the function value with respect to changes in its input 
    - `(change in function) / (change in input)`
- Differential equations: is an equation with an unknown function and one or more of its derivatives. Or, the relation between an unknown function and its derivatives.
-  Order: determined by the highest derivative that appears in the equation. 
- First Order: the first derivative
- Second Order: the second derivative
- High Order: the `nᵗʰ` derivative, `n ∈ 𝑁`
- The highest derivative: the highest repeated steps which can be traced back to the original function by taking derivative.

### Different Differential Equations
- Ordinary Differential Equations are equations with an unknown function(only depends on a single independent variable) and one or more of its derivatives. Or, the relation between an unknown function(only depends on a single independent variable) and its derivatives.
- Partial Differential Equations are equations with an unknown function(depends on several independent variables) and one or more of its derivatives. Or, the relation between an unknown function(depends on several independent variables) and its derivatives.
- Systems of Differential Equations are multiple differential equations that describe the relationship between multiple unknown functions and their derivatives, each differential equation with multiple unknown functions and one or more of its derivatives.

### First Order Differential Equations
- First Order Differential Equations: `dy/dx = f(x, y)`, where `dy/dx` is the first order derivative, `f(x, y)` can be any function of the independent variable x and the dependent variable y. y is a variable that depends on x.

### Linear Equation
- Linear Relationship: describe a straight-line relationship between two variables.
- Linear Equation: the derivative of the highest order is a linear function of the lower order derivatives.
- First Order Linear Differential Equations: `dy/dx = p(x)y + q(x)`, where `p(x)`, `q(x)` are coefficents, which are functions of `x` alone.
- Second Order Linear Differential Equations: `d²y/dx² = p(x)dy/dx + q(x)y + r(x)`, where `p(x)`, `q(x)`, `r(x)` are coefficents, which are functions of x alone.
- Non-Linear Differential Equations: the derivative of the highest order is not a linear function of the lower order derivatives.

### Homogeneous
- Homogeneous Function: in a function, if all its inputs are multiplied by a factor, then its value is multiplied by some power of this factor.
    - `f(av) = aᵏf(v)`, `f(v)` is called homogeneous of degree k.
    - `f(zx, zy) = zⁿf(x, y)`, `f(x, y)` is called homogeneous of degree n.
    - for all suitably restricted `x`, `y`, and `t`. This means that if x and y are replaced by `zx` and `zy`, `zⁿ` factors out of the resulting function, and the remaining factor is the original function.
- First Order Homogeneous differential equation: 
    - `M(x, y)dx + N(x, y)dy = 0` is homegeneous if M and N are homogeneous function of the same degree.
    - it is homogeneous, if the equation can be rewritten in the form of `y' + p(t)y = 0 or y' = -p(t)y`, where `p(t)` is any function depend on t.
- First Order Non-Homogeneous differential equation: if the equation can be rewritten in the form of `y' + p(t)y = f(t)` and `f(t)` is not zero.

### Numerical Methods
- Euler Method - First Order
    - Given `f(t, y)`
    - choose a initial value `t₀` and `y₀`
    - choose step size h and number of steps n
    - Iteration
    - ```python
        for j from 1 to n do:
            k1 = f(t, y)
            y = y + h*k1
            t = t + h
        ```

**Comment by JacquesCarette** [comment]
Meta-notes:
1. you should have assigned us on the issue
2. this kind of information is better on the Wiki than in an issue; the main information should be moved to the wiki, and the a short 'review' issue can be done.

Notes:
- yes, the notion of 'equation' in mathematics is not so well-defined.  Roughly it means (and this is a recent CS-influenced view): for all free variables, if those are substituted with ground terms, and these terms are reduced to a normal form, then the lhs and rhs of the equation are identical. A ground term is a term with no free variables. A normal form is an expression that cannot be evaluated anymore.
- in the case of differential equations, the above is generalized to allow for some free variables (like `x`) denoting numbers.
- So a "solution" to an ODE is a function such that, when it is "plugged in" to the equation, you reduce to "0 = 0".
- yes, textbooks are often quite sloppy in their definitions. Here are slightly better definitions:
   - first order: the only derivative that appears in the equation is a single one, with respect to a single derivative
   - homogeneous: 0 is a solution of the equation.
- a lot of your definitions are mathematically correct. What's needed is to go from these definitions to suggestions for representations of these concepts as data-structures. So you'll find that the phrasing you've used will need refinement for that to be possible.

**Comment by cd155** [comment]
Thanks for the feedback. 
1. I think since this account is not a contributor for Drasil project, Assignees and other features is grey out on my end. Could it possible add this account to maintainer or developer?
2. I will move this information to Wiki.

**Comment by JacquesCarette** [comment]
Account added as a contributor.

**Comment by smiths** [comment]
Yes, moving the information to the Wiki is a good idea.  To the feedback from @JacquesCarette, I'll add the following:

- A Non-Linear Differential equation is a differential equation that is not a linear equation in the unknown function and its derivatives (from the [Wikipedia entry](https://en.wikipedia.org/wiki/Differential_equation). )
- It is good that you looked at numerical methods for solving ODEs, since they will help you understand ODEs

**Comment by cd155** [comment]
I moved the ODE definition to Wiki  [ODE Definitions](https://github.com/JacquesCarette/Drasil/wiki/ODE-Definitions).

Should I close this issue?

**Comment by smiths** [comment]
Yes, can close this issue.
