### ISSUE TITLE
LaTeX string quotes not rendering as expected on Website

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2517]
Consider Projectile's IM:messageIM:

From the PDF, we have nice left-hand side double quotes on the left-hand sides of the strings:
![image](https://user-images.githubusercontent.com/1627302/119672772-db1c1a80-be08-11eb-93ba-e6a4c393e0f7.png)

But then, in the [html version](https://jacquescarette.github.io/Drasil/examples/Projectile/srs/Projectile_SRS.html#IM:messageIM), it renders as:
![image](https://user-images.githubusercontent.com/1627302/119673096-1a4a6b80-be09-11eb-9157-527c0e225c24.png)

~~Looking at the right-hand side as well, it seems that it's not formatted in an equation, and the epsilon symbol is also a unicode symbol inside of both documents.~~

**Comment by JacquesCarette** [comment]
Certainly the quotes are wrong in the html version.  In the bug report, I don't quite see what's wrong the the rhs in the html?

**Comment by balacij** [comment]
Ah, I might've been wrong about the "not formatted in an equation" part, but the epsilon symbol, I believe, we want to have as `\varepsilon` here instead of the raw unicode character?

![image](https://user-images.githubusercontent.com/1627302/119683439-a6609100-be11-11eb-8351-15f2bd1ede94.png)

**Comment by JacquesCarette** [comment]
What's wrong with the raw unicode?

**Comment by balacij** [comment]
I was just thinking we were always wanting to use the LaTeX symbols instead of the raw epsilon symbol, similar to discussion in #2240 (though, here it displays in both HTML and PDF without issue I think). My apologies if I assumed incorrectly!

**Comment by JacquesCarette** [comment]
I do think that there are real issues around unicode, latex and html. It seems to generally work, with a few minor exceptions. We need to figure out those exceptions and how to deal with them.

**Comment by balacij** [comment]
A _possible_ way to fix this is to update our used MathJax version and load the "textmacros" package via [MathJax JS config](https://docs.mathjax.org/en/latest/input/tex/extensions/textmacros.html). Though, this might cause more unexpected changes.

**Comment by JacquesCarette** [comment]
Definitely worth experimenting with.

**Comment by balacij** [comment]
I created a variant in the [updateMathJaxVersion](https://github.com/JacquesCarette/Drasil/compare/updateMathJaxVersion) branch, and it fixes this issue of the double quotes, but it appears that MathJax 3 is completely different than MathJax 2 so the default configuration is a bit different.

@Awurama-N Do you mind checking through the stable website srs as well and see if we can fix any of the differences? Right now it seems like main issue is that we end up with a bit of extra spacing with functions. For example, we had "sin(x)", but now it appears as "sin (x)" with a little bit of extra spacing between the "n" and "(" that I can't seem to figure out how to remove.

**Comment by Awurama-N** [comment]
Okay yes, i'll go through and report back here any differences i find first

**Comment by Ant13731** [comment]
> For example, we had "sin(x)", but now it appears as "sin (x)" with a little bit of extra spacing between the "n" and "(" that I can't seem to figure out how to remove.

I was looking at the projectile SRS docs and the LaTeX version also renders those functions with a space. For example:
- current HTML 
    ![image](https://user-images.githubusercontent.com/69334555/128020344-1645bc06-0992-47f1-ae9d-419052a9834a.png)
- updatedMathJax HTML
    ![image](https://user-images.githubusercontent.com/69334555/128020411-7bdc79f7-d17e-48ab-893b-072a9743961e.png)
- current PDF 
    ![image](https://user-images.githubusercontent.com/69334555/128020455-14b7fec7-f720-4487-bdd0-9a3e3650ce84.png)

Were there any other issues with the updated MathJax branch? (I've only gone through projectile so far but it seems to be okay)

**Comment by balacij** [comment]
The only issue that I found, which I didn't yet try to solve, was with the spaces. At times, we had extra spaces between things. For example, from your pictures, the `sin(theta)` is the original variant, while the new version is more like `sin (theta)`. It's a bit more obvious of an issue when you have `sin(theta)cos(theta)` because it placed them ~ `sin (theta)cos (theta)`.

**Comment by balacij** [comment]
Oh, my bad, you addressed the `sin` issue. If that's the case, and it lines up nicely with both, then we should just skim through the other examples to double-check there's no other issues. If there's no other issues, then we can PR of course.

**Comment by Ant13731** [comment]
Okay, sounds good. Also, I found that `CTRL+F` doesn't work on the new equations (I don't think they render as text, I can't highlight it either), but all of the variables are usually defined whenever they are used in a model/theory so I don't think it matters too much.

**Comment by Ant13731** [comment]
The only change I saw (after skimming each example) was in the pendulum examples:
- Ω renders italicized with new mathjax. In the old HTML and PDFs it was rendered normal
    - Old 
        ![image](https://user-images.githubusercontent.com/69334555/128028117-1bc919b7-915c-46f3-8d24-ba77d775c650.png)
    - New
        ![image](https://user-images.githubusercontent.com/69334555/128028144-f8926049-0a2d-4a4b-900a-4465076be906.png)

**Comment by balacij** [comment]
Nice! Thanks for checking!
