### ISSUE TITLE
How to see full documentation locally

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2525]
Hello, I'm having trouble finding the full docs when running `make docs` locally. Is it in a different file path from the normal documentation?

**Comment by balacij** [comment]
Ah, I had the `make docs` changed slightly. It builds the `docs` folder, but embeds the "full" version in a `full` folder within the `docs` folder.

**Comment by balacij** [comment]
Might be worth noting this somewhere now that I think about it, any ideas where we can?

Thank you!

**Comment by smiths** [comment]
I like the idea of adding the note to the end of the script.  Would there also be value in updating the Contributor's Guide?  There is a section on make (https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#make-and-drasil-packages), although the make section doesn't currently discuss `make doc`.

**Comment by Ant13731** [comment]
Mine doesn't seem to generate a full folder. Also I think mentioning in the Quick Start and Readme files would be good too.

**Comment by balacij** [comment]
@smiths I think that's a great idea! I can write a note about it there too.

@Ant13731 Did you make sure to `git pull origin master` to get upstream changes? Were there any errors in the logs?

**Comment by Ant13731** [comment]
Oh sorry, I thought my master was up to date. Let me see if it works now.

**Comment by Ant13731** [comment]
Okay, I found it! I think I was looking in the wrong place (its under `code/docs/full` but I was looking under `code/.stack-work/install/48ba28e6/doc`). Thanks for your help @balacij!

**Comment by balacij** [comment]
I added a little blurb about the Haddock documentation, a note at the end of the `make docs`, and updated the related README area.

Let me know if this is good and we can close this ticket!

**Comment by balacij** [comment]
@Ant13731 Are we okay to close this now?

**Comment by Ant13731** [comment]
Yep!
