### ISSUE TITLE
Investigating outdated Doclang Constructors (ciGetDocDesc) 

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2541]
This is to investigate the removal of Doclang constructore `ciGetDocDesc`

(details in Issue #1602 )

**Comment by Awurama-N** [comment]
`ciGetDocDesc` is defined in Drasil.ExtractDocDesc

```
ciGetDocDesc :: DocDesc -> [CI]
ciGetDocDesc = fmGetDocDesc ciPlate

```
`ciGetDocDesc` is only found in Doclang and Drasil.ExtractDocDesc

It seems obsolete.

My conclusion is that `ciGetDocDesc` can be deleted.
I have attempted to do this and did not face any issues or conflicts.
should I go ahead and make these changes?

**Comment by JacquesCarette** [comment]
Yes.

**Comment by Awurama-N** [comment]
Below is the definition of ciGetDocDesc

```
ciGetDocDesc :: DocDesc -> [CI]
ciGetDocDesc = fmGetDocDesc ciPlate
```
its definition contains `ciPlate`, which seems to have been defined solely for the purpose of being used in the definition of `ciGetDocDesc`. Without ciGetDocDesc `ciPlate` becomes redundant. 
Could i delete this as well? I experimented and realsied deleting it doesn't break anything.
I could also just comment it out of the working code instead.

@JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
comment out `ciPlate` for now, don't delete it. What about `fmGetDocDesc`?

**Comment by Awurama-N** [comment]
okay.
`fmGetDocDesc` is currently used in the definition of `egetDocDesc` and `egetDocDesc` is also used to define other things. So `fmGetDocDesc` is not obsolete.

```
egetDocDesc :: DocDesc -> [Expr]
egetDocDesc = fmGetDocDesc exprPlate
```
