### ISSUE TITLE
`Space` needs to be able to represent function spaces 

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2554]
There are currently no defined spaces to represent functions.
And Space needs to be able to represent function spaces also.

https://github.com/JacquesCarette/Drasil/issues/2395#issuecomment-853261914

**Comment by JacquesCarette** [comment]
You should add a link to the discussion we had that pointed out the need for this.

**Comment by balacij** [comment]
Nice. I think we'll need this for #2418

**Comment by balacij** [comment]
This was done in the above mentioned PR.
