### ISSUE TITLE
Automate Section 1

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#256]
[Assigned lots of people, so that everyone sees this.  Or do you all get emails when new issues get created?]

Right now, everyone's example has a Section 1 with a table of symbols and a table of units (and maybe a table of acronyms).  This section is relatively well automated, except for two things:

1. There is an explicit list of symbols that get 'documented'
2. There is an explicit list of units that get 'documented'.

This is silly.  The table should list all the symbols that occur in the SRS, and all the units that occur too.  We should be able to 'query' some data-structure which represents the 'requirements', about to be rendered as a document (aka the SRS) to find out what to do.

This data-structure currently does not really exist.  Well, there is a proto-structure, the SystemInformation structure -- but this may not be the best place.  A sub-structure of that, maybe.

One place where this information is 'percolating' is actually the new symbol table that Dan created recently!  Hopefully, that table actually is exhaustive, and we could use it.  But I am not sure it is.

**Comment by smiths** [comment]
@JacquesCarette, will it be possible in the future to make a compilation pass over the equations in the document and build the list of symbols directly from them?

**Comment by JacquesCarette** [comment]
Yes.  That is easy to do.  The hard part is actually to know what are all the relevant equations!

**Comment by smiths** [comment]
I'm sure I'm being too simplistic, but aren't the relevant equations all of them?

**Comment by szymczdm** [comment]
Minor clarification request, by:

> One place where this information is 'percolating' is actually the new symbol table

Do you mean `SymbolMap` or the document language `TSymb` (or something else)?

**Comment by JacquesCarette** [comment]
Re: all equations.  In theory, yes.  But in practice, we'll have equations in our database which we won't use, so we don't want to include them.  And we may have made an error, and one of the equations is not actually 'hooked in' anywhere - and we'd like to see that.  Lastly, we don't have "all equations" stored anywhere (yet?).

Re: clarification.  `SymbolMap` is what I meant.

**Comment by JacquesCarette** [comment]
@szymczdm it feels like we're epsilon close to having this done. What is missing?

**Comment by szymczdm** [comment]
Things have evolved quite a bit since June, so I think we should discuss this issue again and see what we still want to do with it.

I believe we should at the very least have a database of Units alongside the Symbol db before we close this. We could also create one for equations, definitions, etc, but again, those could be separate issues.
