### ISSUE TITLE
Convert Projectile's InstanceModels into EquationalModels

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2569]
Similar to PR https://github.com/JacquesCarette/Drasil/pull/2564/files

Projectile has 4 OthModel/InstanceModels that need to be converted into EquationalModel/InstanceModels.

Similar to that PR, we should do this in 4 PRs, one for each model, and we should introduce an `iMods0` to hold the ones that haven't yet been converted, and then we should use getEqModQDsFromIM to get the QDefinitions of `iMods` instead of the current `relToQD`.

**Comment by balacij** [comment]
@Awurama-N This ticket is for these InstanceModels:

https://github.com/JacquesCarette/Drasil/blob/82701ddc45338a31953a021d36a261bda2da2d45/code/drasil-example/Drasil/Projectile/IMods.hs#L33-L34

**Comment by Awurama-N** [comment]
oh my bad, i must have closed the wrong one.

**Comment by balacij** [comment]
Thanks @Awurama-N! I think this is good to close now.
