### ISSUE TITLE
Motion definition

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2588]
In the double pendulum SRS, the goal is to calculate the motion of two masses. I have some questions regard the motion definition. 

1. Base on [Motion Wiki](https://en.wikipedia.org/wiki/Motion),  motion is the phenomenon in which an object changes its position over time. In other definitions that I found in other sources, it only says "Motion is the action of changing location". It makes sense that the first one is a more accurate definition, so just want to double-check with it. Also, does the motion also include its velocity, acceleration, and directions? Or these just byproducts for calculating the motion?
2. Base on the above, I have another question regarding the position. In the 2D environment, the position could be expressed in the `x, y` coordinate. Is the eventual output be x, y coordinate over time? In the double pendulum example, it outputs the angle of two rods over the simulation time. What I am currently imagining is that given the required inputs, the program will output the position of two rods.

**Comment by smiths** [comment]
@cd155 with respect to your definitions of motion, I don't see much difference.  I do prefer the first definition (an object changes its position over time).  The key parts of the definition are position and time.  The second definition technically allows for the possibility of instantaneously changing location.

Once you have the notion of changing position over time, the concepts of velocity, acceleration and direction come along with it.  The direction comes from introducing a coordinate system and velocity and acceleration come from taking time derivatives of the changing position.

Your second question deals with the notion of coordinate system.  Any motion problem can be expressed in any coordinate system, but we like to pick a coordinate system that is convenient.  It is mathematically possible to switch between different coordinate systems.  If we have the angle of the rod we can calculate the x and y coordinates, and if we have the x and y coordinates we can calculate the angle.  You can just go with what is currently done in the documentation for the pendulum problem.
