### ISSUE TITLE
Notes in tables

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#26]
Would it be possible to add notes to specific items in a table, for example with an asterisk, like in the picture below, without having to type the whole table out manually? Ideally I would want to make tables using mkTable and lambdas, but that's currently not possible if I want to add these notes. 

![tablewithasterisksexample](https://cloud.githubusercontent.com/assets/18634568/15654651/e80dca5a-2663-11e6-87aa-c56a8592f767.png)

**Comment by szymczdm** [comment]
You can still use mkTable and lambdas for any line lacking an asterisk, then manually write the lines with the asterisks, then compose everything together. It's messy, so I'll look into a better way to do it.

**Comment by niazim3** [comment]
@smiths Perhaps a note can be added to the table referenced in requirement 1 in GlassBR (see #367)?

**Comment by smiths** [comment]
@niazim3 , I think I see what you are getting at here.  It seems worth considering.  What would the content of the note be?  I think the SRS document should always use a and b in m.  The only place we should use mm is when reading in the values.  If this will cause confusion, we could introduce new variables just for the purpose of input, say a* and b*.

**Comment by niazim3** [comment]
I was thinking something along the lines of: "(*) This value is input in _mm_".
In this way, the units for **_a_** and **_b_** will always be listed in terms of _m_ in the SRS document, and the fact that the input will be in different units is also mentioned in an area where the reader would look (i.e. in this case, the table linked to requirement 1 listing all the required inputs by the user).

**Comment by smiths** [comment]
Yes, like your note.  Please proceed.

**Comment by smiths** [comment]
The original issue about displaying attribute information as part of a table is a low priority.  However, the bigger picture issue of having a facility to attach additional information through attributes is an important design consideration.  A new issue ( #408 ) has been created for this purpose.

**Comment by balacij** [comment]
So, I have two questions:
1. When would we want to _manually_ attach notes to table cells?
2. When would we want to _programmatically_ attach notes to table cells?

Implementation of a local symbol scope for a table is simple enough, but I don't quite understand the use-case. Shouldn't the example messages as mentioned in the OP picture be argued elsewhere? e.g., in whatever theory brings up the constraint?

**Comment by smiths** [comment]
@balacij the original notes in the table cells (the constraints on some values to be non-zero) are rationale information.  Someone might think that the no-pcm version of swhs can be implemented using the pcm version, but with setting Ap and Vp to zero.  The divide by zero errors means that this isn't possible.

I would have to check to be sure, but I think some of the constraints only come up in this table.  I don't think there is always another location where this information is given.

I think the first problem is capturing our rationale information.  We don't currently do that very well.  How and where we display the rationale is a secondary consideration.  Using footnotes in a table doesn't seem to be the best place to me.  We might have a rationale for every constraint.  That would be a lot of footnotes.  My current thinking is that we should provide the rationale (or derivation) of the constraints in the IM where they arise.  This is what is done in the ["refined theories" version of projectile](https://github.com/smiths/caseStudies/blob/master/CaseStudies/projectile/projectileSRS_RefinedTheories/Projectile_SRS.pdf).  Another option would be a separate section to provide rationale information for constraints, as is done for the refined theory version of projectile for typical values in Section 5.3.4.

I would be in favour of closing this issue.  We might want footnotes for tables someday, but it seems like we would be using footnotes to manually add notes that are strings when we really should be understanding the knowledge we are capturing at a deeper level.

**Comment by balacij** [comment]
Thank you, @smiths. I agree with you, and especially so about the refined theories version providing rationale of constraints where they arise!

So, I suppose we can close this!
