### ISSUE TITLE
Move Actor/Messages+EnumeratedThings out of Expr, into new "CodeExpr"

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2602]
Related to discussion on https://github.com/JacquesCarette/Drasil/commit/ff34fe093b8898383232e2822f478a394243aef9#r52161989

**Comment by balacij** [comment]
This task is proving a little bit more complicated than separating the DisplayExpr-related components. With this one, we frequently embed CodeExprs in Exprs, unlike with the DisplayExpr-related components.

**Comment by JacquesCarette** [comment]
Concrete examples?

For `CodeExpr`, we might have to bite the bullet and make a parallel hierarchy.

**Comment by balacij** [comment]
In drasil-code, we need to convert `FuncStmt` (since most `new` calls are within `FuncStmt`s) and `Step` (because of below `appendCurrSol`) to be using CodeExprs instead of Exprs, but when we do this, the ExternalLibrary related components are the first to breakdown.

For example, 
https://github.com/JacquesCarette/Drasil/blob/268bbdd5b552e2a4c51eebffcdf7303d2689d0a4/code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs#L276-L283

^ we would be comparing a CodeExpr (field ..) to an Expr (ub)

https://github.com/JacquesCarette/Drasil/blob/268bbdd5b552e2a4c51eebffcdf7303d2689d0a4/code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs#L270-L274

^ here the `v` is a CodeExpr, so we would need to instantiate a Matrix containing a single value; a CodeExpr -- we might need to have a Matrix idea in CodeExpr too.

https://github.com/JacquesCarette/Drasil/blob/268bbdd5b552e2a4c51eebffcdf7303d2689d0a4/code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs#L292-L294

^ here the first parameter would need to become a CodeExpr, but we use that CodeExpr in the `idx` call, which means that we do in fact need a copy/idea of a function in the CodeExpr as well.

https://github.com/JacquesCarette/Drasil/blob/268bbdd5b552e2a4c51eebffcdf7303d2689d0a4/code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs#L233-L237

I'm going to try to spend a bit more time seeing if I can the wrapped version going well. If it continues to be difficult, we'll try out the 1-1 way.

**Comment by JacquesCarette** [comment]
I think the 1-1 way will end up simpler. Plus, we can also adjust things so that the `Expr` version is "more abstract" and the `CodeExpr` "more concrete", which would be nice.

**Comment by balacij** [comment]
Additionally, our `Deriv` constructor is seemingly only used for display purposes and the `convExpr` area for `Deriv` is currently left unimplemented. Do we want to move `Deriv` to our `DisplayExpr`?

**Comment by balacij** [comment]
If the answer to the above is yes, then we might also want to have `DisplayExpr` be a 1-1 clone of `Expr` as well, like `CodeExpr`, so that we can intermix things easily. It might be good to have a TTF platform for the smart constructors of the 3 Expr languages too.

**Comment by JacquesCarette** [comment]
Yes to moving `Deriv`. We'll want to have a model-level representation (soon) via @cd155 's work, but it doesn't need to go this deeply into `Expr`.

I think using TTF will make sense once we've moved to these being typed. Otherwise, I think the errors messages during the transition might be too painful.

**Comment by balacij** [comment]
That's perfect! Thank you. I think the work will match nicely with @cd155's.

Regarding TTF, that sounds good to me.

**Comment by balacij** [comment]
With #2622 merged in, we have `CodeExpr`, and we moved the Actors/Messages/New into `CodeExpr`. The EnumeratedThings were never really in Expr, they were only used to create Exprs, and now, they are used to create `CodeExpr`s instead.

However, we still have `Space` as discussed in https://github.com/JacquesCarette/Drasil/commit/ff34fe093b8898383232e2822f478a394243aef9#r52161989. I will create a new ticket for that, with some questions about what how we should go about it.
