### ISSUE TITLE
Code generation redesign

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#261]
I'm finished the gool code for glassbr -- it now produces fully working and complete code that produces the same output as the original (at least for python).  So moving on to generation.

I've been combing through Example.Drasil and Language.Drasil thinking about how to proceed for code generation with respect to the new design (issue #111).  I believe my path to get there is roughly:

1.  Develop data structures for Abstract Theory, Instance, and Executable Spec (red portion of new_design2.pdf in issue #111).  

2.  Develop an executable description that uses the system description (SystemInformation) to produce an executable specification, much in the same way that DocDesc uses SystemInformation to produce documents in DocumentLanguage.hs

3.  Write a new code generation mechanism that translates the executable spec into gool code.

I'm currently stuck on 1:  what exactly is an abstract theory and an instance?  What information do they hold?

**Comment by JacquesCarette** [comment]
That is what we want to end up with, but the opposite of what you should *do*.

You should take a look at the gool code, and see what the patterns are.  Figure out what is 'code specific' and is just a 'rendering' of higher-level information.  Then write a data-structure with just that information, and a renderer that generates gool.  That renderer really ought to be an interpreter, so it can take in an information data-structure and a "program" that guides the rendering.  Roughly step 3 above.

Then you should probably try to figure out a data-structure which abstracts the one you've just created even more -- but its goal would be to encapsulate the information that is in `Example.Drasil.GlassBR.*`.

Always work 'bottom up' on creating DSLs.  Of course, we know where we want to end up, which helps.  But we don't know what the route will look like.  So start from the known (gool code) and walk towards the unknown (abstract theories, instances, executable spec), starting with the closest one.

**Comment by palmerst** [comment]
I'm closing this as it was more of a question than an issue.  The underlying issues are covered in other real issues.
