### ISSUE TITLE
Update Introduction for Double Pendulum

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2615]
The introduction for Double Pendulum does not follow the pattern of the other examples.  Please make the following changes:

- Please modify the wording so that the Pendulum is capitalized in the last word of the first paragraph.
- The introduction says that the purpose will be presented, along with other parts that are not included.  We should add those other parts to the document.  If adding the other parts is a significant amount of work @cd155, please create issues for each subsection.

**Comment by cd155** [comment]
Just confirming with @smiths , the sections that need to be added are 

1. purpose of this document
2. the characteristics of the intended reader
3. the organization of the document

If yes, I will create three separate tickets to tackle each section.

**Comment by smiths** [comment]
Yes, @cd155, creating an issue for each of the three things you mentioned would be a good start for you.

**Comment by cd155** [comment]
Created the following to add sections in the introduction.
#2631
#2632
#2633
