### ISSUE TITLE
Double Pendulum: Update the double pendulum example to actually be a double pendulum

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2618]
The double pendulum example only presents the theory for one pendulum.  We should update it for two rods.

**Comment by cd155** [comment]
@smiths would you mind pointing in a direction? I am not quite sure how to start with this update.

Currently, there is only a single pendulum knowledge on the SRS. My guess is I need to update section 3.2 Solution Characteristics Specification, which has Assumptions, Theoretical Models, General Definitions, and so on. This is actually related to  #2680 , which requires additional information to be added in this example.

**Comment by smiths** [comment]
@cd155 have you looked at the CAS 741 double pendulum example that I sent to you previously?  I think this example is a good place to start.   If you've lost the link, you can find it at:

https://github.com/Zhang-Zhi-ZZ/CAS741Project

A nice little demo of double pendulums can be found at:

https://www.myphysicslab.com/pendulum/double-pendulum-en.html

As you scroll down this page you will see the derivation that was used to build the derivation in the CAS 741 project.  There are many ways to derive and present the equations for a pendulum.  This way is likely the easiest to understand because it is based on Newton's law (F = ma).  Other forms are actually easier to solve, but harder to understand.  We'll stay away from introducing Lagrangians for the moment.  :-)

**Comment by cd155** [comment]
@smiths Thanks.
I just realized the version in [https://github.com/Zhang-Zhi-ZZ/CAS741Project](https://github.com/Zhang-Zhi-ZZ/CAS741Project) is different than the version on Drasil example. I did remember that you mentioned it is a manual version, but I didn't realize that there would be much difference between two at that moment.

**Comment by cd155** [comment]
The follow content will be added

4.1.2 Physical System Description
The physical system of Pendulum, as shown in the Fig:pendulum below, includes the following elements:
- PS1: The first rod (with length of the rod 𝐿1). 
- PS2: The second rod (with length of the rod 𝐿2). 
- PS3: The first object.
- PS4: The second object.

(**image is not included in this ticket**)
<img width="499" alt="Screen Shot 2021-07-14 at 3 24 21 PM" src="https://user-images.githubusercontent.com/16947266/127166376-fa4c8b30-b584-4091-962b-467c92024e6b.png">

**Comment by cd155** [comment]
I am not sure which way is best for reviewing html file or tex file.

@smiths Here is the update for the double pendulum theory
https://github.com/JacquesCarette/Drasil/blob/updateDblPendulumThoery/code/stable/dblpendulum/SRS/DblPendulum_SRS.tex
https://github.com/JacquesCarette/Drasil/blob/updateDblPendulumThoery/code/stable/dblpendulum/Website/DblPendulum_SRS.html

**Comment by smiths** [comment]
@cd155, is there currently an issue for me to review the physics of the two pendulum examples?  If so, can you point me to it.  If not, can you please create an issue for that purpose.  The current issue is closed, so it isn't really useful for the review purpose.

**Comment by cd155** [comment]
@smiths Thanks for the notice, I will create the issue.
