### ISSUE TITLE
PDFs for drasil-lang type dependencies

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2620]
I have pushed the pdf files in the branch `addingTypeDependencyGraph` under the `People/Anthony/Type_Dependency_Graphs` folder. In that folder, there are two different folders with the pdfs inside (along with all the `.dot` files).
Here is the pdf including low-level type dependencies:
https://github.com/JacquesCarette/Drasil/blob/a3cf83b149242f8b281a2418ada0522d0e9f23c8/People/Anthony/Type_Dependency_Graphs/JoinedTypes/June_18_2021/drasil-lang.pdf
And here is another one with separated low-level dependencies (a little bit cleaner):
https://github.com/JacquesCarette/Drasil/blob/a3cf83b149242f8b281a2418ada0522d0e9f23c8/People/Anthony/Type_Dependency_Graphs/SeparatedLowLvlTypes/June_18_2021/drasil-lang.pdf
The autogen ones will probably look like the first one, but I figured I could separate it for now so it is easier to read. Some of the nodes are still separate from the entire graph, but that is probably because I didn't count types defined with `newtype` or `type`. The autogen graphs will though.

For the first graph:
The dotted lines signify that the tip of the arrow could contain the tail type, but may not have to (it is either a `Maybe type` or it is using constructors). Coloured nodes are for those that are defined. 

For the second graph:
The separated low-level graph should have separate nodes for `Maybe types` and will use a solid line instead. The dotted lines are just for type constructor values.

Please let me know anything I could improve/any changes I should make.

**Comment by Ant13731** [comment]
Okay, I see. I've updated the main pdf and `drasil-lang.dot` files so that `Document` is now on top. Should I change the dotted lines for the manual files, or just apply the fix to the autogen graph script when I get to that point?

Sounds good. I'm planning the script to make each datatype its own file, then to combine them into the needed files with the m4 command and a `.m4` file in a bash script. This way, we should be able to group the parts we want (and I think `graphviz` will group `subgraphs` together so it should hopefully be neater)

**Comment by JacquesCarette** [comment]
Re: dotted - just autogen.

You might want to consider [this Haskell package](https://hackage.haskell.org/package/graphviz-2999.20.1.0/docs/Data-GraphViz.html) instead of resorting to m4?

**Comment by Ant13731** [comment]
I checked out the package briefly but it doesn't really seem to work with what I've been trying to do (I'm not actually recording all the .dot information at once. I think the program only records and prints one drasil package at a time). I'm not sure how to record the information, but if I could do that, then maybe the packages would work.

It might be easier (with what I have now) to just use haskell's append mode to create the package document and print out everything there at the same time (instead of using m4 on it afterwards). The script itself will now compile but there's a view variations of type definitions that I haven't accounted for yet, so some .dot files look weird or don't work.

**Comment by JacquesCarette** [comment]
Ok.
