### ISSUE TITLE
Double Pendulum: Organization of the document

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2633]
In the introduction for the double pendulum, add a section about the organization of the document.

**Comment by cd155** [comment]
The following will be added to Organization of Documents

_"The organization of this document follows the template for an SRS for scientific computing software proposed by koothoor2013 and smithLai2005. The presentation follows the standard pattern of presenting goals, theories, definitions, and assumptions. For readers that would like a more bottom up approach, they can start reading the instance models and trace back to find any additional information they require._

_The goal statements are refined to the theoretical models and the theoretical models to the instance models."_

**Comment by JacquesCarette** [comment]
Sounds good to me. But I think @smiths should review.

**Comment by smiths** [comment]
Yes, the proposed text is fine @cd155.  This is the text that we use in the other examples.
