### ISSUE TITLE
`Ch` constructor should know if a term should be titleized

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2635]
Working off of #2489, one issue I was also having (that just happened to pop up in the same bit of code) was the need for duplicate titleized version of combinators. For reference, here are combinators with "and" (both normal and titleized version).
```Haskell
and_ :: (NamedIdea c, NamedIdea d) => c -> d -> NP
and_ t1 t2 = nounPhrase''
  (phrase t1 `S.and_` phrase t2)
  (phrase t1 `S.and_` plural t2)
  CapFirst
  CapWords

and_TSP :: (NamedIdea c, NamedIdea d) => c -> d -> NP
and_TSP t1 t2 = nounPhrase'' 
  (phrase t1 `S.and_` plural t2)
  (phrase t1 `S.and_` plural t2)
  (Replace (atStart t1 `S.and_` plural t2))
  (Replace (titleize t1 `S.and_` titleize' t2))
```
These really shouldn't be needed, as the first one contains all the information needed to display the a `NamedIdea`. So I dug a little deeper, and I think I found the cause. In the instance declaration for `NP` as a `NounPhrase`, the sentence cases and title cases are defined as follows:
```Haskell
  sentenceCase n@(Phrase _ _ r _)   f = cap (f n) r
  titleCase n@(Phrase _ _ _ r)      f = cap (f n) r
```
And the `cap` function:
```Haskell
cap :: Sentence -> CapitalizationRule -> Sentence
cap _ (Replace s) = s
cap (S (s:ss)) CapFirst = S (toUpper s : ss)
cap (S s)      CapWords = capString s capFirstWord capWords
cap (S s1 :+: S s2 :+: x) r = cap (S (s1 ++ s2) :+: x) r
cap (s1 :+: s2) CapWords = cap s1 CapWords +:+ capTail s2
cap (s1 :+: s2) CapFirst = cap s1 CapFirst :+: s2
cap a _ = a
```
This works for all sentences that are made using the `S` constructor, but falls apart when combining concepts together. This is because `cap` doesn't account for the `Ch` `Sentence` constructor, which is used in concept-level combinators. I'll illustrate the process using an example with the terms `terminology` and `definition`. Our end goal is to display `Terminology and Definitions`:
```Haskell
--Combine them:
tAndD = terminology `and_` definition

--Then, we need the title case, so we call `titleizeNP`. 
--This breaks down into the `titleCase` method defined in the `NounPhrase` class (shown above).
-- Which then calls the `cap` function and breaks down as follows:
titleizeNP tAndD = cap (pluralNP tAndD) CapWords
                = cap (pluralNP (terminology `and_` definition)) CapWords
                = cap (phrase terminology +:+ S "and" +:+ plural definition) CapWords
                = cap (Ch TermStyle terminology +:+ S "and" +:+ Ch PluralTerm definition) CapWords
```
So a possible problem lies in the `cap` function, which doesn't know how to deal with a `Ch` constructor.

Two possible ideas for a fix could be:
-  allow `Ch` to take in a `CapitalizationRule` so that the printers could know whether or not to capitalize a term when the term is being looked up in the database. So then its constructor would become:
    ```Haskell
    Ch :: SentenceStyle -> CapitalizationRule -> UID -> Sentence
    ```
- change `SentenceStyle` to accept `CapPluralTerm`, `CapTermStyle`, and `CapShortStyle` in addition to the existing constructors (shown below)
    ```Haskell
    data SentenceStyle = PluralTerm
                   | SymbolStyle
                   | TermStyle
                   | ShortStyle
    ```

**Comment by JacquesCarette** [comment]
I think the intent of the `SentenceStyle` was for a different purpose. So the first fix seems best.

**Comment by JacquesCarette** [comment]
All excellent ideas. Let's analyse each:
1. would work, but is slightly dangerous, as it would allow `CapNone` when it's not appropriate
2. would work. But mixes style and capitalization
3. works. And is "more meaningful" in that it is more precise.

We have our winner!

**Comment by Ant13731** [comment]
I'm just starting out on this and I already have some import cycles as `CapitalizationRule` takes a `Sentence` (and `Sentence` would need a `CapitalizationRule`. Making a different capitalization rule type could alleviate this, as I'm not sure we want to allow the `Replace` constructor to exist in `Ch` in the first place. So it could be a completely different type, as such:
```Haskell
Ch :: SentenceStyle -> TermCap -> UID -> Sentence

data TermCap = Cap  | NoCap | AllCap
```
This might be even more precise, since `CapWords` doesnt really make sense if `Ch` only resolves single-word terms at a time. And it also blocks users from using the `Replace` constructor to overwrite the term.

Would this change be good?

**Comment by JacquesCarette** [comment]
Naming the kinds of capitalization is good.
