### ISSUE TITLE
Git2Know 

### ISSUE THREAD

**Issue by Awurama-N** [JacquesCarette/Drasil#2644]
Here is the current state of the [git2know.pdf](https://github.com/JacquesCarette/Drasil/files/6742084/git2know.pdf)
I was unsure about keeping some things in it because they seem simple now, but knowing these things/ having this when i started I think would have been very helpful.

I took out things about setting up VSCode itself as i realise not everyone might be using that. 
I also wasn't sure whether to add things about Haskell code itself but it seems to veer off a bit from the point of this doc (also because Learn you a haskell exists.)
I also wasn't sure whether to keep things in about navigating Drasil itself.

Please let me know if there is anything you think i should add or take out.

**Comment by Ant13731** [comment]
I checked out the pdf and I think that would've helped me a lot as well! To be honest, I didn't even know some of those keyboard shortcuts existed until I read it. Although some of mine do slightly different things. I can also add in a Windows git section (more focused on installing instructions, some limitations, etc.). I'm not sure if Mac OS users need to install git, but we could also add a section for that (and linux systems - I think its only one command).

It might also be nice to make an example of how to set up a VSCode workspace (including extensions, download links, and maybe put the VSCode specific commands there). I could help share what I learned here as well.

Personally, I think a detailed procedure for getting a workplace started and navigating Drasil would be nice as well (and we could combine our experiences with this too). It can be an optional resource for future students to look at so they can jump right in. We could also include a step for when they should start reading learn you a haskell, and even give some relevant examples in the code (especially the monad stuff). Is there a branch that the git2know source file is on? I could contribute there.

**Comment by balacij** [comment]
Indeed, it's a really good document! I think the simple things should stay, they're probably the most important for getting started like you mentioned :smile: 

I've started importing some of my Haskell installation notes and building out notes over on the `New Workspace Setup` wiki page too. It's still very rough, but it's a start. https://github.com/JacquesCarette/Drasil/issues/2375#issuecomment-870957129 / https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup
Please do feel free to contribute to this as well!

**Comment by Awurama-N** [comment]
Okay Yes Thank you Both!

@Ant13731 Your contributions would be very appreciated. There's no branch with the doc yet, but I could send you the word doc for now till @smiths & @JacquesCarette give the go ahead.
And I agree with the things you recommend we add, I also think adding the process of setting up VSCode would be very helpful.

@balacij Thanks! I'll work on adding your haskell installation notes & work placw Set up too.

**Comment by JacquesCarette** [comment]
Yes, please put this on the wiki instead of as a Word doc. Having multiple pages (yay, hyperlinks!) where, for example, the VSCode-specific stuff could live & be linked to, would be a good way to organize things.

**Comment by smiths** [comment]
Yes, moving from Word to the wiki is a great idea.  Yes, the instructions from @balacij should be merged with those by @Awurama-N.

Great work @Awurama-N.  To the Wiki version of your git advice, please address the following:

- add hyperlinks to external resources on git
- to your list of common commands, add `git add -u`
- the VS Code shortcuts in your document will likely fit better on the wiki page for @balacij 's instructions.
- DON'TS should be DONT'S :smile:
