### ISSUE TITLE
Implementing custom text references

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2653]
Now that we can use intext references (with the `namedRef` function), we should start implementing them into the examples. Some examples use their own references but many are pulled from `docLang`. This issue is to keep track of which examples/sections still need to be done.

For individual examples:
- [ ] Pendulum
- [ ] GamePhysics
- [ ] GlassBR
- [ ] HGHC
- [ ] NoPCM
- [ ] PDController
- [ ] Projectile
- [ ] SSP
- [ ] SWHS
- [ ] Template

From `docLang`:
- [x] (maybe) DocLang/SRS.hs
- [x] DocumentLanguage/Definitions.hs
- [x] Sections
    - [x] AuxiliaryConstants.hs
    - [x] GeneralSystDesc.hs
    - [x] Introduction.hs
    - [x] ReferenceMaterial.hs
    - [x] Requirements.hs
    - [x] SpecificSystemDescription.hs
    - [x] Stakeholders.hs
    - [x] TableOfAbbandAcronyms.hs
    - [x] TableOfSymbols.hs
    - [x] TableOfUnits.hs
    - [x] TraceabilityMandGs.hs
- [x] (maybe) DocumentLanguage.hs

**Comment by smiths** [comment]
Great idea @Ant13731 and nicely organized.  This seems like an issue that others can help with?  Maybe @Awurama-N can help by checking off some of the items on your list?
