### ISSUE TITLE
Add back `OneOf` Value constraints

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2655]
Related to: https://github.com/JacquesCarette/Drasil/issues/2646#issuecomment-871564379 , https://github.com/JacquesCarette/Drasil/issues/2646#issuecomment-873109412 , and #2118 

> The fact that removing those constraints does not alter stable feels like a bug. That information should be used, but apparently it's not.
> So I think the pragmatic thing to do is to remove `Enumerated` but create two high-priority issues to bring the information thus cut out back. Note that a first hack of bringing the information back could be display-only.  #2118 is hard because it tries to deal with code generation, and that design is highly non-trivial. So the high-priority would be to get things back at least for display.

_Originally posted by @JacquesCarette in https://github.com/JacquesCarette/Drasil/issues/2646#issuecomment-873109412_

**Comment by balacij** [comment]
As a reminder, this ticket is about building constraints on quantities, specifically 'this quantity must be one of these values' constraints.

@NoahCardoso To re-iterate our intended work:
1. You have prototyped (are prototyping?) what the 'generated' code _should_ look like for constraints that bind variables to one of many possible values. After this work, we can dissect what is going on and what we really want to be saying (and having generated for us) when we define these constraints.

As of right now, we decided that this should involve sets in the generated code, but we can come back to it later to make sure.

As such,
2. We have a critical piece missing: sets in `*Expr`. We will need to bridge this gap in all `Expr`s and in `drasil-gool` (@B-rando1 can assist with GOOL :slightly_smiling_face:).
3. We can finally define the constraint as something that 'means' `x \in {... , values, ...}`.

**Comment by NoahCardoso** [comment]
Here are the prototyped examples in Python and Java and how I think they should look like
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/3a7553dc-b885-4a01-950f-034c72c1f63f)
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/fb27e477-84ce-44c1-870b-13d5cd038067)

**Comment by JacquesCarette** [comment]
It all looks good - except that enumerated floats are a bad idea. Once in a while, things will go wrong. I would much rather use integers (i.e. multiply everything by 10) for the internal storage of these numbers.

**Comment by NoahCardoso** [comment]
This is what I have so far. I'm currently just working on making sure it is displayed properly. How should I go about creating sets in GOOL? I have been able to get the Python example working with sets as a constraint but I have not yet added to GOOL. I assume I would need an `isIn` operation as well as defining `Set`s

![image](https://github.com/user-attachments/assets/458cfa82-d5f9-4af6-ac5b-d1f7c637391e)

I have a WIP branch open #3846. It's pretty rough currently but I will clean it up once I can get things working.

**Comment by NoahCardoso** [comment]
### Update
I have got `set`s and the `in` operation working in Python. Within the next day or so I should be able to get it working in the other languages.
![image](https://github.com/user-attachments/assets/4ea0a988-523f-4019-bfc5-f2e5252ac184)

**Comment by NoahCardoso** [comment]
Java is now working, I also changed Python to use the `set` function rather than using the `in` operation as I need the element to be on the left side.
![image](https://github.com/user-attachments/assets/6b02277f-d2c7-4db9-95d4-03e6bb70daf0)
![image](https://github.com/user-attachments/assets/cb59d64e-ce7d-4754-96f4-78629224d892)

**Comment by JacquesCarette** [comment]
This is looking good. My C++ is too rusty for me to offer advice on which API to use. I'd have to use the same tools you have to investigate (i.e. SE, google, chatGPT, etc)

**Comment by balacij** [comment]
FWIW, if a language has some missing features, and we can polyfill them with our own generated code, I see no reason why we shouldn't do that. For example (and I'm not saying we should strive for perfection in this PR, but this is a hypothetical follow-up), we can define our own `contains` operation in a `drasil_polyfill` shared library.

```c++
template <typename E>
bool set_contains(const std::set<E>& set, const E& element) {
    return set.find(element) != set.end();
}
```

At least for now, I think you're making the right choice in looking to move the set into a variable.

**Comment by balacij** [comment]
Reading that file I sent now, I think we should prefer a `std::set` over a vector at least, for readability. The performance considerations of set v vector would be preemptive. So, I'd call set the correct data type to use now. I just wanted to make sure because I found the set API to be quite lacking (no `contains` seems quite odd to me).
