### ISSUE TITLE
Wiki: Custom SideBar

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2664]
The current side bar in the wiki sorts alphabetically, but I think we can create a [custom sidebar](https://docs.github.com/en/communities/documenting-your-project-with-wikis/creating-a-footer-or-sidebar-for-your-wiki) using Markdown for the Wiki to organize the pages a bit as they grow.

We could group pages together using markdown lists, similar to: 

![image](https://user-images.githubusercontent.com/1627302/124963063-5cacbe00-dfed-11eb-98a7-030c4acb597e.png)
(from https://github.com/adriantanasa/github-wiki-sidebar/wiki, but we don't need to use their package)

I think a decent starting point would be:

```
* [Getting Started](...) 
  * New Workspace Setup / Installation
  * all contributing links for various kinds of contributions
* [Definitions] 
  * Major definitions, grouped by their categories on pages
* [Readings]
  * ... by groups? 
* [FAQ]
* [Misc.]
  * ... catch-all?
```

Any thoughts/suggestions on this?

( I think this is something that everyone can contribute to, so I won't assign anyone in particular, but please do contribute! )

**Comment by Ant13731** [comment]
I think we could also add a tab for Documentation and Design. I added two wiki pages on `Combinators` and `References` so far. It might be nice to have a page for dependency graphs, chunk design, and section design.

**Comment by balacij** [comment]
Good idea!

Perhaps something more like:
```
* [Home](https://github.com/JacquesCarette/Drasil/wiki)
* [Getting Started]() -- new landing page
  * [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup)
  * [Git2Know](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil)
  * [Contributer's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide)
  * [Creating Your Project in Drasil](https://github.com/JacquesCarette/Drasil/wiki/Creating-Your-Project-in-Drasil)
  * [Debugging](https://github.com/JacquesCarette/Drasil/wiki/Debugging-in-Drasil)
* Documentation <- landing page for a list of docs if we have a lot
* Design <- landing page for a list of design docs if we have a lot
* Readings <- page w/ a list of readings
* Misc.
  * ... catch-all
```

We can discard many of the "in/for Drasil" suffixes from the titles of the pages too.

Are any of those documentation and designs already on the drasil website? If not, should any of them be there first?

**Comment by Ant13731** [comment]
I think only the haddock docs are on the drasil website. They're a little more in-depth than the haddock docs and more meaning-oriented then technically documented, so I'm not sure if we want them there.

I like the organization of that table of contents.

**Comment by JacquesCarette** [comment]
All superb ideas, thank you.

**Comment by Ant13731** [comment]
I implemented a first-pass for a sidebar. Should we have a section for information that is starting to get outdated but may still be important?

**Comment by balacij** [comment]
Ah, thank you @Ant13731! I think we can close this ticket then, and improve the Sidebar as needed later. For the information that's getting outdated, we should probably create tickets to update them. There's a few pages that carry redundant information -- we can probably do a few passes of reorganizing to make sure everything on the pages are relevant to them.
