### ISSUE TITLE
Move some functions out of `drasil-docLang/Drasil/DocumentLanguage.hs`

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2683]
I think some of the functions currently in `DocumentLanguage.hs` could be moved out to their respective files in the `Section` folder. Namely, the functions that do not get the sections of an SRS. For example, these are functions to make an introduction to a section:

https://github.com/JacquesCarette/Drasil/blob/4b9ad0a3016fecb3c7a2aa82ab142f9e805b5cc8/code/drasil-docLang/Drasil/DocumentLanguage.hs#L176-L208

But don't actually make the section themselves like the rest of the functions in the file:
https://github.com/JacquesCarette/Drasil/blob/4b9ad0a3016fecb3c7a2aa82ab142f9e805b5cc8/code/drasil-docLang/Drasil/DocumentLanguage.hs#L227-L350

Moving these out of `DocumentLanguage.hs` could help with organization and quickly seeing which sections are made by which functions.

**Comment by JacquesCarette** [comment]
Sounds good, please go ahead.
