### ISSUE TITLE
Add LaTeX installation notes to `New Workspace Setup`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2685]
We currently have a bit discussed in the contributer's guide, but it would be good to add some basic installation notes.

Also, MikTeX appears to be a really good turnkey solution for Mac + Windows, but Linux repos generally have up-to-date TeX packages.

**Comment by balacij** [comment]
@Ant13731 I added a bit of notes on [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup#latex) page and I remembered you [experienced issues](https://github.com/JacquesCarette/Drasil/issues/2437) with getting `MiKTeX` to work properly on Windows, so I added a bit of notes there on that. Is there anything you think I missed there?

Is there anything else we can add for the LaTeX installation notes?

**Comment by smiths** [comment]
The notes for helping new contributors are great!  I worry a bit that they will need to be maintained, since popular packages change over time.  Even if the notes get a bit out of date, they will still form a great starting point.

For the Mac, I'm not sure that MikTex is that common.  I didn't even know it was available for the Mac.  :smile:  (I just googled to confirm.)  It seems like `homebrew` has become popular for Macs.  I've switched from macport to `homebrew` and I've found it fairly easy to use, including for installing LaTeX.

**Comment by Ant13731** [comment]
I just looked through the updated wiki, and I think its really thorough and well explained! I don't think there's anything else to add for the LaTeX stuff.

**Comment by balacij** [comment]
Thank you both!

Regarding Mac, I think that's a great idea. Do you have a list of packages that we need for homebrew? We can add it as the preferred method for Mac and leave MiKTeX as a secondary option.

Regarding the instructions potentially going out of date, I didn't consider that. Hopefully it will be a while before any of them go out of date. I installed NixOS on my laptop recently, if I figure out how to write nix expressions properly, we could potentially have a `Drasil.nix` package where installing everything will be modular and [as easy as `nix-shell Drasil.nix`](https://nixos.wiki/wiki/Development_environment_with_nix-shell). If this is desired and more people use the Nix package manager, then it may be good thing.

**Comment by smiths** [comment]
@balacij can you please add the following instructions for LaTeX on a Mac:

For the GUI version of Maktex use: `brew install --cask mactex`.  For the non-GUI version use: `brew install --cask mactex-no-gui`.  The GUI version is useful if you would for those that need the tex file editor TeXShop.  The GUI version also installs LaTeXiT, TeX Live Utility, and BibDesk.

I agree that we can close this issue after the above Mac instructions are adapted to fit with the existing instructions.

The `Drasil.nix` idea is really nice.  I know at one time @JacquesCarette was using Nix, but I think he stopped using it.  We should confirm that, and if he did discontinue using it, learning why would be helpful.

**Comment by balacij** [comment]
Just added it, thank you @smiths! :smile: I think the doc is shaping up quite nicely!

Ah, I wasn't aware of that. Sounds like a plan!

**Comment by smiths** [comment]
Thank you @balacij.

**Comment by JacquesCarette** [comment]
I used nix (but not NixOS) for a while, but it was too early, and require more investment of my time than I was willing to give it. It's still a really good idea.
