### ISSUE TITLE
Changing the representation of Section

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#2693]
Currently, we use ``Section`` for sections and subsections, which makes the structure recursive. 
```haskell
-- | Section Contents are split into subsections or contents, where contents
-- are standard layout objects (see 'Contents').
data SecCons = Sub Section
             | Con Contents
-- | Sections have a title ('Sentence'), a list of contents ('SecCons')
-- and a shortname ('Reference').
data Section = Section 
             { tle  :: Title 
             , cons :: [SecCons]
             , _lab :: Reference
             }
makeLenses ''Section
```
To make it not recursive, we need to use a different data for subsections and add level information. I was thinking of something like this:
```haskell
data Section = Section Title [SecCons] Reference
data SecCons= 
     Sub Depth Title [Contents] Reference
   | Con Contents
```
We will need to use ``SecCons`` instead of ``Section`` to represent subsections and add level information to it. It works in a similar way as the printer currently does, maybe it would be more straightforward to wrap the sections and print headers based on the level. But the original structure makes more sense to HTML. Not sure whether should I modify the ``Section`` to make it work in all types of documents or introduce a new type of ``Section`` for notebook.

I'm also considering the possibility of introducing a new type in ``SecCons`` for cells because a markdown cell seems to be something between ``Sub`` and ``Con``. However, it also seems unnecessary because I think a cell could be either a ``Sub`` or a ``Con``. 

@balacij @Ant13731 Any ideas and suggestions will be greatly appreciated!

**Comment by Ant13731** [comment]
I think the new idea for sections could work out really well. I'm not sure if this would be able to work in a notebook, but would we be able to make `SecCons` recursively hold information? Maybe something like:
```Haskell
data Section = { tle  :: Title 
             , cons :: [SecCons]
             , _lab :: Reference
             } -- leaving as a record for the lens to the reference
data SecCons = 
     Sub Depth Title [SecCons] Reference
   | Con Depth Contents -- might need to know this depth but not sure
-- Would it be able to flatten itself before being put into a Section?
-- That way we wouldn't need to know the depth?
```
That way the sections themselves are not recursive (and would match up with cells), but we can still keep the idea of recursively adding content (which might match with HTML nicely).

**Comment by balacij** [comment]
It sounds like you specifically want to remove the recursive structure, but I'm not quite sure I understand why. Can you please explain?

**Comment by tingyuw** [comment]
@Ant13731 I have thought about making ``SubCons`` recursively, but doesn't it work only if we don't have another subsection inside a subsection(? What seems best for the notebook is to flatten everything before we put into a Section, so the only thing the printer need to do is printing. I think maybe making ``SubCons`` recursive and ``Section`` doesn't is a compromise way. I'm not sure whether it works well in a notebook but can give it a try!

@balacij Sure, I'm sorry that I didn't explain it first. I was trying to separate the contents in cells in a smaller unit. Cells are separated by (main)sections currently in notebooks which are still too big to maintain. Because the structure is recursive, I can't "cut" the contents properly into a smaller unit. I think it might be possible to do this in the printer but in that case the printer will do too many works. Dr. Carette said the best way might be changing the representation of ``Section`` and make it not recursive.

**Comment by balacij** [comment]
No worries, thank you! How do you want to cut the contents? Do you want the content lists to have no subsections contained within them? Would laying out the entire document structure into a single flat list of `Either Contents SectionHeader` be approximately what you want (where a `SectionHeader` is a  `Depth`, `Title`, and a `Reference`)?

**Comment by Ant13731** [comment]
Ooh I see what @balacij is saying. Should the `Contents` side also hold a depth so the printer could do something like this?
```Haskell
{- SectionHeader 0 Title Reference
    Con 0 Contents
         Sub SectionHeader 1 Title Reference
         Con 1 Contents
               Sub SectionHeader 2 Title Reference
               Con 2 Contents 
         Sub SectionHeader 1 Title Reference
         Con 1 Contents 
```

**Comment by balacij** [comment]
Would the content cells generated change depending on the depth? I think that this work primarily depends on how we want to split the document into the cells.

**Comment by JacquesCarette** [comment]
My instincts tell me that having the depth in both `Sub` and `Con` will be most useful. Certain computations won't depend on it, but some will.

**Comment by balacij** [comment]
@tingyuw Can you please also check on the status of this ticket?

**Comment by tingyuw** [comment]
As stated in my report, we can consider creating new data types for lesson plans when we have more understanding of them. Currently, the non-nested structure of lesson plans, along with the use of layout objects, meets our requirements without making changes to the SRS structure. We can focus on enhancing the printer and ``LayoutObjs`` (also mentioned in my report) to improve notebook printing in the future.
