### ISSUE TITLE
Make a copy of the current pendulum example and rename it to single pendulum

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2694]
As discussed, we ideally want to have a family of pendulums, and it could solve the n-pendulum problem. The current pendulum example is very close to a single pendulum example.

In this ticket, 
1. I will make a copy of the current pendulum.
2. rename one of them to the single pendulum.

Side effect:
1. Change the name to a single pendulum
If I rename one of them to a single pendulum, I think there are some additional works I need to do. Currently, the pendulum example uses name and directory of `DblPendulum`, but it actually a single pendulum example. After renaming it to `SglPendulum`, all the references to `DblPendulum` need to change, includes package.yaml, `import` module in each .hs file, stable folder, code/website, and code/Makefile.

To the best of my knowledge, I think this is what I need to do. @balacij Is there anything I missed?

relate to
#2692

**Comment by Ant13731** [comment]
The `drasil-website` folder might also need to be updated to include the new example, but I think I can just add on the changes when you make your pull request for it (the organization of the website is still more messy than I'd like, but feel free to change it if you want to give it a try). https://github.com/JacquesCarette/Drasil/blob/163a45889cbba5f43f37d468fe179e09f75e1df7/code/drasil-website/Drasil/Website/Example.hs#L55-L95

**Comment by balacij** [comment]
Good catch @Ant13731!

> After renaming it to SglPendulum, all the references to DblPendulum need to change, includes package.yaml, import module in each .hs file and stable folder.

As long as you do this with a search/`grep` on the repo as well, as I'm sure there will be other spots (e.g., READMEs).

You might also be able to start factoring out some of the common things of both, or create a Pendulum knowledge library that they both share and depend on.

**Comment by JacquesCarette** [comment]
When you do this, take a good look at SWHS and NoPCM - they share a lot of content. So while they are 2 examples, they are cross-linked.  If you look at the [dependency graph](https://jacquescarette.github.io/Drasil/graphs/drasil-example.pdf) of `drasil-example` (and zoom in a lot!) you will see that the modules for these are inter-linked.  This is a good thing.

**Comment by cd155** [comment]
@JacquesCarette Base on NoPCM and SWHS (NoPCM is a simple example of SWHS), the SinglePendulum will be a simple version of DoublePendulum. The DoublePendulum will be more like an independent example, and it will not link to SinglePendulum. However, the SinglePendulum uses some functions from DoublePendulum.

**Comment by JacquesCarette** [comment]
As long as they end up being related, I don't really care about the exact direction.

**Comment by cd155** [comment]
@Ant13731 is there a way to test what I change the drasil-website/Drasil/Website/Example.hs file?

**Comment by Ant13731** [comment]
Yep! If you're on mac or linux, use `make deploy` or `make deploy_lite`. Unfortunately those don't work on Windows, but you can use `make website` to see if it will compile (the links won't work though).

**Comment by smiths** [comment]
@cd155, if you have a Windows machine, it might be worthwhile to install a virtual machine with Linux.  Challenges with Windows come up often enough that having a Linux alternative can come in handy.  We talked about creating a Linux VM in SE 2AA4.

**Comment by cd155** [comment]
@smiths thanks for the notice. I am currently mainly using MacOS. It makes sense to have a Linux in hand. I think @balacij actually use Linux system. My only problem with Virtual Machine is that my laptop usually will run out of space. :D

**Comment by smiths** [comment]
@cd155, the Mac OS should be fine.  Most Linux things have an equivalent, even if sometimes the syntax is different.  I also use a Mac.  I keep a Linux VM, but mainly for teaching purposes.  You are right about running out of space!  :smile:

**Comment by cd155** [comment]
@balacij in the recent change #2722, each example will have its own stack.yaml and package.yaml at their local folder. Is the stack.yaml(in example local directory) generate automatically? I created a new example, and only added package.yaml at its local directory. The example still runs without error. Should I manually add the stack.yaml?

**Comment by balacij** [comment]
Yes, each example and package should be buildable on their own (e.g., if you head into their directory, and run `stack build` respectively, it should compile). For that, we need to designate the local packages they depend on (via stack.yaml).

You can most likely just copy any `stack.yaml` of the other examples to get it working.
