### ISSUE TITLE
Double pendulum: add General System Description in SRS

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2699]
The current SRS does not include the section of General System Description. In this ticket, add the section of General System Description to the SRS.

Relate to
#2615
#2665 (missing hyperlink reference)
#2697 (missing hyperlink reference)

**Comment by cd155** [comment]
The following information will be added in double pendulum SRS.

![SystemContextFigure](https://user-images.githubusercontent.com/16947266/126416754-d73c482f-dfec-44c1-9b6a-b240d887d51b.png)
Figure 1

# 3 General System Description
This section provides general information about the system. It identifies the interfaces between the system and its environment, describes the user characteristics and lists the system constraints.

## 3.1 System Context
Figure 1 shows the system context of the software. The program can be viewed abstractly following the design pattern of Inputs → Calculations → Outputs. The user provides inputs, the system does the calculations and then provides the outputs to the user.

The responsibilities of each of the entities are listed below: 
- User Responsibilities:
  - Ensure the inputs are valid
- Double Pendulum Responsibilities:
  - Detect data type mismatch, such as a string of characters instead of a floating-point number
  - Do the corresponding calculations
  - Generate the graphs of angles of the rods
  - Display the graphs to users

## 3.2 User Characteristics
The end-user should have an understanding of high school Physics and Calculus, with knowledge of ordinary differential equations.

## 3.3 System Constraints
There are no system constraints for this project.

**Comment by cd155** [comment]
@smiths I mainly use the manual version of the double pendulum example, do you think that information could be added?

**Comment by smiths** [comment]
Yes, the addition of the general system description looks good.
