### ISSUE TITLE
Current web site deploy has broken links

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2701]
I clicked on the [package dependency graphs](https://jacquescarette.github.io/Drasil/#Sec:Dependency) link, and it didn't go anywhere.

**Comment by smiths** [comment]
I just checked this and it seems to work for me?

I clicked on the first link and it opened a pdf file.  The path to the file is:

https://jacquescarette.github.io/Drasil/graphs/drasil-build.pdf

**Comment by balacij** [comment]
I believe @JacquesCarette was referring to the "package dependency graphs" href from the Introduction?

There's also 2 other broken ones in the examples section:
* PDController's Python source code has miscapitalization of pdController in the href
* the `Template` example's SRS links -- do we generate anything for the template?

**Comment by JacquesCarette** [comment]
The link that I give above is supposed to zoom you down to the bottom of the page - from which the pdf files do open. But in Firefox and Chrome, it doesn't. The other link [Haddock](https://jacquescarette.github.io/Drasil/#Sec:Documentation) does work.

**Comment by smiths** [comment]
Got it!  You are right, your original link took me to the top of the page, not to the correct sub-section.

**Comment by Ant13731** [comment]
I've got the links working (their UIDs had a space between them so it only got the first part. Removing the space makes it work).
As for the PDController, I initially expected all the stable folders to be lowercase. For now I've hardcoded it with the correct capitalization, but I think #1686 will allow it to go back to normal. I'll make a note on that issue as well, just so the python link will work for now.

**Comment by JacquesCarette** [comment]
So these kinds of bug is what we'd like to avoid. Not repeating strings, **ever** would already help. We want a unique source for all of these things. Then a typo will lead to it being wrong uniformly *everywhere*, which will be caught quickly.
