### ISSUE TITLE
Add `shell.nix` configuration for developers working on Drasil

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2702]
We would want to have the Nix expression install all CLI tools and compilers necessary for Drasil and Drasil-generated software.

It appears that Nix works well with Mac (many users seem to use it), it works very well on Linux, and it appears to run well on Windows under WSL.

The `shell.nix` name is the default name that a `nix-shell` command looks for when searching for a Nix expression file to create a shell environment.

We need:
* Stack v2.5.1
* `inkscape`
* Maybe `imagemagick`
* `graphviz`
* `texlive.combined.scheme-full`
* Fonts: `lmodern` & `lmmath`

**Comment by smiths** [comment]
I did a quick google to learn more about `nix-shell`.  I found a nice post on [Nix Setup for MacOS](https://wickedchicken.github.io/post/macos-nix-setup/).  The idea of having a way to temporarily install packages is nice.  I worry about performance if the shell needs large packages, but if pre-built binaries are used, it probably doesn't take that long.

I use homebrew on my Mac, and the above article hasn't convinced me to change as of today.  However, I look forward to learning more about Nix.  :smile:

**Comment by balacij** [comment]
Great find! That's a great article! To add to it, one of my current issues with Nix's way of package management is that they don't quite make it easy (enough?) to switch package versions yet. I wanted to downgrade my Stack version from the newest 2.7.1 to 2.5.1 for Drasil and I ended up needing to pin a whole package list from which I grab the single old stack version from. Thankfully   one Nix user [created a tool](https://lazamar.co.uk/nix-versions/?package=stack&version=2.5.1&fullName=stack-2.5.1&keyName=stack&revision=046f8835dcb9082beb75bb471c28c832e1b067b6&channel=nixpkgs-unstable#instructions) to help community members.

With NixOS, I've only installed pre-built binaries using their default cache servers, so I hope that just the `nix` package manager would use the same caches. The `nix-shell` commands take a bit of time on the first run to download all of the packages, but after the first run, it's _almost_ instant. Hopefully it goes well!

It also seems that many users have glowing reviews of the [in-beta Nix Flakes](https://nixos.wiki/wiki/Flakes), but I'm not sure if we should try it yet.

**Comment by smiths** [comment]
Nix Flakes does sound good, but your instinct is likely correct that we shouldn't be too eager to adopt the very latest technology.  It is encouraging to see the development of tools that can facilitate generating software that knows its own dependencies and can install them into its own environment.
