### ISSUE TITLE
Is GraphViz a new dependency?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2707]
It seems we use `dot` with the default `make` now. Is GraphViz required for each `make` run? Are we able to get a partial run excluding the graphviz graphs?

If GraphViz is a new dependency, we should also add a section to the Wiki's New Workspace Setup page.

**Comment by JacquesCarette** [comment]
There should definitely be useful targets for doing local development that doesn't depend on GraphViz. It doesn't necessarily need to be raw `make`, but it should still be possible!

**Comment by Ant13731** [comment]
Ah, okay. I can write up in the wiki for it and look into making a new target for a non-graphviz form of the SRS.
