### ISSUE TITLE
Split up example into packages with libraries executables

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2708]
So that we can import the examples as libraries for the drasil-website generator.

Maybe we can get away with using a manually written Cabal file for `drasil-example` (with multiple libraries in said Cabal file) instead of creating a package.yaml/stack.yaml file for each example...

**Comment by balacij** [comment]
It appears that this ticket is a bit finicky. If we want to have a "library and an executable" in a Haskell project, Cabal and Stack want us to separate the directories that they're held in (as in, having an internal library source directory and a separate internal "application"/executable source directory).

Do we want to keep our general source directory structure as is? e.g., we commonly keep our source code in the same directory as the `.cabal` file, but Cabal and Stack seem to prefer keeping "library" code in an embedded directory and the "application"/executable code in another as well.

For example, we have `drasil-example` structured as:
```
Drasil/
    DblPendulum/
      ...
    GlassBR/
      ...
    ...
package.yaml
README.md
stack.yaml
```
but if we want to split up the examples, Cabal+Stack tend to want something more like (1):
```
app/
   Drasil/
     DblPendulum/
       Main.hs
     GlassBR/
       Main.hs
     ...
lib/
  Drasil/
    DblPendulum/
      <exposable code> ...
    GlassBR/
      ...
package.yaml
README.md
stack.yaml
```
^ where we have 1 "focal" `drasil-example` library containing all code from all executables, and multiple executables. We can forgo the `lib/` folder containing the "library" code, but this would create funky names and "excluded module" warnings for Cabal.

Alternatively (2), splitting up our `drasil-example` into multiple sub-projects:
```
drasil-example/
  drasil-example-dblpendulum/
    app/...
    lib/...
  drasil-example-glassbr/
    app/...
    lib/...
  ...
...
```
With each sub-project containing its own stack.yaml, project.yaml, and `.cabal` file.

**Comment by JacquesCarette** [comment]
I prefer option (2), but:
```
drasil-example/
  dblpendulum/
    app/...
    lib/...
  glassbr/
```
