### ISSUE TITLE
`New Workspace Setup` wiki page: Add note about Windows Unicode Registry fix as an alternative to `chcp`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2719]
We have a note about unicode support right now, but I noticed there's also a [WindowsFix](https://github.com/JacquesCarette/Drasil/tree/master/WindowsFix) fix that appears to be a bit more permanent. We should also note this on the Wiki.

@Ant13731 / @tingyuw I _believe_ you both develop on Windows? If so, have either of you attempted this registry fix?

**Comment by Ant13731** [comment]
I haven't tried that, but I don't think its needed (as much, maybe not at all)? I was able to run `make` and `make tex` without needing to run `chcp 65001` first. I think each Drasil example sets the local encoding to UTF8 anyways, so it might just work right out of the box. I haven't looked at the generated examples in depth, but I haven't gotten an error when I wasn't using `chcp 65001` either.

**Comment by balacij** [comment]
Oh, that's great!

In that case, I don't think we will need to add anything further than what is already in it. Thank you!
