### ISSUE TITLE
Get information for website based on examples

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2723]
A couple things to complete for this issue:
- [x] change folder names to be lowercase everywhere (under `build`, `datafiles`, `traceygraphs`, and `deploy` especially. (related to #1686)
- [x] make sure the `directoryNames` and `resourcePaths` for each example are correct given the new capitalization of folders (all lowercase)
- [x] start work on hooking info from the examples themselves rather than hardcoding the website (and make it more recipe-like)
- [x] Make some website sections clearer (DataTable and Package dependencies)
- [x] Remove unneeded manual references
- [x] Get Haddock docs for website

**Comment by Ant13731** [comment]
@balacij, is there a way to import the `Main.hs` files from each example into the website? The `Body.hs` files all have different module names so those work, but all the `Main.hs` files have the same `Main` module name.

I tried changing the module names to `ExampleName.Main` but then I get an error that the examples can't find the file in `ExampleName/Main`.

Using `import Drasil.DblPendulum.Main`, or `import Main` don't work, as the compiler says they both don't exist. However, when I just try and load up GHCi for the website, it asks me which package I would like to take `Main from`. Is it possible to distinguish between the main files. Maybe something in the `stack` arguments?

**Comment by balacij** [comment]
I placed the `Main.hs` file as an unexposed module, only in the executable. We can create a `Choices.hs` or `Artifacts.hs` file in the lib/ folder of each of them and place any information, that's currently only found in `Main`, in them, and then import them.

> Using import Drasil.DblPendulum.Main, or import Main don't work, as the compiler says they both don't exist. However, when I just try and load up GHCi for the website, it asks me which package I would like to take Main from. Is it possible to distinguish between the main files. Maybe something in the stack arguments?

If there is, I don't know of it. I think this is just the behaviour of GHCi but I might be wrong. What happens if we change back the module names of each `Main` file to the original `Drasil.X.Main`, expose them, and then import?

**Comment by Ant13731** [comment]
> If there is, I don't know of it. I think this is just the behaviour of GHCi but I might be wrong. What happens if we change back the module names of each Main file to the original Drasil.X.Main, expose them, and then import?

I get the following error when manually changing the cabal file:
```
dblpendulum   > Preprocessing library for dblpendulum-0.1.24.0..
dblpendulum   > Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.4.exe: can't find source for
dblpendulum   > Drasil\DblPendulum\Main in lib, .stack-work\dist\29cc6475\build\autogen,
dblpendulum   > .stack-work\dist\29cc6475\build\global-autogen
```
And this when changing package.yaml:
```
dblpendulum   > Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.4.exe: can't find source for
dblpendulum   > Drasil/DblPendulum/Main in app
```

>EDIT: What information is needed by the way? Perhaps depending on that, we just push it to other lib/ modules.

I really just need the code choices and code directory name (defined in Main.hs) and the system info (defined in Body.hs).

I also found that we can use `LANGUAGE PackageImports` but it still doesn't work. Is it possible to expose the main module and then use `import qualified "exampleName" Main as ExampleName`?

**Comment by balacij** [comment]
Would this work?
```
app/ 
  Main.hs  <- essentially just the Main function, invoking functions it imports from the lib, no declarations or otherwise new information
lib/Drasil/X/
  Body.hs
  ...
  Choices.hs <- new module where you move the information from Main.hs to
  ...
```

**Comment by Ant13731** [comment]
Yea, I think It would. Let me give it a try.

**Comment by balacij** [comment]
Sounds good, hopefully it works, let me know how it goes!

**Comment by Ant13731** [comment]
Okay, I think the new files worked pretty well! My most recent PR contains those changes if you want to take a look @balacij 

Thanks for your help!

**Comment by balacij** [comment]
Nice! I'm glad I could help!
