### ISSUE TITLE
Failing build - interacting PRs

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2728]
@cd155 and @Ant13731 I pulled 2 recent PRs of yours, which worked fine independently, and could be merged without problems, but whose end-result is a failing build.

I think it just needs a stable revision. It all looks fine, but could one of you do it?

**Comment by balacij** [comment]
I was just about to make an issue regarding this too.

I wonder if we can also observe "merge into master" events in our Test.yaml workflow (the one that works on the PRs) where when something gets merged into master, it restarts all existing PRs' tests with a `git pull origin master` at the start to see if it's still compatible.

**Comment by JacquesCarette** [comment]
When many people are working, just an event would likely really slow things down - including my reviews. As this is quite rare in practice, let's not do that.

**Comment by cd155** [comment]
@Ant13731 thanks for fixing this problem.
