### ISSUE TITLE
Double Pendulum: Complete the cross-linkings between dblpendulum and sglpendulum

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2730]
There is a lot of common knowledge between the example dblpendulum and sglpendulum. After completing the theory of the double pendulum, we will start to narrow shared information into one place.

In this ticket
- Replacing the common knowledge in sglpendulum example, and import shared information from dblpendulum.
- It is possible that sglpendulum will have it's own information which is different from dblpendulum. Keep that information in sglpendulum.

relate to #2694

**Comment by smiths** [comment]
Sounds good @cd155.

**Comment by cd155** [comment]
This is a recap of today's discussion on the issue of parameterizing pendulums.

- In the multiple pendulums, we can parameterize masses and rods. In addition, more derivatives will be parameterized (ith part), such as velocity, acceleration, angle, speed of angle, acceleration of angle. However, when we work on the single pendulum, we don't want to parameterize each variable.

**Comment by cd155** [comment]
@JacquesCarette @smiths I think I forget to mention this issue in the meeting,

Sometimes, the single or plural also come out a problem when I try to cross-reference between two examples. When we work on the single pendulum, most elements only have one in quantity. When we work on multiple pendulums, each type of element will have multiple in quantity. In the SRS, a few places fall in this trick.

For example, in the statement of goals:

- Single Pendulum: **Given the mass and length of the rod, initial angle of the mass and the gravitational constant, the goal statements are…**
- Double Pendulum: **Given the masses, length of the rods, initial angle of the masses and the gravitational constant, the goal statements are:**

Initially, I thought I can combine them into:

**Given the mass(es), length of the rod(s), initial angle of the mass(es) and the gravitational constant, the goal statements are:**

I feel it is maybe too many parentheses, and it may also affect the readability.

**Comment by smiths** [comment]
@cd155, although the idea of writing a generic statement (with plurals in parentheses) is creative, I don't think we should pursue that.  Eventually we want to do it the right way, and the right way has the text and equations in the single pendulum example written as if there is a single pendulum.  We aren't trying to write generic text that works for both examples.

For now, I think you will have to settle for repetition.  You will have to write the text separately for each example.  

It is good to highlight all of these examples.  Please create an issue that lists every instance you are aware of where the case studies are the same, except for the count of some of the nouns.  This issue will be very valuable when we turn our attention to solving this problem in the right way.

**Comment by JacquesCarette** [comment]
Agreed.
