### ISSUE TITLE
Figure position assumption

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2731]
In the section of Physical System Description, it seems the generator will assume where the figure locates. The keyword "above" and "below" will be added. It works fine in html, but the pdf file has a different look.

It seems the Latex will insert the image at the beginning of the page, so the keyword "below" will most likely be wrong in some cases.

The miss-matched error can be reproduced in the double pendulum and projectile. To be honest, I think the problem occurs in all examples. Some examples just get lucky. When the image size is too big or the current page fills in with contents, the image will be inserted at the top of the next page. In that way, the "below" position still works fine. On the other hand, if the current page still has enough space, the image will be inserted at the beginning of the current page, then the "below" position will be wrong.

I think the quickest solution is to remove the position keyword after figures.

<img width="552" alt="Screen Shot 2021-07-25 at 5 36 18 PM" src="https://user-images.githubusercontent.com/16947266/126914215-f77f49d5-01e1-4dda-aaae-e5fd7bb92515.png">

@tingyuw Do you know how the keyword "above" and "below" be generated?

**Comment by cd155** [comment]
relate to #2720

**Comment by smiths** [comment]
I'm surprised the position keyword appears.  I didn't think we did that in the documents.  I'm fine with removing it.

**Comment by tingyuw** [comment]
It's hard coded in the introduction of Physical System Description section (Drasil/Sections/SpecificSystemDescription.hs). Is there a case where "above" is printed? Since we have direct references, I think removing it would be fine.

![image](https://user-images.githubusercontent.com/47548045/126935914-78fd2d09-3df6-40f8-b480-792c695c6dbf.png)

**Comment by cd155** [comment]
@tingyuw thanks. My initial assumption is that there will be either "above" or "below" be inserted. That's wrong, only "below" will be inserted. Thanks for pointing it out.
