### ISSUE TITLE
`README.md`: Incorrect target name for HGHC + Missing Sgl+Dbl Pendulum

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2738]
In the 2 markdown tables on the README, we're missing the sgl+dbl pendulum case studies, and the "tiny" reference appears to be outdated (it's currently just `hghc`).

**Comment by Awurama-N** [comment]
I fixed the missing case studies but as for HGHC could you please let me know what i should replace it with?
it's currently: tiny: HGHC toy example

**Comment by balacij** [comment]
Yep, the target "tiny" should be replaced with "hghc" to make it usable.

**Comment by Awurama-N** [comment]
oh okay, i thought "HGHC toy example" would also be replaced with what it stands for.

**Comment by balacij** [comment]
This was completed in that PR above.
