### ISSUE TITLE
`\symbf` not working properly in some of the HTML SRSs

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2757]
When using LaTeX blocks in the HTML documents, bold variables don't render properly. Could this be something with MathJax? Everything seems to work fine in the PDFs. For reference, we changed to using symbf from mathbf since symbols like `tau` were not showing up properly (#2240).
![image](https://user-images.githubusercontent.com/69334555/127749654-bbd8a360-3d21-42ca-9dd4-76745a6cd9a0.png)

**Comment by balacij** [comment]
I'm not sure about our existing MathJaX version, but I [created a ticket](https://github.com/JacquesCarette/Drasil/issues/2517) about updating it a while ago for another version, it just needed a bit of work to make sure it wasn't a regression. The [latest MathJaX docs](https://docs.mathjax.org/en/latest/input/tex/macros/index.html#s) says that it has support for `\symbf`.

**Comment by Ant13731** [comment]
I took a look at the `updatingMathJax` branch and the `symbf` command seems to work as expected. If we can solve the issues outlined in #2517, I think this will also be resolved.
