### ISSUE TITLE
Change acro- to use makeRef

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/Drasil#276]
This way, rather than generate just "T3", it will generate a link to the theoretical model.

edit: after doing some digging, this would require `RelationConcept` to be an instance of `LayoutObj`

**Comment by njericha** [comment]
Related to #223

**Comment by njericha** [comment]
and #160

**Comment by njericha** [comment]
Also making a note to do a similar thing with `eqN`

**Comment by samm82** [comment]
Lots of these issues are just smaller symptoms of us needing `Label`s. I think this issue can also be addressed now. @JacquesCarette

**Comment by JacquesCarette** [comment]
I think all the `acro` calls are now actually gone. If that is the case, I think this particular issue can be closed.

**Comment by samm82** [comment]
Not yet - working on this now

**Comment by samm82** [comment]
Can be closed with #987
