### ISSUE TITLE
Haddock docs broken on deploy

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2762]
The haddock docs on the deploy are broken, though the build said it passed. Here is the error I found in the github actions logs:
```
drasil-printers >     parse error on input ‘-- **before’
drasil-printers >     |
drasil-printers > 124 |   -- **before
drasil-printers >     |   ^^^^^^^^^^^
```

**Comment by balacij** [comment]
Weird, I can't find it at all on the GitHub Actions, but I can see that the script fails (but ignores the error, which is bad!). I can only find it locally via browsing the Language.Drasil.JSON.Print file from drasil-printers.

Out of curiosity, where did you find the error in the logs?

**Comment by Ant13731** [comment]
I first got the error locally when I was working on adding the haddock headers so I looked up the latest [deploy](https://github.com/JacquesCarette/Drasil/runs/3241847413) run and its under line 4776 of the `docs` section (I'm not sure how to directly link to it, but I found it using `CTRL+F` on `-- **`)

**Comment by balacij** [comment]
Ah, thank you!
