### ISSUE TITLE
`make help` - new target for showing list of available targets + descriptions

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2764]
Having a `help` target would help with displaying what targets are currently available to the user, along with the patterns for the example_X targets.

**Comment by Ant13731** [comment]
Would it be worth having something like [this](https://stackoverflow.com/questions/8889035/how-to-document-a-makefile) as well? I'm not sure how it would work with the filters, but we could probably add the example_X targets manually?

**Comment by balacij** [comment]
Sorry, is there a specific answer on that SO question you were referring to?

I was thinking of them being manually written. I was thinking of something simple, like:
```
@echo "Target list:"
@echo "  clean                 cleans up the stack-work and constructed artifacts"
@echo "  cleanArtifacts    cleans up only constructed artifacts"
@echo "  code                  builds ... (I forget what it did again now)"
@echo "  docs                  builds Haddock docs"
@echo "  help                   this help information"
@echo ""
@echo "Example-specific targets (where X is the example):"
@echo "  X_build             build example X"
@echo "  X_diff                build diff logs against local stable/"
@echo "  X_stabilize       stabilize X"
```
etc etc

**Comment by balacij** [comment]
And, of course, with a monospaced font, the spacing shouldn't be much of an issue.

**Comment by Ant13731** [comment]
Oh, okay yea that would work. I was asking about that first answer (using `sed` to display all the targets and comments with ##), but writing out the echo files would probably help a lot more with organization.

**Comment by balacij** [comment]
Not a bad idea either! Do you want to play around with it? The examples part might be a bit tricky.

**Comment by Ant13731** [comment]
So after a little bit of poking around, I found it works pretty well:
```
make help
all:       Run examples and test against stable.
check_stack:  Check that we are using the right stack version.
graphs:    Generate all module dependency graphs.
help:        This help command.
```
the spacing just has to be done manually. The examples won't really work out, but we can just skip over the targets that use `filter` and manually define those.

**Comment by balacij** [comment]
Ah, that's perfect!

**Comment by Ant13731** [comment]
One small problem - do makefile targets need dependencies to be listed on the same line as the target name? Because then I don't think we can have comments on the same line (It would look really messy).

**Comment by balacij** [comment]
Yes, they do need to be listed on the same line as the target name. The lines after it are meant to be for the shell. The dependencies (list of targets) are on the same line as the captured target.

e.g., the syntax is:
```
mytarget: dep1 dep2 dep3
  shell1
  shell2
  shell3
  ...
```

**Comment by Ant13731** [comment]
Ah okay. is there a way to just skip over all the stuff between a `:` and the `##`? I've been trying to look up what the script given on SO actually does, but I'm having trouble finding what the slashes, exclamation mark, and letters do in the sed command:
```
sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)
```
Other than that, I think we might have to go manual.

**Comment by balacij** [comment]
It looks like you already figured this out, but, yes, you would need to match all characters between them using the regular expression (excluding `:` and `##`) and ignore them. I'm not 100% sure what the slashes or exclamation marks do for sed, but the letters are generally literal character matches in the pattern.
