### ISSUE TITLE
Should PrintingInformation take in SystemInformation?

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2772]
Right now, `PrintingInformation` only contains the same chunk database that `SystemInformation` uses. However, it does not contain any information about the system name, authors, `usedDB` and `refdb`. I think that allowing `PrintingInformation` to wrap all of `SystemInformation` (rather than just the chunk database) would make the generator & printing functions a lot cleaner (at least for the dot graphs and logs).
So `PrintingInformation` would change from this:
```Haskell
data PrintingInformation = PI
                         { _ckdb :: ChunkDB
                         , _stg :: Stage
                         , _configuration :: PrintingConfiguration
                         }
```
to this:
```Haskell
data PrintingInformation = PI
                         { _sysinfo :: SystemInformation -- already contains ckdb anyways
                         , _stg :: Stage
                         , _configuration :: PrintingConfiguration
                         }
```

**Comment by Ant13731** [comment]
After digging a little bit deeper, I found that `PrintingInformation` is created from only a chunk database in the `Plain` printers:
```Haskell
-- | Create expressions for a document in 'Doc' format.
exprDoc :: ChunkDB -> Stage -> Linearity -> L.Expr -> Doc
exprDoc db st f e = pExprDoc f (expr e (PI db st plainConfiguration))
```
I don't think it would be difficult to change these functions to take `SystemInformation` (or even `PrintingInformation` instead, but these printers are used in the Drasil code generators: 
```Haskell
-- | Creates a 'Linear' 'Implementation'-stage 'exprDoc'.
eDoc :: ChunkDB -> Expr -> Doc
eDoc db = exprDoc db Implementation Linear

-- The above function is then called by convDataDesc, and that is called by makeInputFile
-- and that is called by sampleInput, which only takes in ChunkDB
```
Those functions don't really have access to the systems information (at the point where they are used), we would have to create an incomplete `SystemInformation` to get it to work. This seems kind of hacky, so I think it might be best to leave it as it is (at least for now).

**Comment by JacquesCarette** [comment]
What we really want is a sequence (or tree or ...) of `XXXInformation` structures that appear at different stages of processing Drasil information. Not all processing needs all of the information, so we don't want to have to create a `SystemInformation` to do anything.

**Comment by Ant13731** [comment]
Closing in favour of #2195
