### ISSUE TITLE
Duration of run 1117941925

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2785]
It looks like [an Actions run](https://github.com/JacquesCarette/Drasil/actions/runs/1117941925) did nothing for almost 2 days worth of build minutes.

If this consumes the entirety of our free build minutes for August, we may need to contact GitHub to revert it. It _looks_ like it shouldn't have happened. I don't see any reason why it would be from the build script, but it could be a bug.

**Comment by JacquesCarette** [comment]
I tried to investigate this... and failed. I can't see a partial log to even see where it got stuck.

**Comment by balacij** [comment]
I think it has a fair chance of just being a glitch on GH's side. The only error message that it gives is `This run was marked as timed out after more than 72 hours.`. However, on [it's overview page](https://github.com/JacquesCarette/Drasil/actions/runs/1117941925), it says that it ran for only 1d22hrs. If we're running out of build minutes for this month, we may need to ask GH what went wrong.

**Comment by JacquesCarette** [comment]
Given that, I'm going to close this issue. We can always re-open if we run out of build minutes.
