### ISSUE TITLE
Add standard citation (.cff) to repo

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#2794]
There is now a [github-supported citation file format](https://github.com/citation-file-format/citation-file-format) for software. We should add one for Drasil.  @smiths might be interested in looking deeper at the details of this meta-data.

I wonder if we should generate these when we generate 'all artifacts'?

**Comment by smiths** [comment]
Looks good @JacquesCarette.  Yes, I think each of the generated examples should get its own `cff` file, especially since the authors of the examples are not usually the same authors as the Drasil authors.

**Comment by balacij** [comment]
That is very neat!

Their [documentation](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md) is full, so I think that generating the information will be straightforward too.

I'll start with writing a basic version for us.

**Comment by JacquesCarette** [comment]
Just to make it clear: the task here is just for a hand-written one. If it looks easy, a new issue can be created for generating them.
