### ISSUE TITLE
Adding yourself as an author to the CITATIONs file

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2798]
When #2796 is merged in, we will have a contribution list created and publicly displayed. If you would like to add yourself as a contributor, please add yourself as an author under the `authors` section of the `CITATION.cff` file and submit a PR. Check out the [`person` section of the official schema documentation (of the `cff` files)](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsperson) to see what information you can/would want to input publicly.

I'm going to @ anyone with >10 commits to this ticket. If you don't want yourself added to the list, or have added yourself to the list already, please feel free to ignore this ticket.

- [ ] @AKM11 
- [x] @Ant13731 - #2809
- [ ] @Awurama-N
- [x] @balacij - #2806 
- [x] @bmaclach - #2829 
- [x] @cd155 - #2814
- [x] @danscime 
- [ ] @deviprasad135
- [ ] @lmawarid
- [ ] @jeger1917
- [ ] @Mornix 
- [ ] @muhammadaliog3 
- [ ] @Nathaniel-Hu 
- [x] @niazim3 
- [ ] @oluowoj 
- [ ] @palmerst 
- [x] @samm82 - #2812 
- [ ] @Sodaaaa 
- [x] @szymczdm 
- [x] @tingyuw - #2810

**Comment by smiths** [comment]
This is a good approach to populating the citation file @balacij.  I doesn't look like anyone has added their information yet.  I don't think @balacij is in the file yet either?  :smile:

**Comment by balacij** [comment]
:smile: I'll add mine now. Hopefully others will add theirs too! Thank you!

**Comment by balacij** [comment]
Pinging this so that more people have a chance to see it. Sorry to everyone who has already contributed!

Thanks!

**Comment by balacij** [comment]
Should we close this ticket and perhaps add a note at the bottom of the README instead?

**Comment by smiths** [comment]
I think we can assume that anyone that didn't respond doesn't care about being added to the CITATION file.  We can close the ticket.  What is the note you are proposing for the bottom of the README file?

**Comment by balacij** [comment]
I was thinking about a small note at the bottom with just a bit of information about getting added to the citation, e.g.,

```
### Citation
Please use our provided CITATION.cff file for citation information. GitHub provides an export of it in BibTeX, MLA, and APA if needed.

#### For Any Developers
Please note that we only add to the CITATION.cff/preferred citation file on a consent basis. If you would like your name added, please submit a PR, adding your information to the CITATION.cff file.
````
