### ISSUE TITLE
Unused `ModelDB` DT in `drasil-docLang/Drasil.DocumentLanguage.RefHelpers`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2822]
Relates to #2791

This below structure is currently unused. It's instantiated in SWHS, but then goes unused in SWHS.

https://github.com/JacquesCarette/Drasil/blob/b414d9be831ae1458ce9a2cca83f81bd612ed995/code/drasil-docLang/Drasil/DocumentLanguage/RefHelpers.hs#L23-L40

I couldn't find any tickets related to it, so I figured it would be good to note this here as well. It looks like it could be useful inside of SIs, but I'm not quite sure what the intended purpose of this was.

**Comment by JacquesCarette** [comment]
From the various comments, it looks like it was meant for some kind of traceability. But the intent of that design seems long lost, so it's probably better to delete this now, and redo traceability anew.

**Comment by balacij** [comment]
Sounds good. I think we can close this PR by deleting the ModelDB, and then have the related tickets link here so that they have a reference to what previously was done. Do you know if there are already any relevant tickets for this specific component?

**Comment by JacquesCarette** [comment]
I can't remember any such tickets.
