### ISSUE TITLE
Display issue related to the second derivative

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2828]
In the SRS, there is an issue when displaying the second derivative. For example, the [PD Controller IM](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html#IM:pdEquationIM)'s equation has a second derivative that should be written as "d^2y/dt^2" but is currently written as:
![Screenshot from 2021-08-31 12-19-28](https://user-images.githubusercontent.com/1627302/131539800-528e97d6-c34a-4e46-91d3-c66bfc2653d5.png)
Should be more like:
![Screenshot from 2021-08-31 12-22-50](https://user-images.githubusercontent.com/1627302/131539907-80755d90-e7f7-4314-b083-528fe1dc6a0c.png)
In this ticket, changing the way we display the nth derivative.

Here are things need to pay attention to: 

- It is ideal to create a new branch from #2791. After that, look into `Language.Drasil.ModelExpr` and `Language.Drasil.ModelExpr.Lang` files in `drasil-lang`.

- Keep the smart constructor for the first-order derivative. Create a new constructor for taking natural numbers for the order of derivatives. Once code is tested and changes are also made in each example, replacing the first-order derivative smart constructor with a new one. In such a case, we change code gradually, so the workload distributes evenly.

Discussion details in #2827

**Comment by cd155** [comment]
Update 1:

I create a new constructor which is very similar to Deriv and called it DerivN(can be renamed)

`Deriv     :: DerivType -> ModelExpr -> UID -> ModelExpr`
`DerivN     :: DerivType -> Integer -> ModelExpr -> UID -> ModelExpr`

the integer will display in form of n as a superscript of "d", here is how it looks like in edited PDController SRS:
<img width="547" alt="Screen Shot 2021-09-05 at 5 02 57 PM" src="https://user-images.githubusercontent.com/16947266/132141386-287b8ba1-6d48-4be4-bb17-821f175b71b0.png">

Here are a few questions I have for further changes,
1. Should I need to combine Deriv constructor and DerivN constructor? or it is better to have them separated?
2. @balacij also mentioned a feature that the smart constructors for Deriv to search for and increment/merge Derivative terms when Derivative terms are stacked on each other. If I understand this feature right, the Deriv constructor can automatically count the order of the derivative, so the following case should automatically convert to a 2nd order derivative. 
  `deriv (deriv (sy position) time) time`  will be come `d^2 position/d time^2`
Should this feature be included in this change?

**Comment by cd155** [comment]
A recap for Sep 7th meeting related to Display issue

1. change data structure representation of `Deriv`, in `ModelExpr`
    - keep the current `Deriv` constructor, and change the internal representation of `Deriv` to contain the integer to express the order (order default to 1)
    - create a new constructor for higher-order, the user could give an integer as the order.
2. change the represent of linear ODEs. In `ModelKinds`, it is completely separate, because there is no `Deriv` in `ModelKinds` at all.
    - remove RelationConcept from `DEModel`
    - create a `DifferentialModel` that contains a list of coefficients
    - `DifferentialModel` need wrriten base on linear ODE (`Total` or `Partial`)

**Comment by JacquesCarette** [comment]
Yes, this is a good recap.

**Comment by cd155** [comment]
In the following code (not sure why the permalink did not display the code)

```
modelExpr (Deriv Total a b)          sm =
  P.Div (P.Row [P.Spc P.Thin, P.Ident "d", modelExpr a sm])
        (P.Row [P.Spc P.Thin, P.Ident "d",
                symbol $ lookupC (sm ^. stg) (sm ^. ckdb) b])
```

https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-printers/lib/Language/Drasil/Printing/Import/ModelExpr.hs#L140-L143

I changed it to 
```
modelExpr (Deriv n Total a b)        sm =
  P.Div (P.Row [P.Spc P.Thin, P.Ident "d", if n > 1 then P.Sup (P.Int n) else P.Ident "", modelExpr a sm])
        (P.Row [P.Spc P.Thin, P.Ident "d",
                symbol $ lookupC (sm ^. stg) (sm ^. ckdb) b, if n > 1 then P.Sup (P.Int n) else P.Ident ""])
```

The if statement will add P.Sup (P.Int n) append to string `d` if n is great than 1. I don't think adding an empty string is a good solution, but I am not sure how to add `nothing` in this case.

As @JacquesCarette mentioned, the else statement should add exactly what the previous it is, so I think my change needs to be modified.

**Comment by cd155** [comment]
That's neat. Thank for the suggestion!

**Comment by cd155** [comment]
For now, I created a new type called DifferentialModel, and it has properties, coefficients and constant.
```haskell
data DifferentialModel = Linear {
 coefficients:: [Int],
 constant:: Int
}
```
The Linear ODE has a form 
![image](https://user-images.githubusercontent.com/16947266/134828964-86f7b8b5-69a4-48c8-b20f-132097f01c9b.png)

The coefficients represent the a0(x),a1(x), ...  The constant represent b(x)

After that, I wasn't sure what should I do next. I am assuming I should replace all the `RelationConcept` to `DifferentialModel` in `DeModel`. Also, I should create some relationships represent coefficients * y + constant to fully represent the linear ODE. I am kind of clueless on how to execute it?

**Comment by JacquesCarette** [comment]
Yes, the next step will be to change `DeModel` as you describe.  You will also need to add some method of printing it.

Note that you might need to move beyond integer coefficients, i.e. they might need to be `Expr` instead of `Int`.

**Comment by cd155** [comment]
### A brief update (thanks Jason for the discussion):

I created a model call `NewDEModel`, and added in ModelKinds
```haskell
data ModelKinds e where
    NewDEModel            :: Express e => DifferentialModel -> ModelKinds e
```

The `NewDEModel` need to satisfy all the instance (`HasUID`, `NamedIdea`, `Idea`, `Definition`, `ConceptDomain`, `Express`), so I copied the `relation.hs` and rename it to `DifferentialModel.hs`. Start here, I added the `_coefficients :: [Expr]` and `_constant :: Expr` to `DifferentialModel`.

#### Build coefficients:
To answer this question, I think I should know what will be inputs. To take a second ODE as an example, 
- `d²y/dx² = p(x)dy/dx + q(x)y + r(x)`
in this example, `p(x)`, `q(x)`, `r(x)` are coefficents, which are functions of x alone. I assume the input would be `p(x)`, `q(x)`, `r(x)` in a list.

If this assumption is right, the input will be a list of functions with the dependent variable x.

#### Build relation (`_rel`):
After the coefficients are given, the `DifferentialModel` would automatically generate the relation. To take the previous second ODE as an example:
- inputs: `[p(x), q(x), r(x)]`

By giving inputs, the relation will be built in the form of `p(x)dy/dx + q(x)y + r(x)`

#### ODEInfo:
Currently, we build the `ODEInfo` class manually. In the future, should we consider integrating some parts of `ODEInfo` into `DifferentialModel`?

**Comment by cd155** [comment]
To record the feedback about multiple cases on the right-hand side of ODEs from @smiths.  Sorry, I forget @you in the last comment.

The [IM:eBalanceOnPCM](https://github.com/JacquesCarette/Drasil/blob/10f9f9ed0e332c7a31875f6e035db96549c45945/code/drasil-example/swhs/lib/Drasil/SWHS/IMods.hs#L155) ODE has three cases because the PCM heats differently depending on whether it is solid, melting, or all liquid.  The cases where it is all solid or all liquid are pretty easy to understand.  The thermal related material properties change, but the form of the ODE is the same.  The case that is different is when the PCM is melting.  In this case dT_P/dt = 0 because all of the thermal energy that is added is going to melting the PCM.  No energy is “left” for raising the temperature, so the temperature at the beginning of melting (the melting point) and at the end of melting is the same.  Once all the PCM is melted, the added energy will go toward raising the temperature of the liquid PCM.

Cases like this are considered to be ODEs with events.  When the event occurs the form of the ODE changes.  A good overview of this is given here:

https://www.sciencedirect.com/science/article/pii/S0898122100000456

If we want to “teach” Drasil about ODEs with events, then we need to add the notion of an associated event function.  In the paper I pointed to above, the event function is g(t, y).  An event occurs at t* when g(t*, y(t*)) = 0.  

The condition for the first “switch” if when T_P < T_melt.  The function g in this case would be g = T_melt - T_P.  (You can see this in the Matlab code for SWHS here: https://github.com/smiths/swhs/blob/master/src/Program/Matlab/event1.m).

It seems to me that teaching Drasil about events for ODEs wouldn’t be trivial.  We have to introduce the function g as a parameter.  Moreover, we need to consider cases where there is more than one event function (like SWHS).  The direction that the condition occurs from is also relevant.  We only heat the PCM, but in general, the ODE would be different if it is heating or cooling.  You’ll also see that the “canonical” form of g is different from how people usually communicate equations.  This means the “model" and the display of the model will be different.

We should definitely teach Drasil about ODEs with events, but I think for now, we should follow Jacques' suggestion of continuing to use “other” as the model type for SWHS.  Drasil just doesn’t know enough yet to understand an ODE with events.

**Comment by smiths** [comment]
When we look seriously at ODEs with events, a simple abstraction is available in the [MIS document for SWHS](https://github.com/smiths/swhs/blob/master/docs/Design/MIS/PCM_MIS.pdf) in the ODE Solver Module, which starts on page 13.

**Comment by cd155** [comment]
@smiths Thanks for pointing out that the issue tracking over here has become generic as time pass.

The initial change starts with the display issue, and then it starts evolving. I agree I should separate them.

I can create a couple of issues that represent each problem.

**Issue 1:** the current issue, Display issue related to the second derivative

**Issue 2:** Add NewDEModel to replace the DEModel

**Issue 3:** `addRe` negation display issue

**Issue 4:** Add display indicator in NewDEModel

**Issue 5:** Teach Drasil about ODEs with events

If they all look good, I can start to create them.

**Comment by smiths** [comment]
Yes, those sound like good issues @cd155.
