### ISSUE TITLE
Stack/hpack prefer projects to have source code split up into subdirectories

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2835]
Stack + hpack prefers for source code directories of exes & libs to be split up. Hpack relies on this to generate cabal files where no hs files get compiled more than once. Right now, we have no problem with this.

Currently, we have the following structure:
```
code/
    drasil-example/*/
        package.yaml
        stack.yaml
        lib/
            <library code>
        app/
            <code related to creating executables>
    drasil-*/
        package.yaml
        stack.yaml
        ...
        Language/Drasil/... <- hs files
```

If we want to create more tests/executables, it may be helpful to further split up our `drasil-*` packages into the same form as the projects in `drasil-example/*/`. If we choose not to, then the package.yaml files have to manually specify to which executable each file belongs to. If we split them up by directory, then it will be able to tell that all files from within that directory belong solely to that exe/test/lib. As an example, our `drasil-code`'s [package.yaml](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/package.yaml) file contains a lot of explicitly named modules otherwise Cabal gives us errors noting "missing-home-modules". Taking [glassbr's package.yaml file](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-example/glassbr/package.yaml) as an example of the alternative structure, it does not need to list any files other than an entry point/Main module for executables/tests.

The main problem with reorganizing the `drasil-*` libs into the same structure as the examples is that we lose out on GitHub's commit log. From what it appears, GitHub does not track file movements in commit histories (e.g., it does not appear to use `git log --follow <file>` to generate the logs). I believe this exact issue was previously exhibited when Awurama was looking for the git log for some file via GitHub's git commit history web viewer.

Would this low visibility git commit history be okay?

**Comment by JacquesCarette** [comment]
It's still possible to go through the git history, just requires a bit more work. The underlying git seems fine, it's just the web interface to it that's sub-optimal, from what I can see.

I think the advantages of using Haskell tooling "as expected" outweigh the log disadvantages. Certainly, to do this move, we should be careful to use `git mv` to give `git` as much help as possible with respect to tracking things.

**Comment by balacij** [comment]
Yep, that's exactly the issue. When GitHub's commit viewer fails, we'll need to manually run `git log --follow <file>` to search for a file's history.

Sounds good. Thank you.
