### ISSUE TITLE
Should Makefile be installing binaries on host computer?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2845]
The Makefile's basic `make` installs the project example executables in the host computer's Stack binaries path. Later, when using the software, we reference the executable using `stack exec` (the binary from the project-local `.stack-work` folder). As a result, it seems we don't use the binaries that we copied over into the Stack binaries path at all (e.g., on Linux machines, it appears in `~/.local/bin`), so I think we should remove them if not needed. If a user wants to install an example on their system, I think we should provide them with a `make <example>_install` (individual examples) and `make install` (all examples) commands to install the executables on their machines.

Do we require the executables to be installed on the host machine for any purposes? Regarding tests, I think we can get away with avoiding copying over the binaries.

Additionally, in our basic `make`, we use `stack install X` for each drasil package. I think this can be swapped with just a `stack build` to build the entire suite, and then following up with the diff tests. This should also allow for more of the packages to be built at once (might even help with build times very slightly).

**Comment by JacquesCarette** [comment]
I agree with the whole first paragraph. I don't think we currently require them to be installed. re: `build` vs `install` -- this is something I've always been a little fuzzy on wrt what each part of `stack` really means!

**Comment by balacij** [comment]
Sounds good. I think I'll try to adjust this. It should also make #2698 _slightly_ easier.

`build` vs `install`: `stack install` is a shorthand for `stack build --copy-bins`, where it builds everything and copies all binaries into the host machine's Stack binaries path (which is assumed to be added to the host machines $PATH).
