### ISSUE TITLE
A Sustainable Approach to Developing Software in Well Understood Domains

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2854]
As we discussed earlier today, @JacquesCarette and I would like you to help us co-author a paper.  The title of the paper will be something that incorporate "Well Understood Domains".  For instance, maybe something like "A Sustainable Approach to Developing Software in Well Understood Domains."  We can use that as our working title for now.

The paper is to be submitted to [NIER - New Ideas and Emerging Results](https://conf.researchr.org/track/icse-2022/icse-2022-nier---new-ideas-and-emerging-results).

We are working on the paper in the [NIER2021 branch](https://github.com/JacquesCarette/Drasil/tree/NIER2021/Papers/WellUnderstood).  (We should have called it NIER2022 :smile:, but it doesn't matter since we'll delete the branch once it is merged in.)

The initial text in the paper is related to what we'll include, but it will be significantly changed.  To start with we just repurposed another document that we were working on.  

As a first step, please change the tex file to match the ACM format requested by the track:

"LaTeX users must use the provided acmart.cls and ACM-Reference-Format.bst without modification, enable the conference format in the preamble of the document (i.e., `\documentclass[sigconf,review]{acmart}`), and use the ACM reference format for the bibliography (i.e., `\bibliographystyle{ACM-Reference-Format}`)."

**Comment by balacij** [comment]
Thank you, I added those 2 files mentioned, and read through their requirements (and the linked ACM one too). I tried to conform to all of their requirements. I'm not sure if the "fontenc" package edits the font yet, but I'll need to double check.

Regarding the references, I found [2 of them (Knuth1984, and SchulteEtAl2012)](https://github.com/JacquesCarette/Drasil/blob/NIER2021/Papers/WellUnderstood/References.bib) using the `.bib` file from [Dan's thesis proposal](https://github.com/JacquesCarette/Drasil/blob/NIER2021/People/Dan/Thesis%20Proposal/drasil.bib). However, we're missing:
1. Farmer - "biform theories"
  
    There are at least 3 papers regarding biform theories, do we have a specific one we're referring to?
    https://link.springer.com/chapter/10.1007/978-3-540-73086-6_6  <- Appears to be the original one from the date
    https://link.springer.com/chapter/10.1007/978-3-319-96812-4_7
    https://link.springer.com/chapter/10.1007/978-3-319-62075-6_2
  
2. RationalDesign - "idealized process (influenced by parnas \ref)"
  
    Using Google Scholar, I found:
    https://ieeexplore.ieee.org/abstract/document/6312940
    https://link.springer.com/chapter/10.1007/3-540-15199-0_6
  
3. KM-Textbook - "Knowledge Management"
    
    Using Google Scholar, I found this recurring textbook:
    https://dl.acm.org/doi/book/10.5555/1995301
  
4. org-mode - org-mode

    `bibtex` was giving me errors with writing an entry for this manually. I will look for an official one.

We'll also need to figure out the CCS Concepts.

**Comment by smiths** [comment]
Thank you @balacij.  That was fast and thorough.  You might actually be a little too thorough, since we might not need (at least not for this paper) the references you've tracked down.  It is good to find the references though, since they will likely be something we need for future writing, even if not for this paper.

The Parnas paper that @JacquesCarette had in mind is most likely the "A rational design process: How and why to fake it" paper that you found.  The bib entry for that paper is in the pub repo in the `References.bib` file.  I'm not sure about the other citations.

**Comment by balacij** [comment]
Thank you @smiths! :smile: 

Regarding the RationalDesign paper, I found a [reference](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/tree/master/ReferenceMaterial) to the `pub` repo using one of your public class notes, but I haven't yet been able to access the `pub` repo because my [CAS GitLab account](https://gitlab.cas.mcmaster.ca/balacij) is currently locked. For now, I used the entry from https://github.com/JacquesCarette/Drasil/blob/NIER2021/Papers/Bib/drasil.bib.

**Comment by smiths** [comment]
@balacij, the version of the Parnas reference you used is fine.  You should talk to Sebastian about getting your access back for your GitLab account.  It doesn't come up that often, but the `pub` and `se4sc` repos might be relevant again for something in the future.  I've had 3 other students have a problem with GitLab.  I suspect that Sebastian (or Derek) changed something that is impacting students.  In the case of all of the other students one e-mail to Sebastian sorted it out quickly.
