### ISSUE TITLE
Recreate GlassBR Traceability Figure

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2855]
As a follow-up to issue #2854, can you please recreate the [figure that shows the traceability from Drasil inputs to Drasil outputs](https://github.com/JacquesCarette/Drasil/blob/NIER2021/Presentations/BRIC_2021/figures/DrasilSupportsChange.png).  The figure was originally drawn in [draw.io](https://app.diagrams.net/).  I cannot find it, so I must have accidentally deleted the original drawio file.  Fortunately I still have the [sub-figures](https://github.com/JacquesCarette/Drasil/tree/NIER2021/Presentations/BRIC_2021/figures) that were used to construct it.  The sub-figures are also in draw.io.

We were going to have to change the original figure anyway, so it shouldn't be too bad that I lost the original.  Compared to the original [DrasilSupportsChange.png](https://github.com/JacquesCarette/Drasil/blob/NIER2021/Presentations/BRIC_2021/figures/DrasilSupportsChange.png) can you please make the following changes:

- circle all instances of GlassBR
- put a rhombus around all instances of LDF
- change the aspect ratio so that the figure is less wide (it was more formatted to fit on the screen, rather than on an 8.5x11 piece of paper)

If you have any questions, please let me know.

**Comment by smiths** [comment]
I found the file I deleted.  It has been added to the branch in commit 9d82cdf0f.  We'll still need to make the changes I listed above, but it should be quicker now.  :smile:

**Comment by balacij** [comment]
Ah, thank you very much @smiths! :smile:

**Comment by balacij** [comment]
Would it be okay to change the layout? If so, it might be a bit easier if we move the directory box to the left-hand side. As a very rough prototype:

![DrasilSupportsChange drawio](https://user-images.githubusercontent.com/1627302/136137589-1a18836c-5afb-444d-a545-cd987e942102.png)

Of course, I will need to fix the positions of the shapes.

Thank you

**Comment by smiths** [comment]
Yes, it is definitely okay if we change the layout.  It might take a bit of experimenting, but changing the layout should let us fit more on the page.  We also don't have to keep the figure to one column of the two column format.  We can let the figure span across both columns.

**Comment by balacij** [comment]
@smiths I just uploaded [DrasilSupportsChange-right-portrait-overlapped-ungrouped-v1.drawio.png](https://github.com/JacquesCarette/Drasil/blob/NIER2021/Papers/WellUnderstood/assets/DrasilSupportsChange-right-portrait-overlapped-ungrouped-v1.drawio.png) (and variations in the `assets` folder + their drawio xml files). I've also placed the image on the document on the [4th page](https://github.com/JacquesCarette/Drasil/blob/2a7a1308e854dd47046c7e77143edd3929bdfa10/Papers/WellUnderstood/wu.pdf) (of which, it takes up a lot of space on). Please let me know what you think!

**Comment by smiths** [comment]
What is the reason to change to libertine?  I see that [Libertine](https://en.wikipedia.org/wiki/Linux_Libertine) is an alternative to proprietary fonts.  Are we currently using proprietary fonts?  I have no problem at all with the change, but I don't want you to do unnecessary work.  I've never really run into a problem with figures I've created using proprietary fonts, but maybe I've just been lucky.  To be honest, I don't really think about where the font comes from.  :smile:

**Comment by smiths** [comment]
I think redoing the figure in a libertine font would be time consuming.  Let us postpone that step for now.  If the paper is accepted and this is required, we can do it at a later time.  We should make sure that the text of the paper is in an acceptable font.

**Comment by smiths** [comment]
Right after closing this issue, I'm going to reopen it.

@balacij can you please edit the author information to remove my name and just keep Nikitha's name?  @JacquesCarette pointed out that the double-blind could be compromised by my name appearing in the figure and in the references.  (We are also going to remove all but one of the references with my name on it, so it should be sufficiently blind.)

**Comment by balacij** [comment]
Sounds good, I've made the changes now. Thank you!
