### ISSUE TITLE
GlassBR: unital `J_tol` description contains manual reference to `Pbtol`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2860]
In GlassBR, `J_tol` contains a manually written reference to `P_btol`, resulting in:
![image](https://user-images.githubusercontent.com/1627302/137233221-b1f73591-fec7-453c-821b-5365ead1d361.png)

It should be adjusted to use the real symbol of `P_btol`.

**Comment by balacij** [comment]
So, the "fix" for this should be simple enough: either making sure to use the symbol of `Pbtol` or removing the "based on Pbtol" portion of the definition (which I think is the "right" choice since most row entries don't discuss these aspects).

The text description of "Jtol" is duplicated and diverging in two separate parts of the same "whole" chunk (below). So, depending on which type you take and use, you'll get a different string description of Jtol. While this isn't a large issue, it is on the same wavelength as the "conflicting information in UIDs" issue.

As a `ConstrainedChunk`:
https://github.com/JacquesCarette/Drasil/blob/c7c57e77e0de03158e7c4db6e74e13898a889764/code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs#L129-L130

As a `QuantityDict`:
https://github.com/JacquesCarette/Drasil/blob/c7c57e77e0de03158e7c4db6e74e13898a889764/code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs#L265-L266

**Comment by balacij** [comment]
^ Related to #2908

**Comment by JacquesCarette** [comment]
That duplication is really bad, and should be fixed too. It's unclear how to do that.

I agree that the simplest solution, and the most consistent one, is to delete "based on Pbtol".

**Comment by smiths** [comment]
I also agree with removing "based on Pbtol".
