### ISSUE TITLE
Review: When Capturing Knowledge Improves Productivity

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2866]
Please review the attached paper and give us some feedback.  Your feedback can be in the form of question(s).

- [x] @tingyuw 
- [x] @peter-michalski 
- [x] @cd155 

You can check your name off once you've provided a comment.

[wu.pdf](https://github.com/JacquesCarette/Drasil/files/7366133/wu.pdf)

**Comment by JacquesCarette** [comment]
I wouldn't necessarily 'opposed' code-centric to anything. Current development focuses, rather single mindedly, on the code, at the detriment of most everything else!  Focusing on documents is tempting, but also not quite right.

By *transformers*, I'm thinking of both my work with Bill Farmer on symbolic computation, and program transformation. They are kind of the same thing, over different languages and formalisms.

The issue with emphasizing cross-project knowledge re-use based on GlassBR is that there is less "scientific knowledge" that we can re-use from that one. We still share a huge amount of stuff, but it's more on the meta-information, like the knowledge about specification documents, etc.
