### ISSUE TITLE
Review "Science, not Preference" position paper

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2888]
@JacquesCarette the ["Science, not Preference" paper](https://github.com/JacquesCarette/Drasil/tree/ASCR2021/Papers/ScienceForProductivity) is ready for review.  We have until Nov 19th, so it is fine if you postpone your review until our regular Monday meeting.

**Comment by JacquesCarette** [comment]
Done, but I forgot about the issue.
