### ISSUE TITLE
The difference between CodeExpr, Expr, and Model Expr

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2897]
When I was working on Drasil, I have some difficulties with the difference between CodeExpr, Expr, and ModelExpr. What's the mechanism of those files?

For example, in the imported phrase, the CodeExpr, Expr, and ModelExpr are looking almost identical, so I think it would be great to have some documentation to describe what are those files, and what's their relationship.

(Is that be ok assign the ticket to you? @balacij)

**Comment by balacij** [comment]
Posting an excerpt from a Teams message between Dong and I regarding this ticket:

```
CodeExpr -> Expression language intended to have easy translations to be totally (e.g., every term in it) converted into GOOL (which ultimately is used as the language to generate Java/Python/C++/Swift/etc).

Expr -> "Core" expression language (Both CodeExpr and ModelExpr are based on this one). It is meant to be always "calculable" (to a literal). In other words, you can calculate any expression using a calculator to calculate any constructed expression.

ModelExpr -> Extended "Core" expression language. It is not necessarily meant to be "calculable" always. Sometimes, it needs a bit of extra processing (e.g., on paper and pencil to calculate a derivative) to be calculated (if possible).
```

However, I will still translate this more clearly into the Haddock docs in the code, and then close this ticket with a PR.

**Comment by JacquesCarette** [comment]
I would perhaps phrase this differently. Some are the same, but I'll do all 3 for completeness:
- CodeExpr : expression language where all terms also denote a term in GOOL (i.e. translation is total and meaning preserving)
- Expr : expression language where all terms are supposed to be 'well understood', i.e. have a definite meaning. Right now, this coincides with "having a definite value", but should not be restricted to that.
- ModelExpr : expression language where all terms are supposed to have a meaning, but that meaning may not be that of a definite value. For example, specification expressions, especially with quantifiers, belong here.

**Comment by balacij** [comment]
I like these descriptions a lot better; they're much more concise.

Thank you!
