### ISSUE TITLE
Unify Data Definitions automation for Theoretical models and Instance Models?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#29]
Can we unify how data definitions, theoretical models and instance models are handled in Drasil.  Currently the description field of the data definition is automated for data definitions, but not for theoretical models and instanced models.  In many cases the content of the description for instance models and theoretical models is just a summary of the variables in the equation or relation.

**Comment by JacquesCarette** [comment]
Inasmuch as these 3 things are "the same", then yes, we should.  But I don't have a good enough understanding of what these really are.  Can you point to a specific example?  Certainly if this issue had been assigned to me, I would have no idea what to do without at the level of detail given above.

**Comment by smiths** [comment]
I'll attach examples of a data definition, a general definition, a theoretical model and an instance model.  The examples come from the Solar Water Heating tank SRS (https://github.com/smiths/swhs/tree/master/SRS).  The fields for each are similar.  In particular, they all have a description field and a significant portion of the description field is a summary of the symbols, their meaning and their  units.  My understanding is that the description field is automated for data definitions, but not for the other entities.

![dd](https://cloud.githubusercontent.com/assets/1422000/15749939/5a4d073e-28b2-11e6-8d06-e0646d883ada.png)

![gd](https://cloud.githubusercontent.com/assets/1422000/15750133/3f74fb3c-28b3-11e6-9f25-c5a81f4ddc49.png)

![t](https://cloud.githubusercontent.com/assets/1422000/15750143/49203af2-28b3-11e6-9a9f-7b2fee0fe6f1.png)

![im1](https://cloud.githubusercontent.com/assets/1422000/15750146/4defd75e-28b3-11e6-9f66-26d2b84ddd78.png)

**Comment by JacquesCarette** [comment]
Indeed - now it makes sense to design something to do just this.

**Comment by szymczdm** [comment]
Going back to this issue, it should be taken care of once we have #104 taken care of, since that requires a fairly large overhaul, but then it should be straightforward to apply the same technique to the TMs, GDs, and IMs.

**Comment by szymczdm** [comment]
Once this is implemented we need to double check that the second issue @njericha mentioned in #141 is solved.

**Comment by njericha** [comment]
As I was reviewing SSP's case study, I noticed the Instance Models have an additional "input" row which can be auto generated by finding the variables in the equation for the model. I just wanted to make a note that this section is not present in Theoretical Models, Data Defs, and Gen Defs.

**Comment by smiths** [comment]
@szymczdm, please double check that this is fixed.

**Comment by szymczdm** [comment]
As far as I can tell, this is fixed with the new TMs, IMs, DDs, and GDs
