### ISSUE TITLE
Max/Min Values in Constraints?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#290]
Not sure if this was already addressed somewhere but how would you like us to handle max/min values when we are defining constraints.  Right now most of us are simply using place holders (e.g. `sfwrc $ \c -> c :<= c :<= c` or a new term such as `dim_max`) to define their positions but I was wondering what the long term plan was.  I am tempted to try and create some kind of make-shift function/class constructor that 'builds' these limits off of the original term (e.g. `maxV length` redefines symbol and description for length in terms of a maximum value) but I wanted to hear what the preferred solution is at this point in time.

**Comment by JacquesCarette** [comment]
Not sure yet.  I was awaiting more examples, to see the patterns that arise.

**Comment by njericha** [comment]
related to bounding constraints in #306

**Comment by JacquesCarette** [comment]
Various work (especially on `RealInterval`) has fixed this.
