### ISSUE TITLE
Solve a first order system ODE with two dependent variables

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2906]
### Current situation
The front-end (interface) of the ODE solver only takes one dependent variable. When we solve the second-order ODE, we will rewrite it as two first-order ODEs.

For example:
```
The original equation is
z'' = -(1+K) z' - (20+K) z + rK

In order to solve this second-order ODE, it be rewritten into two equations
x' = y
y' = -(1+K) y - (20+K) x + rK
```

In this case, there are two dependent variables after rewriting. The current front-end only takes one dependent variable (Magically, the current ODE solver is able to solve two first-order equations by just using one dependent variable.)

However, the problem is raised when we want to solve a first-order system ODE with two dependent variables without any re-write.

For example:
x' = 4 x + 7 y
y' = -2 x - 5 y

Both x and y are dependent variables.

### Purposed change
Front-end:
- The front-end should allow taking two dependent variables. 

Back-end:
- After taking two dependent variables and multiple `Expr`, that information needs to be properly sent to External Library.

### Result
Solve a first-order system ODE with two dependent variables

### My thought and questions
When I was checking Python library scipy, it is fairly common to solve a system ODE with two variables. The original design only takes one dependent variable, so I just wonder to know why we take one dependent variable at that moment. @JacquesCarette 

Mentioned #2902

**Comment by smiths** [comment]
@cd155, when you solve a second order ODE you do add another dependent variable.  An example is shown here:

https://tutorial.math.lamar.edu/classes/de/systemsde.aspx

Your wording above makes it sound like the system of first order ODEs from solving a second order ODE only involves one dependent variable.

**Comment by cd155** [comment]
@smiths Thanks for the correction. Indeed, to solve a second-order ODE, a new dependent variable is introduced. I will edit my post once I am ready. I think my confusion is coming from the interface of `ODEInfo`, it only has one dependent variable.

```haskell
data ODEInfo = ODEInfo {
  -- | Independent variable.
  indepVar :: CodeVarChunk,
  -- | Dependent variable.
  depVar :: CodeVarChunk,
  -- | Other variables in the ODE.
  otherVars :: [CodeVarChunk],
  tInit :: CodeExpr,
  tFinal :: CodeExpr,
  -- | Initial value of an ODE.
  initVal :: CodeExpr,
  -- | ODE equations.
  odeSyst :: [CodeExpr],
  odeOpts :: ODEOptions
}
```
For example: 
x' = 4 x + 7 y
y' = -2 x - 5 y

Both x and y are dependent variables for both equations.

**Comment by smiths** [comment]
Yes, it looks like `ODEInfo` only takes on dependent variable.  For solving a second order ODE, I don't know if you need to change that though.  I do not know how difficult it would be for Drasil to derive the system of first order ODEs from the second order ODE.  We don't really do symbolic computation in Drasil, so I guess the programmer will have to do it? 
@JacquesCarette will know.  We will have cases in the future where we need to solve systems of ODEs, so making depVar a list, as for odeSyst, makes sense to me.  Again, @JacquesCarette is likely the best person to offer advice on this.  In particular, I'm not sure if there will be other layers between the ODE model and `ODEInfo`, since `ODEInfo` as it currently stands is the interface to the external library.

**Comment by JacquesCarette** [comment]
`ODEInfo` will need to evolve. It was created for the purpose of first-order, single ODEs in mind.  Note that, in some sense, if you consider a vector as a single variable, then `indepVar` could actually be multiple variables. Of course, what's wrong with it as it exist now is that this is opaque information, as you can't inspect inside a `CodeVarChunk`.  The `ODEInfo` from above is really a 'black box' that exposes little of the actual information; so it can be output as code / documentation, but nothing else. And limited kinds of those.

Which brings us back to representing different kinds of ODEs. The infrastructure has been improved in the front-end, now that improvement needs to be propagated to the back-end.  This needs careful design. We can't just throw some lists in there.

I do have one question: do we have any case now where `odeSyst` is a list that is not length 1 ?

**Comment by cd155** [comment]
@JacquesCarette PDController.
https://github.com/JacquesCarette/Drasil/blob/c00990e67f1072c0ae5b34847d0d8ff7c452af71/code/drasil-example/pdcontroller/lib/Drasil/PDController/ODEs.hs#L21-L32

The original equation is 
y'' = -(1+K) y' + (20+K) y + rK

In order to solve this second-order ODE, it be rewritten into two equations
x' = y
y' = -(1+K) y + (20+K) x + rK

After re-writing, dependant variables should be both x and y, but it is just like a 'black box', the ODE solver still able to solve it by giving one dependant variable.

**Comment by JacquesCarette** [comment]
The original ODE model has a single dependent variable, `y`. Now, it depends **who** rewrites it as 2 first-order ODEs. If it is the 'user', then indeed, it now has 2 dependent variables, and that has to be encoded.

If it is Drasil that does it, or some other entity, then it's a different question.  So who does this rewriting?

**Comment by cd155** [comment]
@JacquesCarette I think it is the user who chooses to re-write the second-order ODE as two first-order ODEs. The re-write only occurred in ODEInfo. The rest of SRS didn't mention the re-write at all. And the re-write is done manually. Manually I mean the user decomposes the original ODE based on mathematic fact, and puts two new equations into ODEInfo. 

I think this example comes from a student who took @smiths class. It is a little surprising that it works in the current ODE solver. Even though, dependent variables are `x` and `y` now, instead `y`.

**Comment by JacquesCarette** [comment]
Can you point me to the code that does that? I mean the 'manual' rewrite into the `ODEInfo`.  Yes, it is surprising that it works, but that makes it even more interesting to understand!

**Comment by cd155** [comment]
@JacquesCarette 

`odeSyst` which is `[CodeExpr]` type has the following ODEs in the line 28-31, 
https://github.com/JacquesCarette/Drasil/blob/c00990e67f1072c0ae5b34847d0d8ff7c452af71/code/drasil-example/pdcontroller/lib/Drasil/PDController/ODEs.hs#L28-L31

Here are two new frist-order ODEs be rewritten in paper

  *x' = y*
  *y' = -(1+K) y - (20+K) x + rK*

### x' = y
```haskell
idx (sy opProcessVariable) (int 1)
```

### y' = -(1+K) y - (20+K) x + rK
```haskell
neg ((exactDbl 1 `addRe` sy qdDerivGain) `mulRe` idx (sy opProcessVariable) (int 1))
 $- ((exactDbl 20 `addRe` sy qdPropGain) `mulRe` idx (sy opProcessVariable) (int 0)) 
 `addRe` (sy qdSetPointTD `mulRe` sy qdPropGain)
```

(Note: Original ODE: `z'' = -(1+K) z' - (20+K) z + rK`)

The idx is used to access an index, in this case, it is the index of `z`, base on the code, the index has length '2'. 

and

idx[0] = x  (this is like z in original second-order ODE)
idx[1] = y   (this is like z' in original second-order ODE)

My hypothesis is that even though we rewrite the second-order ODE into two first-order ODEs, it didn't add things new. The relation between `x` and `y` still can be figured out. The 'primary' dependent variable is still z in the original equation.

**Comment by JacquesCarette** [comment]
Right. And the `odeSyst` is now in one vector variable, i.e. `opProcessVariable`.  Interesting that that is all that it takes.

**Comment by cd155** [comment]
Links tickets that modify the PDController to solve a second ODE.
- https://github.com/muralidn/Drasil/issues/17

I think one reason causing confusion to me is the lack of documentation on solving the second ODE. Before the modification for solving the second ODE, it is easy to follow the Brook thesis in the ODE chapter. After it, some parts seem not to align. I think it would be good to add some documentation on how to solve the second ODE. Some of them could go to Wiki.

The new implementation of solving ODE with two dependent variables would likely make a change to the ODE code generator, so I'll add documentation for it.

**Comment by cd155** [comment]
I recently made some refinements for the `DifferentialModel`, I believe it could represent more complicated ODEs, including linear ODE and system of ODE. I have some questions regarding how to name them, and here is the new data type.

## Polynomial
```haskell
data Polynomial = P{
  _terms :: [Term],
  _constant :: Expr
}

data DifferentialModel = System {
  _indepVar :: UnitalChunk,
  _polynomials :: [Polynomial],
}
```

To break down the above code. A `DifferentialModel` will have independent variables and multiple **polynomials**. 
1. My first question is should I call them [polynomial](https://en.wikipedia.org/wiki/Polynomial)? I really mean multiple equations. For the first order ode, there is only one equation. For a system ODE, there could be multiple equations. Will `polynomial` make more sense here? The definition of a polynomial is expression consist variables and coefficients. For the ODE, the equation will consist not only of variables and coefficients but also of its derivatives. Can its derivatives be categorized as a variable or coefficient?

Inside of a `Polynomial`, it consists of multiple terms and one constant. This is mimic a normal form of an ODE. 

![image](https://user-images.githubusercontent.com/16947266/163402711-d7507de5-4926-48ac-9fe0-9da083e32b99.png)

All derivative terms + constant = 0

note: b(x) is constant, and the rest of a(x)y are All derivative terms

To take a system ODE as an example
```
A: x' -4x -7y = 0
B: y' + 2x + 5y + 5 = 0
```
In A, `x' -4x -7y` is the all derivative terms part, and the constant term is 0
In B, `y' + 2x + 5y` is the all derivative terms part, and the constant term is 5

## Term
```haskell
data Term = T{
  _coeff :: Expr,
  _variables :: [Variable]
}
```
A term will have its coefficient and **multiple** `Variable`. Also to take the previous system of ODE as an example.

In A, `x'`, `-4x`, and `-7y` are `Term`. The `x'` will have coefficient 1, and `Variable` to be `x'`. The `-4x` will have coefficient -4, and `Variable` to be `x`. 

Here is the part I am not quite sure about.  What if we have a system of ODE
```
A: x' -4x -7xy = 0
B: y' + 2x'y' + 5y + 5 = 0
```
Is the modified equation still a system ODE?  To make a `Term` to have a list of `Variable` can represent the modified equation. The `7xy`, can be represented as 7 is coefficient, and x and y be a list of `Variable`

Further modified the system ode
```
A: x' -4x^2 -7xy = 0
B: y' + 2x'y' + 5y + 5 = 0
```
Now I have a square of x in equation A, To encode x^2 into `Term`. I have to make it x*x, this is because the `Variable` is represent the nth order of derivative, and the 0 order is x itself. 

## Variable
```haskell
data Variable = V{
  _depVar :: ConstrConcept,
  _degree :: Int
}
```
I probably shouldn't call it variable, should I? The `Variable` consist of a dependent variable and an nth derivative indicator. This means we can have multiple dependent variables in one `Polynomial`. For example, `4x'`, the variable is just `x'`, the dependent variable is x, and the nth derivative indicator is 1. 

Walk back to the -4x^2 for a minute, the variable only can represent the nth directive, so to represent the nth **exponent**, it needs to bring it to 0 order, then multiple itself multiple times.

## Input language
Here is the input language
```haskell
($^^) :: ConstrConcept -> Int -> Variable
($^^) = V

($*):: Expr -> [Variable] -> Term
($*) = T

($+) :: [Term] -> Expr -> Polynomial
($+) = P
```
nopcm can be rewritten as 
```haskell
eBalanceOnWtrRC :: DifferentialModel 
eBalanceOnWtrRC = 
  makeASystemDE
      time -- independent variable time
      [ -- list of polynomial
        [exactDbl 1 $* [tempW $^^ 1], 
         recip_ (sy tauW) $* [tempW $^^ 0]] -- list of derivative terms
        $+ neg (recip_ (sy tauW) `mulRe` sy tempC) -- constant term
      ]
```
## Linear or System
```haskell
data DifferentialModel = System {
  _indepVar :: UnitalChunk,
  _polynomials :: [Polynomial],
}
```

This `DifferentialModel` can represent a system of ode or a single ODE. I think the ODE could be either linear or non-linear

eg. y' + 5y^2 + 5 = 0 is non-linear, and this can be write in this `DifferentialModel`

I also wonder if there would be an academic source I can refer to. I will try to write them down on paper, so I wonder if there could be a proper reference to cite all the design decisions for the ODE model.

@smiths @JacquesCarette any suggestion would be really appreciated.

**Comment by JacquesCarette** [comment]
Answering these questions:
1. I think what you call `Polynomial` might be better called `Coefficients`.
2. What you call `_polynomials` is better called `_equations`.
3. `System` might here be best called `SystemOfLinearODEs`
4. Your example of a system of differential equations after the definition of `Term` is an ODE, but it is not *linear*. Let's not worry about these right now.
5. For representing Linear ODEs, you are best off representing them as a n by m Matrix of Expr, where n is the number of equations and m is the number of functions (or the other way around, I get these mixed up), and the `_constant` by a vector.
6. For the input language, it makes sense to have a special case for just 1 equation.
7. The input language as you have it will require a lot of processing to verify that the resulting expressions are well-formed. This is ok, but is something to keep in mind.

**Comment by smiths** [comment]
I like your analysis @cd155.  The advice from @JacquesCarette nicely clarifies the terminology.

**Comment by cd155** [comment]
@JacquesCarette Just want to double check, with regard to representing Linear ODEs, the coefficient matrix will look like that
![image](https://user-images.githubusercontent.com/16947266/164738502-861b4b1a-1f5e-4d2f-9739-03e30cbb81c8.png)
A**x** = **b**
A is the matrix of coefficient, and b is a vector of constant, x is a vector of unknown(dependent variables)

The matrix in Expr is just a list of lists. For vector, do you mean I need to use Drasil vector or it can be represented as a list? If we use the Drasil vector, I am not very familiar with how the Drasil vector works, maybe @balacij know?

Last, to make the special case for just 1 equation, should I create a new input language just to work for 1 equation?

**Comment by cd155** [comment]
Here is how a matrix of linear ODE looks like in SRS

Previous in nopcm

<img width="200" alt="Screen Shot 2022-01-29 at 6 35 12 PM" src="https://user-images.githubusercontent.com/16947266/164946129-33f1483e-6cfd-421e-9ccc-98a69e96c42c.png">

Now in nopcm (A**x** = **b**)

<img width="200" alt="Screen Shot 2022-01-29 at 6 35 12 PM" src="https://user-images.githubusercontent.com/16947266/164946186-36f4004e-71a1-47ed-a47f-0e775aa32a4d.png">

In this case, A is a row vector, and x and b is a column vector.

**Comment by smiths** [comment]
@cd155, I believe that the advice from @JacquesCarette is not about displaying the ODEs, but about the data structure you use internally.  For a single ODE (not a system), we don't want to display the ODE using matrix notation.  We might eventually want to provide this as a display option variability, but that isn't a priority.

**Comment by cd155** [comment]
@smiths  Here is the code part
```haskell
data DifferentialModel = SystemOfLinearODEs {
  _indepVar :: UnitalChunk,
  _coefficients :: [[Expr]],
  _unknowns :: [Unknown], -- a column vector
  _constants :: [Expr],  -- a column vector 
}

data Unknown = UK{
  _depVar :: ConstrConcept, -- dependent variable
  _degree :: Int -- which order of dep variable
}
```
For a linear equations A**x** = **b**
  - _coefficients is A, use `[[]]` to represent a matrix
  - _unknowns is **x**, use `[]` to represent a column vector
  - _constants is **b**, use `[]` to represent a column vector

**Comment by smiths** [comment]
For the code the above looks reasonable to me (although @JacquesCarette is a better judge), but when a single ODE is displayed, it should not be displayed with matrix notation.  This is an unnecessary complexity for the reader of the SRS.  How we store the information and how we display it can, and often should be, different from each other.

**Comment by JacquesCarette** [comment]
@smiths is right: I meant as a data-structure representation (yours is fine), not for **display**.
