### ISSUE TITLE
Quick Setup guide in README; is cygwin needed? & should we update anything?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2913]
In our main README.md file, we have a Quick Setup guide:

![image](https://user-images.githubusercontent.com/1627302/144687876-5dd482fd-124f-4031-81ca-e82dbc5d9e8b.png)

Do Windows users really need cygwin? If so, for what? As of right now, it's missing from the [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) wiki page, and I'm wondering if we should add it there, or remove it from the README.md file. In my VM, I didn't install Cygwin but I did have chocolatey, which might have come with tools out of the box that I wasn't aware of.

Is there anything we should update from this area? I just noticed the "make help" was misaligned, so I'll fix that.

**Comment by JacquesCarette** [comment]
The 'requirement' for cygwin is not a true requirement, but rather an artifact of how the early developers worked on Windows, and no effort to see how else it could work.

So if other workflows have been tested and work, that's great, and this part of the guide can be changed accordingly.

**Comment by Ant13731** [comment]
I didn't need to use cygwin or minGW at all since git bash (and downloading `make`) ran most of the makefile by default. There were a few commands that didn't work like deploying the website locally (#2642), and I can't remember if cygwin or minGW could run it. It could be good to mention as an alternative in the new workspace setup. [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) has improved a lot from the summer and I think it comes ready to install on Windows 11, so we could mention that too. It also integrates pretty smoothly with VS Code.

**Comment by balacij** [comment]
@JacquesCarette Thank you!

@Ant13731 Thank you! It looks like you addressed the one "if" component to Dr. Carette's message. I'll also add WSL as a suggestion, I imagine the rest of the installation steps would follow Ubuntu then, which simplifies it a lot.

**Comment by balacij** [comment]
I looked up Cygwin and gave it a go on a fresh Windows VM, and it looks like using Cygwin instead of Git Bash provides a lot more GNU tools out of the box (it claims to provide [a lot](https://cygwin.com/packages/package_list.html) quickly installable too, and it also respects the PATH on Windows properly). In particular, rev is included in Cygwin, and it looks like installing "make" and other tools via Cygwin is smooth. Of course, using Windows WSL seems better since it runs a full Ubuntu distribution, so it's still recommended (and is in the wiki).

**Comment by smiths** [comment]
Thank you for the information @balacij.  Based on the above discussion, it sounds like we can close this issue, or does the setup guide still need to be updated to remove the recommendation for cygwin in favour of WSL?

**Comment by smiths** [comment]
I agree.  We can close the issue now.  Thanks @balacij.
