### ISSUE TITLE
Review SRS for 3dfim+

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#292]
As time allows, please review the SRS for 3dfim+.  You can find the SRS (3dfim+.pdf) in the following repo:

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/tree/git-svn/GradStudents/Mojdeh/SRS_3dfim+

The software in question is used for calculating the correlation between functional MRI data and an ideal signal.  It is part of the research being done by my Masters student Mojdeh.  This would be a nice example to eventually port to Drasil, because it is more about math than physics.  I don't think this will have much of a consequence, but it is nice to have a variety of examples.

If you read the documents critically, there are likely to be parts that do not make sense, or assumptions that are missing.  The goal of the SRS is to have the necessary answers for someone that has the assumed background.  If you find you have questions that aren’t answered, then I would like to know about it.  😄   This will be a task that is lower priority than your Drasil work, since we want to make sure you are in sync with Dan, Steven and your co-workers.

To close this issue, please find at least 5 issues with the original documentation.  The issues can be minor or major, questions or noted mistakes.  The issues should be posted to the se4sc repo, with the label 3dfim+.  Assign the issues to Mojdeh.

**Comment by szymczdm** [comment]
Please note, I added the 0.3.0 milestone, but that is strictly for organization purposes. Not exactly a deadline for this issue.

**Comment by szymczdm** [comment]
@smiths should we reassign this?

**Comment by smiths** [comment]
We can close this issue.  Until such time as we are looking for additional case studies, there is no point in maintaining the 3dfim+ example.
