### ISSUE TITLE
How to read the generateCode chart

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2921]
I am not quite sure I understand this chart correctly, so I wonder if someone could explain how to read this chart.

<img width="300" alt="" src="https://user-images.githubusercontent.com/16947266/150195028-fa05acbc-2f95-4563-aa29-92650216a264.png">

In the brook thesis, this chart shows how the result of `genPackage` is processed by `generateCode` to generate files in the user’s system. And arrows represent function calls, and boxes show the type each call results in.

This is the `generateCode` method.
https://github.com/JacquesCarette/Drasil/blob/4d0ba25ce5037a2474cf7b6b28eb5154f7c11a7e/code/drasil-code/lib/Language/Drasil/Code/Imperative/Generator.hs#L101-L113

From the beginning, what is Reader DrasilState, and then what is the runReader? It would be great to be guided a little bit on how to read this chart.

**Comment by JacquesCarette** [comment]
It's a dataflow diagram, with the arrows representing the functions applied and the boxes the types. 

The code doesn't quite match, since it's using `runState` instead of `runReader`.  Also, it calls `unReprPack` twice (on the same argument) to get at both pieces. The state/reader disconnect happened because this code used to use just reader, but state was added later. It's kind of a good example of why we need Drasil: the documentation became out-of-date with the code!

**Comment by cd155** [comment]
Thanks @JacquesCarette , I also add some notes for last week's meeting. 

The following is the note for the Jan 21st, 2022 discussion

The workflow for this chart
- `Reader`: this is a data structure that will be processed in reader monad
- `Reader` Constructor takes Drasil state, and `(packRepr (Package packRepr)`
- The `Reader` is packed, so we need to instantiate it (`unReprPack`), then it will give you a `PackData`
- The `PackData` split into the program(`ProgData`) and various auxiliary files
- A program made up by modules (the list of files on the left under `ProgData`)
-  Left files(`[FileData]`) and right files(`[AuxData]`) will assemble again, to generate all the code, including code, headers files, make files
- `Doc` is the pretty printed version of each artifact
- `FilePath` is the pass to where the file will be

Notes
- `runState (genPackage unReprProg) g` takes a package representation, and give you the data structure, `PackData`
-  `packRepr` is a type variable,
- function `(packRepr (Package packRepr) -> PackData)` removes the polymorphism of `packRepr`, and create useful data (`PackData`)
- "un-" prefix used in this case. When there is a constructor for a data type, and it has no name and it is also a new type that has only one filed, we add "un-" to the field accessor.
