### ISSUE TITLE
Thesis: Topics in Point Form Notes

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2922]
I just wanted to let you know that I've posted some notes on the two focal topics under the jasonWriting branch. It's starting to appear that we could even merge the two topics together if we really wanted to, under a common "exposing more information and working to ensure it can only be used to create valid expressions" idea. Please let me know what you think about these.

Regarding the existing information in the background and introduction sections, I'm going to take another look at them now as well.

**Comment by JacquesCarette** [comment]
It's good to have a single encompassing story - but we don't want to merge too much. It's better to go with you tackling 2 separate pieces of a single large project.
