### ISSUE TITLE
Should `ModelKinds` allow users to write an overriding name/term for the underlying theory?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2937]
Currently, with `ModelKind`-s, we allow users to manually override the naming `term` of the theory being created. We currently override the original theory container's provided names/terms with something shorter (like an abbreviation) or with something _approximately_ the same.

Taking the NewDEModel as an example,
https://github.com/JacquesCarette/Drasil/blob/5dc10b54aefd5c6ddcef0ce15706b95760f6d7ca/code/drasil-theory/lib/Theory/Drasil/ModelKinds.hs#L42-L57

<details>
<summary>
Most, if not all, usage of ModelKinds' current ability to altering the term of a theory is restricted to EquationalModels.
</summary>

Note: the `equationalModel` smart constructor is an area where a term was manually entered:
https://github.com/JacquesCarette/Drasil/blob/5dc10b54aefd5c6ddcef0ce15706b95760f6d7ca/code/drasil-theory/lib/Theory/Drasil/ModelKinds.hs#L75-L77

instances in code:
```console
drasil-example/swhs/lib/Drasil/SWHS/TMods.hs
137:latentHtEMK = equationalModel "latentHtETM"
174:nwtnCoolingMK = equationalModel "nwtnCoolingTM"

drasil-example/swhs/lib/Drasil/SWHS/IMods.hs
275:heatEInWtrMK = equationalModel "heatEInWtrIM"

drasil-example/gamephysics/lib/Drasil/GamePhysics/IMods.hs
120:col2D = imNoDerivNoRefs (equationalModel "col2DIM" col2DNP col2DFD)

drasil-example/dblpendulum/lib/Drasil/DblPendulum/IMods.hs
55:angularAccelMK_1 = equationalModel "angularAccelerationIM1"
74:angularAccelMK_2 = equationalModel "angularAccelerationIM2"

drasil-example/ssp/lib/Drasil/SSP/IMods.hs
596:crtSlpIdMK = equationalModel "crtSlpIdIM"

drasil-example/sglpendulum/lib/Drasil/SglPendulum/IMods.hs
37:angularDisplacementMK = equationalModel "angularDisplacementIM"
```
</details>

This question is also somewhat similar to #2853 because the potential alternative solutions to ModelKinds discussed involved forcing all information be held within the containers that made up a specific ModelKind, instead of adding information to the ModelKind when placing it there.

From what I understand about how we build our current models, this isn't necessarily _bad_. However, I think we should be moving these terms into the EquationalModels/QDefinitions (and thereby altering stable to make names/terms of the same "thing" always align) and remove the ability to override names/terms as a functionality of ModelKinds. The reason why I suggest moving the name overriding in ModelKinds down into QDefinitions is because overrides in ModelKinds breaks traceability (at the very least, slightly), or at least allows the user to break traceability unknowingly.

I am tagging both @JacquesCarette and @smiths because this is something that will most likely affect `stable/` and the existing work on #2599 w.r.t theories.

**Comment by JacquesCarette** [comment]
It is conceptually incorrect to think of this was overriding the name of the `term` 'e'.  It just so happens that our current theories are so simple that they are almost all single-equation, and the theory's name is essentially the same as that of the term. But this is an illusion caused by our examples.

You are correct that there is a traceability issue, in the sense that in some places, the theory name will be used, and in others, the name of the underlying component (equational, etc). But I don't see this as major, as we can trace through everything - it's just a matter of our making sure that Drasil, the program, does so.

I think this ought to become a lot clearer when all we have are theories. I think some of these extra layers of names will more naturally disappear. It feels premature to change this now, as it will just change again.

**Comment by balacij** [comment]
>  It is conceptually incorrect to think of this was overriding the name of the term 'e'. It just so happens that our current theories are so simple that they are almost all single-equation, and the theory's name is essentially the same as that of the term. But this is an illusion caused by our examples.

Ok, that makes a lot of sense to me. I said "override" because we push "IdeaDict"s out of many things, and use the IdeaDict of chunks instead of the chunks themselves directly. So, I got confused by the cases where we share a UID (e.g., InstanceModels at times with their QDefinitions) but then use the manually set `term` of the InstanceModel instead of the QDefinition's. To be clear, it looks like these cases _shouldn't_ share a UID at all with the underlying QDefinition at all, and should have a new IdeaDict pushed out into the ChunkDB.

>  You are correct that there is a traceability issue, in the sense that in some places, the theory name will be used, and in others, the name of the underlying component (equational, etc). But I don't see this as major, as we can trace through everything - it's just a matter of our making sure that Drasil, the program, does so.

I agree, it's definitely not a 'major' issue.

>  I think this ought to become a lot clearer when all we have are theories. I think some of these extra layers of names will more naturally disappear. It feels premature to change this now, as it will just change again.

Sounds good to me.

In that case, I _think_ we can close this ticket (so I will), but please re-open it if you feel otherwise.

**Comment by JacquesCarette** [comment]
Just a few comments, for clarity (no need to reopen): yes, we share too many UIDs right now. But it's not clear exactly which those are, we'll have to discover it as things evolve.

**Comment by balacij** [comment]
That sounds very good to me. Thank you! :smile:
