### ISSUE TITLE
PL related questions in Choices data

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2938]
When I was documenting `choice` data represent, there are some vocabulary that puzzled me, and I don't have a solid understanding of them, so I hope there could be some guild to lead me. 

### 1. Input function
In the modularity, we can have `combined` and `separated`,  here is the definition
- Combined: all **input functions** will be combined in one module
- Separated: all **input functions** will have their own module

My question is how to understand what is the input functions in the definition.  Modularity can divide the program into four different modules, controller, input, calculations, and output. Does `input module` ≡ `all input functions`?

### 2. Input variable structure
In the input structure, we can have `Unbundled` and `Bundled`
- Unbundled: each input variable was passed to the function as its own parameter.
  - If I understand it right, a generated function will have multiple parameters `f(x, y, z)`.
- Bundled: all input variables bundled in an object.
  - object: [x, y ,z]
  - If I understand it right, a generated function will have one parameter `f(object)`.

### 3. ConstantStructure
- Inline
  - What is inline mean? For example, value can be inlined. When I was googling inline, there are some explanations about the inline function in C and C++. Could you point to a resource I can study/read further?

### 4. onSfwrConstraint vs onPhysConstraint 
- Is there a concrete example of what is software constraint and physical constraint? Particularly, I have a hard time thinking about a physical constraint in a generated program. Is that related to the limitation of hardware(e.g. CPU)?

## Question relates to Haskell
- constant and variable
  - This actually confused me for a long time, so I think it is time to ask experts what the difference between constants and variables in a functional language? In Haskell, variables are immutable. One part of the definition for constant is that a constant never changes. How do constants and variables differ in functional language if both constants and variables are unchangeable?

Sorry, this gets longer than I expected. My apology, if I ask a dumb question, but I really appreciate the answers.

**Comment by smiths** [comment]
As we discussed during #2940, the best way to see what the variabilities do is to look at the generated code for the [case studies](https://jacquescarette.github.io/Drasil/).

**Comment by cd155** [comment]
1. input module ≡ all input function
    - Theoretically, the input module is not the same as all input functions.  With the code I found, with `Combined`, all input-related functions will combine into one class (input class). This class has all input functions. Depending on other settings, it is possible the input class will have a variable with a constant. For example, in constStructure, with attribute set to `WithInputs`. Therefore input module could have more things other than all input functions

2. Unbundled and Bundled
    - Unbundled: each input variable was directly passed to the function as its own parameter. 
    - Bundled: all input variables stored in a separated object.

3. Inline, WithInputs, Store Unbundled and Store Bundled
    - Inline: macro expansion on variables. All variables will be replaced by constants.
    - WithInputs: constants are stored in variables within the input object 
    - Store Unbundled: constants are stored in variables that were directly passed to the function as its own parameter. 
    - Store Bundled: constants are stored in variables within a separated object

4. Software Constraint and Physical Constraint
They are originated from Software Requirement Specification.
    - Software Constraint: constraint about the idealized model, once the parameter falls out of constraint, there is no guarantee the result is valid.
    - Physical Constraint: constraint in the physics world. eg. the mass cannot be negative

5. Constant and Variable in Functional programming language
Summary based on Chat with Jason
    - Constants are the terms of a type, known at the compile-time
    - Variable is just a placeholder for a value, not known at the compile-time, eg if you have a variable that depends on user input, you wouldn't know the value until the user gives the input.

**Comment by smiths** [comment]
@cd155 for the input function, what does `separated` mean?  I know you say above that the input function will be separated into their own modules, but what exactly are the input functions?

Above you say: "Inline: macro expansion on variables. All variables will be replaced by constants."  I don't think this is exactly what you mean.  Variables aren't going to be known until run-time.  Are you talking about constants being implemented as variables in the selected programming language?

**Comment by cd155** [comment]
I think the vocabulary of the input function, module, file have been used interchangeably in Drasil documentation. From my understanding, the input function means all the functions that interact with user inputs, like `get_input`, `input_constraints`.

in the Modularity, we can choose
- Modular: divide the program into a controller, input, calculations, and output. In the code, it will have four different files.
    - Combined: the input module will be just one file. For example, by selecting `Combined`, the functions like `get_input` and `input_constraints` will be combined into one file.
    - Separated: the input module be separated into different files. For example, by selecting `Separated`, the functions like `get_input` and `input_constraints` will be written in their own file.
- Unmodular: all modules will be in one file.

With regard to the keyword `inline`, admittedly, I made a mistake there. I mean "Inline: macro expansion on variables. All variables will be replaced by **its value**." For example, if a variable named `d_min` has a value of 5. With a selection of `Inline`, the `d_min` will be replaced by 5.

@smiths Thanks for bringing it up. When I first read the Drasil documentation on the code generation part, I did find a little struggling with the all vocabulary we used. Some words like input module and input file, the sematic behind them are very subtle.

**Comment by JacquesCarette** [comment]
For @cd155 's summary (right before it was closed and the one above): this description seems coherent with my memory of things.

Hopefully @peter-michalski is keeping track of this, as it is related to his work too.

All of the above information is great, and should find its way to places elsewhere than this closed issue. Maybe the wiki (and your project report) and with a link from the source code to the wiki?

**Comment by cd155** [comment]
1. > All of the above information is great, and should find its way to places elsewhere than this closed issue.

@JacquesCarette All information related to the `Choices` data type has been recorded in [Wiki](https://github.com/JacquesCarette/Drasil/wiki/The-Code-Generator). I also proposed some changes for re-organizing the `Choices` data type, once it gets approved, the wiki will change as well. 

2. > Maybe the wiki (and your project report) and with a link from the source code to the wiki?

Just want to double-check with this, do you mean to place the source code link in Wiki? For example, [lang](https://github.com/JacquesCarette/Drasil/blob/dc3674274edb00b1ae0d63e04ba03729e1dbc6f9/code/drasil-code/lib/Language/Drasil/Choices.hs#L26)

**Comment by smiths** [comment]
Sounds good @cd155.  I do still have a minor comment about the following:

> With regard to the keyword `inline`, admittedly, I made a mistake there. I mean "Inline: macro expansion on variables. All variables will be replaced by **its value**." For example, if a variable named `d_min` has a value of 5. With a selection of `Inline`, the `d_min` will be replaced by 5.
> 

You don't mean **all** variables; you mean constants that are represented by variables.  Saying all variables implies that you know the values of the variables at compile time, but you don't.  Some of the variables are actual variables, in that their value will potentially vary each time the program is run.  :smile:

**Comment by cd155** [comment]
@smiths I see, that certainly makes sense. All constants that are represented by variables will be replaced by their value. I will update it.
