### ISSUE TITLE
Categorize Choice attributes

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2947]
This is the new tree I propose for the `Choice` hierarchy tree. Here is what I changed.
- **Moved Implementation Type into Modularity**. The Implementation Type is about whether the generated code is an actual program or library. In the root of code, the difference is whether there is a `Controller`. By choosing `Modular` in modularity, it will divide the program into four modules, controller, input, calculations, and output. Therefore, it makes sense to move Implementation Type into Modularity
- **Combined inputStructure, constStructure, and constRepr**. I think those three are about how information should be encoded. The difference between Modularity and Data is that Modularity builds the framework, and Data enforce the details of how information should be written down. The Input information is data, and the constant itself is data, so I choose the name `Data`.
- Combine ConceptMatchMap and SpaceMatch as `Map`
- Combine Doxygen configuration as `Documentation`
- Combine logging configuration as `Log`
- Combine Software Constraint  and Physics Constraint as `Requirement`
- Combine Documentation, Log, Auxiliary files as `OptionalFeatures`

The following is the details on the tree diagram
<img width="1200" src="https://user-images.githubusercontent.com/16947266/155255155-8f9694d0-49a9-444f-82c2-1cdd66f9abf4.png">

1. modularity: Modularity
    - Unmodular
    -  Modular
        - Input Module
            - Combined: all input functions will be combined in one module/file.
            - Separated: all input functions will have their own module/file. eg, InputConstraints.py and InputFormat.py are in their own file.
        - Control Module
            - Library: no controller component or main function will be generated
            - Program: a controller component or main function will be generated

2. Data: how information be encoded
    - inputStructure
        - Unbundled: each input variable was directly passed to the function as its own parameter
        - Bundled: all input variables stored in a separated object.
    - constStructure: ConstantStructure
        - Inline: macro expansion on variables. All variables will be replaced by their value.
        - WithInputs: constants are stored in variables within the input object
        - Store Unbundled: constants are stored in variables that were directly passed to the function as its own parameter.
        - Store Bundled: constants are stored in variables within a separated object
    - constRepr
        - Var: all constants represented as regular variables.
        - Const: use selected language's mechanism for defining constants. eg. C# has a build-in constant called `const`

3. Map: maps for which concept/space to use
    - conceptMatch: specifies matches between chunks and `CodeConcept`
    - spaceMatch: specifies matches mathematical spaces and type in the targeted language.

4. Optional Features: those features can be toggled on/off
    - Documentation: Doxygen configuration
        - comments: comment in function, class, module
        - doxVerbosity: types of documentation
        - dates: Doxygen date-field visibility options.
    - Log: logging configuration
        - LogFunc: log messages for function calls
        - LogVar: log messages for variable assignments
    - Auxiliary files: other files, 
        - SampleInput
        - ReadME

5. Requirement: those come from SRS
    - Software Constraint
    - Physics Constraint

6. ODE: ode should be built from Instance Model. Putting ODE in `Choice` is a temporary solution. I inclined to just leave it alone for now, because eventually ODE will be removed from `Choices`.

Detail definitions on every attribute
https://github.com/JacquesCarette/Drasil/wiki/The-Code-Generator

**Comment by JacquesCarette** [comment]
As far as I can tell, all of this makes sense. (Although the other issue that I just commented on is relevant here too)

**Comment by smiths** [comment]
I almost agree with @JacquesCarette.  I also think the diagram makes sense, but I have two points of feedback:
1. You have removed the feature diagram notations found in the original diagram from @bmaclach.  The notations show mandatory choices, options etc.  This is valuable information.
2. I don't think I like implementation type under modularity.  The type of implementation does change whether there is a control module, but I don't think that is where someone would look to find implementation type.  It feels artificial to me.

**Comment by cd155** [comment]
@smiths I have one question regarding the feature diagram notation in @balacij thesis
![Screenshot from 2022-03-06 17-31-51](https://user-images.githubusercontent.com/16947266/156947875-62dcb9cc-34b0-465c-9367-8974f334ae72.png)

Under the legend, on the right top corner, there are one solid circle and one hollow circle, what is the solid circle mean? It says **Mandatory (exactly one)**. The first level of attributes all have a solid circle.

**Comment by smiths** [comment]
Mandatory (exactly one) means that it isn't an option to not make a selection.  For instance, it is not optional whether or not to select lang - the user has to select lang.  They also have to select all of the others that are marked as mandatory.  I assume that Drasil would fail if someone tried to not make one of the mandatory choices.  If it doesn't fail, it should (unless we have default choices implemented.)

**Comment by cd155** [comment]
We did have a default choice. In some case studies, we didn't set some mandatory choices, but apparently, the default choice kicked in and handle the setting. Thanks for the clarification
<img width="400" src="https://user-images.githubusercontent.com/16947266/156950242-6a9c8c70-645b-46f3-8f52-236d5083ec2b.png">

**Comment by smiths** [comment]
Thank you for the information @cd155.  Given the use of default values, it sounds like the feature diagram and the implementation are consistent.

**Comment by cd155** [comment]
This is the new feature diagram contain more value information.
<img width="1200" src="https://user-images.githubusercontent.com/16947266/156951832-4d965584-90ec-4fae-a566-773df404b65e.png">

**Comment by smiths** [comment]
The new diagram looks good @cd155, but should ODE be mandatory?  Not every project is going to have an ODE.

**Comment by cd155** [comment]
I think the `ODE` and its sub-datatype `odeLib` and `odes` are mandatory because `odeLib` and `odes` were mandatory in the previous design. In the previous design,  everything in the first level of the tree is mandatory, and it is where `odeLib` and `odes` were. In a case study, if a user didn't specify `ODE`, `odeLib` and `odes` will default to an empty list.

There is an open ticket #2194 that discussed building the `ODE` from `IM`. This is probably a better way to extract ODE information rather than manually input by users in `Choices`, so a likely scenario is that some part of `ODE` will be removed from `Choices`.

One thing I notice is that @bmaclach divides `Choices` into three categories, Global, Local and Optional Features. 
- Global: the design variabilities that have a pervasive effect on the entire generated program.
- Local the design variabilities whose effects are local to a specific part of the generated program.
    - Implementation Type
    - ODE
    - Constraints

I moved Implementation Type into `Architecture` and `ODE` will be changed in future, so the only thing left is Constraints, so I completely removed Local category. Do you think it is better to have Local as a category?

**Comment by smiths** [comment]
@cd155, I believe we decided in today's meeting (#2950) that what you did with local is fine, but we should change the implementation so that ODE is not mandatory.

**Comment by cd155** [comment]
@smiths I created a new datatype called `ExtLib`, I make the ExtLib mandatory, and ODE is optional. Currently, we only use ODE external libraries, but I think it is possible we can connect more libraries other than ODE. For example, algorithm libraries.
```haskell
data ExtLib = None | Math ODE
```
Here is the new tree diagram,
<img width="1200" src="https://user-images.githubusercontent.com/16947266/158251367-30f24d22-0bb9-4f4e-9db1-33d99e6be70a.png">

**Comment by smiths** [comment]
This suggestion works for me.  You are correct that we will eventually add more external libraries.  It seems a little odd to have a mandatory option with "None" as one of the choices, but if that makes sense from an implementation point of view, that is fine with me.  @JacquesCarette will let us know if there is a better way to implement this.  :smile:

**Comment by cd155** [comment]
I think there could be two ways to make the whole `ExtLib` optional. 
1. Use `Maybe` monad, the `ExtLib` become `Maybe ExtLib`
2. make `ExtLib` be a list, which means we can use one/more libraries at the Drail run time. The `ExtLib` will be empty if no library is assigned.
