### ISSUE TITLE
Drasil Research Group Meeting Agenda, 1:30 pm, Friday Apr 22, 2022 (On Teams)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2965]
The agenda for this coming week is as follows:

1. Peter update
2. Jason update
3. Dong update
4. Cold cases
a. @cd155 - #946
b. @peter-michalski #541
c. @balacij - #498
5. Questions/Comments/Concerns/Discussion

**Comment by smiths** [comment]
We were not able to complete the cold cases, so I've added them to next week's agenda (#2967).

We discussed grammar checking tools and @balacij suggested [LanguageTool](https://marketplace.visualstudio.com/items?itemName=adamvoss.vscode-languagetool) and [Hemingway App](https://hemingwayapp.com/).

**Comment by smiths** [comment]
Thank you @balacij for the advice to try LanguageTool.  I've been very impressed so far, especially after I increase the number of sentences it stores in cache.  Much easier than fighting with Grammarly!

**Comment by balacij** [comment]
That's great to hear! I didn't even know it had a limited cache, I'll need to try configuring mine a bit too now :smile:

**Comment by smiths** [comment]
The default of 2000 sentences seems big enough for most documents, but the paper I'm working on is at the 47 page mark now.  I increased the cache to 7500 sentences and the improvement was really noticeable.
