### ISSUE TITLE
Drasil Research Group Meeting Agenda, 1:30 pm, Friday Apr 29, 2022 (On Teams)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#2967]
The agenda for this coming week is as follows:

1. Dong update
2. Peter update
3. Jason update
4. Meeting schedule
5. Cold cases
a. @cd155 - #946
b. @peter-michalski #541
c. @balacij - #498
6. Questions/Comments/Concerns/Discussion

**Comment by smiths** [comment]
All items on the agenda were discussed.  We agreed, until July 8th, to maintain our Friday at 1:30 pm meeting slot.

**Comment by cd155** [comment]
@smiths An idea comes from my mind. Is it worthwhile to have a list of reading materials on Wiki?
We kind of have the [Suggested-Reading](https://github.com/JacquesCarette/Drasil/wiki/Suggested-Reading) web page but seems no one maintains it.

At the beginning of this program, I think you sent a list of reading material to my email address. The reading materials are 
1. Drasil case study
2. multiple public papers
3. beginner guidelines on Drail, Github, latex, Haskell

Personally, in the beginning, I feel I was struggling with reading Drasil's case studies. When I start programming on Drail, I found the [learnyouahaskell](http://learnyouahaskell.com/) is helpful to understand the code in Drasil, but it didn't explain well how functional programming works. It taught me how to program in Haskell, but it didn't explain the mechanics behind the code. The decision we choose in Drasil has been heavily influenced by functional programming. Reading Haskell or functional programming books actually promote me to go back to check the code I wrote before and start to think about producing a better design/code.   When I use learnyouahaskell, I just copy the example and apply it to the Drasil and most time it is working. The book that I mentioned in the meeting, [Thinking Functionally with Haskell](https://www.amazon.ca/Thinking-Functionally-Haskell-Richard-Bird/dp/1107452643), I actually almost finished the first chapter. It answer a lot of questions I had.

This promote me to think we could have a web page to list all the potential reading material, papers, blogs, and textbooks, that could contribute to the success of the Drasil project.

**Comment by smiths** [comment]
I agree @cd155 that it would be great to have more material on suggested readings.  Moreover, it would be better if this material was actively maintained.  :smile:  We do have some additional Drasil specific resources on [Drasil Papers and Documents wiki page](https://github.com/JacquesCarette/Drasil/wiki/Drasil-Papers-and-Documents).

What I didn't find anywhere under the Readings heading in the Wiki was resources on functional programming.  I think extra material on this topic would definitely be valuable for team members starting out with Drasil.

As much as I don't like adding issues, I think we should create an issue for adding a wiki page on functional programming resources.

We also need to do a major overhaul of our wiki pages, but I won't create an issue for that.  It isn't an issue that could be closed quickly, and we are all well aware that in the future our documentation will need to be updated.
