### ISSUE TITLE
Add inputs, outputs, and QDefinitions to SystemInformation in examples

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#297]
In 2d4dfa96156e7dfb456d09554a5c453ae7d1d252 I added lists of program inputs, program outputs, and qdefinitions to the SystemInformation.  I added empty lists to your examples so compilation didn't break.  Please fill in these lists.

- [x] tiny
- [x] glassbr
- [x] gamephys
- [x] swhs
- [x] nopcm
- [x] ssp

**Comment by hmadej** [comment]
How does the list of QDefinitions differ from the list of Block QDefinitions?

**Comment by palmerst** [comment]
The Block list is for capturing the order that functions must be called in to go from inputs to outputs.  The list of QDefinitions is just a full unordered listing of all the QDefinitions that show up in your example (there might be some functions in this list that don't show up in the ordered list).

**Comment by hmadej** [comment]
do variables as time step, output interval, output time, specifics about the rigid body IE circle, rectangle, radius/dimensions of rigid body count as "inputs" as they are required for the gamephys program, but they are not defined or vaguely defined in the SRS and MIS.

For the output, the output of the code outputs strings containing, position, velocity, and time, should the output be that string or the set of output parameters of the string? The output of the program is vaguely a simulation of rigid bodies in 2D.

**Comment by palmerst** [comment]
Inputs should be things that are external to the program, that are supplied by the user via file or command line.  Outputs are what is reported back to the user (again through file or command line).  If the output is formatted as a string made up of actual output variables, then don't worry about the string itself and just list the variables.

**Comment by smiths** [comment]
Hello Henry.  Great question.  You highlight the problem that we are going to have in transitioning from the SRS to the code.  There are other decisions that need to be made.  These decisions are design decisions.  They don't belong in the SRS, but in another document.  The exact format of that other document is not yet clear.

The shape of the rigid bodies is a great example of this.  Mathematically if we talk about a rigid body in 2D as a set of connected points, we can work with this abstraction.  However, when we enter the shapes into a computer, we need to define the boundary that defines the rigid body.  Do we represent it as a planar straight line graph?  Do we include curvature?  Do we only allow simple shapes, like squares, rectangles, triangles and circles?  Even if these decisions are made in the SRS, maybe as a simplifying constraint, we still need to make decisions on the structure and format of the input.

@hmadej, I do not think you will be able to complete the task assigned to you by @palmerst .  There are just too many decisions that haven't been made by the SRS.  I suggest that you do the best with the decisions that are made in the SRS.

For the other part, my recommendation is to write an MG and an MIS.  The final design documents that Drasil needs might not look like these documents, but this gives us a good starting point.  We'll need to discuss this with @palmerst , @JacquesCarette and @szymczdm before proceeding.  They may have other ideas.

**Comment by hmadej** [comment]
in the case of gamephys there are no inputs from a file, or command prompt all the variables are set in code by "magic number/constants", are those still considered input variables?

Example:
```
Vector gravity = vect(0, -9.8);
shapeSetFriction(ground, 0.7);
double innerRadius = 0;
double outerRadius1 = 10;
double outerRadius2 = 15;
double outerRadius3 = 5;
double mass = 10;
double timeStep = 1 / 60.0;
double outputInterval = 5;
double outputTime = 0.0;
```
these are "inputs".

**Comment by hmadej** [comment]
Ok, will do what I can for now and hold off until further instructions.

**Comment by JacquesCarette** [comment]
Regarding the list of `QDefinition` vs `Block` of `QDefinition`, I disagree with @palmerst here.  It is easy to obtain the list from the `Block`, and hard the other way around (requires topological sorting based on dependencies).  So I think it would be best to store the `Block` in the system information.

I think the structure should be changed accordingly.

**Comment by szymczdm** [comment]
I agree with @JacquesCarette regarding ease of obtaining the list, though I've been thinking about the case @palmerst mentioned: "there might be some functions in [the list of QDefinitions] that don't show up in the ordered list [of Blocks]". 

Do we have any examples where that is true? I would think that our block listing would need to include every function, since they will all need to be used at some point (otherwise, why would they be in the example?).

**Comment by njericha** [comment]
@szymczdm There are theoretical models in SSP that have an equation that's used for reference/derivations/assumptions but not actually implemented (ex. Factor of Safety shows up in T1 and IM1 but only IM1 is need in code). These functions would not show up in the list of Blocks.

**Comment by szymczdm** [comment]
Ah right, that makes sense.

**Comment by niazim3** [comment]
GlassBR's **outputfile.txt** outputs all the values that are used in calculations (including inputs and constants defined in the documentation), as stated in **Individual Product Use Case 2**.
However, I was wondering if it makes sense to add the input variables to the list of outputs for GlassBR? Are "list of inputs" and "list of outputs" supposed to be mutually exclusive?

**Comment by smiths** [comment]
There may be a case where it makes sense, but we should keep our inputs and outputs separate.  The inputs are included in the outputfile.txt in the interest of reproducibility.  By including the information in the same file, the user knows what inputs generated their outputs.  However, this information is redundant; they knew their inputs in the first place when they provided them to the program.  You shouldn't really think of the inputs as outputs.  If we can think about the program as a function that takes inputs and produces outputs, it is much easier to understand and reason about.

**Comment by palmerst** [comment]
These were all filled in a while ago.
