### ISSUE TITLE
Rename GOOL's `const` to something less commonly used

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2970]
Fine for now, but I think the better change would be to rename `const` in our classes to something else. Too much danger.

_Originally posted by @JacquesCarette in https://github.com/JacquesCarette/Drasil/pull/2969#pullrequestreview-956561840_

Any suggestions on what we can make it?

* 'gConst', as in "gool const"
* 'const_', appending an underscore
* 'ctv', as in compile-time static value

**Comment by JacquesCarette** [comment]
`const_` is not bad. `constant` would work too. The other two are too obscure/implementation dependent.

**Comment by ManvendraJani** [comment]
@balacij is this only used in the "/code/drasil-gool/" directory?

**Comment by balacij** [comment]
Admittedly, I'm not sure off the top of my head, you might just need to change it in the defined area (drasil-gool) and let GHC guide you in finding the breakage (and hence things that also need to be renamed), or you can try to find the breakage beforehand using [`grep`](https://github.com/JacquesCarette/Drasil/wiki/Debugging-in-Drasil#grep-summary). Note that since the ticket is about renaming `const` to something less commonly used, you might other areas of code using other `const`s (in particular, the [`Prelude`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#v:const) contains a `const` function, imported by default in each module), so you will need to be careful when searching!

**Comment by ManvendraJani** [comment]
Could I get help with an error I get when trying to run `make pr_ready`. After fetching HLint it outputs this error message

**sh: line 65: 7z: command not found
make: *** [Makefile:364: hot_hlint] Error 127**

This does not occur when runnig `make test`

**Comment by balacij** [comment]
It looks like you need to install [7zip](https://www.7-zip.org/). `7z: command not found` is the hint. Were you on Windows? Did you follow the steps in the `New Workspace Setup` guide? If 'yes' to both, we might need to update it!

**Comment by balacij** [comment]
Ok, let's open up a ticket about it and continue discussion there.
