### ISSUE TITLE
ODE equation transform, how to deal with transform

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2973]
In order to solve a high order of ODE, it has to transform into a system of first-order odes. To take a second-order ODE as an example

The equation `2y′′−5y′+y=0`
will be transfer to (we introduce two variable **x1 = y**  and **x2 = y'**)
- x1'=x2
- x2'=−1/2 * x1 + 5/2 * x2

For a 2nd order ODE, we can write it as a system of first-order ODEs in **two** equations
For a 3rd order ODE, we can write it as a system of first-order ODEs in **three** equations
For a 4th order ODE, we can write it as a system of first-order ODEs in **four** equations
.... and so on

In the new system of first-order ODEs, on the left-hand side are the first-order derivatives of newly introduced variables. Take `2y′′−5y′+y=0` as an example. It was re-written and become 
- x1'=x2
- x2'=−1/2 * x1 + 5/2 * x2
The left-hand side becomes x1' and x2'.

This rewriting is sufficient to allow the external libraries (scipy python) to solve a high-order ODE. The question comes what is the user input, and how to convert the user input into a well-form format which external libraries can solve.

**I am not quite sure whether Drsail is capable of this kind of transformation**. Once the input is given, Drasil has to do some internal transformation to generate the expression of the new system of first-order odes.

A temporary solution would be manually doing the transformation in `ODEInfo`. By manually creating the well-form format, the external libraries can solve the high-order ODE. However, we are currently working on getting rid of `ODEInfo`, so automating the transformation seems inevitable.

**Comment by smiths** [comment]
@JacquesCarette knows more about symbolic manipulation, but my guess is that we will be sticking with the manual entry of the system of ODEs for now.  We should enter them in Drasil code in the way that is most convenient for us.  We can display them in other forms, but the original encoding into Drasil should be standardized.  My guess is that the matrix form you have been working with is the best way to enter the knowledge of a specific higher-order ODE for Drasil.

**Comment by smiths** [comment]
@cd155, find a textbook or web-page that shows examples of the transformation from one higher ode to a system of first order odes.  @JacquesCarette can then determine how difficult this is.  (Discussed in https://github.com/JacquesCarette/Drasil/issues/2971).

**Comment by cd155** [comment]
@JacquesCarette Here is the example I use to reduce a high order ODE to a system of first-order ODE, the resource is given by @smiths in https://github.com/JacquesCarette/Drasil/issues/2906#issuecomment-983824262

The website has two examples, second-order ODE(example 1) and fourth-order ODE (example 2)

This is a 4th order ODE we want to solve:
y'''' + 3y′′ − sin(t) * y′ + 8y = t²

For a 4th-order ODE, we can write it as a system of first-order ODEs in four equations.

We start to introduce four new variables x₁, x₂, x₃, and x₄

x₁ = y          =>         x₁' = y' = x₂
x₂ = y'          =>         x₂' = y'' = x₃
x₃ = y''         =>          x₃' = y''' = x₄
x₄ = y'''        =>          x₄' = y'''' = -8y + sin(t) * y′ - 3y'' + t² = -8x₁ + sin(t) * x₂ - 3x₃ + t²

Then, we get a system of first-order odes
x₁' = x₂
x₂' = x₃
x₃' = x₄
x₄' = -8x₁ + sin(t) * x₂ - 3x₃ + t²

**Comment by JacquesCarette** [comment]
So if the input is a vector `[8, -sin(t), 3, 0, 1]` and `t^2` for constant, the resulting system has matrix `X' = AX + B` with `A`
```
 0        1    0   0
 0        0    1   0
 0        0    0   1
-8    sin(t)  -3   0
```
and B is
```
0
0
0
t^2
```
where I wrote things in order x₁ to x₄. 

This is general, in the sense that the given matrix always has shape of a vector `0` beside an identity matrix, stacked on top of (minus) the input vector with the trailing `1` deleted.  If the leading coefficient of the y'''' isn't `1`, it can be divided through. Generalizes to dimension n too.

**Comment by JacquesCarette** [comment]
The basic thing: there is no "computation" needed, just shuffling data around into a different form. That's why this particular transformation can be automated inside Drasil, as it doesn't involve looking into `Expr`. It strongly assumes that the input has the coefficients separated, otherwise it would be much harder.

**Comment by cd155** [comment]
@JacquesCarette There is a further question I would like to ask, how to deal with the transformation of a system of ODE with two second-order ODEs in couple.

We can still use the same method to reduce the second-order ODE to a system ODE.

For example:

x'' + 2x' + 4x +7y = 0
2y'' + y' + 2x -4y = 0

we can introduce four variables a₁, a₂, a₃, a₄ 
a₁ = x => a₁' = x' = a₂
a₂ = x' => a₂' = x'' = -2x' - 4x - 7y = -2a₂ - 4a₁ - 7a₃
a₃ = y => a₃' = y' = a₄
a₄ = y' => a₄' = y'' = -0.5y' - x + 2y = -0.5a₄ - a₁ + 2a₃

Then, we get a system of first-order odes
a₁' = a₂
a₂' =  -2a₂ - 4a₁ - 7a₃
a₃' = a₄
a₄' = -0.5a₄ - a₁ + 2a₃

In this case, I wasn't sure what will the input vector look like, and how to shuffle data around.

**Comment by smiths** [comment]
In this case the matrix equation is:`X' = AX + B` with `A`
```
   0       1    0   0
  -4      -2   -7   0
   0       0    0   1
  -1       0    2   0.5
```
and B is
```
0
0
0
0
```
This can be seen from your last set of 4 equations.  (It would be easier to see if you sorted the entries in each equation as a1, a2, a3 and a4.)

I'm not at all sure how one sees the 4x4 matrix form from the first two ODEs that you provided.  It feels to me like pulling the matrix equation out of the two equations requires some symbolic manipulation.  @JacquesCarette can we automate this, or, for now, should we just ask the Drasil users to enter their ODE in "canonical" matrix form?

**Comment by cd155** [comment]
Thanks Dr.Smith. The input for the following odes 
x'' + 2x' + 4x +7y = 0
2y'' + y' + 2x -4y = 0

A is 
`[4 2 1 7 0 0]`
`[2 0 0 -4 1 2]`

B is 
`[0]`
`[0]`

The A and B will likely be the input for the user to put in.

**Comment by smiths** [comment]
@cd155 your 2 by 6 matrix could be used to enter the information for displaying the ODE, but that matrix isn't useful for the system of first order ODEs form.  I think your mapping between the 2 by 6 matrix and the 4 by 4 matrix isn't going to generalize for any matrix.

**Comment by JacquesCarette** [comment]
@cd155 yes, that result is correct. The process is also essentially correct, but difficult to generalize as exactly written, as @smiths pointed out.

My feeling is that we shouldn't worry about systems of higher order ODEs right now, unless one of the examples needs it.

**Comment by smiths** [comment]
@JacquesCarette has a good point.  We should follow our practical approach of keeping our examples working.

**Comment by cd155** [comment]
@JacquesCarette The double pendulum example #2619 may need to pass the transformation of systems of higher-order ODEs to ODE solvers.

**Comment by JacquesCarette** [comment]
"needs to" or "may need to" ?

**Comment by cd155** [comment]
I will say we "needs to". @JacquesCarette @smiths 

The double pendulum example works the same way as we did to solve the second-order ODE, but it is a system of second-order ODEs. Here are the theoretical steps on how we can solve it in ODE solvers, just as we did in PDContoller

![image](https://user-images.githubusercontent.com/16947266/168436590-498ec2d4-d88c-462b-afd5-13d2a94708ee.png)

1. we did the algebra to get the system of second-order equations. It is two equations with θ₁'' and θ₂'' on the right-hand side
    - θ₁'' is the angular acceleration of θ₁
    - θ₂'' is the angular acceleration of θ₂
    - To solve θ₁'', we need to know θ₂, and to solve θ₂'' we need to know θ₁. θ₁ and θ₂ are in couple.
2. We can introduce four new variables a₁, a₂, a₃, a₄
    - a₁ = θ₁
    - a₂ = θ₁'
    - a₃ = θ₂
    - a₄ = θ₂'
3. After the replacement, we can get 
    - a₁' = something
    - a₂' = something
    - a₃' = something
    - a₄' = something
4. Now we have four first-order odes with four unknowns. Given four initial values (a₁, a₂, a₃, a₄), the numerical solution can be solved by the ODE solver or even a human can solve it

Here is the original post for the [double pendulum solution](https://www.myphysicslab.com/pendulum/double-pendulum-en.html)

**Comment by JacquesCarette** [comment]
Wonderful proof: you are right, the basic equations will be a second order system.

I do think the procedure to create a system is fairly straightforward. Your informal description is good. What we need is to make sure we can get a formal description that can be programmed.
