### ISSUE TITLE
Change python to pyhton3 in gerenate make file

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2974]
The make file which will run the generate code still uses python as the command. Python2 which uses `python` as a command is no longer maintained, and the majority of programmers move to Python3. In python3, it uses `python3` as a command.

**Comment by JacquesCarette** [comment]
Well spotted!

**Comment by balacij** [comment]
A part of this is information about the host system -- assuming a binaries name in the working shell environment. Many Linux distributions don't ship with python2 at all anymore, so `python` is acceptable now too, at least for Linux. I'm not quite sure how macOS and the typical Python installation on Windows are packaged.

**Comment by cd155** [comment]
I think the MacOS have python2.7 installed by default. `python3` seems a more universal command to invoke the python interpreter across OS.
