### ISSUE TITLE
Can we generate the sampleInput.txt from SRS

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2983]
Currently, the sampleInput.txt is manually created and stored in datafiles in each example. Can we generate the sampleInput.txt base on the inputs we defined in the SRS?

Here are the inputs in SRS in
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-example/pdcontroller/lib/Drasil/PDController/Unitals.hs#L58-L59

https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-example/nopcm/lib/Drasil/NoPCM/Unitals.hs#L13-L14

If we look at them furthermore, inputs are a list of `QuantityDict`, and the individual `QuantityDict` comes from `UncertQ`. UncertQ is a constraint and it has quantities. I believe the quantities will be used in `Typical Value` in the Data Constraint section. From what I observe, the typical value for each constraint has exactly the same value as sampleInput.txt.

However, I did find some of the inputs in SRS and input parameters in sampleInput are not 100% aligned. Some input might not show up in txt file but do show up in Data Constraints. May I ask do these two inputs (SRS and sampleInput.txt) can be consolidated? They seem used for a different purpose but the data they give is the same. The problem comes when we want to change one input, we may need to change it in two places.

**Comment by smiths** [comment]
@cd155, I couldn't find it in the issue tracker, but if I remember correctly this is something we discussed in the past (before you joined our team.)  Although the values are the same between the typical values and the sample input, they do have a different purpose.  The values being almost the same isn't a coincidence, but it isn't required either.  It wouldn't break anything to use one source of information for both, but it also suggests a relationship that doesn't exist.  Eventually the sample input file will (hopefully) be expanded into a set of test cases.  The test cases (when we have them), will have a greater variety of values than just the typical values.

**Comment by cd155** [comment]
Thanks for the clarificaiton.
