### ISSUE TITLE
neg should generate parenthese

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#2985]
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L98-L99

When we apply an `Expr` to `neg`, it doesn't generate a parenthesis in the code. For example, if we apply an `Expr` in `neg` it just generates a `-` in the code. This becomes a problem when the `Expr` is `a+b`, rather than a single individual `Expr`. 

Right now `neg (a + b)` will be `- a + b` in code rather than `- (a + b)`

I think we saw the issue related to `neg` multiple times.

Previously, we discussed that
1. a + -b should be a - b
2. a - -b should be a + b

Without the fix, it really hard to do matrix transformation to a certain format. There is one step that requires applying `neg` to Expr. https://github.com/JacquesCarette/Drasil/issues/2973#issuecomment-1120442094

**Comment by smiths** [comment]
@cd155, are you sure about this?  I'm not surprised that Drasil has awkward notation like `a--b`, as we have previously discussed, but `neg (a + b)` being expanded as `- a + b` surprises me.  This isn't just awkward notation; it is wrong.  Can you create a working example that you can point to that shows this behaviour?  The example will verify the problem in the existing implementation, and it will give us a path toward fixing the problem.

**Comment by cd155** [comment]
A quick example can be created by editing in NoPCM, @smiths 

In this file
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-example/nopcm/lib/Drasil/NoPCM/ODEs.hs#L19

Change
```haskell
[recip_ (sy tauW) `mulRe` (sy tempC $- idx (sy tempW) (int 0))]
```
 to 
```haskell
 [neg (sy tauW `addRe` sy tauW) `mulRe` (sy tempC $- idx (sy tempW) (int 0))] 
```

In the python code it has (the problem occurs in every language)
```python
-tau_W + tau_W * (T_C - T_W[0])
```

but it supposes to be 
```python
-(tau_W + tau_W) * (T_C - T_W[0])
```

**Comment by smiths** [comment]
Thank you @cd155.  That is indeed incorrect.  It looks like we are too aggressive in removing parentheses.  

@JacquesCarette is the expert, but I feel like the fix for this shouldn't be too hard.  If we don't discuss it sooner, we can talk about this during our Drasil meeting tomorrow (Friday, May 20).

**Comment by JacquesCarette** [comment]
Yes, this is most definitely a bug. The pretty-printers for the documentation likely handle this right but, surprisingly, the code printers don't seem to.

Not quite sure who to assign it to. But it's a very bad bug, we should fix it sooner rather than later.

**Comment by balacij** [comment]
To get it noted on GitHub as well, Dong and I briefly spoke about this on Teams earlier today as well, we suspected it has to do with the GOOL renderer.

Taking the Java renderer as an example:
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs#L317-L318

which relies on `unExpr'`:
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/Constructors.hs#L105-L107

which relies on `unExprDocD'`:
https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer.hs#L308-L312

Dong is trying the same code, but with changing `unExpr'` to rely on `unExprDocD` (no prime/') to see if it fixes it. If it does, we'll need to figure out a way for `unExprDocD'` to check if it should be wrapping its inner expression in parentheses or not (so that we don't plaster parentheses everywhere without a real need to).

**Comment by cd155** [comment]
By changing 
```haskell
unExpr' = join .: on2StateValues (mkUnExpr unOpDocD') 
```
to 
```haskell
unExpr' = join .: on2StateValues (mkUnExpr unOpDocD) 
```

It adds parenthesis to every `neg` expression. 

Surprisingly, it only affects one case study - glassbr

For example in glassbr
```python
return 1.0 - math.exp(-B)
```
changed to
```python
return 1.0 - math.exp(-(B))
```

**Comment by smiths** [comment]
Good investigation @balacij and @cd155.  The extra brackets are better than the error.  However, I hope we can also get rid of the extra brackets.  :smile:

**Comment by balacij** [comment]
I think that what we really need is some extra information from the inner expression of a unary negation expression. If the inner expression is a unary operation as well, it's a literal, or it's a "function call", then we can avoid adding the extra parentheses (there might be other cases in GOOL too though, I probably didn't cover everything). With an ADT representation, it's a bit more straight-forward to pattern match to get that extra information on the inner expression. With the TTF GOOL representation, I _think_ we would need to look to some of [Dr. Kiselyov's examples](https://okmij.org/ftp/tagless-final/course/lecture.pdf).

**Comment by JacquesCarette** [comment]
The LaTeX rendered uses precedence information to get this right. That's the extra information that's needed. Note that GOOL's representations already allow extra information, so this should be fixable.

**Comment by cd155** [comment]
@JacquesCarette I think I am getting close. In the `unExpr`, it takes `VSUnOp r` and `SValue r` as parameters. These are two extra pieces of information we need. The `VSUnOp r` is the operator and the `SValue r` is the expression.

https://github.com/JacquesCarette/Drasil/blob/af49fba74aecb1593dc5b91cb42d92a0121fb506/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/Constructors.hs#L101-L111

However, I am not so sure how to really compare those two. I would like to add an if condition based on these two values.

**Comment by cd155** [comment]
I am not quite sure why `u <- u'` will let u' : `VSUnOp r` become u: `r (UnaryOp r)` 

Although 
```haskell
type VSUnOp a = VS (a (UnaryOp a))
```
I think I seem to miss the key point here, how to interchange between `VSUnOp a` and `a (UnaryOp a)`.

The following code extract precedence information, and add parenthese to the unary `neg`
```haskell
unExpr' :: (RenderSym r) => VSUnOp r -> SValue r -> SValue r
unExpr' u' v'= do
  u <- u'
  v <- v'
  (join .: on2StateValues (mkUnExpr (if maybe False (< uOpPrec u) (valuePrec v) then unOpDocD else unOpDocD'))) u' v'
```

**Comment by JacquesCarette** [comment]
It's a little surprising that `valuePrec` returns a `Maybe` - but it does seem like the right code to be calling.

**Comment by cd155** [comment]
@balacij provided an excellent blog to explain the `Monad` happened in code. Basically, by using `<-` it will unwrap the Monad type. The `VS (a (UnaryOp a))` is a monad type, we can unwrapping it in a do statement, and it becomes `a (UnaryOp a)`

Here is the link
https://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html
