### ISSUE TITLE
Some dot graphs broken on website

### ISSUE THREAD

**Issue by Ant13731** [JacquesCarette/Drasil#2988]
When looking at the Class Instance dot graphs on the Drasil website, some do not render at all. For example, on Chrome, clicking the [drasil-lang](https://jacquescarette.github.io/Drasil/analysis/ClassInstDep/packagegraphs/lang.svg) graph outputs the following message:
![image](https://user-images.githubusercontent.com/69334555/169890045-6da5f857-ba95-47c8-8b17-b0a3e50207d4.png)

However, other packages like [drasil-doclang](https://jacquescarette.github.io/Drasil/analysis/ClassInstDep/packagegraphs/docLang.svg) work as expected.

After a bit of looking around, I found that the dot files don't like qualified class instances. For example, the `M.` of this line causes a syntax error in the generated dot files: https://github.com/JacquesCarette/Drasil/blob/adfc15f13c7cf81101c1dbab97a6aa61f10a4ec6/code/drasil-lang/lib/Language/Drasil/Expr/Class.hs#L406

I think this would need a change in the dotfile generators to filter instances of the format `Qualifier.Class` to something like `Qualifier_Class`.

**Comment by JacquesCarette** [comment]
Thanks @Ant13731 - @balacij would you mind taking a look?

**Comment by balacij** [comment]
Yep, I can see what I can do. Thanks for analyzing this already @Ant13731 ! :smile:
