### ISSUE TITLE
Front 3 Chapters for review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2991]
I've posted a [copy of my thesis](https://github.com/JacquesCarette/Drasil/blob/jasonWriting/People/Jason/thesis/thesis.pdf) on the `jasonWriting` branch.

Ignoring some TODO notes, which are mostly for unimportant things and holes for examples, the front 3 chapters should be good for review.

- [x] Chapter 1
- [x] Chapter 2
 - [x] Chapter 3

**Comment by balacij** [comment]
Chapter 1 is ready for another pass after our emails.

**Comment by JacquesCarette** [comment]
Is this still 'live', i.e. I should (re)review chapter 1, and also do 2 and 3?

**Comment by balacij** [comment]
I still have some notes to go over for chapter 1, but I think Chapter 2 and 3 would be okay to read through, yes. Thank you!

**Comment by JacquesCarette** [comment]
See email for notes on Chapter 2.

**Comment by JacquesCarette** [comment]
And email sent for Chapter 3 as well.
