### ISSUE TITLE
Chapter 4: "Framing Theories" Ready for Review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#2999]
I've now posted a rough draft of Chapter 4 ready for review in my [thesis pdf](https://github.com/JacquesCarette/Drasil/blob/jasonWriting/People/Jason/thesis/thesis.pdf).

There are many TODO notes in there, primarily for examples and code snippets. However, I also had a few questions.

Thank you very much! :smile:

**Comment by JacquesCarette** [comment]
Found this buried deep in my github emails... (I need to also look at my assigned issues!)  Is this still 'live'?

**Comment by balacij** [comment]
It's a bit outdated, considering I haven't edited yet with your feedback for my Chapter 1 in mind. However, if you wanted to skim through it still, I would appreciate it.

**Comment by JacquesCarette** [comment]
Email about chapter 4 sent.
