### ISSUE TITLE
Allow choice between MathJax or plain HTML

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#300]
As mentioned in c96c57439ca5f6931b8ec1456f71e6361dd2476f we need to incorporate the ability to configure whether we want to use MathJax or plain HTML for rendering math in HTML.

Just posting this so it doesn't get forgotten. It will help with #273.

**Comment by smiths** [comment]
See #412

**Comment by JacquesCarette** [comment]
I'm going to close this one in favour of #479.
