### ISSUE TITLE
GitHub code stats are skewed

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3000]
According to GitHub, it appears that after #2979 was merged, C++ became our primary language:

![image](https://user-images.githubusercontent.com/1627302/170770607-a643bf27-16c3-4e47-b7b1-ab4745edbd4c.png)

We just need to update the `.gitattributes` file to completely remove `datafiles/` from being counted in the stats. Currently, the .gitattributes only omits files from `datafiles/nopcm` w.r.t. Boost. I will submit a fix for this later today.

**Comment by JacquesCarette** [comment]
That's another reason I didn't want Boost checked in!

**Comment by cd155** [comment]
Yeah, I think it is related to the boost library in datafiles.
