### ISSUE TITLE
How to cite this on the report: observation or finding existed resources

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3016]
I am currently trying to write down how to convert nth order linear ODE to a system of first-order ODEs.

A lot of online resources give **examples** of how to convert nth order ODE.  For example https://tutorial.math.lamar.edu/classes/de/systemsde.aspx, this gives two examples 2nd order and 4th order.

The problem is I didn't find a clear source that says how to convert nth order ODE. By looking at the pattern of 2nd order and 4th order, is not hard to generalize how to convert nth order ODE by **observing the pattern**.

The comment below gives a road map on how to generalize it.
https://github.com/JacquesCarette/Drasil/issues/2973#issuecomment-1120442094

However, I think there should be some resources talking about converting nth order ODE, but I didn't find it, or I didn't really understand it. A lot of ODE paper comes with tons of symbols, and I found it is too abstract to understand.

**Comment by smiths** [comment]
@cd155, I think the [Ohio University Lecture 29 notes](http://www.ohiouniversityfaculty.com/youngt/IntNumMeth/lecture29.pdf) have what you want.  They don't actually show the matrix, but they show almost everything else you need.  The steps are as follows:

1. Isolate the highest derivative on the LHS (x^{n} = f(t, x, x', x'', ...)).
2. Change of variables (y1 = x, y2 = x', y3 = x'', ...)
3. Differentiate the new variables (y1', y2', ...) and relate the derivatives to the new variables (y1, y2, ...)
4. Summarize the resulting first order system

The missing piece in the link is reinforcing that the function f is linear.  That is:

f(t, y1, y2, ..., yn) can be represented as h(t) + g1(t)*y1 + g2(t)*y2 + ... gn(t)*yn

Therefore the equations can be written in the form x' = A*x + B  as:

```
[y1'] = [0      1       0     ...    0 ] [y1] = [0]
[y2'] = [0      0       1     ...    0 ] [y2]   [0]
[...] = [ ...                          ] [...]  [0]
[yn'] = [g1(t)  g2(t)   g3(t) ... gn(t)] [yn]   [h(t)]
```

I don't think you need anything "fancier" than the above.  You can cite the Ohio chapter, add in the definition of a linear function and summarize the matrix.

**Comment by cd155** [comment]
Thanks for providing the source. Today I actually try to generalize it by myself with the pattern I observe.

Here is what I have:

we can rewrite a high order linear ODE into the following form

a*y⁽ⁿ⁾ + f = c

- y⁽ⁿ⁾ is the highest order of y in the equation
- a is the constant coefficient of the highest order term
- f is other terms besides the highest order
- c is the constant term


x₁ = y      ⇒ x₁' = y'  = x₂ 
x₂ = y'     ⇒ x₂' = y'' = x₃
x₃ = y''    ⇒ x₃' = y'''= x₄
...
xₙ = y⁽ⁿ⁻¹⁾ ⇒ xₙ' = y⁽ⁿ⁾= (−f + c)/a 

then, replace y, y',...,y⁽ⁿ⁻¹⁾ with x₁, x₂,..., xₙ inside of (−f + c)/a 

The above system can be written in form of matrix X' = AX + C
X' = x₁', x₂', ..., xₙ'
X  = x₁, x₂, ..., xₙ
C  = 0, 0, ..., c/a
A  = 
  0  0 ... 1    0     
  0  1 ... 0    0     
  1  0 ... 0    0
  ...     
  z₁ z₂... zₙ₋₁ zₙ

**Comment by smiths** [comment]
Looks good @cd155.  You did almost the same thing as what I described.  I think you run will run into problems with your example because you only have one derivative (y^n).  This lets your last row in the matrix be simple, with all the problem specific parts moved into the vector C.  I think you are better off presenting your theory with y^{n} and all the lesser derivatives as a linear combination.  The coefficients for each of the derivatives will find their way into your matrix A.
