### ISSUE TITLE
Generate derivations with their DataDef and IMod

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/Drasil#302]
Is it possible to add a header to a paragraph? I would use it in the derivation sections.

Example,
![image](https://user-images.githubusercontent.com/26230851/27440642-5ed74812-5739-11e7-8d09-eae1e112ee30.png)

**Comment by szymczdm** [comment]
Are there any instances where we have these headers that are not related to derivations of instance models?

**Comment by njericha** [comment]
Not in my example

**Comment by njericha** [comment]
related to #46

**Comment by szymczdm** [comment]
Alright, I think we're going to auto-gen the derivation section (Not the derivations themselves, but the header and whatnot, and we can have the contents manually written), so you won't actually need to create that header at this point. If it comes up elsewhere, then we can worry about it.

**Comment by smiths** [comment]
Your solution sounds good to me Dan, except I think there are examples where there are derivations for general definitions or definitions.  (For example, the general definition in the solar water heating example (SWHS) has a derivation following the general definition for "Simplified rate of change of temperature.")  The reason for the derivation section below the instance model (or other theory or definition) is that the derivation doesn't fit in the description field of the table.  It is definitely like another field for the model, just not in the table.

**Comment by njericha** [comment]
Yes. I forgot to mention I have derivations in some of my Data Definitions.

Example,
![2017-06-22 3](https://user-images.githubusercontent.com/26230851/27452831-1a59d438-5762-11e7-9a2b-7d76b416d80d.png)

**Comment by szymczdm** [comment]
@smiths I think we're on the same page, but I'm not sure exactly what you're trying to get across.

When I said we'd auto-generate the derivations, I meant to be more general (hence no mention of "instance models" or the like), as I figured they'd show up across instance, data def, gen def, etc. and would act exactly as another piece of knowledge to be captured. That way we'd just generate the IM, DD, TM, etc. with the appropriate derivation following it.

This ties into #29 and related issues.

**Comment by njericha** [comment]
> Are there any instances where we have these headers that are not related to derivations of **instance models**?

I think your earlier comment caused the confusion.

**Comment by smiths** [comment]
There was a question above on whether the derivation section only followed instance models; I just wanted to point out that this isn't the case.  @njericha just beat me to this explanation, but I'll post my comment anyway.  😄

**Comment by smiths** [comment]
Related to #409

**Comment by JacquesCarette** [comment]
This is also related to the design issue of having "self-describing" chunks. Right now, we mix the display structure and the more semantic aspects of things too much. We need to 'pull apart' these two aspects.  I couldn't find the issue where this is though.

**Comment by szymczdm** [comment]
Derivations can now (commit a13d7ebcb7186173ba3d0fe9ef8a3ce3d2dd8dad) be generated alongside their definitions/models using Attributes.
