### ISSUE TITLE
Latex thesis template

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3022]
I wonder to know if there is a standard latex template for the final report or thesis. 

I checked 
- GradStudents folder in se4sc
- People folder in Drasil

there is a lot of previous Drasil team members' work. Some are different than others. Is there a standard template or do we all make our customized one?

**Comment by smiths** [comment]
@cd155, you can find an [empty latex template](https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/GradStudResources/EmptyThesis) in the se4sc repo.

There are also some [writing guidelines](https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/tree/git-svn/GradStudResources/WritingGuidelines).

**Comment by JacquesCarette** [comment]
Geneva has updated the template - ask on the Discord. She's given a copy to Connie and John, so that it can be made available to all in the department as well.

**Comment by cd155** [comment]
@JacquesCarette is the updated template available for the public?

@smiths Thanks, it's a very neat template. I find some files in GradStudResources are doc or docx, they seem not very friendly for Linux users. :sweat_smile:

**Comment by cd155** [comment]
@smiths  here is the sample for the new template in double space [Thesis_SamplePDF_DoubleSpaced.pdf](https://github.com/JacquesCarette/Drasil/files/8950199/Thesis_SamplePDF_DoubleSpaced.pdf)

It has an updated table of content, a list of figures, tables, and examples of some layouts (equation, table, figures)

**Comment by cd155** [comment]
Yes, Geneva sent me this [LaTeXTemplate_GraduateThesesandReports.zip](https://github.com/JacquesCarette/Drasil/files/8950599/LaTeXTemplate_GraduateThesesandReports.zip)

**Comment by smiths** [comment]
Thank you @cd155.  I've added the template to the se4sc repo under GradStudResources.  I can remove it in the future when the resource is made available on the CAS web-page.
