### ISSUE TITLE
Classification of numerical ODE algorithms 

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3031]
Four selected external libraries have the option to use different algorithms to solve an ODE numerically. I tried to classify them because they use very different names in each library. Some algorithm is a variation of others, so it would be hard to find one to one match.  A lot of them belong to a family type of algorithm, so I wonder to know if my classification is right. I mainly classify them into three categories, a family of **Euler** methods, a family of **Adams** methods, and a family of **Runge-Kutta** methods.

# 
In Python - **scipy.integrate.ode**, the following table show what algorithm its library can provide.
source from https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html

| Name      | Description |
| ----------- | ----------- |
| zvode      | Complex-valued Variable-coefficient Ordinary Differential Equation solver, with fixed-leading-coefficient implementation. It provides implicit Adams method (for non-stiff problems) and a method based on backward differentiation formulas (BDF) (for stiff problems).|
| lsoda   | Real-valued Variable-coefficient Ordinary Differential Equation solver, with fixed-leading-coefficient implementation. It provides automatic method switching between implicit Adams method (for non-stiff problems) and a method based on backward differentiation formulas (BDF) (for stiff problems). |
| dopri5   | This is an explicit runge-kutta method of order (4)5 due to Dormand & Prince (with stepsize control and dense output).|
| dop853 | This is an explicit runge-kutta method of order 8(5,3) due to Dormand & Prince (with stepsize control and dense output).|

1. It is clear to me that dopri5 and dop853 belong to a family of runge-kutta methods. 
2. However, zvode and lsoda use both Adams method and BDF method. Should they belong to a family of Adams or a family of BDF? or both? Will there be a family of BDF methods? @smiths

#

In Java - **Apache Commons Math**, the following table show what algorithm its library can provide.
source from https://commons.apache.org/proper/commons-math/userguide/ode.html

| Name      | Description |
| ----------- | ----------- |
| Euler      | This class implements a simple Euler integrator for Ordinary Differential Equations.|
| Midpoint | This class implements a second order Runge-Kutta integrator for Ordinary Differential Equations. |
| Classical RungeKutta | This class implements the classical fourth order Runge-Kutta integrator for Ordinary Differential Equations (it is the most often used Runge-Kutta method). |
| Gill |  This class implements the Gill fourth order Runge-Kutta integrator for Ordinary Differential Equations . | 
| 3/8 | This class implements the 3/8 fourth order Runge-Kutta integrator for Ordinary Differential Equations. |
| Luther | This class implements the Luther sixth order Runge-Kutta integrator for Ordinary Differential Equations.|
| HighamHall | This class implements the 5(4) Higham and Hall integrator for Ordinary Differential Equations. This integrator is an embedded Runge-Kutta integrator of order 5(4) used in local extrapolation mode (i.e. the solution is computed using the high order formula) with stepsize control (and automatic step initialization) and continuous output. This method uses 7 functions evaluations per step.|
| DormandPrince5(4) | This class implements the 5(4) Dormand-Prince integrator for Ordinary Differential Equations. This integrator is an embedded Runge-Kutta integrator of order 5(4) used in local extrapolation mode (i.e. the solution is computed using the high order formula) with stepsize control (and automatic step initialization) and continuous output. |
| Dormand-Prince8(5,3) | This class implements the 8(5,3) Dormand-Prince integrator for Ordinary Differential Equations. This integrator is an embedded Runge-Kutta integrator of order 8(5,3) used in local extrapolation mode (i.e. the solution is computed using the high order formula) with stepsize control (and automatic step initialization) and continuous output.  |
| Gragg-Bulirsch-Stoer | This class implements a Gragg-Bulirsch-Stoer integrator for Ordinary Differential Equations. The Gragg-Bulirsch-Stoer algorithm is one of the most efficient ones currently available for smooth problems. It uses Richardson extrapolation to estimate what would be the solution if the step size could be decreased down to zero. |
| Adams-Bashforth | This class implements explicit Adams-Bashforth integrators for Ordinary Differential Equations. |
| Adams-Moulton | This class implements implicit Adams-Moulton integrators for Ordinary Differential Equations. |

1. The Euler belongs to a family of the Euler methods. 
3. Adams-Bashforth and Adams-Moulton belong to a  family of Adams methods. 
4. I wasn't really sure about [Gragg-Bulirsch-Stoer](https://en.wikipedia.org/wiki/Bulirsch%E2%80%93Stoer_algorithm).  Will Gragg-Bulirsch-Stoer belong to a new family? @smiths 
5. The rest of them from Midpoint to Dormand-Prince8(5,3) belong to a family of Runge-Kutta methods.

#

In C++ - **ODEINT**, the following table show what algorithm its library can provide.
source from https://www.codeproject.com/Articles/268589/odeint-v2-Solving-ordinary-differential-equations

| Name      | Description |
| ----------- | ----------- |
| euler      | Explicit Euler |
| runge_kutta4      | Runge-Kutta 4 |
| runge_kutta_cash_karp54| Cash-Karp |
| runge_kutta_dopri5 | Dormand-Prince 5 |
| runge_kutta_fehlberg78 | Fehlberg 78 |
| adams_bashforth_moulton | Adams-Bashforth-Moulton |
| controlled_runge_kutta | Controlled Error Stepper |
| dense_output_runge_kutta | Dense Output Stepper |
| bulirsch_stoer | Bulirsch-Stoer |
| implicit_euler | Implicit Euler |
| rosenbrock4 | Rosenbrock 4 |
| symplectic_euler | Symplectic Euler |
| symplectic_rkn_sb3a_mclachlan | Symplectic RKN McLachlan|

1. Explicit Euler, Implicit Euler, and Symplectic Euler belong to a family of Euler methods.
2. Runge-Kutta 4, Cash-Karp, Dormand-Prince 5, Fehlberg 78, Controlled Error Stepper, Dense Output Stepper, and Symplectic RKN McLachlan belong to a family of Runge-Kutta methods.
3. I wasn't sure about [Rosenbrock 4](https://en.wikipedia.org/wiki/Rosenbrock_methods), it is more like belongs to a family of Runge-Kutta methods. @smiths 
4. Adams-Bashforth-Moulton belongs to a family of Adams methods
5. Same questions here, will Bulirsch-Stoer belongs to a new family? @smiths 

#

In C# - **OSLS**, the following table show what algorithm its library can provide.
source from https://www.microsoft.com/en-us/research/wp-content/uploads/2014/07/osloUserGuide.pdf

| Name      | Description |
| ----------- | ----------- |
| RK547M    | This method is most appropriate for solving non-stiff ODE systems. It is based on classical Runge-Kutta formulae with modifications for automatic error and step size control.|
| GearBDF  | It is an implementation of the Gear back differentiation method, a multistep implicit method for stiff ODE systems solving |
1. RK547M belongs to a family of Runge-Kutta methods
2. The same question asked before here, will GearBDF belong to a family of BDF methods? @smiths

**Comment by cd155** [comment]
![Screenshot from 2022-07-14 14-50-40](https://user-images.githubusercontent.com/16947266/179060536-0e917df8-889b-403a-be34-17f8e393b60e.png)

**Comment by JacquesCarette** [comment]
This is superb information! Definitely should end up in your thesis. The way you present the information is really good. I understood what you meant right away. [I can't answer your more detailed questions, sorry, you really do have to wait for @smiths  for that.]

**Comment by smiths** [comment]
@cd155, I do not know all of the methods you have listed.  You or I would have to do some homework to answer your questions.  Just putting different algorithms in different bins doesn't really have value on its own though, right?  I'm not sure what you are looking for, but I think it is to allow the user to select a type of algorithm and then allow code to be generated in each library that can generate the code.

I think we can do this for a subset of what you have listed, like Euler and Runge Kutta methods.  Doing an exhaustive analysis of the commonalities and variabilities between all of the algorithms would be too time consuming. 

We can talk about this further during our meeting that is about to start.  :smile:

**Comment by cd155** [comment]
After spending some time reading, I eventually merged Euler methods into Runge-Kutta, because Euler methods are the simplest Runge-Kutta method. The [Rosenbrock 4](https://en.wikipedia.org/wiki/Rosenbrock_methods) is a type of Runge-Kutta method. [Gragg-Bulirsch-Stoer](http://www.mymathlib.com/diffeq/bulirsch_stoer.html) belongs to a new family because it uses Gragg's modified midpoint method. 

Therefore, I divided categories into Family of Adams methods, Family of Backward Differentiation Formula (BDF) methods, Family of Runge-Kutta (RK) methods, and other methods. Here is the new classification in the table.

![Screenshot from 2022-07-22 00-04-03](https://user-images.githubusercontent.com/16947266/180360858-8884bd21-e577-404d-93b4-992e33fa3205.png)

@smiths, @JacquesCarette Any feedback or suggestion would be really appreciated.

**Comment by smiths** [comment]
@cd155, I googled to confirm that the [Rosenbrock method is considered a Runge-Kutta method](https://encyclopediaofmath.org/wiki/Rosenbrock_methods).  If we were doing a full analysis we would distinguish explicit and implicit methods, but your grouping is fine for our purposes.  Based on my quick reading, I agree that Gragg Bulirsch Stoer should be in its own class.
