### ISSUE TITLE
Chapter 3 External Libraries - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3034]
Chapter 3 External Libraries is ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/chapter3.tex

last commit e3bebb64e01b2a290bfbe6a0dfb37e54d728b6a2

With regard to using the commit to highlight the change I made, so I can get feedback after editing. I usually have a couple of commits for one feedback, so I wasn't sure which commit should I use. @smiths

**Comment by smiths** [comment]
I'll have a look at Chapter 3 soon.  As far as which commits to highlight the changes, you just list them all.  :-)

**Comment by smiths** [comment]
Feedback on Chapter 3 is available in cb47623de.

For adding output type information to Chapter 3, as mentioned in my comments on the pdf, I suggest you look at the [MIS for the ODE Solver module for the  SWHS example](https://github.com/smiths/swhs/blob/master/docs/Design/MIS/PCM_MIS.pdf).

**Comment by JacquesCarette** [comment]
Do indicate when this feedback has been incorporated, I can look at Chapter 3 after that.

**Comment by cd155** [comment]
@smiths The **3.3 Output an ODE** is the section I made significant changes. Some specifications were inspired by [MIS for the ODE Solver module for the  SWHS example](https://github.com/smiths/swhs/blob/master/docs/Design/MIS/PCM_MIS.pdf). Suggestions on this section would be really appreciated.

**Comment by smiths** [comment]
@cd155 my feedback on Section 3.3 is available in 5df25558b.  I'm suggesting introducing a possibly unusual notation for an infinite sequence.  When Jacques reviews your work, he may know a better notation.  For now though, lets go with my idea.  :smile:
