### ISSUE TITLE
Drasil Research Group Meeting Agenda, Week of August 1st (On Teams) 

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3036]
The agenda for this coming week is as follows:

1. Dong update
2. Peter update
3. Jason update
5. Cold cases/Code Review/Discussion
a. @peter-michalski - #1599
b. @balacij 
c. @cd155 
d. @JacquesCarette [DSL for inforgraphics](https://modeling-languages.com/model-driven-production-of-data-centric-infographics/) as a really interesting case of "knowledge capture" (placeholder for the following week). [The way we cite](https://arxiv.org/abs/2205.13419)'s Table 1 is another really good example.
6. Questions/Comments/Concerns/Discussion

@balacij will coordinate a meeting time with @JacquesCarette.  @smiths will not be available for this meeting or the following week's meeting.

**Comment by cd155** [comment]
Hi everyone, I believe we have a meeting this week, but do you know when is the best time for everyone?

**Comment by smiths** [comment]
I wasn't at last week's meeting, so I don't know how you left things.  I agree that a meeting this week is a good idea.  @cd155  can you please coordinate a meeting time?   My schedule is available [online](http://www.cas.mcmaster.ca/~smiths/SSmithSchedule.html).

**Comment by peter-michalski** [comment]
Thursday at noon would work for me.

**Comment by smiths** [comment]
@cd155, yes back to back meetings are fine.

**Comment by balacij** [comment]
Thursday at noon is fine with me! Thank you!

**Comment by cd155** [comment]
Sounds good. @smiths August 18th, 2022, at 12:00 pm works for all of us.

**Comment by cd155** [comment]
created #3038, close this.
