### ISSUE TITLE
Drasil Research Group Meeting Agenda, Week of August 18th 12:00pm (On Teams)

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3038]
The agenda for this coming week is as follows:

1. Jason update
2. Peter update
3. Dong update
4. Scheduling next meeting
5. Cold cases/Code Review/Discussion
a. @peter-michalski - #1599
b. @balacij 
c. @cd155 
d. @JacquesCarette [DSL for inforgraphics](https://modeling-languages.com/model-driven-production-of-data-centric-infographics/) as a really interesting case of "knowledge capture" (placeholder for the following week). [The way we cite](https://arxiv.org/abs/2205.13419)'s Table 1 is another really good example.
6. Questions/Comments/Concerns/Discussion

**Comment by smiths** [comment]
Thank you for creating this @cd155.  Looks good.

**Comment by smiths** [comment]
We covered everything in the agenda, except for 5d, which has been added to the next week's agenda (#3040).
