### ISSUE TITLE
Drasil Research Group Meeting Agenda, August 24 (On Teams)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3040]
The agenda for this coming week is as follows:

1. Dong update
2. Jason update
3. Peter update
4. Cold cases/Code Review/Discussion
a. @balacij 
b. @cd155 
c. @peter-michalski 
d. @JacquesCarette [DSL for inforgraphics](https://modeling-languages.com/model-driven-production-of-data-centric-infographics/) as a really interesting case of "knowledge capture" (placeholder for the following week). [The way we cite](https://arxiv.org/abs/2205.13419)'s Table 1 is another really good example.
5. Questions/Comments/Concerns/Discussion

**Comment by smiths** [comment]
@peter-michalski, when you get a chance you should have a look at item 4.d about a DSL for infographics.  The infographic example makes the vocabulary for infographics explicit.  Similar to this we will want to make the vocabulary for Drasil explicit.

**Comment by cd155** [comment]
We also recorded our conversation about 4.d, it should be available on Teams

**Comment by peter-michalski** [comment]
@smiths, thanks for bringing my attention to this. There certainly are some good ideas and methodologies to consider applying in Drasil projects. It would be nice if we had access to the paper.

**Comment by smiths** [comment]
@peter-michalski we may have access to the paper.  The Library has many subscriptions to on-line journals and resources.  Try searching for the journal/conference on the [library page](https://library.mcmaster.ca/).
