### ISSUE TITLE
Add haddock syntax guildline in Drasil Wiki

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3041]
Drasil source code uses Haddock to generate code documentation. Haddock has a specific format to change Haskell's comments into a Haddock document. For example, the syntax below
```code
-- |
```

Website https://haskell-haddock.readthedocs.io/en/latest/markup.html, gives the example and instructions. I think this information better included in the Drasil Wiki.

**Comment by smiths** [comment]
I agree @cd155 that this information would be useful.  We could add it to the [Contributor's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#contributors-guide).

**Comment by cd155** [comment]
I added this part in [Contributor's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#coding-style) - Coding Style
