### ISSUE TITLE
Chapter 4 Connect Model to Libraries - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3042]
Chapter 4 Connect Model to Libraries is ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/chapter4.tex

last commit a06b175cfe361c36a260c6253e4170ea92899686

**Comment by smiths** [comment]
Feedback on Chapter 4 is available in 517ba233d.  Please let me know if you have any questions, or if you can't read any of my writing.  :smile:
