### ISSUE TITLE
Summary of future work - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3044]
Summary of future work is ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/futurework.tex

last commit fc55482389edf948f8b60ea38a50dcfa16070876

**Comment by smiths** [comment]
Feedback on Chapter 4 is available in 517ba233d.  Please let me know if you have any questions, or if you can't read any of my writing.  :smile:

**Comment by smiths** [comment]
I put my comment in the wrong issue.  :smile:  I'll close this issue once I've reviewed Chapter 5.

**Comment by smiths** [comment]
Feedback on Chapter 5 is provided in e1e53806e.
