### ISSUE TITLE
`drasil-website`: "Package: drasil-all-pkgs-deps" graphs don't show up

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3047]
https://jacquescarette.github.io/Drasil/

At the bottom of the websites homepage, the "all package dependencies" graphs appear to be broken.

**Comment by peter-michalski** [comment]
Looks like `make packagedeps `was not run

**Comment by balacij** [comment]
Ah, do we just need to add that to our Actions workflow then?

**Comment by peter-michalski** [comment]
@balacij, correct me if I am wrong, but it appears that we do not run `make deploy` in the Actions workflow. 

I had thought that deploy was run to generate the website and had added `packagedeps` there. 

I can add `packagedeps` to `graphs` to fix the issue,

`graphs: $(GRAPH_PACKAGES) packagedeps `,

but am now wondering what `deploy` is actually used for. It is just for testing locally?

**Comment by balacij** [comment]
Yep, `make deploy` is meant for local development. `scripts/deploy_wrapper.bash` and `make deploy_lite` together are a stripped down version of it, specifically intended for deploying the website. I _think_ this was done a long time ago to have the CI steps highlight a bit more, to not just have the CI "steps" be a single gigantic `make deploy` command that hides information. More information about this should be in the `Makefile` and the `deploy_wrapper.bash` files.

I _think_ that adding `packagedeps` as a dependency of the `graphs` target is a good idea too.

**Comment by peter-michalski** [comment]
This can be closed with #3050
