### ISSUE TITLE
Conclusion and Abstract - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3048]
Conclusion and Abstract are ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

conclusion tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/conclusion.tex

abstract tex file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/abstr.tex

last commit 525c4ad920cfaa26b70f517144b93e7e27545ba5

**Comment by smiths** [comment]
I reviewed these as part of #3049.
