### ISSUE TITLE
Overall Review - MEng Report

### ISSUE THREAD

**Issue by cd155** [JacquesCarette/Drasil#3049]
All parts are ready for review.

pdf file: https://github.com/JacquesCarette/Drasil/blob/dongFixWhenWritting/People/Dong/report/templates/Thesis_Main.pdf

This ticket is for reviewing the report as a whole.

**Comment by smiths** [comment]
@cd155 I've added feedback up to Chapter 2 in b27772382.  I will add more feedback either later tonight or tomorrow.

**Comment by smiths** [comment]
@cd155 I've completed the feedback on your report in c94429203.  In addition to the comments written on the report, please add additional references to the Drasil framework, as follows:

- use [the Drasil citation file](https://github.com/JacquesCarette/Drasil/blob/master/CITATION.cff) to generate a BibTex entry
- from the [References.bib] file include SzymczakEtAl2016

If you have any questions or comments @cd155, please let me know.  In particular, I found that I was making the same comments on this revision as I did when I reviewed individual chapters (especially for Chapter 4 and the in-text symbols versus the in-equation symbols).  If there is something you don't know how to do or a comment you don't understand, please ask.

**Comment by cd155** [comment]
@smiths I complete editing most feedback. Some I wasn't sure and I listed them as follows:

(the page numbers are a reference to the feedback version)

- List of Code (page ix): I change all words with the necessary capitalization. It is the same as the format in the list of figures and list of tables. It is slightly different than the comment suggested.
- Chapter 0 (Intro page 1): some comments I don't know what it is 
  - "Programmers usually write software in a specific language and produce other byproducts, like documentation and **??** (this is test cases?)"
- Chapter 2 (Intro page 6):
  - there is a long comment on the first page's left side. "The higher order from is suitable for presenting the **??**, but..." 
  - "The new structure **??** allow the different forms to be isomorphic, ..."
- Chapter 3
   - intro part (page 22): "Creating a complete ODE solver in Drasil would take considerable time and there are **alternative**(is this right word); many reliable external libraries that have been tested by long **use**(is this right word).
   - In 3.1 (page 25), "The ???? ((1.0 +K d) * y t[1] + -(20.0 + K p) * y t[0] + r t * K p) represents the second equation". is it "the second value in the relative list"?
- Chapter 4 (page 39): To explain matrix data type. I added a parenthesis after introducing matrix. "... by matrix (it is not A, it is just a wrapper for a vector), ..." is this enough
- Future work
  - 5.4, "you can solve with an adaptive solver and still output the results of a fixed **??**". Where should I add this sentence?
 
Lastly, there are two references I need to add, 

- [the Drasil citation file](https://github.com/JacquesCarette/Drasil/blob/master/CITATION.cff)
- SzymczakEtAl2016

Do you know where I should reference my thesis? The Drasil citation file is a reference to the whole Drasil project. Should I reference it when it first appears?
For SzymczakEtAl2016, it talks about capturing knowledge in Drasil. I wasn't sure where exactly I should reference, or just the reference should be enough?

**Comment by smiths** [comment]
> @smiths I really appreciate all the feedback. I complete editing most feedback. Some I wasn't sure and I listed them as follows:
> 
> (the page numbers are a reference to the feedback version)
> 
> * List of Code (page ix): I change all words with the necessary capitalization. It is the same as the format in the list of figures and list of tables. It is slightly different than the comment suggested.

As long as you are consistent in the capitalization, that's fine with me.

> * Chapter 0 (Intro page 1): some comments I don't know what it is
>   
>   * "Programmers usually write software in a specific language and produce other byproducts, like documentation and **??** (this is test cases?)"

Yes, the text says "test cases".  "Programmers usually write software in a specific language and produce other byproducts, like documentation and test cases."

> * Chapter 2 (Intro page 6):
>   
>   * there is a long comment on the first page's left side. "The higher order from is suitable for presenting the **??**, but..."

The higher order form is suitable for presenting the physics but the system form is suitable for solving the ODE numerically.

>   * "The new structure **??** allow the different forms to be isomorphic, ..."

The new structure must allow the different forms to be isomorphic, which means we can made one ODE form to another.

> * Chapter 3
>   
>   * intro part (page 22): "Creating a complete ODE solver in Drasil would take considerable time and there are **alternative**(is this right word); many reliable external libraries that have been tested by long **use**(is this right word).

Creating a complete ODE solver in Drasil would take considerable time and there are already many reliable external libraries that have been tested by long use.

>   * In 3.1 (page 25), "The ???? ((1.0 +K d) * y t[1] + -(20.0 + K p) * y t[0] + r t * K p) represents the second equation". is it "the second value in the relative list"?

The second value in the returned list ((1.0 +K d) * y t[1] + -(20.0 + K p) * y t[0] + r t * K p) represents the second equation, ...

> * Chapter 4 (page 39): To explain matrix data type. I added a parenthesis after introducing matrix. "... by matrix (it is not A, it is just a wrapper for a vector), ..." is this enough

Parentheses are fine, but I think you want more information.  Maybe something like (In Drasil the data type matrix is used to represent both a 1D matrix (conventionally called a vector) and a 2D matrix.)

> * Future work
>   
>   * 5.4, "you can solve with an adaptive solver and still output the results of a fixed **??**". Where should I add this sentence?

You can solve with an adaptive solver and still output the results at a fixed step size.

Your presentation makes it sound like the output of an adaptive solver automatically uses the adapted step sizes.  You can add a sentence somewhere to clarify that a user can control the output of the  adaptive solver to output values at their required values for the independent variable (time).

> 
> Lastly, there are two references I need to add,
> 
> * [the Drasil citation file](https://github.com/JacquesCarette/Drasil/blob/master/CITATION.cff)
> * SzymczakEtAl2016
> 
> Do you know where I should reference my thesis? The Drasil citation file is a reference to the whole Drasil project. Should I reference it when it first appears? For SzymczakEtAl2016, it talks about capturing knowledge in Drasil. I wasn't sure where exactly I should reference, or just the reference should be enough?

The Citations to Drasil can be included right after you mention it the first time.  I believe that will correspond to the first sentence of your Introduction.

**Comment by cd155** [comment]
@smiths I completed the editing, and this is the version for the examiner. dd0fcf7797a5f4edb7be00f7406ff461d66715a2

Again, I really appreciate the details of feedback you provided, it really helped to make this report better.

**Comment by smiths** [comment]
Great!  I will forward your report to the examiner tonight.

**Comment by cd155** [comment]
Hi Dr. @smiths, just a quick follow-up regarding my final report. Is there any update? I think you mentioned the examiner will probably respond to us by Thursday.

**Comment by smiths** [comment]
@cd155, I was going to be writing you about this shortly.  The reviewer had a minor request for some additional information.  Once you add the information, you'll be done your MEng!  I'll send you the details shortly.  Congratulations!  You'll be done very soon.  :smile:

Once the changes are made, please do a PR to pull your branch into main.  I didn't want to forget to remind you to do that.  :smile:

**Comment by cd155** [comment]
No problem, thanks for the arrangement in such a timely manner. It really eases my nerve, and it is my great pleasure to work with you and Dr. @JacquesCarette. I will make sure I make the PR to the main branch. It should include my final report and some refined comments.
