### ISSUE TITLE
Generate SRS in .ipynb format

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3078]
Generate .ipynb file for all examples and fix the formatting issues so it can be read by the Jupyter Notebook.

**Comment by tingyuw** [comment]
JSON format for all SRS examples will now be generated. Formatting issues are fix as well. We can view and open the SRS in Jupyter Notebook. The file for each example can be found under path ../SRS/JSON/example.ipynb. There are still some references and equations need to be fixed. 

Reminder: Add .ipynb_checkpoints to gitignore.

**Comment by tingyuw** [comment]
Fix this issue #2761 in SRS.

**Comment by JacquesCarette** [comment]
Nice progress. Looking forward to the PR.

**Comment by tingyuw** [comment]
Closing this as it's been merged to master.
