### ISSUE TITLE
Extra Comma in Projectile Data Constraints

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3087]
The highlighted comma shown below should be removed, since the independent clause comes before the dependent clause (if they were reversed, the comma would be necessary).

![image](https://user-images.githubusercontent.com/35857611/199798001-eb887b05-a6dd-4fcd-b1fe-d2923d734d29.png)

**Comment by smiths** [comment]
Agreed.  Good catch.

**Comment by smiths** [comment]
I wonder if the same mistake exists in the other examples.  Hopefully, we shared any generic description of the table between examples, so fixing it for the projectile example will fix it for any other examples.
