### ISSUE TITLE
Chapter 6: More Theories Ready for Review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3099]
Please let me know what you think about about chapter 6. I've posted it to `jasonRewritingCh4`.

This chapter comes from feedback from Chapter 4 as it was mixing up Research Questions. This chapter in particular is the split of many more of the theories post-creation of ModelKinds and the language division.

**Comment by JacquesCarette** [comment]
This is much more concrete now, which is good. However, for easier comprehension, you should give the examples in "human readable form" as well as in code form. (Source code 6.2 and 6.4 for example).

Even better would be a section, to come before the current 6.1, where these "other kinds of theories" would show up, purely in human-readable format. You could then analyze them, in that form. That would then motivate the encoding that happens in the current 6.1

Yes, [27] is the correct reference for Realms.

"Dong's work", not Dongs.
