### ISSUE TITLE
Chapter 8: ChunkDB Ready for Review

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3100]
Chapter 8 is posted on `jasonRewritingCh4` branch. Since you last reviewed it, the chapter number got bumped up because I split up chapter 4 into 3 chapters. I believe I addressed the grammar issues, and I filled in all the code snippets. LanguageTools doesn't give me any errors anymore, but I'll give it another read-through later too.

**Comment by JacquesCarette** [comment]
The writing directives here aren't as crisp as some of the others... that's usually a bad sign!

Having said that, this chapter is good enough. If we had lots of time, I could pick on a bunch of things, but none of them are important enough to prevent you moving forward to defending.

**Comment by balacij** [comment]
Sounds good. Thank you very much! :smile:
