### ISSUE TITLE
Type checking error in ssp EqModel: nrmShrFor

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3106]
Related to #3093, similar to #3105 

```
`nrmShrForIM` exposes ill-typed expressions!
  - List accessor expects a list/vector
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs#L374-L388

**Comment by JacquesCarette** [comment]
Fixed by #3158
