### ISSUE TITLE
Type checking error in GlassBR DD: `demandq`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3115]
Related to #3093 

```
`demandq` exposes ill-typed expressions!
  - ERROR: Function application on non-function `interpY` (Real).
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/glassbr/lib/Drasil/GlassBR/DataDefs.hs#L225-L233

**Comment by JacquesCarette** [comment]
Just a note that I'll leave all "Function application" problems to last, as I'm afraid that functions are ill-supported in the current code base.
