### ISSUE TITLE
Import SWHS Content with better Implementation of acro-

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#312]
Once likely changes, assumptions, etc. are able to be referenced via a predefined id and are no longer manually defined, import sections 4.2, 5.1 and 6  from SWHS where applicable.

**Comment by njericha** [comment]
#276

**Comment by AKM11** [comment]
This is a note to self for something slightly different.

**Comment by AKM11** [comment]
At this point Likely Changes and most of the Assumptions have been imported. Still need to work on Requirements (implement in SWHS), Instance Models (issue #276), Data Definitions, etc.

**Comment by JacquesCarette** [comment]
This should be looked at for 'completion'.  I think that @halonazhao has also worked on this. And most definitely the various `acro` functions should NOT be used.  They were a solution idea that turned out to not be a good idea at all!

**Comment by elwazana** [comment]
@JacquesCarette So should I remove the acro- functions from,
https://github.com/JacquesCarette/Drasil/blob/95532f9a012c8d034312beb1fdfe3cf2b88a7007/code/Data/Drasil/SentenceStructures.hs#L109-L122
https://github.com/JacquesCarette/Drasil/blob/95532f9a012c8d034312beb1fdfe3cf2b88a7007/code/Data/Drasil/Concepts/Documentation.hs#L15-L26

and if so, should I replace them with anything?

**Comment by JacquesCarette** [comment]
Yes - by the proper referencing system that @szymczdm has implemented. It's best if he shows you an example or two.

**Comment by samm82** [comment]
#987 removes all of these `acro-` functions - is this issue closed then? @JacquesCarette

**Comment by JacquesCarette** [comment]
It will be as soon as #987 is actually merged in. You should look at #360 and #742 as well once you're done this, as I think they are both 'affected'.

**Comment by JacquesCarette** [comment]
Actually, now that I reread the whole thing carefully, I am not 100% sure that it is all done. This seems to be about NoPCM content that might not be present, even though it is there in SWHS.

**Comment by samm82** [comment]
@JacquesCarette Is this an OK implementation? I have it now that NoPCM uses `acronyms` and SWHS uses `acronymsFull`

https://github.com/JacquesCarette/Drasil/blob/2b26c28212acfd861eace23938cbd7966a0cf8e8/code/drasil-example/Drasil/SWHS/Concepts.hs#L12-L18

Other that this, I think NoPCM already takes what it needs from SWHS

**Comment by JacquesCarette** [comment]
Yes.  And good!
