### ISSUE TITLE
Merge `addRe` and `addI`, and `mulI` and `mulRe`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3153]
I agree about merging `addRe` and `addI` and hiding.

        The errors are real (pun intended) basically because none of those things should be `Rational`, that seems like a plain hack that should be fixed.

_Originally posted by @JacquesCarette in https://github.com/JacquesCarette/Drasil/issues/3131#issuecomment-1327661632_

**Comment by daijingz** [comment]
@balacij Jason, I want to work on this issue. Although previously I did not do any difficult questions. I want to have a try.

The code is at \code\drasil-lang\lib\Language\Drasil\Expr\Class.hs
![@LR5 3D5F$BOTHQ5D$SQXW6](https://github.com/JacquesCarette/Drasil/assets/61481741/64d95f3f-9757-49e2-916b-9da75995bca9)

In my opinion, the first part we need to do is check whether both function types are compatible or not. However, both functions have arbitrary types, so I need to check other function callings first.
![H_CBJM4%EPKQJ9MVWE5 QVK](https://github.com/JacquesCarette/Drasil/assets/61481741/3c531c15-284a-48c8-b171-c3382263d682)
