### ISSUE TITLE
Typechecking error in GamePhysics: v_i^AB

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3162]
Meta-comment: super-hard to track these down, as it's only detected through chasing down a long tunnel starting at `v_i^AB`, but really happening somewhere else.
```
`v_i^AB` exposes ill-typed expressions!
  - ERROR: Both operands of an (in)equality (=/≠) must be of the same type. Received `Vect Real` & `Real`.
```

So first thing to figure out is what this is (from Unitals)
```haskell
initRelVel = ucs' (dccWDS "v_i^AB" (compoundPhrase'
                 (compoundPhrase' (cn "initial relative") (QP.velocity ^. term))
                 (cn "between rigid bodies of A and B")) (phrase QP.velocity))
                 (sup (sub (eqSymb QP.velocity) QP.initial) (Concat [lBodyA, lBodyB])) (Vect Real) velU
```
Note that the UID is very different than `initRelVel`, which is now what must be used to really track things down. 

From DataDefs:
```haskell
reVelInColl :: SimpleQDef
reVelInColl = mkQuantDef initRelVel reVelInCollEqn

reVelInCollEqn :: Expr
reVelInCollEqn = sy velAP $- sy velBP
```
So indeed, that `SimpleQDef` is ill-typed since the lhs is `Vect Real` and the rhs is `Real`. I think the rhs should be a vector too? @smiths ?

**Comment by JacquesCarette** [comment]
Once you've figured out what the types should be @smiths , assign the fixing to me, unless you want to dig in yourself!

**Comment by smiths** [comment]
Yes, both sides of the equation should be `Vect Real`.  I'll assign the fix to you @JacquesCarette.  I'd like to do some coding in Drasil, but this doesn't feel like the right entry point.
