### ISSUE TITLE
Drasil Research Group Meeting Agenda, Wednesday Dec. 7 at 8:00 am (On Teams)

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3184]
The agenda for this coming week is as follows:

1. Jason update
2. Ting-Yu update
3. Sam update
4. Peter update
5. Cold cases/Code Review/Discussion
  b. @balacij
  c. @peter-michalski
  d. @tingyuw
  a. @samm82
  e. @cd155
  f. Update/change Projectile example (@smiths)
6. Questions/Comments/Concerns/Discussion

(Have to send my regrets as I'll be working in someone else's living room that day!)

**Comment by smiths** [comment]
All agenda items were covered.  Next meeting #3185.
