### ISSUE TITLE
Update the used Stackage & GHC version

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3204]
The latest Haskell Language Server (HLS) release, [1.9.0.0](https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html), has deprecated support for GHC 8.8.4 (which we use). I'm not fully sure why they've chosen to do this, but I imagine it's just an issue of maintenance. 

If new users come across Drasil and want to use it, they _might_ want to use HLS (as I do). The typical way to install HLS is using the prebuilt binaries and currently supported GHC versions. As such, users would need to install from source to use HLS with Drasil.

It seems that the Haskell community navigates HLS developments against "current" stackage & GHC versions. So, I wonder: should we upgrade our focused GHC version? If so, should we also upgrade from the Haskell2010 language spec. to GHC2021?

The current Stackage version is [20.5](https://www.stackage.org/lts-20.5) and uses GHC version 9.2.5.

Naively updating the Stackage version to 20.5 doesn't appear to cause any errors, but it does result in some build warnings that we would need to resolve.

**Comment by smiths** [comment]
@JacquesCarette has more expertise than me, but my instinct is that we should update.  It won't get easier over time.  Maybe we could wait until the summer, with the hope that we'll have a summer student that can help with any migration issues that arise?

**Comment by balacij** [comment]
Sounds good, thank you.

Regarding the changes, I'm more than happy to make the changes. I don't there are too many needed changes. I changed the logs and I'm having the [CI run](https://github.com/JacquesCarette/Drasil/actions/runs/3843220511/jobs/6545283072) to show all the warnings that pop up now.

**Comment by JacquesCarette** [comment]
If it's easy, we should upgrade.

**Comment by balacij** [comment]
I'll handle it.

Aside: "difftastic" is a nice drop-in replacement to "diff"!

![Screenshot from 2023-01-06 09-50-52](https://user-images.githubusercontent.com/1627302/211036229-7606cc15-c513-4c02-962b-2e295c40d242.png)
