### ISSUE TITLE
Projectile: Add Background information to Projectile

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3206]
As discussed in #3159 there are different chunks (pieces?) of information within each example.  One example for the README that was discussed is background information.  The Projectile example is lacking background information.  Therefore, I propose adding the following to the Projectile SRS in the introductory paragraph, after the second sentence:

"Common examples of projectile motion include ballistics problems (missiles, bullets, etc.) and the flight of balls in various sports (baseball, golf, football, etc.)."

**Comment by samm82** [comment]
Just a note that this should probably go in the Introduction section.

**Comment by smiths** [comment]
@harmanpreet-sagar I'm assigning this issue to you because we'd like to get it closed to make Projectile a strong basis for other projects.  In the Drasil implementation, it would be good if you identified the information that is being added as examples.  Eventually the notion of examples will be something that is likely to appear in more of the case studies.
