### ISSUE TITLE
Projectile: Update TM:acceleration and TM:velocity - add explicit dependence on time and vector information

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3210]
In the Projectile example, TM:acceleration and TM:velocity do not explicitly show that the acceleration and velocity depend on time.  The equations should be changed to include t:

**a**(t) = d**v**(t)/dt and **v**(t) = d**p**(t)/dt

The Description field of TM:acceleration and TM:velocity should also explicitly say that **a**, **v** and **p** are vectors.  For instance, instead of saying **a** is the acceleration, it should say that **a** is the acceleration vector.

**Comment by ManvendraJani** [comment]
@smiths what would be the difference between the `linearAccel` and `acceleration`  conceptually?  

Since their types would conflict if acceleration would be represented as a funtion of time, they would both be a_vect(t) causing issues in the generated code. I was wondering why we can't use either/or exclusively?

**Comment by smiths** [comment]
@ManvendraJani, I'm assuming that `linearAccel` and `acceleration` are variables in the Drasil code.  I haven't looked at the Drasil code recently, so I'm not sure what distinction is made in the code.  My guess though is that `linearAccel` is related to rectilinear motion and `acceleration` is related to the more general concept of acceleration.  If you look at the SRS acceleration is defined in [TM:accleration](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#TM:acceleration).  This concept defined the acceleration vector in terms of the time rate of change of the velocity vector.  [GD:rectVel](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#GD:rectVel) defined the rectilinear (1d) velocity as a function of time for constant acceleration.  The equation for GD:rectVel shows a vector, but it shouldn't.  This equation is a 1D equation.  The acceleration here is a scalar, not a vector.
