### ISSUE TITLE
Projectile: Code: Change `g_vect` to `G`

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3219]
The constant for the gravitational acceleration in the [Projectile code](https://github.com/JacquesCarette/Drasil/blob/09365d7d1f5dc9b54e84a8d64cb601184456ea0c/code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/Projectile.py) is currently `g_vect`.  This name is a bit odd, since it is a symbolic constant that is not in ALL_CAPS and g is a component of acceleration, not a vector.  For this issue, we want to change the symbol from `g_vect` to `G`.  (`G` is also problematic since capital `G` is often used to represent Newton's gravitational constant, but this seems like a good compromise at the moment.)

Part of this issue is to record the steps required to make the change of the symbol.  The hope is that the code will only need to be touched in one spot.  This then will give us another simple example of the benefits of the Drasil approach.

A nice bonus would be if the units for `G` were generated as a comment in the code.

**Comment by samm82** [comment]
Is this value not a vector, as gravitational acceleration is in the "down" direction? Throughout the documentation, the symbol for gravitational acceleration is bolded, following the convention for a vector.

**Comment by smiths** [comment]
@samm82 I can see the source of confusion.  The acceleration can be expressed as a vector, but in the projectile example, we are using a scalar component of the vector, not a vector.  The g should not be bolded.  Bold **g** as a vector would be [0 -9.81].  If we put this in an equation, like IM:calOfLandingTime (the time of flight), you'll see we are dividing a scalar by the vector **g**.  This is a mathematical operation that doesn't make any sense.

The bold **g** is confusing.  There is a separate issue about the mix of 1D scalars and 2D vectors (#3189).

**Comment by ManvendraJani** [comment]
@smiths A few of the other directories are using both the Gravitational constant and gravitational acceleration, i.e. gamephysics, so we wont be able to use `G`. Were there any issues with using just lower case `g`?

**Comment by smiths** [comment]
@ManvendraJani, yes, use the lower case g.  I like constants to be in ALLCAPS, but the symbol g is commonly used by convention.  I actually think g is better than G, now that I look at it again because of the class with the Gravitational constant.
