### ISSUE TITLE
Improve logging of design decisions in `designLog.txt`

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3222]
In the `designLog.txt` file, which shows the values of the design variabilities for a given generated example, the text when there is no logging code generated is incomplete.  When there is no logging, the following is output in the `designLog.txt` file:

`Logging selected as.`

As an example, this is the output in the [`designLog.txt`](https://github.com/JacquesCarette/Drasil/blob/09365d7d1f5dc9b54e84a8d64cb601184456ea0c/code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/designLog.txt) file for [projectile_u_p_nol_u_wi_v_d](https://github.com/JacquesCarette/Drasil/tree/09365d7d1f5dc9b54e84a8d64cb601184456ea0c/code/stable/projectile/projectile_u_p_nol_u_wi_v_d).

I suggest that we change the output in this case to:

`Logging selected as None.`

**Comment by balacij** [comment]
The actual `designLog.txt` file is also ignored by the `diff` checks against `stable/`. It _might_ be good to add it back so that people remember to also update the `designLog.txt` files when they update `stable/`.

**Comment by JacquesCarette** [comment]
I'll bump that up to "would be a really goo idea" to add it back. [Why was it removed?]

**Comment by balacij** [comment]
I'm not too sure why it was removed (it might have been an accident? I remember changing `designLog.txt` files previously), but I can probably handle this ticket (and the bit about adding the `.txt` file inclusion to the `diff`s). However, as always, if anyone wants to knock it out before me, please feel free to.
