### ISSUE TITLE
CITATION.cff degraded?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3229]
It looks like GitHub's generated citation for Drasil (from the CITATION.cff file) has degraded a bit:

```
@software{The_Drasil_Research_Team_Drasil,
author = {{The Drasil Research Team}},
title = {{Drasil}}
}
```

Now it doesn't seem to be printing the URL of the repository, nor any sort of versioning.

**Comment by smiths** [comment]
Yes, this generated BibTeX is not as detailed as it was previously.  I used the old generated file to add a Drasil entry to [`References.bib`](https://gitlab.cas.mcmaster.ca/smiths/pub/-/blob/master/References.bib) in the pub repo.  The old version include all authors and other details.

I did a quick check using [`cffconvert` for validation](https://github.com/citation-file-format/citation-file-format/blob/main/README.md) and the output was simply: `Citation metadata are valid according to schema version 1.2.0.`.  I don't think we have any problems on our end.  The GitHub BibTeX (and APA) generator must have been changed.  Maybe they added "functionality" to reduce large lists of co-authors to a generic Team placeholder?  I liked it better the old way, even if it was a long citation.

**Comment by balacij** [comment]
I think that GitHub changed something with how `preferred-citation` is handled. It seems that only the fields manually set in that object is being used now (this is not how it was previously).

The change to the authors list was intentional (#3023) for inclusivity of all contributors, but the recent removal of the URLs, license, etc. was not.

Comparing to the original citation (below, from the pub repo), I think we should at least have the license, url, and year. I'm not quite sure how important versioning is with Drasil, however.

```
@software{CaretteEtAl2021-Drasil,
	author = {Carette, Jacques and Smith, Spencer and Balaci, Jason and Hunt, Anthony and Wu, Ting-Yu and Crawford, Samuel and Chen, Dong and Szymczak, Dan and MacLachlan, Brooks and Scime, Dan and Niazi, Maryyam},
	date-added = {2022-03-03 11:08:55 -0500},
	date-modified = {2022-03-03 11:09:14 -0500},
	license = {BSD-2-Clause},
	month = {2},
	title = {{Drasil}},
	url = {https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha},
	version = {v0.1-alpha},
	year = {2021},
	bdsk-url-1 = {https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha}}
```

**Comment by balacij** [comment]
I will assign myself to 'fix' this issue, but I think we just need to settle what fields we want to show in the preferred citation, and if we even want the preferred citation as it currently is (e.g., the author names).

**Comment by smiths** [comment]
I agree that we at least want the license, url and year.  I like the idea of including the version of Drasil, to make the citation unambiguous, but I'd be okay if that doesn't get included.  With respect to the authors, I prefer listing everyone, but it isn't a strong preference.

**Comment by samm82** [comment]
> I don't have any preference for the authors list vs bubble name. If we do go down the authors list, should we consider an alternative ordering of the names?

How feasible would it be to maintain a sort by contributions (as shown in the Insights tab)?

**Comment by smiths** [comment]
The proposal from @samm82 sounds good to me.  @JacquesCarette should definitely go first in the order of contributions.  Different arguments could be made on where I should go in the list, since I don't write code, but the convention is that supervisors either go early in the list, or last, and I don't want to be last.  :-)  (Another convention is alphabetical, but I've never really taken to that convention.)

**Comment by samm82** [comment]
I think that the number of questions you answer just from me is enough to put you near the front 😂

**Comment by balacij** [comment]
I agree that @JacquesCarette and @smiths should be at the top of the list. However, I'm not sure how we could sort the others by contribution. The [Contributions](https://github.com/JacquesCarette/Drasil/graphs/contributors) page uses commits, but I don't think that I'm the 2nd highest contributor to Drasil. Did you have a scheme in mind?

Does the order of the people other than the PIs matter? I would be fine with it being an append-only list sorted by time the user started working on Drasil, for example.

**Comment by samm82** [comment]
Appending based on user start is probably the easiest to maintain, since we don't need to keep resorting the list

**Comment by smiths** [comment]
If we have to automate sorting our author list, using start date is fine.  However, I prefer the original idea of the list starting with the two PIs and then sorted by number of commits.  If we look at the list manually ever time we cite it, we can update the list at the time of citation.

**Comment by balacij** [comment]
Okay, to be clear, preferred citation needed changes:

1. Add year
2. Add website URL
3. Add license
4. Add version
5. Switch preferred citation from "The Drasil Research Team" to the list of names

I think it might be easier to just remove the "preferred-citation" section entirely, which now appears to override the other fields which would be used normally.

Should I make a PR to close this ticket?

**Comment by JacquesCarette** [comment]
Yes, please make a PR to close this ticket. I'm happy with @smiths latest proposal on ordering. It still has Dan very high up, which is appropriate.
