### ISSUE TITLE
Duplicate "the" (coming from `the_ofThe`, etc.?)

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3234]
From my investigation in #3199, I noticed some `UnitalChunk`s with sentences built using `the_ofThe`, etc. but also having "the" prepended (these specific examples from DblPendulum):

https://github.com/JacquesCarette/Drasil/blob/1831438948f4bb92ba7050a27ccbff6489904784/code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Unitals.hs#L90-L92
https://github.com/JacquesCarette/Drasil/blob/1831438948f4bb92ba7050a27ccbff6489904784/code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Unitals.hs#L98-L100
https://github.com/JacquesCarette/Drasil/blob/1831438948f4bb92ba7050a27ccbff6489904784/code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Unitals.hs#L58-L60
https://github.com/JacquesCarette/Drasil/blob/1831438948f4bb92ba7050a27ccbff6489904784/code/drasil-example/dblpendulum/lib/Drasil/DblPendulum/Unitals.hs#L146-L148

I believe this results in "the" being duplicated:
![image](https://user-images.githubusercontent.com/35857611/211656239-fbccdcab-18ef-4ab0-a5a2-053ef6fb476f.png)

**Comment by JacquesCarette** [comment]
Nicely spotted!

**Comment by cd155** [comment]
The problem occurs while using the combination of `phraseNP` and `"the_ofThe"`. 

For example, 
``` nounPhraseSent $ phraseNP (horizontalVel `the_ofThe` firstObject) ```

`the_ofThe` will add "the" at the beginning, but the whole word is treated as an `NP`. The second "the" will be added when Drasil thinks "the whole word" is singular.

If we change the `the_ofThe` to `ofThe`, will remove the extra "the" from the definition. However, this will also remove "The" from the Table of Symbols.

**Comment by JacquesCarette** [comment]
This code seems to be quite cursed: it really visibly adds `the` twice. Worse, it does its own capitalization. And it duplicates things too.

**Comment by smiths** [comment]
At the risk of glossing over a more serious issue, I'm completely fine with the last idea from @cd155.  That is, using `ofThe` is fine with me.  The consequence is removing the "The" from the Table of Symbols, but that "The" isn't really necessary.  If we say vx1 is the "horizontal velocity of the first object" that is fine with me.  We don't have to say "The horizontal velocity of the first object".  I looked at the GlassBR example and it isn't full of "the"s in the table of symbols.  Including a "The" in the definition of the symbol seems like unnecessary information, especially since we can add a "the" if we want to with the combinators.

**Comment by samm82** [comment]
I agree with @smiths here; making our descriptions more consistent is a good idea, especially if it also works to remove errors elsewhere. It will be interesting to see the implications of this change!

@JacquesCarette How do you propose handling the duplication? Define a local `Sentence` (like `lenRod_1Desc`) and use it twice? We could potentially introduce a `UnitalChunk` constructor for simple terms (where the term is the description), but means creating more constructors, which could potentially introduce unwanted complexity (#3199).

**Comment by JacquesCarette** [comment]
Yes, at this point, something as simple as `lenRod_1Desc` would do. Let's not introduce more constructors, but see what we do in practice first.

**Comment by ManvendraJani** [comment]
@samm82 I am not sure why we use 
```
nounPhraseSent $ phraseNP(len `the_ofThe` secondRod)
``` 
instead of just 
```
(len `the_ofThe` secondRod)
```

**Comment by samm82** [comment]
Just by looking at the code, me neither. I can't verify that the types all match up with 100% certainty, but if everything works using the second approach, I agree that it is much nicer
