### ISSUE TITLE
Review ChemCode Problem Statement

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3240]
The Problem Statement for ChemCode can be found [here](https://github.com/JacquesCarette/Drasil/tree/chemCode/People/Sam/ChemCode/Problem%20Statement).

**Comment by balacij** [comment]
I just added the "CAS 741" label -- it might just be good to differentiate our stuff from the other tickets?

**Comment by smiths** [comment]
Great work @samm82.  This might be the best problem statement I've read for a course project.  :smile:  In some scholarly writing the use of the first person would be a problem, but for a problem statement as part of a graduate course, the first person is entirely appropriate.  The project is your project after all.  Using "I" might feel strange, but referring to yourself by your name in a project where you are essentially the sole developer would feel stranger.  :smile:

Your project is approved.  I'll update `Repos.csv` in the cas741 repo to reflect this.
