### ISSUE TITLE
Real literals with exponential notation

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#325]
As mentioned in issue #320, showing real literals without the multiplication symbol looks odd.  That is, 7.0(10^7) would look better as 7.0 x 10^7.

**Comment by niazim3** [comment]
Update: there are no longer "( )" around the base number
Current output in HTML is as follows:
![image](https://user-images.githubusercontent.com/28247301/40071747-b5c2fb1e-583f-11e8-81d5-fa7b1b6b2ba0.png)
Current output in LaTeX is as follows:
![image](https://user-images.githubusercontent.com/28247301/40071882-11208530-5840-11e8-8d3a-08e5fa228e74.png)

**Comment by JacquesCarette** [comment]
Right now there's a hack in the source to input 'scientific'-like notation, which used to have a further hack to make it print nicely.  The printing hack is gone, making things work.

The right fix is to print doubles using scientific notation, especially as soon as they involve scales larger than 6 (i.e. xxxey with |y|>= 6). Then all the hacks in the source can be removed.

**Comment by JacquesCarette** [comment]
@halonazhao I think your recent fixes have fixed this!  Can you double-check (and then probably can close this).

**Comment by JacquesCarette** [comment]
This is still open, yet I am pretty sure that @halonazhao did fix all of this. Could you check please?

**Comment by halonazhao** [comment]
Yes, this issue can be closed. The fixes were made in PR #974  and PR #983.
