### ISSUE TITLE
Rename the `master` branch to `main`.

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3255]
As the name suggests, should we rename the `master` branch? It doesn't necessarily need to be `main`. Another popular one is `consensus`.

I don't think it would be too difficult at all to fix. There is just a spot or two in the scripts folder and the CI workflow files that specifically reference "master" branch which would need to be adjusted.

**Comment by balacij** [comment]
I don't remember how this got into the conversation in CAS 741, but I remember @smiths mentioned most new repos are using it now and some are adjusting. It might be nice for us to as well, since I hope Drasil is a long-term project :smile:

**Comment by smiths** [comment]
If @JacquesCarette agrees, I think we should rename `master` to `main`.  The name `master` is upsetting to some people and it definitely has fallen out of favour.  I'm not a big fan of the branch name `consensus`, but that would still be better than `master`.  Thanks for raising this issue @balacij.

**Comment by JacquesCarette** [comment]
`main` works for me. That's what my new repos use.

**Comment by balacij** [comment]
Sounds good :smile: 

I think there are a few references to 'master' in the code related to the CI, so I will look into it and write back later about this.

**Comment by balacij** [comment]
Last step is to switch our default branch to `main`, and then we can close this ticket.

**Comment by JacquesCarette** [comment]
So what exactly do I need to do? It seems there is a specific task for the repo owner to do, but "change branch name" is too vague for me to act on.

**Comment by balacij** [comment]
Yes, I think the only step now is to switch our default branch from `master` to `main` (so that the first branch that new users see is `main` and so that all PRs default to targeting `main`) and sync any changes from `master`, which can be done through the repo's Settings page (rightmost button).

![Screenshot from 2024-06-19 00-08-57](https://github.com/JacquesCarette/Drasil/assets/1627302/2478461e-8336-4bf7-b2ae-6a94cc801ae1)

After our default branch is set to `main`, we can double-check that `main` contains everything that `master` contains (using the [compare](https://github.com/JacquesCarette/Drasil/compare/main...master) page between) and delete `master`.

**Comment by JacquesCarette** [comment]
I've done the above.

**Comment by balacij** [comment]
Great! Thank you, it looks like we can close this then! :smile:

**Comment by JacquesCarette** [comment]
Done, it is now `main` rather than `master` that is protected.

**Comment by balacij** [comment]
Perfect, everything looks good now! Thank you!

@BilalM04 Thank you as well for double-checking our side of settings too!
