### ISSUE TITLE
Review ChemCode SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3261]
Except for my questions about traceability matrices in the Teams channel (which I'm pretty sure aren't a big deal), the [ChemCode SRS](https://github.com/JacquesCarette/Drasil/blob/chemCode/People/Sam/ChemCode/SRS/SRS.pdf) is ready for review. There are some minor things that I wasn't quite sure about, so I just left in comments explaining my thought process/identifying areas I could use a second (and third and fourth!) opinion on.

- [x] @smiths 
- [x] @balacij

**Comment by smiths** [comment]
Sounds good @samm82.  Thank you.

**Comment by balacij** [comment]
I skimmed it today. I will resume reading and review properly tomorrow!

**Comment by smiths** [comment]
In retrospect, we probably should have developed the SRS for ChemCode in a separate repo and used the Drasil issues for the Drasil implementation.  Using the 741 label does help separate these issues from the main Drasil issues.

I'm working on the SRS review.  In the interest of saving time, I won't be creating my feedback as issues.  I'll create a marked-up pdf instead.  I'll only type the things that are hard to write.  :smile:  For instance, for a reference for your matrix notation, you can use [Gulob and Van Loan](https://twiki.cern.ch/twiki/pub/Main/AVFedotovHowToRootTDecompQRH/Golub_VanLoan.Matr_comp_3ed.pdf).

**Comment by smiths** [comment]
@samm82 I've completed my review in 8b98eec5b.  A very organized and well-written document.  However, as I explained on the write-up, I think the presentation is too abstract.  We aren't really capturing much actual chemistry knowledge.  I gave some advice that might help with a future revision.

**Comment by smiths** [comment]
For formalizing, I'm thinking your theories can be based on the [wikiHow](https://www.wikihow.com/Balance-Chemical-Equations-Using-Linear-Algebra) page for balancing chemical equations.  It explains the meaning of each column and row of your underdetermined matrix.  It also explains how to pick the whole number solution from the parameterized solution.

**Comment by balacij** [comment]
I neglected to mention earlier, but I completed my review as well! :smile: Thank you @samm82, it was a great read, I learned a lot, and I look forward to seeing what you come up with!

**Comment by balacij** [comment]
Since Deesha also finished her review, I'll close this ticket.
