### ISSUE TITLE
Duplicate _conc lens in RelationConcept and UncertainChunk?

### ISSUE THREAD

**Issue by peter-michalski** [JacquesCarette/Drasil#3263]
https://github.com/JacquesCarette/Drasil/blob/84272acccc09574dec70d8d96c6ea994f15f8b22/code/drasil-lang/lib/Language/Drasil/Chunk/Relation.hs#L19-L25

https://github.com/JacquesCarette/Drasil/blob/84272acccc09574dec70d8d96c6ea994f15f8b22/code/drasil-lang/lib/Language/Drasil/Chunk/UncertainQuantity.hs#L29-L35

This is the only case of a duplicate lens in `drasil-lang` where the lens is not of the exact same type.

**Comment by JacquesCarette** [comment]
Well spotted! "Concrete Chunk" -> conc and "Constrained Chunk" -> conc. Can definitely see how this arose.

Interestingly, it doesn't cause any problems in practice, because the way Haskell does class resolution, this kind of overloading is allowed. But it is a bad idea, and we should fix it.

**Comment by balacij** [comment]
Out of curiosity, why is this 'bad'? If `conc` was a name for a 'classy lens' (... am I using this name right?) to a `ConceptChunk`, I might see why, but they're just defined locally, and I don't think we are supposed to be exporting non-classy lenses?

**Comment by JacquesCarette** [comment]
Certainly `_conc` is private, so that's not a problem. And if we don't export `conc` itself, just the `instance` in which it shows up, it is not a problem.

**Comment by balacij** [comment]
Is any further action needed then?

**Comment by JacquesCarette** [comment]
It looks indeed like there is nothing to do.
