### ISSUE TITLE
chemCode: Drop "x 1" in superscripts

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3264]
This is a conventional syntax because matrices are really just vectors of vectors.

![image](https://user-images.githubusercontent.com/1627302/217429443-ac74d822-04f7-4e7d-b752-b4a4f91675bc.png)

**Comment by samm82** [comment]
Fixed in d0bc47b0d753999d0e303b22cb081fb8e894bf00 (forgot to include this issue in the commit 😅).
