### ISSUE TITLE
chemCode: List of Unimportant Misc. (typos, etc.)

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3267]
(I will edit as I go)

- [x] Typo in 2.1, you mentioned the waterfall model in quotation marks, with a comma _after_ the quotation mark. I believe the comma should be inside the quotation mark.
- [x] 2.1 last sentence: I think you can reword this sentence a bit. It's a bit awkward towards the end.
- [x] 2.3: I think you can remove the last sentence, as it will be re-iterated later.
- [ ] 2.4: What does it mean for Goal Statements to be refined to theoretical models?
- [x] 4.1.2: "...how many **atoms** of each element ~~is~~ **are** present..."

**Comment by samm82** [comment]
For 2.4 (now 3.4), I'm not actually sure what that means; it was from the template. @smiths Is this worth being kept?

**Comment by smiths** [comment]
The wording that goals are refined by theoretical models isn't great.  It is used throughout our SRS examples.  The goals are eventually satisfied by refining the theoretical models into instance models.  I don't think we should fix the wording in the SRS though.  At some point we will redo the SRS examples using a "refined theories" version of the SmithEtAl template.  That will be the time to fix wording problems.
