### ISSUE TITLE
Requirements Content Creation for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#327]
In order to remove the "code smell" that comes from the use of `enumSimple 3` under the **Requirements** section for GlassBR, as suggested in Monday's meeting, `s7_1_req1`, `s7_1_req2`, and `s7_1_req6` have to be of `[Sentence]` type so that `enumSimple 1` can be applied to a whole list of requirements. `s7_1_req1` has been modified to reference a table that'll appear after the list of requirements (as mentioned in issue #323); `s7_1_req2` has been modified so that instead of a nested list (
![image](https://user-images.githubusercontent.com/28247301/27655874-eb1fa50a-5c14-11e7-9fb3-8caa1474090c.png)), a single sentence is produced: 
![image](https://user-images.githubusercontent.com/28247301/27655901-06c7b1f8-5c15-11e7-9662-6971e0c56a92.png).

Would it be possible to get some suggestions on the best approach to changing `s7_1_req6`?
![image](https://user-images.githubusercontent.com/28247301/27655959-45bdbf92-5c15-11e7-8649-b8b3f0e7a665.png)
@smiths Should `s7_1_req6`'s bulleted list be converted to a table that can be referenced (similar to `s7_1_req1`)? Compressed into a Sentence (similar to `s7_1_req2`)?
@szymczdm Or is there a function I am missing to change the type from `ItemType` -> `Sentence`? I'm not sure that it would make much sense for an `ItemType` to be changed to a `Sentence` type anyhow, which brings the question of perhaps numbering the requirements using a new function that takes in `ItemType`s?

**Comment by JacquesCarette** [comment]
I actually like R6 the way it is.  The main thing I would change would be to make the words (like "Actual thickness") be the link -- I despise 'this' links.

**Comment by niazim3** [comment]
@JacquesCarette  If I were to leave it as is, GlassBR will have `Enumeration $ Simple $ map ... [acroR 6...` in its code, which is a "code smell"... despite that, should it be left as is?

**Comment by JacquesCarette** [comment]
For now, yes.  Once we better understand what we want, we can create the right combinators that make it happen.

**Comment by szymczdm** [comment]
@JacquesCarette regarding the "this ..." vs. linking the words themselves. Currently that's all handled in the back end, so once I finish updating referencing (milestone 0.1.5; #35 ), we should be able to specify that.

**Comment by niazim3** [comment]
In that case, this issue can remain open until the decisions are made to remove these "code smell"s, thank you for the input @JacquesCarette.

**Comment by smiths** [comment]
@niazim3 , you asked me "Should s7_1_req6's bulleted list be converted to a table that can be referenced (similar to s7_1_req1)? Compressed into a Sentence (similar to s7_1_req2)?"  When Drasil is complete this kind of decision would be an option that would be given in the recipe for generating the requirements documentation.  I don't have a strong preference.  If it isn't much additional work, and if it would align better with the other formatting, I do slightly prefer the idea of a table of outputs.

**Comment by JacquesCarette** [comment]
@smiths is quite right here: the choice between the various format options should be 'trivial' - because the data should exist on its own, and there should be "formatting combinators" for that data, and it should be a matter of just choosing one.

We're not there, but getting extremely close - and that's what we should aim for.

**Comment by niazim3** [comment]
Since the decision in question is something that will be trivially decided in the future, should this issue be closed?

**Comment by JacquesCarette** [comment]
No.  Because even if we implement the feature (still not fully done), that doesn't mean that the encoding in GlassBR will be such that the feature will be used/enable.  That might require a change in GlassBR too. And this issue will remind us of that.

**Comment by JacquesCarette** [comment]
All of the non-trivial pieces of this are all done. Only the 'future' feature is left. Put a link on the wiki so that this issue can be closed.
