### ISSUE TITLE
chemCode: Make A2 more clear

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3270]
A2 should be reworded to articulate that it is a non-trivial (impossible?) task to verify if a given reaction would occur or not, and that assuming that the user only inputs reactions that could happen gives them "the flexibility to experiment with unusual situations."

_Original text: Since we check for feasibility (IM2), the assumption that every inputted chemical reaction is a real one is probably unneeded._

**Comment by smiths** [comment]
I like this assumption.  The reality is that not every balanced chemical equation will work as written in the real world.  The experiment has to be done to see if the reaction will happen in the predicted way.  Your software won't look at a database of valid chemical reactions.  You will just assume that the equation will happen as written (once balanced), even if in reality the reaction is unrealistic.

**Comment by samm82** [comment]
But if the reaction is unrealistic, I'm not sure we should exclude the user from working with it. If a user decides to input a reaction that wouldn't happen in the real world, we can still balance it and do other related things with it as long as it is feasible. Given this and the notion of giving "the user of the model the flexibility to experiment with unusual situations" from Drasil's Data Constraints section, I'm not sure if this assumption is actually adding anything (and it might even be taking away some of the user's flexibility!). @smiths

**Comment by smiths** [comment]
I actually interpreted your wording differently than what you are saying above.  The assumption is that every reaction is real, even though it might not be real.  The software is acting as if the reaction is legitimate.  I think we are actually saying the same thing.  :smile:  The thing to do is to change the wording of A2 to make it clear, rather than delete it.
