### ISSUE TITLE
ChemCode: Relation between scope and assumption

### ISSUE THREAD

**Issue by DeeshaPatel** [JacquesCarette/Drasil#3272]
In section 2.2 (Scope of Requirement), I think as per the requirement, everything should be reflected once in the assumption and the lines which says about "Smallest whole number" is no more reflecting to the assumption. I guess those things are not necessary in scope of requirement. 

Requirements: 
<img width="679" alt="Screenshot 2023-02-10 at 2 14 55 PM" src="https://user-images.githubusercontent.com/25998025/218191153-74c13aa1-9ec8-443c-b0a5-aefac295d877.png">

Your statement: 
<img width="853" alt="Screenshot 2023-02-10 at 2 15 13 PM" src="https://user-images.githubusercontent.com/25998025/218191189-5b8c795b-c7a2-4a1d-8b0a-57ad1d0f29d1.png">

**Comment by samm82** [comment]
The "smallest whole number coefficients possible" is really a requirement, not an assumption. Since it is part of the purpose of the program, I included it here, but I am unsure if it is needed.
