### ISSUE TITLE
ChemCode: Theoretical Models

### ISSUE THREAD

**Issue by DeeshaPatel** [JacquesCarette/Drasil#3276]
In TM1, you described the equation with the type of the data. Instead of type, it should be what is actual meaning of the variable it self make more sense. For example, A is generic metrics is good enough to describe it.

**Comment by DeeshaPatel** [comment]
Also, in TM2 you mention that equation is not applicable. But my googling tells me that Law of conservation of mass has some equation. I am not sure for it. but please take a look at it. 

<img width="739" alt="Screenshot 2023-02-10 at 2 57 37 PM" src="https://user-images.githubusercontent.com/25998025/218193624-b1f65647-a9cb-44ea-8461-b3177e0dde57.png">

<img width="802" alt="Screenshot 2023-02-10 at 3 03 28 PM" src="https://user-images.githubusercontent.com/25998025/218193639-a4617b85-e7cd-4d8a-85c1-e2c175c07c9a.png">

I can be wrong for it.

**Comment by samm82** [comment]
The first part of this issue was addressed in samm82/Drasil@849c19791.

The second part of this issue will be tracked in https://github.com/samm82/Drasil/issues/20.
