### ISSUE TITLE
ChemCode: Question 

### ISSUE THREAD

**Issue by DeeshaPatel** [JacquesCarette/Drasil#3277]
In section 4.2.5 Instance model, Is IM1 is related to the external library that you have mentioned in the system context?

**Comment by samm82** [comment]
Indirectly. IM1 formats the user's input as a matrix, and this matrix (when augmented with the zero matrix) will then be sent to the external library for processing. So while the purpose of the IM is to prepare for using the external library, its functionality is separate from it.

**Comment by samm82** [comment]
Is there any other follow-up you need @DeeshaPatel or can this issue be closed? (Also, in future, issues should have more descriptive names.)

**Comment by DeeshaPatel** [comment]
Yes we are good to close it.
