### ISSUE TITLE
ChemCode: Reference between TM1 and IM3

### ISSUE THREAD

**Issue by DeeshaPatel** [JacquesCarette/Drasil#3278]
I am not sure how TM1 is related to the IM3. Is there any derivation of TM1 is used in IM3? If yes, then you should add the detailed description of those things in the "Description" or "Derivation of.."

**Comment by samm82** [comment]
Essentially the generic matrices and vectors in TM1 are replaced with specific ones; I'll make this more explicit.

**Comment by samm82** [comment]
Closed by samm82@f5006d014
