### ISSUE TITLE
ChemCode: Functional Requirement

### ISSUE THREAD

**Issue by DeeshaPatel** [JacquesCarette/Drasil#3279]
Requirement number 4 and 6 are quite unclear about how they both are coming from the IM3. I think more clarification in IM3 should be proposed.

**Comment by DeeshaPatel** [comment]
Here, I have done my review. I would like to say that you did a great job.

**Comment by samm82** [comment]
An instance model for the output was added in samm82@3904bd2 with traceability information updated in samm82@461cde9 which should close this issue
