### ISSUE TITLE
chemCode: PSD vs Introduction

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3281]
I really enjoyed reading your Physical System Description (PSD), it gave me a basic amount of information to understand the remainder of your project. However, I feel that you had to outline many "entry-level" ideas to chemistry there, and in the Introduction, you immediately refer to it.

I _think_ it would be beneficial for you to move your top two paragraphs of your PSD, almost completely, to the Introduction, and have a more terse PSD. Also, I believe you should keep the second paragraph of your PSD. I found it helpful. However, if you choose to move these 2 paragraphs up to the introduction, it would do good to re-write the second paragraph without assuming other knowledge from other sections of the document.

In all honesty, the PSD was a pleasant read. I was a bit doubtful that I would be able to adequately review your SRS because I had absolutely no knowledge of chemistry (and I really still don't), but it helped me a lot.

**Comment by samm82** [comment]
I'm not really sure if this is the best idea - I think the Physical System Description is really just an overview of what the real-life phenomena being modelled is; if I were to move this to the Intro, what would be left for this section? I linked to the PSD just for those who wanted to learn more about the real-world system, but fully understanding it isn't necessary for understanding the purpose of ChemCode. I'm inclined to close this issue but I'm still not 100% sure.

**Comment by balacij** [comment]
> what would be left for this section?

You would need to write a terse copy of the existing PSD in its place.

I think it's better to have a beefier introduction and a more terse PSD, especially because it avoids jumping around the document, but it's completely up to you. The ticket is really just about style and flow.

**Comment by samm82** [comment]
I guess my issue is then is seems like there is an overlap between the Intro and PSD, meaning either (a) info is duplicated or (b) info is misplaced (i.e., PSD information is in the intro). Just my thoughts.

**Comment by smiths** [comment]
I haven't re-read the intro and PSD sections, but I tend to agree with @samm82.  We really don't want to duplicate information and we want the information in its proper "home."  The document isn't really intended to be read sequentially, so jumping around isn't a big deal.

Having said that, I wouldn't be surprised if the intro would benefit from having an abstract version of the PSD section.  It isn't considered repetition if the same information is given twice if in each instance the level of abstraction is different.

**Comment by balacij** [comment]
I don't feel like I've explained my rationale quite enough. I might have misunderstood the template SRS' explanation of the PSD section, which I understood as saying that the PSD is primarily element identification.

Related: 
![image](https://user-images.githubusercontent.com/1627302/223898727-3d727882-5a12-45c2-992b-466b4d0b4eb6.png)

Taking a look at [Projectile](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Sec:PhysSyst), [DblPendulum](https://jacquescarette.github.io/Drasil/examples/dblpendulum/SRS/srs/DblPendulum_SRS.html#Sec:PhysSyst), [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html#Sec:PhysSyst), [SWHS](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#Sec:PhysSyst), and [PD Controller](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html#Sec:PhysSyst)'s PSDs, they have _very_ terse descriptions (an extra paragraph description might be beneficial for them, but that's a separate issue), but they do conform to what I understood. However, they are all physics-focused and have a “world” to discuss. So the PSD might be simpler for them since they only need to discuss the components of the world.

Looking at ChemCode (and I'll post a picture here for ease of access):

![image](https://user-images.githubusercontent.com/1627302/223894384-ebae6743-5cfe-4d0d-9c05-be4de651025a.png)

_Aside:_ I'm not sure if you could similarly have a diagram (again, I've never taken any chemistry class before, sorry!). 

The two PS components shown in Sam's work look good to me, especially given how generic the inputs can be (unlike the other projects). The two paragraphs are also great (as I mentioned in the ticket description). However, the two paragraphs define what chemical reactions are, describe the syntax, give an example of a chemical reaction being modelled, justify the need for the software (first sentence of the second paragraph), and discuss balancing. Should these components be in the PSD? If so, I might have misunderstood what can go in the PSD. If not, then here were my thoughts on where we could move the components to:
* chemical reaction definition → as the comment mentions, the terminology and definitions table,
* syntax → either the notation section or the “Characteristics of the Intended Reader” section,
* example → perhaps the introduction,
* justification of need of the software → perhaps the introduction, and
* balancing discussion → perhaps in the introduction? (or presupposed knowledge of the reader)

Since Sam's project is quite flexible with what you can input (compared to other projects), I might not be understanding how to think of his quite yet, too. 

Regardless, the way I thought of the work involved with resolving this ticket is closer to what @smiths mentioned in:

> Having said that, I wouldn't be surprised if the intro would benefit from having an abstract version of the PSD section. It isn't considered repetition if the same information is given twice if in each instance the level of abstraction is different.

It is a kind of duplication, but I wouldn't really be against it. One has examples and a long description, while the other (the PSD) would have a terse copy of the components relevant to the problem described, with a bit of extra commentary. The “extra commentary” would be a bit of brief reiteration of some key knowledge relevant to understanding the problem. For ChemCode, I think the commentary would be particularly short because inputs are quite generic.

**Comment by samm82** [comment]
So this discussion ended up being pretty much moot, since Drasil only supports a figure and a list of elements in the PSD section! 😅 I'll be adding the information from my manual version that I couldn't add to the PSD in Drasil elsewhere in the document, but for now, I think I can close this specific issue

**Comment by balacij** [comment]
Ah, perhaps we should create a ticket on the Drasil repo then to allow this?

**Comment by samm82** [comment]
That depends on whether or not it is desired - I'll add it to our next meeting's agenda

**Comment by smiths** [comment]
@balacij has provided a great summary of his thoughts. The above excerpts from the documents are particularly helpful.  Having read through them again, I agree that much of what is in the PSD should actually be in the Intro.  Examples are great content for the intro, but the PSD section should really just define the physical system.  We have only partially laid out the knowledge that should be part of the intro.  We should discuss further, but I think we should aim for incorporating examples as potential content for the introduction.
