### ISSUE TITLE
chemCode: types of molecules

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3283]
@samm82 and I already discussed this before Thursday's class :smile: 

For the sake of posting it to our issue tracker as well, however:

The "+" is an interesting operation here (as well as the right arrow, and that might also need to spoken about). The "+" is representing some sort of mixture of the molecules. In your document, you mention "coefficients" of these molecules, and you add that "moles" are the units of these molecules. If that's the case, why can't I add them together? They're both numeric types with "mol" units. [note: I _actually_ don't know why, but @samm82 explained it to me a bit in class, I'm not trying to be silly here with this question]

As @samm82 mentioned, it doesn't make any sense to do that. So, now I ask: should there be a type parameter for the "mol" type to stop us from naively adding them?

**Comment by balacij** [comment]
Note: depending on how this should be implemented, the type-checker can be reused for this.

**Comment by smiths** [comment]
@balacij [moles](https://en.wikipedia.org/wiki/Mole_(unit)) aren't a unit on their own.  You have moles "of" something.  You can have a mole of water (H2O) and a mole of mercury, but it wouldn't be meaningful to add them.

**Comment by balacij** [comment]
Thank you @smiths In that case, it sounds like there should be a “type parameter” (approximately, the “of something” relation here) so that we can avoid the coefficient folding (which wouldn't be meaningful). I don't think that Drasil's `Expr` type takes units into consideration when merging (constant) numerics, so this might also be a bug in Drasil.

**Comment by smiths** [comment]
I don't think there is a bug in Drasil.  There is something that we need to understand better, but the best way to handle it isn't obvious.  If two things have the same units, it does not mean that they have the same type.  For instance, we can't add (simply sum) the number of mols of H and O, and we can't add work and torque.  (We talked about work and torque previously.  They both have units of newton * m, but they mean different things.  @JacquesCarette found a paper on this topic, but I can't remember the title off the top of my head.)

**Comment by JacquesCarette** [comment]
The paper only mentions this in passing, but it is part of its justification for a "deeper" set of 'types' that go beyond units.
