### ISSUE TITLE
Drasil Research Group Meeting Agenda, Tuesday Feb 21 at 2:30 pm (On Teams)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3292]
The agenda for this coming week is as follows:

1. Sam update
2. Peter update
3. Jason update
4. Ting-Yu update
5. Summer student recruitment update
6. Design review next steps
7. Cold cases/Code Review/Discussion
  a. @peter-michalski
  b. @tingyuw
  c. @cd155
  d. @samm82
  e. @balacij
8. Questions/Comments/Concerns/Discussion

**Comment by samm82** [comment]
Will the meeting for today (the 28th) be in-person or on Teams? @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
I'm planning to be in-person today.

**Comment by smiths** [comment]
I just realized that I forgot to create an issue for this week's meeting.  The new issue is #3299.  If you are on campus, feel free to come to my office (ITB/167) for the meeting.
