### ISSUE TITLE
Review ChemCode VnV Plan (Dr. Smith)

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3293]
It can be found [here](https://github.com/JacquesCarette/Drasil/blob/chemCode/People/Sam/ChemCode/VnVPlan/VnVPlan.pdf). Thanks again for the extension! ♥

**Comment by smiths** [comment]
No problem @samm82.  I look forward to reviewing your VnV plan.  :smile:

**Comment by samm82** [comment]
Moved to https://github.com/samm82/Drasil/issues/2
