### ISSUE TITLE
Can the `quantPlate` branch be deleted?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3295]
The main change in the `quantPlate` branch was the addition of the titular `quantPlate` (see [this commit](https://github.com/JacquesCarette/Drasil/commit/3b3f38a42ebc020c4a8658355decf1a27a9536f4)) for extracting quantities, but it seems like we are already doing this "correctly" in Drasil's current version.

A byproduct of `quantPlate` in this branch is the addition of symbols to the Table of Symbols for NoPCM. I have confirmed that all these symbols are currently present in generated artifacts. Some future work in that branch was to add some symbols to the ToS of SSP and SWHS (from [this comment](https://github.com/JacquesCarette/Drasil/commit/be8aa64515e65736a98291723c083ed2b0d1983c#commitcomment-34659879)), and these have also since been added to our main artifacts.

Is there anything else we would want to preserve from this branch? I'm not sure how these quantities are currently pulled out for the Table of Symbols, so I don't know if there is any knowledge in this branch that would be beneficial.

**Comment by samm82** [comment]
Pinging this since it came up in out meeting in #3451

**Comment by smiths** [comment]
Yes, we decided during #3451 that @JacquesCarette would look at this to see if there is anything worth salvaging.

**Comment by JacquesCarette** [comment]
I have double-checked: yes it can be. I will do so right now.
