### ISSUE TITLE
Drasil Research Group Meeting Agenda, Tuesday Feb 28 at 2:30 pm (on Teams or in-person)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3299]
The agenda for this coming week is as follows:

1. Ting-Yu update
2. Sam update
3. Peter update
4. Jason update
5. Cold cases/Code Review/Discussion
  a. @peter-michalski
  b. @tingyuw
  c. @cd155
  d. @samm82
  e. @balacij
6. Questions/Comments/Concerns/Discussion

@JacquesCarette is on campus, so we have the option of an in-person meeting.  If you are on campus, we can meet in my office (ITB/167).  If there are too many people for my office, we can look at booking a room.

**Comment by samm82** [comment]
I can be on campus for this meeting!

**Comment by tingyuw** [comment]
I can be on campus too

**Comment by balacij** [comment]
I'm on campus, so I can swing by too :smile: Is there enough space?

**Comment by smiths** [comment]
I'm looking into booking a room for the meeting.

**Comment by smiths** [comment]
For those on campus our meeting room is ITB/201.

**Comment by smiths** [comment]
We covered all items on the agenda.
