### ISSUE TITLE
Test Documentation

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#330]
Document the purpose of each of the test values in the python and C code in a separate file.  May help with referencing later on.

**Comment by AKM11** [comment]
Note: Pertaining to NoPCM

**Comment by szymczdm** [comment]
@smiths, @JacquesCarette, Should we do something with this issue?

**Comment by JacquesCarette** [comment]
If I understand it correctly, yes, we should exactly as described.  But likely re-assign it to whoever is taking over NoPCM.

**Comment by smiths** [comment]
@elwazana, you have been looking at the noPCM example.  What are your thoughts on this issue.  As far as I can tell, there is no test plan, or test report, for the noPCM example.  There is testing code in the CCode and Python folders.  In your review of this code, was the meaning of the test values clear?  My guess is that the meaning was confusing, but we would like to hear your thoughts, since this example is new to you.

**Comment by elwazana** [comment]
@smiths I did find it more confusing reviewing the noPCM testing code than the SWHS repository testing code, but I wanted some clarification with regards to what you mean by test values, do you mean the inputFiles? 

As an example SWHS Python inputFiles:
https://github.com/smiths/swhs/tree/master/Program/Python/Testing/inputFiles

**Comment by elwazana** [comment]
@smiths Dr. Smith, I was wondering if there is anything specific I should do for this issue? I understand that I should document the test values, but is there any specific format that you and @JacquesCarette Dr. Carette would prefer? Should I hold off?

**Comment by JacquesCarette** [comment]
You should document these in a way that they can be used in Drasil itself. Some of these will be "reasonable values" (already implemented), but we might not be able to capture all of this knowledge in Drasil yet.

I guess the first thing is to (informally) document what each test value means, and then we'll see.

**Comment by smiths** [comment]
@elwazana, please write a document like PCM_VVPlan for the noPCM example.  You don't need to worry about all of the sections.  You should focus on summarizing the test cases themselves.  Each of the input files (which you pointed to above) provide an input case.  What we really want is to know what distinguishes each case from the others.  To do this, I have the following advice:

- Give each of the test cases a name.  Names like P01, P02 say nothing.  The order means nothing.  We should give the test cases meaningful names in the documentation and in the associated files.
- Not to needlessly repeat values in the documentation.  The easy solution would be to just copy the input files into the test plan, but this would made it a long document, and difficult to maintain.  We should summarize the information that is common between the test cases and then distinguish each test case by its "delta" from the standard test case (or cases).

**Comment by smiths** [comment]
@elwazana, since this issue is specific to the "manual" version of the tests cases, could you close this issue by making a new issue in the case study repo?  I think it would help manage the projects better if we separate the Drasil issues from the case study issues.

**Comment by elwazana** [comment]
https://github.com/smiths/caseStudies/issues/75
