### ISSUE TITLE
Drasil Research Group Meeting Agenda, Tuesday Mar 7 at 2:30 pm (on Teams)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3300]
The agenda for this coming week is as follows:

1. Jason update
2. Ting-Yu update
3. Sam update
4. Cold cases/Code Review/Discussion
  b. @tingyuw
  c. @cd155
  d. @samm82: Do we only generate code from IMs or can code be generated from GDs as well?
  e. @balacij
  f. @smiths - If we change g for one example (say to 9.81 for more precision, or 10, for less; or for a change in elevation; or for a change of units to 32.2 ft/s^2), it looks like we change it for all code that depends on g (https://github.com/JacquesCarette/Drasil/blob/f81c9a7188767a6a0446285d8f817c7ea01a246e/code/drasil-data/lib/Data/Drasil/Quantities/Physics.hs#L147-L148)
g: (@samm82): https://github.com/JacquesCarette/Drasil/issues/3295
5. Questions/Comments/Concerns/Discussion

**Comment by samm82** [comment]
We covered all items on the agenda.
