### ISSUE TITLE
Chapter 2 Drasil Printer is ready for review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3304]
Please see chapter 2 from [Thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf). Thank you!

**Comment by smiths** [comment]
@tingyuw, I've unassigned @JacquesCarette from reviewing your Chapter 2.  It is a more efficient use of everyone's time if @JacquesCarette and I review sequentially, rather than in parallel.  @JacquesCarette did the first review of Chapter 1, so I'll do the first review of Chapter 2.  

If possible, I'd like to review Chapter 1 at the same time.  I posted a question in #3262 about the status of the Chapter 1 revisions.

**Comment by tingyuw** [comment]
@smiths I hope you haven't started reviewing chapter 2. I'm making some changes to it, not structurally but to some wordings and typos.

**Comment by smiths** [comment]
Thank you for the note @tingyuw.  I was actually deciding between tasks to work on and reviewing your Chapter 2 was on my list.  :smile: Let me know when your changes are done.

**Comment by tingyuw** [comment]
@smiths I have finished updating chapter 2. The original link should reflect the changes. Thank you😊

**Comment by smiths** [comment]
@tingyuw my feedback for Chapter 2 is attached.  Please let me know if there is anything you can't read, or if you have any other questions.

[thesis_Ch2_Fdbck.pdf](https://github.com/JacquesCarette/Drasil/files/11149963/thesis_Ch2_Fdbck.pdf)

**Comment by tingyuw** [comment]
@smiths I have a few questions about the feedback:
1. In regards to pseudocode: I use pseudocode because it is not the actual code in Drasil. I modify it to make it more readable and understandable, or I use it to provide an example. This is why I differentiate it from the source code. Does it make sense? Or should I name it Code?
2. Do you mean by moving this paragraph before the start of 2.1?
<img width="647" alt="image" src="https://user-images.githubusercontent.com/47548045/232255652-9b7a69a5-05f2-46ad-90eb-52a55a5da752.png">
3. Can you explain the comment of capitalization for 2.2.1 header?

**Comment by smiths** [comment]
@tingyuw I can see why you are saying pseudo code, but for my taste your work is closer to code.  When I think of [pseudo code](https://www.wikihow.com/Write-Pseudocode), I think of something more abstract.  However, there are also examples of what people call pseudocode that are code, with just a few parts replaced with natural language.

My suggestion is that you call your code blocks as code, but be clear to the reader that they have been modified to remove/simplify the unnecessary/uninteresting bits.  For anything that isn't standard code, you could use a different typographic convention.  I assume that you are using the `listings` package.  You can switch to a different font for parts that aren't from the original Haskell.

With respect to your second question, the instructions for the reader would be more helpful if they occurred earlier in the chapter.  I've suggested that you move these instructions to the introduction section, probably right at the end of the introduction section.

**Comment by tingyuw** [comment]
About the comment you made on the use of blue, red, or bold text, I initially thought that blue could be used for "data type," and red could be used for "helper functions." But after further consideration, I think the distinction might not be obvious. Therefore, I am considering using the \texttt command to present all the variables and functions in Drasil.

**Comment by smiths** [comment]
The distinction wasn't obvious to me, but if you want to distinguish data types and helper functions, you just have to tell the reader about your typographic convention.  You would explain the convention in the first Chapter.  If you don't think the distinction is worth the effort, then using \texttt (or some other consistent convention) for both is fine.
