### ISSUE TITLE
CodeBlocks and package dependencies

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3307]
In https://github.com/JacquesCarette/Drasil/commit/a6b2edef9c9bcd128796fd6848913bbafbf7bc4f#commitcomment-104797093 @tingyuw said:

> A new type CodeBlock is added in this commit. The code is not final, I'm testing but we are now able to generate code cells in the notebook after these changes (still need to address how the code will be printed). The reason why I use ModelExpr is because CodeExpr is defined in drasil-code-base, and due to package dependencies, we cannot use it in drasil-lang. What do you think would be the best approach to proceed this?

[This is better discussed in an issue than as a commit comment.]

As far as I can tell, the problem is that `drasil-code-base` contains two separate things
- `Language.Drasil.Chunk.*` which depends on drasil-database
- `Language.Drasil.Code.Expr` which does **not**.

At the moment, I think there are two routes forward that both make sense:
1. move `CodeExpr`'s defintion to `drasil-lang`
2. split `drasil-code-base` into two packages

Both of these would resolve the dependency problem. @balacij , since I think you're the last one to have committed code in `drasil-code-base`, opinions?

Personally, I think we should be looking hard at re-merging the 3 `Expr` types, so I think that all of them should be defined in the same spot. (I don't really mean 'merge', I mean to de-duplicate.)

**Comment by balacij** [comment]
It would definitely be nice to de-duplicate the 3 kinds of `Expr`s. I don't quite like that we have `drasil-code-base` _and_ `drasil-code` either, but I think we discussed this elsewhere too.

What do you think of creating a `drasil-jupyter` package, with a Jupyter notebook encoding? This way the code related to Jupyter has access to everything from the 'code' packages and various math packages.

The tickets related to the dependencies are still a WIP. Hopefully we can work on those this summer.

**Comment by JacquesCarette** [comment]
I agree about the de-duplication -- but the important question here is about package dependencies & how to resolve things in the short-term.  Yes, `drasil-jupyter` can make sense, but I think that the dependency is more of a short term problem that needs to be resolved soon.

**Comment by balacij** [comment]
I agree. We should be re-organizing some dependencies in #2885 and the related tickets. I'm eagerly waiting for the summer :sweat_smile:

**Comment by JacquesCarette** [comment]
@balacij I agree that that is the long-term plan. This issue asks you for your opinion on which of 1 or 2 above makes the most sense in the short term.

**Comment by balacij** [comment]
Sounds like I misunderstood (my bad!).  In that case, I think (1) will be simpler just because we avoid more package changes. Either way, I think we should be able to re-export anything from `CodeExpr` from `drasil-code-base`, so we should hopefully be able to avoid large 'import' changes.

**Comment by tingyuw** [comment]
Sounds good! If we agree to proceed with the first approach, I'm going to create a new branch and move the ``CodeExpr`` to ``drasil-lang``. Just so we are the same page, it would be moving ``Language.Drasil.Code`` to ``drasil-lang`` and leave the ``Language.Drasil.Chunck`` in ``drasil-code-base``, right?

**Comment by JacquesCarette** [comment]
Yes, let's go with the first approach. And yes, you have understood that correctly.

**Comment by tingyuw** [comment]
Ah I think the ``Chunk`` needs to be moved as well as classes (``CodeIdea``, ``CodeVarChunk``) are being used in Language.Drasil.Code.

**Comment by JacquesCarette** [comment]
That's too bad, but if they are needed by `CodeExpr`, they need moved. Make sure it's not an artificial dependency though.

**Comment by tingyuw** [comment]
Okay, I will move both packages to `drasil-lang`. Also, I believe that the ``drasil-code-base`` should be deleted since it's empty?

**Comment by JacquesCarette** [comment]
Yes.
