### ISSUE TITLE
Questions about chapter 3 content

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3309]
In chapter 3, we discuss the projectile lesson case study. The first part covers the language of lesson plans (the structure of lesson plans and the document language), and the second part is about the projectile lesson. For the second part, I was thinking to touch on how the information is encoded and how the lesson is reproduced, but I'm not sure how detailed the discussion should be. Should I provide a few examples of how the information is encoded, show the generated lesson plan, and include the complete code in the appendix? Or should I walk through each step of how each chapter is built by presenting the complete code and like breaking down each line? I briefly touch on how the information is encoded and how the document is generated and printed in the previous chapter. Therefore, my question is: what would be the best way to present and discuss the projectile lesson? (plus, considering that I don't own the lesson plan)

**Comment by JacquesCarette** [comment]
(You should also assign it to someone when you ask a question).

Personally, I would split abstract description (of lesson plans and of projectile in particular) from implementation details. Yes, it would be good to have a chapter in which you do discuss some implementation details with pieces of code; and indeed, not all of the code, just the interesting parts.

**Comment by smiths** [comment]
I answered this question as well, but I don't see my comment.  Maybe I didn't hit the comment button?  I don't remember exactly what I wrote, but it was along the same lines as the comment from @JacquesCarette.  All the code will be too repetitive.  You just want the interesting parts.

You also mention showing the complete lesson plan in the Chapter.  You can include the lesson plan in an Appendix, but the entire plan is too big for a Chapter.  As for the code, you just want to bring in the interesting parts.

I'm not sure what you mean about not owning the lesson plan.  We cite the original source (Hibbler), so I think we are okay on that front.  The current lesson is quite different from the original, so we don't have to worry about copyright.  If you mean you didn't author the lesson plan, that is also fine.  As long as you give proper credit for the lesson, everything is fine.

**Comment by smiths** [comment]
Since the question is answered, we can close this issue.
