### ISSUE TITLE
Set up "Code Ownership"

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3312]
For those of you who weren't at the meeting from #3302, GitHub supports assigning [code ownership](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). While it is a bit of a misnomer, it really means that all "owners" for a given subsection of code "are automatically requested for review when someone opens a pull request that modifies [code that they are marked as an owner of]." This essentially just formalizes practices we already follow and allows those who wish to stay involved in Drasil after moving on an easier way to jump in.

I've started a list of pieces of code that certain Drasil contributors might like to be assigned ownership of below; feel free to edit/add to these lists and check off your name once you are happy with the scope of your ownership. (Note that this can always be changed later and can also be empty if you don't wish to be involved in Drasil anymore!) I will then, at some point in the future, create the necessary file and close this issue; even then, ownership can be changed.

- [ ] @AKM11:
- [ ] @Ant13731:
- [ ] @Awurama-N:
- [ ] @balacij:
- [x] @bmaclach: Projectile, GOOL
- [x] @cd155: DblPendulum, `DifferentialModel`
- [ ] @Daisy-C:
- [ ] @Daniel-Genkin:
- [ ] @danscime:
- [ ] @deviprasad135:
- [ ] @elwazana:
- [ ] @halonazhao:
- [ ] @hmadej:
- [x] @JacquesCarette: All of it lol
- [ ] @jeger1917:
- [ ] @lmawarid:
- [ ] @Mornix:
- [ ] @muhammadaliog3:
- [ ] @muralidn:
- [ ] @Nathaniel-Hu:
- [ ] @niazim3:
- [ ] @njericha:
- [ ] @oluowoj: SglPendulum?
- [ ] @palmerst:
- [ ] @peter-michalski:
- [x] @samm82: Projectile, GlassBR, Template, `Drasil.Symbol` (for `unicodeConv`), `Drasil.Sentence.Fold`
- [x] @smiths: stable
- [ ] @Sodaaaa:
- [ ] @szymczdm:
- [ ] @TamkeenFatima:
- [ ] @tingyuw: Any Jupyter notebooks?
- [ ] @vajihehm:

_Sorry for tagging everyone 😬_

**Comment by JacquesCarette** [comment]
@samm82 whoever doesn't answer within 2 weeks, you can consider them "not interested" in the sense of wanting to do any reviews, and then just close this issue.
