### ISSUE TITLE
Missing Introduction sections in Projectile

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3317]
Projectile is missing the Purpose of Document, Characteristics of Intended Reader, and Organization of Document subsections in the Introduction (and are all mentioned in the "roadmap" for the section). These should probably be filled in (unless they were intentionally left out for the sake of keeping Projectile small). Any thoughts @smiths?

**Comment by smiths** [comment]
I agree @samm82 that this information should be added.  Although adding them will make the roadmap correct, the current roadmap really shouldn't mention things that aren't present.  We've noticed this problem before.  Some of the boiler plate unfortunately stays the same, even for the incomplete examples.

**Comment by daijingz** [comment]
Hi Dr.Smith, I want to work on this issue. Can you allow me to participate?

**Comment by smiths** [comment]
@daijingz of course you can participate.  You can fork the Drasil repo, make the changes, and then generate a pull request.

**Comment by ManvendraJani** [comment]
In the Purpose of Documents in the Introduction, the first sentence goes as follows:
```
The primary purpose of this document is to record the requirements of the GlassBR
```
where `GlassBR` is replaced by the respective title of the SRS. 

This looks grammatically wrong as we are referring to a piece of `knowledge` and if we were to say something like `requirements of the Projectile` it would imply we are talking about a physical object Projectile instead of what we mean, the generated artifact Projectile. Should this be changed @smiths?

**Comment by samm82** [comment]
> This looks grammatically wrong...

If you are suggesting that the "the" should be removed before GlassBR, I agree - make a new issue labelled <kbd>[newcomers](https://github.com/JacquesCarette/Drasil/labels/newcomers)</kbd> to do this for all examples.

**Comment by samm82** [comment]
> Also, what should the characteristics of the reader say?

I would compare it to the other examples and the characteristics of the user (if that is filled in) and suggest content for this

**Comment by smiths** [comment]
> > This looks grammatically wrong...
> 
> If you are suggesting that the "the" should be removed before GlassBR, I agree - make a new issue labelled [newcomers](https://github.com/JacquesCarette/Drasil/labels/newcomers) to do this for all examples.

I agree that the "the" should be removed.  @ManvendraJani you might also be concerned that the name of the software might result in a sentence that is confusing, like "The primary purpose of this document is to record the requirements of Projectile."  I think you are worried that the reader might not realize that Projectile is the name of the software.  We introduced the name of the software in the SRS prior to this point, so we should be okay.  We could potentially put Projectile in italics to highlight that it is the name of the software.  I don't feel like that is necessary right now.

I agree with @samm82 that we need an issue to remove the "the".

For the discussion about the Characteristics of the Intended Reader, you should be able to write a draft of this section @ManvendraJani.  As @samm82 suggested looking at the other examples will be helpful.  If there is more discussion of the Characteristics, please create a separate issue.  The conversation gets confusing (at least for me) when we end up interleaving multiple threads together.  :smile:
