### ISSUE TITLE
Add SmithAndKoothoor2016 reference for SRS template

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3318]
# TODO
Smith and Koothoor (2016) (which can be found in [References.bib](https://gitlab.cas.mcmaster.ca/smiths/pub/-/blob/master/References.bib) in the pub repo) should be referenced alongside Smith and Lai (2005) and Smith et al. (2007) for the SRS template in the Organization of Document section of all applicable examples.

## _Initial question:_
While working on ChemCode, I realized that the SRS template provided by @smiths found [here](https://github.com/smiths/capTemplate/blob/main/docs/SRS/SRS.pdf) is based on Smith and Lai (2005) and Smith et al. (2007), where as our Drasil SRSs are based on Smith and Lai (2005) and Koothoor (2013). Should Smith et al. (2007) be added to the rest of our Drasil examples (and should Koothoor (2013) be added to the capTemplate SRS)?

**Comment by smiths** [comment]
Actually, a better reference than the Koothoor 2013 reference is SmithAndKoothoor2016.  The bib entry for this paper can be found in the [References.bib](https://gitlab.cas.mcmaster.ca/smiths/pub/-/blob/master/References.bib) in the pub repo.

**Comment by harmanpreet-sagar** [comment]
A quick doubt regarding this. Should I add both the Smith et al. (2007) and Smith and Koothoor (2016) references for all the examples where Smith and Lai (2005) and Koothoor (2013) were referenced or should I just add Smith et al. (2007) or Smith and Koothoor (2016)?

**Comment by smiths** [comment]
Add both Smith et al (2007) and Smith and Koothoor (2016).

**Comment by harmanpreet-sagar** [comment]
Ok, I will do that!

**Comment by harmanpreet-sagar** [comment]
The following are articles but have a link available to view them. I used `cArticle` to cite them in the Citations.hs file, however, when I generate the build, it is adding the word "Print" at the end even though there is a link present.

![image](https://github.com/JacquesCarette/Drasil/assets/110783820/9864a149-954b-4859-9f73-ed511afc958c)
![image](https://github.com/JacquesCarette/Drasil/assets/110783820/c3fa7fa9-6402-4fe0-96d8-bb102a296c1f)

Should I just omit the links, or is there another classification that I should use to cite the articles?

**Comment by samm82** [comment]
There's a separate issue for the "Print." display issue (#3357).

**Comment by harmanpreet-sagar** [comment]
Ok, so I will move forward with what I have right now then.
