### ISSUE TITLE
Building new case studies with the `template` project is a bit difficult (at least for me)

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3326]
Building basic, empty, SRS documents using the existing template is somewhat problematic. If you add sections to the current, largely empty, list of declared sections, you will come across some errors that might impede progress:
1. missing acronyms from the acronyms section (e.g., "SRS" itself in the predefined introduction section isn't automatically included in the table of acronyms when you add the section to your SRS declaration [`SRSDecl`]),
2. many missing `term` dependencies for the basic dependencies of the SRS components (see my [small list](https://github.com/balacij/Drasil/blob/e0c230521b3b2f2f182799711c6e762df94c3b8e/code/drasil-example/bmbnd/lib/Drasil/BmBnd/Meta.hs#L67-L76) of things I had to manually add to get a fairly minimal SRS building with Drasil) -- these should probably be part of the background knowledge presupposed for all Chunk Databases (seeing as we already have a basic set), and
3. the rules for building documents can be a bit restrictive for SRS documents early in development. For example, I had to...
    1. disable [hard requirements for all SRS documents to have a list of IMs and TMs](https://github.com/balacij/Drasil/blob/e0c230521b3b2f2f182799711c6e762df94c3b8e/code/drasil-docLang/lib/Drasil/DocumentLanguage.hs#L363-L366), and
    2. disable [checking that the traceability matrices are non-empty](https://github.com/balacij/Drasil/blob/e0c230521b3b2f2f182799711c6e762df94c3b8e/code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityMatrix.hs#L41-L43).

Edit: moved:
1. Approximately #3429
2. #3429 
3. 1 -> #3427, 2 -> #3428

**Comment by balacij** [comment]
Another issue: unit symbols are not presupposed, but we use the same SI units for each of the case studies, it would be nice to have them automatically inserted (but only shown in the SRS documents if used) into the chunk database.

**Comment by JacquesCarette** [comment]
I think every single one of these is a different issue, and ought to end up being solved separately. Having said that, they are all quite interesting!

**Comment by smiths** [comment]
Thank you for the info @balacij.  This is good feedback for improving the template.

We definitely want the flexibility to build the SRS from an empty template.  As a thought experiment though, would there be any advantage to having a template that was fully populated with all the sections, but with the content of all the sections being "Not applicable".  We don't want to get too attached to the "SmithEtAl" template; however, if someone wants to use it, they really aren't supposed to remove sections.  As we discussed in 741, if you use a template but don't have content for a section, you don't leave the section out, you include it with a note that it is "not applicable."  This implies that an "empty" template would actually have all of the sections with their content being empty.

**Comment by balacij** [comment]
Thank you both, we will definitely need to split up the ticket, as @JacquesCarette mentioned.

@smiths: I like the idea of having the SRS template being "locked in" to showing all sections with the basic "not applicable" text (or as appropriate) you mention. Other than having a name for new projects, I'm not entirely sure what would be required for users before any sort of HTML/TeX rendering could be done. I think this would also cut some of the boilerplate `SRSDecl` shared between each case study.

**Comment by balacij** [comment]
Closing in favour of the linked tickets. Points 1 and 2 were a bit too similar, I'm not sure what if I had something specific in mind when opening this issue, but it'll be a good reminder for myself to write examples more often in the future :smile:
