### ISSUE TITLE
BmBndng: How can we use SciPy's `integrate.solve_bvp` instead of `integrate.ode` in our generated solutions?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3327]
SciPy's official documents have `scipy.integrate.ode` (which we currently rely on for ODE handling with SciPy) listed as part of their [Old API](https://docs.scipy.org/doc/scipy/reference/integrate.html#old-api) and have specialized components for other kinds of problems. For BmBnding, I would like to use scipy's [solve_bvp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_bvp.html) function to build out the solution instead of the general `ode` tool.

I wrote a prototype relying on `solve_bvp`, but I am not quite sure of how we should design this for Drasil. In terms of capturing calculation solutions for variables in Drasil, it seems we currently have (a) a method for "pure" translations (e.g., Exprs), and (b) a way for some ODEs. If I wanted to add in a manually built, overriding, custom, etc. solution for any particular variable which has a conscious choice made by software implementation designers, how should I?

**Comment by smiths** [comment]
I agree that having the option for a custom solution would be nice, but I feel like you are missing an option.  Rather than adding `solve_bvp` as a custom solution, maybe we should expand the options for Drasil solving ODEs?

**Comment by balacij** [comment]
In all honesty, before spending a lot more time with #3322, I was working under the assumption that Drasil's current solving methods for ODEs included BVPs and that I was just encoding the BVP problem incorrectly. I will try to add support for BVPs. Thank you :smile:
