### ISSUE TITLE
Drasil Research Group Meeting Agenda, Thursday Apr 27 at 12:30 pm (in Person, ITB/167)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3332]
The agenda for this coming week is as follows:

1. Sam update
2. Jason update
3. Ting-Yu update
4. Issues for summer students
5. Cold cases/Code Review/Discussion
  a. @tingyuw
  b. @cd155
  c. @samm82
  d. @balacij
6. Questions/Comments/Concerns/Discussion

@JacquesCarette plans on attending.

**Comment by smiths** [comment]
@JacquesCarette we've moved the meeting time.  I don't know if that helps with you being able to attend or not.

**Comment by JacquesCarette** [comment]
Yes, it does - in my calendar now.

**Comment by smiths** [comment]
Great that you can make it to the meeting @JacquesCarette.  Please let me know if you will be attending in person or virtually.  I'll book us a room if you are coming in-person.

**Comment by JacquesCarette** [comment]
I'm thinking virtual - I'll be quite jet-lagged that day.

**Comment by samm82** [comment]
So will this meeting be hybrid or entirely virtual? Still trying to figure out when I go home that weekend 😅

**Comment by smiths** [comment]
Hybrid.  If you wish to participate virtually, that is fine.

**Comment by samm82** [comment]
Just to confirm, this meeting is taking place at 1:30? For some reason I had it in my calendar as 12:30 😅

**Comment by smiths** [comment]
The meeting is at 12:30!  I made a mistake in the heading.  I have another meeting to attend at 1:30 pm.  Hopefully everyone will get this message in time.

**Comment by samm82** [comment]
Oh whoops! Then in that case I'll be attending virtually 😬

**Comment by smiths** [comment]
Okay.  I'll start a call in the Rsch Stdnt Meeting Channel on Teams.  Hopefully others will be able to join us, either in-person or virtually.

**Comment by smiths** [comment]
If not everyone can attend at 12:30 pm, the remaining people can maybe meet virtually at 1:30 pm.
