### ISSUE TITLE
“RefBy” and “Refname” should be abbreviations in the SRS Table of Abbreviations

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3337]
We currently use the two abbreviations in the SRS documents, but I haven't found any occurrence of them in the table of abbreviations and acronyms.

**Comment by harmanpreet-sagar** [comment]
@balacij Just to make sure before I make any changes, the definitions for Refname and RefBy are the following:
Refname = "Reference Name"
RefBy = "Reference By"

**Comment by balacij** [comment]
I believe RefBy is Referenced By

**Comment by harmanpreet-sagar** [comment]
The HGHC section has no Table of Abbreviations and Acronyms, however, it does use acronyms such as DD for Data Definitions and Refname. Should I add a table or leave it as it is?
![image](https://user-images.githubusercontent.com/110783820/236908738-04385f59-075d-4e38-a6c7-a26444351a43.png)

**Comment by smiths** [comment]
We've always kept HGHC simple.  We can probably continue to leave the table of abbreviations out of it for now.
