### ISSUE TITLE
Chapter 4 Code Block Generation is ready for review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3344]
Please refer to chapter 4 in [thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf). Thank you!
The last chapter will be ready tomorrow, and I believe our goal is still to complete it before the April 28th deadline?

**Comment by smiths** [comment]
@tingyuw my feedback on Chapter 4 is attached.  Overall it looks good.  However, I was confused that I didn't see anything about how you track subsections in your new flattened structure.  Did I miss something in the writeup?  I remember we discussed ways to flatten the structure, but still have the information on which sections were parents and children.
[TingYu_Ch4_Fdbck.pdf](https://github.com/JacquesCarette/Drasil/files/11234950/TingYu_Ch4_Fdbck.pdf)

**Comment by tingyuw** [comment]
@smiths The current implementation uses level indicators to track the level of each section (0->parent, 1->subsection, 2->subsub ...). But since splitting with content types makes more sense and have better result, I do not touch a lot on that. I'm even thinking switching back to the nested structure, as making lesson plans structure linear (and keep SRS nested) work.

A quick question: what is the sentence to add after lesson plans? :sweat_smile:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/47548045/232961962-d3e6d787-4b18-40d7-97cf-8528f2353944.png">

**Comment by smiths** [comment]
Thank you for the extra information @tingyuw.  Please make sure the discussion of the different design options for the structure are covered in your report.

The edited sentence would be: "... lesson plans (or user manuals), we ...".  I just wanted to add an example to show that notebooks are well-suited to more than just lessons.
