### ISSUE TITLE
Chapter 5 Conclusion is ready for review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3345]
Please refer to Chapter 5 in [thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf). 
Thank you!

**Comment by JacquesCarette** [comment]
Comments:
- there should always be text in between headings (i.e. here between Conclusion and 5.1 and also between 5.1 and 5.1.1)
- the "future work" would be richer if there were links to issues on github (probably inserted as footnotes in the appropriate places) that document these missing items.

But that's it; this chapter is very good, and basically done except for those two items.
