### ISSUE TITLE
Abstract Review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3346]
I've the abstract ready. The complete paragraph is provided below and can also be found in [Thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf).

Abstract:
Scientific Computing (SC) involves analyzing and simulating complex scientific and engineering problems using computing techniques and tools. To improve the understandability, maintainability, and reproducibility of SC software,  documentation should be an integral part of the development process. Jupyter Notebook is a popular tool for developing SC software documentation, and is also used to enhance teaching and learning efficiency in engineering education due to its flexibility and benefits. Despite the importance of documentation, it is often missing or poorly executed in SC software for several reasons, including time-consuming. 

Drasil is a framework that aims to improve the efficiency of documentation development. By encoding each piece of information of scientific problems once and generating the document automatically, Drasil saves time in the documentation development process. We are interested in generating Jupyter Notebooks in Drasil to expand its applications, including generating educational documents, and extend the values of Jupyter Notebooks to Drasil.

To achieve this, we implement a JSON printer capable of generating Drasil software artifacts, such as SRS, in notebook format. This enables us to generate Jupyter Notebooks in Drasil, and generate educational documents, starting with lesson plans. We develop the structure of our lesson plans and designed the language of lesson plans in Drasil. Additionally, Jupyter Notebooks seamlessly integrate different content types with code, making them ideal for data research. We discuss two approaches and the implementations to combine text and code in our Drasil-generated Jupyter Notebooks. 

This paper achieves our main objectives of generating Jupyter Notebooks that integrate both text and code, as well as generating lesson plans using Drasil.

**Comment by smiths** [comment]
The abstract looks good.  Some comments are included in the attached file.

Am I correct that all of the review tasks assigned @JacquesCarette and me are now complete?  If there is anything outstanding, please point us toward it.

I would like to re-review everything, especially the parts that I didn't read on the first pass.  As you complete the revised version, please create issues for review.

[AbstractFdbck.pdf](https://github.com/JacquesCarette/Drasil/files/11262453/AbstractFdbck.pdf)

**Comment by tingyuw** [comment]
Yes, all assigned review are completed! Thank you!
I'm working on all the feedback and will create an issue for overall review by the end all the day.

**Comment by smiths** [comment]
Great!
