### ISSUE TITLE
Overall review

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#3349]
The complete report can be found here [thesis](https://github.com/JacquesCarette/Drasil/blob/tyThesis/People/Ting-Yu/thesis/thesis.pdf).
The only thing left is the figure for Example chapter of the Projectile lesson. I haven't encoded the entire chapter yet.

**Comment by smiths** [comment]
Great work @tingyuw.  I have another marked-up version, but there is nothing major.  I don't think it will take you long to address my comments.

[TingYu_thesis_Fdbck.pdf](https://github.com/JacquesCarette/Drasil/files/11279664/TingYu_thesis_Fdbck.pdf)

**Comment by smiths** [comment]
@tingyuw, what is the status of generating Jupyter notebooks in our case studies?  I believe you generate a Jupyter notebook SRS for one case study.  (Which one?)  How much work would be involved in generating a Jupyter SRS for all of the case studies?  (I'm not sure we want to do that, but I'm curious to know the effort involved.)

Is the projectile lesson plan now part of stable?  (I could look, but it is faster to ask.)  :-)

**Comment by tingyuw** [comment]
> what is the status of generating Jupyter notebooks in our case studies? I believe you generate a Jupyter notebook SRS for one case study. (Which one?)

All of them! You can find the SRS in Jupyter Notebook in the `casestudy/SRS/JSON` directory. (I guess I should also include an example of SRS in notebook :-) )

> Is the projectile lesson plan now part of stable? (I could look, but it is faster to ask.)

Yes, it is. Except the example chapter (still need time to have the whole chapter encode).

**Comment by smiths** [comment]
The generated Jupyter SRS documents and lesson plan look good.  We don't need to worry about including an SRS example in your report, since that part isn't as interesting as the part where you mix code and documentation.

@tingyuw please let me know when the edits are done.  I've checked with @JacquesCarette and he is fine with us proceeding to sending your report to the external examiner.  Once the report is ready I'll give it one last quick review and then send it to the examiner.

**Comment by tingyuw** [comment]
@smiths I've finished editing. Thank you!

**Comment by smiths** [comment]
Great!  I will send your report to the examiner for review.  I'll remind them to get the review to us by the 26th at the latest.

**Comment by tingyuw** [comment]
This issue has been completed. The report has been reviewed by the examiner and I will create a pull request for it.
