### ISSUE TITLE
Add a `ModelKind` for defining functions

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3350]
As a specific instance of #3333, we should be able to define functions in Drasil in a way that allows them to be outputted as such. For example, the following DD is a function, but its input/output information is not displayed anywhere (other than the manually added note). The main place this should be displayed is in the equation, e.g. $\text{elems}(r) = \dots$; alternatively, we could create an Input row and rework the Equation row to simply be an Output row.

![image](https://user-images.githubusercontent.com/35857611/234710850-1fa7a417-214f-40c4-96b6-47fe1f3d8f91.png)

**Comment by samm82** [comment]
Ahh gotcha - is there a ticket open for this or not? (I.e., should I reword this issue and keep it open or close it?)

**Comment by balacij** [comment]
#3338 covers the display issue, and I believe #3325 covers the remainder, so I would tend towards closing, I think?

Do those cover all the needs? I didn't write the best tickets, so feel free to clean them up too, of course.
