### ISSUE TITLE
Mandated dimensions for vectors and matrices?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3354]
In `Space`, we currently explicitly enforce that all matrices have defined dimensions while vectors do not (although there is a note to potentially consider this in the future). However, ChemCode involves generic vectors and matrices with undefined dimensions (in the sense that they are arbitrary and don't have a specific value). Should we be requiring these types of structure to have explicit dimensions?

https://github.com/JacquesCarette/Drasil/blob/c0467c3438ec859749d7599f5e35e856acbc5f69/code/drasil-lang/lib/Language/Drasil/Space.hs#L31-L40

**Comment by balacij** [comment]
I think this is along a similar line of thinking to #3135. The tldr is that we need vectors to also 'know their length', but even then, we need to make sure that both vectors and matrices can have a dynamic size.

**Comment by samm82** [comment]
Hmm... should I migrate this to #3135 or keep this issue open?

**Comment by balacij** [comment]
I think migrating is appropriate.

**Comment by samm82** [comment]
Closed as a duplicate of #3135
