### ISSUE TITLE
Issues with display of reference section

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3357]
_Any of these can be pulled out to separate issues if they end up being more complex._

- [ ] We may want to separate author names with semicolons (keeping the separation of first and last names to use commas)
![image](https://user-images.githubusercontent.com/35857611/234738628-da201530-9be6-4660-b379-66b7a8fd6c7d.png)
   - This might depend on which citation style we are using
- [x] "3st" should be "3rd" (fixed in #3421)
In ChemCode: ![image](https://user-images.githubusercontent.com/35857611/234739455-9670f48e-2513-455d-a502-ae8a5dacf910.png)
In SSP: 
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/1d03076b-1498-4795-be0b-1c05a5d38165)
- [x] Online resources probably shouldn't have "Print." (fixed in #3422)
![image](https://user-images.githubusercontent.com/35857611/234752316-7e6570b4-610a-4b26-9626-296c35264643.png)

**Comment by harmanpreet-sagar** [comment]
@samm82 Could you tell me where you found the reference from Philip Wexler, as I am unable to find it in any of the code, issues, PRs or bibliographies, either here or on Gitlab.

**Comment by samm82** [comment]
Ooh good point - I didn't even think of that! This was reference specific to the ChemCode example, which is being worked on on my fork of the repo; this specific reference can be found [here](https://github.com/samm82/Drasil/blob/ab00d3ae1e80751e081cb94dd357434ecbda62e1/code/drasil-data/lib/Data/Drasil/Citations.hs#L80-L82). However, the edition number for this reference is specified with `edition 3`, which is being incorrectly rendered by Drasil; hopefully you'll be able to find and fix where this rendering takes place.

This issue also takes place in SSP (which I've added to the actual issue body above).

**Comment by harmanpreet-sagar** [comment]
Oh ok. Yhanks for clarifying and for that additional reference!

**Comment by samm82** [comment]
It looks like we're actually using the IEEE style, which explains why we are getting the numbers in square brackets generated in the HTML reference list.

https://github.com/JacquesCarette/Drasil/blob/6c9313c35800fb032087637949a4d507363189b6/code/stable/projectile/SRS/PDF/Projectile_SRS.tex#L1295

I would wait for @smiths to confirm that this is desired and if not, which [Natbib style](https://www.overleaf.com/learn/latex/Natbib_bibliography_styles) we would want to use. Then we can make sure that our HTML (and probably Jupyter) references are being generated according to these rules.

**Comment by harmanpreet-sagar** [comment]
You mention that we use IEEE style but like these code chunks here 

https://github.com/JacquesCarette/Drasil/blob/6c9313c35800fb032087637949a4d507363189b6/code/drasil-printers/lib/Language/Drasil/HTML/Print.hs#L411-L422

kind of indicates that we are using the MLA, APA and Chicago. I may be misunderstanding this but aren't we rendering the citations based on this style? 

https://github.com/JacquesCarette/Drasil/blob/6c9313c35800fb032087637949a4d507363189b6/code/drasil-printers/lib/Language/Drasil/HTML/Print.hs#L353-L359

The square numbers do make sense now but I am not quite understanding why we are using MLA, APA and Chicago style helpers if we are citing in IEEE. I will research the IEEE style also though now.

**Comment by smiths** [comment]
@samm82 I personally prefer natbib, but for now I think we should leave the references in the ieee format.  Eventually changing the format should be a configurable parameter for the user.  For now generating in one standard format is fine.  Our sentences will be awkward if we naively change to natbib, since they were written for the ieee format.

The [ieee format](https://www.bath.ac.uk/publications/library-guides-to-citing-referencing/attachments/ieee-style-guide.pdf) uses commas between authors, as @harmanpreet-sagar mentioned for other formats above.  We should probably drop the idea of semicolons for now.

**Comment by samm82** [comment]
I think we should return to this discussion again, since IEEE also lists authors by their initials follow by their last name, so commas _only_ appear between different authors, but I agree that this is a lower priority thing to focus on. I'll make an issue to implement choices for reference format so we don't lose this idea, but I think this issue can be closed for now.
