### ISSUE TITLE
Drasil Research Group Meeting Agenda, May 2nd at 2:30pm EST in ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3361]
The agenda for this coming week is as follows:

0. Introductions
1. Jason update
2. Sam update
3. Issues for summer students (Harmanpreet (@harmanpreet-sagar), Ricky (@hrzhuang), Manvendra)
4. Overview of ChemCode SRS (@samm82), we can discuss the Drasil implementation too if there is time
5. Cold cases/Code Review/Discussion
  a. @tingyuw
  b. @cd155
  c. @samm82
  d. @balacij
  e. @tingyuw 
6. Questions/Comments/Concerns/Discussion

Future Agenda items

- Discussion of Problems with Model Driven Engineering paper by Paige et al. (@balacij) (Antonio Bucchiarone, Jordi Cabot, Richard Paige, and Alfonso Pierantonio. “Grand challenges in model-driven engineering: an analysis of the state of the research”. In: Software and Systems Modeling 19 (2020-01), pp. 1–9. doi: 10.1007/s10270-019-00773-6)
- CAS 741 Project: BeamBend overview (@balacij)
- CAS 703 Project: Verified Calculators (@balacij)

**Comment by balacij** [comment]
Looks like we're going to be continuing the Tuesdays at 2:30pm. Shall we book a room?

I look forward to meeting everyone! :smile:

**Comment by smiths** [comment]
Thank you @balacij for updating the issue with the date and time.

I've sent in a request to book a room.  I'll update the issue when I get a confirmation back.

**Comment by smiths** [comment]
The meeting will take place in ITB/225.

**Comment by smiths** [comment]
We covered all the planned agenda items.
