### ISSUE TITLE
Possible typo in `pidControllerSystem`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3364]
The variable is called `pidControllerSystem` but the strings inside all say "PD" instead of "PID."

**Comment by smiths** [comment]
Good job noticing the potential inconsistency @hrzhuang, but the scope of PD Controller doesn't include the integral part.  It is PD on purpose (proportional and differential, not integral).  You can find the scope for PD Controller in the [SRS](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html) in the "Scope of Requirements" section.

**Comment by hrzhuang** [comment]
In that case, shouldn't the variable be called `pdControllerSystem` instead of `pidControllerSystem`?

**Comment by smiths** [comment]
Yes, you are right that `pdControllerSystem` makes more sense.  I'll reopen this issue.  :smile:
