### ISSUE TITLE
Purpose of `pdControllerCI`, `proportionalCI`, `derivativeCI`, `integralCI`, and `pidCI`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3365]
These are abuses of `commonIdeaWithDict` in the context of #3315 (they have no domain), and they also do not seem to be used anywhere in the codebase. What is their purpose?

**Comment by JacquesCarette** [comment]
It would be worth looking to see if they *should* be used in the code base. Maybe there is some duplicated information? I would certainly look to see if things like if the word `proportional` (as a `String`, not as a name of a variable) shows up in other `String` s. There are likely chunks that are built "by hand" that ought to be built more incrementally.

Of course, it might also make sense to remove the raw `CI` s as those are not very informative.

**Comment by hrzhuang** [comment]
I see, that makes sense. In the scope of this issue, is it okay if we close it with the removal of the raw `CI`s?

**Comment by JacquesCarette** [comment]
Yes.

**Comment by hrzhuang** [comment]
Actually I was mistaken about these not being used anywhere in the code base. They are used for the acronyms section of the SRS. They are still abuses of `commonIdeaWithDict`, and that can be addressed as part of #3315. I think we can close this now. Thanks!
