### ISSUE TITLE
Add summer students to Discord

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3366]
@ManvendraJani @hrzhuang and @harmanpreet-sagar, what are your Discord IDs so @JacquesCarette can add you to the Discord?

**Comment by harmanpreet-sagar** [comment]
Discord: Crix007 #1592

**Comment by ManvendraJani** [comment]
Man_Vendor#3573

**Comment by smiths** [comment]
Is there any drawback to sharing discord ids in a public place?  I don't see the harm, but out of an abundance of caution, I thought I'd ask the question.  :smile:

**Comment by samm82** [comment]
That is ... an excellent question I hadn't thought of 😅 I think the worst case is that someone could be able to send someone a friend request/message, but then they could easily be blocked - we could also delete the usernames from here once we're done with them (or do it now and share these IDs in a more private way!)

**Comment by hrzhuang** [comment]
In light of the discussion here with respect to privacy, I have emailed my Discord ID to Dr. Carette.

**Comment by harmanpreet-sagar** [comment]
I agree, it would be great to delete the usernames once we have been added to Discord.

**Comment by balacij** [comment]
It shouldn't be much of an issue since we don't store anything sensitive (or rather shouldn't!) on Discord. I _think_ you should also be able to join via the Discord invite links. I'll email one to test!

**Comment by samm82** [comment]
Since everyone's in the Discord and all IDs have been deleted from this issue, I'm closing it 😁

**Comment by smiths** [comment]
Thanks @samm82 and @balacij.
