### ISSUE TITLE
Improving the stylesheet

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#337]
As mentioned by @szymczdm in commit 844638d, "some CSS still needs to be added to the stylesheet in order to get the line over the sqrt. That is fairly low priority at the moment."

**Comment by njericha** [comment]
http://www.scientificpsychic.com/etc/square-root.html

**Comment by szymczdm** [comment]
#479 will handle this, since we will be using MathJax. However, if we're going to continue maintaining both (#300), we'll either need to tackle this issue or decide it's "good enough" and for it to be "prettier" move to MathJax.

@JacquesCarette @smiths any thoughts?

**Comment by JacquesCarette** [comment]
I agree. I think we will maintain both the raw HTML version (which will not be all that pretty, and not fix this) and the MathJax, which should be pretty (or be fixed). So I think this one can in fact be closed?

**Comment by smiths** [comment]
Agreed.  We can close this issue.
