### ISSUE TITLE
7z: Command Not Found on Windows

### ISSUE THREAD

**Issue by ManvendraJani** [JacquesCarette/Drasil#3373]
[New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) missing [7zip](https://www.7-zip.org/) installation guide for Windows.

**Comment by balacij** [comment]
Did this fix your issue? I thought you said it didn't.

**Comment by ManvendraJani** [comment]
no I still get command not found

**Comment by JacquesCarette** [comment]
You might need to close your terminal window and re-open for the new path to take effect. Or even reboot.

**Comment by ManvendraJani** [comment]
I did try that. Additionally both `make` and `make hlint` work separately.

**Comment by balacij** [comment]
Sorry, what do you mean by they work separately?

I'm very surprised that you two are facing these issues so often. Did you both follow the New Workspace Setup guide? I used that on a fresh Windows VM when I made it, and everything worked fine at the time.

**Comment by ManvendraJani** [comment]
Sorry the wording want very clear, both make and make hlint work without returning any errors, but when running make pr_ready I get the mentioned error code. 

I did follow the workplace guide all the way through, I am using git bash.

**Comment by balacij** [comment]
Gotcha! Ok, in that case, we'll need to later update the New Workspace Guide too.

Were you able to locate the 7z binary on your computer? Did you add it to your PATH and relogin to your Windows user account?

**Comment by balacij** [comment]
I vaguely remember @JacquesCarette saying that "Chocolatey" fixes a lot of the package management issues on Windows nowadays, so an alternative installation method might be to use the `choco` package manager.

**Comment by ManvendraJani** [comment]
I used Chocolatey to install stack and graphviz, I am not sure if anything else can be installed through it though.

**Comment by balacij** [comment]
https://community.chocolatey.org/packages/7zip.install

Can this be used?

**Comment by ManvendraJani** [comment]
So I reinstalled 7zip using `choco` and that seems to have fixed the issue.

**Comment by balacij** [comment]
Ah, perfect, no issues at all after that? If so, can you please also add this to the Windows-focused area of the "Basic Development Tools" in the New Workspace Setup Guide, and then close this ticket?

**Comment by smiths** [comment]
@ManvendraJani for future traceability, can you please add a link to the changes that you made in the "Basic Development Tools" section before closing the issue.

**Comment by ManvendraJani** [comment]
https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup#7-zip
