### ISSUE TITLE
Typo in wiki page for lenses

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3374]
The section [Defining Lenses](https://github.com/JacquesCarette/Drasil/wiki/Lenses#defining-lenses) contains the following code snippet.
```hs
data MyFirstProgram = FirstProgram {
    _hello :: String
    _world :: String
}
makeLenses''
```
Is the last line supposed to say `$(makeLenses ''MyFirstProgram)`? I am not very familiar with lenses and Template Haskell so I just want to check.

**Comment by balacij** [comment]
Ah, I think it should say `makeLenses ''MyFirstProgram`, good catch!  We don't need to splice it ourselves because GHC splices all module-level template Haskell declarations.

**Comment by balacij** [comment]
There should also be a comma after the first `String` :wink:

**Comment by hrzhuang** [comment]
Ah I see. I fixed both the `makeLenses` and the comma. Closing the issue now.
