### ISSUE TITLE
Add choices to design language

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#338]
The following choices should be added to the language of design:

- [x] Inputs as class vs. individual variables

- [ ] Generation of library vs. program

- [x] Logging of function calls

- [x] Logging of variable assignments

- [ ] Commented code

- [x] Assertions vs. warnings on physical constraints

- [x] Assertions vs. warnings on software constraints

**Comment by JacquesCarette** [comment]
What is blocking further progress on this?

**Comment by JacquesCarette** [comment]
@palmerst As this turned out to be a bigger thing, could you please create issues for each of the 3 not-yet-done aspects above, delete them from this list here, and close this one?

**Comment by palmerst** [comment]
Logging of variable assignments is actually done (forgot to check it off).  

This issue is closed for the marked items.  The other 2 have new separate issues in #443 and #444.
