### ISSUE TITLE
Empty `purpose`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3390]
It seems that in all of our examples, the `purpose` in a `SystemInformation` is always empty. Is this being set somewhere that I missed, or are we simply not using this at the moment?

**Comment by balacij** [comment]
This is a recent addition -- from #3225. @smiths might need to be the one to fill them in (?).

**Comment by smiths** [comment]
@hrzhuang please create an issue for us to fill in the `purpose` information.  You don't have to assign it to me.  Anyone should be able to deduce the purpose of our different examples by reading the introduction.

**Comment by hrzhuang** [comment]
I created issue #3391. Closing this one now.
