### ISSUE TITLE
Trouble compiling generated LaTeX

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3392]
When I run `make` under the `SRS/PDF` directory of any of the the examples (I'm using Projectile here as an example), I get the following error.
```
! Dimension too large.
\LT@max@sel #1#2->{\ifdim #2=\wd \tw@ 
                                      #1\else \number \c@LT@chunks \fi }{\th...

l.140 \end{longtabu}
```
I am using version 2023.0314 of the MacTeX distribution.

The full table that causes this error is as follows.
```latex
\begin{longtabu}{l X[l] l}
\toprule
\textbf{Symbol} & \textbf{Description} & \textbf{Units}
\\
\midrule
\endhead
$a$ & Scalar acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${a^{c}}$ & Constant acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${a_{\text{x}}}$ & $x$-component of acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${{a_{\text{x}}}^{\text{c}}}$ & $x$-component of constant acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${a_{\text{y}}}$ & $y$-component of acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${{a_{\text{y}}}^{\text{c}}}$ & $y$-component of constant acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
$\symbf{a}$ & Acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
${\symbf{a}^{\text{c}}}$ & Constant acceleration vector & $\frac{\text{m}}{\text{s}^{2}}$
\\
${d_{\text{offset}}}$ & Distance between the target position and the landing position & ${\text{m}}$
\\
$\symbf{g}$ & Gravitational acceleration & $\frac{\text{m}}{\text{s}^{2}}$
\\
$p$ & Scalar position & ${\text{m}}$
\\
${p^{\text{i}}}$ & Initial position & ${\text{m}}$
\\
${p_{\text{land}}}$ & Landing position & ${\text{m}}$
\\
${p_{\text{target}}}$ & Target position & ${\text{m}}$
\\
${p_{\text{x}}}$ & $x$-component of position & ${\text{m}}$
\\
${{p_{\text{x}}}^{\text{i}}}$ & $x$-component of initial position & ${\text{m}}$
\\
${p_{\text{y}}}$ & $y$-component of position & ${\text{m}}$
\\
${{p_{\text{y}}}^{\text{i}}}$ & $y$-component of initial position & ${\text{m}}$
\\
$\symbf{p}$ & Position & ${\text{m}}$
\\
$s$ & Output message as a string & --
\\
$t$ & Time & ${\text{s}}$
\\
${t_{\text{flight}}}$ & Flight duration & ${\text{s}}$
\\
$v$ & Speed & $\frac{\text{m}}{\text{s}}$
\\
${v^{\text{i}}}$ & Initial speed & $\frac{\text{m}}{\text{s}}$
\\
${v_{\text{launch}}}$ & Launch speed & $\frac{\text{m}}{\text{s}}$
\\
${v_{\text{x}}}$ & $x$-component of velocity & $\frac{\text{m}}{\text{s}}$
\\
${{v_{\text{x}}}^{\text{i}}}$ & $x$-component of initial velocity & $\frac{\text{m}}{\text{s}}$
\\
${v_{\text{y}}}$ & $y$-component of velocity & $\frac{\text{m}}{\text{s}}$
\\
${{v_{\text{y}}}^{\text{i}}}$ & $y$-component of initial velocity & $\frac{\text{m}}{\text{s}}$
\\
$\symbf{v}$ & Velocity & $\frac{\text{m}}{\text{s}}$
\\
$\symbf{v}\text{(}t\text{)}$ & 1D speed & $\frac{\text{m}}{\text{s}}$
\\
${\symbf{v}^{\text{i}}}$ & Initial velocity & $\frac{\text{m}}{\text{s}}$
\\
$ε$ & Hit tolerance & --
\\
$θ$ & Launch angle & ${\text{rad}}$
\\
$π$ & Ratio of circumference to diameter for any circle & --
\\
\bottomrule
\caption{Table of Symbols}
\label{Table:ToS}
\end{longtabu}
```

**Comment by JacquesCarette** [comment]
Can you put the whole table that is generated into the bug report please? Am I correct when I think that this works under the CI, so that there is a mismatch between the latex it uses about your version?

**Comment by balacij** [comment]
[It's supposed to](https://github.com/JacquesCarette/Drasil/blob/102d126671c1e3cdbe06ffcd8dd3f65769911962/.github/workflows/Build.yaml#L67-L68), yes.

I've never heard of the longtabu environment. I wonder if longtable could be a drop-in fix?

**Comment by JacquesCarette** [comment]
That's not even a large table! I have no idea what's going on. I'd use `git blame` first, to see who introduced the use of `longtabu`. I'm fairly sure there were reasons - there might be something in a (closed) issue to investigate before jumping to a "fix".

**Comment by smiths** [comment]
@hrzhuang I don't get the longtable error when I locally run make for the pdf files.  (I get errors related to missing traceability graphs, but that is because I haven't created them locally.)

**Comment by hrzhuang** [comment]
So before I was going into the `build/glassbr/SRS/PDF` directory and running make there, but just now I tried `make tex` from the `code` directory and it is able to generate the PDFs. The `longtabu` errors are still in the console output but I guess our `Makefile` instructs $\TeX$ to push on despite it. The `make` command does still end in the error

```
make[1]: *** [GlassBR_SRS.pdf] Error 1
make: *** [glassbr_tex] Error 2
```

But it is not clear to me what the error is (there is a lot of console output and it is not clear what is **the** error), since the PDFs are being generated and at a glance they look fine.

**Comment by smiths** [comment]
I don't get the same errors @hrzhuang when I run `make tex`.  I get warnings about `longtabu`, but no errors.  All of the pdf file are generated without make ending with an error.

Is there maybe a configuration different for your local installation of Lualatex that considers some warnings as errors?

**Comment by hrzhuang** [comment]
So actually the `longtabu` messages don't explicitly say "error," they are just what stopped LuaLaTeX when I was running it manually (semi-manually through the Makefile inside `build/glassbr/SRS/pdf`).

When I search for the string "error" in my LuaLaTeX output, most of them are of the form
```
! LaTeX Error: There's no line here to end.
```
Then there are some errors related to SVG, like
```
! Package svg Error: Inkscape version not detected.
```
and
```
! Package svg Error: File `avsa_svg-raw.pdf' is missing.
```

Do you get these errors? Based on the SVG errors, is Inkscape required for generating the PDFs?

**Comment by smiths** [comment]
Yes, Inkscape is necessary to fully compile the LaTeX documents.  If it isn't available, then the traceability graphs won't be 
 built via `make tracegraphs`.  This topic has recently been discussed in #3445 and #3443.  The instructions for installing Inkscape are in the [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) instructions.  If you follow the instructions and something is missing, or unclear, we should work to address the problem.

**Comment by hrzhuang** [comment]
I have now installed Inkscape, which resolves the SVG errors but the "no line here to end" errors still remain. Do those errors occur on your setup?

**Comment by smiths** [comment]
@hrzhuang I don't get the same complaints about "no line here to end".  The offending line (`\\ midrule \\`) doesn't cause any complaints on my system.  I tried to reproduce your error message with a different LaTeX compiler, but I couldn't get it to complain.  What is your version of `lualatex`?  Mine is `1.13.0 (TeX Live 2021)`.

**Comment by hrzhuang** [comment]
I have
```
This is LuaHBTeX, Version 1.16.0 (TeX Live 2023)
```

**Comment by smiths** [comment]
That makes me think that I should update my version of lualatex.  :smile:

**Comment by smiths** [comment]
Good investigation @balacij.  Can we change the tex generator so that it doesn't place `\\` at the beginning of a line?  If it only happens for `\midrule` it should be easy to find, I think?

**Comment by balacij** [comment]
I think so. A quick `rg "midrule" -ths` shows we only have 2 mentions:
```console
drasil-printers/lib/Language/Drasil/TeX/Print.hs
209:  %% command0 "midrule"
351:  where dBoilerplate = pure $ dbs <+> text "\\midrule" <+> dbs
```

Any takers? 🙂

**Comment by smiths** [comment]
@hrzhuang I don't know the answer to your question.  I don't get the same error from `make`.  I don't think the cause is `Overfull`.  I get that with almost all of my LaTeX files.  :smile:  

Maybe the problem is related to the version of `make`?  My `make` is `GNU Make 3.81`. 

Do you get the error when you run `make` for a single example in the `\SRS\PDF` folder, or is this only from `make tex`?

**Comment by hrzhuang** [comment]
> I don't think the cause is `Overfull`. I get that with almost all of my LaTeX files. 😄

In your generated PDF for GlassBR, does the table of symbols extend off the page to the right? That would be a problem even if it's not the cause of the error in this case, right?

> Maybe the problem is related to the version of `make`? My `make` is `GNU Make 3.81`.

My `make` is also `GNU Make 3.81`.

> Do you get the error when you run `make` for a single example in the `\SRS\PDF` folder, or is this only from `make tex`?

I also get the error when I run `make glassbr_tex`. If I run `make` in `build/glassbr/SRS/PDF` or run `lualatex GlassBR_SRS.tex` directly, `lualatex` stops on the `longtabu` problem and asks me how to proceed.

I also tried adding the `TEXFLAGS` that are used by `make tex` when running `make` under `build/glassbr/SRS/PDF`. So I run
```
make TEXFLAGS="-interaction=nonstopmode --shell-escape" BIFLAGS=""
```
and it ends with
```
make: *** [GlassBR_SRS.pdf] Error 1
```

When I run `lualatex -interaction=nonstopmode --shell-escape GlassBR_SRS.tex` directly it ends with a exit code of 1.

**Comment by smiths** [comment]
@hrzhuang my table of symbols for projectile does not extend past the bottom of the page.  (I'll attach my generated pdf.)  The traceability tables extend past the margins, but Table 2 (Table of Symbols) seems to be working as expected.

I think you are on to something with your problem being related to `longtabu`.  I searched the output of make to see any errors or warnings related to `longtabu` and I didn't find any.  In case it helps, I'll attach the output from using make on the projectile example (in the SRS/PDF folder).

Given that you can get the pdf files @hrzhuang, maybe we ignore the make errors?  It isn't a very satisfying resolution, but I'm running out of ideas.  :smile:

[Projectile_SRS.pdf](https://github.com/JacquesCarette/Drasil/files/11615987/Projectile_SRS.pdf)

[makeout.txt](https://github.com/JacquesCarette/Drasil/files/11616044/makeout.txt)

**Comment by hrzhuang** [comment]
Yeah something is definitely wrong with my tables. In my table of symbols the description extends too far so even the units are pushed off the page. I think the `longtabu` is the culprit here after all, since the message
```
! Dimension too large.
<to be read again> 
=
l.142 \end{longtabu}
                  
I can't work with sizes bigger than about 19 feet.
Continue and I'll use the largest value I can.
```
begins with an exclamation mark.

I think this is definitely a problem beyond just annoying error messages, but I don't think it is a priority in the present moment? I would be interested in hearing how this runs on anyone else's setup though.

There is also the fact that the error from GlassBR stops `make tex` from generating PDFs for the other examples, which is a little annoying but also not a priority?

Though I am at a good stopping point with regards to GOOL vectors before tomorrow's meeting, so I think I will spend a bit more time trying to figure out what's going on with `longtabu`.

**Comment by smiths** [comment]
@hrzhuang it would be good to know who else has this problem.  @balacij, @samm82, @ManvendraJani, @harmanpreet-sagar, what happens when you run make in the `/Drasil/code/build/projectile/SRS/PDF` folder?  Do you get error messages, or do you get the expected pdf file?  (If you haven't been following this thread, some common error situations you might run into (like problems with Inkscape) are covered above.)

I'm not an expert on makefiles, but it would be nice if a failure in GlassBR didn't halt the process for the other files.

I agree that you should continue to look into this.  I don't want to ignore an error message.  Besides the annoyance of the message, it might be a clue to some deeper issue.  On the other hand, there are plenty of important issues that we wish to close.  As always, it is difficult to decide when to move on from a problem that hasn't been resolved.  We can discuss priorities during our meeting tomorrow.

**Comment by balacij** [comment]
If I run the makefile in the projectile/SRS/PDF folder, I get the following error:
```
! Dimension too large.
\LT@max@sel #1#2->{\ifdim #2=\wd \tw@ 
                                      #1\else \number \c@LT@chunks \fi }{\th...
l.142 \end{longtabu}
```

If I run `make projectile_tex` from the `code/` folder, I get Inkscape errors:
```
Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: 12:38:37.812: Error: Inkscape encountered an internal error and will close now.
```

However, if I open the PDF, everything is seemingly fine -- dot graphs appear, traceability matrices appear, I don't see anything not there.

**Comment by balacij** [comment]
I think that our [Makefiles and scripts can use a good clean up](https://github.com/JacquesCarette/Drasil/projects/15).

**Comment by smiths** [comment]
I think part of the problem is that we tend to ignore the LaTeX files.  The html version is much easier to interact with.  Since we don't really look at the LaTeX files anymore, we don't notice the problems.

**Comment by balacij** [comment]
@hrzhuang Yes, it goes off the page as you explained.

**Comment by samm82** [comment]
> If I run the makefile in the projectile/SRS/PDF folder, I get the following error:
> 
> ```
> ! Dimension too large.
> \LT@max@sel #1#2->{\ifdim #2=\wd \tw@ 
>                                       #1\else \number \c@LT@chunks \fi }{\th...
> l.142 \end{longtabu}
> ```

Going through all of the errors, I get some dimensions too larges, undefined references, no line here to breaks, and missing SVGs. This results in a PDF with an empty table of contents and References section, a Table of Symbols that unnecessarily goes off the page, an incorrectly sized Table of Abbreviations and Acronyms and Table of Auxiliary Constants, incorrectly aligned FRs and NFRs, traceability matrices that go off the page, and no working hyperlinks.

**Comment by ManvendraJani** [comment]
I did not see anything in the new workspace setup about adding `tabu` as a package of MiKTeX should this be added?

**Comment by ManvendraJani** [comment]
I also am having the same issues as Ricky and Harman regarding the pdf file

**Comment by smiths** [comment]
I had no idea that everyone is having trouble compiling the pdf files.  Nobody has complained lately.  We know there are issues with the appearance of the tables (because of the long names), but the current problems obviously go deeper.  I've added this as an agenda item for this week.

**Comment by hrzhuang** [comment]
I think the problem comes from the `tabu` package. I found a [Stack Exchange post](https://tex.stackexchange.com/questions/611974/tabu-package-table-out-of-page) of people having similar problems, and the response seems to be that the `tabu` package is broken and unmaintained.

This aligns with what I've seen, which is that `tabu` offers a way to specify the width of the table, but it just doesn't listen (the table still goes off the page even when I tell it to be 4 inches wide). It also makes sense that @smiths is able to generate the PDF without problems: this functionality worked at some point in the past (in @smiths's version) but it is now broken.

The aforementioned Stack Exchange post offers the package `tabularray` as an alternative. I will look a bit more into it.

**Comment by smiths** [comment]
Your explanation makes sense @hrzhuang.  I also agree with the proposed solution of using a more up to date alternative to `tabu`, like `tabularray`.  I would hope that it would be an easy change to change the generator to use a different package.  We should keep track of how many lines of code need to be modified.  Hopefully they are all in one place, or at least not in too many places.  We could then use this as an example of the maintainability of the Drasil-generated code.   All the examples with `tabu` will be broken and we can fix them all at once.  If the fix isn't easy, we should figure out why it isn't easy, so that we can make it easier in the future.

**Comment by hrzhuang** [comment]
I created new issues #3457 and #3458 to address the `\\ \midrule \\` and `longtabu` errors respectively. I think we should keep this issue open since this issue is about being able to generated PDFs without errors. Once #3457 and #3458 are both resolved, there should be no more LaTeX *errors* (lots of warnings remain!) and we can then close this issue.

**Comment by hrzhuang** [comment]
#3457 and #3458 have both been resolved. Closing this issue now.
