### ISSUE TITLE
Difference between `make stabilize` and `make test`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3411]
`make test` ignores `.txt` files in the `diff` checks, which is why we now have (surprising) changes in current PRs.

To solve this, we either need to ignore `.txt` files in `make stabilize` or consider `.txt` files in `make test` (which I think we should do). If the latter, we should only need to remove the `-x '*.txt'` from the Makefile's defined `DIFF`.

**Comment by JacquesCarette** [comment]
Any idea why we ignore `.txt` files?

**Comment by JacquesCarette** [comment]
(oops, I don't think I meant to close this!)

**Comment by balacij** [comment]
After a bit of digging: #1266, `.txt` files were removed because of copied `.txt` files into the `build/` folder for testing the build artifacts. However, when we use `make stabilize` now, it builds a fresh copy of the `build/` folder for each example, and then copies them over. So, the issue _should_ never occur. I guess it was an overlooked thing, since I think the `designLog.txt` files should be checked in and `diff`'d.
