### ISSUE TITLE
Program consisting of only a `varDec` causes GOOL to fail

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3420]
The following GOOL program produces the error message `Main module missing`.
```haskell
testProgram :: OOProg r => GSProgram r
testProgram = prog "Test" [fileDoc $ buildModule "Test" [] [testMain] []]

testMain :: OOProg r => SMethod r
testMain = mainFunction $ body [block [varDec (var "x" int)]]
```
However, if I change the `varDec` to a `varDecDef`, then it works.
```haskell
testMain :: OOProg r => SMethod r
testMain = mainFunction $ body [block [varDecDef (var "x" int) (litInt 0)]]
```
What is going on here?

**Comment by balacij** [comment]
Hmm, that's interesting. Do you think you can push your working code to a branch so that we can have a look at it too?

**Comment by hrzhuang** [comment]
I've pushed the working code to the branch `3420-working` and the failing code to the branch `3420-failing`. In both branches the code is in `drasil-code/test/TestProgram.hs`. I have been running it with `stack test drasil-code` (I describe this in more detail in #3414).

**Comment by JacquesCarette** [comment]
That's definitely a bad error message. But I think this should be an error - Swift, for example, must have all variables initialized. So just declaring it is not enough.
