### ISSUE TITLE
`Macros` vs `LanguagePolymorphic`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3426]
It seems that `GOOL.Drasil.LanguageRenderer.Macros` and `GOOL.Drasil.LanguageRenderer.LanguagePolymorphic` contain similar kinds of constructs. What is the difference between these two modules? (Or rather, when we write a function, how do we know whether to put it in `Macros` or in `LanguagePolymorphic`?)

**Comment by balacij** [comment]
Taking a quick look at them, it looks like `Macros` contains tools that are built based on `LanguagePolymorphic`. So, I think that if you're adding something "completely new", then it should go into `LanguagePolymorphic`, however, if you're building something that can be defined in preexisting terms, then it should go in `Macros`.

**Comment by hrzhuang** [comment]
I see, that makes sense. Thanks!
