### ISSUE TITLE
Investigate requirements for `make tracegraphs'

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3443]
The [makefile wiki entry](https://github.com/JacquesCarette/Drasil/wiki/Makefile) doesn't mention `make tracegraphs`.  Should we add a description?  I always forget that this is how the traceability graphs are created since I don't do it very often.  :smile:

**Comment by balacij** [comment]
That sounds like a good idea to me! I added a small description. Do you think it is ok?

**Comment by smiths** [comment]
Thanks for the hint @balacij.  I created a new stack project in a new folder and `stack install dotgen`, followed by `stack install graphmod` resulted in the same error.  Since you mentioned the cache, I went with this and deleted the `.stack` folder.  It took some time to rebuild everything, but the next time around `make tracegraphs` worked!

To finish the story, I had two more problems to solve before I could successfully build our PDF files:

1. The makefile runs `lualatex Projectile_SRS`, but svg requires (on my computer at least) `lualatex --enable-write18 Projectile_SRS`
2. Inkscape wasn't visible on the command line, so I had to add it to the `PATH` environment variable

Would adding `--enable-write18` to the `Makefile` break the build on other computers?  If not, I'd like to suggest that we add it to our generated `Makefile`.

With respect to the second point, I'll add a hint in the [New Workspace Setup for Inkscape](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup#inkscape) to mention adding Inkscape to the `PATH` environment variable.

**Comment by balacij** [comment]
Ah, nice!

I see. It looks like [`write18` is deprecated](https://tex.stackexchange.com/questions/366189/how-should-i-have-found-out-that-luatex-removed-write18) now. Does `--shell-escape` work instead? For sure, we should add something to make sure InkScape-based SVG rendering works.

**Comment by smiths** [comment]
The first thing I tried was `--shell-escape`.  For some reason it didn't work, but when I just tried it again it worked fine!  The short answer is that yes, `--shell-escape` works.  :smile:

**Comment by smiths** [comment]
If we can't modify the generated `Makefile` to work for everyone, we could maybe generate a comment that `--shell-escape` might be necessary for some systems.  I find that I forget little tricks like this.  3 months from now I won't remember what I had to do to get inkScape-based SVG rendering to work.  :smile:

**Comment by balacij** [comment]
I'm surprised it's been working without `--shell-escape`. We should definitely add it if we are using `\includesvg`.

**Comment by smiths** [comment]
I created an issue (#3445) for adding the shell escape to the makefile.  The original issue was actually closed a long time ago, so I'll close this issue.  Thank you @balacij for indulging my questions.  :smile:
