### ISSUE TITLE
What is `Linearity`?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3448]
`sentenceDoc` from `Language.Drasil.Printers` in `drasil-printers` takes a `Linearity`. What is `Linearity`?

**Comment by JacquesCarette** [comment]
Digging a little deeper, we see that only `Language.Drasil.Plain.Print` defines/uses `Linearity`. This is our "plain text" printer, which is used, in part, by the code printer as well as the Log printer. [The code printer wants certain things to be on one line, the log printer doesn't care).

In this case, `Linearity` is used to mean "all on one line". This is possibly not the best name ever, as `Linearity` is also used in scientific computing as well as in programming languages, to mean 'something else'.

```haskell
data SingleLine = OneLine | MultiLine
```
would be way better.

**Comment by hrzhuang** [comment]
I see, thanks! Should I create an issue to update the documentation for `Linearity`? The current documentation just says "Data is either linear or not."

**Comment by smiths** [comment]
Yes, I think it would be a great idea to update the documentation, or we'll be getting the same question again in the future.  :smile:

**Comment by hrzhuang** [comment]
I have created an issue to improve the documentation, closing this one now.
