### ISSUE TITLE
Enumeration of Missing Items (Assumptions, LikelyChanges, etc.) in HTML

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#345]
I have been trying to implement the remaining layout object types in order to create more accurate acro- commands, and by extension import additional content from SWHS, but I have hit an issue.  As it stands, constructors such as Assumption make use of what appears to be a built in counter-function for the TeX files, allowing for enumeration of a particular set of type X without additional information.

e.g.: `\item[\refstepcounter{assumpnum}\atheassumpnum\label{Aassump3}:]The water in the tank is fully mixed, so the water temperature is the same throughout the entire tank.`

However, since HTML does not have access to this kind of thing (I think?) it cannot generate an enumerated list with the information it currently has.  Is there a preferred way of dealing with this?

edit:
Ideas (Using Assumption as an example):
-Alter the information that needs to be passed to Assumption (e.g. Have Drasil provide each Assumption with a number and pass that to the converter)
-Pass Assumption as a list of AssumpChunks and process it like a List
-Disregard the need for enumeration of Assumption in HTML

**Comment by szymczdm** [comment]
Can you show an example of the different outputs in the generated versions? We may use short names instead of enumeration for HTML (as we've been heading in that direction), but I'd need to see an example of what exactly is going wrong.

**Comment by AKM11** [comment]
Here is an example of the differences in output.

![image](https://user-images.githubusercontent.com/28261578/27912311-6821f6d2-622a-11e7-9a04-339448321343.png)

Keep in mind I have been messing around with the HTML output.  This is using the Assumption type.

**Comment by AKM11** [comment]
I have created a useable referencing system for the Assumption type as of commit b8a03ba5794d9e7a71eb74d3fc814e2c14b0ce26. Will this work?  Example in NoPCM.

**Comment by JacquesCarette** [comment]
[See the comments there].  Something like that will indeed work.

**Comment by AKM11** [comment]
@JacquesCarette I updated the acroNumGen function in commit 4f4ceebe0d76ffb7a2f94897573402cdbf16e89c.  This slightly better?

**Comment by AKM11** [comment]
Also, are things like physical system descriptions and goal statements supposed to have there own type as well? They require referencing in places and we have acro- commands for them.

**Comment by JacquesCarette** [comment]
I do think that physical system description and goal statements should have their own type.

**Comment by AKM11** [comment]
@JacquesCarette I agree that physical system description probably does not require its own type but what is the plan, if any, for referencing goal statements if goal statements does not?

**Comment by JacquesCarette** [comment]
We might need to create a type for goal statements if that is how we do referencing in all other cases.

**Comment by AKM11** [comment]
Note to self: Keep trying to get Definition type to work.

**Comment by AKM11** [comment]
Note to self: Theory works as of commit f6b6573b81be2353021978794f37f2c52d6696b6, keep working on Data.

**Comment by AKM11** [comment]
Note to self: Data is now working, need to wait on the complete implementation of other types before Definition can be considered completely functional.

**Comment by JacquesCarette** [comment]
Upon rereading this, I am not sure what I can do on it.  Yes, it does seem that something piecemeal can be done, but it is all about referencing -- so paging @szymczdm to tell us what specifically should be done to move this forward.

**Comment by szymczdm** [comment]
This one's essentially done except for the part mentioned in #470 which is blocking the last piece from falling into place.

**Comment by JacquesCarette** [comment]
Will there be things for either me or Spencer to do?  If not, does it make sense to have us as assignees?

**Comment by samm82** [comment]
This should be addressed with #562

**Comment by JacquesCarette** [comment]
Because the last piece of this is related to ALUR de-embedding and related changes, I am changing ownership of this to @Mornix .

**Comment by Mornix** [comment]
ALUR is gone. As are the builtin counters. I'm closing this issue as it is effectively done and the final details can be followed in #1026 and the PR #1100.
