### ISSUE TITLE
LaTeX generated files not ignored by Git

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3456]
After I run `make projectile_tex` for example, the generated PDF and auxiliary files causes an error when we diff `build` with `stable`.
```
Only in build/projectile/SRS/PDF: Projectile_SRS-blx.bib
Only in build/projectile/SRS/PDF: Projectile_SRS.pdf
Only in build/projectile/SRS/PDF: Projectile_SRS.run.xml
Only in build/projectile/SRS/PDF: bibfile.bib
Only in build/projectile/SRS/PDF: svg-inkscape
```
I think these files should be added to `.gitignore`?

**Comment by smiths** [comment]
@hrzhuang I agree about adding to the `.gitgnore` file, but we shouldn't make all the additions to the top-level `.gitignore`.  We will sometimes want to add "non-generated" bib files, pdf and xml files.  How about a `.gitignore` file in the `stable` folder to ignore these generated files, but not cause problems at higher levels in the folder hierarchy?

**Comment by smiths** [comment]
I think @hrzhuang is referring to the output of `git status`, rather than the output of `make`?

**Comment by hrzhuang** [comment]
Oh I think @balacij is right! This is not a `.gitignore` issue, this is an issue with the diffing of `build` and `stable`.
