### ISSUE TITLE
Loading Drasil Modules into GHCi

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3470]
Do we have a best practice for opening a GHCi instance with Drasil modules? I tried just running `stack ghci` in the `code` directory but I am getting the following error.
```
[ 97 of 401] Compiling Language.Drasil.Chunk.DifferentialModel ( /Users/hrz/Drasil/code/drasil-lang/lib/Language/Drasil/Chunk/DifferentialModel.hs, interpreted )
Module imports form a cycle:
        module ‘Language.Drasil.CodeExpr.Class’ (/Users/hrz/Drasil/code/drasil-lang/lib/Language/Drasil/CodeExpr/Class.hs)
        imports module ‘Language.Drasil.Chunk.CodeBase’ (/Users/hrz/Drasil/code/drasil-code/lib/Language/Drasil/Chunk/CodeBase.hs)
  which imports module ‘Language.Drasil’ (/Users/hrz/Drasil/code/drasil-lang/lib/Language/Drasil.hs)
  which imports module ‘Language.Drasil.CodeExpr.Class’ (/Users/hrz/Drasil/code/drasil-lang/lib/Language/Drasil/CodeExpr/Class.hs)
Failed, 97 modules loaded.

<no location info>: error:
    Could not load module ‘Data.Drasil.Citations’
    It is a member of the hidden package ‘drasil-data-0.1.13.0’.
    You can run ‘:set -package drasil-data’ to expose it.
    (Note: this unloads all the modules in the current scope.)
```

**Comment by JacquesCarette** [comment]
That's really weird: there should be no cycles.  Is this cycle in what is currently checked in, or just local to your machine?

**Comment by hrzhuang** [comment]
This is happening on what is currently checked into the `master` branch.

**Comment by smiths** [comment]
I don't have an explanation, but I have verified that I get the same error message as @hrzhuang from `stack ghci`.

**Comment by hrzhuang** [comment]
Yes, I have verified that this import cycle is indeed present in the code. One possibility I can think of is that there is some GHC extensions enabled via pragmas that somehow make this cycle okay when we run `make`. I know that GHCi ignores LANGUAGE pragmas in the source files (extensions need to be enabled via command-line arguments or using `:set` from within GHCi).

**Comment by JacquesCarette** [comment]
But this cycle is cross packages. I wonder if the problem might be that some unused file has not been deleted? `make` will only use the ones needed, but I think `ghci` will try to load everything. I'm also going to ping @balacij to see if he's got any ideas.

**Comment by hrzhuang** [comment]
Another observation is that if I run GHCi on just `drasil-lang` via `stack ghci drasil-lang` then it loads just fine and `Language.Drasil.Chunk.DifferentialModel` compiles with no errors.

**Comment by balacij** [comment]
Hmm, I don't think a cyclic dependency exists right now. The Haskell ecosystem don't seem to like multi-root projects in general, we might try revisiting this after #3395.

**Comment by balacij** [comment]
Yep, mine failed as well now. I'm not sure when this started happening, but I did notice the following warning during the `stack ghci` execution.

```console
* * * * * * * *

Warning: Multiple files use the same module name:
         * Language.Drasil.Chunk.CodeBase found at the following paths
           * /home/jasonbalaci/Programming/Drasil/code/drasil-code/lib/Language/Drasil/Chunk/CodeBase.hs (drasil-code:lib)
           * /home/jasonbalaci/Programming/Drasil/code/drasil-lang/lib/Language/Drasil/Chunk/CodeBase.hs (drasil-lang:lib)
* * * * * * * *
```

**Comment by balacij** [comment]
So, if we take a look at the starting import:

https://github.com/JacquesCarette/Drasil/blob/ad9a64f442cf76f2bd52534d9eff797a8f734564/code/drasil-lang/lib/Language/Drasil/CodeExpr/Class.hs#L7

The log says it is importing `X/lib/Language/Drasil/Chunk/CodeBase.hs`, but it says `X = drasil-code` (?!). I think this is where the problem comes in. The actual import is from `drasil-lang`, which is where the imports are defined:

https://github.com/JacquesCarette/Drasil/blob/ad9a64f442cf76f2bd52534d9eff797a8f734564/code/drasil-lang/lib/Language/Drasil/Chunk/CodeBase.hs#L22-L26

This file doesn't import `Language.Drasil`, but `drasil-code`s similarly named and located file does... do you think this is a bug in GHC, @JacquesCarette ? It seems to be importing the wrong file!

Also, if we:
```console
git checkout b73f49ff4a144322d1b1840d43a45b4ad64a074e
stack ghci
```
 Then everything works fine! That blob is the parent to 8dfd12037d09cbb44da16de7eb3773d6df908776 which is the latest change to these files.

**Comment by JacquesCarette** [comment]
Right, this might be a ghc weakness, but they might not call it a bug. I think having the exact same module name in two packages is *our* bug (we're just asking for trouble -- and found it).

The correct solution is to rename one of the two modules - I don't actually care which one.
