### ISSUE TITLE
Merge `NamedChunk` into `IdeaDict`

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3471]
Both are in `Language.Drasil.Chunk.NamedIdea`.

The constructors `nc` and `ncUID` should, in a first pass, be kept, but adapted.

**Comment by smiths** [comment]
To support this issue, and the [Chunk Investigation Project](https://github.com/JacquesCarette/Drasil/projects/10#card-89466875), we should link to a summary of yesterday's meeting.  @balacij could you write a quick summary of yesterday's (June 7, 2023) discussion?  The current issue is a step toward our eventual goal of replacing NamedChunk, IdeaDict, Concept, ConceptInstance etc with one (new) Concept.

**Comment by smiths** [comment]
Sounds good @balacij.  In the preamble to your explanation, I think we should mention that we are replacing `NamedChunk`, `IdeaDict`, `Concept`, `ConceptInstance` etc with one (new) Concept.  The reason for this is that the previous design was unnecessarily complex, difficult to explain and unintuitive.

**Comment by JacquesCarette** [comment]
I was going to say something similar: what you have above is the conclusion of our discussion, without the accompanying problem that it solves, nor the context in which the problem arose.

A big part of the lessons around Drasil is that it's often the in-context problem statement that contains the most valuable information; the conclusion is often "obvious" once the problem has been sufficiently well framed. (In this case, concept is interesting because there is actually some information in the solution itself.)

**Comment by balacij** [comment]
:smile: Ah, my bad, I overlooked this somehow.

I posted an [updated copy](https://github.com/JacquesCarette/Drasil/wiki/Attributes-and-Chunks:-Meeting-June-7th,-2023) on the wiki.
