### ISSUE TITLE
Dynamic vs static variables in GOOL

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3473]
What do we mean by dynamic vs static binding of a variable in GOOL?

**Comment by JacquesCarette** [comment]
Can you add more context? Unfortunately those terms are used in conflicting ways in different PL contexts, so I don't want to make things worse by giving the 'wrong' answer!

**Comment by hrzhuang** [comment]
Yes, the fact that "dynamic" and "static" can mean a lot of things is the source of my confusion. The GOOL paper says "it is common in OO programs to declare some variables as `static` to signify that the variable should be bound a compile-time." So is this about the scope/lifetime? The paper and the code both refer to "binding time" and "binding at compile-time" vs "binding at run-time" which I find a bit confusing.

**Comment by hrzhuang** [comment]
I think in Java `static` means the variable belongs to the class rather than an instance of the class. The equivalent of `const` in Java is `final`. So here `static` is about lifetime (a `static` variable lives for the duration of the program while a non-`static` variable lives for the lifetime of the instance holding it) and somewhat related to scope (a class has only one value for a `static` variable while each instance of the class can have a different value for a non-`static` variable).

I think in GOOL we mean "static" in the Java sense (based on the variable-related code in `drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs`, see below), but the use of the word "binding time" confuses me. Here are some snippets from the GOOL paper and code that might be relevant.

In `drasil-gool/lib/GOOL/Drasil/AST.hs`:
```haskell
-- Static means bound at compile-time, Dynamic at run-time, used in BindData 
-- and VarData
data Binding = Static | Dynamic
```

In section 4 of the GOOL paper:
> It is common in OO programs to declare some variables as `static` to signify that the variable should be bound at compile-time. The `Binding`, either `Static` or `Dynamic`, is thus part of a variable’s representation.

In `drasil-gool/lib/GOOL/Drasil/LanguageRenderer/Constructors.hs`:
```haskell
-- Variables --

-- | Constructs a dynamic variable in a stateful context
mkStateVar :: (RenderSym r) => String -> VSType r -> Doc -> SVariable r
mkStateVar = varFromData Dynamic

-- | Constructs a dynamic variable in a non-stateful context
mkVar :: (RenderSym r) => String -> r (Type r) -> Doc -> SVariable r
mkVar n t = varFromData Dynamic n (toState t)

-- | Constructs a static variable in a stateful context
mkStaticVar :: (RenderSym r) => String -> VSType r -> Doc -> SVariable r
mkStaticVar = varFromData Static
```

In `drasil-gool/lib/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs`:
```haskell
-- Variables --

var :: (RenderSym r) => Label -> VSType r -> SVariable r
var n t = mkStateVar n t (R.var n)

staticVar :: (RenderSym r) => Label -> VSType r -> SVariable r
staticVar n t = mkStaticVar n t (R.var n)

-- | To be used in classVar implementations. Throws an error if the variable is 
-- not static since classVar is for accessing static variables from a class
classVarCheckStatic :: (RenderSym r) => r (Variable r) -> r (Variable r)
classVarCheckStatic v = classVarCS (variableBind v)
  where classVarCS Dynamic = error
          "classVar can only be used to access static variables"
        classVarCS Static = v

objVar :: (RenderSym r) => SVariable r -> SVariable r -> SVariable r
objVar o' v' = do
  o <- o'
  v <- v'
  let objVar' Static = error 
        "Cannot access static variables through an object, use classVar instead"
      objVar' Dynamic = mkVar (variableName o `access` variableName v) 
        (variableType v) (R.objVar (RC.variable o) (RC.variable v))
  objVar' (variableBind v)

arrayElem :: (RenderSym r) => SValue r -> SVariable r -> SVariable r
arrayElem i' v' = do
  i <- i'
  v <- v'
  let vName = variableName v ++ "[" ++ render (RC.value i) ++ "]"
      vType = listInnerType $ return $ variableType v
      vRender = RC.variable v <> brackets (RC.value i)
  mkStateVar vName vType vRender
```

**Comment by JacquesCarette** [comment]
Oops, you're absolutely right, `static` in Java means "only once" which is implemented as being in the class rather than in instances. And yes, you can then interpret it as involving lifetime and scope.

Definitely the code in `LanguagePolymorphic` uses the notion *a la Java*. But I see why you're confused, because the description in `AST` is much closer to the meaning in Partial Evaluation! It is not wrong for its current usage, but definitely easy to misconstrue. I'm going to see if @bmaclach remembers any of this.

**Comment by bmaclach** [comment]
I'm confident that all of the code examples @hrzhuang references above mean `static` in the Java sense. I think it's also true that a `static` variable in Java is known or "bound" when the program compiles, whereas non-static variables are known/bound only at run time, which is why I called the type `Binding` and described them that way.
