### ISSUE TITLE
Implementing "Likely Changes" in SRS

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#349]
![image](https://user-images.githubusercontent.com/28247301/27974922-1b98b332-632e-11e7-8da0-a083344e0be4.png)
It seems that that `LCChunk`s are currently taking `[ModuleChunk]`s as an argument (for the likely changes listed in the module guides of the examples?); however, this doesn't make much sense for the likely changes listed in the SRS document...
@szymczdm Should we be treating the chunks differently depending on what document the likely changes are a part of? 
![image](https://user-images.githubusercontent.com/28247301/27975270-71f3b078-632f-11e7-91db-cea2837bfb5f.png)
(@AKM11 and I were discussing how perhaps we can send the likely chunks a list of `Assumption` chunks or a list of `Contents` to each likely chunk so that automatic referencing can be possible)
Noting this in an issue so the inquiry isn't forgotten...

**Comment by szymczdm** [comment]
The way LCChunks are currently implemented is not ideal. The use of related module chunks was strictly for design doc and code side of things (right @palmerst ?). 

We don't treat the chunks differently depending on the document, we need to ensure that the chunks contain all of the requisite information for **all** artifacts they will be used in.

You will likely need to modify how LCChunks are implemented (just make sure you fix whatever breaks) to capture the right knowledge.

**Comment by smiths** [comment]
@szymczdm , is there code that needs to be deleted to close this issue?

**Comment by szymczdm** [comment]
Likely changes have been overhauled as of the addition of Language.Drasil.Chunk.Change

As such I'd consider this issue resolved (should anything else come up, we'll create a new issue).
