### ISSUE TITLE
Add General System Description to Projectile

### ISSUE THREAD

**Issue by ManvendraJani** [JacquesCarette/Drasil#3495]
For Projectile, in the `Characteristics of Intended Reader` section, we reference the `User Characteristics` section.
![image](https://github.com/JacquesCarette/Drasil/assets/58832908/74988ba7-4efe-4000-ba0d-fe9985082ac9)
This should be removed (only for projectile) as we do not generate the User Characteristics section for projectile.

**Comment by smiths** [comment]
Another option would be to add the User Characteristics section.  I think the users will be fine to have high school level physics.  Based on my kids, I think we'd be good with Grade 9 highschool.

**Comment by ManvendraJani** [comment]
I was about to ask you in the PR 😅. But should we add the whole `General System Description` section?

**Comment by smiths** [comment]
Yes, I think we should have the `General System Description` section.  My position is that if we are following a template, we should have every section from the template.  If a section isn't relevant, then it can still be there, but with a note that it is not applicable to the project.
