### ISSUE TITLE
Create a better means of referencing (Remove RefHelpers hacks)

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#35]
Need to remove the hacks (inferName, firstLetter, repUnd) from RefHelpers and replace them with a better automatic referencing system.

Preferably something that will ensure unique identifiers for each of the TeX/HTML references.

**Comment by smiths** [comment]
Add figures and tables as chunks?

**Comment by niazim3** [comment]
Looks like `getDefName` is the only function that needs removing/updating for this issue: https://github.com/JacquesCarette/Drasil/blob/75d20770fd487633eaefb6e37a9e4aa1ec73fe6f/code/Language/Drasil/Reference.hs#L260-L267.

**Comment by JacquesCarette** [comment]
Right - the "words" `DD`, `IM`, `T` and `GD` should not be hard-coded here, but obtained from elsewhere. At least, that is the right fix.

However, it might be difficult to do this right now. I think first we need to deal with those 'FIXME'. Then various refactor(s) will be easier to achieve.

**Comment by szymczdm** [comment]
@JacquesCarette is correct. We need to remove the first two lines of getDefName (those relating to Data c and Theory c), then we can remove the rest of the function entirely.

Those two lines can be removed once @halonazhao's and @deviprasad135's branches have been merged in and we've ensured that we're no longer using the old Data and Theory constructors (they've been deprecated for a while now, but due to lack of hands on keyboards, they haven't been completely removed).

**Comment by niazim3** [comment]
Based on the comments in https://github.com/JacquesCarette/Drasil/commit/8ab27e764113aa23b49efb4ae79eb52ebd46bdcd, it seems that the `repUnd` hack can be removed by settling for camelCase as the reference addresses. The examples that do use `_`s are being updated in the addLabels branch to be camelCased. After that is merged into master, this issue can probably be closed.

**Comment by samm82** [comment]
Bumping @niazim3's question now that `addLabels` is merged.

**Comment by JacquesCarette** [comment]
I think the use of camelCase in orthogonal to this issue.  At least, I don't quite get how `repUnd` is related, especially as it seems that `Data` and `Theory` are gone. Is `getDefName` gone yet?

**Comment by samm82** [comment]
@szymczdm Unless you have your heart set on working on this, I'm going to re-assign this issue to myself. I noticed that `makeRef` can replace a lot of functions in the RefHelpers file.

**Comment by szymczdm** [comment]
@samm82 by all means go for it.

**Comment by samm82** [comment]
@JacquesCarette `getDefName` is still used, but the lines with the old `Data` and `Theory` types are gone.

**Comment by samm82** [comment]
Just an update. At this point, it looks like the entire RefHelpers file can be deleted; I'm just removing functions one-by-one right now.

**Comment by samm82** [comment]
None of this code is used - can it safely be removed? Other than this, I think I removed all the unnecessary functions from RefHelpers, but feel free to double check @szymczdm @JacquesCarette 

https://github.com/JacquesCarette/Drasil/blob/70fddc872cd6e7b05db46d21a03d853b388532db/code/drasil-docLang/Drasil/DocumentLanguage/RefHelpers.hs#L32-L55

**Comment by JacquesCarette** [comment]
Yes, if it isn't used, delete it.
