### ISSUE TITLE
Add "Generated by Drasil Version" text in all Drasil artifacts

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3501]
Currently, the `Makefiles` do not have a statement that indicates that these `Makefiles` were generated by Drasil. As mentioned in the opening comment in #3217 and in this comment [here](https://github.com/JacquesCarette/Drasil/pull/3499#pullrequestreview-1495551883), a comment should be added at the beginning of the `Makefiles` that indicates the `Makefiles` were generated by Drasil.

A suggestion by @smiths was to add the following line "Generated by Drasil Version" where Version represents the version number of Drasil.

Adding the Version number in this line would require the [stable to be updated every time there is an update to Drasil](https://github.com/JacquesCarette/Drasil/pull/3499#:~:text=The%20version%20number%20in%20particular%20seems%20helpful%2C%20although%20it%20will%20require%20a%20change%20to%20stable%20every%20time%20there%20is%20an%20update%20to%20Drasil.). 

What are your thoughts on this @JacquesCarette @balacij @samm82 ?

**Comment by smiths** [comment]
Great wording of the issue @harmanpreet-sagar.  I especially like that you explicitly sought feedback - I was just planning on adding something similar, but I see that you anticipated what I was thinking.  :smile:

I think we should also expand the conversation beyond Makefiles.  I think all generated files should include a line that says that are generated.  This would include our SRS, README files, code, etc.

I'm thinking the generated by "Drasil version X" line is analogous to how doxygen generated web-pages say they were generated by doxygen.

**Comment by samm82** [comment]
How concrete is our versioning of Drasil? I remember one summer we had to increment the version number of a package if we worked on it to force it to be recompiled, but I haven't been doing that and things still compile correctly (whether or not I should be is a different story! 😅). As far as I know, we only have one "official" version for Drasil as a whole: [v0.1-alpha](https://github.com/JacquesCarette/Drasil/releases/tag/v0.1-alpha). Depending on how significant a change is required to change the version number, stable might not have to be updated with every change, but this is a good thing to think about!

**Comment by smiths** [comment]
Great question @samm82.  I don't know the answer, but @balacij or @JacquesCarette will likely know.  I made the suggestion to @harmanpreet-sagar based on my implicit assumption that updates to the version number will be relatively slow.  Like you said, I don't really remember the last time we updated the number.  We also could list the version number as the major version number, if we were worried about frequent small changes.

**Comment by JacquesCarette** [comment]
@samm82 we used to have to do this (bump versions) because of vagaries of cabal. I think our upgraded setup and improved cabal/stack means we don't have to do that anymore.

Right now, we have a single official version of Drasil. We haven't been bumping it, as we have not made further releases.

In other words, this currently doesn't change often. So putting it into our generated files is not going to cause us much pain: only when we make an official release. So this seems like a safe feature to implement.

**Comment by balacij** [comment]
Ah, posted right before me. We can have version bumps in our `package.yaml` files. I'm not quite sure what we would mark as our Drasil package however for the actual files. It might be nice to refer to some of the metadata too (e.g., configuration knowledge), so perhaps we can move the versioning information to a metadata file?

**Comment by JacquesCarette** [comment]
Yes, versioning information should be in a metadata file.

**Comment by smiths** [comment]
@harmanpreet-sagar it looks like we agree that the version number should be in the generated files.  Please work with @balacij to figure out where to locate and how to format the metadata file.  You can then pull the information from that file for use with the generated files.

**Comment by harmanpreet-sagar** [comment]
The overall Drasil version is only currently present in the `CITATION.cff` file. I was wondering if it would be okay if I create a new file within the `drasil-metadata` package because the file currently within that package is `Domains.hs` where all the domain `IdeaDict`s are declared. I do not think that the Drasil version would be the right fit in that file.

**Comment by balacij** [comment]
I don't think we really have a good versioning scheme yet. I have no idea how it will work either, so using that version from the `CITATION.cff` file is probably a good idea to start. Creating a new file nearly anywhere is fine, so as long as you can justify. Did you have a specific solution in mind?

**Comment by balacij** [comment]
Ok, sounds good. Let's see how it goes. We can see how much it can evolve.

**Comment by harmanpreet-sagar** [comment]
Sounds good! I will continue on with that then.

**Comment by JacquesCarette** [comment]
Could we maybe not bury this information inside Haskell? Could we make it a plain text file (or a JSON file) instead? We may as well start some kind of "Drasil configuration file".

**Comment by harmanpreet-sagar** [comment]
Sure! I will try to do that now.

**Comment by harmanpreet-sagar** [comment]
@balacij I have created a `DrasilConfiguration.json` file which has the following data:

```json
{
  "Version": "v0.1-alpha"
}
```
I am trying to obtain this data in Haskell. However, that requires me to use the `IO ()` type to obtain this data. However, the places where this information is being used, cannot have `IO ()` as the type. Any suggestions on how I could potentially move forward with this?

**Comment by JacquesCarette** [comment]
You need to obtain this configuration data "very high up" in the running of the generator, and then pass it around.

Likely somewhere in `drasil-gen`.

**Comment by harmanpreet-sagar** [comment]
Ok, thank you! I will try to do that.
