### ISSUE TITLE
Drasil Research Group Meeting, Thursday, July 6, 2:00pm in ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3506]
NOTE the day of the week has been changed to Thursday

Decide at the start whether to record the meeting.

The agenda for this coming week is as follows:

1. Progress on [Chunk Investigation Project](https://github.com/JacquesCarette/Drasil/projects/10#card-89466875)
2. Progress on [Analysis of Space, Symbol and Unit](https://github.com/JacquesCarette/Drasil/projects/20)
3. Progress on GOOL changes, including GOOL CI (@hrzhuang)
4. Progress on test generation (@samm82)
5. Questions/Comments/Concerns/Discussion/Issues (please add after your name)
   a. @samm82
   b. @balacij 
   c. @hrzhuang: #3518
   d. @ManvendraJani: Discuss `progName` (https://github.com/JacquesCarette/Drasil/issues/3491)
   e. @harmanpreet-sagar: Design questions regarding #3515 
6. Summer research poster showcase (Thursday, August 17)
6. Open Discussion/Questions

Future Agenda items
- Overview of [BeamBend](https://github.com/balacij/Drasil/blob/bmBndngNoFunctions/People/Jason/CAS%20741/srs/build/srs.pdf) (@balacij) - should we have two representations (user-defined and abstract) for each variable? (We might not have time for this agenda item.)

Virtual attendees: @samm82

Regrets: @cd155

**Comment by samm82** [comment]
An appointment came up, so I likely won't be able to make this meeting anymore; I'll assume that I can't, but I'll do my best to make it (either virtually or in-person) if that ends up being possible!

**Comment by cd155** [comment]
Hi, I have an appointment today and can't make this one.

**Comment by samm82** [comment]
Update: I will be joining virtually from QuikChik!

**Comment by smiths** [comment]
The meeting started at 2:00 pm without the camera, because there were no virtual participants.  I just started the meeting on Teams for you @samm82.

**Comment by smiths** [comment]
We didn't really talk about the poster session, so I moved that item to the next agenda (#3527).
