### ISSUE TITLE
Disambiguate the UIDs of models from those of concepts

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3525]
Spun off of #3518. In the meeting (#3506) we decided that we should change the UIDs of models (i.e. data definitions, general definitions, instance models, and theory models) to be different from the UIDs of the underlying concepts. I think @JacquesCarette suggested that we prepend `theory:` to the UIDs of the models. Should we proceed with this change?

**Comment by balacij** [comment]
#2904 started with `ModelKinds`. I think that starting with `InstanceModel`s is a good idea, I think a lot of them now inherit their `UID` from the quantity they define a solution for.

**Comment by JacquesCarette** [comment]
Yes, we should, and indeed, implementation has started.
