### ISSUE TITLE
Case studies: should we add citations to the original versions?

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3526]
Since the Drasil-encoded case studies are based on manually created artifacts, I imagine we should, but I'm not sure how we feel about it.

For example, perhaps in the Introduction sections of each case study (for which this applies), we could add a small blurb noting that this is a recreation of the original, manually-created version in the https://github.com/smiths/caseStudies/tree/master/CaseStudies repo.

**Comment by smiths** [comment]
Yes, I like this idea.  I'm a big proponent that one can't really over cite.  It is an oversight to not over cite!  :smile:

Yes, in the introduction we should point to the previous manually created case studies, as appropriate.

**Comment by balacij** [comment]
Sorry for the delay!
