### ISSUE TITLE
Generate description of Examples using `purp` in `Body.hs` of all examples on Website.

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3532]
The description for most of the examples provided on the main Drasil website does not currently match the purposes specified for each of those examples in their `Body.hs` files. For example, the website's description for `GlassBR` reads: "predicts whether a given glass slab is likely to resist a specified blast." However, the purpose of `GlassBR` as evident below is slightly different from the description on the main website. 

https://github.com/JacquesCarette/Drasil/blob/1acb8ba1553d16d1c949e3b55049fb2242dfe555/code/drasil-example/glassbr/lib/Drasil/GlassBR/Body.hs#L126-L128

The text on the Drasil website for all the examples is currently obtained from these lines of code here:

https://github.com/JacquesCarette/Drasil/blob/1acb8ba1553d16d1c949e3b55049fb2242dfe555/code/drasil-website/lib/Drasil/Website/Example.hs#L158-L167

This is the case for all the various other examples as well. `PD Controller` currently does not have a description on the main website. The following image indicates the location on the website where the issue is prevalent. 

![image](https://github.com/JacquesCarette/Drasil/assets/110783820/5513e1bd-843b-4548-8816-733f63a35a7a)

The location of the code where this description is being generated is as follows:

https://github.com/JacquesCarette/Drasil/blob/1acb8ba1553d16d1c949e3b55049fb2242dfe555/code/drasil-website/lib/Drasil/Website/Example.hs#L59-L88

We should obtain the description for each of these examples using the `purp` that is specified in the body files for each of these examples in order to remove the duplicity of these sentences. 

In addition, text files that contain just one line for most of these descriptions are also present in the folder linked [here](https://github.com/JacquesCarette/Drasil/tree/1acb8ba1553d16d1c949e3b55049fb2242dfe555/code/drasil-website/WebInfo/descriptions). I am wondering as to why these text files exist?

What do you think @JacquesCarette @smiths @balacij @samm82?

**Comment by smiths** [comment]
@harmanpreet-sagar I agree that we should only record the purpose once and reuse it everywhere that we need it.  You have found an example where we aren't really doing things the right way.  We really should fix this.

With respect to the folder you linked, I have no idea why those files exist.  If they are important, we should generate them with the same purpose as we use everywhere else.

**Comment by samm82** [comment]
Are those text files actually being used? I would check this by changing one and seeing if any of the generated output changes. If not, they can probably be removed

**Comment by harmanpreet-sagar** [comment]
I just deleted the files and ran `make pr_ready`, then `make docs`, then `make website` and finally `make deploy_lite` and was unable to view any changes or errors as a result of deleting those files. From these tests, I believe that these files are not being used anywhere. Are there any additional methods or checks that I should perform in order to better confirm these?

**Comment by samm82** [comment]
Not that I know of 😅

**Comment by JacquesCarette** [comment]
1. Just delete those files!
2. Yes please (to implementing what is described in this issue)
