### ISSUE TITLE
Drasil Research Group Meeting, Thursday, July 27, 2:30pm in (ITB/225 ?)

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3558]
The agenda for this coming week is as follows:

1. Update from @hrzhuang.
2. Progress on [PhD research proposal](https://github.com/balacij/Doctorate/discussions/4) (problem statement) (@balacij)
3. Progress on test generation (@samm82):
   - #3259
   - project for requirement/test generation?
   - design for capturing choices that affect documentation and code
4. Progress on [Chunk Investigation Project](https://github.com/JacquesCarette/Drasil/projects/10#card-89466875) (@harmanpreet-sagar) ([latest update](https://github.com/JacquesCarette/Drasil/issues/3472#issuecomment-1638883175))
5. Progress on [Analysis of Space, Symbol and Unit](https://github.com/JacquesCarette/Drasil/projects/20) (@ManvendraJani)
6. Questions/Comments/Concerns/Discussion/Issues (please add after your name)
  a. @samm82
  b. @balacij 
  c. @hrzhuang
  d. @ManvendraJani
  e. @harmanpreet-sagar:
7. Open Discussion/Questions

Future Agenda items
- Overview of [BeamBend](https://github.com/balacij/Drasil/blob/bmBndngNoFunctions/People/Jason/CAS%20741/srs/build/srs.pdf) (@balacij) - should we have two representations (user-defined and abstract) for each variable? (We might not have time for this agenda item.)

Virtual attendees: @balacij, @cd155 

Regrets: @smiths

**Comment by smiths** [comment]
Unfortunately I'll be absent for this meeting.

**Comment by JacquesCarette** [comment]
Turns out I have to drive to Toronto airport at exactly this time on Tuesday, and I was going to write that I can't make the meeting... so instead I am moving it to Thursday. As I have a fairly full day on Thursday, I'll be remote.

**Comment by smiths** [comment]
Since this meeting concluded, I'll close this agenda item.
