### ISSUE TITLE
Implementing Discrete Sets

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#356]
In commit 5876e62, `DiscreteI`, `DiscreteD`, and `DiscreteS` were created. Upon implementation, however, the following error was showing up: 
![image](https://user-images.githubusercontent.com/28247301/28387995-30a356e0-6c9f-11e7-8f01-74e89ed9c5d9.png). In commit 90ed590, a `Discrete` space was created similar to the `Vect` space, however, the same error showed up with this implementation as well...

The reason new Spaces were being created is because 
> type Set = Space

from (Expr.hs), and the sets for **nominal thickness** and **glass type** (see screenshot below) are not currently represented or stored as discrete sets (but rather are stored as lists of Strings/Double and displayed as Sentences).

![image](https://user-images.githubusercontent.com/28247301/28387856-b0040930-6c9e-11e7-914e-4409a136deed.png)

@JacquesCarette @szymczdm 
If possible, can I get some clarification on what is the best way to implement such discrete sets in Drasil? Or are they already considered discrete sets from their current definition in the constraints of each `ConstrainedChunk`?
![image](https://user-images.githubusercontent.com/28247301/28389672-250ea090-6ca5-11e7-818c-63d0aecd5385.png)

**Comment by njericha** [comment]
We could change the definition of type `Set` to not be the same as `Space`. The reason this happened is because the code generation side doesn't have these types of sets implemented. We could do,
```
type Set where
  Spc :: Space -> Set
  Desc :: [Expr] -> Set
``` 
and trust that someone won't try and put a full equation in a set.

**Comment by JacquesCarette** [comment]
Hmm, the code that I saw checked-in seemed quite reasonable.  So something else must be going on that I am not quite getting.  The `Set` definition above is indeed a little too open for abuse.

I'll be around on Monday (and likely Tuesday) and can look at it then.

**Comment by niazim3** [comment]
If we could `import Language.Drasil.Space` into the Unitals file, (which is currently not possible because it is hidden), it would be possible to use the types 
```
  DiscreteI [Int]  --ex. let A = {1, 2, 4, 7}
  | DiscreteD [Double]
  | DiscreteS [String] --ex. let Meal = {"breakfast", "lunch", "dinner"}
```

**Comment by JacquesCarette** [comment]
`Drasil.hs` exports `Space(..)`, so all these discrete types should already be available.

**Comment by niazim3** [comment]
That's true, though attempting to make a change in the file to replace a `String` space with `DiscreteS [String]` resulted in the following error, so I will get back to this issue:
```
glassbr.EXE: defaultValue' undefined for type
CallStack (from HasCallStack):
  error, called at .\Language\Drasil\Code\Imperative\AST.hs:265:19 in drasil-0.0.9-EhO8nEtQjIEKb093SzEDf2:Language.Drasil.Code.Imperative.AST
make: *** [glassbr_build] Error 1
```
, where line 265 of that file is part of the definition of `defaultValue'`: 
```
defaultValue' :: StateType -> Value
defaultValue' (Base b) = defaultValue b
defaultValue' _ = error "defaultValue' undefined for type"
```

**Comment by JacquesCarette** [comment]
I think this is actually fixed. But I need to double-check.

**Comment by balacij** [comment]
@NoahCardoso , when you're finished with integrating `Set`s in Drasil, this will be a nice follow-up to your work. We currently have two `DiscreteXSet`-like types in our `Space` that need to be removed. While we do eventually want to have custom data type definitions (as @samm82 previously discussed), for now, we can at least your 'one-of'-constraint feature in progress to remove the `DiscreteX` types from `Space`.

**Comment by NoahCardoso** [comment]
Once `set`s are added to Drasil I can remove the `DiscreteX` types in space and add a set constraint to `glass_type`.
