### ISSUE TITLE
Problem with `make debug`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3560]
By default, `make` only produces one level of stack trace for an error, i.e. indicate where the `error` functions is called and nothing else. I would like to get to get a full stack trace to track down the root cause of the error, so I'm looking into `make debug`. However, it gives me the following error.
```
cd "build/glassbr" && stack exec -- "glassbr" +RTS -xc -P
glassbr: the flag -xc requires the program to be built with -prof
glassbr: the flag -P requires the program to be built with -prof
```
I am running this after a `make clean`, so the programs should be built with the compiler flags that are needed.

**Comment by JacquesCarette** [comment]
I don't think `make debug` should be relying on flags for profiling? There should be a `make profile` for that. Debugging and profiling are two different activities...

**Comment by JacquesCarette** [comment]
Ah, it's GHC's fault for conflating these things. Sigh.
