### ISSUE TITLE
PD Controller example is labelled as "PD_Controller" instead of "PDController" on website

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3565]
I noticed this before but waited in case #3521 fixed this. The PD Controller example is called exactly that, space included:

https://github.com/JacquesCarette/Drasil/blob/8d5e8f8088bb87cd351d07f4104faae7fd49111f/code/drasil-example/pdcontroller/lib/Drasil/PDController/Concepts.hs#L17

However, it seems that on the website, this space is replaced with an underscore instead of just being omitted:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/e98350f6-f6f6-4570-aa50-2db503d58c68)
A consequence of this is that the links generated are incorrect:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/35a77972-e051-4a69-a069-751c29953ccc)
Removing these underscores from the URL leads to the correct page:
![image](https://github.com/JacquesCarette/Drasil/assets/35857611/e8abe674-4052-4e7b-a212-7a87e3174c65)

Since this is the only example name with a space, I think there is likely a function that gets called at some point that replaces spaces with underscores, when they should just be omitted (at least in the use case of the website).

**Comment by smiths** [comment]
Good catch @samm82.  We should definitely fix this.

**Comment by JacquesCarette** [comment]
I think `pn` should give a hard error if the "proper noun" being given has some forbidden characters in it.

**Comment by balacij** [comment]
Off-topic: should the acronym for PD Controller instead be `PDC`? `PD Controller` seems to break continuity with the 'normal' acronym naming scheme.

**Comment by smiths** [comment]
I think we'll have a tough time coming up with consistent acronym rules.  The people in the field talk about PID controllers and PD controllers.  They don't say PDC.  In this case, it is more important that we follow the conventions of the community.

**Comment by balacij** [comment]
That makes sense. Thank you, @smiths!

Regarding the issue, the problem area is obvious enough, but a proper solution isn't quite clear. The problem has to do with `programName` usage. Hopefully I'll figure it out tomorrow.
