### ISSUE TITLE
Drasil Research Group Meeting, Tuesday,Aug. 1,  2:30pm in ITB/225

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3571]
The agenda for today is as follows:

1. Updates from everyone (it has been a while, and the PRs have slowed down)

Future Agenda items

 -   Overview of [BeamBend](https://github.com/balacij/Drasil/blob/bmBndngNoFunctions/People/Jason/CAS%20741/srs/build/srs.pdf) (@balacij) - should we have two representations (user-defined and abstract) for each variable? (We might not have time for this agenda item.)

Virtual attendees: @samm82 , @cd155

Regrets: @smiths

**Comment by cd155** [comment]
Hi, is there a meeting today?

**Comment by balacij** [comment]
Yes, we are in person. We will try to get it set up.

**Comment by smiths** [comment]
I feel like we can close this issue.
