### ISSUE TITLE
An `InstanceModel` should not have space, symbol, and unit

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3573]
Currently `InstanceModel` is an instance of `HasSpace`, `HasSymbol`, and `MayHaveUnit`. The space, symbol, and unit of an instance model is defined to be the space, symbol, and unit of the output variable of the instance model. We should really be explicitly getting the output variable then getting its space, symbol, and unit, as opposed to defining them to be the space, symbol, and unit of the instance model itself, which is incorrect.

## Sub-issues

* [x] #3631
* [x] #3632
* [x] #3633
* [x] #3634

**Comment by JacquesCarette** [comment]
Agreed.

**Comment by balacij** [comment]
Looks like this is done :smile:
