### ISSUE TITLE
Should `DataDefinition` be an instance of `HasOutput`?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3575]
Currently the only instance of `HasOutput` (that I can see on Haddock) is `InstanceModel`. I think the left-hand side of a `DataDefinition` could also be considered the output of the `DataDefinition`.

An example for how this would be useful is as follows.

Currently, the function `mkQRTuple` is applied to both `DataDefinition`s and `InstanceModel`s.
```haskell
mkQRTuple :: (Quantity i, MayHaveUnit i, HasShortName i, Referable i) => [i] -> [(QuantityDict, Sentence)]
mkQRTuple = map (\c -> (qw c, refS c))
```
But if we go ahead with #3573 and #3574, then there would no longer be a uniform way to access the space, symbol, and unit of the output variable (i.e. left-hand side) of `DataDefinition`s and `InstanceModel`s.

`DataDefinition` being an instance of `HasOutput` allows us to bring this back, by redefining `mkQRTuple` as follows.
```haskell
mkQRTuple :: (HasUID i, HasRefAddress i, HasShortName i, HasOutput i) => [i] -> [(QuantityDict, Sentence)]
mkQRTuple = map (\c -> (c ^. output, refS c))
```

**Comment by JacquesCarette** [comment]
Agreed!

**Comment by samm82** [comment]
What does it mean for a chunk to have an output? Just confirming that it means that there is a value calculated by the model but **NOT** actually outputted by the system (if the latter was the case, then the work on #3569 seems redundant).

**Comment by JacquesCarette** [comment]
`HasX` always means the same thing: there is a X that makes sense to us, and whatever information is associated to X, the methods of `HasX` will retrieve it.

So `HasOutput` should be associated to any piece of data which encapsulates an 'Output' concept.

Yes, implicitly `HasOutput` should only happen for things that somehow computes a value.

**Comment by smiths** [comment]
I'm fine with changes that make data definitions more like instance models.  I don't think we should make the change, but most of the data definitions really are like "instance models".  Actually, in our latest terminology, most of the data definitions and the instance models are examples of theories.  We might have a data definition that is like a definition, but most of them are theories.  The original distinction between data definitions and instance models was that instance models were refined from something else, and data definitions were just given.  In our new terminology the data definitions would be initial (or maybe background?) theories.

As the edits by @samm82 to GlassBR show, "promoting" data definitions to instance models doesn't cause any problems.  

I really do think things will be more consistent and easier to explain when everything is viewed as a theory.

**Comment by hrzhuang** [comment]
Should `DataDefinition` have output constraints? I think my first step is to have the output constraints of `DataDefinition`s to just be the empty list, but we could add a field for output constraints into `DataDefinition` as another issue.

**Comment by smiths** [comment]
The data definitions don't currently display output constraints, so we don't have to have them as we refactor the implementation.  In the future we could add constraints, since I think eventually the data definitions will be treated the same way as the instance models.  (That is, both data definitions and instance models will be treated as theories.)  The one difference could be that input constraints on the instance models might include software constraints, but the data definitions would only have physical constraints.  The reason for this is that the instance models are what we'll eventually call the final theories.   They are the theories that are closest to code.

**Comment by samm82** [comment]
Since DDs don't have outputs constraints (yet), would it be too involved to make the output constraint field a `Maybe` type to differentiate between an IM with no constraints (`Just []`) and all DDs that don't have constraints implemented/displayed (`Nothing`)?

**Comment by JacquesCarette** [comment]
This feels like over-complicating things - `[]` for no constraints seems fine to me for both kinds.
