### ISSUE TITLE
No spacing between IM tables in HTML SRS

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3576]
See image below, which is from the GlassBR SRS in `stable`.

<img width="971" alt="Screenshot 2023-08-02 at 10 59 23 AM" src="https://github.com/JacquesCarette/Drasil/assets/3335167/e7d3866a-9d13-4dd0-9833-26f680c1cd68">

Has it always been this way? Or should there be spacing between the "RefBy" row and the "RefName" row of the next instance model?

**Comment by samm82** [comment]
I noticed that too, just haven't gotten around to making an issue for it 😅 I think there should be a space as well, to make it more obvious where one table ends and the next begins
