### ISSUE TITLE
Does `HasOutput` have to use lenses?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3577]
Currently the methods `output` and `output_constraints` of `HasOutput` are lenses.
```haskell
class HasOutput c where
  output :: Lens' c QuantityDict
  out_constraints :: Lens' c [RealInterval Expr Expr]
```
Is there any reason for this? Or can we make them simple functions as follows?
```haskell
class HasOutput c where
  output :: c -> QuantityDict
  out_constraints :: c -> [RealInterval Expr Expr]
```

**Comment by JacquesCarette** [comment]
No reason. They could be simple functions.

In fact, I'm not sure we use `set` (or any of its variants) anywhere right now. So maybe we could switch most methods to plain functions at no real loss of functionality.
