### ISSUE TITLE
Empty paragraph produced when data definition has no derivation

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3580]
In investigating #3576, I found that in the HTML SRS for GlassBR, there is spacing between data definition tables but not between instance model tables. As it turns out, the spacing between DD tables is put in on accident! It results from an empty paragraph inserted after each DD table, which is supposed to be the derivation of the DD but it is an empty paragraph when the DD has no derivation.

I think ideally we should really be outputting nothing as opposed to an empty paragraph when a DD has no derivation, and in this case the result actually looks different visually.

The most relevant piece of code is as follows.
```haskell
-- | Create a derivation from a chunk's attributes. This follows the TM, DD, GD,
-- or IM definition automatically (called automatically by 'SCSSub' program).
derivation :: (HasDerivation c, HasShortName c, Referable c) => c -> Contents
derivation c = maybe (mkParagraph EmptyS)
  (\(Derivation h d) -> LlC $ llcc (ref c) $ DerivBlock h $ map makeDerivCons d) $ c ^. derivations
```

**Comment by JacquesCarette** [comment]
Agreed.
