### ISSUE TITLE
`HasDerivation` should be called `MayHaveDerivation`

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3581]
The class `HasDerivation` actually only gives you a `Maybe Derivation`.
```haskell
class HasDerivation c where
  derivations :: Lens' c (Maybe Derivation)
```

**Comment by JacquesCarette** [comment]
Good remark. This would be an easy thing to just knock off and get a sense of accomplishment!

**Comment by daijingz** [comment]
After using the grep command, I see these occurrences:
![U~ Z(FQ_JUUAX@H71SSX4CA](https://github.com/JacquesCarette/Drasil/assets/61481741/c04a5a2c-8da8-4d8a-ad7b-5d3d7df09c6e)
I am going to change these in the next step

**Comment by daijingz** [comment]
After changing all these places, there is no obvious errors
Here is the output:
![1QE2I5WWVT( L3825CT$EV](https://github.com/JacquesCarette/Drasil/assets/61481741/e3d59b1f-34b8-47f8-b23e-185961a8f23b)
I am going to build a new request soon
