### ISSUE TITLE
PD Controller SRS link on website leads to 404

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3585]
On the main [Drasil website](https://jacquescarette.github.io/Drasil/), the link to the PD Controller SRS is broken.

The link: https://jacquescarette.github.io/Drasil/examples/pd_controller/SRS/srs/PD_Controller_SRS.html

**Comment by samm82** [comment]
Dupe of #3565 😉

**Comment by balacij** [comment]
Whoops! Thank you @samm82 :smile:
