### ISSUE TITLE
Lack of spacing between instance model tables in GlassBR PDF SRS

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3586]
At a glance, this seems related to #3576, but as I will demonstrate I think this is a separate issue.

Since the instance models are so large, the two instance models in GlassBR are placed on separate pages, so this issue is not actually visible in the normally generated PDF. However, if I were to edit the `.tex` file and remove some of the rows from the tables, it becomes apparent.

<img width="905" alt="Screenshot 2023-08-03 at 1 14 04 PM" src="https://github.com/JacquesCarette/Drasil/assets/3335167/fdcd36b7-72ef-487d-ae17-4a442fcffaca">

This may not look terrible, but unlike in HTML (see #3576), in $\LaTeX$ we actually do ask for space between the two tables via the command `\vspace{\baselineskip}`, and that is way less space than we ask for! (`\baselineskip` is the distance between two lines of text in a normal paragraph)

The reason this happens is that `\vspace` needs to be followed by a newline, otherwise the table that follows gets placed on the same "line" as the `\vspace`. This is illustrated in the diagram below.

![vspace](https://github.com/JacquesCarette/Drasil/assets/3335167/346f3e73-6d6c-4c1a-9aac-1b0d33961a00)

**Comment by JacquesCarette** [comment]
Do we put in raw tables in our latex? I think if we put them in figures, latex will automatically add some space.

[Your reasoning above is sound, but it always feels like adding explicit spacing in latex is "wrong", which is why I'm continuing to explore.]

**Comment by hrzhuang** [comment]
Are we okay with the tables for GDs, DDs, IMs, and TMs being floats? It might be strange for the a DD table to be displayed in the IM section.

**Comment by JacquesCarette** [comment]
It's bad latex style to have large tables be forced to be inline.

Having said that, one could claim that we're abusing tables for layout of GDs, etc, so that they really shouldn't be in figures (unlike other items, which should be).

So... probably best not to float these.  Reading around, maybe using `\par` instead of `\vspace` would end up doing the equivalent but let latex futz around if it wants?

**Comment by hrzhuang** [comment]
I tried replacing the `\vspace` with a `\par`, but `\par` doesn't actually put in any spacing. According to [this StackExchange answer](https://tex.stackexchange.com/a/82666), `\par` is equivalent to a blank line. So I think the blank line I add with #3587 already provides $\TeX$ the leeway to put in more space, the specified `\vspace` is just the minimum space.

**Comment by JacquesCarette** [comment]
Not quite 'complete' yet.
