### ISSUE TITLE
Can we move `HasInputs` and `HasOutput` to `drasil-lang`?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3591]
In order to implement `HasOutput` for `DataDefinition` (see #3575), it needs to be implemented for the underlying `QDefinition` so that we can get the output variable out of the `QDefinition`. The issue is that `QDefinition` is in `drasil-lang` and `HasOutput` is in `drasil-theory`, and I don't think we want `drasil-lang` to depend on `drasil-theory`. Since `Theory.Drasil.Classes` (which contains `HasInputs` and `HasOutput`) only imports `Language.Drasil` and seems to apply to more than just theories, can we move it to the `drasil-lang` package?

**Comment by JacquesCarette** [comment]
Is there an existing method (implemented by `QDefinition`) that gets the output variable?

**Comment by hrzhuang** [comment]
I don't think so. The internals of `QDefinition` are not exported outside of `Language.Drasil.Chunk.Eq`, and no typeclass instance or exported function in this module provides this functionality.

I think the current way we achieve this is by implementing `HasSpace`, `HasSymbol`, etc. on the `QDefinition`, where the symbol of a `QDefinition` is defined to be the symbol of its output variable. This then makes a `QDefinition` a `Quantity` and allows us to use `qw` to get a `QuantityDict` representing the output variable. I think this approach is abusing the notion of `Quantity` though, because a `QDefinition` really isn't a quantity, it's a definition of a quantity.

**Comment by JacquesCarette** [comment]
I'm reluctant to move `HasInputs` and `HasOutput` to `drasil-lang`. I would almost be more inclined to move `QDefinition` to `drasil-theory`! (I don't think I'm seriously suggesting it for right now).

I'm wondering if there should be some kind of intermediate concept that `QDefinition` could implement that would be reasonable to have in `drasil-lang`.

**Comment by hrzhuang** [comment]
Is your reservation coming from bringing constraints into `drasil-lang` world? Perhaps we could split off `out_constraints` into its own typeclass?

**Comment by hrzhuang** [comment]
Resolved with #3601.
