### ISSUE TITLE
Should `Data.Drasil.Domains` be moved out of `drasil-metadata`?

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3592]
Currently, `Data.Drasil.Domains` sits in `drasil-metadata`, however, it does not have the traditional metadata stored within it. Should it be moved to `drasil-data` or into any other directory? 

@JacquesCarette @smiths @balacij @samm82 What do you think?

**Comment by JacquesCarette** [comment]
What is defined in `Data.Drasil.Domains`?

**Comment by harmanpreet-sagar** [comment]
Currently, `Data.Drasil.Domains` contains the definitions of various domains such as `compScience`, `softEng`, `mathematics`, etc.

The details of the file are as follows:

https://github.com/JacquesCarette/Drasil/blob/00961248c3ef90e5c70bdf87f1a33cc216e60e20/code/drasil-metadata/lib/Data/Drasil/Domains.hs#L6-L29

**Comment by JacquesCarette** [comment]
So this really isn't Drasil metadata at all. These ought to be in drasil-data.

Now, there might have been a reason they were put (likely: moved) to metadata. Let's reconstruct that by trying to move them! It's likely going to cause problems with dependencies, which is going to tell us what the real problem is.

**Comment by harmanpreet-sagar** [comment]
Ok, I will move them to `drasil-data` and see what will break.

**Comment by harmanpreet-sagar** [comment]
If we were to move `Data.Drasil.Domains` to `drasil-data`, then a cyclic dependency is created between it and `drasil-theory` as `drasil-theory` consists of all the various types of definitions and models such as `DataDefinition`, `GenDefn`, `InstanceModel`, and `TheoryModel`.

We could consider moving `Data.Drasil.Domains` to `drasil-lang`, where it was originally moved from. 

Also, since I am currently working on a branch based on master, the program will fail to compile unless either the `drasil-metadata` package is fully removed or has at least one file inside it that is exposed. Hence, in order to resolve this without removing the `drasil-metadata` package, we will need #3566 merged into the master.

**Comment by JacquesCarette** [comment]
You know what, let's leave things as is. In some ways, it is meta-data for Drasil's current way of doing theories in `drasil-theory`. So at least the pieces of `Data.Drasil.Domains` needed in `drasil-theory` should stay there.

**Comment by harmanpreet-sagar** [comment]
Ok, sounds good!
