### ISSUE TITLE
Add a stable for the main Drasil Website and change the manner in which `make deploy_lite` runs

### ISSUE THREAD

**Issue by harmanpreet-sagar** [JacquesCarette/Drasil#3598]
The main Drasil website is currently generated by Drasil, however, it is not part of stable. Based on what was discussed, the best way to move forward on this would be to create a new stable folder specifically for the website. This would also allow us to change the way `make deploy_lite` works as we could use this issue to modify the conditions of the makefile to use artifacts currently present in stable to aid in the deployment of the main Drasil website.

What do you think? @smiths @JacquesCarette @balacij @samm82

**Comment by smiths** [comment]
Sounds good to me.

**Comment by JacquesCarette** [comment]
As we discussed in the meeting: yes, but not "merged" with the current stable. We should have a little bit of separate between our different use cases.
