### ISSUE TITLE
Assessment of acroTest Implementation

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#360]
I have been working on a new version of referencing that would create a better hyperlink for html. However, I wanted some input/suggestions on what I was implementing and how I was implementing it.  In particular, I am concerned by two functions:

I) acroNumGen: This function takes an ordered list of contents and applies the correct enumerated abbreviation (e.g. LC1, LC2, LC3) to each item.  At the moment, the major concern for this function is the need to unwrap a sentence to create an abbreviation.
![image](https://user-images.githubusercontent.com/28261578/28433260-f14a3cf6-6d58-11e7-84e4-6ed99016fd65.png)

II) acroTest: This function creates a more accurate hyperlink for references e.g.:
![image](https://user-images.githubusercontent.com/28261578/28434110-3898a93c-6d5c-11e7-8ed3-b953175ebcdc.png)
However, I dislike the fact that two variables need to be passed (the content to be referenced and the 'enumerated' list of the contents) in order to make one reference. For instance `acroTest req1 s5_1_list_words_num`. Unfortunately, I am having difficulty thinking of a solution that does not involve two variables.

![image](https://user-images.githubusercontent.com/28261578/28433825-1a169bc8-6d5b-11e7-9eac-122d57c9f1e5.png)

I have already altered the involved instances and types so that the code operates with the regular `makeRef` and the experimental `acroTest` so everything should run fine.  Most of these changes can be seen in commit dbfa8b990d32f1867899016587331b3bda6d7650.

**Comment by AKM11** [comment]
@smiths suggested that this was more of a question for you @szymczdm.
Note to Self: There was a suggestion that we use the name of the data type as opposed to its number in the document (e.g. A:heatCap vs A1)  which would be easier to implement and is apparently preferred.

**Comment by smiths** [comment]
@AKM11 , for the record, my preference is to have both numbers and short names as options.  In many contexts the short name is better, since it holds self-documenting information.  However, in some cases the relatively larger short names are still too big.  For instance, in a table, the numbers are easier to use.

If we are prioritizing, right now, I would pick shortnames as references over numbers.

**Comment by smiths** [comment]
For an example that uses short names (called labels in the document), please have a look at:

http://www.cas.mcmaster.ca/cas/0reports/CAS-17-01-SS.pdf

This requirements document (for a family of material models), uses both numbers and labels for the data definitions, assumptions, theoretical models etc.

**Comment by AKM11** [comment]
@smiths Is there a preferred way of passing said label to the text generator (i.e. should we use the id, the abbreviation or create an entirely new field to create the label)

**Comment by smiths** [comment]
@AKM11 , I do not know the preferred method of passing the label.  That question is better for @szymczdm .  Ideally, yes I would like to have the option of numbers and labels available at the same time.

**Comment by JacquesCarette** [comment]
We should never allow the id to be used directly.  The abbreviation is a much better choice; however it might make sense to create a notion of a 'label' that could be attached to certain chunks.

**Comment by AKM11** [comment]
Alright then, I will see what I can do.  Sounds like we will have to add a "Label" component to each of the contents types (or their chunks) to fulfill all these requirements.

**Comment by szymczdm** [comment]
Since acroTest and acroNumGen are being removed at this stage, I'm going to close this issue. It was a good workaround while we needed it.

**Comment by JacquesCarette** [comment]
I'm a little reluctant to close this until `acroNumGen` is **actually** removed. Then it can be closed. I'm happy for this issue to continue to be an irritant until that is the case.

**Comment by JacquesCarette** [comment]
Note that you can start to assign removing `acroNumGen` to various people.

**Comment by samm82** [comment]
@JacquesCarette Waiting on #312 - since @elwazana is pretty much done now, either @niazim3 or myself could take over if it is a high enough priority.

**Comment by JacquesCarette** [comment]
Yes, please do. #312 is one part of a giant puzzle relying on referencing. Getting it closed will indeed lead to a number of other issues also being closed.
