### ISSUE TITLE
Drasil Research Group Meeting, Tuesday, Aug 15, 10:30 am in (ITB/201) [Note the time change and room change]

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3602]
1. Overview of [BeamBend](https://github.com/balacij/Drasil/blob/bmBndngNoFunctions/People/Jason/CAS%20741/srs/build/srs.pdf) (@balacij) - should we have two representations (user-defined and abstract) for each variable?
2. Update from @harmanpreet-sagar - close PR, close issues, website in a stable folder
3. Update from @hrzhuang - conflicting uids
4. Update from @ManvendraJani - close PRs, space/unit/symbol
5. Update from @samm82
6. Questions/Comments/Concerns/Discussion/Issues (please add after your name)
  a. @samm82
  b. @balacij 
  c. @hrzhuang
  d. @ManvendraJani
  e. @harmanpreet-sagar: #3566, #3622 
7. Relinquish our room booking for ITB/225?
8. Open Discussion/Questions

Virtual attendees: @cd155, @harmanpreet-sagar, @balacij 

Regrets: @samm82

**Comment by smiths** [comment]
The meeting room has been changed to ITB/201.

**Comment by balacij** [comment]
Hi all, it looks like I'm going to need to join remotely, if that's alright. We can delay my presentation to the following week if needed, otherwise, I can present remotely.

**Comment by smiths** [comment]
Let's proceed with the presentation, even though it has to be remote.  I think we've put it off long enough.  :smile:  If we wait, then @harmanpreet-sagar, @hrzhuang and @ManvendraJani will miss out.  :smile:

**Comment by samm82** [comment]
Because I'll be getting ready to leave for my wisdom tooth removal, I don't think I'll be able to make it to this meeting 😕 if this will be the last time we meet with the summer students, it has been a pleasure working with you guys and seeing what you can do! Thanks for helping with Drasil! 😁❤

**Comment by smiths** [comment]
Good luck with your teeth @samm82.  I wish you a speedy recovery!

**Comment by smiths** [comment]
This was the final meeting in the Drasil summer meetings series.  For @balacij and @samm82, we won't be scheduling a group meeting again until September.  Of course if we need ad hoc meetings in the mean time we will schedule those as they arise.

**Comment by smiths** [comment]
@cd155 no we aren't meeting next week on Tuesday.  We actually aren't planning a meeting at all for next week.  The Drasil meetings will take a brief hiatus from now until September.  @JacquesCarette and I will need to look at our teaching schedule and our other meetings.  We'll also need to coordinate with other group members schedules and not everyone will know their schedule yet.  The short version is that we don't currently know when the next Drasil meeting will take place.  :smile:
