### ISSUE TITLE
Can `DataDefinition` and `InstanceModel` implement `DefinesQuantity`?

### ISSUE THREAD

**Issue by hrzhuang** [JacquesCarette/Drasil#3621]
This is motivated by the `definedIn` family of functions.

```haskell
-- | Takes a 'HasSymbol' that is also 'Referable' and outputs as a 'Sentence': "@symbol@ is defined in @reference@."
definedIn :: (Referable r, HasShortName r, HasSymbol r) => r -> Sentence
definedIn q = ch q `S.is` S "defined in" +:+. refS q

-- | Same as 'definedIn', but allows for additional information to be appended to the 'Sentence'.
definedIn' :: (Referable r, HasShortName r, HasSymbol r) => r -> Sentence -> Sentence
definedIn' q info = ch q `S.is` S "defined" `S.in_` refS q +:+. info
```

Correct me if I'm wrong, but as far as I can see `InstanceModel` and `DataDefinition` are the only types that satisfy both `Referable` and `HasSymbol`. So those are currently the only possible arguments to the `definedIn` functions. As part of #3573 and #3617 (part of #3574), I would like to replace `HasSymbol` with `HasOutput` in the type signatures of the `definedIn` functions.

However, `HasOutput` is in `drasil-theory` and the `definedIn` functions are in `drasil-lang`, and we don't want `drasil-lang` to depend on `drasil-theory` (see also #3591 and #3597). Would it be appropriate then to implement `DefinesQuantity` for `InstanceModel` and `DataDefinition` so we can use it in the `definedIn` functions as follows?

```haskell
definedIn :: (Referable r, HasShortName r, DefinesQuantity r) => r -> Sentence
definedIn q = ch (q ^. defLhs) `S.is` S "defined in" +:+. refS q

definedIn' :: (Referable r, HasShortName r, DefinesQuantity r) => r -> Sentence -> Sentence
definedIn' q info = ch (q ^. defLhs) `S.is` S "defined" `S.in_` refS q +:+. info
```

**Comment by JacquesCarette** [comment]
`definedIn` does not need to be defined in `drasil-lang`. Things that output `Sentence` in that way really should be elsewhere.

We don't want to change things based on just where they are being used right now (i.e. that only `InstanceModel` and `DataDefinition` currently satisfy the constraints). We want to have the "most meaningful constraints".

Having said that: using `DefinesQuantity` sounds like a better high-level constraint that the low-level `HasSymbol`.

**Comment by hrzhuang** [comment]
I see. I will move the `definedIn` functions to `drasil-docLang` then?
