### ISSUE TITLE
Website links to the HTML versions of our examples are broken

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#3646]
While the URLs seems to be correct, the HTML file can't be found - was there a change to how we deploy the website that may have broken this?

![image](https://github.com/JacquesCarette/Drasil/assets/35857611/d4d6f8fb-b759-42e4-903c-2aa8ab9163af)

**Comment by balacij** [comment]
This might be caused by a hastily merged PR #3603. I'll try to have a look.
