### ISSUE TITLE
Doxygen warns about “bad” comments: `\Generated`

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3660]
#3566 introduced small “Generated by Drasil...” watermarks to each file's Doxygen comments. The watermarks appear as Doxygen annotations `\Generated by Drasil ...`. Unfortunately, `\Generated` is not a [valid annotation](https://www.doxygen.nl/manual/commands.html#cmdnote) for Doxygen, and so `make doxygen` throws a bunch of extra warnings. I think we should change it to `\note Generated ...`.

**Comment by smiths** [comment]
Yes, I agree with this proposed change.  Nice to have another newcomer issue identified too.  :smile:  Maybe @daijingz will be interested?

**Comment by daijingz** [comment]
> Yes, I agree with this proposed change. Nice to have another newcomer issue identified too. 😄 Maybe @daijingz will be interested?

Let me work on it, because of lots of things, I just arrive today.

**Comment by daijingz** [comment]
This issue I use a month not because I feel hard to do because I spend a lot of time reviewing Doxygen. Now you can see my pull request.

**Comment by daijingz** [comment]
Write it there. At first, let me find how many project folders have `\Generated` problem

After using the command `grep "Generated" -r * --include "*.*"`, I found these 5 segmental projects need to be contributed:
`dblpend`, `glassbr`, `pdcontroller`, `projectile`, `swhsnopcm`
