### ISSUE TITLE
Drasil Research Group Meeting, Thursday, Sept 21, 1:00 pm in (TBA) 

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3661]
1. Update from @balacij 
2. Update from @samm82
  a. What to do with DblPend's outputs (https://github.com/JacquesCarette/Drasil/issues/3533, blocking #3259) 
  b. Design variabilities to capture when generating testing

Regrets:

Virtual: @smiths, @samm82

**Comment by smiths** [comment]
I'll be attending the meeting virtually tomorrow.  I've changed the location to TBA.

**Comment by samm82** [comment]
What is the plan going forward @smiths? Is this our new weekly meeting time? Are larger group meetings on a case-by-case basis depending on when it would be useful?

**Comment by smiths** [comment]
@samm82 we don't currently have a plan.  We have temporarily replaced the Drasil meeting with separate meetings with you and Jason.  We have a new student starting this week.  My guess is that we will reboot the meetings after @JacquesCarette returns from Dagsthul.
