### ISSUE TITLE
Escape special characters in each various generated format (HTML, TeX, etc)

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3669]
See the below image. Currently we restrict ourselves to a particular character set when generating final documents. We should figure out what the character sets are and how we should escape the special characters so that we can allow users to write whatever they want, and have the innerworkings 'fix' it as necessary. For example, "C Sharp" is one particular example where we write "C Sharp" instead of "C #" to dance around generating a `#`, which would cause problems for generated TeX code. To fix this particular example, we would only need to prepend a `\` in front of the `#`. Conversely, in HTML, this should be written with `&num;` -- &num;

![image](https://github.com/JacquesCarette/Drasil/assets/1627302/f929f6d9-a360-4dc0-8d88-c64d4b431f41)

**Comment by smiths** [comment]
This is a nice issue @balacij.  It is a real problem and frustrating, but once we teach Drasil about the various formats, we shouldn't have to think about problems with special characters.

**Comment by balacij** [comment]
That sounds good to me. Let's just hold off until then :smile:
