### ISSUE TITLE
Drasil Research Group Meeting, Monday, Feb 5, 4:30 pm, ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3688]
1. Summer student plans
2. Strategy?
3. Context?
4. Context theories (@smiths)
5. Rationale
  - attached to every scope decision, modelling decision, assumption and data constraint
  - required for overriding and assumption
  - rationales can be overridden
  - generic theories will likely have generic rationales
  - provide a rationale for a sequence of theories, like the generic theories in projectile
  - a rationale for a sequence of sequences of theories?
  - is derivation of a theory also a rationale?

6. Simple infrastructure work to prepare for changes, as mentioned in #3672.
7. Speculation on fields of a theory (@balacij) -- likely postpone to a future meeting
8. ?

Regrets:

Virtual:

**Comment by smiths** [comment]
If we schedule the next meeting for Monday, Feb 5 at 3:00 pm, @smiths will not be able to make it because of capstone Rev 0 demos from 2:30 pm to 4:30 pm.  @samm82 might have the same constraint (I haven't actually checked his TA schedule).  @JacquesCarette is it an option to meet at 4:30 pm on Feb 5, possibly shifting your Finally Tagless meeting to start at 3:00 pm?

**Comment by JacquesCarette** [comment]
Yes.

**Comment by smiths** [comment]
Our meeting next Monday (Feb 5) will take place in ITB/225.

**Comment by samm82** [comment]
I think we can close this issue; is there any follow up we needed to do?

**Comment by smiths** [comment]
We should schedule our next Drasil group meeting.  February 19 won't work because it is a holiday (Family Day).  @JacquesCarette is there a day during Reading Week when you know you will be on campus?  If your plans are still up in the air, we can wait before deciding.

**Comment by samm82** [comment]
The only timeframe where I could be on campus would be earlier on Friday (morning or potentially early afternoon) 😅 I'm also happy to join virtually to give more flexibility

**Comment by JacquesCarette** [comment]
I'll be on campus both Tuesday and Thursday of reading week.

**Comment by smiths** [comment]
How about 11:00 am on Tuesday, Feb 20 for the next Drasil meeting?

**Comment by JacquesCarette** [comment]
In my calendar now.

**Comment by smiths** [comment]
I've created an issue (#3690) for our next meeting.  The agenda isn't yet clear.
