### ISSUE TITLE
Drasil Research Group Meeting, Monday, Mar 18, 3:00 pm, ITB/111

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3701]
1. [Little theories version of Projectile](https://github.com/smiths/caseStudies/blob/master/CaseStudies/projectile/projectileSRS_RefinedTheories/RefiningTheories/ProjectileLittleTheories.pdf).
2. 'Theories': Shift association with IM/DD/TM/GD terms to 'printing' level #3691
3. Add more static analysis to our Haskell tool chain? #3700

Regrets: ?

Virtual: @balacij

**Comment by smiths** [comment]
We are booked into ITB/111 for our meeting on Monday.

**Comment by JacquesCarette** [comment]
I may be a bit late if the GCPC meeting goes extra-long. Unlikely, but possible.

**Comment by smiths** [comment]
Thanks @samm82.

Part of the summary about the little theories version of projectile is captured above.  @JacquesCarette presented how it might look in Agda.  Agda is a source of inspiration for us.  It doesn't facilitate capturing the documentation data (text), but it works really nicely with theories.

We skipped agenda item 2.  I'll add it to the next meeting agenda.

For agenda item 3, @balacij will put the output of stan and weeder into the discussion for the original issue (#3700).  We'll likely decide that these tools are worth integrating into our CI workflow, assuming that they do not add too much to the time.  Before integrating them into our workflow though, we need to get a complete pass from the tools on our current version of the Drasil.  We can create an issue for the summer students to update the current code-base so that it passes the stan and weeder checks.
