### ISSUE TITLE
Drasil Research Group Meeting, Monday, Apr 15, 3:00 pm, Room ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3711]
1. 'Theories': Shift association with IM/DD/TM/GD terms to 'printing' level #3691
2. Tasks and training for summer students (@balacij)
  - start May 6
    - Mohammad Bilal (will have completed second year SE) (NSERC)
    - Noah Cardoso (will have completed first year Eng) (Eng Research Exp Award)
    - Brandon Bosman (will have completed third year CS) (USRA)
  - start July 15
    - Xinlu Yan (Mitacs student)
  - on boarding document (porting to [doc](https://github.com/JacquesCarette/Drasil/tree/master/doc) folder?)
     - current team members
     - practical info (start date, dress code, etc.)
     - Repos (Drasil, se4sc, etc.)
     - Initial tasks
        - verify access to GitLab, GitHub
        - Consent for Limited Personal Information
        - Linked In
        - Getting started with Drasil
        - Basics of git
        - Contributor's guide
        - Haskell resources
        - Papers to read
        - Software carpentry
        - LaTeX
      -  Advice from previous students
  - initial tasks?  Well-defined pieces the students could take ownership of? Meetings with students?
3. Questions to discuss:
  - Where does the rationale go? Should it be provided for each theory, or only for the final theory?
  - Should we have a "universal" mathematical type for physical variables, analogous to how in Matlab everything is a complex array (I think)?  [Collins2008](https://apps.dtic.mil/sti/tr/pdf/ADA638194.pdf) suggests the mathematical type for physical variables should be "formed as the commutative mathematical product of a physical unit, such as meter or second, and an element of a geometric algebra, which belongs to the family of Clifford algebras."

Regrets: ?

Virtual: @samm82

**Comment by samm82** [comment]
I'll be virtual since I'm feeling under the weather and don't want to spread anything around 😫

**Comment by smiths** [comment]
Thank you for the notification @samm82.  Get well soon!

**Comment by samm82** [comment]
Will we be having this meeting in the Rsch Stdnt Meeting channel? If so, Levi's not in it yet

**Comment by balacij** [comment]
# Potential Work

Work can be on one of two things:
1. an "issue," or
2. a "project."

Getting started/comfortable with any project, it's always best to start off with
knocking off some smaller projects ("issues" in GitHub/<common tech.>
terminology) until you're comfortable larger ones ("projects" in GitHub/<common
tech.> terminology). Furthermore, it would be best to start off with _known_
projects that you can get help with and are guaranteed (or so we believe) to be
relevant and good for the greater project: Drasil.

## Open Issues

Things we want out of Drasil, which are relatively small (or should be) and may
be completed within a single issue/pull request, or is used to track progress of
a larger project.

1. "newcomers"-labelled issues (preferred).
2. Picking random tickets from the backlog.

## Open Projects

Things we want out of Drasil, but are too complex or large to be completed
within the confines of a single issue/pull request.

Note: projects with a "**?**" next to their title have an unclear scope.

### Science-related

Related to physics, mathematics, etc. (i.e., science-related) matters in Drasil.

1. Finalizing removal of `OthModel` variant of `ModelKinds` - https://github.com/JacquesCarette/Drasil/projects/16
2. Adding features to `*Exprs`
   1. Improving vector support (big task) - https://github.com/JacquesCarette/Drasil/projects/17
   2. Miscellaneous - https://github.com/JacquesCarette/Drasil/projects/18
3. Chem Code (stalled?) - https://github.com/JacquesCarette/Drasil/projects/11
4. **?** Documenting DblPend - https://github.com/JacquesCarette/Drasil/projects/6

### Inner-workings-related

Related to the inner workings of Drasil itself (e.g., 1) as an extensible
product and the project setup.

1. Extensible ChunkDBs - https://github.com/JacquesCarette/Drasil/projects/13
2. Package Refactoring (based on #2883) - https://github.com/JacquesCarette/Drasil/projects/14
3. Project Setup Cleanup - https://github.com/JacquesCarette/Drasil/projects/15

### Investigations (Stalled?)

Self-explanatory. Projects related to investigating various aspects of Drasil
and/or related works.

1. **?** "Chunk Investigation" - https://github.com/JacquesCarette/Drasil/projects/10
2. **?** "Rationalizing the data-structures / classes in drasil-lang" - https://github.com/JacquesCarette/Drasil/projects/7
3. **?** "Explore Space, Symbol, and Unit" - https://github.com/JacquesCarette/Drasil/projects/20

### Stalled Projects

Projects that are dependent on many things that are far removed from the primary
task at hand.

1. **?** Projectile - https://github.com/JacquesCarette/Drasil/projects/5

**Comment by balacij** [comment]
@samm82 I imagine so. We're not setup in ITB225 yet though. 4min until 3

**Comment by smiths** [comment]
Great summary of potential summer tasks @balacij.

**Comment by smiths** [comment]
We covered all of the agenda items so this issue can be closed.
