### ISSUE TITLE
Overview of Drasil Meeting, Monday, May 6, 1:30 pm, ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3715]
1. Introductions
2. [Purpose of Drasil starting on slide 22](https://gitlab.cas.mcmaster.ca/smiths/cas741/-/blob/master/Lectures/L20_ArtifactGen/ArtifactGen.pdf?ref_type=heads) (@smiths) (20 minutes)
3. [SRS Template](https://github.com/smiths/capTemplate/blob/main/docs/SRS/SRS.pdf) (@smiths) (10 minutes)
4. [Overview of using/developing Drasil](https://github.com/JacquesCarette/Drasil/blob/drasilPackageStories/notes/DrasilProcessingProjectile.md) (@balacij) (45 minutes)

**Comment by smiths** [comment]
@J1aM1ng this meeting is aimed at the summer research assistants, but it would likely be useful for you to attend as well.

**Comment by J1aM1ng** [comment]
Yes, I'll attend it, because I'll be working on my project during the summer and it may be useful for it.

**Comment by balacij** [comment]
Just to confirm: we're meeting at 1:30pm, right? The title currently says 3pm, but I think that might just be out of date.

**Comment by smiths** [comment]
@balacij you are correct.  I just fixed the title.  Our other meeting #3714 is at 3 pm.

**Comment by J1aM1ng** [comment]
@smiths @balacij I'm sorry for the late notice, but I'll be virtual today.

**Comment by samm82** [comment]
@J1aM1ng I'll call you on Teams

**Comment by samm82** [comment]
I can't seem to find any contact info for you 😅 Do you have any way of contacting me? If not, send me a way I can reach you to sam.crawford82@gmail.com 😁

**Comment by J1aM1ng** [comment]
Can we call in the teams channel called Rsch Stdnt Meeting? This should work.

**Comment by smiths** [comment]
We concluded this meeting and covered all agenda items.
