### ISSUE TITLE
Capture modules/functions not specified in the SRS

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#372]
Look through your implementations for code that doesn't "come from" the SRS and define them using the data types in https://github.com/JacquesCarette/literate-scientific-software/blob/master/code/Language/Drasil/CodeSpec.hs  (lines 152 - 181).  This will probably need to be extended as I only implemented what was needed for glassbr.

As an example see https://github.com/JacquesCarette/literate-scientific-software/blob/master/CaseStudies/glass/Implementations/Python_Simplified/Implementation/interp.py.  This code is for functions that perform linear interpolation on input data in glassbr.  If you look at the glassbr SRS, some of the data definitions and instance models refer to interpolation in their descriptions, but there is no way to get to code from this.   See https://github.com/JacquesCarette/literate-scientific-software/blob/master/code/Example/Drasil/GlassBR/Interpolation.hs.  This is the interpolation module for glassbr defined in terms of Drasil chunks.

You can add these modules to the generated code using the `addModDefs` functions -- see glassbr Body.hs line 120.

- [ ] SSP
- [ ] GamePhys
- [x] GlassBR
- [x] NoPCM
- [x] SWHS

**Comment by hmadej** [comment]
is there currently a way to define a record or class?

**Comment by palmerst** [comment]
@hmadej  Not yet.  This will be added soon.  For simplicity, I will start with records.  (I assume records will be sufficient for your example since it is written in C?)

**Comment by hmadej** [comment]
Ya, I think records should be enough.

**Comment by AKM11** [comment]
Short of the ODE, there does not seem to be much that SWHS and NoPCM can pull in terms of non-SRS related code.  Checking them off for now.

**Comment by JacquesCarette** [comment]
I am going to go ahead and close this issue. Not because it is all implemented, but because we'll naturally get back here once we dive into code generation again. [on wiki]
