### ISSUE TITLE
How to correct stable?

### ISSUE THREAD

**Issue by NoahCardoso** [JacquesCarette/Drasil#3724]
While working on renaming chunks named in the form "XChunk" as just "X" #3244 I changed UncertainChunk to Uncertain. Stable complains that the generated and stable code are different. The outputs look the same. I looked at stable but I am unsure of what I have to change to correct it.
![imagetoday](https://github.com/JacquesCarette/Drasil/assets/106560551/c0a0eb0d-a9fe-4062-9d50-8f6222df59f7)

**Comment by balacij** [comment]
I was passing by, and we discussed this in person, but for the sake of completeness:

For almost all of our targets, we don't clean `build/` before generating any sort of artifacts, we just overwrite them (this is something to consider for #3557). Did you have any artifacts lying around (e.g., PDFs after having built any tex artifacts in the `build/` folder)?

There were some there, so we just made sure to `make cleanArtifacts` or `make clean_artifacts` first, and then it works fine.

For reference, `make help` provides a nice list of targets we can use in the Makefile, and in the future, please post anything interesting you found in the logs with your ticket (this just makes it easier to help virtually).
