### ISSUE TITLE
Hiding all OS instructions in the New Workspace Setup by default 

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3725]
<details>

<summary>Seeing the New Workspace Wiki this year, I think the document looks larger than it effectively is for each OS. I think we should wrap each related operating systems instructions, where it makes sense, using `details` nodes.  (OPEN ME!)</summary>

See how this can hide text irrelevant to me if I use one OS and don't care for the instructions of another?

</details>

The scheme is as follows:

```html

<details>

<summary>Operating System X</summary>

Instructions go here

</details>
```

**Comment by smiths** [comment]
Sounds like a good idea to me @balacij.  This seems like a good newcomer issue.

**Comment by BilalM04** [comment]
@balacij I updated the [wiki](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup), please check it out.

**Comment by balacij** [comment]
Thank you, @BilalM04! It looks great!
