### ISSUE TITLE
Fix Typo in Projectile SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3731]
There is a typo in the [Terminology and Definitions](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Sec:TermDefs) section of the Projectile example.  In the definition of rectilinear, "ocurring" should be "occurring."

**Comment by BilalM04** [comment]
@smiths I can't seem to find the typo [here](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Sec:TermDefs). This issue also does not seem to be linked to any commits or PR's indicating it may have been solved.

![image](https://github.com/JacquesCarette/Drasil/assets/77511892/606dbb2a-dc53-4b1e-bdf0-bebb73556bca)
