### ISSUE TITLE
Question about multiType

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3738]
I'm just looking to confirm my assumption about `multiType`.  GOOL has a `multiType` function as part of the `RenderType` typeclass in `RendererClasses.hs`:

https://github.com/JacquesCarette/Drasil/blob/e974d5af2f0f4e2433b5066aeed4d17499766557/code/drasil-gool/lib/GOOL/Drasil/RendererClasses.hs#L89-L91

It's implemented like so in `SwiftRenderer.hs`:

https://github.com/JacquesCarette/Drasil/blob/e974d5af2f0f4e2433b5066aeed4d17499766557/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs#L212-L217

As far as I can tell this is for defining tuple types.  Could I get a confirmation though?  Thanks.

**Comment by bmaclach** [comment]
Your assumption is correct.

**Comment by smiths** [comment]
The question has been answered, so we can close this issue.  :smile:
