### ISSUE TITLE
Generate Labels for Section Referencing

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#374]
The `missingP` hack needs to be removed eventually. In order to do so, as mentioned in commit 0b7d75c by @JacquesCarette: "We need to generate 'labels' for sections, and then use those for reference. They 
should be a new chunk type, and they'll be stored in a table, like the current symbol table.".

**Comment by JacquesCarette** [comment]
I think that labels are already high on Dan's "to do" list.

**Comment by szymczdm** [comment]
Done as of a51a739315345f07a0a017cf. Not exactly a new chunk type, but a new field for our existing referable chunks/layout objs.
