### ISSUE TITLE
Drasil Research Group Meeting, Friday, May 24, 11:00 am, ITB/225

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3742]
Due to the holiday Monday we will be meeting at a different time next week, Friday, May 24 at 11:00 am.

1. Do we have any work we could be aiming to submit to [ETAPS](https://etaps.org/2025/cfp/)?  (ETAPS will be at Mac next year.)
2. Design discussion
- progress on redesign of attributes and chunks #3733 @NoahCardoso (related links [redesign of attributes and chunks](https://github.com/JacquesCarette/Drasil/wiki/Attributes-and-Chunks%3a-Meeting-June-7th,-2023), [Explore Space, Symbol and Unit](https://github.com/JacquesCarette/Drasil/projects/20), #3314, #3244, #3733)
- `constDecDef` (#2179) @B-rando1 
- #3722 @BilalM04 
- [how does code generation in Drasil work](https://github.com/JacquesCarette/Drasil/issues/3712#issuecomment-2083442644) @balacij 
- @balacij are there other issues we should add to this or future discussions?

Regrets: ?

**Comment by samm82** [comment]
I realized I probably should have mentioned this earlier, but I'm busy at 10:30am until 11:30am at the LATEST; I could be there as soon as I can, unless it's worth it to reschedule 😬 I'm OK either way!

**Comment by BilalM04** [comment]
Here is the [repo](https://github.com/BilalM04/projectileSRS-mdbook) for the manually created Projectile SRS in mdBook.

**Comment by smiths** [comment]
Thank you for the link to the mdbook version of projectile @BilalM04.  Looks nice!  I noticed you had "Option 2 (HTML)" for the theoretical models.  It seems like you might have been comparing the LaTeX and HTML versions.  If you are looking for feedback, the LaTeX version looks better in my opinion and the html version doesn't display the equations properly.  :smile:

**Comment by smiths** [comment]
@samm82 to save on the headache, I'm not going to reschedule.  It doesn't sound like you will miss everything.  Arrive when you can.

**Comment by J1aM1ng** [comment]
I've just recovered from a new Covid, and so far the symptoms are only mild headaches. Regarding the agenda on this meeting, should we take time to discuss #3717? This relates to our designs for discrete indexing #3718 and #3719 and my inventory shows that open issues on indexable structures are very diverse, so we may need to scope and prioritize them.

**Comment by smiths** [comment]
@J1aM1ng I've added the issues on indexing to the agenda.  We might not get to it in this meeting, but we can bump the topic to the next Drasil meeting if necesssary.

**Comment by JacquesCarette** [comment]
I'm not sure, as of yet, what there is to 'discuss'. I was expecting you @J1aM1ng to put together some material (where #3717 is merely the data-gathering stage), analyze "where we are now" (and write it down for all of us to read), and synthesize a potential way forward (also written down). Then we can have a proper discussion.

**Comment by smiths** [comment]
Good point @JacquesCarette.  We can remove the @J1aM1ng topic from the next agenda and reintroduce it when the written material is available.

**Comment by J1aM1ng** [comment]
I agree with @JacquesCarette  that the current "data collection" isn't too specific, and I'll be analyzing the backlog linkages in a more specific doc? in #3717, which may involve analyzing our current progress in indexing data structure, and which issues may be "more valuable" or "more urgent".

**Comment by J1aM1ng** [comment]
I still tested positive for the Covid virus this evening, so I'll be staying home tomorrow to avoid infecting anyone else. @smiths Can you offer me a virtual meeting at that time, it would be very helpful! I look forward to discussing the topics in the agenda with you guys!

**Comment by smiths** [comment]
I'm sorry to hear you aren't feeling well @J1aM1ng.  I hope you get well soon!

Unfortunately, I find it challenging to both chair the meeting and deal with IT issues.  Please ask one of your colleagues to virtually connect you to the meeting.

**Comment by balacij** [comment]
I can try to help with that.

Hope you feel better soon @J1aM1ng!

**Comment by J1aM1ng** [comment]
Thank you @balacij !

**Comment by J1aM1ng** [comment]
@balacij Let's start a video of this meeting in Teams.

**Comment by NoahCardoso** [comment]
Here is a link to my Chunk diagram. 
https://drive.google.com/file/d/1kwox9THKnfZaWZgU9xsBMZOj9skH8I5p/view?usp=sharing

**Comment by samm82** [comment]
Things that stood out to me:
- In our current chunk usage, it seems like there's a bit of overlap between `ConstraintSet e` and `ConstrConcept`. What is the real difference between them? Could we potentially merge the two if there isn't one?
- The current usage of `CI` seems to imply we'd want to be able to encode some information at a "Drasil-specific" level, where we can require more things to be present (e.g., abbreviations)
   - A specific example I noticed: `gamePhysics :: CI` has the `ConceptDomain` `physics`, even though it isn't a "physics" concept (i.e., "GamePhysics" won't be talked about in the vast majority of physics-related discussions, lectures, or textbooks). Based on our "representation" discussion, is there a distinction between being _part of_ a domain vs. just _describing_  or being _related to_ a domain? It seems like while acceleration is _part_ of the physics domain, GamePhysics isn't, but the physics domain is part of _it_, potentially at just a Drasil level?
https://github.com/JacquesCarette/Drasil/blob/22a164cb42ac3dac240502f0911de9644129df2b/code/drasil-example/gamephysics/lib/Drasil/GamePhysics/Concepts.hs#L22
- Related to `ConceptDomains`, at what level would we want to be adding these to chunks? At what level is this semantically useful? Jason mentioned that domains are interesting and could be developed/used more; we'd probably discuss this as part of this "digging deeper"
- We mentioned that while we don't currently support synonyms, we may want to in the future

**Comment by smiths** [comment]
@NoahCardoso thank you for taking the picture of the whiteboard.  Please add the picture and a link to this meeting agenda to our [wiki](https://github.com/JacquesCarette/Drasil/wiki).  You can add it under Design/Attributes and Chunks.  There are already two items under this, including the meeting notes from a previous meeting.  It is great to have the picture in this discussion, but we likely won't be able to find it in the future.  By putting it in the wiki we'll be able to find it again in the future.  :smile:

**Comment by smiths** [comment]
The meeting was completed.  Uncovered agenda items were moved to the next meeting.

**Comment by JacquesCarette** [comment]
Those are really good comments @samm82 . Any suggested redesign should be able to provide 'answers' to these points.
