### ISSUE TITLE
Add Constant Folding to GOOL?

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3747]
Are we planning to add [Constant Folding](https://en.wikipedia.org/wiki/Constant_folding) to GOOL at some point?  The reason I'm asking is that I'm implementing support for 1-indexed array API's (#3746), and this leads to a lot of adding and subtracting `1`.  For this reason and likely for others, it would be nice to be able to fold arithmetic of constants.  For example, the line of GOOL code
```haskell
var "e" int &= listAccess (valueOf $ var "a"
    (listType double)) (litInt 1)
```
translates to the Python code 
```python
e = a[1]
```
and the Julia code
```julia
e = a[1 + 1]
```
which looks pretty ugly in my opinion.  This likely won't happen very often, since most of the time we'll be accessing arrays by a variable index, but it would be nice to simplify the constants in cases like these.

The only difficulty I can think of with this is that there may be cases where two constants are intentionally left apart, for example to show where a 'magic number' came from.  So I guess if we choose to implement constant folding, we might also need some way of specifying when to use it, and when not to.

**Comment by balacij** [comment]
I'm not sure if we've planned on it (did you check the backlog?), but it sounds like a good idea for list accessors especially. 

The `Expr` -> `CodeExpr` -> `GOOL` pipeline already does some folding, so I don't think we necessarily need to worry about "magic numbers" being hidden (i.e., we're continuing what we already do). Additionally, I think magic numbers should probably be contained in named constants if we care about code readability. There's only one edge case to that, I think, which is when a magic number only appears once within some relatively small block of code.

We're currently missing a generated design document, which I imagine this information would go into

**Comment by JacquesCarette** [comment]
I think that general constant folding is a ways off. However, having `listAccess` be 'smart' (and effectively do constant folding) does seem like a good idea.

**Comment by J1aM1ng** [comment]
As mentioned in #3717 and as @balacij mentioned above, I checked the backlog, and it looks like it's not a small amount of work (which can be discussed further in the meeting). Also, I agree that GOOL listAccess should make a conscious decision to start indexing at 0 or 1, as this is oriented towards two different scenarios for SRS / Julia and other codes.

**Comment by B-rando1** [comment]
It sounds like we're not ready to do this in general, but it might be possible within the context of the List API.  When I get back to #3746, I'll see if I can incorporate constant folding into the design.
