### ISSUE TITLE
Potential redesign of chunks

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3754]
This is just a placeholder issue for things we need to remember. It can be closed once we've figured out where the information really ought to go. In particular some [comments from Sam](https://github.com/JacquesCarette/Drasil/issues/3742#issuecomment-2130061240) are definitely worth keeping in mind.

**Comment by balacij** [comment]
Perhaps we can move this to #3773 ?

**Comment by JacquesCarette** [comment]
Sure - closing in favour of that discussion.
