### ISSUE TITLE
Change Non-Functional Requirement (NFR) labels in the SRS to be consistent with the template

### ISSUE THREAD

**Issue by BilalM04** [JacquesCarette/Drasil#3756]
This issue is a result of issue #3753 

Currently, the NFR labels are inconsistent between examples. For some examples, the NFR labels end in `"-able"`. Ex. maintainable, understandable, usable, etc. While for others, it ends in `"-ability"`. Ex. maintainability, understandability, usability, etc. 

Change the all the NFR labels to be consistent with the [Smith et al SRS template](https://github.com/smiths/capTemplate/blob/main/docs/SRS/SRS.pdf). This means we should be using the labels ending in `"-ability"`.

Change Should be made in the following examples:
- [ ] [dblpend](https://jacquescarette.github.io/Drasil/examples/dblpend/SRS/srs/DblPend_SRS.html#Sec:NFRs)
- [ ] [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/srs/GlassBR_SRS.html#Sec:NFRs)
- [ ] [SWHSNoPCM](https://jacquescarette.github.io/Drasil/examples/swhsnopcm/SRS/srs/SWHSNoPCM_SRS.html#Sec:NFRs)
- [ ] [PDController](https://jacquescarette.github.io/Drasil/examples/pdcontroller/SRS/srs/PDController_SRS.html#Sec:NFRs)
- [ ] [Projectile](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/srs/Projectile_SRS.html#Sec:NFRs)
- [ ] [SglPend](https://jacquescarette.github.io/Drasil/examples/sglpend/SRS/srs/SglPend_SRS.html#Sec:NFRs)
- [ ] [SSP](https://jacquescarette.github.io/Drasil/examples/ssp/SRS/srs/SSP_SRS.html#Sec:NFRs)
- [ ] [SWHS](https://jacquescarette.github.io/Drasil/examples/swhs/SRS/srs/SWHS_SRS.html#Sec:NFRs)

**Comment by smiths** [comment]
@BilalM04 I do not know how the NFRs are implemented, but if it is feasible, it makes sense for me for maintainability, usability etc to be concepts.   It seems odd to me that the concepts have different string outputs in the different examples.  They really should all be the same (even if we later change our mind on what they should be) across all examples.

**Comment by BilalM04** [comment]
@smiths the NFRs are implemented as follows:

https://github.com/JacquesCarette/Drasil/blob/5b5faadb1a130b24225106f4f71fcc9b65afe369/code/drasil-example/glassbr/lib/Drasil/GlassBR/Requirements.hs#L90-L121

The code above is for GlassBR. Each example similarly creates its own non-functional requirements, they are not being reused across examples, resulting in different string outputs. Thus, the small inconsistencies are likely due to human errors.

A possible solution is to create functions for common requirement descriptions, similar to #3735, and importing them to the examples that use them.

**Comment by smiths** [comment]
Thank you for the information @BilalM04.  I was just assuming we were using these NFR concepts across the examples.  We should definitely treat them like you did the maintainability requirement.  We will want to be able to have problem specific details of the NFRs, but the names are part of the template and should be standardized.

**Comment by BilalM04** [comment]
Should this be moved to another issue or should I add it to this existing issue? I feel like changing the NFR labels and standardizing them would be easier and more convenient to do at once.

**Comment by smiths** [comment]
@BilalM04 if I understand the question correctly, "this" is the right way to close the issue.  I think your "this" is referring to functions for common requirements.  Having functions for common requirements would let you close the original issue.  Manually changing things would also let you close the issue, but there is nothing in the issue that says how you are required to solve the problem manually.  You can think of your original issue as an abstract statement of what you want.  How it is done is a concrete decision that is not imposed by the issue.  This is similar to our discussion of markdown tables yesterday.  The "spec" says to have the information look nice in an organized format, but the implementation doesn't have to be a markdown table.  :smile:
