### ISSUE TITLE
Figuring out good precedence

### ISSUE THREAD

**Issue by NoahCardoso** [JacquesCarette/Drasil#3759]
While working on #3710, one of the suggestions from `stan` was regarding fixity. In some files like Monad.hs we should add 'infix[l|r]' declaration to the operator with explicit precedence rather than giving the operator the default of 9. 
(https://github.com/JacquesCarette/Drasil/blame/5b5faadb1a130b24225106f4f71fcc9b65afe369/code/drasil-printers/lib/Language/Drasil/TeX/Monad.hs#L87-L89)

%% is just given the default of 9 but since Text.PrettyPrint steals <>, %% is used instead for "$$". So %% should have a fixity of 5 like "$$".
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/8387c42f-b62a-4105-ad8e-f6dcbcb46d06)
Would a change like this make sense?

**Comment by balacij** [comment]
Using the same precedence as `pretty`'s `$$` makes sense to me. Do we have any other operations around that would conflict with 5?

**Comment by NoahCardoso** [comment]
I found this. 
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/d0caf562-0d17-4403-9159-06bc36b71a19)

**Comment by balacij** [comment]
Great. We're only interested in the ones from `drasil-printers` here, I think. Keeping consistent with `pretty`s `$$` 5 sounds good to me.
