### ISSUE TITLE
Splitting up Constructors and Methods in GOOL's Representation

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3763]
Currently, in GOOL's representation of classes it stores the constructor in the same list as the other methods.  This is fine in most cases, but there are a few benefits to storing them separately:
- Currently, GOOL prints all methods (including the constructor) in the order they appear in its list.  Constructors should appear at the top of a class's definition, and right now we rely on `drasil-code` to put the constructor at the top of the list of methods.
- With Julia, 'methods' are really just functions that need to be outside the definition of the struct, but constructors are part of the struct, and in some cases must be within the struct definition.  Currently when generating a Julia struct library from a GOOL class, the only way to know that a method is the constructor is to check if its name is the same as the object's name.  Keeping them separate from the beginning would make this possible in a much cleaner way.

I started work on making this change, and it seems pretty straightforward to do.  I'll submit a PR when it's ready, but until then, does this sound like a reasonable change to make?

**Comment by balacij** [comment]
Since constructors are a special category of 'methods' that we often need to treat differently in the backend (e.g., make sure at least one exists, sort them, make sure they're placed above functions, make sure they initialize all variables in the class, etc.), I think it makes sense, like we discussed in person. For the sake of clarity for others, it would be great if you can link the area of code that the actual change would affect (same with the problematic code in the second point).

**Comment by B-rando1** [comment]
Good point @balacij.

Here is an example of a place where the constructors and methods are put into the same list, and where order matters for the final code:
https://github.com/JacquesCarette/Drasil/blob/213d57f9612993b841e85697348516b7917e63e0/code/drasil-code/test/Observer.hs#L31-L34
Note that `observerConstructor` is in the same list as the other methods.

Here is the spot in the Julia renderer where we need constructors to be separate from methods:
https://github.com/JacquesCarette/Drasil/blob/70b91661d8a3501bd9827ae0013ce860ead5166b/code/drasil-gool/lib/GOOL/Drasil/LanguageRenderer/JuliaRenderer.hs#L778-L784
The `blank` on line 783 is a placeholder for where constructors need to go.

There are a lot of lines of code that would be affected by this change in small ways, so it might be easier to refer to the PR directly for some of them.  If there's anything else I should mention here though, feel free to point it out!

**Comment by JacquesCarette** [comment]
@B-rando1 might be a good idea to put a summary of today's discussion in here, for posterity. And then possibly a need to split things up into more than one issue.

**Comment by B-rando1** [comment]
@JacquesCarette I don't believe we discussed this specific issue yesterday.  Are you referring to #3752?

**Comment by JacquesCarette** [comment]
On this issue: as constructors and methods mean different things (at least in some languages), it makes sense to keep them separate.
