### ISSUE TITLE
Questions about multiple constructors

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3765]
All of our languages except Python allow multiple constructors for an object.  We should probably lay out a stance on whether GOOL allows multiple constructors.
- We could prioritize Python compatibility and only allow one constructor in GOOL.
- We could allow multiple constructors in GOOL, but throw an error if we try to generate Python code with multiple constructors.
- We could try to find a way to adapt multiple GOOL constructors into a single Python constructor.
    - I'm worried that this would be difficult and would not lead to idiomatic code.

As a side note, Julia encourages having constructors call other constructors (e.g. cascading up default values) when it makes sense.  See [here](https://docs.julialang.org/en/v1/manual/constructors/#man-outer-constructor-methods) for an example.  I don't think this idea works in other languages, so I'm assuming we don't need to worry about that in GOOL?

**Comment by B-rando1** [comment]
We discussed in our meeting today that it's ok if some design decisions don't work in all languages.  Based on that, it seems to me that the right choice is to allow multiple constructors in GOOL, but have the Python renderer throw an error if we give it multiple constructors.  This is in line with our treatment of floats (also not supported by Python).

As another side note, this is one more reason why #3763 is a useful change: counting the number of constructors!

**Comment by balacij** [comment]
Using the `@classmethod` annotation on methods defined inside of classes is conventional for building alternative constructors. Actually, those are technically named constructors -- they're just not a language-native concept, but a base library annotation one.

For example,
```python
from math import cos, sin

class Point:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  
  @classmethod
  def from_polar(c, radius, angle):
    return c(radius * cos(angle), radius * sin(angle))
```

This is relevant to our recent discussion about the [constructors and methods](https://github.com/JacquesCarette/Drasil/pull/3764#discussion_r1647734108).

**Comment by B-rando1** [comment]
Oh, that's interesting @balacij!  I'm trying to think if there would be a way to take advantage of this functionality in GOOL.
- I guess we can't call it a method, since it has the `@classmethod` annotation and it's called like a static method.
- With our current structuring of constructors it would be difficult to make it work, as we would need to give a different name to each constructor.  Getting unique names wouldn't be a problem, but keeping track of which name is used for each type signature would be.
- I suppose if we extended the functionality of constructors to allow named constructors (as you mentioned above and in our discussion of [constructors and methods](https://github.com/JacquesCarette/Drasil/pull/3764#discussion_r1647734108)), we could probably make it work that way.

Do we think this is a worthwhile change to make?  Enabling named constructors in GOOL likely wouldn't be too big of a task (apart from a few discussions about semantics), but taking advantage of it in `drasil-code` might be tricky.

**Comment by balacij** [comment]
> I guess we can't call it a method, since it has the @classmethod annotation and it's called like a static method.

Yep, it is a class-level method (individual instances of the class do not have the `@classmethods` defined within them)! One note: `@staticmethod` differs from Python's `@classmethod` in one 'real' way: a `@classmethod` method has access to the class through the first parameter (i.e., `self`, except `self` refers to the class).

> With our current structuring of constructors it would be difficult to make it work, as we would need to give a different name to each constructor. Getting unique names wouldn't be a problem, but keeping track of which name is used for each type signature would be.

Yep. This is really where we would need named constructors. Now that I think about it: I think that named constructors should be the _default_. They provide information about which constructor we really intended to call. Overloading can then be employed only when rendering into a language that supports it.

> I suppose if we extended the functionality of constructors to allow named constructors (as you mentioned above and in our discussion of constructors and methods), we could probably make it work that way.

Yep!

> Do we think this is a worthwhile change to make? Enabling named constructors in GOOL likely wouldn't be too big of a task (apart from a few discussions about semantics), but taking advantage of it in drasil-code might be tricky.

If it's not too much work on GOOL's side, I think it would be a great idea! Do we even have any instances of multiple constructors on the `-code` side? It might be useful to only have it one-sided for now?

**Comment by B-rando1** [comment]
@balacij I did more research on what the `@classmethod` is doing, and I think I understand it better now.  This [article](https://www.sitepoint.com/self-types-with-javas-generics/) summarizes it pretty well.  Essentially, the `@classmethod` allows you to return an instance of the class you call the method with, rather than the class that implemented the method.  It removes the need to override the method with every child class.

Python and Swift have this functionality, but it looks like Java, C#, and C++ do not.  The article mentions that you can use a hack to get some of the functionality, but it's convoluted and still somewhat limited.

I see the value of adding support for named constructors to GOOL, but the semantics and level of support seem to vary quite a bit between languages.

Beyond that, I think we'll have to separate representation of the 'true' constructors from named constructors, because they have a few unique features.

I'm less confident now that it would be a simple job to add support for them in GOOL.  Do we still think they're worth adding?

**Comment by balacij** [comment]
I think you linked the wrong thing? Regardless, the [official documentation](https://docs.python.org/3/library/functions.html#classmethod) explains it very well. I'm not quite sure what you mean by "rather than the class that implemented the method" because that class should be the same class that the `@classmethod` method should return instances of.

Java, C#, and C++ don't have it in the same fashion, but they like to call it the "Factory" pattern. Both `@classmethod` and the factory patterns are accidental complexities of the core language being ill-suited to handling what we wanted to build with them. Regardless, they've become convention.

In all honesty, I think that class constructor overloading is a bit overrated as a feature (classes become bloated, code becomes unreadable) -- the "factory" pattern (named constructors) makes more sense in my opinion.

I can definitely see it being complex w.r.t. implementation. It might be something better suited to being built in `drasil-code` rather than `drasil-gool`, but I'm not really sure. I definitely think they're still worth adding, I don't think it's a priority at all.

**Comment by B-rando1** [comment]
@balacij we talked about this a bit yesterday.  Here's a concrete example of the type of behaviour that `@classmethod`s allow:

```python3
class Bird:
    def chirp(self):
        print("Chirp!")

    @staticmethod
    def newBird():
        return Bird() # always returns an instance of Bird

    @classmethod
    def newBirdChild(cls):
        return cls() # returns an instance of cls, where cls is whatever class it was called from (Bird or Hawk in this case)
    
class Hawk(Bird):
    def soar(self):
        print("Soar!")

b = Bird.newBird()
h1 = Hawk.newBird() # returns an instance of Bird
h2 = Hawk.newBirdChild() # returns an instance of Hawk
b.chirp()
h2.chirp()
h2.soar() # allowed, since h2 is a Hawk
h1.chirp()
h1.soar() # not allowed, since h1 is a Bird
```
Running it gives us:
```
Chirp!
Chirp!
Soar!
Chirp!
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    h1.soar()
AttributeError: 'Bird' object has no attribute 'soar'
```

It's this sort of thing that Swift can also do, but Java, C#, and C++ can't do.  From talking with you yesterday it sounds like we don't want this sort of functionality anyway, as giving child classes additional public methods tends to cause confusion in most scenarios.  In that case, I think `@staticmethod`s might be what we want to use with Python, as they are more consistent with static methods in other targets.

From all that, I just need to ask - if we're just implementing named constructors as static methods (as in your example [here](https://github.com/JacquesCarette/Drasil/pull/3764#discussion_r1647734108)), do we really need a separate construct for them?  We can already do static methods in GOOL, so is there a benefit of adding syntactic sugar for them?

**Comment by JacquesCarette** [comment]
We really don't want to be adding random features to GOOL, even if some underlying language supports them. We need to add only the features that we need to get our job done. This seems to be crossing that line.

**Comment by B-rando1** [comment]
Hmm, I see what you mean.  It's probably best to focus our efforts elsewhere for the present.

Coming back to the original discussion, would it be a good change to have the Python renderer throw an error if it is given a 
 class with multiple (standard, unnamed) constructors?  Assuming we can merge #3764 soon, this would be an easy change to make.

**Comment by JacquesCarette** [comment]
Yes, if you try to use features in GOOL that some language can't handle, it should throw an error.

**Comment by B-rando1** [comment]
Sounds good.  I'll get that change out in the next day or so, and with that we should be able to close this issue.
