### ISSUE TITLE
Expr Type Definition Issue

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/Drasil#377]
I have been trying to create a function that finds the units of an equation based on its values.  However, I have encountered an issue.  At the moment, the most basic component of an Expr is the `C a` component.  This type just takes a SymbolForm, which is fine for generating the equation as text, but an issue when I am trying to pull out a unit for evaluation and the code assumes that only a symbol is present.  Making the type `(SymbolForm c, Quantity c)` might work but I am having problems.  Need to find a way around the cyclic imports that result when trying to import Quantities into Expr and the plethora of errors that pop up in every other file assuming one can work around the cyclic import.

**Comment by JacquesCarette** [comment]
Don't try to put `Quantity` in `Expr`, this is a move backwards.  The solution is to use a "symbol table" that tracks units.

**Comment by AKM11** [comment]
How will it track units if the type does not know it has units?

**Comment by JacquesCarette** [comment]
You look up a symbol in a table of all symbols which are associated to a `Quantity`.  If it is not there, it's an error.  Note that it may still be unitless.

Does that make sense?

**Comment by AKM11** [comment]
Maybe? Does that mean I have to create a list of the symbols (as opposed to the units) cross-reference it with the table of symbols, pull out the units from that and then simplify the value?

**Comment by JacquesCarette** [comment]
Yes, that's right.

**Comment by AKM11** [comment]
Okay then... how do I go about referencing a table without explicitly passing it into the function (or am I supposed to explicitly pass it?).  Is the table not being automatically generated with section one?

**Comment by JacquesCarette** [comment]
I mean a table in the sense of Haskell, i.e. `Map.Map`.  In NoPCM, what the lines

    nopcm_SymbMap :: SymbolMap
    nopcm_SymbMap = symbolMap nopcm_Symbols

do.  Which apparently contains `QSWrapper` -- so this is already the right 'table' for you to look things up from.

Yes, for now, you'll need to thread that table through.  We're still looking at better means to achieve that.

**Comment by AKM11** [comment]
Alright then, I will see what I can do. Thank you.

**Comment by szymczdm** [comment]
I'm unclear as to whether this is still an issue, and what the issue itself was (ie. where was this being implemented?). @JacquesCarette or @smiths , have any ideas?

**Comment by smiths** [comment]
I believe that @AKM11 was trying to automatically determine the units for an equation from the units of its constituent parts.  For instance, the units of density rho would be calculated (as kg/m^3) from the equation rho = m/V, where m is the mass (kg) and V is the volume (m^3).

This would be a great functionality to have, but I think we can classify this as a low priority enhancement.  If @JacquesCarette sees things differently, I'm certainly open to an adjustment.

**Comment by AKM11** [comment]
Sorry for not finishing this and leaving the issue ambiguous. @smiths is correct, I was trying to create a function that would automatically determine the units of an equation based on the units of its input parameters.  To answer @szymczdm questions, I opened this issue to try and get advice on how to make this function work, no actual code breaking problem is present unless the code in Language\Drasil\Misc is uncommented.  Hope this helps.

**Comment by JacquesCarette** [comment]
@AKM11 Thanks for the comment, it helps a lot.

**Comment by JacquesCarette** [comment]
The "help" part is done, so I am closing this one. Moved the feature request to a new issue.
