### ISSUE TITLE
Create a Wiki Page for Benefits of Drasil

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3778]
As discussed in #3772, we would like to create a wiki page showcasing examples of the benefits of Drasil over other methods of writing software.

As discussed in the PR, @BilalM04 is going to create the document, and add it to the sidebar under Misc.

A first example will be based on the PR, showing how changing a single line of code affected 175 files in the generated code.

**Comment by smiths** [comment]
This is a nice example of an issue.  What is needed to close it is clear.  Moreover, the scope is not too large.  The issue will likely be closed quite soon.
