### ISSUE TITLE
Handling multiplicative complexity of `Choices`

### ISSUE THREAD

**Issue by B-rando1** [JacquesCarette/Drasil#3780]
I was starting to implement new input patterns based on our discussion in #3752, and I stumbled upon a bug.  I wanted to see what `projectile` looked like with `Bundled` inputs and `Modular Separated` input methods.  When I ran the `make` command with these parameters, the generated code had an issue.  Because inputs are `Bundled` there is an `InputParameters` class, but since input methods are `separated`, the `InputParameters` class doesn't have a constructor.  

It shouldn't be too hard to fix this bug (I'll open an issue for it), but I think it might point to a larger problem with the exponential growth of `Choices`.  With our current set of `Choices` there are roughly $9$ combinations of options that affect parsing, validation, and storage of input; and already some of these are untested.  Our discussion in #3752 could easily lead to dozens of combinations (the design I'm currently thinking about would lead to $9 \times 3 \times 3 = 81$ combinations), so I think we need a more systematic approach to this design.

Somehow, we need to implement how we use `Choices` in a way that either doesn't lead to these edge cases, or makes it clear where the edge cases are.  Ideally we should have some kind of adapter that allows each field in `Choices` to do its job without caring what the values of the other fields are.  E.g. if we need to ask if inputs are `Bundled`, we shouldn't simultaneously ask if input methods are `Separated`.

I'm still wrapping my head around this, but do you guys have any ideas?

**Comment by B-rando1** [comment]
Update: I just realized that the 'bug' was actually an artifact of changes on my branch.  The scenario I was talking about is tested with the GlassBR example.

This might mean that this isn't as big of a deal as I originally thought, but I do think it's still worth discussing: how do we provide lots of options without making a mountain of work for ourselves to both implement and test?

**Comment by smiths** [comment]
@B-rando1 good to hear that the suspected `bug` isn't a problem, but you are correct that the combinatorial explosion of design choices is going to lead to problems.  We don't want users to be able to generate code (or documents) that are wrong.  Our current design variabilities are close to independent, so we've avoided trouble.  The variabilities you are looking at are definitely not independent.  Maybe we can "bundle" the variabilities to only allow reasonable options for the user.  For instance, for a Linux desktop users select from themes (I can't remember what they call them) that change many things, like colours, fonts, etc.  The user doesn't control each variability; they can pick between different sets of curated variabilities.

**Comment by JacquesCarette** [comment]
Combinatorial explosions are inevitable and thus our inability to test all choices. Eventually what we'd want to do is testing by 'sampling' sets of choices.

In the shorter term, we definitely need to have 'coherence conditions' between choices. You can think of it as a "type system for choices" if that helps.

When things explode, then usability dictates schemes like Linux's. But note that advanced Linux hackers can actually go "under the hood" and still make all those choices by hand. They do have a system that does try to prohibit the most obvious inconsistent sets of choices.

**Comment by B-rando1** [comment]
@JacquesCarette just to clarify, you're saying that you want to avoid Dr. Smith's idea of 'themes'.  That we should make Drasil capable of performing under any combination of `Choices`, even if we hide `Choices` behind 'themes' for most users.  And you're saying that if we design `Choices` in a smart way, we should be able to minimize the edge cases we run into.

Is that a good summary of your comment?

**Comment by JacquesCarette** [comment]
To be precise: I don't want to force themes. Otherwise yes, that is a good summary.

**Comment by B-rando1** [comment]
From what I've seen, I think that with a better-designed set of `Choices` this issue will be less of a problem than I originally thought.  If I run into more problems I'll reopen this issue, but for now I think we might as well close it.

@smiths @balacij for future reference, would it be better to have conversations like this in Discussions rather than Issues?

**Comment by smiths** [comment]
Sounds good @B-rando1.  I agree that the Discussions forum is a better location for conversations.
