### ISSUE TITLE
Erroneous use of nounPhraseSP in `drasil-example`

### ISSUE THREAD

**Issue by NoahCardoso** [JacquesCarette/Drasil#3782]
I have noticed that in `glassbr` almost all words defined in `Unitals.hs` are made using `nounPhraseSP` from #3777 and #2299. Is there a reason for this? `nounPhraseSP` blocks words from being plural. For example, the word "explosion" was a `nounPhraseSP` even though it has the plural form "explosions". I think that we should use `cn'` rather than `nounPhraseSP` as it allows plural. This `nounPhraseSP` default is also used a lot in the other examples not just `glassbr`.

| `cn` | Create a self-plural, common-noun NounPhrase | String -> NP |
| `cn'` | Create a common-noun NounPhrase which becomes plural by adding "s" | String -> NP |

![image](https://github.com/JacquesCarette/Drasil/assets/106560551/8b5a8438-7271-42d7-8e37-77359fda3af9)

![image](https://github.com/JacquesCarette/Drasil/assets/106560551/1beeb051-f9bd-4396-828d-1d2005c3f9da)

**Comment by balacij** [comment]
It might've just been "pattern following" when writing code. I think it's safe to say that we can go ahead and just start fixing the other ones too.

**Comment by JacquesCarette** [comment]
Agreed, this was likely copy-pasta without understanding of the consequences.

**Comment by NoahCardoso** [comment]
While working on this I have come across some special cases where there are multiple words within the sentence and I am not sure how to handle the plural form. For example, should the plural of this sentence be `probabilities of failure`, `probability of failures` or `probabilities of failures`
https://github.com/JacquesCarette/Drasil/blob/6ce1c24e10255132c1bbd73a716dcec87c871093/code/drasil-example/glassbr/lib/Drasil/GlassBR/Unitals.hs#L132

**Comment by smiths** [comment]
@NoahCardoso can you give the context (sentence) in which the phrase in question is being used?  There is one plural form that would work in all situations.

**Comment by NoahCardoso** [comment]
The phrase is not used in the plural form in the text. Should it still be able to be used in the plural form? If it were I assume that the plural would be probabilities of failure. 
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/6a9dad90-ab0a-4098-aae7-9fed9c223389)

**Comment by NoahCardoso** [comment]
I changed some of the examples I mentioned in `glassbr.unitals`. I think that unless the plural form of the word is needed there is not really a point in changing it to a `nounPhraseSP` into `cn'`. @balacij what do you think?

**Comment by balacij** [comment]
IIRC, it took us a while to debug this. So, it might be good to get it out of the way for future contributors, at least for the simple cases. Do you know how long it would take for the rest to be done?

**Comment by NoahCardoso** [comment]
It would take less than 30 minutes if I only change things that, based on their definition in the example, make sense to be plural. 
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/9057c3ac-ff23-4c56-8b6e-b10e727b189a)
Since in the example there is only one project and target does it make sense to change them to `cn'`.

**Comment by balacij** [comment]
> It would take less than 30 minutes if I only change things that, based on their definition in the example, make sense to be plural.

I think that's a great criterion for 'which ones should we just get rid of while it's fresh in our minds, now'. So, I vote to just have 1 PR that just fixes a bunch of them.
