### ISSUE TITLE
Implementing use of DDs

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#379]
As mentioned in commit 7c24552, attempting to use `DDs` to output the data definitions did not produce an output. Instead, the output is as follows: 
![image](https://user-images.githubusercontent.com/28247301/29180856-15b062f4-7dc7-11e7-9dda-7d2d4b309433.png)

**Comment by szymczdm** [comment]
Implemented for HTML, next is TeX, then will need to test and confirm that the new versions are either A) As good as the old, or B) better. Likely some small issues will come up.

**Comment by szymczdm** [comment]
This is much further along as of 36e29f99d309dfcc5d36609c4647d8c643238301. It still needs some testing and tweaking, but now the DDs (and TMs!) are printing.

**Comment by szymczdm** [comment]
This is complete as of a13d7ebcb7186173ba3d0fe9ef8a3ce3d2dd8dad
