### ISSUE TITLE
Broken links in Contributor's Guide

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#3816]
The [Contributor's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide) has some broken links that we should fix.  They should all be checked, but the ones I noticed are as follows:

- "or example, the syntax -- |. The [website](https://haskell-haddock.readthedocs.io/en/latest/markup.html), gives examples and instructions."
- Read through [Git2Know](https://github.com/JacquesCarette/Drasil/wiki/Git2Know) to learn more about branching, pull requests, merging, and anything else git or Github related.

**Comment by NoahCardoso** [comment]
Those were the only two bad links I found. They are both working now.

**Comment by smiths** [comment]
Is there a PR for your fix?

**Comment by balacij** [comment]
Oddly, going to the wiki and clicking the links from there, the two links you reference, seem to work for me! Are the links you referenced here directly from the wiki page?

**Comment by smiths** [comment]
The links work for me now too.  Since there was no PR, I think that @NoahCardoso might have directly edited the Contributor's Guide.  This is probably what happened because the [wiki version under version control](https://github.com/JacquesCarette/Drasil/blob/main/wiki/Contributor's-Guide.md) still has the errors.

**Comment by NoahCardoso** [comment]
I put through the pr to fix the links
