### ISSUE TITLE
Order of `eNames'`

### ISSUE THREAD

**Issue by NoahCardoso** [JacquesCarette/Drasil#3828]
While working on changing `eNames` from Lists to Sets I found that the order of `eNames'` and `meNames` is important to stable. I don't think that this is necessary. I'm not quit sure how to interpret the log for `eNames'`. For the `meNames` log, it just looks like it's sorting them by name instead of order of appearance. I don't see any inherent reason to say that the new sorting style is bad "bad".
[eNames'.txt](https://github.com/user-attachments/files/16071827/eNames.txt)
[meNames.txt](https://github.com/user-attachments/files/16071828/meNames.txt)

**Comment by JacquesCarette** [comment]
Yes, the order does matter, in that the order must be fixed and can't be random and change from run to run. But the *current* order does not necessarily matter. This change may legitimately induce a lot of one-time changes to stable.

**Comment by balacij** [comment]
Exactly as @JacquesCarette explained, `stable/` needs to indeed be the 'expectable' artifacts that we generate. However, that doesn't mean that they're permanently set in stone.

With the stable changes, it would be sorting them by UID, which we know is the wrong strategy long-term, but I think it's better to use a `Set` than a million `nub`s. Only small heuristics (e.g., group things related to each other next to each other, 'relative'-functions should have the 'relative' object as the first parameter) come to mind when talking about the order in which variables should be introduced, and I don't think they have anything to do with the alphabet nor order of appearance in complex expressions. That being said, if we have any doubts right now about the order, we can retain it using an [ordered set](https://hackage.haskell.org/package/ordered-containers-0.2.4/docs/Data-Set-Ordered.html).

**Comment by JacquesCarette** [comment]
We should figure out a decent key (i.e. not UID) to sort these sets by. If we can't find one, we're probably setting ourselves up for later pain.

**Comment by NoahCardoso** [comment]
In projectile, when `eNames'` is switched to a `set` the order of the `theta`, `v_lanch` and `g` variables is changed in the generated code.
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/24cdeedc-db0e-4598-9257-8115ad627314)

In dblpend, when `eNames'` is switched to a `set` the order of the `theta`, `v_lanch` and `g` variables is changed in the generated code.
In swhsnopcm, when  `eNames'` is switched to a `set` the order of `m_1`, `m_2`, `L_1` and `L_2` are changed. The `srs` is unchanged.
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/50b5a043-ecae-4434-b0c6-12fb3c219436)

in glassbr, the order of the `LR` and `q` variables is changed in the code but the `srs` is unchanged.
![image](https://github.com/JacquesCarette/Drasil/assets/106560551/838b3e54-5168-4c67-a01a-bca1b6cfa4ff)

When `meNames` is a `set` only the order of things within the `srs` is affected not the generated code.

It seems that only the order of one set of variables is changed in each of the effected examples when `eNames'` is changed, but the `srs` is unaffected. Only the `srs` is effected when `meNames` is changed but the generated code is the same as it is not reported in `logs`.

**Comment by JacquesCarette** [comment]
We need to know:
1. what the sorting criterion was before,
2. what is the key now.

None of the changes above seem bad. Nevertheless, we should have an explanation for all of them, to make sure that it is a reasonable way to order things.

**Comment by NoahCardoso** [comment]
Currently `eNames'` doesn't explicitly sort the `UID`s it collects them in the order they are encountered. Is it possible to use `symbol`s as the key rather than `UID`s? I am not sure what else we could use as a key other than `UID`s and `set`s.

**Comment by balacij** [comment]
Ok, I think we have a starting point from the meeting. Do you have any leftover questions, @NoahCardoso ? Can we close the issue?

**Comment by smiths** [comment]
@NoahCardoso as we discussed, please put a comment in the code that sorting by symbol might not be the ideal solution.

**Comment by NoahCardoso** [comment]
Yes this issue can be closed and I will indicate in the code that this is a temporary fix, not the final solution
