### ISSUE TITLE
Why are we copying ids?

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#384]
I was thinking about issue #383 while reviewing check-in d4dd541efe85b8146a3decca56dedf4b54d6d42a, and it struck me that we're doing something really odd there.  In fact, `vc` seems odd as well: it builds-in id copying as a pattern.

Is this a good thing?  In some ways, yes, as in some ways the new chunk is a refinement of the old one, so it is 'the same'.

In other ways no: now we have different data-structures that share the same id.  We **will** encounter the problem that we'll want to insert two of these into the same `Map.Map` -- and then what?

We need to think this through properly.

**Comment by szymczdm** [comment]
>  We will encounter the problem that we'll want to insert two of these into the same Map.Map -- and then what?

I don't think that's as big an issue as it seems, though I can definitely see the potential for problems. Namely, our maps contain certain specific information (ie. SymbolMap is Symbols related to an id), if we have multiple chunks with the same id, they are the same chunk. One of them may lack a field, but they should not have inconsistent information. 

For example: a NamedChunk vs. a Quantity. If they have the same `id` they should have the same `term` and abbreviation. The Quantity extends the NamedIdea to have a relevant symbol, so if we look for a symbol for that chunk (regardless of whether it's the NamedIdea version or the Quantity), we should be able to find it.

If we ever reach a state where two chunks have the same ids, but conflict in other ways, they should not be considered the same chunk, and should be separated.

**Comment by JacquesCarette** [comment]
> if we have multiple chunks with the same id, they are the same chunk

So we have to know (and tell everyone and ...) that this indeed true.  I am vaguely uncomfortable about this.  Not sure what to do about it though.

**Comment by szymczdm** [comment]
@JacquesCarette Can we close this question (and/or replace it with an actionable item)? Or does it require further discussion?

**Comment by JacquesCarette** [comment]
I think this requires further discussion. I am still uncomfortable about it. One of the nice things about using lenses is that we can have a single data-structure representing what we know about something (idea/concept/quantity/etc), but view it at all the other 'levels' too. So it feels like it doesn't make sense to create the data-structure for a concept that is also a quantity. When we create the quantity, the concept just comes along "for free" as it were.

**Comment by JacquesCarette** [comment]
So I now know why we do this, and why it is, in fact, ok: we should see IDs as primary keys in a database. If things have the same key, then they are 'the same thing', but potentially appear in multiple datastructures. The thing itself is then the join of all of the structures.

Of course, accidental overlap will create havoc.  But well, so be it.
