### ISSUE TITLE
CI: need to re-test PRs more often when other PRs are merged in

### ISSUE THREAD

**Issue by balacij** [JacquesCarette/Drasil#3875]
> Yep, it looks like we had 2 branches that were merged into `main` which edited `stable/`. Specifically, mdBook's stable used and old version of the NFRs, while this branch used the new one.
> 
> When we merge commits into `main` that edit `stable/`, we need to make sure that all open PRs are synced with `main`. For files that are already tracked and conflicting, GitHub will report the _git_ conflicts on the PR. However, for new files, GitHub  doesn't find any conflicts with tracked files. So, we end up in an awkward situation where the CI hits an edge case, and fails.
>
> I think there are a few things we can do:
> 1. Add a `git pull origin main` step early on in the CI to make sure that when PRs are opened/contributed to while `stable/` was potentially edited after opening/before a new contribution, we make sure to force errors to come up.
> 2. When a PR is merged (that affects stable), we need to re-run all CI-passing PRs that don't have a merge conflict with `main` to make sure that with `main` pulled in again, the PRs still pass the CI.
>
> (2) might make (1) slightly redundant, but that's fine. 
>
> Thinking out loud: with (2), to save CI minutes, we could split up our main Build & Test workflow into:
> 1. Build code, test `stable/` diff, test Haddock docs, test `stable-website/` diff.
> 2. If `stable/` has TeX changes, build TeX using `stable/` (not using our current `build/`-based builds!). 
> 3. If `stable/` has mdBook changes, build mdBooks with the same `stable/`-based scheme as (2).
> 4. If `stable/` has changes to generated code, build the generated code with the same `stable/`-based scheme as (2).
>
> However, that leaves our deployment in an awkward position where it would either have to rebuild everything from 1-4 or use cached results from 2-4 (which is a bit more difficult). 
>
> I like the idea of splitting up the CI into a few files (that would conveniently resolve #2836 for us too, I think), but I'm not quite happy with how website deployments would work later on. There would either be some redundancy or there would be hacky 'retrieve cached results or do the redundant rebuild again'-style work needed. I suppose the redundancy is better, however. 

_Originally posted by @balacij in https://github.com/JacquesCarette/Drasil/issues/3862#issuecomment-2247960547_

**Comment by JacquesCarette** [comment]
As I said there: this seems like overkill. I think we should solve this by process, not automation. It's not failsafe, but it's lighter weight.

**Comment by balacij** [comment]
I'm perfectly fine with solving this through process rather than automation :smile:
