### ISSUE TITLE
Figures in the PDF SRS are Scattered 

### ISSUE THREAD

**Issue by BilalM04** [JacquesCarette/Drasil#3882]
The figures in the PDF SRS are scattered. In LaTeX, figures can sometimes float to unexpected locations because LaTeX tries to optimize the layout. I've noticed that often times figures get placed in a location that disrupts the flow of the document. For example, the trace graphs in [GlassBR](https://jacquescarette.github.io/Drasil/examples/glassbr/SRS/PDF/GlassBR_SRS.pdf) get placed in the middle of a list, same for the system context figure in [Projectile](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/PDF/Projectile_SRS.pdf).

One possible option is to use the `float` package. We would add the following to the preamble:

```LaTeX
\usepackage{float}
```

Then modify the code for figures by adding a placement specifier. In this case, `H`, for "here".

```LaTeX
\begin{figure}[H]
...
\end{figure}
```

I manually tested the above code for GlassBR and it seems to work quite nicely.

**Comment by smiths** [comment]
I agree with this.  I often use the float package in my own LaTeX documents.  I think most of the Drasil developers look at the html version of the documents because they look better than the LaTeX ones.  It would be nice to get the pdf versions to be something we can show off more.  :smile:
