### ISSUE TITLE
Re-inventory data structures which implement chunks. Modify as necessary.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#390]
From @JacquesCarette 's comments on #98 

- LCChunk seems obsolete
- MethodChunk, ReqChunk and ModuleChunk perhaps shouldn't be chunks at all
- RelationChunk seems too crude. I think a proper decomposition of Theory will take care of that.
- Some of the wrappers (CQS, QS) may not be needed anymore?
- Looks like Q and QSWrapper are in fact isomorphic?

I'll also do a full pass and minor report after making changes to see where we stand.

**Comment by szymczdm** [comment]
Double-check necessity of SymbolChunk (did previous changes remove the need for it?)

**Comment by szymczdm** [comment]
NTS: This is going to keep coming up. Definitely something that can be done in stages. With the coming addition of attributes it would be a good idea to look at this again.

**Comment by JacquesCarette** [comment]
Looks like @njericha did a good inventory on the wiki at
https://github.com/JacquesCarette/Drasil/wiki/Types-and-Typeclasses-in-Drasil
It is likely somewhat out of date, but it is a good start.

**Comment by szymczdm** [comment]
I'll make sure that wiki page is updated on the next pass, and all future passes should be done directly to the wiki (with comment here to point out the wiki commit).

**Comment by JacquesCarette** [comment]
I'm doing another pass on this (and then I'll update the wiki too). But I think this can be closed.
