### ISSUE TITLE
SSP - Codegen hangs indefinitely

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#391]
After finally fixing everything up so that it compiles and is runnable, I noticed that attempting to generate code for SSP will cause the execution to hang indefinitely. I assume there's some infinite recursion happening, but haven't been able to track down the error yet. I commented it out as of commit dd5e8fe8e046e07968712ed2fc5b907787cadac7.

**Comment by palmerst** [comment]
This was fixed in f3c7080e1d8183530dcc1014b77ce5f0548ed163
