### ISSUE TITLE
Drasil Research Group Meeting, 3pm, Tuesday Aug 27, 2024, Virtual

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3946]
It's a smaller crew this week and as @balacij and @samm82 will both be virtual, we'll make the whole meeting virtual. @Xinlu-Y please add your weekly report below.

**Comment by samm82** [comment]
I'll actually be in Hamilton that day for our thesis meeting, so I could be in-person for this as well if that would be better! Virtual works for me as well though.

**Comment by Xinlu-Y** [comment]
### Weekly Summary
- Based on the suggestion, I modified the code in #3916.
- Created a draft PR #3945 to extend support for additional simple types of literal values.
- Started work on #3248.
### Blockers
- Awaiting feedback on #3916.
- Regarding #3945:
  - Currently, `LitValue` is used to hold certain types of literal values.
  `data LitValue = LitChar Char`              
              `| LitDouble Double`
             ` | LitFloat Float`
             ` | LitInt Integer`
             ` | LitString String`
  - The goal is to extend this to support any literal value. However, does it make sense to extend `LitValue` to support other types of literals that GOOL handles, such as `List` or `Array`? If we find that handling all possible cases is impractical, I am considering converting `LitValue` in `valFromData` to a `Maybe` type. This would allow us to replace default values like `LitInt 0` with `Nothing` when appropriate.
