### ISSUE TITLE
Build failiing

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#3966]
I think the combination of #3939 and #3940 merged together has caused a build failure. Since both @B-rando1 and @NoahCardoso are back on school terms, @Xinlu-Y could you take a look at this? I think the new behaviour is probably correct, so some kind of `stabilize` is likely needed -- but I think the usual one doesn't look at GOOL tests at all.

**Comment by B-rando1** [comment]
If the issue is that the code generated by the GOOL tests is different, you should be able to run `codegenTest_stabilize` to update it.
