### ISSUE TITLE
Remove duplicate symbols from Table of Symbols

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#397]
Some of the examples have multiple copies of symbols appearing in their table of symbols. This is likely an error with some of the underlying chunks (ie. two chunks that have the same term and symbol, but a different id).

**Comment by szymczdm** [comment]
Currently SSP has 2 different 'E's (I believe one should be E_i and this may be an issue with how indexing is performed) and Chipmunk has 2 different 'F's (again, one should be F_i), 'j's (equivalent), 't's (equivalent). The rest have been removed.

**Comment by szymczdm** [comment]
@JacquesCarette just want to keep this on your radar since it seems to be an 'indexing' issue (which was part of Expr and we need to decide if it should stay there or not).

**Comment by JacquesCarette** [comment]
"seems to be" is a little vague. Can you point out some specific lines in some specific files which are causing problems?

**Comment by szymczdm** [comment]
### SSP E

SSP.Unitals line 165-167: intNormForce is an interslice normal force (E_i), but its symbol is E (seen on line 167 as `cE`). When used in expressions, it is used with indexing (example: SSP.DataDefs line 162 -> `inxi intNormForce`).

**Comment by szymczdm** [comment]
### Chipmunk F

Similarly, `force_i` (defined in GamePhysics.Unitals line 216) is the force applied to the i-th body, but its symbol is F (actually, is identical to that of `force` from Data.Drasil.Quantities.Physics --> `eqSymb QP.Force`).

This looks like it was just a typo, as I can't find any use of indexing herein. I'm currently testing my hypothesis.

**Comment by szymczdm** [comment]
This and #359 are linked (almost duplicates). I'm reassigning this one to @JacquesCarette because you've been working with Expr and we still haven't come to a clear decision on how we should handle indexing (that is still the problem behind SSP's duplicate symbol as mentioned above).

I think the problem hinges on whether indexing is going to remain something that's specifically Expr-level or not.

**Comment by JacquesCarette** [comment]
This has come back onto my radar.  'duplicate' is a symptom. The cause is indexing, i.e. our serious lack of a coherent design when it comes to indexed things.  And index is the discrete special case of functions, which are also a bit of a problem.  I'm going to have to think about this, as this isn't straightforward (various experiences with indexing in Maple inform that opinion).

**Comment by JacquesCarette** [comment]
I've looked some more into this. Continues to be tricky. I'm going to have to sit down with @smiths and look at what is really being said here. We need to make sure we pull apart the display issues from the knowledge capture issues. I think we captured things naively (i.e. as they're normally displayed), and that has contributed to this problem.  In other words, we don't really know how to capture 'component-wise' information.

**Comment by samm82** [comment]
@JacquesCarette The duplicate entries described in this issue seem to be resolved, as the duplicates were removed in Chipmunk, and there is _no_ occurrence of _E_ at all in SSP. The absence of the _E_ might be a separate issue, but I think this might be able to be closed?

**Comment by JacquesCarette** [comment]
Assuming you've gone through every single comment above and were unable to find duplicates that match the description, then yes, this can be closed.

**Comment by samm82** [comment]
The above changes have been resolved, but there is now an "almost" duplicate between the two is-safe values in GlassBR that looks related to what @vajihehm is working on in #1304:

![is-safe](https://user-images.githubusercontent.com/35857611/57798566-09939500-771b-11e9-8b8b-17233954ad7a.png)

**Comment by JacquesCarette** [comment]
Right, @vajihehm and @smiths should take a look at that. But we can call this particular issue closed, and if there is something new in GlassBR, a new issue can be created.

**Comment by vajihehm** [comment]
@samm82 There is not any "exact" duplicate symbols in the GlassBR. Since I confirmed with @smiths the name of these symbols and I did not make sense what changes you need. Thus, @JacquesCarette  and @smiths please let me know the new changes which would figure out the above problem.

**Comment by samm82** [comment]
In the above screenshot, `is-safeLoad` and `is-safeLR`, and `is-safePb` and `is-safeProb` are very similar and capture the same information, so only one should really be used of each pair. Feel free to clarify which one with @smiths.

**Comment by vajihehm** [comment]
@samm82 "is-safeLoad" and "is-safeProb" and "capacity" and "load" symbols are the requested changes based on the manual version and are required for "theoretical model" and they should been considered as a "concept" and should be abstraction of the chuncks and reusable as well. Besides, they are not a part of the inputs or outputs unlike "is-safeLR" and "is-safePb" which are required for "IM". For more clarification please take a look at the below snapshot (manual version of SRS) and  #1293, #1255  , #1185 pull requests.
![TM](https://user-images.githubusercontent.com/42664092/57806455-2b961300-772d-11e9-872a-c0b0e0564b5d.PNG)

**Comment by samm82** [comment]
@vajihehm So are you replacing `is-safeLR` with `is-safeLoad` and `is-safePb` with`is-safeProb`?

**Comment by vajihehm** [comment]
@samm82 Nope, we need both of them, abstract symbols like "is-safeLoad" and "is-safeProb" for "TM" and  " is-safePb" and "is-safeLR" for "IM" as the below snapshot.

![IM](https://user-images.githubusercontent.com/42664092/57810628-415c0600-7736-11e9-9ab8-acbb6d0de2d4.PNG)

**Comment by samm82** [comment]
@vajihehm But what's differentiates them? Don't they contain the same information? From my screenshot above, their definitions are almost the same, so why specifically do we need both?

**Comment by vajihehm** [comment]
@samm82 please take a look at the TM snapshots carefully. For example "Pb" is the probability of breakage in "IM" and "Pfail is the probability of failure in "TM". "failure" is a concept. The new theoretical models should be abstraction of the two chunks in "Instance Model". The concept of **safety** is something that should generalize from the GlassBR example. The theoretical model should be reusable in other contexts. The concept of safety would also make sense in the SSP for example. So, they are different in concept. 

![TM2](https://user-images.githubusercontent.com/42664092/57812034-da405080-7739-11e9-84c7-2bffba2df00c.PNG)

**Comment by smiths** [comment]
@samm82, the two similar symbols are on purpose, as @vajihehm has described.  I specifically asked for the second similar symbol because the original version of GlassBR did not have an abstraction representation of the notion of safety.  As we refine the example, we might come up with better wording, but for now, I'd just like to get the changes I requested to GlassBR into Drasil.  Hopefully @vajihehm will be able to do this soon.  Once the changes are made, we can look at how all of the details "hang" together.
