### ISSUE TITLE
Check out these resources

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#398]
Look at [learnyouahaskell](learnyouahaskell.com) and [software carpentry](https://software-carpentry.org/lessons/) to go over material that will be useful to you. Specifically check out the lessons on Git, Make, and the Unix shell.

Once you've done this, please close the issue.

**Comment by szymczdm** [comment]
@deviprasad135 have you done this yet? If so, please close this issue. If not, please let me know (and it should be on your to-do list for once you're done your current tasks).

**Comment by deviprasad135** [comment]
@szymczdm I have gone through the material but I dint complete every thing.

**Comment by smiths** [comment]
If you have any questions @deviprasad135, please let us know.  These topics are fundamental building blocks for the Drasil project (and for many other projects), you want to be comfortable with them.  Maybe set aside an hour each day to work through the software carpentry modules and the Learn you a Haskell chapters?

**Comment by deviprasad135** [comment]
Ok @smiths
