### ISSUE TITLE
Review Chapter 2 of Dan's Thesis

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#3983]
Please review Chapter 2 (Background) of my thesis found on the `Writing` branch under People/Dan/Thsis/Draft/ (The file `Thesis_Main.pdf` should be up-to-date wrt changes we discussed.

The file for Chapter 2 is `background.tex`

**Comment by szymczdm** [comment]
@smiths Yeah, it should be fine to look it over. I jotted ideas and such down for what should go in there.

**Comment by smiths** [comment]
@szymczdm here are my comments on Chapters 1 and 2.  If you have any questions, please let me know.  We can discuss further during our next meeting.

[Dan_Thesis_Ch1-2_Fdbck.pdf](https://github.com/user-attachments/files/18049561/Dan_Thesis_Ch1-2_Fdbck.pdf)

In my comments, I mentioned my recent NSERC application.  I think the proposal could be useful for you on the topic of reproducibility and replicability.  The literature review section in particular has some references you could use.  My review follows a pattern I'm hoping you can add to your Chapter 2.  After I review the options available from the literature, I contrast those with the proposed work. After you present existing options, it would be good for you to contrast them with the generate everything approach.  Whenever possible, you should say how the generate everything approach addresses weaknesses of the current options.

[Proposal.pdf](https://github.com/user-attachments/files/18049568/Proposal.pdf)

[References.pdf](https://github.com/user-attachments/files/18049569/References.pdf)
