### ISSUE TITLE
Sanity checkers

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#401]
In the future, it would be nice to add "sanity checkers" to review the Drasil code.  These checkers should prevent "silly" mistakes.  For instance, if there is a min and a max specified for data constraints, the min should be less than (or equal to?) the max.

**Comment by JacquesCarette** [comment]
Would you be ok if we moved this enhancement to the wiki?

**Comment by smiths** [comment]
Yes, I just moved this idea to the potential projects page in the wiki.
