### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#405]
Improve our Drasil infrastructure to properly use continuous integration (https://github.com/marketplace/category/continuous-integration).  Travis seems to be the tool that many prefer to use with GitHub.  We discussed this briefly during our meeting on October 10, 2017.

**Comment by szymczdm** [comment]
We have CI with Travis working, however, I'm going to hold off on closing this issue until we've got our build versions matching stable.

I want to make sure I add code similar to that from df49291df8d6c076a85dfe70a251ce1f785be687 for Chipmunk and GlassBR once we've gotten them to a stable state.

**Comment by szymczdm** [comment]
I think this should be closed. Since we have #452 where we "forced" things to match, the CI side is now working as expected. The stable versions will be cleaned up, but that's not relevant to this issue.
