### ISSUE TITLE
Revise Manual version match Stable, highlight issues: NoPCM, SWHS, SSP

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#406]
Please review the "manual" version of your assigned case studies against the "stable" version.  When there are differences, your action will depend on the character of the differences as follows:

1. The stable version is better - change the manual version to agree with the stable version.
2. The manual version is better - post an issue (initially assigned to @szymczdm) to point out the difference.
3. There is a tie in terms of quality - change the manual version to agree with the stable version.

If you do not know which is better, please post an issue.  You can assign it to @szymczdm, to begin with; he will reassign the issue, if required.

The manual version can be found in the CaseStudies folder.  The stable version can be found in the code/stable folder.

If there are any questions, please post them as comments below.  After completing this issue, the next issue (not yet created) will be to critically evaluate the documentation and improve it.

**Comment by JacquesCarette** [comment]
I think this is done - @smiths can you verify?

**Comment by smiths** [comment]
Yes, this is as done as it is going to be.  :smile:  Going forward we will only be maintaining the Drasil version of the case studies.
