### ISSUE TITLE
Revise Manual version match Stable, highlight issues: hghc, GlassBR, Game Physics

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#407]
As for to issue #406, please review the "manual" version of your assigned case studies against the "stable" version. When there are differences, your action will depend on the character of the differences as follows:

 1.  The stable version is better - change the manual version to agree with the stable version.
 2.  The manual version is better - post an issue (initially assigned to @szymczdm) to point out the difference.
 3.  There is a tie in terms of quality - change the manual version to agree with the stable version.

If you do not know which is better, please post an issue. You can assign it to @szymczdm, to begin with; he will reassign the issue, if required.

The manual version can be found in the CaseStudies folder. The stable version can be found in the code/stable folder.

If there are any questions, please post them as comments below. After completing this issue, the next issue (not yet created) will be to critically evaluate the documentation and improve it.

**Comment by JacquesCarette** [comment]
@smiths this seems like a dead issue - should it be closed?

**Comment by smiths** [comment]
Yes, going forward we will only be maintaining the Drasil version.  We have got everything we can hope to get out of this issue.
