### ISSUE TITLE
Add attributes to chunks

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#408]
Issue #26 points out that constraints can have additional rationale information.  The potential need for rationale information can easily be seen to extend to other types of chunks, like assumptions.  Moreover, supporting information, like a detailed derivation could be an attribute of a theory, or general definition, or instance model.

@szymczdm , if my description above does not mirror the discussion we had in our group meeting (Thursday, October 26), please adjust it.  😄

**Comment by szymczdm** [comment]
Started this in commit e4f381f2d1becd2aa3ef2aa96feeb6916a0253ad, but I haven't had a chance to add some new instances yet. It's on my priority list.

**Comment by JacquesCarette** [comment]
@szymczdm Can you carefully what needs done? I think you've done the bulk of the infrastructure work, so that this can now be mostly be chopped up into smaller 'to dos' that can be parcelled out piecemeal (as it were).

**Comment by szymczdm** [comment]
Attributes exist throughout the infrastructure. Now it's just a matter of adding attributes to all of the appropriate data types that don't yet have them, and then updating the smart constructors to work with Attributes. This is definitely something that can (and will) be split up easily (which I'll do in the morning).

**Comment by samm82** [comment]
Is this now obsolete or is there still work to do in this regard? @szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
Good catch - obsolete.  Closing.
