### ISSUE TITLE
Add facility to attach derivation attributes to chunks that need this information

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#409]
We need a way to link chunks, like general definitions, theoretical models and instance models, with supporting information on related derivations.  An example from the Solar Water Heating System example follows.  The equation given in GD2 is derived following the summary of the general definition.  Issue #46 mentions this, but in the context of formatting the output.  The more important problem is linking the derivation information to the chunk.

![examplederivation](https://user-images.githubusercontent.com/1422000/32072359-53ec6484-ba60-11e7-8214-c63f3a375a58.jpg)

**Comment by szymczdm** [comment]
Added as of 5e3ba91cdcdc42cb197d2a731b5f656d6434a0e9. I'll close this once I've confirmed it renders properly.

**Comment by szymczdm** [comment]
This is working for General Definitions as of c3d0453d2e3b2e632ed3c8a15ccda19d62494926. It will be fairly straightforward to add it to DDs and TMs as well. Once IMs are working, it should also be straightforward to add it to them.

**Comment by szymczdm** [comment]
Done as of a13d7ebcb7186173ba3d0fe9ef8a3ce3d2dd8dad
