### ISSUE TITLE
Delete MG from Drasil

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#413]
Delete all references to the MG generation in the current version of Drasil.  It is not correct.  We will readdress this in a different way in the future.  This issue closes #119.

**Comment by palmerst** [comment]
All of the code relating to the old design doc generation has been removed as of e993aa0b737b6eddbd7690a550dcfc94376cf8a3

**Comment by JacquesCarette** [comment]
Do we have a 'future' issue to remind us to re-add this?  There was some useful information that is now 'deleted'.  Of course, revision control is great, so it isn't completely gone.  But for easy reference, commits 0c93079, 7458b00, 342f1f3, e1d6b65, 59290a5, 949330b, cc16a63, e993aa0 can be useful to remind us of the information that was removed.
