### ISSUE TITLE
Simple Design Document

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#417]
Work with @palmerst to create a design document from the knowledge that is already in Drasil.  Start with the GlassBR example.  Look at existing MG, but leave out modules that are implemented by OS, leave out decomposition hierarchy.

**Comment by JacquesCarette** [comment]
I have inserted this one on the wiki as something to get back to later (so it's not lost), but will close it for now. By the time we do get back to this, lots more will have changed.
