### ISSUE TITLE
SSP Case Issues

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#419]
Hello @szymczdm ,
These are problems I found in SSP case. But I didn't finish yet. So probably I will get more...
Thanks : )

1. Section 1.1 Table of Unit. I feel the manual version table layout is better, which version should I keep?

2. Section 4.2.2 Theoretical models. For T3, two versions' equations are different. After tracing back to symbol table, I feel P = ... + c' may be the right. Isn't it?

3. Section 4.2.2 Theoretical models. For T4, I am confused by different notation. I feel no prime notation is right because there is no delta' in symbol table. Just want to make sure.

4. Section 4.2.3 General Definitions. For GD1, the manual version description part referenced both fig and section. I think this makes more sense. But stable version only referenced the section number. What do you think?

5. Section 4.2.3 General Definitions. For GD2, equations for two versions are different. In Manual one, two  parts of expressions are connected with 'minus', but stable version saying 'plus'. Which one is right?

6. Section 4.2.3 General Definitions. For GD3, the description part seems have the same problem reference problem2 the T3. 

7. Section 4.2.3 General Definitions. For GD6, equations are diff. The second term and the forth term in manual say 'minus', but stable version say 'plus'?

8. Section 4.2.3 General Definitions. For GD9, the equation notations are diff. I feel the manual version is right according to the description. What do think?

9. Section 4.2.4 Data Definitions. After DD14, the equation (4) are different. Manual version connects two terms with 'minus', but stable 'plus'.

**Comment by szymczdm** [comment]
2. Stable is correct.
3. Manual is correct. Stable should have a prime
4. Manual is better (but there should be a space between Fig and the number)
5. @smiths will double check (create an issue)
6. Stable description is better, but should have working references.

Stopping there for the time being.

**Comment by szymczdm** [comment]
7. @smiths will look into which is the correct version and create an issue if necessary.
8. Manual one is correct. Stable needs to be updated.
9. Manual is most likely correct, but @smiths will confirm.

**Comment by smiths** [comment]
@smiths will look at the physics.  @halonazhao will look at whether stable has been updated to match manual.

**Comment by smiths** [comment]
With respect to item number 7 in this issue (moment equilibrium), I've verified that both manual and stable are incorrect!  The manual version seems to have changed the numbering in the slices from i and i-1 to i-1 and i.  This matches one of the sources of information (Zhu paper), but not the figure of a slice given in the SRS.  The numbering in the figure was used for the force equilibrium, so the moment equilibrium needs to be consistent with this.  I'll rederive the equation and find the correct one.

**Comment by smiths** [comment]
I've corrected GD6 (Moment Equilibrium) in the SSP example.  The manual version should now be correct, and the stable version should be changed to match with it.

The manual version can be found at:

https://github.com/smiths/caseStudies/blob/master/CaseStudies/ssp/Documentation%20Files/SRS_SSP.pdf

**Comment by smiths** [comment]
With respect to item 9, the manual version is correct.  The stable version should be changed to match the manual version.

**Comment by halonazhao** [comment]
All spots needed to be updated in manual version were fixed.

**Comment by smiths** [comment]
Thank you @halonazhao for updating the manual version.  Fixing the stable version should be able to start when @szymczdm gets referencing working.

**Comment by smiths** [comment]
@halonazhao, where were the fixes to the manual version committed?  I cannot find any commits by you in the case studies repo.  In the future, when you say something is fixed, please give a pointer to the fix, so that others can inspect your fixes.

**Comment by niazim3** [comment]
@halonazhao What is the status of this issue?

**Comment by halonazhao** [comment]
These were fixed. Just I didn't have commits for each issue, so it's kind of different to wrap up a decision. I will close this issue.
