### ISSUE TITLE
Verify one to one mapping between assumptions and likely changes for noPCM

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#421]
Please verify that for Section 4.2.1 (Assumptions) in the manual version of the SRS for noPCM that each LC reference only comes up once.  I seem to recall in our meeting earlier today that LC1 (or maybe it was LC2?) showed up with multiple assumptions.  In the version I have, each likely change maps to only one assumption.  Most likely it was the fuzzy projector that confused me, but I don't want to assume.  Does each of your likely changes only appear beside one assumption in the manual version of the SRS?

**Comment by halonazhao** [comment]
They are good. They all only reference one assumptions both in manual version and stable version.

**Comment by smiths** [comment]
Okay.  I'll close this issue.
