### ISSUE TITLE
Add Section references to the manual version of NoPCM

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#422]
In the intro of Section 4.2.1 (Assumptions) of NoPCM please add the section references to the manual version so that it matches the stable version.  This issue is an outcome of the discussion in issue #418.

**Comment by halonazhao** [comment]
Yes, fixed.

**Comment by smiths** [comment]
Where has the fix been made?  I do not see a commit to the case studies repo?

**Comment by halonazhao** [comment]
This issue has been solved in CaseStudy repo. I just double checked. Modification has been made. Can I close this issue? @smiths

**Comment by smiths** [comment]
Can you please include a link here to the case study repo commit that closes this issue.  (You can copy urls into GitHub comments.)  The link provides traceability if we need it in the future.

**Comment by halonazhao** [comment]
Changes were made in https://github.com/smiths/caseStudies/commit/c1decefcea41636e7cc893d0d4088dc3339c8ecf.
This issue can be closed.

**Comment by smiths** [comment]
Good!
