### ISSUE TITLE
Change URLs in Source Fields to BibTeX Citations for NoPCM Manual Example

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#425]
For the Manual version of NoPCM, please change the source fields that are URLs to citations.  You will need to create BibTeX entries for each referenced web-page, and then cite these resources in the Source field.

**Comment by halonazhao** [comment]
Does this issue have the same meaning with #424?

**Comment by smiths** [comment]
No, this issue is different from #424.  That other issue is more general.  It is about adding a source field to those parts of the document that do not have them, but should.  This issue is specific to NoPCM and correcting the existing source fields.  The other issue is assigned to @szymczdm, but you should be able to address this one by creating BibTeX entries for each of the URLs and then citing them.

**Comment by halonazhao** [comment]
I just found that I solved this issue. Can I close this one? @smiths

**Comment by smiths** [comment]
Please add a link to the commit that closes this issue.
