### ISSUE TITLE
Apply Grounded Theory to Building Module Guide Generator

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#430]
If you cannot find a good on-line overview,  you should ask @JacquesCarette for direction.

**Comment by smiths** [comment]
Related to issue #417.  We discussed on Feb 28 "all hands meeting" and agreed that the first step is "manually" writing a sketch of a simple design document for one of our case studies.  Probably GlassBR.

**Comment by JacquesCarette** [comment]
And was with #417, closing and relegating to wiki.
