### ISSUE TITLE
IM4 Equation SSP

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#433]
In IM4, there should be two seperate eqution in stable version. And after IM4 the equation part has the same problem which also make the number of equation wrong. I think the stable version should be changed. P35

**Comment by szymczdm** [comment]
@smiths will look at it and correct Manual to make something more readable.

**Comment by szymczdm** [comment]
The derivation for Rigid Finite Element Displacement may need to be deleted as well, so @smiths will look into it as well.

**Comment by smiths** [comment]
At present the best way to fix this example is to simply remove the rigid finite element portions of the documentation.  At this time, it isn't worth the effort to fix these parts of the specification.  An issue for the first step of updating the manual version of the SRS is given in the Case Studies repo:

https://github.com/smiths/caseStudies/issues/24
