### ISSUE TITLE
Functional Requirement Reference SSP

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#435]
R1, R3 in manual version have references, but not in stable version. Should reference be kept? P39

**Comment by smiths** [comment]
Once references are working the stable version will be updated to include this information.

**Comment by samm82** [comment]
@halonazhao You should be able to go ahead with this now.

**Comment by halonazhao** [comment]
@samm82 Thanks!

**Comment by smiths** [comment]
@halonazhao, @bmaclach is currently working through the SRS for SSP as part of his CAS 741 course.  The SSP example had some major flaws and we are taking this opportunity to fix it.  @bmaclach still needs to figure out how best to change SSP.  We aren't done yet.  For your purposes, we should just make those changes that break the cycles.  The other changes will have to follow later.

**Comment by halonazhao** [comment]
These references have been added back since after chunk rearrangement, cyclic importing issue no longer exists. The only problem would be SSP is still missing some chunks in drasil and they need to be gradually added. I will open an issue for @bmaclach so that he can take over. Is this ok @smiths ?

**Comment by smiths** [comment]
@halonazhao, yes, your proposal to have @bmaclach add the chunks makes sense.  He will be modifying ssp anyway in his efforts to update the SRS.
