### ISSUE TITLE
Functional Requirement Missing Information? SSP

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#436]
R8, R10, R11 have more information in manual version than in stable version?

**Comment by smiths** [comment]
@smiths will look at whether the RFEM can be removed from the manual version.

**Comment by JacquesCarette** [comment]
Looks to be linked to #434 ?

**Comment by smiths** [comment]
@bmaclach did a thorough fix of ssp.  We can certainly review this work at some point, but this issue has no useful information for future reviews of ssp.  The new version is much better than the version these comments were based on.  We can close this issue.  We can also close #434.
