### ISSUE TITLE
IM in manual version keeps more information SWHS

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#438]
All IM in manual version keep the constraint information in output part. Should them be remove? P18

**Comment by niazim3** [comment]
@halonazhao Does this issue close with the merge of the yuzhi branch?

**Comment by halonazhao** [comment]
No. There are still some statements for output and input missing.

**Comment by halonazhao** [comment]
This is a redundant issue to #523. I will close this one.
