### ISSUE TITLE
Functional Requirements In Manual Have More Information SWHS

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#439]
R5, R6 in manual have more information than stable version. Should I keep them? P25

**Comment by smiths** [comment]
Manual should be updated in the description field so that phi is defined as the melt fraction, like it is in the stable version.  @szymczdm is trying to fix the stable version label for this DD so that it matches the manual label (melt fraction).

**Comment by smiths** [comment]
Stable version should be made to match the manual version.

**Comment by halonazhao** [comment]
Am I also able to modify stable version?

**Comment by smiths** [comment]
You should hold off on updating the stable version for now.  We are waiting for @szymczdm to get referencing working.

**Comment by samm82** [comment]
I'm going to tackle this as part of #1281, so I'm closing this.
