### ISSUE TITLE
Should tables be decomposed? SSP

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#440]
In the most original manual version DD5 had both two angle equations. But in stable version, they were decomposed and with the same lable. P19

DD6 Lengths was decomposed to 3 tables in stable version.

DD12 was decomposed to 2 tables labeled 'pressure'. And do have to keep the vector format? P22

**Comment by szymczdm** [comment]
Manual needs to be updated, this is an issue for the case studies repository.

@halonazhao Can you please ensure an issue is created in the other repository and link to it here. You'll also need an issue for making more meaningful titles (ie. for "Angle").

**Comment by niazim3** [comment]
Can this issue be closed?

**Comment by halonazhao** [comment]
Tables were split but the names still have problem.

**Comment by smiths** [comment]
Since the issue about the names is for the case study version, was an issue created (as mentioned above) in the case study?  An issue from the case study can be linked here, and then this issue can be closed here.

**Comment by halonazhao** [comment]
Just checked Brooks branch 
 https://github.com/smiths/caseStudies/blob/ssp_SRSMajorRevisions/CaseStudies/ssp/docs/SRS/SRS.pdf.
 In this branch, all the issues mentioned before no longer exist. So this can be closed now.
