### ISSUE TITLE
Fix implementation choice for library vs. executable

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/Drasil#443]
There is currently a choice option for generating a library or a executable, but the choice doesn't actually do anything.  Right now the generated code is always for an executable program.

This will require additions to the makefile generator so that we can generate makefiles that either build a library or executable depending on the choice.

**Comment by bmaclach** [comment]
As stated above, everything we have currently is for generating an executable. To add the option of generating a library, we'll need to update the Makefile generator and code generator accordingly. 

For the Makefile generator, the `BuildConfig` for each language will need to be different depending on if we are generating an executable or library. We can update our `getBuildConfig` function to take an `ImplementationType` (this type already exists and is either `Library` or `Program`, and is present already in our `Choices` structure) in addition to a `Lang`, and return the correct `BuildConfig` based on both. The "run" rule will not be needed for libraries. I'm not entirely sure what the format should be for libraries in our different target languages. My guesses are:
- Java: .jar
- C# and C++: .dll
- Python: .py (i.e. do nothing to the source files?)

For the code generator, my understanding of the difference between a `Program` and `Library` is as follows. The general flow of all `Program`s is "accept input -> calculate -> return output". This flow is driven by a main function. For a `Library`, the input and output steps are dropped, and there is no main function. All a `Library` would do is offer functions for performing calculations. If that's right, then writing the code generator for a `Library` is just a matter of defining a path through our existing code generator that skips over the input, output, and control portions of the code.

**Comment by smiths** [comment]
Great to see you looking at this @bmaclach.  It would be nice to be able to generate libraries.  In my way of thinking, just having the code, without a main, gives us an uncompiled library.  We could have a library of input functions, or output functions, so I don't think we want to exclude those from the generated code.

The makefile could be used to create the compiled binaries of the libraries, which would then be available for other programs to link to.  For C++ (and I think C#), you would want an object file (*.o) on a Unix style OS.

**Comment by Mornix** [comment]
For Python, maybe generate the metadata needed to package as a [wheel](https://www.python.org/dev/peps/pep-0427/)? (I skimmed the format, but it's what's used when publishing packages on PyPi.)
The OS shared library extensions are Windows (`.dll`), macOS (`.dylib`), and Linux (`.so`). Just as documentation you come across for compiler flags may refer to them with these different extensions. 

As far as I can tell the makefile infrastructure needed to alter the makefiles should already be in place.

**Comment by JacquesCarette** [comment]
Perfect.  For generating a library, API documentation will be quite necessary. But that should all be part of the infrastructure. And previous comments added some nice clarifications.
