### ISSUE TITLE
Ensure issues with stable versions are resolved

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#445]
The case studies repo (https://github.com/smiths/caseStudies/issues) has identified multiple issues that will require updates to stable.  This issue can be closed when the related issues in the case studies repo have been closed.

**Comment by JacquesCarette** [comment]
Unfortunately the issues on the case studies repo have multiplied, and it is no longer clear which of those issues need to be updated before this can be closed. So this issue is now a 'bad' issue. I will re-assign ownership accordingly.

**Comment by smiths** [comment]
Nearly all, if not all, of the issues in the case studies repo can be closed.  They are from reviews done during CAS 741 last year.  Not everyone was comfortable with closing issues.  :-)  Regardless, the maintenance of the examples has now almost completely switched to the Drasil versions.  The one hold out is the game physics example, since @oluowoj has not yet finished porting the changes we discussed in 741 to the Drasil version.

I will close this issue now.  I'll eventually get through all of the issues in the case studies repo.  If any of them are an issue that also applies to stable, I will create a new issue in the Drasil repo.
