### ISSUE TITLE
Update GlassBR to use new TheoryModel, GenDefn, and InstanceModel Chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#446]
As we discussed, create a new branch from mine (Definitions) and work on converting the rest of the theoretical models, instance models, and general definitions to the new chunk types.

Then, update the mkSRS "program" to use these new chunks.

Double check that the changes don't lose any information in the generated versions (compared to stable).

**Comment by JacquesCarette** [comment]
This is as done as it's going to get.
