### ISSUE TITLE
Update NoPCM to use the new TheoryModel, GenDefn, and InstanceModel chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#447]
As we discussed, create a new branch from mine (Definitions) and work on converting the rest of the theoretical models, instance models, and general definitions to the new chunk types.

Then, update the mkSRS "program" to use these new chunks.

Double check that the changes don't lose any (more) information in the generated versions (compared to stable).

**Comment by halonazhao** [comment]
Hello @szymczdm,
I just added the new chunk of theory model into the nopcm case. I am not sure whether I am on the right track. Can you take a look at it? There are two ignored errors making the build break, but I think they have nothing to do with the new Theory Model I just added. Because before I added the new TM and after I uncomment the SSD section, there were already two ignored errors there.
Thanks.

**Comment by szymczdm** [comment]
Just took a look. 

The code you uncommented was the "Specific System Description" section, but it isn't currently complete (whereas the version you replaced was more complete). The errors you're seeing (particularly the error in NoPCM) is because there are pieces of that section missing. If you want to see what I mean, open up stable/nopcm/NoPCM_SRS.html and compare it to build/NoPCM/Website/NoPCM_SRS.html

You'll see that under "Specific System Description" the "Assumptions" subsection is missing from the build version! Also, you'll see that the theoretical model now looks much nicer. There are other pieces missing, since they weren't implemented when that first (commented out) piece of code was written.

Overall, the errors here are expected and it's good to see that the TM is working. We'll need to add in the missing sections to the SSDSec program to clear up some of the issues, as well as update stable to use the new (better!) TM.

**Comment by halonazhao** [comment]
@szymczdm 
I think TMs, GenDefs, IMs and DDs are all working now. I am not sure what I did is we expected. Can u check for a bit? Also, the IMs may have some problem. The input part is having some printing issues and the new instance model chunks do not actually match the stable version, so I leave the input and output constraints empty. I'm not sure what proper content is expected to show in those session.

**Comment by halonazhao** [comment]
According to #507 #506 #505 #504 #497, updates can not be done so far.

**Comment by halonazhao** [comment]
The changes related to this issue mostly have been done. All issues related to this issue have been open. Can I close this issue or wait until that branch merged in? @szymczdm

**Comment by szymczdm** [comment]
If the example has been fully updated to use the new chunks, I think we can close this issue. The other issues with generation will still need to be fixed, but this issue appears to be done.

**Comment by halonazhao** [comment]
This issue has been solved.
