### ISSUE TITLE
foo.txt

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#454]
This was a note that was left on my board as an issue to assign to @palmerst.  To be honest, I'm not sure what it means.  😄 Is it something to do with a variable type for strings?  This might job the memor of @JacquesCarette or @szymczdm.  If nobody remembers, we can just close this issue and wait for it to come up again.

**Comment by JacquesCarette** [comment]
Yes, we need to extend `Expr` to have a case for `String`.  Or at least, that's what seems to be going on.

One might also consider that `Expr` shouldn't have `FCall` at all, and that that should be just in `Code`, which would eliminate the need for such a hack.

**Comment by JacquesCarette** [comment]
`Expr` does have a `String` case, so this is kind of moot.  The other issue (`FCall`) will come up again when we get back to more code generation.  So I'm closing this one.
