### ISSUE TITLE
Remove use of variable in compound symbols

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#455]
Hi Dan.  If I remember correct, we had an issue with variables being introduced just so that they could be displayed in a compound symbol, like Kmin.  You may have already dealt with this.

**Comment by JacquesCarette** [comment]
I believe that I removed a couple of those already.  Not sure if there are any left...

**Comment by szymczdm** [comment]
There are still a couple in SSP's IMods which I need to look at, and one being used by a Util (??) function (Data.Drasil.Utils), which should probably be changed to an error (again, I need to take a slightly longer look at it). Otherwise I think the rest have disappeared.

**Comment by JacquesCarette** [comment]
When do you expect to be able to do this? It doesn't feel like it should take very long.

**Comment by szymczdm** [comment]
Forgot about it and didn't check the issue tracker in the last couple days. Sorry! I'll get that done on master so we can close this issue.
