### ISSUE TITLE
Find cases where grouping is used in expressions 

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#457]
Find the cases (examples) where grouping is explicitly used in Drasil expressions.

**Comment by JacquesCarette** [comment]
- All 8 uses in `GlassBR.DataDefs` were not needed -- deleted.
- All 3 uses in `GlassBR.Unitals` were not only not needed, deleting them improved the display.
- The use in `SSP.IMods` for `fosFracSum` was really not needed either -- deleted.
- The uses in `SSP.IMods` for the two different `normToShear` were needed, as they meant something; these are now hacked.  They are easy to tell as they contain the phrase `SpencerFixme` in them!

**Comment by bmaclach** [comment]
Note that another case of explicit grouping arose in SSP as part of PR #1097. It is currently marked with a FIXME.

**Comment by JacquesCarette** [comment]
You should also open an issue (and refer to the specific line of code with the fixme) for this.
