### ISSUE TITLE
Explore meaning of groupings

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#458]
Determine the meaning of the groupings found in issue #457.  Is there useful information being captured with the grouping?  How else could we express it?

**Comment by JacquesCarette** [comment]
So this is now high priority, because I have hacked 4 uses of grouping (to use intermediate variables) in a horrible way.  This 'breaks' SSP.  I've documented the breaks in #457.

**Comment by JacquesCarette** [comment]
This issue is now moot.  It might arise again later, but having this one open doesn't serve as useful purpose.
