### ISSUE TITLE
Excluding a section from the section numbering

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/Drasil#46]
In the TeX file for my manual SRS,  `\subsubsection*` is used to initialize the derivation sections, so that they can be a separate section with a title, but do not count towards the section numbering. Is there a way for this to be implemented in Drasil? 

I can't just make a new Section object for them currently, because they would need to be a subsubsubsection, which isn't possible.

**Comment by njericha** [comment]
subsubsubsection 's would be possible now that we have wrappers for sections that use `SRS.sectionName [] [SUBSECTIONS HERE]` so you could in theory have as many sub's as needed.

**Comment by njericha** [comment]
I think I miss understood the question. They DON'T want this section counted, but still be a subsection with a heading.

**Comment by smiths** [comment]
Having a section heading without a number is not the real issue here.  The important issue #409 is being able to associate derivation information with a chunk.  Once we address issue $409, we should be able to determine how to best generate a view of the quantity and the associated derivation.  Once we do this, we can also close this issue.

**Comment by szymczdm** [comment]
#409 is closed, but there hasn't been a decision on how the derivation should be rendered yet. Currently it's just a paragraph following the model/definition. Once we've decided what to do and I've updated it, I'll close this issue.

**Comment by szymczdm** [comment]
I believe as per a discussion in a previous meeting we've decided to leave the derivations rendering as paragraphs following the model/definition. @smiths do you have any preference on whether we should have a 'phantom section' or leave it as-is?

**Comment by smiths** [comment]
@szymczdm, I'm fine with things as they are.  I don't see a need for a phantom section for the derivation.  However, I'm not sure exactly what the advantage of a so-called phantom section would be, so maybe I am missing something here.

**Comment by JacquesCarette** [comment]
Note that `\subsubsubsection` is usually spelled `\paragraph` in latex -- and that's what pandoc does when trying to go that many levels deep.

**Comment by szymczdm** [comment]
So would we like to ignore `\subsubsubsection` (as we presently do) or transform it to `\paragraph`?

**Comment by JacquesCarette** [comment]
Transform it. At least, we can try it and see.

**Comment by szymczdm** [comment]
Apparently that's been done since 64f5374a863626f63 (in the tex).

**Comment by JacquesCarette** [comment]
I'm sure you're right that it's done, but the check-in you point to doesn't seem to have anything related to that in it.  Oh well.

**Comment by szymczdm** [comment]
ctrl-f "genSec" in that commit. It's where it was introduced, but there was no mention of it.

**Comment by JacquesCarette** [comment]
Thanks, I missed that, must have scrolled too fast.
