### ISSUE TITLE
DocumentLanguage.Chunk.InstanceModels

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#460]
Why is this in `Examples`, under `DocumentLanguage`? This belongs in `Language.Drasil` !

**Comment by JacquesCarette** [comment]
Same for `GenDefn`. I cannot think of good reasons to define new chunk types in example infrastructure.

**Comment by szymczdm** [comment]
Fixed it. That was a relic from back when I first started trying to move over to the new DocumentLanguage.Definitions and was using some imports from DocumentLanguage. Those imports were deprecated, so all is good.
