### ISSUE TITLE
Fix printing of 'Body a' to 'Body A' in gamephysics

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#461]
As part of the changes made for #452, game physics now has 'a' instead of 'A' in a number of places when referring to a body. This is likely due to that 'A' being part of a compound NounPhrase and not being capitalized as expected. Note: NounPhrases don't allow us to use symbols, however, this A really seems like it should be a symbol.

**Comment by JacquesCarette** [comment]
@szymczdm this is probably an issue that can be re-assigned. However, the description is not good enough to do so. "in a number of places" is too vague. If we knew exactly which ones were the problematic ones, someone else could investigate.

**Comment by szymczdm** [comment]
It seems to only be happening in the table of symbols at the moment, so there's something being done differently between the printing there vs. in the data defs /tms/gds/ims. Specific locations shown below.

![a1](https://user-images.githubusercontent.com/235140/48319654-58cb0280-e5de-11e8-91cc-8e6d4623d6e3.PNG)
![a2](https://user-images.githubusercontent.com/235140/48319655-58cb0280-e5de-11e8-992b-4f7d4a0a0459.PNG)
![a3](https://user-images.githubusercontent.com/235140/48319656-58cb0280-e5de-11e8-8853-db9ea4aa54ce.PNG)

**Comment by JacquesCarette** [comment]
This was a really subtle bug in the capitalization routines.  It is fixed in 476eb8114 in branch QDef-in-InstMod, which is going to be made into a PR soon (there are some oddities outstanding).

**Comment by JacquesCarette** [comment]
That whole branch was not merged, but this fix was.
