### ISSUE TITLE
Unit should be split into IsUnit and HasUnit

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#465]

**Comment by JacquesCarette** [comment]
Well, I ended up doing |IsUnit| and |HasUnitSymbol|, but this is done. Took about 35 minutes, of which close to 10 was spent waiting for compiles.  So not bad at all!

**Comment by JacquesCarette** [comment]
Should have also said - commit 0b9db065.

**Comment by smiths** [comment]
Great!  Out of curiosity I timed how long a clean build takes and it was about 3 minutes on my laptop.

**Comment by JacquesCarette** [comment]
3m42s of real time on my Mac Air.
