### ISSUE TITLE
Double-check and fix citation printing

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#466]
As mentioned in commit 2d7da501a53b1c463ff32f57300c1b90e47b9811 stable has been updated with the new citation printing, but it has not been checked for accuracy (some fields may be missing and/or some citations may be printing according to the wrong style).

This mainly affects the HTML, as the TeX all use BibTeX items which *should* be correct. Wouldn't hurt to double-check those as well.

**Comment by smiths** [comment]
I haven't noticed any specific problems with the citations, but I also haven't really reviewed many of them.  I'm thinking that I might ask my CAS 741 students to review the Drasil example output and create issues for problems that they notice.  This would familiarize the students with the examples, and it would help them learn about GitHub.

I wonder if we can close this issue?  Unless we want to assign someone the specific task of checking the citations?

**Comment by JacquesCarette** [comment]
I haven't noticed anything weird with the HTML citations, so I think this can be closed.
