### ISSUE TITLE
HTML Assumptions/Requirements/etc. cannot print as properly numbered list without using hacks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#470]
As of testing with commit 10a01a289c8624968c3526e4fa542ff8f0a69a6e I have determined there is no easy way to create a numbered list of assumptions/reqs/etc. in the HTML builds without hacks. I'm not going to hack it in (since that's what I've been trying to remove -- acroNumGen), so for the time being I'm going to adjust stable as necessary for this one and comment here any time I make similar un-hacks to the (now wrong) stable version.

Since Assumptions/Reqs/etc. are handled too deeply in Document, it's currently not possible to pull their numbers from the reference database when rendering them. The fix seems pretty straightforward: remove ALUR... from Document and have it as part of DocumentLanguage (our SmithEtAl. SRS template) or wherever else it would make sense. That seems like something that can wait until the current referencing fixes are fully merged into master.

**Comment by Mornix** [comment]
The proposal in #562 aims to address this issue.

**Comment by Mornix** [comment]
Yup. This is done. ALUR no longer exists and rendering of ConceptInstance is quite flexible. Closing.
