### ISSUE TITLE
SWHS IM3 has unsatisfiable constraint

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#471]
`0 < temp_W < 0`.  What should it be?

**Comment by JacquesCarette** [comment]
Turns out `temp_W` is a temperature (doh!), and in celsius, so the upper bound should be `100`. And I was editing that for other reasons, figured it out, and so fixed it.  Lucky Spencer!

**Comment by smiths** [comment]
Thanks Jacques!
