### ISSUE TITLE
The Right Constructor For "MINFRAC"

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#474]

**Comment by szymczdm** [comment]
Can you please point me to where this is defined (and has it been pushed?)

After looking through the constructors, it appears the right one would be `makeVC` (which, of course, would mean changing the type signature of the minfrac chunk and moving it into a different list of chunks).

**Comment by szymczdm** [comment]
@halonazhao did my previous comment help? I'm going to re-assign this to you and we can go from there.

**Comment by halonazhao** [comment]
Issue has been solved in e9a0fffe0913268fd194de8e4b8858e7761898a9
