### ISSUE TITLE
Setting up Drasil documentation/test infrastructure

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#475]
[This is really a task that should be done with the summer students, but before I forget it, I will create an issue and assign it to Steven as a means to tracking this.]

We need to improve what we do with respect to examples and tests for Drasil. This was prompted by seeing the thread
https://www.reddit.com/r/haskell/comments/84mirm/recommended_way_of_documenting_examples/
on how it is done for Haskell/Cabal/Stackage packages.

The interesting thing about this is that it could be used at two levels, both for Drasil itself, and for Drasil-generated code.

**Comment by JacquesCarette** [comment]
@Mornix implement this, and much more.

**Comment by smiths** [comment]
Yes, @Mornix more than satisfied this issue.
