### ISSUE TITLE
HTML table hack for big operators

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#478]
Right now, the HTML headers reference MathJax, but I don't think we actually use it.  Which seems like a silly state of affairs.

Even sillier is that absolutely horrendous hack in the HTML printer for rendering sums and integrals -- tables are used. Yes, it works.  But it just doesn't seem worth it.

**Comment by JacquesCarette** [comment]
As with #477, I was hoping to get @smiths and @szymczdm 's comments before proceeding.  Removing hacks is one thing, committing to certain technologies is another.

**Comment by smiths** [comment]
I don't really have an opinion on this one.  All I know about MathJax is what I learned in the last couple of minutes looking at the MathJax web-site.  The quality of the renderings are great, but if we aren't using it, then it seems like we shouldn't be complicating matters at this time.  Maybe MathJax is something we could investigate moving toward in the future, but right now I don't see a reason to keep it.  However, @szymczdm will have a much more informed opinion than me.

**Comment by JacquesCarette** [comment]
The flipside is that out sums, products, integrals and square roots look pretty ugly, are hacks, and are likely to get worse.

I've done some more investigations, and it seems that the rest of the world is adopting MathJax.  Which, in some ways, will actually simplify things for us, as it would mean a single back-end for everything from `Expr` below!

**Comment by szymczdm** [comment]
I think MathJax is the way we should be going (and probably should have started the transition a while ago). It's quite a bit better than the current HTML hacks. Not to mention, any change to the css could break the current styling output.

**Comment by JacquesCarette** [comment]
Makes sense.  So I'll move things in that direction.  I will keep the option of going to 'raw' HTML, but not try to make it look good.

It will require quite a bit of work to get there. In some weird sense, some of the hardest parts will be to keep ensuring that our test output isn't broken. This is because a lot of these refactorings will cause a lot of changes to the output, and it would be easy to hide a breaking change in there.  So I'll proceed very incrementally. I will remove hacks, one by one, as a first step.

**Comment by JacquesCarette** [comment]
The table hack is gone.  Closing this one.  Will open a new one for MathJax.
