### ISSUE TITLE
Should move from raw HTML to MathJax for embedded math

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#479]
See #478 for most of the discussion on this topic.

**Comment by JacquesCarette** [comment]
Put in as low priority, as the current HTML is ok.

**Comment by JacquesCarette** [comment]
We'd already discussed this in #300. And should keep #412 in mind too.

**Comment by JacquesCarette** [comment]
@danscime can you check that all of the examples use MathJax as the default?  If so, then close this issue.

**Comment by danscime** [comment]
All 6 examples have this line in the HTML files. 

<img width="546" alt="Screen Shot 2019-05-21 at 8 35 36 AM" src="https://user-images.githubusercontent.com/28261339/58097529-a20b9880-7ba5-11e9-93c2-3ef61b6307b1.png">

**Comment by JacquesCarette** [comment]
That doesn't mean it uses it, unfortunately!  We added that to all examples very early, as it is relatively harmless to do so. You have to look both inside the html file to find some latex, and look in the example's configuration settings to make sure it uses the MathJax option.

**Comment by danscime** [comment]
I did a search through the files. No use in any files for `\`, `$`, or `$$` which seem to be most commonly used characters for MathJax.

And for the config settings, the .css files did not have anything resembling or mentioning Latex or MathJax.

**Comment by JacquesCarette** [comment]
Right, so this is not fixed at all. I guess it will make sense to do this after the current pass on indenting is done. Re-assigning.

**Comment by danscime** [comment]
As a test (on Tiny).

Before:
<img width="744" alt="Screen Shot 2019-06-06 at 9 15 10 AM" src="https://user-images.githubusercontent.com/28261339/59035646-b608f880-883b-11e9-92c8-d0d385d078d6.png">

Changing one equation to use Latex symbols:
<img width="739" alt="Screen Shot 2019-06-06 at 9 15 53 AM" src="https://user-images.githubusercontent.com/28261339/59035710-dafd6b80-883b-11e9-82bb-89ab3d83bbeb.png">

Changes from 9d537cec77382ea03778974207862a3f87f64999

**Comment by smiths** [comment]
The second version of the table definitely looks nicer than the first.  Great!

**Comment by danscime** [comment]
Adding displayed equations.

Before:
<img width="661" alt="Screen Shot 2019-06-06 at 9 59 21 AM" src="https://user-images.githubusercontent.com/28261339/59039023-071beb00-8842-11e9-93f7-914b68603feb.png">

After adding `displayMath` option:
<img width="642" alt="Screen Shot 2019-06-06 at 9 59 33 AM" src="https://user-images.githubusercontent.com/28261339/59039056-1a2ebb00-8842-11e9-9223-d183511ac1a2.png">


Changes from 3213be893fc758c40fb9ddb67b1554dfb2a8029e

**Comment by smiths** [comment]
I like the fonts for the second example better, but the left justification (from the first example) looks better than the centre justification in the second (in my opinion).  How hard would it be to left justify the second case?  (This is a minor request; I wouldn't want to block progress for such a simple formatting suggestion.)

**Comment by danscime** [comment]
Left justified / inline:
<img width="642" alt="Screen Shot 2019-06-06 at 9 59 33 AM" src="https://user-images.githubusercontent.com/28261339/59039570-118ab480-8843-11e9-8305-b65ef1115efb.png">

Left justified makes the font smaller not sure exactly why. But from what I know so far, equations can be `inline` with surrounding text or `displayed` to be a separate entity.

**Comment by danscime** [comment]
The tex also has this equation displayed / centered.
<img width="711" alt="Screen Shot 2019-06-06 at 10 12 16 AM" src="https://user-images.githubusercontent.com/28261339/59039881-a4c3ea00-8843-11e9-8596-e72037a595d1.png">

**Comment by smiths** [comment]
It isn't a big deal, but one looks in-line in tex with `$ $`.  While the other looks like a full equation, using `$$ $$`.

**Comment by danscime** [comment]
You're right, source code for the Tex displays the Units part inline and equation part as displayed.

I feel like the end goal would be to use whatever prints the math in Tex to be used for HTML, so the HTML would follow whatever Tex does in terms of which parts are inline vs. displayed.

So I think I should base the HTML off of the Tex for now. And then once automated, we can change the formatting if we decide to.

**Comment by smiths** [comment]
Sounds like a good plan.  :smile:

**Comment by danscime** [comment]
Tiny stable fully updated via c95cdf0753d85b6f552ad722c094c848ab992929

**Comment by danscime** [comment]
As of 76418b9f13b85c114524a9a6fb3594860678d091, I believe I have made all necessary changes on my [beginMathJax branch](https://github.com/JacquesCarette/Drasil/tree/beginMathJax) in order to have expressions and units display as embedded Latex.

These cause significant changes to the HTML files. So I will go through the stable changes.

@smiths @JacquesCarette what should be the workflow?
Should I check through each diff to make sure nothing unexpected has occurred? And just cautiously make my way through each example?

**Comment by JacquesCarette** [comment]
See my comments on the commits on that branch.  But that won't actually affect the HTML files themselves.

Yes, you'll have to go through them carefully. Start with the smaller ones - if there's something weird, it's likely pervasive and will already show up there.  You can also turn on MathJax example-by-example (right?), so that these can be incorporated into stable incrementally.

**Comment by danscime** [comment]
@JacquesCarette currently, the way it is set up, it affects all examples. If in the future, we want to have the ability to switch, then I could look into it. But if the end goal is to only have MathJax (which it seems like it should be), then it may not be worth looking into. In this case, there will be a big PR with many merges to master.

So far I am almost done Projectile and have not noticed anything unexpected.

**Comment by JacquesCarette** [comment]
I had asked Devi to have an option for that, which he did implement, to funnel that option around.

**Comment by danscime** [comment]
@JacquesCarette I am not sure where this is.

I have changed the actual functions in HTML/Print.hs. I would probably need to keep the original functions and create new functions with mathJax abilities, and then this option would choose which functions to use I suppose.

**Comment by JacquesCarette** [comment]
It was in a branch of his. It might have gotten deleted, I'm not sure.

I don't think there's a need for copying anything. Yes, the original functions will need to be kept, and then the option would choose which ones to call.

**Comment by danscime** [comment]
@JacquesCarette I will look to try to find something he may have created.

**Comment by danscime** [comment]
Currently, I have updated Projectile HTML. Mathjax right now is only being used for:
- displayed math equations
- fractions
- square roots
- matrices
- cases

These changes can be found in this [compare](https://github.com/JacquesCarette/Drasil/compare/be2283f..704d779).

**Comment by JacquesCarette** [comment]
We might eventually want to have fractions in mathjax too - but otherwise, this looks good.

**Comment by danscime** [comment]
Fractions are being implemented in mathjax. Did you mean something else?

**Comment by JacquesCarette** [comment]
I saw some fractions in HTML. Maybe just for units? Which I think is fine.

**Comment by danscime** [comment]
Oh yes, that’s exactly it

**Comment by danscime** [comment]
One minor issue, should be a trivial fix.

In some equations, a less than symbol `<` with a letter beside it seems to make the HTML think it is starting a tag.
<img width="506" alt="Screen Shot 2019-08-12 at 9 55 11 AM" src="https://user-images.githubusercontent.com/28261339/62870350-84068d80-bce7-11e9-947c-33ad83cf7c05.png">

Renders this:
<img width="352" alt="Screen Shot 2019-08-12 at 9 55 36 AM" src="https://user-images.githubusercontent.com/28261339/62870463-aef0e180-bce7-11e9-937d-79608625418e.png">

**Comment by JacquesCarette** [comment]
We need to figure out how to "properly" embed latex in html.  My guess is that the easiest way to do that is to always use `\lt` (and `\leq` and ...) in the latex instead of ever putting out a `<` or even a `>`.

**Comment by smiths** [comment]
@danscime, I did a bit of googling on this.  Can you define new commands for `\lt` and `\gt` in the generated tex files?

https://tex.stackexchange.com/questions/12519/what-library-do-i-have-to-use-such-that-the-document-can-render-lt-and-gt-as-l

**Comment by danscime** [comment]
@smiths that seems to work! I will begin to implement.

**Comment by JacquesCarette** [comment]
Note that the proper macros should be
```latex
\newcommand{\lt}{\ensuremath <}
\newcommand{\gt}{\ensuremath >}
```

**Comment by JacquesCarette** [comment]
And `\leq` and `\geq` already work as is, so not need to define those.

**Comment by JacquesCarette** [comment]
I note that the mathjax documentation http://docs.mathjax.org/en/latest/tex.html says we should use `\(...\)` for inline math (rather than `$...$`) and `\[..\]` for displayed (rather than `$$...$$`).

Further down that same page, it has advice regarding < and > .

**Comment by danscime** [comment]
I will make these changes.
