### ISSUE TITLE
Remove Greek from Unicode

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#481]
As we discussed, each of the Greek character constructors (Alpha_L, Alpha, etc.) in Unicode need to be removed, and all instances of their use need to be replaced with the appropriate unicode character. For example Alpha_L will be replaced by "α" wherever it appears. There might be some type mismatches that occur which you'll need to fix.

This should be done one character at a time. After you've removed each one, ensure you test the result. If it's all good, update the stable output. Only after that should you be committing the changes to the new branch.

Once all of these characters have been updated, please file a pull request and link it with this issue.

If you have any questions, please post them here.

**Comment by deviprasad135** [comment]
Closing this issue as per #533
