### ISSUE TITLE
The Type of the Assumptions Causes Many Redundant Code

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#484]
There is one case that Assumptions section has to take the type of " [AssumpChunk] " whose content has to be built using the constructor " ac' ".
ac' :: String -> Sentence -> AssumpChunk

There are some other case that we have to use the same string and Sentence information to produce a "content" type.  

mkAssump :: String -> Sentence -> Contents
mkAssump i desc = Assumption $ ac' i desc

So to produce a "content" type assumption used the exactly the same information by building AssumpChunk. Can we change the mkAssump to be like something like:

mkAssump :: AssumpChunk -> Contents ?

@szymczdm

**Comment by szymczdm** [comment]
That sounds perfectly reasonable. It actually makes more sense!

**Comment by JacquesCarette** [comment]
The details on what the problem's core source is good. I would have liked an explicit example on top of that (some specific source file and line numbers where we can see the duplication). That would indeed make it easier to figure out what the next steps should be.

**Comment by halonazhao** [comment]
I've added the new assumptions at type AssumpChunk in the [Assumption file of SWHS](https://github.com/JacquesCarette/Drasil/blob/yuzhi/code/Example/Drasil/SWHS/Assumptions.hs), line 44. The other group of assumptions at type "contents"are defined in the same file starting from line 163.

The assumptions at type AssumpChunk are used in the [Body file of SWHS](https://github.com/JacquesCarette/Drasil/blob/yuzhi/code/Example/Drasil/SWHS/Body.hs#L121) and swhsRefDB is offering the internal reference to Assumptions of SSD section at Line 159.

The assumptions at type contents are used in the [Body file of SWHS](https://github.com/JacquesCarette/Drasil/blob/yuzhi/code/Example/Drasil/SWHS/Body.hs), at Line 451, 461, 1408 and etc.

The duplication is the whole bunch of repeated sentences in two different type definitions for assumption.

**Comment by JacquesCarette** [comment]
Thank you.

**Comment by JacquesCarette** [comment]
So lines 451 and 461 both re-use previous definitions. So I don't quite understand the duplication.  That there is duplication in the resulting document is expected.  What we worry about is duplication in the Drasil source.

**Comment by szymczdm** [comment]
This issue (at least the initial part of it) does not exist on master. As mentioned in my last comment on a different issue, we need to get the yuzhi branch up to date ASAP and then figure out if there is still a problem here. For example, the master branch already removed the mkAssump constructor, as well as ac and ac', creating `assump` in their stead.

**Comment by halonazhao** [comment]
Thank you. I think that I really need to merge too. After merging, for sure, there are many works needed to re-done.

**Comment by halonazhao** [comment]
I have merged master into my branch and this problem is solved in https://github.com/JacquesCarette/Drasil/commit/1d835d2f05a5c7a894ebc326dca9506728ffb709. I will close this issue.
