### ISSUE TITLE
Minor Problem with the CSS

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#489]
When I scale the web window, there would be overlapping of a paragraph as in the snipshot. And I noticed that that paragraph is controlled by "display: block", which doesn't do automatically changing lines properly. Probably not using CSS display and maybe using "br" or "div" manually blocking that paragraph out would be nicer. What do you guys think? 

![screen shot 2018-05-03 at 17 16 47](https://user-images.githubusercontent.com/28347043/39603305-dd354e7a-4ef5-11e8-8ece-1937ceb99677.png)

**Comment by JacquesCarette** [comment]
Yes, I think the generated HTML here is trying to be too clever, and fails. I am meta-assigning this to @szymczdm who needs to figure out who to assign this to.

Also, it's odd that there are some &lt;em&gt; and &lt;sub&gt; tags showing up above. That seems like a bug as well.

**Comment by halonazhao** [comment]
Unfortunately, they are still there. 
I figured the wrong tag `<em>` is because the html ran `alt` and special tag doesn' work in `Alt`.
![screen shot 2018-11-02 at 11 21 53](https://user-images.githubusercontent.com/28347043/47924866-2a894c80-de93-11e8-9d11-8c6c9bab22b5.png)

The overlapping I can look into to see whether it is easy fix.

**Comment by halonazhao** [comment]
I figured that the caption of the figure in HTML was displayed as a paragraph in tag `<p>`.
But we can use `<figcaption>` tag directly so that the caption would change the line properly when scaling the window. I have fix that in 031a2061a13aa8b23189445c2c61737c66753f0c. If you agree with this change, I would change stable to match.

The difference would be the caption will be not bold anymore. And the caption is not centered. The center style can be controled in CSS to fix. But I didn't find where to generate the css file.  @JacquesCarette

**Comment by halonazhao** [comment]
Sure. Just did in #1038. 
And we do have `alt` text not obeying the rules and they are why the bugs occured. 

My suggestion would be generating a text specifically for `alt` since now the text for `alt` is from caption. If there are symbols in the text, the tags would cause the error. And maybe manually avoid putting symbols into the text for `alt`, because even though `<em>` can be avoided. `<sub>` is necessary for symbol printing. So I feel there is not that much we can do auto check of the text for `alt`.

**Comment by JacquesCarette** [comment]
I agree, we should be forced to generate text specifically for `alt`, and make sure that text obeys the rules. If we have such a check, then people will know what they need to fix.

**Comment by halonazhao** [comment]
As PR #1038 merged in, this issue can be closed.
