### ISSUE TITLE
Instance Model Section in the SSD probably Doesn't Plug in Properly

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#490]
I found out that the intro of IM is missing. After tracing it, I found that the problem is probably at [DocumentLanguage](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/DocumentLanguage.hs#L432) Line432. Since "SRS.inModel"  (in [SRS](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/SRS.hs#L66)) is used instead of "SSD.inModelF" (in [SSD](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/Sections/SpecificSystemDescription.hs#L177))which includes the intro section, the intro isn't plugged in properly.

@szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
Well done!  You are most likely correct.

Can you create a new branch (perhaps based on master, not your branch) where you try to fix this?

**Comment by halonazhao** [comment]
I just solved it. They are posted in the new branch called "im_modify". I also tested it in my brach and it works. The intro shows up properly.

![screen shot 2018-05-05 at 12 52 57](https://user-images.githubusercontent.com/28347043/39668780-43b72eb4-50a6-11e8-9e70-94f7dfdeb992.png)

**Comment by JacquesCarette** [comment]
Good!  Can you submit this as a Pull Request?  I want to test the process.
