### ISSUE TITLE
Is 'QDefinition' the Right Type for DataDef?

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#497]
As the DD section shows in [DocumentLanguage](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/DocumentLanguage.hs#L186), the DataDef is at 'QDefinition' type. Now, the DataDef is produced by using 'mkDataDef' defined in [Data.Drasil.Utils](https://github.com/JacquesCarette/Drasil/blob/master/code/Data/Drasil/Utils.hs#L167), which doesn't help show the Attribute: Derivation. Compare with the IM, seems the constructors 'ec' and 'aqd' together could derive the right thing, shown in [Chunk.Eq](https://github.com/JacquesCarette/Drasil/blob/master/code/Language/Drasil/Chunk/Eq.hs) Line 59 and Line 75. But the comment for 'aqd' saying that "For testing ONLY. Once all the chunks are updated for attributes this should be removed and the other constructors should be updated to include attributes". So probably the type of DataDef isn't finalized yet or there is no proper constructor for it which help show the derivation.

**Comment by JacquesCarette** [comment]
Yes, I think you have indeed spotted something which @szymczdm was working on.  I think this is mostly implemented, but needs some fine-tuning.  He should at the very least document what remains to be done on this, and then we can figure out how to get that done.

**Comment by szymczdm** [comment]
QDefinition is the right type to use here, we just need to use the appropriate constructor. If there isn't one (as yet) that includes attributes for a specific use case (for example, if we're using `fromEqn` that doesn't handle attributes properly) we'll need to either update the constructor in use, or add a new constructor until every use of the old one includes some attributes (even just an empty list).

This is pretty mechanical work to do, so I'll divide it up tomorrow morning.

**Comment by niazim3** [comment]
This is being worked on in the [adding-attributes branch](https://github.com/JacquesCarette/Drasil/tree/adding-attributes).

**Comment by halonazhao** [comment]
DataDef derivations have been plugged in. This issue can be closed now.
