### ISSUE TITLE
HTML Output Headings are Inconsistent

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#500]
As seen in the meeting earlier today, the headings in the output HTML are of different sizes (e.g. 
![image](https://user-images.githubusercontent.com/28247301/39774295-703ea524-52c8-11e8-9be0-79173b6cd0df.png)
; specifically, "Reference Material", "Introduction", "General System Description", "Specific System Description", "Requirements", "Likely Changes", "Values of Auxiliary Constants", and "References" are of smaller sizes), which causes the overall page to look inconsistent and not formal.

**Comment by Mornix** [comment]
Already fixed in [PR #499](https://github.com/JacquesCarette/Drasil/pull/499).

**Comment by JacquesCarette** [comment]
And merged.
