### ISSUE TITLE
Literature Review and Summary of Scientific Knowledge Taxonomy/Ontology

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#501]
The Drasil project would be improved by a greater understanding of how scientific knowledge is captured and classified.  Can you please start filling in information at the following wiki:

https://github.com/JacquesCarette/Drasil/wiki/Scientific-Knowledge-Taxonomy-Ontology

You can start with a literature search.  Any examples are good to start with.  Don't worry about maintaining a clear narrative.  To start with just collect all resources that are worthy of investigation.

**Comment by JacquesCarette** [comment]
Is this still a useful task? If so, for who?

**Comment by smiths** [comment]
We can close this issue.  A scientific knowledge ontology is one of the tasks listed in our potential projects wiki.
