### ISSUE TITLE
Grounded Theory Summary and Review

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#502]
The Drasil project would be improved by a greater understanding of grounded theory.  Can you please start filling in information at the following wiki:

https://github.com/JacquesCarette/Drasil/wiki/Grounded-Theory

You can start with a literature search.  Any examples are good to start with.  Don't worry about maintaining a clear narrative.  To start with just collect all resources that are worthy of investigation.

**Comment by samm82** [comment]
@smiths So what is the end goal here? I've found some resources, so should I summarize them individually or make a summary of Grounded Theory as a whole or something else?

**Comment by szymczdm** [comment]
I think individual summaries by resource are a good way to organize thoughts. I think the end goal is a more complete summary of Grounded Theory.

**Comment by samm82** [comment]
I probably should have asked this a while ago, but if I find a source, should I add it to the se4sc repo?

**Comment by smiths** [comment]
Yes,  please add any relevant sources to the se4sc repo.  When adding a resource, please also add the bibtex information.  When you add a source, please use the NatBib style of naming the citation and naming the pdf file.  For a sole author publication, the name should be the author's name and year, like Crawford2018.  If there are two authors , it should be the last author's names and year, like CrawfordAndCarette2018.  If there are more than three authors, it should be the first author followed by EtAl and the year, like CrawfordEtAl2018.  In the rare case where this does not lead to unique names, you can add an a, b, c, etc at the end of the name to distinguish them.

**Comment by samm82** [comment]
I've started a summary of Whitman2003 - do you have any specific direction you want me to go with the summaries? I'm not sure what kind of information you guys want me to find @szymczdm @smiths

**Comment by smiths** [comment]
The eventual goal is to motivate/justify/explain the design/implementation of Drasil using grounded theory.  However, we cannot go directly to this goal, since the connections will not be clear at first.  To begin with just think about this as a school report summarizing grounded theory.  Write you document like you are teaching someone grounded theory.

**Comment by smiths** [comment]
It has been a while since I reviewed the work of @samm82.  Nice to see that he collected some good references for us to base future investigations of grounded theory.  :smile:
