### ISSUE TITLE
Subsection "Properties of a Correct Solution" is missing in new SSD section

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#504]

**Comment by halonazhao** [comment]
Temporarily remove this section in stable so that the new section can match it.

**Comment by niazim3** [comment]
For now, we're currently adding the following section using `Verbatim`, but it should eventually be automatically generated like the other subsections for SSD. 
![image](https://user-images.githubusercontent.com/28247301/42581915-d67402c0-84fb-11e8-9331-a05e1b73071d.png)

Relevant lines of code are linked below for ease in implementation:
https://github.com/JacquesCarette/Drasil/blob/bf64f78be805c405da10f9aaadb88822b8e36892/code/drasil-example/Drasil/SWHS/Body.hs#L465-L485

**Comment by szymczdm** [comment]
@niazim3 Would you mind creating an issue that explicitly lists the sections which are not currently being auto-generated through DocLang (if one does not exist already)?

I know there are several that need to be auto-generated, but weren't high priority at the time it was created.
