### ISSUE TITLE
SSD Section Intro Need to be Fixed

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#505]
The Intro of SSD isn't generated properly to match stable.

[SSD](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/Sections/SpecificSystemDescription.hs#L34) Line34 is used in Line39. And `specSysDescr` is used in [DocumentLanguage](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/DocumentLanguage.hs#L397) to generate the Intro of SSD. `specSysDescr` and `intro_` may need new idea.

**Comment by halonazhao** [comment]
Temporarily match intro in stable with generated intro.

**Comment by samm82** [comment]
I'm pretty sure this has been dealt with

**Comment by smiths** [comment]
@samm82, your closing message does not instil confidence.  😄   We don't really want to close issues that we are "pretty sure" have been dealt with.  We should only close them when we are sure.

I agree that we can close it, but I think the closing message should record the reasons:
- stable now matches the generated code
- some of the links point to things that no longer exist
- changes were made in the code as described above
- the Yuzhi branch was merged
