### ISSUE TITLE
Intro of TM and DD doesn't work properly In new SSD sec

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#506]
The common part of intro in these two sections works well. But they may all need an additional tail sentence to complete the unique description part.

**Comment by halonazhao** [comment]
Temporarily match intro in stable with generated intro.

**Comment by niazim3** [comment]
What's the status of this issue? And what specifically needed to be done?

**Comment by samm82** [comment]
This has been fixed.
