### ISSUE TITLE
The Descriptions of TM, GD, IM Show Up Incompletely

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#507]
I will give an example below and other instances in TM, GD, IM may have the same issues.
The first one is from stable version:
![screen shot 2018-05-08 at 15 52 14](https://user-images.githubusercontent.com/28347043/39779672-e9588bf0-52d7-11e8-865c-c827b334f578.png)
The second one is from new SSD section:
![screen shot 2018-05-08 at 15 52 43](https://user-images.githubusercontent.com/28347043/39779678-ef33c56c-52d7-11e8-91f7-bf971451974e.png)

Apparently, the green marked part doesn't show up although these information is captured in code, but somehow is abandoned or doesn't display.
[Example](https://github.com/JacquesCarette/Drasil/blob/yuzhi/code/Example/Drasil/SWHS/TMods.hs) from Line 116 to 103 to 92, these information is carried but not used.

**Comment by halonazhao** [comment]
Temporarily remove these sentences in stable version so that the new generated section can match it.

**Comment by niazim3** [comment]
Since #727 is closed, can this issue be closed @halonazhao?

**Comment by halonazhao** [comment]
Yes. @niazim3 Thanks.
