### ISSUE TITLE
Missing Attribute ShortName

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#513]
While working on #408, I ran `make` to make sure I fixed the assumption error everywhere `assump` was called, and I encountered an error. This is the relevant information from MINGW:

`swhs.EXE: missing attribute ShortName`
`CallStack (from HasCallStack):`
`    ` `error, called at .\Language\Drasil\Printing\Import.hs:nguage.Drasil.Printing.Import`
`make: *** [swhs_build] Error 1`

And here is the code referenced:
https://github.com/JacquesCarette/Drasil/blob/cad5e614b0cfa68ce05f69ef7944bdfa53df77a6/code/Language/Drasil/Printing/Import.hs#L271-L272

This is the original code:
https://github.com/JacquesCarette/Drasil/blob/cad5e614b0cfa68ce05f69ef7944bdfa53df77a6/code/Language/Drasil/Chunk/AssumpChunk.hs#L30-L31

And I added `Attributes` as an input and  replaced line 31 with `assump i a s att = AC i a s att --[shortname s]` in commit 32b809ba, but it appears that `[shortname s]` was functioning as the attributes. Do attributes still need to be passed to the function?

**Comment by JacquesCarette** [comment]
Right, `[shortname s]` did add a single attribute (a short name), which is required for assumptions. Because you replaced it with something arbitrary, and in the code itself, you pass in an empty list, that's what triggers the error. You need to make sure that `shortname s` in some fashion is still part of the attributes attached to assumptions.

**Comment by samm82** [comment]
So instead of passing `[ ]`, I should pass `[shortname s]`? Will that fix it?

**Comment by samm82** [comment]
@JacquesCarette I replaced `assump i a s att = AC i a s att --[shortname s]` with `assump i a s att = AC i a s ((shortname s):att)`, which ensures that `shortname s` is part of the attributes in commit ##
