### ISSUE TITLE
Differences Resulting from Removing acroNumGen

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#516]
@JacquesCarette 
While going through and removing occurrences of acro- a few difference between the generated files and the stable files appeared. I'm unsure if this qualifies as requiring a stable-fix but I'm posting an issue just in-case it does

Generated
![image](https://user-images.githubusercontent.com/35268928/39832848-6049c684-5396-11e8-8a34-eb06339c0d21.png)

Stable
![image](https://user-images.githubusercontent.com/35268928/39832879-7a6630b6-5396-11e8-9388-26bdd4538cef.png)

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39834637-a10b8702-539b-11e8-8907-267f52e30475.png)
Left: Stable 
Right: Generated

I'm going to continue adding any stable differences I come across just to keep track of them for myself.

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39838020-20add5d2-53a6-11e8-89cf-938f5bc8db9e.png)
Left: Stable
Right: Generated

**Comment by elwazana** [comment]
Should I continue removing <code>acroNumGen</code> or skip it and remove the over <code>acro-</code> functions?

**Comment by szymczdm** [comment]
@JacquesCarette These are not using uid (but I think you've discovered that already), we just need better labels. Also, as mentioned in #470 there is currently no way to fix the printing as yet (until the assumptions/reqs/etc. have been pulled out from Document and moved to DocumentLanguage).

I think it's worthwhile to continue removing acroNumGen, and we'll update stable as necessary (keeping issues like these open!) until we have the means to fix it.

**Comment by JacquesCarette** [comment]
Right - I did figure that out a few minutes later.  I agree, we should continue this work.

**Comment by elwazana** [comment]
The following is from NoPCM
![image](https://user-images.githubusercontent.com/35268928/39927017-f954ee58-54fe-11e8-862c-b5e402d8ac62.png)

Left: Generated => There is an error with two tags at the bottom, I think it becuase NoPCM imports some assumptions from SWHS also I didn't create these tags as I didn't need to modify the function that assigns assumptions their tags.
![image](https://user-images.githubusercontent.com/35268928/39927347-ed24b626-54ff-11e8-8648-59cfdd14fb37.png)
@JacquesCarette Should I modify these tags as well?

Right: Stable

**Comment by JacquesCarette** [comment]
Yes.  NoPCM and SWHS really are one big 'unit'.

**Comment by elwazana** [comment]
From NoPCM
![image](https://user-images.githubusercontent.com/35268928/39927939-e1feeba2-5501-11e8-95ae-fab4bb3772fd.png)
![image](https://user-images.githubusercontent.com/35268928/39927989-0e59d00e-5502-11e8-9f88-b95019378f4b.png)
Left: Generated
Right: Stable

**Comment by elwazana** [comment]
From NoPCM
![image](https://user-images.githubusercontent.com/35268928/39928518-8a24db92-5503-11e8-97e5-f6ded641529f.png)
Left: Generated
Right: Stable

**Comment by JacquesCarette** [comment]
To me, that looks much better.  Now, of course, we'll need a way to tag these with super-short labels (akin to R1, R2, ... !) for the purposes of using them in tables, graphs, etc. But those can be proper links. Common use can be the more mnemonic names.  Of course, we'll likely want @smiths to help shorten these long labels. Probably by introducing some conventions.

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39944132-5ba9e16a-5533-11e8-8b60-2046d7577379.png)
![image](https://user-images.githubusercontent.com/35268928/39944264-04007626-5534-11e8-8307-7484573445cf.png)

Left: Generated 
Right: Stable

**Comment by smiths** [comment]
The name Use-Above-Find-Mass-IM1-IM4 isn't a great name.  The IM numbers may change.  Find-Mass would probably be fine as a name.

@JacquesCarette and I will likely have a difference of opinion on this, but I miss the prefixes for the assumptions requirements, likely changes etc.  If they have an R, or an A, or whatever, in front of them, I quickly know what I'm looking at.

We will need short names.  To be honest, I would be tempted to use numbers.  There is no other convention that we could come up with that would be as short.  If that doesn't work, then the author will have to come up with a short name.  I don't like the idea of auto generating, since the names are quite likely to be meaningless if auto generated.

**Comment by JacquesCarette** [comment]
I agree that the name is bad as the IM numbers may change.

I am fine with mnemonic prefixes to such names (like Find-Mass, can be R-Find-Mass). I agree that we will in some cases also want short names. Though in that case, I am tempted to use machine-generated numeric short-names -- as these are always meaningless anyways.
