### ISSUE TITLE
Question: Dead Knowledge?

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#517]
While looking over the examples to familiarize myself a bit more with the code, I ran into this. I'm not sure what it means or what it's referring to.
https://github.com/JacquesCarette/Drasil/blob/e82da482309339c787ee028e38dbb3325569b506/code/Example/Drasil/SWHS/Body.hs#L716-L718

**Comment by smiths** [comment]
I didn't know that.  Thanks @szymczdm.  I'm not sure if the name Dead Knowledge has the right connotation, but it does make sense to distinguish knowledge we can generate something from, from knowledge that doesn't change.

If this answer makes sense to you @elwazana, you can close this issue.

**Comment by JacquesCarette** [comment]
That was most likely a term I used at some point.
