### ISSUE TITLE
Differences resulting from Removing acroTest

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#519]
Here are more differences between the stable version and my generated version for NoPCM as I've been removing acroTest part of  #518 .

![image](https://user-images.githubusercontent.com/35268928/39887494-5af67644-5460-11e8-8d9f-25e312af83f5.png)
![diff](https://user-images.githubusercontent.com/35268928/39887711-e8045da8-5460-11e8-98d8-e8a155f25442.JPG)

Left: Generated
Right: Stable

**Comment by JacquesCarette** [comment]
The left (generated) is *better*. I'm still not liking it, but that can be a further pass.

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, should I close this issue? 

Now that the `acro-` functions, those that were already removed and will be removed, will be completely reworked so these differences probably won't be the same.

**Comment by JacquesCarette** [comment]
The differences won't be the same, but there will continue to be differences.

The question is, have these differences (that already exist) been accepted into stable?  If yes, then this is indeed obsolete and should be closed.

**Comment by elwazana** [comment]
@JacquesCarette The nomenclature you recommended example: "Temperature-Coil-Variable", etc. Was propagated to Stable.
