### ISSUE TITLE
Find all current uses of Attributes in master

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#527]
Can you detail every instance of the use of `Derivation`, `SourceRef`, `ShortName`, `Rationale`, and `Uses` throughout all of Language, Data, and Example (in the master branch only)? Please include the context of how they are being used as well.

You'll also need to look for any instances where the smart constructors (for the appropriate Attribute) are used, as well as any of the lookup functions like `getSource` or `getDerivation`. Again, context is important.

Feel free to divide the work among yourselves however you see fit.

**Comment by JacquesCarette** [comment]
Further context: we've had a long chat about attributes. What they accomplish, we need. How it's currently implemented (and I'm sure I had some non-trivial input on that), isn't right. But we needed to implement it, get familiar with it, see its flaws "first hand", to figure that out.  So now we'll need to try another route. But we want to make sure to use all we've learned [and that's what this issue is about] in the design for the replacement.

Welcome to research! Sometimes you need to take some steps back to enable the next steps forward.

**Comment by samm82** [comment]
How should we go about this? Should we just make a super long comment here, or should we add it to the wiki?

**Comment by elwazana** [comment]
## Language
- [ ]  <code>Derivation</code>
- [ ]  <code>SourceRef</code>
- [ ]  <code>ShortName</code>
- [ ]  <code>Rationale</code>
- [ ]  <code>Uses</code>
- [ ]  Lookup functions (ex: <code>getSource</code>, <code>getDerivation</code>)

## Data
- [ ]  <code>Derivation</code>
- [ ]  <code>SourceRef</code>
- [ ]  <code>ShortName</code>
- [ ]  <code>Rationale</code>
- [ ]  <code>Uses</code>
- [ ]  Lookup functions 

## Example
- [ ]  <code>Derivation</code>
- [ ]  <code>SourceRef</code>
- [ ]  <code>ShortName</code>
- [ ]  <code>Rationale</code>
- [ ]  <code>Uses</code>
- [ ]  Lookup functions

**Comment by JacquesCarette** [comment]
I don't think adding it to the wiki is good, as this information will almost instantly become obsolete. A series of comments on here is probably best.

**Comment by samm82** [comment]
<h1>Language</h1>

Here is where the types of `Attribute` are defined:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute/Core.hs#L14-L23

<h2>Derivation</h2>
Defined here:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute/Derivation.hs#L5-L8

`getDerivation` takes something that has `Attributes` and returns the (first?) `Derivation`...

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L26-L32

...and `derivationsteps` takes a `Derivation` and returns it as an `Attribute`

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L46-L47

<h2>SourceRef</h2>

Used here to take `Attributes` and return the (first?) `SourceRef`:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L21-L24

`getSource` takes something with `Attributes` and returns the (first?) `SourceRef`:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L18-L19

<h2>ShortName</h2>

`getShortName` takes something with `Attributes` and returns the (first?) `ShortName`

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L34-L40

<h2>Rationale</h2>

 Only found in the definition of the `Attributes` type.

<h2>Uses</h2>

I could only find it here, and I don't think I understand how it is being used:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Code/AST.hs#L17-L18

<h2>Lookup Functions</h2>

The only use of a lookup function in Language is in `getSN`, which takes something with `Attributes` and returns its `ShortName` if it has one and an error if it doesn't:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Printing/Import.hs#L271-L272

**Comment by samm82** [comment]
@JacquesCarette for functions like `getSource` that appear to only return the first `SourceRef`, is it assumed that there's only one `SourceRef` in the `Attributes`?

**Comment by niazim3** [comment]
# Data
There are currently no instances of Attribute implementation in this folder.
Although, it will be implemented in the future, as it is the knowledge base of Drasil.

**Comment by JacquesCarette** [comment]
Re: `getSource` - yes. Unfortunately. It is indeed a bug waiting to happen.

**Comment by samm82** [comment]
@JacquesCarette Also, in `getDerivation`, `deriv` is defined locally and only used for `getDerivation`:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L26-L32

However, `sourceRef` functions the same way as `deriv`, but is defined globally:

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Language/Drasil/Chunk/Attribute.hs#L18-L24

Is there a reason for this? Or am I missing something?

**Comment by elwazana** [comment]
<h2>Derivation</h2>
`Derivation` used in the type definition of `roc_temp_simp_deriv`

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/NoPCM/GenDefs.hs#L19-L23

`getDerivation` takes a `g` of type `HasAttribues` and used to help create a derivation from a chunk's attributes

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage/Definitions.hs#L65-L66

`derivation` used to generate various subsections of derivations for `Data Definitions`, `General Definitions`, and `Instance Models` (`derivation` is defined with `getDerivation`)

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage.hs#L423-L424

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage.hs#L427-L428

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage.hs#L431-L432

`derivationsteps` wraps the Derivation `roc_temp_simp_deriv` in `D` making it an `Attribute`

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/NoPCM/Body.hs#L157-L159

<h2>SourceRef</h2>
`getSource` used to retrieve the source references from the attributes in `QDefinition`s, `GenDefn`, and `InstanceModel`s  for the purpose of creating the fields for those respective sections

https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage/Definitions.hs#L105
https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage/Definitions.hs#L136
https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/DocumentLanguage/Definitions.hs#L147

`sourceref` pulls out the first occurence of a source reference from a list of Attributes and outputs it as a sentence
https://github.com/JacquesCarette/Drasil/blob/4a1c4f8f82eb50957d19494f45fd6b3c1dbfda7a/code/Example/Drasil/GlassBR/DataDefs.hs#L44-L46

<h2>ShortName</h2>
No occurences in  <code>Example</code>

<h2>Rationale</h2>
No occurences in <code>Example</code>

<h2>Uses</h2>
No occurences in <code>Example</code>

<h2>Lookup functions</h2>
They are placed in the corresponging sections above

**Comment by szymczdm** [comment]
@samm82 Re: `Uses` - The one you found is actually a completely different (non-attribute) type! This is a duplicate name. So it looks like the attribute `Uses` has not actually been used.

**Comment by samm82** [comment]
@szymczdm Huh. I'll remove it from the comment then

**Comment by JacquesCarette** [comment]
I want to look at it in more detail.  It's in my list for just a little later this afternoon.

**Comment by JacquesCarette** [comment]
Ok, I've finally had a chance to look.  Upshot:

1. **Derivation**: create a `HasDerivation` lens with `getDerivation` accessor. Remove from Attribute. Add derivation field to `QDefinition`, and I think `DQD`. See what else.
2. **SourceRef**: create `HasReference` lens with `getReferences` accessor. Remove from Attributes. Add field to `QDefinition`
3. **ShortName**: create `HasShortName` lens. Merge this with `refAdd` lens (as a second step). Remove from Attributes. Add to same places that are currently instances of `Referable`
4. **Rationale**: remove. We will re-create this later.
5. **Uses**: remove. We will deal with this via 'inversion'.
6. **Attributes**: remove!

I would implement this in several passes. I would do 5, 4, 2 lens, 2 add field, 2 remove from attrib, 1 lens, 1 add field, 1, remove from attrib, 3 lens, 3 add instances, 3 remove refAdd and replace with shortname, 3 remove from attributes, 6.

@szymczdm ?  If you agree, then we can make a new issue with those steps, and close this one.

**Comment by szymczdm** [comment]
I completely agree. Closing this issue and opening a new one now.
