### ISSUE TITLE
Rendering π in LaTeX

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#529]
As mentioned in PR #509, producing pdfs from .tex files containing the line 
```
$\pi{}$ & π &
```
results in the following: 

![](https://user-images.githubusercontent.com/28247301/40082581-644d0c96-585f-11e8-9a3e-c9ccbd2117c8.png).

It "seems like a problem with the unicode rendering (since TeX doesn't necessarily support it natively). We may need to include something like \usepackage[utf8x]{inputenc} or unixode to fix it."

**Comment by szymczdm** [comment]
Note: we could also use LuaTeX or XeTeX as well.

**Comment by JacquesCarette** [comment]
The process generates a Makefile in the SRS directory, which uses lualatex, and it works with that.  Or at least, it worked when I tested it a couple of weeks ago.

To use pdflatex, different options need to be used, as some slight differences in packages are needed. We could (should) make that an option.

**Comment by szymczdm** [comment]
It turns out it's just a default font issue. I've taken a crack at it and it seems like we'll need to figure out which font is the *best* for unicode support. DejaVu Sans works fine, but it doesn't look that great (imo).

**Comment by JacquesCarette** [comment]
Second answer to https://tex.stackexchange.com/questions/35032/luatex-and-unicode-math-without-unicode-math recommends Latin Modern.
https://tex.stackexchange.com/questions/422039/best-unicode-font-to-work-with-minted-in-xelatex-lualatex
recommends FreeMono.

**Comment by JacquesCarette** [comment]
Not only is it a default font issue, but it is still necessary to indicate math vs text.  Because proper nouns are text, right now, let's just have this called "pi".  I did change the math front to Latin Modern, but that wasn't enough...  Although I did not change the "main" font.

**Comment by JacquesCarette** [comment]
So now pi is showing up.  I'll close this one for now, as things are working.  We'll likely have to revisit the issue later...
