### ISSUE TITLE
Constructors Throw Away Stage Information

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#531]
As mentioned in the comments of 2f8b6fa, the constructors `cqs` and `mkQuant`:

https://github.com/JacquesCarette/Drasil/blob/d7c626bc470f8ef4f0ea641469999767e5d7cb72/code/Language/Drasil/Chunk/DefinedQuantity.hs#L42-L43
https://github.com/JacquesCarette/Drasil/blob/d7c626bc470f8ef4f0ea641469999767e5d7cb72/code/Language/Drasil/Chunk/Quantity.hs#L46-L47

both assume that the `Symbol`s are the same in both `Stage`s. There needs to be a second constructor for each that accounts for the `Stage`.

**Comment by samm82** [comment]
@szymczdm (I just moved this comment to this issue) What if we made one function that checked the stage, and if it is `Equational` or `Implementation`, return the appropriate `Symbol`, and if not, assume the `Symbol`s are the same?

Also, syntactically, how do you check/pass in the stage?

**Comment by szymczdm** [comment]
The stage is a data type that we can pattern match against. What happens is when we're looking up a symbol we use a helper function (ex. `eqSymb`) which takes care of passing the right stage in.

We need our symbols stored as functions from a stage to a symbol. Symbols that are the same for each stage throw away the staging information (ie. \_ -> s). For symbols with distinct representations at each stage, we need to define them both (ie. Pass them to the constructor in the right order) and have it build the function for us, so it could be something like:

Pseudo-code:
```
cqs' :: ConceptChunk -> Symbol -> Symbol -> Space -> Attributes -> DefinedQuantityDict
cqs' c s s2 sp atts = DQD c (symbs s s2) sp atts
  where symbs x _ Equational = x
        symbs _ x Implementation = x
```

**Comment by samm82** [comment]
So would you have to pass in `Equational` and `Implementation`? I know they're the stages, but where do they come from in your `where` statement?

**Comment by samm82** [comment]
Follow up: would this work?
```
cqs :: ConceptChunk -> Symbol -> Symbol -> Stage -> Space -> Attributes -> DefinedQuantityDict
cqs c s s2 st sp atts = DQD c (symbs s s2) sp atts
  where symbs x _ Equational     = x
        symbs _ x Implementation = x
        symbs x _ _              = x
```

**Comment by JacquesCarette** [comment]
Note that this is more complicated that needed, as if you're going to use local functions, then
```haskell
    where symb Equational = x
          symb Implementation = y
```
will be better.
