### ISSUE TITLE
Duplication of CodeSpec

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#534]
So I noticed that `codeSpec` passes its variables to `codeSpec'` that has the same type definition. Are they the same function, and can one of them be removed?

https://github.com/JacquesCarette/Drasil/blob/52c494864be7e8bd098a94cfda0f28d2c144cd2b/code/Language/Drasil/CodeSpec.hs#L76-L113

@JacquesCarette @szymczdm

**Comment by JacquesCarette** [comment]
Yes, these can be merged. Not sure what happened here.
