### ISSUE TITLE
Units no longer being displayed for some data types

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#536]
Many changes were made to the data types for issues #524 and #514 (that can be followed in the open pull request #526).

Now that `Make` runs without hitting any errors, the discrepancies in the examples are now visible.
It turns out, some units are not being displayed in the generated example versions.

For example, these are the instances that are showing up in [GlassBR_log.log](https://github.com/JacquesCarette/Drasil/files/2018502/GlassBR_log.log).

code/build/GlassBR/Website/GlassBR_SRS.html
![image](https://user-images.githubusercontent.com/28247301/40257016-8bd98372-5aba-11e8-80ec-80680a9d410d.png)

vs

code/stable/glassbr/GlassBR_SRS.html
![image](https://user-images.githubusercontent.com/28247301/40257025-949d99b2-5aba-11e8-90be-46fdd845ffb6.png)

**Comment by JacquesCarette** [comment]
The last check-in (and subsequent merge) fixed this.
