### ISSUE TITLE
Replace uid hack for creating references

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#545]
`uid` in the instances of the class `Referable`  is a hack for creating addresses for links in the generated documentation.

Example: 
<pre>
instance Referable GenDefn where
  refName _ = error "No explicit name given for theory model -- build a custom Ref"
  refAdd  g = "GD:" ++  g ^ <b>.uid</b>
  rType   _ = Def
</pre>

**Comment by elwazana** [comment]
@szymczdm Hello Dan, now that work has started on `Label` should I start to create a possible design proposal to bring forward in our next all-hands meeting?

Or should I leave that for once `Label` and `LabelledContents` are fully implemented?

**Comment by szymczdm** [comment]
You can begin work on a design proposal. Make sure you incorporate labels where appropriate.

**Comment by szymczdm** [comment]
Also, a change added by #945 needs to be considered here too. Specifically commit be80afdf29b0f76e1c60230f1c94d963b48

**Comment by JacquesCarette** [comment]
The instance for `GenDefn` has been fixed.  Only the instance for `ConceptInstance` still has traces of this hack (and it is not as bad). In fact, it seems like a hack that `ConceptInstance` is `Referable` as it has no `Label`.
