### ISSUE TITLE
Using a short name when printing contents 

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#560]
As mentioned in a review for PR #553 by @JacquesCarette, this issue needs to be filed to ensure that `Contents` uses a shortname somewhere (specifically: [code/Language/Drasil/Printing/Import.hs](https://github.com/JacquesCarette/Drasil/pull/553/files/f717a093a8c4dc8447078b8ded2c65939428e3c0#diff-e6c01bedd4128a1940b02d898a8b5d7dR264)).

**Comment by Mornix** [comment]
If I'm understanding the definition of `Ref` constructor for `Sentence`, it appears that both `RefName` and `Sentence` values are the same with the latter being wrapped in `S`. 

From there, the `sn` is used through `RefName` in the HTML backend. 
The TeX backend does not use `sn` at all. @JacquesCarette @szymczdm, is my understanding of `shortname` correct, in that if it's present that should be used as the label for references?

**Comment by JacquesCarette** [comment]
`Sentence` are quite complicated -- just one of its constructions is an `S` over a `String`.

But your understanding is correct: `shortname` is supposed to be used as the label for references.

**Comment by niazim3** [comment]
Since the creation of `LabelledContent`, a `shortname` is "attached" to a `Content` with the presence of a `Label`. @Mornix, does that mean this issue can be closed? Or is it being worked on somewhere?

**Comment by JacquesCarette** [comment]
Indeed, pinging @Mornix on this.

**Comment by Mornix** [comment]
Merge of #1148 resolved this. Closing.
