### ISSUE TITLE
Fix up stable on master

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#564]
I just committed a fix to the makefile, could you three please check the logs and see if there are any actual errors in there? Then, if not, update stable on master to ensure we get back to a clean CI build.

**Comment by elwazana** [comment]
@szymczdm I'm not getting anything in my logs:
![image](https://user-images.githubusercontent.com/35268928/40684023-2e9d81f2-635e-11e8-96e8-06fa933e694e.png)

Unless you meant something else?

**Comment by niazim3** [comment]
The changes to the makefile didn't change any of the discrepancies in the SSP_log.log or SWHS_log.log on my local machine...
![image](https://user-images.githubusercontent.com/28247301/40724898-24eb3ffe-63f0-11e8-93a8-f0519b5fec53.png)

**Comment by niazim3** [comment]
Technically, the above was the result I was getting earlier as well, so I'm unsure if the changes in the makefile actually addressed the problem or not... 
Nonetheless, I can work on fixing the discrepancies.
