### ISSUE TITLE
Create and assign issues for Label, isLabel, and ContentChunk implementation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#567]
A lot of design decisions were discussed in yesterday's all hands meeting.

### `Label` Module
- create abstract data type `Label` which has a `uid`, and an enumerated type (`reference address`, `meta-link`, `uri`) and is not "attached" to anything
- `shortname` (external) is the display for a `reference address` (internal)
- multiple `mkLabel` constructors should be created for label creation
- make several `refer` functions that `:: <ctx> -> Label -> Reference` where `ctx` is some contextual information that may be useful in displaying the reference. So `refer` is to be used 'close to rendering'.
- take a label to build  a shortname in the Label module
- for anything that's referable (since anything that's referable should have a label), update smart chunk constructors to 
```
uid of chunk -> _ -> _ -> ... -> Label (uid) -> Chunk 
```
i.e. what should be passed in to the smart constructor should be a `Label` but what should be stored in the Chunk is its `uid` (only).

### `isLabel`
- create an `isLabel` class which will be associated with rendering strings
- no methods for now
- should be a sub-class of `HasUID`.
- can create an `HasLabel` class for those things which "have a label".  `isLabel` would then just be `HasUID` and `HasLabel` (i.e. no need for the sub-classing).

### `ContentChunk`
- `ContentChunk` creation as a way of getting around the problems that were popping up in #537 (i.e. `shortname` for `Contents` was resulting in errors)
- build off of the current `Contents` type by appending to it a (`RefAdd`) id and a `Maybe ShortName`?

Please feel free to update this post with notes that elaborate or fix any misunderstood comments made.

**Comment by JacquesCarette** [comment]
Edited for clarity.  Should this remain assigned to @szymczdm and myself as a 'design'?  If so, it can likely be closed... but if it is for implementation, then I think the assignees should change.

**Comment by niazim3** [comment]
The contents of this issue are mainly documenting discussed design, however, can this issue be closed once the above tasks are assigned and issues are created for `Label`, `isLabel`, and `ContentChunk`? Or should we just be assigning work to ourselves from here?

**Comment by JacquesCarette** [comment]
I think we should somehow capture the fact that this issue contains valuable design information. On the wiki? Or a `DESIGN.md` file?  Then issues created & assigned for each, and then this can be closed.

**Comment by niazim3** [comment]
Added a link to this issue in already existing wiki [Design-Choices](https://github.com/JacquesCarette/Drasil/wiki/Design-Choices).

**Comment by szymczdm** [comment]
I take it we still need to create and assign the issues to close this?

**Comment by samm82** [comment]
We've created a workflow proposal in #629 -- this issue can be closed at your discretion @szymczdm @JacquesCarette
