### ISSUE TITLE
Making Import Statements more Specific

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#569]
As a time-filler task, we can make the import statements of files more specific - ie. don't import a whole module if the file only uses one or two functions from it. We should coordinate this so we don't miss files/go over files twice.

Also, make a separate branch/PR for **each** import statement in **each** file.

**Note:** Certain files in `Language.Drasil` need to be ignored until #558 gets finished and merged.

---
# TODO:
## Language.Drasil
- [x] NounPhrase.Core
- [x] URI.AST
- [x] ChunkDB
- [x] Classes
- [x] Config
- [x] Document
- [x] Expr
- [x] Format
- [x] Misc
- [x] NounPhrase
- [x] People
- [x] Reference
- [x] RefTypes
- [x] Setup
- [x] Space
- [x] Spec
- [x] Symbol
- [x] SymbolAlphabet
- [x] SystemInformation
- [x] Unicode

### Chunk @elwazana
- [x] Concept.Core
- [x] Constrained.Core
- [x] AssumpChunk
- [x] Attribute
- [x] Change
- [x] Citation
- [x] CommonIdea
- [x] Concept
- [x] Constrained
- [x] DefinedQuantity
- [x] Derivation
- [x] Eq
- [x] GenDefn
- [x] Goal
- [x] InstanceModel
- [x] NamedIdea
- [x] PhysSystDesc
- [x] Quantity
- [x] References
- [x] Relation
- [x] ReqChunk
- [x] ShortName
- [x] SymbolForm
- [x] Theory
- [x] UncertainQuantity
- [x] Unital
- [x] Unitary
- [x] UnitaryConcept
- [x] VarChunk

### ~~Expr~~ @niazim3
- [x] Extract
- [x] Math
- [x] Precedence

## Data.Drasil
- [x] Software.Products
- [x] Citations
- [x] Constraints
- [x] People
- [x] Phrase
- [x] SentenceStructures
- [x] Utils

### ~~Concepts~~ @samm82
- [x] Computation
- [x] Documentation
- [x] Education
- [x] Math
- [x] PhysicalProperties
- [x] Physics
- [x] Software
- [x] SolidMechanics
- [x] Thermodynamics

### ~~Quantities~~ @samm82
- [x] Math
- [x] PhysicalProperties
- [x] Physics
- [x] SolidMechanics
- [x] Thermodynamics

### ~~Units~~ @niazim3
- [x] PhysicalProperties
- [x] Physics
- [x] SolidMechanics
- [x] Thermodynamics

## ~~Example.Drasil~~
- [x] DocumentLanguage @samm82
- [x] SRS @samm82

### ~~DocumentLangauge~~ @samm82
- [x] Definitions
- [x] RefHelpers
- [x] TraceabilityMatrix

### ~~GamePhysics~~ @samm82
- [x] DesignDec.Artbiter
- [x] DesignDec.Vector
- [x] Body
- [x] Concepts
- [x] DataDefs
- [x] GDef
- [x] IMods
- [x] Main
- [x] References
- [x] TMods
- [x] Unitals

### ~~GlassBR~~ @samm82
- [x] Assumptions
- [x] Body
- [x] Concepts
- [x] DataDefs
- [x] IMods
- [x] Main
- [x] ModuleDefs
- [x] References
- [x] Symbols
- [x] TMods
- [x] Unitals
- [x] Units

### ~~HGHC~~ @samm82
- [x] HeatTransfer
- [x] HGHC
- [x] Main

### ~~NoPCM~~ @elwazana
- [x] Body
- [x] DataDesc
- [x] Definitions
- [x] GenDefs
- [x] IMods
- [x] Main
- [x] Unitals

### ~~Sections~~ @elwazana
- [x] AuxiliaryConstants
- [x] GeneralSystDesc
- [x] Introduction
- [x] ReferenceMaterial
- [x] Requirements
- [x] ScopeOfTheProject
- [x] SolutionCharacterSpec
- [x] SpecificSystemDescription
- [x] Stakeholders
- [x] TableOfAbbAndAcronyms
- [x] TableOfSymbols
- [x] TableOfUnits
- [x] TraceabilityMandGs

### ~~SSP~~ @samm82
- [x] Assumptions
- [x] BasicExprs
- [x] Body
- [x] DataDefs
- [x] DataDesc
- [x] Defs
- [x] GenDefs
- [x] Goals
- [x] IMods
- [x] Main
- [x] References
- [x] Requirements
- [x] TMods
- [x] Unitals

### ~~SWHS~~ @elwazana
- [x] Assumptions
- [x] Body
- [x] Concepts
- [x] DataDefs
- [x] DataDesc
- [x] GenDefs
- [x] Generate
- [x] IMods
- [x] LikelyChanges
- [x] Main
- [x] References
- [x] Requirements
- [x] TMods
- [x] Unitals

---
# After Merge of #558 
## ~~Language.Drasil~~ @elwazana
- [x] Chunk.Code
- [x] Outputs.Formats
- [x] Code
- [x] CodeSpec
- [x] Generate 
- [x] Unit 
- [x] UnitLang

### ~~Code~~ @elwazana
- [x] AST
- [x] Code
- [x] CodeGeneration
- [x] ~~CodeTest~~
- [x] DataDesc

#### ~~Imperative~~ @elwazana
- [x] LanguageRenderer.CppRenderer
- [x] LanguageRenderer.CSharpRenderer
- [x] LanguageRenderer.GOOLRenderer
- [x] LanguageRenderer.JavaRenderer
- [x] LanguageRenderer.LuaRenderer
- [x] LanguageRenderer.ObjectiveCRenderer
- [x] LanguageRenderer.PythonRenderer
- [x] Parsers.ConfigParser
- [x] AST
- [x] Helpers
- [x] Import
- [x] ~~Lang~~
- [x] LanguageRenderer

### ~~HTML~~ @elwazana
- [x] Helpers
- [x] Monad
- [x] Print

### ~~Make~~ @elwazana
- [x] AST
- [x] Helpers
- [x] Import
- [x] Print

### ~~Printing~~ @elwazana
- [x] AST
- [x] Citation
- [x] Helpers
- [x] Import
- [x] LayoutObj

### ~~TeX~~ @elwazana
- [x] Helpers
- [x] Monad
- [x] Preamble
- [x] Print

## ~~Data.Drasil~~ @elwazana
- [x] SI_Units

**Comment by JacquesCarette** [comment]
And if you do it for a **single** import statement, for a **single** file per check-in, such PRs should be trivial to merge in.  [Still good to go through PRs as we'll get Travis to verify that everything's fine.]

**Comment by elwazana** [comment]
@JacquesCarette @samm82 Would it be better to have a separate branch/PR for each file, not each import statement? Having a separate branch for each import statement in even a single file seems a bit excessive.

**Comment by samm82** [comment]
I think so, but we should wait until we hear back from @JacquesCarette

**Comment by JacquesCarette** [comment]
If you happen to do one file completely in one sitting, sure, do a single PR.  But if you happen to just do a bit, it is still worth not just checking in, but making it a PR.  You don't necessarily need to created a new branch to continue the work though.

I think my main message is that it is worth doing this in small bits, not that you *must* do it in small bits.

**Comment by samm82** [comment]
`Data.Drasil.SI_Units` has the following import statment:
https://github.com/JacquesCarette/Drasil/blob/494140f59358f4f14b35443754a3e51e95de42d4/code/Data/Drasil/SI_Units.hs#L2-L9

How will this work with #558? @JacquesCarette @szymczdm

**Comment by JacquesCarette** [comment]
Right, `Data.Drasil.SI_Units` is indeed a bit problematic, as the comment says.  And I think the solution in the comment is the right one as well: drasil-lang should actually export two modules.

**Comment by samm82** [comment]
Should I be working on this in parallel with #558, or should I address it at the end?

**Comment by JacquesCarette** [comment]
It should be an independent task (i.e. to create that extra export, and then switch to using that in `Data.Drasil.SI_Units`), which can be merged in to #558 before it is complete. It should be separate from #569 as it isn't just a straightforward improvement but an actual change.

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, just a quick question should we specify the imports for files like these?
![image](https://user-images.githubusercontent.com/35268928/42337089-9f77fdaa-8053-11e8-9653-7abad08c7a63.png)

**Comment by JacquesCarette** [comment]
Yes please.

**Comment by elwazana** [comment]
@JacquesCarette is Code/CodeTest.hs meant to be used? I ask becuase of a few reasons:

1. It wasn't in the cabal file 

2. It seems to have an error without any modification:
![image](https://user-images.githubusercontent.com/35268928/42600434-4483d0fe-8530-11e8-92f4-d2dbf3a1f4c3.png)

**Comment by JacquesCarette** [comment]
It is dead code. I think it was an attempt at generating tests, but has bit-rotted.  Go ahead and delete it.
