### ISSUE TITLE
Create a web-page using MathJax to Display at least 5 equations from the GlassBR example

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#576]
@deviprasad135, given that you are not sure where to start with MathJax, I suggest that you make a little html file that displays some equations from the  GlassBR example.  Please put the code under version control, say in the "notes" folder.  We'll delete it when you are done.

**Comment by deviprasad135** [comment]
@smiths, Do I need to push it on the master branch?

**Comment by smiths** [comment]
A branch is fine.  This isn't something we are going to keep.  We can delete the branch once the experiment is over.

**Comment by smiths** [comment]
Looks good Devi.  I was able to view the equations on a web browser without any difficulties.

You can close this issue and delete your branch.

Now you need to determine how to get MathJax to work within Drasil.  You should discuss with @szymczdm , but I think I am starting to see why this shouldn't be that difficult a problem.  The html looks like tex when you are using MathJax, and we already have means to render tex.

**Comment by deviprasad135** [comment]
Okay. Thanks @smiths
