### ISSUE TITLE
Suggested Reading

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#630]
Hello @szymczdm.  During my trip to ICSE, I found a few more papers that advocate the use of DSLs to bring SE to SC.  Have a look at the following papers, and then you can close this issue.  @Mornix, @niazim3, @elwazana, @samm82, @deviprasad135 and @halonazhao, you may also be interested in looking at these papers.  They provide justification/motivation for what we are doing. 

All of these papers are suggesting DSLs as future work, as far as I can tell, we are well ahead of others are making this a reality.

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/ffcebd8967c05be2a2b3d5a3d73c2e31c7d0297b/SciCompAndSoftEngPapers/SimmEtAl2018.pdf

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/c9a468aaf3b9d062cc5dd145884697acce477155/SciCompAndSoftEngPapers/JohansonAndHasselbring2018.pdf

https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/blob/git-svn/SciCompAndSoftEngPapers/Smith2018.pdf

**Comment by JacquesCarette** [comment]
Have you done your homework @szymczdm ?

**Comment by szymczdm** [comment]
Yup. I think these are worth keeping a reference to, so I've moved the links to the wiki and created a page for suggested reading. That way we can keep adding to it as we see fit (and maybe organize things into a number of sub-categories based on topic area)
