### ISSUE TITLE
Update GlassBR SRS to match modifications to manual version

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#675]
A small change has been made in the SRS for GlassBR.  Please update the Drasil version to match these changes:

https://github.com/smiths/caseStudies/commit/65cc95b15140fa1ab54b978b2a31eb11e857ece1

**Comment by smiths** [comment]
There may be one more change coming for this issue.  I'll let you know soon.

**Comment by samm82** [comment]
Do you want me to update the stable or the code too?

**Comment by smiths** [comment]
Both.  When the changes are made GlassBR should pass the Travis CI tests.

**Comment by smiths** [comment]
@samm82, can you please add to this issue the changes to the SRS for GlassBR that were made in the manual version for the following commit:

https://github.com/smiths/caseStudies/commit/1514d32e3d926af7e7bde94fcb81cf4a61323db3

The data definition for SD was previously implied, but not explicit.  The connection between the requirements, the design, and the implementation should be easier with an explicit definition of SD.

**Comment by smiths** [comment]
Please add this one too:

https://github.com/smiths/caseStudies/commit/8f7bb39165b86772f34f4734c05c541f3d667244

**Comment by samm82** [comment]
TODO:

- [ ] smiths/caseStudies@65cc95b
- [ ] smiths/caseStudies@1514d32
- [ ] smiths/caseStudies@8f7bb39

**Comment by smiths** [comment]
The cosmetic differences between manual and generated are fine.  The absence of the (SD) is also fine.  I think you can close this issue.

**Comment by samm82** [comment]
@smiths There are a couple of little things I still need to do, the main one being the comment on 1514d32 - what is the status on that?

**Comment by smiths** [comment]
@samm82, to save me time, can you tell me where to find 1514d32?  Is it a commit hash from another repo?  If so, can you add a link here?

**Comment by samm82** [comment]
@smiths smiths/caseStudies@1514d32 Sorry I forgot in was in the caseStudies repo 😬

**Comment by smiths** [comment]
I added a comment with the commit.  I think we need to wait until the devi branch is closed before finishing the changes.

**Comment by samm82** [comment]
The following is in the Notes section of Calculation of Demand IM - "q or demand, is the 3 second duration equivalent pressure obtained from Figure 2 by interpolation using stand off distance (SD) and wTNT as parameters. wTNT is defined as w TNT. SD. is the stand off distance where √(SDx2+SDy2+SDz2) where (SDx, SDy, SDz) are coordinates." Since SD is its own data definition now, should this be changed to "q or demand, is the 3 second duration equivalent pressure obtained from Figure 2 by interpolation using stand off distance (SD) and wTNT as parameters. wTNT is defined as w TNT **and SD is defined as SD", or is there something else that should be done? @smiths

**Comment by smiths** [comment]
@samm82,  yes, your proposed changes are along the right lines, although I would like the Data Definition for SD to be explicitly referenced.  The text in the current version of the SRS for GlassBR in the case studies repo captures the information that I believe should be included in the generated version.

**Comment by samm82** [comment]
I'm going to close this issue, as this is being tackling in the Update GlassBR SRS Project more generally and in smaller steps, but I will make changes in the same branch, updateGlassSRSb, that I will rename to just updateGlassSRS.
