### ISSUE TITLE
Broken Link from Likely Change to Assumption in SSP

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#683]
In PR #681, a likely change was added to the SSP example.

However, the link for the assumption that the likely change attempts to use doesn't actually work.

This problem is related to how Assumptions are displayed **/** stored.

In glassBR, the assumptions are shown as shortnames followed by a ":" and a description of the assumption, and there is no such issue when a likely change source-assumption like the following is clicked:
![image](https://user-images.githubusercontent.com/28247301/41564269-43851e1e-7320-11e8-9bb2-54f644aa9d0e.png)

-->

![image](https://user-images.githubusercontent.com/28247301/41564312-64178ffe-7320-11e8-8d85-26afd35ec1fb.png).

On the other hand, assumptions are still displayed as "A" appended to a number, followed by a ":" and finally, the description. When the source-link in SSP's likely change is clicked,

![image](https://user-images.githubusercontent.com/28247301/41564363-90080cd8-7320-11e8-8a43-f04f052552f5.png)

the address is updated from "...code/build/SSP/Website/SSP_SRS.html" to "...code/build/SSP/Website/SSP_SRS.html#A:Soil-Layer-Homogeneous", but one doesn't actually see the assumptions section.

Although this is the case, both examples' likely changes and `assumpchunk`s seem to be built the same way.
Relevant files: [SSP Body](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/SSP/Body.hs), [SSP Assumptions](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/SSP/Assumptions.hs), [GlassBR Body](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/GlassBR/Body.hs), [GlassBR Assumptions](https://github.com/JacquesCarette/Drasil/blob/master/code/Example/Drasil/GlassBR/Assumptions.hs).

**Comment by elwazana** [comment]
#687
