### ISSUE TITLE
Changes not Merged from master

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#688]
I updated the GlassBR SRS (c) as per issue #675 in a branch which got merged into master in #684. Now, on my SubPackages branch, I merged master into it, so these changes should be here. However, when I run `make`, this shows up in GlassBR_log:

```
129a130,131
> $SD$ & Stand off distance & m
> \\
526a529,544
> ~\newline
> \noindent \begin{minipage}{\textwidth}
> \begin{tabular}{p{0.2\textwidth} p{0.73\textwidth}}
> \toprule \textbf{Refname} & \textbf{DD:sd}
> \phantomsection 
> \label{DD:sd}
> \\ \midrule \\
> Label & Stand Off Distance
> \\ \midrule \\
> Units & m
> \\ \midrule \\
> Equation & $SD=\sqrt{{SD_{x}}^{2}+{SD_{y}}^{2}+{SD_{z}}^{2}}$
> \\ \midrule \\
> Description & $SD$ is the stand off distance (m)\newline${SD_{x}}$ is the stand off distance (x-component) (m)\newline${SD_{y}}$ is the stand off distance (y-component) (m)\newline${SD_{z}}$ is the stand off distance (z-component) (m)
> \\ \bottomrule \end{tabular}
> \end{minipage}\\
580c598
< $a$ & $a>0$ and $a\geq{}b$ & ${d_{min}}\leq{}a\leq{}{d_{max}}$ and $a<{AR_{max}} b$ & $1.5$ m & 10.0\%
---
> $a$ & $a>0$ and $a>b$ & ${d_{min}}\leq{}a\leq{}{d_{max}}$ and $a<{AR_{max}} b$ & $1.5$ m & 10.0\%
466a467,477
> <em>SD</em>
> </td>
> <td>
> Stand off distance
> </td>
> <td>
> m
> </td>
> </tr>
> <tr>
> <td>
1765a1777,1824
> <div id="DD:sd">
> <table class="ddefn">
> <tr>
> <th>
> Label
> </th>
> <td>
> <p class="paragraph">
> Stand Off Distance
> </p>
> </td>
> </tr>
> <tr>
> <th>
> Units
> </th>
> <td>
> <p class="paragraph">
> m
> </p>
> </td>
> </tr>
> <tr>
> <th>
> Equation
> </th>
> <td>
> <div id="">
> <div class="equation">
> <p class="paragraph">
> <em>SD = &radic;(SD<sub>x</sub><sup>2</sup>&plus;SD<sub>y</sub><sup>2</sup>&plus;SD<sub>z</sub><sup>2</sup>)</em>
> </p>
> </div>
> </div>
> </td>
> </tr>
> <tr>
> <th>
> Description
> </th>
> <td>
> <p class="paragraph">
> <em>SD</em> is the stand off distance (m)<br /><em>SD<sub>x</sub></em> is the stand off distance (x-component) (m)<br /><em>SD<sub>y</sub></em> is the stand off distance (y-component) (m)<br /><em>SD<sub>z</sub></em> is the stand off distance (z-component) (m)
> </p>
> </td>
> </tr>
> </table>
> </div>
1924c1983
< <em>a&thinsp;&gt;&thinsp;0</em> and <em>a&thinsp;&ge;&thinsp;b</em>
---
> <em>a&thinsp;&gt;&thinsp;0</em> and <em>a&thinsp;&gt;&thinsp;b</em>
```

These were all changed I made in the branch; the changes in stable were preserved, but not in the build.
(Stable on left, build on right):
![diff](https://user-images.githubusercontent.com/35857611/41661930-d2ac0280-746d-11e8-8999-c0487b8f5887.JPG)

This issue is also present in the TeX, it's just easier to show with the HTML.

However, in the Haskell code for generating the code, the change that I made is present:

 https://github.com/JacquesCarette/Drasil/blob/92bbee6259b13ab2ed00d37674e368273c0071ca/code/Example/Drasil/GlassBR/Unitals.hs#L70
(`Inc` used to be `Exc`)

So why the difference in the generated HTML/TeX? I've run `stack clean` multiple times.

**Comment by szymczdm** [comment]
Which branch are you currently working in (ie. where is the problem)? And have you committed/pushed since merging?

I have no idea (off the top of my head) why the changes would be present but not applied. However, I'll take a look.

**Comment by samm82** [comment]
SubPackages

**Comment by szymczdm** [comment]
I just ran make (based on the most recently pushed version of that branch) and the entire Data Constraints subsection is missing from GlassBR's SRS (hence, that a > b is missing too). Do you have other local changes I'm not seeing?

**Comment by samm82** [comment]
Nope

```
$ git status
On branch SubPackages
Your branch is ahead of 'origin/master' by 95 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by szymczdm** [comment]
Alright, I checked out bd476ed6 and that worked fine, so I'm testing your hand-merge now.

**Comment by szymczdm** [comment]
I re-checked out the branch and did a clean make, everything looks fine except for some diffs w/ the resource folder path.

**Comment by samm82** [comment]
Not only should I not have made the original resource path change, but I should've made only one revert to fix it. 😬 

Not sure what my issue is then - I'll look into it again

**Comment by samm82** [comment]
@szymczdm I checked out master, ran `make`, checked out SubPackages, ran `make`, and now I only have the resource path difference? Weird. I guess this issue is closed.

**Comment by samm82** [comment]
I made a fix in master to finally fix the resource path and now SubPackages works great
