### ISSUE TITLE
GlassBR - References not showing up in SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#691]
The Reference section in GlassBR_SRS is empty - the header is there and it is in the table of contents, but there are no references displayed. (I'll add a picture later.)

**Comment by szymczdm** [comment]
Is this on a particular branch? On master the references are still showing up.

**Comment by samm82** [comment]
I think I need to re-evaluate how I change branches/run `make`/do something - I tried it on master. I just quick made this issue so I didn't forget - I'll look into it in detail later and keep you posted.

**Comment by szymczdm** [comment]
Alright. I just confirmed my build on master has references on both the GlassBR HTML and TeX versions (and of course the TeX is showing only those refs that are actually in use currently).

**Comment by samm82** [comment]
Yup. References are being built. 😩 Ever since I switched to command prompt for running `make` instead of MinGW, I seem to be having issues like these - any ideas?

**Comment by JacquesCarette** [comment]
Do you mean you are using a cygwin shell?  Or some other shell? The details are likely to matter.

**Comment by JacquesCarette** [comment]
The DOS command prompt 'cmd' ?  How do you start it?

**Comment by samm82** [comment]
Yes, 'cmd'. I start it by just searching for 'cmd' in start

**Comment by samm82** [comment]
Do I have to do anything when I switch branches when using cmd?

**Comment by szymczdm** [comment]
You shouldn't have to. I use cmd as well, but I've got my PATH setup to include the appropriate git, minGW, and msys binaries (so I can use commands like `git`, `ls`, and `make`.

**Comment by samm82** [comment]
So I'm not sure if I've done that/how to find out if I've done that

**Comment by JacquesCarette** [comment]
Right - @szymczdm can help. I haven't used 'cmd' in years [I've switched to cygwin long ago].

**Comment by szymczdm** [comment]
@samm82 check your system environment variables (if you're on win10, just open the start menu and type "environment variables" and something should come up. On win7 you need to go through Control Panel -> System Properties -> Advanced -> Environment Variables. If you check the variable called PATH it should have (somewhere in it) your msys directory (ex. `C:\MinGW\msys\1.0\bin`). It should also have your git directory.

**Comment by samm82** [comment]
I added my msys directory, and this was already there: `C:\Program Files\Git\cmd` - I'm assuming that's my git directory? Also, do I need to restart for changes to apply?

**Comment by szymczdm** [comment]
You need to restart cmd (so close and re-open). Also, did you apply the registry key from #482 ? If not, you might need to since that will ensure the `chcp 65001` command is run every time cmd starts.

**Comment by samm82** [comment]
Ok, I will, and yes I did.

**Comment by szymczdm** [comment]
If you're still having issues, you also might want to try updating git,

**Comment by samm82** [comment]
Thanks! It seems to be working now
