### ISSUE TITLE
htTransCoeff_min Should have definition?

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#696]
![screen shot 2018-06-21 at 10 11 13](https://user-images.githubusercontent.com/28347043/41724457-9460a34a-753b-11e8-87c5-b6528af09ae9.png)
Should this h_min appear in the symbol table? It is not just for the data constraints. And it should be a chunk with definition?

![screen shot 2018-06-21 at 10 03 04](https://user-images.githubusercontent.com/28347043/41724827-6f4cead6-753c-11e8-9a12-e1f57dd90832.png)
gradient symbol is missing from the table in SWHS manual version. If you can confirm both, I can make changes for both manual version and drasil. @smiths

**Comment by JacquesCarette** [comment]
Yes, h_min should be properly defined. Same for $\delta$.

I am glad that your work is paying off in this way. These are exactly the kinds of consistency problems we want to catch.

**Comment by halonazhao** [comment]
For SWHS case, from automatically collecting, these symbols are missing. (Need to be improved in collecting structure.)
D | Diameter of tank | m    
L | Length of tank | m        (should be collected from Expr, not showing up in sentences)


tfinal | Final time | s
ρP | Density of PCM | kg/m3
ρW | Density of water | kg/m3  (should be collected from ioput table in Requirement Section)

**Comment by JacquesCarette** [comment]
Great. I think the above should be a separate issue. Especially as it should be immediately fixeable. [It doesn't necessarily need to be fixed by you, I would prefer if you continued to be focused on finding such issues. If the fixing becomes a bottleneck for your work, we can revisit this.]

**Comment by halonazhao** [comment]
The missing symbol issues were fixed.
For h_min, it appears at three places in total.
![screen shot 2018-06-21 at 10 11 13](https://user-images.githubusercontent.com/28347043/41891961-7847ec5c-78e4-11e8-8e42-f06ca3ae719a.png)
![screen shot 2018-06-26 at 01 56 03](https://user-images.githubusercontent.com/28347043/41891980-8f39dbb4-78e4-11e8-90c2-f55b95c0e4a7.png)
![screen shot 2018-06-26 at 01 57 10](https://user-images.githubusercontent.com/28347043/41891982-908dc49e-78e4-11e8-9e27-fa388d1e40ac.png)
To me, the definition for h_min are not consistent from the first and the third places and I think the third one saying the coefficient makes no sense. But after seeing it again, I am not quit sure which one is right. What I did for this is redefining h_min and remove it from the aux table.

**Comment by smiths** [comment]
@halonazhao, this is another example where simplifications made from the original "manual" case study have had unfortunate consequences.  If you look at the original at:

https://github.com/smiths/swhs/blob/master/docs/SRS/PCM_SRS.pdf

You'll see that h_{min} is only used for the minimum thickness.  There is no reference to h_{min} as the minimum heat transfer coefficient.  Instead, we have h_P^{min} and h_C^{min} as two different minimum heat transfer coefficients.  My guess is that somewhere along the line someone decided that we didn't need two have two different constraints.  Maybe they didn't like having a symbol with both a subscript and a superscript?

If you modify the Drasil code to match the case study, this ambiguity will go away.  If there is a problem with doing this, then we should discuss it.

**Comment by halonazhao** [comment]
So do I redefine it to "minimum thickness" instead of its original definition "minimum heat transfer coefficients"? If so, what is the unit for this, m, m^-1, m^-2 ..?

**Comment by smiths** [comment]
Yes, redefine it as the minimum thickness of a sheet of PCM.  I'm pretty sure you can guess the units for thickness, but if you are really uncertain, they are m.  😄

**Comment by halonazhao** [comment]
Ok. The definition is fixed in https://github.com/JacquesCarette/Drasil/commit/5f8cd64ab92d6f08787ecca1d845e360dc936639.
Symbol collection application for SWHS case is completed. This issue can be closed.

**Comment by smiths** [comment]
Looks good.
