### ISSUE TITLE
Missing `symbol =` in equations of Data Definitions for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#699]
This change was first spotted in the Devi branch and was documented in #682:

Stable:
![image](https://user-images.githubusercontent.com/35268928/41603210-82ab0704-73aa-11e8-9724-411154c1dee6.png)
Generated:
![image](https://user-images.githubusercontent.com/35268928/41603262-9dfd7e74-73aa-11e8-8ece-8421f6a8198c.png)

Originally thought to be an easy fix, unfortunately attempts haven't fixed the issue.

Signifiicant things to note:

- GlassBR is the only example that uses `mkDataDef'` to build its QDefinitions
- Making any changes here https://github.com/JacquesCarette/Drasil/blob/c60280a142830e26ac11dfb51b0b7b15b2ff8b60/code/Language/Drasil/HTML/Import.hs#L142-L162 and https://github.com/JacquesCarette/Drasil/blob/c60280a142830e26ac11dfb51b0b7b15b2ff8b60/code/Language/Drasil/HTML/Import.hs#L168-L172 makes no change to the output or compilation whatsoever, can probably be removed (along with a lot of the other functions in this file)
- Making any changes here https://github.com/JacquesCarette/Drasil/blob/c60280a142830e26ac11dfb51b0b7b15b2ff8b60/code/Language/Drasil/Printing/Import.hs#L335-L352 and https://github.com/JacquesCarette/Drasil/blob/c60280a142830e26ac11dfb51b0b7b15b2ff8b60/code/Language/Drasil/Printing/Import.hs#L358-L361 changes the output in all the examples except for GlassBR: 
SSP generated 
![image](https://user-images.githubusercontent.com/28247301/41786966-f2193784-7614-11e8-8274-e6516caf4553.png)
GlassBR generated is still the same 
![image](https://user-images.githubusercontent.com/28247301/41786996-0a378d2a-7615-11e8-8964-cbe33e15803e.png)

There is a difference between how GlassBR's data definitions and the other examples' are being built that hasn't yet been detected.

**Comment by elwazana** [comment]
So I reintroduced the missing DDs section into Chipmunk as discussed in issue #682, but then I noticed that the same problem discussed here is occuring there. The `symbol = ` is missing:
![image](https://user-images.githubusercontent.com/35268928/41788714-914514c2-761a-11e8-9f8a-7f9621666676.png)

This is the commit that reintroduces DDs into Chipmunk which causes the problem: d7fdbde02a74f82835aa4e38ff2de8dd35a0f706

**Comment by JacquesCarette** [comment]
So it looks like the problem might be in the DD printer?

There used to be a hack that stored the data definition as an equation, which lead to all sorts of evil hacks in the code generation. I 'fixed' that and separated the definiens (B in the GlassBR example) from the definition (aka the right hand side), but then change the document printer accordingly.  Apparently I missed a case which wasn't used until now [maybe?].  At least, that's my best guess.

**Comment by szymczdm** [comment]
@JacquesCarette you're almost definitely correct. The case that was missed is most likely in DocumentLanguage.hs as the DDs are handled at a much higher level there, then transformed to something usable by the printers. I have a good idea of where this is happening, and will try to track it down soon.
