### ISSUE TITLE
Class instance cheat-sheet now out of date

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#703]
The file [DataTypes.xlsx](https://github.com/JacquesCarette/Drasil/blob/master/People/Dan/DataTypes.xlsx) in the Dan folder is now (almost certainly) out of date. Can you please update/correct it?

We'll also likely want to move that information onto a Wiki page at some point (just having the table should be enough), though auto-generating it would be ideal if it's easy enough.

Whichever of you'd like to take this on, please feel free.

**Comment by elwazana** [comment]
@szymczdm Hello Dan, I've started working on this and I'm just wondering if I should add `Label` and `LabelledContents`? The reason I'm asking is that neither of those data types are in the `Chunk` folder and everything in there before editing is.

**Comment by szymczdm** [comment]
It should be there once the implementation is complete.

**Comment by elwazana** [comment]
So should I put off doing it for now?

**Comment by szymczdm** [comment]
Yeah, just leave this issue open and come back to it once #629 / #567 are done.

**Comment by samm82** [comment]
@szymczdm What should be done about data types that aren't in the Chunk folder? Should I change the column to contain the name of the folder, instead of just a yes/no if it's in the Chunk folder?

**Comment by szymczdm** [comment]
@samm82 that sounds like a great idea!

**Comment by samm82** [comment]
PR open in #1847. I decided not to close this issue, since moving it to the Wiki/auto generating it could be done.

**Comment by smiths** [comment]
Yes, autogenerating DataTypes.xlsx makes sense, as does posting it on our web-page as part of the Drasil documentation.
