### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#704]
Can you please create a class diagram showing how our classes are built off one another? Preferably created using tikz or some other LaTeX graphics package. The reason for this is that it'll be far easier to modify an existing diagram over time if we have it encoded as (essentially) code instead of a flattened image.

For an idea of what I mean by class diagram, please see the [hierarchy redesign](https://github.com/JacquesCarette/Drasil/blob/master/Dan/Presentations/Presentation4ForErnieMileta/hierarchy-redesign.png). That's the, now deprecated, hierarchy we used to have.

Our current classes don't necessarily follow the same style, so we can consider the "is-a" relationships to be constraints, ex "must-have", or something of that ilk.

Once again, whoever wants to jump on this can feel free. The sooner this is completed, the better (for me), but don't drop whatever you're currently working on to take this on.

**Comment by samm82** [comment]
@szymczdm For the diagram, `SymbolForm` was on the old, deprecated class diagram, but isn't in the class spreadsheet and is never used - I'm assuming it should be removed from the new diagram?

**Comment by JacquesCarette** [comment]
If it is never used, it shouldn't be on the diagram -- and removed from Drasil too!

**Comment by elwazana** [comment]
@szymczdm Hello Dan, I have begun working on adding on to the diagram, I wanted to get suggestions on improving it or if you had a specific design in mind:
[ClassDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2161040/ClassDiagram.pdf)

**Comment by JacquesCarette** [comment]
So I don't quite understand this diagram. Well, not quite: the bottom part seems to indeed be our 'class diagram'. I just don't quite understand the top part?

`Chunk` has been renamed, it is now `HasUID`.

Don't worry about space. The diagram should be thought of being poster-sized, not page-sized.

**Comment by szymczdm** [comment]
For the class diagram, we should only have classes. I haven't quite decided how to document the data types  we've implemented, either a separate diagram (or diagrams), or a table would work. I'll figure that out soon.

**Comment by JacquesCarette** [comment]
@szymczdm beat me to it.  Separate.

**Comment by elwazana** [comment]
@szymczdm @JacquesCarette Ok so would this be better?
[ClassDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2164080/ClassDiagram.pdf)

**Comment by JacquesCarette** [comment]
Yes. But it makes it look like `Quantity` has 2 `HasUID` -- is that right?

Also, it makes it look like `Concept` may have (`Definition`, `Idea` and `ConceptDomain`), and I don't think that's right.  Dashed should be only for 'may have', while solid for 'isA'.

There are a whole bunch of 'HasFoo' classes in `L.D.Classes`. I think all of them should show up here.

**Comment by elwazana** [comment]
@szymczdm @JacquesCarette Hello Dr. Carette and Dan, I just wanted to post the diagram and ask for feedback on it before pushing it to the repository.

[ClassDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2164247/ClassDiagram.pdf)

I also wanted to ask you, what do you want me to do with the classes that aren't connected to any of the other classes (`NounPhrase`, `Referable`, etc)

**Comment by JacquesCarette** [comment]
Getting a lot better.
- All arrows should go 'mostly upwards'. IsUnit to Idea and IsLabel to HasLabel do not.
- Why did now all 'may have' disappear?
- Keep all the unconnected classes as is -- this will help us figure out what structure should be there.

**Comment by elwazana** [comment]
@JacquesCarette What is 'may have' supposed to represent? Because I thought that the `may have` classification is meant for connections involving `Maybe ...`., is this wrong? Can I get clarification on what exactly is intended by `may have`

**Comment by JacquesCarette** [comment]
That is correct, 'may have' is related to `Maybe`. And indeed, the connections (via `Maybe`) are about data-structures (now) rather than classes.  Thus if the current diagram only has 'isA' relations, which are done via class constraints, then it is correct.

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I've corrected the diagram in accordance with some of the notes you made above:

[ClassDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2166907/ClassDiagram.pdf)

**Comment by szymczdm** [comment]
Just to jump back to one of @JacquesCarette's earlier comments, why does `Quantity` have the extra `id'`? Also, `Quantity` should not have `typ'` or `symb'`, it should be connected to the `HasSpace` and `HasSymbol` classes. I think you used the data structure `QuantityDict` instead of the class while drawing that one. The only addition to a `Quantity` is `getUnit`.

**Comment by szymczdm** [comment]
Oh, also, `Quantity` is an `Idea` (which is a `NamedIdea` by extension, not directly).

**Comment by elwazana** [comment]
@szymczdm Sorry about that it was `QuanitityDict` before you told me to remove the Data tyes from it, I've corrected it along with connecting it to `HasSpace` and `HasSymbol`:

[ClassDiagram.pdf](https://github.com/JacquesCarette/Drasil/files/2167083/ClassDiagram.pdf)

**Comment by szymczdm** [comment]
Awesome!

**Comment by elwazana** [comment]
@szymczdm Hello Dan, Should I start creating the Data Types Diagram? If so should I create a separate issue for tracking it?

**Comment by JacquesCarette** [comment]
This diagram is now good. We can learn from it, and figure out what we need to fix to make it easy to explain what is going on.

I think it is worth starting on the Data Types diagram -- and yes, do it in a separate issue, as I'm sure we'll want to continue talking about the classes, and we don't want to mix the two conversations.
