### ISSUE TITLE
Move stable into Sub Folders

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#713]
Right now, PDFs in stable for GlassBR and GamePhysics examples don't build and images don't display in the HTMLs because of how the subfolders are set up. Figures are located in code/datafiles/GlassBR/, the path to stable TeX/HTML is code/stable/glassbr/, and the path to stable TeX or HTML is code/build/GlassBR/SRS/ or /GlassBR/Website/, respectively. From build. the path to figures is ../../../datafiles/GlassBR, but from stable, it is ../../datafiles/GlassBR, with one less "../". The stable has the extra "../" anyways, since stable and build must be the same, but this results in stable not finding the images it needs, which leads to TeX failing and HTML not displaying them.

I propose we sort the stable folder into a similar SRS and Website folders as build, as it will (a) keep the repo more organized and consistent, and (b) make it a lot easier to work on examples in Drasil.

I've marked this as "high priority", despite it being an easy fix, as I would like to implement this change before I work on GlassBR in Drasil. Let me know if this sounds good @JacquesCarette and I will do it as soon as possible.

**Comment by szymczdm** [comment]
I believe this change has been discussed in the past and never acted on, so I'm all for it. Standardizing things will make everything cleaner and clearer.

**Comment by JacquesCarette** [comment]
Yes, go for it!

**Comment by samm82** [comment]
What should I do with the MG - make a separate folder for the it (not necessary for accessing figures), leave it in the glassbr folder, or just put it in the SRS folder?

**Comment by JacquesCarette** [comment]
I think this is actually a question for @smiths.

**Comment by samm82** [comment]
@smiths 

1. Should all examples be sorted into SRS and Website?
2. Where should MGs go? In SRS, in an MG folder, in a docs folder with the SRS stuff, left loose?

**Comment by smiths** [comment]
Yes, all of the examples should go into the same folder structure for consistency.  Please create the SRS and Website folders for all examples.

I'm not sure I understand your question about MGs.  I'm assuming that we are talking about the Drasil repo.  We don't have MGs in Drasil, do we?   We can worry about where to put MGs once we are actually generating them.  That seems like a problem for the future, unless I am misunderstanding something?

**Comment by samm82** [comment]
@smiths MGs aren't built by Drasil, but they do exist in stable for some reason. Should they even be there? There are commented out lines in the Makefile that deal with differences between the generated and stable MGs that I'm guessing are for the future.

**Comment by smiths** [comment]
No, the MGs should no longer be anywhere in Drasil.  Please remove them.  I confirmed this verbally with @JacquesCarette.  We will be adding design information back into Drasil, but we will be starting fresh.  The current flotsam and jetsam that is floating around on MGs won't help us in the future.

**Comment by samm82** [comment]
So remove everything about MGs in Drasil?

**Comment by smiths** [comment]
Yes.

**Comment by samm82** [comment]
Similar issue - built SSP can't find pictures because they are in the stable folder. Should I put them in datafiles like GlassBR and GamePhysics and change the file paths in gen and stable? @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes.
