### ISSUE TITLE
Deprecated Code Removal Exercise

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#714]
This is more of a note-to-self than anything, but I want to do an exercise on removing deprecated code from the examples once we've finished merging in the Devi branch and creating `Label` and whatnot.

We should do a run-through of each of the examples to find old pieces of code that are no longer being used (even though they might look like it!). I'll start by choosing one example and going through it live with the rest of you. Then we can divide up the remaining examples and you'll do the same thing on your own.

I've noticed (in a few places, namely Body) that there's `Document` level stuff that isn't actively being used (it may have been once, but not anymore) and it could be slowing down advancement of features because of weird edge-cases that we've long since resolved with newer code.

Again, this is a note-to-self for the time being, but we'll probably tackle it sometime in the next couple of weeks.

**Comment by JacquesCarette** [comment]
I am going to close this as I think this is obsolete. The addition of specific exports and imports to the vast majority of the files has allowed GHC to issue warnings on all unused code, and these have been fixed.

There may well be some unused functions still, which are exported by a package but never used, but that requires quite a different workflow than that outlined here.
