### ISSUE TITLE
Proposal for LabelType Getter/Lens

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#719]
It was mentioned in #695, that `Section` should become a record type for ease in access of the different parts that make it up.

https://github.com/JacquesCarette/Drasil/blob/1a7065e8116d3ec8b157d3a902c6657ed8c337dd/code/Language/Drasil/Document.hs#L66-L69

Since a `Section` currently has both a `RefAdd` and `ShortName`, replacing those fields with a label will cause a problem in terms of getting the reference address (not the shortname though since a shortname lens is in the process of being implemented).

I propose creating a getter `getLblType` that will go into the label of a data type to get the reference address so that the data types can be defined as instances of the class `Referable`. Is this too hacky?

***

On the other hand, with the introduction of a `HasShortName` and `HasLabel` class, is it possible that the `Referable` class be removed completely? @szymczdm @JacquesCarette 

Asking because `ShortName` has replaced the `RefName` that used to be there (now encapsulated in `Label`), and `RefAdd` is now also in `Label`, which will eventually leave only `rType` 
https://github.com/JacquesCarette/Drasil/blob/4fca08b95e561b4cb7ba3fecc0a68bba4b1cb258/code/Language/Drasil/Reference.hs#L184-L189.

**Comment by JacquesCarette** [comment]
The `Referable` class should stay. Though there might be a need to split it into `HasRefAddress` and `HasRefType`. Then one could build lenses for those, which would take care of getting a `RefAdd` from a `Section`.

**Comment by niazim3** [comment]
As of bfd0225, a `HasRefAddress` class has been created.

Although, there isn't really a way to lens to a specific enumerated type (that I know of), so attempting to define how `Label` is an instance of the `HasRefAddress` class poses some problems, as simply adding
```
instance HasRefAddress Label where getRefAdd = lblType
```
for 
```
-- import reference address from Language.Drasil.References?
data LblType = RefAdd String | MetaLink String | URI String

-- Used for referencing; has to be pure ASCII
data Label = Lbl
  { _uniqueID  :: UID --internal, unique
  , _lblType    :: LblType
  , sn         :: ShortName
  }
makeLenses ''Label
```
is not a solution.

**Comment by niazim3** [comment]
I see; implementing that would mean that a metalink or URI can also be a reference address. Is this desirable behaviour? Or would some pattern matching be necessary to throw errors if a `Label` has a `LblType` of `MetaLink` or `URI` instead of `RefAdd`?

**Comment by JacquesCarette** [comment]
In theory, any of those is a valid reference address - it just means an external reference instead of internal. So they really should all be fine.
