### ISSUE TITLE
Unable to generate code for Integral / Summation

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#72]
No code making function implemented yet for Integral/Sum.

**Comment by szymczdm** [comment]
Wait on implementing this until #74 is finished.

**Comment by JacquesCarette** [comment]
Note that #74 is now done and closed. Still, it's not clear to me how to implement this.

**Comment by niazim3** [comment]
This is an issue for generating python code for Integrals/Summation, correct? (https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html)

**Comment by JacquesCarette** [comment]
Although it is entirely true that we cannot do this right now, there also doesn't seem to be any pressing issue to do so. I'm not sure it is useful to have such a long-standing "feature request" open as an issue.
