### ISSUE TITLE
Allow choice for formatting descriptions of models and definitions

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#724]
As mentioned in #682, there should be an option as to how the descriptions for instance models, theoretical models, general definitions and data definitions are output (format-wise); that is because some readers/users may find it more appealing to have smaller tables (more easily achieved through a paragraph description) and others may find the automated description more easy to read if it's in a list format.

**Comment by smiths** [comment]
This is a good issue.  We don't yet have much in the way of user configurable options for the output.  We really starting reaping the benefits of our approach when we can generate different views of the documentation.

**Comment by balacij** [comment]
Well, we actually indirectly spoke about this ticket when @BilalM04 presented the alternative flavours of theory renderings in Markdown. I believe we ended up unanimously agreeing that the existing design is best. If someone later has a concrete design choice that they want to make, then I think we can go from there in a new ticket. As it stands, this ticket doesn't seem readily actionable.
