### ISSUE TITLE
Add notes field for models and definitions

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#727]
This issue comes from attempting to reduce discrepancies in the logs (documented in #682).

For now, `Notes` will contain a `[Sentence]` that'll be rendered as a new field in the produced table.

**Comment by halonazhao** [comment]
I started to do the same thing for Swhs, Ssp and NoPcm. I'm guessing that you would do these for Devi's cases? @niazim3

**Comment by niazim3** [comment]
Yes, these changes are for Devi's cases. However, I noticed that in #507 (for example), the missing information was removed from the stable versions as well for your cases. With this implementation, we can bring back that information and close issues related to #507.

@halonazhao , can you please clarify what you mean by you started doing the same thing for Swhs, ssp and nopcm? Are you creating something similar to the notes field proposed here?

**Comment by halonazhao** [comment]
Yes, adding notes field. But the thing is that if you are doing this on devi's branch, that means that you are adding notes to the new SSD section which is different from the master branch. I am wondering that I should do this based on the new SSD section or the master one. 
@szymczdm ?

**Comment by smiths** [comment]
Great to see this discussion between @niazim3 and @halonazhao.  It is important that we communicate to avoid duplicate or incompatible efforts.  Going forward, I think we should have Derivation and Notes fields.  The derivation information can go in the Derivation, and anything else that is left over can go in the Notes.

**Comment by niazim3** [comment]
Thanks for the input @smiths! Just documenting here from a face to face conversation with @JacquesCarette and @halonazhao that the notes field addition should be done in the `Devi` branch (instead of the master branch), and that since @halonazhao is done adding the derivation information on the `yuzhi` branch, any notes that need to be added for her examples will be done in the `Devi` branch.

**Comment by halonazhao** [comment]
Hello @niazim3 ,
I have merged `master` and `devi` branch to `yuzhi` branch. I will start adding notes on my branch. I will merge devi branch frequently to my branch. Feel free to make any changes.

**Comment by halonazhao** [comment]
This issue can be closed. All note fields have been added and implemented.
