### ISSUE TITLE
Sort References by Author

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#729]
In GlassBR, as noted in the comments of #721, references are sorted by UID instead of by author. As the convention that UIDs should be of the form "authorYYYY" is not enforced, we need to make sure that correct sorting takes place.

Also, if two references have the same author, should they then be sorted by year or by title? 
@smiths @JacquesCarette

**Comment by samm82** [comment]
So `Citation` is defined here:

https://github.com/JacquesCarette/Drasil/blob/fc388fc5cb9e30166a0feca9e55dd80e86d75ac3/code/Language/Drasil/Chunk/Citation.hs#L93-L98

and the sorting happens here:
https://github.com/JacquesCarette/Drasil/blob/fc388fc5cb9e30166a0feca9e55dd80e86d75ac3/code/Language/Drasil/Reference.hs#L95-L101
https://github.com/JacquesCarette/Drasil/blob/fc388fc5cb9e30166a0feca9e55dd80e86d75ac3/code/Language/Drasil/Reference.hs#L266-L267

I'm going to make an `authorSort` similar to `uidSort`. I'm going to make a class `HasFields` with a lens to pull out the `fields` from `Citation`; how should I go about extracting the author from the list of `CiteField`?

Can I proceed with this? @JacquesCarette @szymczdm @smiths

**Comment by smiths** [comment]
Yes, you should proceed with this task.  You will have to wait for @JacquesCarette and @szymczdm for specific advice on your question about `CiteField`.

**Comment by JacquesCarette** [comment]
There are combinators somewhere to grab the author from the `fields`. It should be an error if there isn't one.  I guess you can start by looking in the printing code. The combinator might not be there, but it should be used there (at least).  Secondary sort key should be year.  [And we can later make that a parameter too!]

**Comment by samm82** [comment]
I added HasFields in 2621a9a, but I can't seem to find a combinator that grabs the author... What exactly am I looking for @JacquesCarette?

**Comment by JacquesCarette** [comment]
Still looking for the right combinator.  But I did find `compCiteField` in L.D.HTML.Print which seems like a useful function for sorting.

**Comment by JacquesCarette** [comment]
Looks like the kind of filter on `[CiteField]` that I was thinking of is no longer in use. Or it might have been on another related type.

**Comment by samm82** [comment]
Now I have it to sort by `People`, but it cannot deduce (Ord Person). I need to sort by surname, but I can't seem to figure out a way to do that. Should I make a class `HasSurname`?

**Comment by JacquesCarette** [comment]
You'll need to hand-implement `Ord Person` in `Language.Drasil.People`. You won't need an extra class for that.

**Comment by samm82** [comment]
In 36119317, I changed the UID of a reference to ensure that they are actually being sorted by author and not UID, but it seems to be sorting by UID still, despite `authorSort` being used here:

https://github.com/JacquesCarette/Drasil/blob/361193177217aabe85a38ca2ce8ccc6a0636222f/code/Language/Drasil/Reference.hs#L97-L100

Did I implement `Ord` correctly? @JacquesCarette @szymczdm

**Comment by JacquesCarette** [comment]
You don't need to involve `Ord` at all.  I wonder if something downstream extracts things from the `BibMap` using a different order.  It is odd to sort and then put into a `Map`.

**Comment by samm82** [comment]
Removing `Ord` throws `Could not deduce (Ord Language.Drasil.People.Person) arising from a use of 'compare'` - should I make a `getLastName` function as opposed to a `getAuthor` one?

**Comment by Mornix** [comment]
I believe it's sorted before being inserted into the map so it can be looked up by `uid` or by the index it would be in the resulting enumerated list (the `zip`s). It seems something is looking them up by `uid` (or a list of `Citation`s in some other order) causing the discrepancy. If I were to guess, `citationsFromBibMap` is could be the function that is missing `authorSort` resulting in the current behaviour.

**Comment by JacquesCarette** [comment]
So how is `compare` on `Person` implemented?  It could be that the bug is there!

**Comment by samm82** [comment]
I don't know if you want be to be more specific, but:
https://github.com/JacquesCarette/Drasil/blob/361193177217aabe85a38ca2ce8ccc6a0636222f/code/Language/Drasil/Reference.hs#L271-L278

Do I need to implement an ordering of `Person` that sorts by last name? I'm not exactly sure how I would do that, but that seems like the solution here.

**Comment by JacquesCarette** [comment]
So `authorSort` seems fine.  But clearly, from the error message, something *else* sorts on `Person` (thus the need for `Ord`). That is quite possibly the `Map` itself.

So maybe adding an `Ord` instead for `Person` that sorts by last name (then first name for ties) would be good.

**Comment by samm82** [comment]
I have an idea that might make this easier - instead of just adding `Ord` to `Person`, we should also add one to `Citation`, that sorts by author name [first by last name, then by first, (then by middle?)], and then by year. Ex. ASTM is the author for ASTM2009, ASTM2012, and ASTM2016, so year should definitely be a factor.

**Comment by samm82** [comment]
I implemented this change, but it caused diffs in other examples because they weren't being sorted by author, and now they are. I'll update stable for them - my only concern is that any hardcoded references will now be wrong, and might be hard to keep track of. Let me know if you have any concerns. @JacquesCarette

**Comment by JacquesCarette** [comment]
Some time ago, I removed the `Ord` instance for `Citation`... because different citation styles use different means of sorting. The right fix is to create a `compareXXX` function (instead of an `Ord` instance). That way when we pick a citation style, we can also pick the sorting style that goes with that.

**Comment by samm82** [comment]
Oh OK - I'm going to fix the merge issues with SubPackages, then implement this change. Should I close the PR for now?

**Comment by JacquesCarette** [comment]
As it is not ready for merge, yes please.

**Comment by samm82** [comment]
What sorting styles should be implemented? @JacquesCarette @smiths @szymczdm

**Comment by JacquesCarette** [comment]
The two that I know are alphabetical by author last name (disambiguated by first name initial, then year, then I think title). The other is order of appearance in the document! I don't know if there are multiple ways to sort people's names.  In any case, best to not have any `Ord` instances until we really need them.

**Comment by samm82** [comment]
Do you think it would be faster if I just deleted the branch and started over? @JacquesCarette

**Comment by JacquesCarette** [comment]
I don't think that's necessary. For the examples, alphabetical by author. I wouldn't even bother implementing the other for how. There are other higher priority things to do.

**Comment by samm82** [comment]
Can `Ord` be kept for `Person`, or should it be removed in case there is a sorting method we want to use later that sorts by author in a different way @JacquesCarette?

**Comment by samm82** [comment]
Also, when comparing two citations, if the first author matches, should the sort then move to the second author or the year? @JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
No idea - but some googling around got me to https://tex.stackexchange.com/questions/51434/biblatex-citation-order, which then led me to section 3.6.1 and appendix C.1, C.2 and C.3 of http://muug.ca/mirror/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf.

**Comment by samm82** [comment]
So what is the status of this issue? Is the fix implemented well enough for the time being/should I make another low priority issue for implementing a sort by order in document? @JacquesCarette @smiths

**Comment by JacquesCarette** [comment]
If the implementation uses `sortBy` with a comparator and not `Ord`, then yes, it is good enough for the time being [and yes, please add an issue].

**Comment by samm82** [comment]
I thought I removed `Ord` for `Person`, but apparently I didn't, so I'll implement the change and then open a PR and create the issue.

**Comment by samm82** [comment]
Can be closed with merge of #805
