### ISSUE TITLE
Should I try to merge Master to Yuzhi branch?

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#733]
Since I have added some information like input, output and derivation fields to `yuzhi` branch, I think it's better that I add the note based on the `yuzhi` branch. #727 

But my concern is that since that branch is running so behind, I am not sure whether I'm able to fix the errors and whether it's a good time to merge? Is there anything that I should take care if I do merge?

@szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
It's usually a bad idea to have 'long running' branches, as it causes all sorts of problems like this.

But in any case: you should try to merge master into your branch. I do believe there are ways to attempt to merge, and then discard the results if they are a mess.  But I forget how.

**Comment by halonazhao** [comment]
Ok. I just want to make sure that we still want to use the new way to generate SSD section?

**Comment by JacquesCarette** [comment]
I don't understand what you mean by 'new way'?

**Comment by halonazhao** [comment]
New way means using `SSD{IM[]DD[]...}`.
Old way means `Verbatim[S4]`.

**Comment by JacquesCarette** [comment]
Definitely new way.

**Comment by halonazhao** [comment]
Merged. This issue can be closed.
