### ISSUE TITLE
Collapse Summation and Integral into one constructor

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#74]
Summation and integral should be created using one constructor similar to:

```
Integral Symbol DomainDesc Expr
```

Where Integral, Symbol, and Expr are self explanatory (already exist in the current code). DomainDesc will take the place of bounds in that it will give us a brief description of the domain, including bounds if necessary.

Summation will also collapse into this as a sum and an integral are essentially the same thing across different domains (ie. continuous vs. discrete).

**Comment by szymczdm** [comment]
@JacquesCarette I'm going to assign this to you since I think you already did it.

Can you confirm that this is finished in the changes you made to Expr?

**Comment by JacquesCarette** [comment]
This is definitely not done:

    data EOperator where
      Summation :: DomainDesc -> Expr -> EOperator
      Product :: DomainDesc -> Expr -> EOperator
      Integral :: DomainDesc -> Expr -> EOperator

is the definition. Types will help with this, as the `DomainDesc` will let us know which is which.

**Comment by JacquesCarette** [comment]
And now done!
