### ISSUE TITLE
Update automatic description generation for specific cases

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#740]
As mentioned in #682, it's incorrect and awkward to say that
```
\item{$is\_safe1$ is the true when calculated probability is less than tolerable probability (Unitless)}
``` 
(from GlassBR).
This is being produced since the default and only automatic description generation is `symbol` "is the" "symbol description".

Updates need to be made so that the above line (for example) should instead say 
```
\item{$is\_safe1$ is true when calculated probability is less than tolerable probability (Unitless)}
```
.

**Comment by niazim3** [comment]
Same thing needs to be done for 
```
\item{$is\_safe2$ is true when load resistance (capacity) is greater than load (demand) (Unitless)}
---
\item{$is\_safe2$ is the true when load resistance (capacity) is greater than load (demand) (Unitless)}
```
.

- [ ] Check all the other examples for such occurrences
- [ ] Revert changes in stable (html and tex) to not match the generated version (done to avoid discrepancies in the log) so that it's easier to see the effect of updated implementation

**Comment by niazim3** [comment]
### Other related things to do:
#### Chipmunk
- [ ] update definitions of τi, ωA, and ωB to not include "is the" in their definitions (results in a display like "τi is the **is the** torque applied to the i-th body (N⋅m)"
- [ ] remove the word "the" from the beginning of pCM's definition "pCM is the **the** mass-weighted average position of a rigid body's particles (m)"

#### GlassBR
- [ ] removal of "the" from a definition/implementation that's causing "Capacity is the **the** load resistance calculated and..." in "Individual Product Use Cases" section

**Comment by niazim3** [comment]
After looking into this, I'm unsure if updating the functions that simply pair inputs with "is the" is the right stage for this problem's potential solution. Essentially, what would need to be updated is https://github.com/JacquesCarette/Drasil/blob/fcf67fec5c8864e62ff90ce919017cc56623ae88/code/Language/Drasil/HTML/Print.hs#L268-L269 https://github.com/JacquesCarette/Drasil/blob/fcf67fec5c8864e62ff90ce919017cc56623ae88/code/Language/Drasil/TeX/Print.hs#L373-L376, where I see 2 potential routes, both of which are hacky/not the best design/probably what we shouldn't be looking for: 
1. check if passed in `b` and `x` are instances of the `HasSpace` class, and if the `space` is `Boolean`, append just "is" instead of "is the" (According to https://stackoverflow.com/questions/35785176/check-whether-a-type-is-an-instance-of-show-in-haskell, something like this would be considered bad design)
2. unpack the input symbols somehow in the called `p_spec` and `spec` functions
https://github.com/JacquesCarette/Drasil/blob/fcf67fec5c8864e62ff90ce919017cc56623ae88/code/Language/Drasil/HTML/Print.hs#L80-L81 https://github.com/JacquesCarette/Drasil/blob/fcf67fec5c8864e62ff90ce919017cc56623ae88/code/Language/Drasil/TeX/Print.hs#L237 and if there is text that was turned into a symbol that happens to be "is" (https://github.com/JacquesCarette/Drasil/blob/fcf67fec5c8864e62ff90ce919017cc56623ae88/code/Example/Drasil/GlassBR/Unitals.hs#L218), assume this is a boolean value by the convention that boolean variables usually start with `is...` and append "is" instead of "is the".

INSTEAD, what can also be done is stick to the "is the" convention used by Drasil, and update the mentioned-above definitions of the variables that look awkward to
"is_safe2 is the true when load resistance (capacity) is greater than load (demand) (Unitless)" --> "is_safe2 is the **variable that is assigned** true when load resistance (capacity) is greater than load (demand) (Unitless)" or something to that effect.

@szymczdm Can you please take a look to see if a solution can be implemented?

**Comment by JacquesCarette** [comment]
The fact that we hard-code "is the" in the generation is quite evil of us. Yes, that is correct 99% of the time, but that 1% becomes a real pain.

I think your 'alternative' is, for now, the 'better' solution.  An even better solution would need us to have more information about the structure of `Definitions` to properly tailor the English. Which, long term, is the right thing to do. Could you create an enhancement issue for that?

**Comment by niazim3** [comment]
@smiths Since the definitions for `is_safe1` and `is_safe2` will be updated, should the GlassBR SRS in the case studies be updated as well? Or would it be better to leave it as is there so the discrepancy is easily visible?

**Comment by smiths** [comment]
Yes, please update the manual version of the GlassBR SRS to match the revisions to the automated version.  As much as possible I would like the two versions to be the same, to avoid future confusion.
