### ISSUE TITLE
QDefinition Does Not Have a Defn

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#741]
When I was implementing symbol collection to GamePhysics, the symbol `r(t), a(t), v(t)` weren't be collected. I found out that they are defined as `Data Defintion` at a type `QDefinition`. 

`linDisp :: QDefinition`
`linDisp = mkDataDef QP.linearDisplacement dispEqn`
The second argument will be collected through QDefinition, but the defined data `linearDisplacement` can not be retrieved again from QDefinition Structure becasue it doesn't have a defintion so that the sentence of defn won't be collect by sentences.

There are comments from the code as this:
https://github.com/JacquesCarette/Drasil/blob/54787887dcc7df4555520109c45d391810708980/code/Example/Drasil/GamePhysics/DataDefs.hs#L31-L52

Any suggestions here?  @JacquesCarette

**Comment by JacquesCarette** [comment]
I'm going to bring in @szymczdm here. I forget the exact details of all our data-structures.  Plus, it is a higher-level design question: there seems to be a mismatch between "what we want to say" and "what our structures let us say".  This relates to the inventory of classes/structures being carried out (I forget by whom exactly).

**Comment by szymczdm** [comment]
Hmm, I looked at this for a little while and it seems like we discard `defn` to create `QDefinition`s, which is weird in and of itself (probably a relic from way back before we had `defn` as a separate entity from `term` actually), but you should still be able to collect the symbol from the QDefinition itself and collect any other used symbols from its equation.

**Comment by halonazhao** [comment]
Ok. I have to look into this problem deeper because I just found out that when we change to use `IM` `TM` and etc to generate SSD section. Symbols aren't collected properly. Maybe the problem is not about `QDefinition`.

**Comment by halonazhao** [comment]
If QDefinition doesn't need new design, I will close this issue for now.
