### ISSUE TITLE
Compress spacing in model and definition descriptions

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#744]
In the Devi branch (#530) and in PR #743, it was mentioned that it would be better if the automated descriptions in the tables for models and definitions were more compressed (i.e. by removing unnecessary spaces and indents), for example:
![image](https://user-images.githubusercontent.com/28247301/42232789-8aa1fa26-7ebd-11e8-90b1-405db0f3a989.png)

This was worked on for the HTML side of things, but has yet to be investigated for LaTeX/PDF generation.

**Comment by niazim3** [comment]
Adding
![image](https://user-images.githubusercontent.com/28247301/42242254-409d5fec-7edb-11e8-97f3-4d3612b25b6e.png)
compresses the spaces between the listed items:
![image](https://user-images.githubusercontent.com/28247301/42242350-8dcb2470-7edb-11e8-8daf-9169eddcd8a1.png)

**Comment by niazim3** [comment]
The only potential problem with implementing this change, however, is that anything else that uses the `\begin{description}...\end{description}`. That gets compacted as well, which is probably not desirable:
![image](https://user-images.githubusercontent.com/28247301/42243215-94bf7c24-7ede-11e8-87d2-8c2ee404d113.png) 
gets changed to 
![image](https://user-images.githubusercontent.com/28247301/42243246-b396b1d0-7ede-11e8-9524-5f8823dcf747.png).

Knowing this, is this an optimal solution for this issue? @JacquesCarette @szymczdm

**Comment by smiths** [comment]
I don't like the compacted version of the Assumptions.  Can a new \setdescription be executed before each description environment?  The \setdescription parameters would be then set according to the context where the description appears?

**Comment by JacquesCarette** [comment]
I agree with @smiths -- while I like the compressed description, the compressed assumptions is too squeezed.

Luckily the package `enumitem` has options for just that! [see http://www.texnia.com/archive/enumitem.pdf for detailed documentation].  The simplest would be to use explicit spacing commands for the version put out for descriptions rather than using global options.  Perhaps even better would be to use `\newlist` (see section 7) to create a new environment for description lists. That would make later customization even easier.

**Comment by niazim3** [comment]
Thanks for the feedback @smiths and @JacquesCarette!

Will be updating the tex generation to
```
\usepackage{enumitem}
\newlist{symbDescription}{description}{1}
\setlist[symbDescription]{noitemsep, topsep=0pt, parsep=0pt, partopsep=0pt}
```
, where the descriptions will have to be made using 
```
Description & \begin{**symbDescription**}
              \item{${\mathbf{a}_{i}}$ is the the i-th body's acceleration ($\frac{\text{m}}{\text{s}^{2}}$)}
              \item{$t$ is the time (s)}
              \item{${\mathbf{v}_{i}}$ is the velocity of the i-th body's velocity ($\frac{\text{m}}{\text{s}}$)}
              \item{$g$ is the gravitational acceleration ($\frac{\text{m}}{\text{s}^{2}}$)}
              \item{${\mathbf{F}_{i}}$ is the force applied to the i-th body at time t (N)}
              \item{${m_{j}}$ is the mass of the j-th particle (kg)}
              \end{**symbDescription**}
```
.

**Comment by niazim3** [comment]
Whoops, thanks, I didn't double-check that the code was bolded for emphasis (updated to actually be bold).

**Comment by JacquesCarette** [comment]
I suspected that that was the case, but wasn't 100% sure.

**Comment by niazim3** [comment]
The following file is an example of what the updates in #743 generate [Chipmunk_SRS.pdf](https://github.com/JacquesCarette/Drasil/files/2163886/Chipmunk_SRS.pdf).

**Comment by smiths** [comment]
Looks good.
