### ISSUE TITLE
Stand off distance data definition is missing from Drasil

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#748]
(Moved from #350)
There is a data definition for stand off distance (GlassBR) in the manual version of the SRS: 
![image](https://user-images.githubusercontent.com/28247301/42283674-29f2d220-7f78-11e8-8d7c-8bbc02d36334.png), but not in the generated one. @smiths, should this missing information be added to Drasil or is it to be removed from the manual version?

**Comment by samm82** [comment]
Being worked on in #675

**Comment by smiths** [comment]
Thanks @samm82.  Very observant @niazim3.  😄 I have been working on the manual version of GlassBR so that the requirements and design are more in sync.  This means massive changes to the design and small changes to the requirements.  I'll update you when the design is ready for review.
