### ISSUE TITLE
GlassBR's "Tolerable pressure" vs "Tolerable load"

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#752]
(Moved from #350)
DD8 in stable has the label "Tolerable Pressure" 
![image](https://user-images.githubusercontent.com/28247301/42294349-237c7b90-7fae-11e8-9eb6-02e10222130d.png)
whereas the generated data definition is labelled "Tolerable Load"
![image](https://user-images.githubusercontent.com/28247301/42294369-422e5536-7fae-11e8-8781-01627b676da4.png)
... we should probably stick to one to reduce ambiguity. @smiths, is there a preference for one or the other?

**Comment by smiths** [comment]
Great catch @niazim3.  I don't know the source of the discrepancy, but I prefer load.  Can you please update the GlassBR example to use q as the tolerable load, not tolerable pressure.  The manual, stable and generated should be consistent.  I believe in this case that means updating the manual version to agree with the stable version.

**Comment by samm82** [comment]
## TODO

- [ ] Update Drasil
  - "Tolerable pressure" is used in some of the notes in other Data Definitions
- [ ] Update caseStudies
