### ISSUE TITLE
Difference in Introduction between Drasil and caseStudies

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#753]
## Generated Drasil Intro

"Software is helpful to efficiently and correctly predict the blast risk involved with the glass slab. The blast under consideration is any kind of man-made explosion. The software, herein called GlassBR aims to predict the blast risk involved with the glass slab using an intuitive interface.

The following section provides an overview of the Software Requirements Specification (SRS) for GlassBR. **This section explains the purpose of this document, the scope of the system, the organization of the document, and the characteristics of the intended reader.**"

## CaseStudies Intro

"Software is helpful to efficiently and correctly predict the blast risk involved with the glass slab. The blast under consideration is any type of man-made explosion. The software, herein called Glass-BR, aims to predict the blast risk involved with the glass slab using an intuitive interface. The following section provides an overview of the Software Requirements Specification (SRS) for Glass-BR. **This section explains the purpose the document is designed to fulfill, the scope of the requirements, and the organization of the document: what the document is based on and intended to portray.**

---

Not sure if this is being covered in another issue or if someone else should do this, but should I fix these differences? @smiths 
- [ ] Merge the two paragraphs into one (or split the one into two?)
- [ ] Make the bold sections the same (I personally think the caseStudies one is more clear).

Or does it not really matter that they are different?

**Comment by szymczdm** [comment]
I believe at some point (a long while ago) we decided the generated version was "better", but I'd wait for @smiths to weigh in.
