### ISSUE TITLE
Create drasil-printers SubPackage

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#766]
There should be a new subpackage called `drasil-printers` that handles code for actually printing the documents. A starter list of files includes:

- [x] `Language.Drasil.Format`
- [x] `Language.Drasil.Output.Formats`
- [x] `Language.Drasil.TeX`
- [x] `Language.Drasil.HTML`
- [x] `Language.Drasil.Make`
- [x] `Language.Drasil.Printing`

It is possible that some code will be moved to `Language.Drasil.Development` to facilitate this change.

**Comment by elwazana** [comment]
@JacquesCarette Hello Dr. Carette, I'm just wondering if all the files in `drasil-printers` should be exposed? Or should I create an export file similar to `Language.Drasil`?

**Comment by JacquesCarette** [comment]
I believe that the number of exports from `drasil-printers` should be really small. A handful of functions. So an export file, yes, but a minimal one.

**Comment by elwazana** [comment]
@JacquesCarette @szymczdm  Hello Dr. Carette and Dan, I've worked on creating the subpackage and an error I've run into once I've transferred a few files over from `drasil-lang` is:
 
![image](https://user-images.githubusercontent.com/35268928/42768442-82b02574-88ed-11e8-843c-2f0e16b23ba0.png)

I've tried working through it with @samm82 but we can't figure out what the error is pointing at.

**Comment by szymczdm** [comment]
Looks like the wrong `phrase` function is being used there. It should fix itself if you remove `^. term` from the highlighted part.

**Comment by elwazana** [comment]
@szymczdm @JacquesCarette Hello Dan and Dr. Carette, a problem I've run into which is related to the above is that there are a few things in `Language.Drasil. and in some of the printer files that have the same name but different meanings:

`Expr` in `drasil-lang`  has the type:
```Haskell
data Expr where
  Dbl      :: Double -> Expr
  Int      :: Integer -> Expr
  Str      :: String -> Expr
  AssocA   :: ArithOper -> [Expr] -> Expr
  AssocB   :: BoolOper  -> [Expr] -> Expr
  Deriv    :: DerivType -> Expr -> UID -> Expr
  C        :: UID -> Expr 
  FCall    :: Expr -> [Expr] -> Expr 
  Case     :: [(Expr,Relation)] -> Expr 
  Matrix   :: [[Expr]] -> Expr
  UnaryOp  :: UFunc -> Expr -> Expr
  BinaryOp :: BinOp -> Expr -> Expr -> Expr
  Operator :: ArithOper -> DomainDesc Expr Expr -> Expr -> Expr
  IsIn     :: Expr -> Space -> Expr 
  RealI    :: UID -> RealInterval Expr Expr -> Expr 
```

but `Expr` in `Printing/AST.hs` is defined as:
```haskell
data Expr = Dbl   Double
          | Int   Integer
          | Str   String
          | Case  [(Expr,Expr)]
          | Mtx [[Expr]]
          | Row   [Expr]
          | Ident String
          | Spec  Special
          | Sub   Expr
          | Sup   Expr
          | MO    Ops
          | Over  OverSymb Expr
          | Fenced Fence Fence Expr
          | Font  Fonts Expr
          | Div   Expr Expr 
          | Sqrt  Expr     
          | Spc   Spacing
```

These two seemed to be conflicting in a file so I hid `Expr` in `Language.Drasil` import for that file but then I get this error:
![image](https://user-images.githubusercontent.com/35268928/42830414-58e8542e-89b9-11e8-8888-6ec737d7e336.png)

A possible solution I've thought of is to rename one of them but I wanted to pass this idea for review before proceeding with it.

**Comment by szymczdm** [comment]
Don't rename Expr. You'll want to change the way you import from Language.Drasil. There are two approaches you can use:

`import qualified Language.Drasil as L` where L can be any name which you'll need to prepend to uses of Language.Drasil functions and data types (ie. instead of `Dbl` you'd use `L.Dbl` for Language.Drasil.Expr doubles). Then you can use the Printing Expr unqualified (ie. `Dbl` will assume Printing's Expr).

If you're using a lot of functions that only appear in Language.Drasil, then qualified imports can become cumbersome since you *must* use the qualified name before the function at all times. In that case, I believe it's also possible to do:

`import Language.Drasil as L` (note the lack of `qualified`) and then only use the L where you need to explicitly differentiate between Language and Printing.

**Comment by elwazana** [comment]
@szymczdm @JacquesCarette Hello Dr. Carette and Dan, I've finished creating the `drasil-printers` subpackage. Here are the files currently in it:
- `Language.Drasil.Format`
- `Language.Drasil.Output.Formats`
- `Language.Drasil.Make` 
- `Language.Drasil.HTML`
- `Language.Drasil.TeX`
- `Language.Drasil.Printing`

Is there anything else that you would like moved to this subpackage?
