### ISSUE TITLE
Create drasil-docLang SubPackage

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#768]
The `drasil-docLang` subpackage should be created to start the process of supporting multiple languages.

## TODO
- [x] Move Files
  - Example.Drasil.DocumentLanguage
  - Example.Drasil.Sections
  - Example.Drasil.SRS
- [x] Fix examples

**Comment by JacquesCarette** [comment]
Right -- this would be the home for what is currently in `Example.Drasil.DocumentLanguage` (and all its support functions). `Example.Drasil.SRS` too.  This would be the start of being able to have multiple languages.

**Comment by samm82** [comment]
Should this export an Example.DocLang, or should examples only import what they need?

**Comment by samm82** [comment]
I just want to confirm with you - as of now, `drasil-docLang` needs Drasil.Sections, which is in `drasil-example`, so I'm going to move Drasil.Sections to `drasil-docLang`. @JacquesCarette

**Comment by JacquesCarette** [comment]
DocLang. And yes, move Drasil.Sections here too.

**Comment by samm82** [comment]
A lot of files have the import statement: `import qualified Drasil.SRS as SRS (<imports>)`. Should Drasil.SRS be another exposed module in drasil-docLang? I think that that would be the easiest solution, but I'm not sure what is desired here @JacquesCarette @szymczdm

**Comment by samm82** [comment]
And imports should be specified from DocLang, correct? Examples shouldn't just import the whole subpackage? @szymczdm @JacquesCarette

**Comment by JacquesCarette** [comment]
I think that `SRS` has a lot of names that clash with pre-existing names. But the names used are 'meaningful', so the easiest way to deal with that is to use `import qualified`. So it should indeed be another exposed module of `drasil-doclang`.  And right, let's specify the imports from DocLang.
