### ISSUE TITLE
Update READMEs

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#769]
READMEs need to be updated in the following directories:

- [x] datafiles
- [x] stable
- [x] code/
- [x] drasil-code/
- [x] drasil-code/Language/
- [x] drasil-code/Language/Drasil/
- [x] drasil-code/Language/Drasil/Chunk/
- [x] drasil-code/Language/Drasil/Code/
- [x] drasil-code/Language/Drasil/Code/Imperative/
- [x] drasil-code/Language/Drasil/Code/Imperative/LanguageRenderer/
- [x] drasil-code/Language/Drasil/Code/Imperative/Parsers/
- [x] drasil-data/
- [x] drasil-data/Data/
- [x] drasil-data/Data/Drasil/
- [x] drasil-data/Data/Drasil/Concepts/
- [x] drasil-data/Data/Drasil/Quantities/
- [x] drasil-data/Data/Drasil/Software/
- [x] drasil-data/Data/Drasil/Units/
- [x] drasil-docLang/
- [x] drasil-docLang/Drasil/
- [x] drasil-docLang/Drasil/DocLang/
- [x] drasil-docLang/Drasil/DocumentLanguage/
- [x] drasil-docLang/Drasil/Sections/
- [x] drasil-example/
- [x] drasil-example/Drasil/
- [x] drasil-example/Drasil/GamePhysics/
- [x] drasil-example/Drasil/GamePhysics/DesignDec/
- [x] drasil-example/Drasil/GlassBR/
- [x] drasil-example/Drasil/HGHC/
- [x] drasil-example/Drasil/NoPCM/
- [x] drasil-example/Drasil/SSP/
- [x] drasil-example/Drasil/SWHS/
- [x] drasil-gen/
- [x] drasil-gen/Language/
- [x] drasil-gen/Language/Drasil/
- [x] drasil-lang/
- [x] drasil-lang/Language/
- [x] drasil-lang/Language/Drasil/
- [x] drasil-lang/Language/Drasil/Chunk/
- [x] drasil-lang/Language/Drasil/Chunk/Concept/
- [x] drasil-lang/Language/Drasil/Chunk/Constrained/
- [x] drasil-lang/Language/Drasil/Development/
- [x] drasil-lang/Language/Drasil/Document/
- [x] drasil-lang/Language/Drasil/Expr/
- [x] drasil-lang/Language/Drasil/Label/
- [x] drasil-lang/Language/Drasil/NounPhrase/
- [x] drasil-lang/Language/Drasil/Sentence/
- [x] drasil-lang/Language/Drasil/URI/
- [x] drasil-printers/
- [x] drasil-printers/Language/
- [x] drasil-printers/Language/Drasil/
- [x] drasil-printers/Language/Drasil/HTML/
- [x] drasil-printers/Language/Drasil/Make/
- [x] drasil-printers/Language/Drasil/Output/
- [x] drasil-printers/Language/Drasil/Printing/
- [x] drasil-printers/Language/Drasil/TeX/

**Comment by samm82** [comment]
@JacquesCarette @szymczdm Should every folder have a README in it? Or can this issue be closed now that I've updated the existing READMEs (and created ones for consistency - ie. adding one to each subpackage)?

**Comment by smiths** [comment]
I agree with @szymczdm.  It is never wrong to have a README in a folder.  Future users are going to be grateful for the information.

**Comment by samm82** [comment]
If there's a folder with only another folder in it, would it be necessary to put a README in it? It makes more sense to me to just have a README in the inner folder to give specific what the file contents do.

**Comment by szymczdm** [comment]
It's not like it costs us anything to have a README as a placeholder. Maybe even with a brief description of why there's just a top level folder (ex. Contains all of the X code)

**Comment by smiths** [comment]
I agree with Dan.

**Comment by samm82** [comment]
Do you want READMEs in datafiles and stable? @szymczdm @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
I would think only at the top-level of those. I don't want to mix READMEs in with data files and test files.
