### ISSUE TITLE
Create Dependency Tree for #766

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#770]
As per #766, files are being moved around, so the dependencies need to be well understood before the files can be separated from `drasil-lang`. This can be done with the creation of a dependency tree of how the following files are dependent on `drasil-lang`:

- Language.Drasil.Format
- Language.Drasil.Output.Formats
- Language.Drasil.TeX
- Language.Drasil.HTML
- Language.Drasil.Make.Print

**Comment by JacquesCarette** [comment]
https://docs.haskellstack.org/en/stable/dependency_visualization/ should be helpful here.
