### ISSUE TITLE
Add Makefile function to make from master

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#775]
Sometimes, changes from a previous branch are propagated when building `master` on a local machine. Bumping the version number up and then down fixes this issue (cf. [FAQ <span>#<span/>2 in SubPackages wiki page](https://github.com/JacquesCarette/Drasil/wiki/SubPackages-Merge-Information#faq)). We should add an automatic process to the makefile (perhaps called `make master`) to bump the version number up, (potentially run `make`), then down again, and finally run `make` to remedy this automatically.

There also could be a way simpler solution to this that I'm missing, so I'll wait for approval from @JacquesCarette and/or @szymczdm before implementing.

**Comment by JacquesCarette** [comment]
This does not seem like a solution, but a bit of a hack. I would like more details, hopefully enough to be able to reproduce the issue, so as to better understand what's going on. Then we might be able to design a solution.

**Comment by samm82** [comment]
I'll describe how it happened to me:

1. Ran `make` on glassSRSGrammar branch
2. `git checkout` to master
3. Ran `make` on master - stable was updated to master's stable, but the code was still building the changes from glassSRSGrammar
4. Bumped version number in `drasil-example` (where I made the changes in glassSRSGrammar)
5. Ran `make` on master
6. Build worked as expected and matched stable
7. Bumped version of `drasil-example` back down
8. Ran `make`
9. Build still worked!

Notes:
- By reverting the version number back, no committing was necessary.
- This is a "local-machine-only" problem. The Travis CI build passed the whole time.

It seems that bumping the version number forced the code to re-compile and realize that it wasn't on the branch anymore. Let me know what more information you need.

**Comment by samm82** [comment]
I think the problem might be lying in the Makefile - all the packages are built off of `drasil-lang`, not the next level below it - I'll implement this in a branch and see if you agree.

**Comment by JacquesCarette** [comment]
I believe the issue is probably related to dependencies (in the cabal files) of each of the packages. It is a little hard to explain via text-box though.

**Comment by samm82** [comment]
Should we meet on Monday then, or should this wait til the Tuesday meeting?

**Comment by JacquesCarette** [comment]
I'm not around for 2 weeks. Ask @szymczdm on Monday, he should be around.

**Comment by samm82** [comment]
Right - OK

**Comment by JacquesCarette** [comment]
Cool - I didn't know about that option!

**Comment by samm82** [comment]
Running this also allows us to force recompile after a change in a package, so we only need to bump the version number once per change

**Comment by samm82** [comment]
Related to this, running `make stackArgs=--force-dirty` doesn't require a version number bump to recompile, so what should the understanding be about version numbers? Bump in every package you've changed with every major pull request? @JacquesCarette  @szymczdm

**Comment by JacquesCarette** [comment]
As I said, whenever you change the interface to a package, you should bump up its version number.  Otherwise not.
