### ISSUE TITLE
Update Drasil Version of SRS to Match Case Studies

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/Drasil#785]
Recent improvements to GlassBR in the Case Studies repo has meant some updates to the SRS.  @samm82 can you please look at the updates and propagate them to the Drasil version.

https://github.com/smiths/caseStudies/commit/daf5ffff607b3eaf725d0c73553a63c6f060838d#diff-5f1e6069263e93547d1c746eb6e6753c

Please coordinate with @niazim3, since she may still be making some edits to the SRS for GlassBR.

**Comment by samm82** [comment]
Working in updateGlassSRS

**Comment by samm82** [comment]
I'm going to close this issue, as this is being tackling in the Update GlassBR SRS Project more generally and in smaller steps.

**Comment by smiths** [comment]
Good idea.  When I created this issue I was assuming that the Drasil version and the Case Study version were essentially the same.  We had previous reviews that were intended to make them the same.  These previous reviews obviously missed a surprising number of differences.
