### ISSUE TITLE
Cleanup Assumption Implementation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#792]
In #360, it was mentioned that `acroNumGen` needs to be removed. 

This was an issue that was worked on in #518, where @elwazana added many `AssumpChunk`s to allow for referencing (this was before design or implementation of the `Label` solution that is currently being worked on in the [addLabels branch](https://github.com/JacquesCarette/Drasil/tree/addLabels)) that were essentially just different data types that held the labels/shortname that `Contents` couldn't.

Since `Label` is now being implemented, only one implementation should be kept: assumptions as `Contents` or assumptions as `AssumpChunk`s.

https://github.com/JacquesCarette/Drasil/blob/e154c9b29ec6745639190711e7d59c4bce2f4340/code/drasil-example/Drasil/SWHS/Assumptions.hs#L37-L63
https://github.com/JacquesCarette/Drasil/blob/e154c9b29ec6745639190711e7d59c4bce2f4340/code/drasil-example/Drasil/SWHS/Assumptions.hs#L171-L199

**Comment by JacquesCarette** [comment]
This is a bit more complicated than this, as @Mornix is working explicitly on generalizing how we deal with Assumptions, Likely Change, Unlikely Changes and Requirements. So whatever is done for this should be coordinated.

**Comment by niazim3** [comment]
@Mornix What are your thoughts on removing the `Contents` versions of the assumptions from the examples? In the addLabels branch, `AssumpChunk`s were given a `Label` field, which means those can be used for referencing purposes.

The document builds using the `AssumpChunk`s as well: https://github.com/JacquesCarette/Drasil/blob/71b4a83a4c834a871ceddf0bb4079b9d618a1b1a/code/drasil-docLang/Drasil/DocumentLanguage.hs#L484-L486
by calling https://github.com/JacquesCarette/Drasil/blob/71b4a83a4c834a871ceddf0bb4079b9d618a1b1a/code/drasil-lang/Language/Drasil/Reference.hs#L331-L334.

**Comment by Mornix** [comment]
I think these middle steps can be cut out and `Assumptions` can be completely migrated to `ConceptInstances` instead. I can do this since I've already started with requirements for NoPCM.

**Comment by Mornix** [comment]
I think `Reference2` and `ConceptInstance` took care of the issue here. Closing.
