### ISSUE TITLE
Pull out our "real" recipes

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#80]
We need to create parameterized recipes for our documents which take specific inputs and create documents from there. Our document templates provide insight into how to do this.

Currently it may be a bit unclear how to implement this, but the design will (hopefully) present itself soon, after more cleaning up and refactoring of the examples.

**Comment by JacquesCarette** [comment]
In some ways, `DocumentLanguage` represents a fair amount of work in that direction. Furthermore, any work on getting the OPG-format into place will continue to go in this direction.  I don't think that having this issue open will really remind us of anything. So I'm closing this one.
