### ISSUE TITLE
Propagating changes from caseStudies issue

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#817]
These changes were done and discussed in the issue: https://github.com/smiths/swhs/issues/35.

**Comment by smiths** [comment]
@elwazana I just assigned this issue to you.  Please propagate the changes from the manual case study to Drasil.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, I've added the DDs for \tau_W and \eta, but I had a few questions.

DDs (Top \tau_W| Bottom \eta):
![image](https://user-images.githubusercontent.com/35268928/42578786-ebc00ce8-84f4-11e8-8e59-646ade04ad7f.png)


1.  The Label field for the tables seems to be automatically generated based on the symbol's description. The only way I can change this to "Energy Balance Water Decay Time/Rate" as discussed in 
https://github.com/smiths/swhs/issues/35 would be to modify the description of the symbols themselves which I don't believe is a good solution.

2. The description doesn't seem to note the symbols "Unit" if that symbol is dimensionless\unitless

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, should I discuss @szymczdm before trying to fix it myself?

**Comment by smiths** [comment]
@danscime has added the missing definitions.  We can close this issue.
