### ISSUE TITLE
Differences in Title of GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#818]
The following differences exist between the Drasil (left) and caseStudies titles:

- [x] Remove "program" from the Drasil title
- [x] Add "W." to caseStudies author line
- [x] Fix effects in examples

![titles](https://user-images.githubusercontent.com/35857611/42574021-a39c58d0-84eb-11e8-80bc-de17409e73bd.png)

**Comment by smiths** [comment]
I don't think we need to worry about the lower title.  This would be a LaTeX difference.  As long as the case study title page looks balanced, we can leave it alone.

Please remove program from the Drasil title.  It is redundant information.

The W in the Drasil version might be there because that is how the author information is entered for me.  The W seems a bit pretentious, but with a last name like Smith, I need every hint I can provide to help people disambiguate me.   😄  It doesn't really matter, but you might as well change the case study version to match on the name.  This will prevent someone else wondering about this difference in the future.

**Comment by samm82** [comment]
Making this change results in this sentence: "This is followed by the solution characteristics specification, which presents the assumptions, theories, and definitions that are used **for the GlassBR.**" Which should be "for GlassBR", but this fix is entails a bunny trail of modifications that span across the examples. (Unless you don't really care about this change, I'll keep working on it - just wanted to let you know why I pushed such a simple issue off this long. 😄)

**Comment by samm82** [comment]
The effects in the examples:
- "that are used for Chipmunk2D game physics library." - Chipmunk
- "that are used for Solar Water Heating Systems." - NoPCM
- "that are used for slope stability analysis." - SSP
- "that are used for solar water heating systems incorporating PCM." - SWHS

Assuming that this is an OK fix, should I add the word "the" to the beginning of these `CommonConcept`s in the examples, and if so, which ones need it? (Chipmunk definitely does, and SSP might, but NoPCM and SWHS could go with or without.) @smiths

**Comment by smiths** [comment]
If we can come up with what this "tiny bit" of information is, I'm all for the suggestion of @JacquesCarette.  However, we should be cautious about getting too caught up on trying to capture English grammar.  We've fallen into this trap in the past and it has distracted from our current goals with Drasil.  If it isn't easy to automate, then we should leave it in the hands of the user for now.  Later on we can make Drasil smarter, but for now, we want to emphasize the "stupid" things that automation does well.  😄

**Comment by samm82** [comment]
So should this be hardcoded for now? If so, should I create a low priority issue for this, or should it just be left for now? @JacquesCarette @smiths

**Comment by smiths** [comment]
I like the idea of hardcoding it for now and creating a low priority issue to fix it in the future.

**Comment by smiths** [comment]
I'm fine with the proposed simplification to not mention the program name.  This will come up again in other places, but this particular place is not that interesting.  The text for this section should eventually be generated based on the information that is included for any example.  Right now I believe it is the same text for all of the examples, but if an example didn't have section, it would be nice if that section wasn't included in the "roadmap."  At present though, this isn't a high priority.

**Comment by samm82** [comment]
I figured it wasn't a super important issue - I'm just frustrated that such a "simple" fix is taking so long 😆

**Comment by smiths** [comment]
That is why we like math.  Once we bring natural language into things, everything gets more complicated.  😄
