### ISSUE TITLE
Missing System Context Section in Drasil GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#820]
The section "System Context" is missing from the Drasil (left) PDF entirely, in the table of contents and the document itself. Also, all references to other subsections of "General System Description" are shifted, due to the missing section.

![system context](https://user-images.githubusercontent.com/35857611/42574759-31c983e8-84ed-11e8-8b6b-28ea8fbe525f.png)

<ins>Example of shifted references:</ins>
![refs](https://user-images.githubusercontent.com/35857611/42574913-95341b78-84ed-11e8-9531-0edd0140f415.png)

---

This is what is missing:

![system context caseStudies](https://user-images.githubusercontent.com/35857611/42574849-6df6e4c8-84ed-11e8-90dc-49a2aef9870e.png)

**Comment by szymczdm** [comment]
That's interesting. Is there a System Context section somewhere in the Body.hs file that's not being used, or is it just missing entirely?

**Comment by smiths** [comment]
We are aware of the missing system context section.  The section was added to the case study version of GlassBR in:

https://github.com/smiths/caseStudies/issues/74

The issue for updating the Drasil version was assigned to @deviprasad135 in #574.

@deviprasad135, please work with @samm82 on closing issue #574.
