### ISSUE TITLE
General Definitions Section in Drasil GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#821]
There is a(n empty) General Definitions section in Drasil (left) that is not present in caseStudies. We should either remove it from Drasil, or add it to caseStudies. Also, references to subsections of "Solution Characteristics Specification" below it are shifted.

![gen defs](https://user-images.githubusercontent.com/35857611/42575258-023ed9f6-84ee-11e8-93c2-1662982180ff.png)

<ins>Example of shifted references:</ins>
![gen defs shifted refs](https://user-images.githubusercontent.com/35857611/42575392-57d11af0-84ee-11e8-9324-e3847734afe8.png)

---

This is the section contains:
![no gen defs](https://user-images.githubusercontent.com/35857611/42575435-77e938e0-84ee-11e8-863b-272b6ff2da96.png)

**Comment by szymczdm** [comment]
It should be added to the case studies. @smiths has mentioned if we remove sections from a template it's unclear whether they were forgotten or not applicable. Better to have it explicitly mentioned as being empty.

**Comment by smiths** [comment]
Agreed.

**Comment by smiths** [comment]
Looks good.
