### ISSUE TITLE
Differences in Table of Units in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#823]
The following differences exist between the tables of units in the Drasil (left) and caseStudies PDFs:

- [x] Capitalize column headers in caseStudies
- [x] Rename "unit" column to "Description" in caseStudies
- [x] Display all units used (ie. add meter, kilogram, and second) in caseStudies
- [x] Alphabetize units in caseStudies
- [ ] Update caseStudies description to match Drasil

![table of units](https://user-images.githubusercontent.com/35857611/42576162-b96a389a-84ef-11e8-9a15-bcf6bc2c374f.png)

**Comment by smiths** [comment]
I'll edit in my comments below.
- [ ] The Drasil table is centered while the caseStudies one is left-justified [This one is arbitrary.  We don't really need to change either case to match the other.]
- [ ] The column headers are lowercase and bold in caseStudies [To be consistent with the other tables, the headings in the case study should be capitalized]
- [ ] The "Description" heading in Drasil is split into "unit" and "SI", perhaps confusingly
  - Perhaps the "unit" column could be renamed to "used to measure" or something less ambiguous? [Yes, the case study headings are confusing.  Unit was meant to be the generic name for what is being measured, and SI is the unit symbol in SI.  Some day we might add other unit systems, like Imperial.  I think we can name the unit column Description to match the Drasil version.]
- [ ] Only the derived units (which is what is described in the highlighted section) are shown in caseStudies [Please change the case study to match the Drasil version.  We should list all of the units that are used.]
- [ ] Symbols are sorted alphabetically in Drasil [I prefer this.  Please change the case study accordingly]
- [ ] The description of the section has slightly different wording throughout [I believe we standardized the wording for this section in Drasil.  Please change the case study to match.]

@szymczdm, these differences that @samm82 is noticing should be useful for your writing.  What is happening is that Drasil is improving the consistency, within a case study, but also between case studies.  If we fix the wording for the table of units, we fix it for all of the examples.  If we fix the capitalization rules, we fix them within the entire document.

**Comment by samm82** [comment]
Do you think that the SI units (Newton, Pascal, etc.) should be lowercase in caseStudies or keep them capitalized?

**Comment by smiths** [comment]
The SI units should be lowercase in case studies.  I remember looking into this at one time and the names of the units are officially in lowercase.  (The unit symbol for proper names is capital, like N, but the name of the unit is newton.)
