### ISSUE TITLE
Differences in Table of Abbreviations and Acronyms in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#825]
The following differences exist between the tables of abbreviations and acronyms in the Drasil (left) and caseStudies PDFs:

- [x] Change "Symbol" column header to "Abbreviation" and "Description" to "Full Form" in Drasil
- [x] Remove the following from caseStudies: AR<sub>max</sub>, LDF, LR, LSF, NFL
  - These should instead be defined in the Table of Symbols - related to #824
- [x] Add the following to caseStudies: A, DD, GS, IM, LC, PS, R, SD, SRS, T, UC
- [x] Remove TU from Drasil
- [x] Remove TNT from Drasil
- [x] Remove TNT from caseStudies

![abbr and acro](https://user-images.githubusercontent.com/35857611/42578968-4d62b798-84f5-11e8-82aa-7bb3bda4f6e1.png)

**Comment by smiths** [comment]
I will edit in my thoughts below.

- [ ] The Drasil table is centered while the caseStudies one is left-justified [This is an arbitrary choice, although for this particular table, I think the left justified looks better.  There is no need to change it in either example.]
- [ ] Column headers are different: [The fields in Drasil seem to be borrowed from the table of symbols.  I prefer the headings in the table of abbreviations and acronyms.  Can we correct this in Drasil?]
  - [ ] "Symbol" in Drasil vs. "Abbreviation"
  - [ ] "Description" in Drasil vs. "Full Form"
  - [ ] Section headers are bold in caseStudies [It isn't a priority to make the two versions consistent on this formatting detail.]
- [ ] "TNT Equivalent Factor" in Drasil vs. "TNT equivalent factor" [I think I know the reason for this difference.  Acronyms are expanded with capitals in Drasil, to make the connection between the acronym letter and the word it stands for.  Unfortunately in the case of TNT the symbol's meaning isn't exactly an expansion of each of the letters.  Does TNT appear in the table of symbols for Drasil?  We should consider removing TNT entirely from the table of abbreviations and acronyms.  We aren't really treating it like an acronym.  We discussed this in a previous issue.  I think we should discuss only having TNT and other acronym inspired symbols only appearing in the table of symbols.  Please create a separate issue to discuss this point.]
- [ ] The following are missing from Drasil: AR<sub>max</sub>, LDF, LR, LSF, NFL
  - These are instead defined in the Table of Symbols of Drasil - related to #824 [I was just thinking about that.  I think these are better defined in the table of symbols.  Please update the case study to match Drasil.]
- [ ] The following are in Drasil but not caseStudies: A, DD, GS, IM, LC, PS, R, SD, SRS, T, TU, UC [Please add these to the case study.]

**Comment by samm82** [comment]
TNT is in Drasil's Table of Symbols, and I'll make an issue for discussing the table of symbols point.
