### ISSUE TITLE
Missing Sentence in Purpose of GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#827]
The sentence wrapped in red parentheses doesn't exist in caseStudies

![purpose](https://user-images.githubusercontent.com/35857611/42580090-be923180-84f7-11e8-9097-d71cb22d0eb9.png)

**Note:** There aren't italics in the Drasil version in the highlighted regions, but this will only be resolved once #12 is addressed.

**Comment by samm82** [comment]
Emphasis issue: #12 
Should I ignore this difference then?

**Comment by smiths** [comment]
Yes, you can ignore this difference.  Great work in finding the previous issue.  Can you please add a pointer to this discussion to the previous (closed) issue?  When we eventually return to the idea of adding emphasis, this example will be helpful.

**Comment by samm82** [comment]
@smiths This sentence references a reference not in caseStudies - I'm assuming I should add it?

**Comment by smiths** [comment]
Yes, please add it.  (You might want to read it too.  A great paper.)  😄
