### ISSUE TITLE
Minor Difference in Scope of Requirements Section in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#828]
For clarity/consistency, the last sentence in this section should be changed to "Given the appropriate inputs, GlassBR predicts whether a glass slab is safe or not." 

- [x] Drasil
- [x] caseStudies
- [x] Update other examples in caseStudies?

![scope](https://user-images.githubusercontent.com/35857611/42582800-05cfce30-84fe-11e8-8b93-9bd25f8b7518.png)

**Comment by smiths** [comment]
Although there will be many issues, I like separate small issues better.  It is easier to have the discussion.  If they are truly small, the issue will be closed quickly.  However, in some cases small issues turn out to be larger than expected.  In those cases, already having a separate issue is beneficial.

As far as this particular issue goes, this comes down to a style and preference.  For the name of GlassBR, let us decide right now to standardize on GlassBR, not Glass, glass, Glass-BR etc.  It is an arbitrary preference, but I believe GlassBR shows up more often than any of the other variations.  For the text itself, I actually prefer a combination.  Can you please modify both of the final sentences to read:

"Given the appropriate inputs, GlassBR predicts whether a glass slab is safe or not."

This will mean changing some of the non-highlighted text too.

**Comment by smiths** [comment]
It was intentional in that I recalled reading the title of an issue that implied a consistency problem with the naming, but unintentional that I made the same conclusion as you.  (To standardize on GlassBR.)  Glad to know that great minds think alike.  😄

**Comment by samm82** [comment]
This will change all the other examples, as this paragraph is controlled in drasil-docLang, not drasil-example

**Comment by samm82** [comment]
https://github.com/JacquesCarette/Drasil/blob/d8e343f1b4f0e6878da59f51dad282b4962c8ff6/code/drasil-docLang/Drasil/Sections/Introduction.hs#L81-L89

To word this section as proposed, should it be "hardcoded" here, or should I change/make a new `intendedPurpose`?

**Comment by smiths** [comment]
A new intendedPurpose makes sense to me.  I'm assuming the intendedPurpose is unique to each example.

**Comment by samm82** [comment]
This had a slight ripple effect throughout the examples. I just thought of something - if this happens, should I update caseStudies so we don't accidentally revert the change in the future?

**Comment by JacquesCarette** [comment]
I think so - because someone in the future might spot this discrepancy, flag it as a potential error, and waste people's time investigating it. They might not even find this issue until too late.

**Comment by smiths** [comment]
Yes, we are trying to keep the case studies and the Drasil versions the same for now.  At some point we will be in a position to abandon the case study, but we aren't there yet.
