### ISSUE TITLE
Should Drasil display "unitless"?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#830]
As uncovered in #824, Drasil doesn't display anything if a quantity is unitless. This occurs specifically in Table of Symbols but probably in other places as well.

![Drasil unitless](https://user-images.githubusercontent.com/35857611/42581226-445d6530-84fa-11e8-9d08-17cd4c4d0236.png)

@smiths, @JacquesCarette, @szymczdm - Is this the desired output, or should it display "unitless", as in caseStudies:

![caseStudies unitless](https://user-images.githubusercontent.com/35857611/42581347-88d46c54-84fa-11e8-8a1d-e93bafd51125.png)

**Comment by smiths** [comment]
@szymczdm and @JacquesCarette I vaguely recall a conversation about this.  To me it makes sense to explicitly say unitless, since otherwise the reader may wonder whether the author forgot something.  However, I seem to recall one of you having a reason for leaving the entry blank instead.

**Comment by szymczdm** [comment]
I remember there was an issue of it looking far more cluttered when "unitless" was printed, but in that case we should just give the option to switch it on or off.

@JacquesCarette do you remember why we decided on using blanks?

**Comment by JacquesCarette** [comment]
Because "unitless" is visually very distracting -- it is typically much longer than the rest of the units. So it draws the eye more than the rest, and it should be the opposite.

I am fine with not using blank but rather "--" or some such 'low footprint' visual symbol to denote "unitless".

**Comment by smiths** [comment]
The compromise proposed by @JacquesCarette is a good one.  We should use "--" to represent unitless.  I'll add to this that we should also include a note in the introduction to the table explaining that "--" means unitless.  @samm82, can you please create an issue for this.  You can assign it to yourself, or you can assign it to someone else.  Although it is a low priority, it would be nice to see this change propagated to the manual case studies too.

**Comment by samm82** [comment]
Issue created - #851
