### ISSUE TITLE
Improvement to System Constraints Section in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#832]
In addition to the reference number difference, addressed in #820, the Drasil version of the "System Constraints" section is more "complete". The caseStudies version should be updated to match.

![sys cont](https://user-images.githubusercontent.com/35857611/42582131-5e7829b2-84fc-11e8-86a3-dd6db70b939a.png)

**Comment by smiths** [comment]
Yes, please proceed.
