### ISSUE TITLE
Product Use Case Table Number in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#833]
This table is called "Table 2", despite being the first table in the document. It should be updated to "Table 1" to match caseStudies and be correct.

![product use](https://user-images.githubusercontent.com/35857611/42582555-7746f77e-84fd-11e8-9551-90879135983d.png)

The rest of the tables then need to be shifted ie. the following should be tables 2 and 3:

![other tables](https://user-images.githubusercontent.com/35857611/42583120-6914b8e8-84fe-11e8-92e3-fc4c556d4778.png)

**Comment by smiths** [comment]
Yes, please update the generated tex so that the table number is correct.  However, I have a feeling that this might be challenging.  It doesn't happen often, but I vaguely recall running into issues like this in the past.  It may be a weird interaction between LaTeX packages.  It might not be easy to diagnose the problem and come up with a fix.

**Comment by samm82** [comment]
The correct table number is shown when the Table of Symbols (the only `longtabu` before the Product Use Table; the Tables of Units and Abbreviations/Acronyms use `longtable*`) is removed. I think this is because there isn't a caption specified for the Table of Symbols, but the figure number is still "1", so the next `longtabu` (the Product Use Table) gets incremented to "2".

**Comment by JacquesCarette** [comment]
Any recommendation on how to fix this?

**Comment by samm82** [comment]
We could make every table referable (ie. give them captions with their numbers), although this could have formatting issues for the LaTeX. This would also allow us to reference these tables directly in the future.

**Comment by samm82** [comment]
An update: out of the three tables that appear before this "Table 2" (Table of Units, Table of Symbols, and Abbreviations and Acronyms), "Table 1" is the only one that uses `\begin{longtabu}` (Table of Symbols); the other two use `\begin{longtable*}`. This prevents them from having figure numbers and throws an error if a caption is added to it. Labeling these tables seems redundant, since they are the only thing in their section, and the section title labels the table quite nicely, but I think the easiest and most consistent fix would be to add a caption to every table, which will include changing `\begin{longtable*}` to `\begin{longtable}`.

Thoughts?

**Comment by smiths** [comment]
@samm82,  your recommendation seems to match with the comment from @JacquesCarette from last summer.  You can create a table with a caption, and set the caption to an empty string.

**Comment by samm82** [comment]
I interpreted Dr. Carette's comment to have an "empty caption" to mean that there shouldn't be anything under the table, but I think an "empty caption" as in no description is straightforward enough. My one suspicion is that an empty string will cause "Table #:" to be displayed under the table, and the colon would be unwanted, but I'll check it out tomorrow.

**Comment by smiths** [comment]
@samm82, you have a good point about the Table number.  I think what we are talking about is the same interface in Drasil, but having an empty caption in Drasil.  I'm sure @JacquesCarette will let us know what he is thinking.  :smile:

**Comment by samm82** [comment]
I've started a change, and it looks like the colon won't be an issue. Our current design is to have a boolean that denotes if a caption is shown and then a caption. If False, no caption (or table number) is displayed.

I'm changing it now to get rid of the boolean, and always print the caption, which can be an empty string. This might add an extra line in the HTML, but I haven't gotten that far yet. I might have to stash this change depending on what @JacquesCarette says, but I'm really curious to see how this will affect the generation!

**Comment by samm82** [comment]
The behaviour is changed so that every table is numbered (and labelled ie. "Table 1" in LaTeX) and the caption can be toggled ("Table 1" vs. "Table 1: Table of Units"). Will be closed with merge of #1250.

**Comment by JacquesCarette** [comment]
My opinion: good work @samm82 !
