### ISSUE TITLE
Removal of extra IM from GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#838]
In GlassBR's stable and implementation, risk of failure is both a data definition
![image](https://user-images.githubusercontent.com/28247301/42585333-4f9e37f4-8503-11e8-82b8-4c6610dcfc99.png)
and an instance model
![image](https://user-images.githubusercontent.com/28247301/42585357-643a1728-8503-11e8-8696-65ac0bc3bcb5.png).
According to the manual version in [/CaseStudies/glass/docs/SRS/glassbr_srs.pdf](https://github.com/smiths/caseStudies/blob/master/CaseStudies/glass/docs/SRS/glassbr_srs.pdf), it is not an instance model.

Edit: seeing commit d3cd3c3, it was added for testing purposes a while ago. @szymczdm is the test still relevant or can it be removed from the implementation?

**Comment by szymczdm** [comment]
It can, and should, be removed.
