### ISSUE TITLE
Only Acronym-Inspired Symbols in Table of Symbols?

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#842]
As mentioned in #825: "... Acronyms are expanded with capitals in Drasil, to make the connection between the acronym letter and the word it stands for. Unfortunately in the case of TNT the symbol's meaning isn't exactly an expansion of each of the letters.... We should consider removing TNT entirely from the table of abbreviations and acronyms. We aren't really treating it like an acronym.... I think we should discuss only having TNT and other acronym inspired symbols only appearing in the table of symbols."

**Comment by smiths** [comment]
I don't currently see a reason for having a symbol in the table of symbols and in the table of acronyms.  It seems to cause more confusion than help.  However, we did discuss this in past and there may be cases where we want this duplication.  In the case of TNT I could actually see the table of acronyms defining what TNT stands for ( TriNitroToluene) and the table of symbols defining the symbol as the TNT equivalent factor.  This seems unnecessarily complicated though.

@szymczdm and @JacquesCarette, what do you think of having something appear either as a symbol, or as an acronym, but not both?

**Comment by szymczdm** [comment]
I could see the symbol for the TNT equivalent factor being a stylized version of TNT (for example ***TNT***), whereas the acronym TNT would be shown in the table of acronyms to stand for TriNitroToluene. I do not believe we should ever have a symbol appear identical to an acronym (ie. the symbol for TNT equivalent factor should never be a plaintext TNT). To me that just screams confusion.

**Comment by JacquesCarette** [comment]
I concur with @szymczdm -- it should either be a symbol xor an acronym. I'm fine with the text 'TNT' to appear twice (i.e. as TNT and *TNT*) to mean different things too.

**Comment by smiths** [comment]
Good.  We agree that TNT will only be used as a symbol in GlassBR, not an acronym.  I do not believe that a stylized version will be necessary to distinguish the symbol from the acronym.  @samm82, can you ensure that TNT only appears as a symbol in the manual and Drasil versions of GlassBR?  Once this is checked, you can close this issue.

**Comment by samm82** [comment]
I added it to #825 and will fix it right now. Currently, TNT exists in the TAandA and the ToS in both repos, so I will remove it from the TAandA. Should "(Trinitrotoluene)" be included in the TAandA?

**Comment by smiths** [comment]
Trinitrotoluene doesn't need to be in the list of acronyms.  I'm sure it only comes up once at most.  We can use the long form when it comes up.  The case of symbols and acronyms being the same seems rare to me.  It comes up in GlassBR because that is how the ASME wrote it, but this pattern of using symbols and acronyms for double duty isn't particularly common in my experience.
