### ISSUE TITLE
Difference in Solution Characteristics Specification in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#846]
The "Solution Characteristics Specification" section is very different between the Drasil (left) and caseStudies versions.

![sol char spec](https://user-images.githubusercontent.com/35857611/42597361-72f0a3ae-8526-11e8-9e18-f66165b3e3a0.png)

**Comment by smiths** [comment]
Please update the case study version to match the Drasil version.
