### ISSUE TITLE
Missing Section Links in Assumptions Section in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#847]
The caseStudies version is missing links to references, and is also missing a great deal of references in the "Assumptions" section.

![assumps](https://user-images.githubusercontent.com/35857611/42597605-4db0aa02-8527-11e8-8d3b-dbb1a0fae5f8.png)

**Comment by smiths** [comment]
Please update the case study to match the Drasil version.

**Comment by elwazana** [comment]
@smiths I've updated the Assumption introduction paragraph to have these links:
![image](https://user-images.githubusercontent.com/35268928/42637897-44fe007e-85ba-11e8-8641-cb50f43daf87.png)

**Comment by elwazana** [comment]
https://github.com/smiths/caseStudies/commit/92672a859d8613018719e343a7a22597087230c7

**Comment by smiths** [comment]
Thank you @elwazana.  Very convenient!  I like your changes, although I did have a little LaTeX comment to share with you.  You'll see it as a comment with the commit.

**Comment by elwazana** [comment]
@smiths I believe everything involved with issue is closed including your requested changes in the commits themselves

**Comment by smiths** [comment]
Great.
