### ISSUE TITLE
Missing Reference in Assumptions GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#853]
Add reference with additional information to A2 in caseStudies.

![A2](https://user-images.githubusercontent.com/35857611/42639030-18a2c1e2-85bd-11e8-9019-1fc19417e277.png)

**Comment by smiths** [comment]
Yes, please add the reference information to the case study.  Also, please create an issue that will allow us to create references in Drasil that have extra information, like page numbers.  I don't know how difficult this will be, but as the examples @elwazana is working on in GlassBR (#824), we are finding that this extra traceability information is invaluable.
