### ISSUE TITLE
Missing DD/IM References in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#856]
Assumptions in Drasil don't reference the Data Definitions/Instance Models dependent on them.

![dd/im refs](https://user-images.githubusercontent.com/35857611/42640265-ecab1b18-85bf-11e8-8e40-af88f371b4ee.png)

**Comment by smiths** [comment]
We definitely want this traceability information in Drasil.  Is referencing now working?  Can this be implemented now?  Regardless of whether it is working now, we need this issue to remind us to not lose this traceability information.

**Comment by samm82** [comment]
We have to wait for `Label` on this one, but I'll hardcode it for now so we can change it once its been implemented. Should I then close the issue or not? There are other hardcoded "references", so I'm sure these will be updated regardless once we go through and remove the hardcoding.

**Comment by smiths** [comment]
Yes, your plan makes sense.   We'll close this issue now and we'll fix the hard code reference when we fix the rest of them.

**Comment by samm82** [comment]
Reopening it as a reminder to do the hardcoding 😄

**Comment by smiths** [comment]
Oops, I thought you had already done the hard coding.  😄
