### ISSUE TITLE
Missing Section Intros in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#857]
The Theoretical Model and Instance Model sections introduction are missing in caseStudies (right).

![tms](https://user-images.githubusercontent.com/35857611/42640435-4e181e78-85c0-11e8-8939-53ad79fcbc06.png)

![ims](https://user-images.githubusercontent.com/35857611/42641838-76e10466-85c3-11e8-951b-4647f1b41358.png)

**Comment by smiths** [comment]
Can you please add these introductions to the case study.
