### ISSUE TITLE
Different Names for Actual Thickness DD in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#858]
- [x] Change "actual thickness" to "minimum thickness" throughout caseStudies
- [x] Change title to "Minimum thickness" in Drasil

![act thick](https://user-images.githubusercontent.com/35857611/42640642-c19fa3e8-85c0-11e8-84ae-551a17a70697.png)

**Comment by smiths** [comment]
I almost agree.  h isn't the actual thickness though; it is the minimum thickness.  I believe that it is phrased this way in the original documentation to be conservative.  The thinner the window the weaker it will be, so they do their analysis with the minimum thickness.  The label for the case study also isn't right; it is too long.

I suggest that both labels are changed to minimum thickness.
