### ISSUE TITLE
Difference in Equation for J in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#859]
Change the Drasil version (left) to use AR to calculate J.

![stessDistFac](https://user-images.githubusercontent.com/35857611/42640994-853e8a8a-85c1-11e8-96c4-e39d77526f38.png)

**Comment by smiths** [comment]
I like AR better.  (This was one of the changes in the issue that you recently closed related to updating Drasil to match the case study.)  😄 The AR provides a better connection to the MIS and eventual code.

**Comment by samm82** [comment]
Should the note in caseStudies be changed to "AR is the aspect ratio defined in DD11." for consistency?

**Comment by smiths** [comment]
Yes.
