### ISSUE TITLE
Wrong Variable Referenced in NFL DD in GlassBR SRS

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#860]
In Drasil, make the highlighted note reference _h_ instead of _t_. 

![NFL](https://user-images.githubusercontent.com/35857611/42641232-15c3adba-85c2-11e8-8a2e-2d9093a6428f.png)

**Comment by smiths** [comment]
I noticed this earlier today.  I agree that we should remove the reference to $t$.  However, I would still like to include the information that h is defined in DD2 (in the case study version numbering).  This kind of traceability is valuable.

**Comment by samm82** [comment]
This turned out to be a simple fix - a note called `hRef` just used _t_ instead of _h_.

**Comment by smiths** [comment]
Yes, please change it to minimum.  Thank you.
