### ISSUE TITLE
Difference in Data Constraints Section Intro

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#862]
- [x] Change the first sentence to be "Table 3 and Table 4 show" in Drasil
- [x] The last sentence should be deleted in Drasil
- [x] Reference output constraints table in caseStudies (right)
- [x] Move the blue underlined sentences in caseStudies to the location in Drasil
- [x] Change the highlighted table reference in caseStudies to match Drasil, as this section is referenced by section and not table other places in the document
- [x] Remove the additional sentence about AR<sub>max</sub> in caseStudies, as this information is contained elsewhere

![data cons](https://user-images.githubusercontent.com/35857611/42645265-9ac14582-85cb-11e8-9082-d972546e5093.png)

Just comment with the changes you disagree with - hopefully this is easier/clearer 😄

**Comment by smiths** [comment]
Yes, the Drasil version is better (or at least equivalent).  Please modify the case study to match the Drasil version.  (Good idea to combine these issues.)

**Comment by samm82** [comment]
I just noticed that the first sentence in Drasil should be "Table 3 and Table 4 show.." instead of  "Table 3, and Table 4 show..." with the comma and without the 's'. @smiths

**Comment by smiths** [comment]
I agree on all points.

**Comment by samm82** [comment]
Should TU be change to Uncert. in all examples, and in future, should I assume that it's OK that a change affects other examples if I document it?
