### ISSUE TITLE
Input Data Constraints Table | Difference in Column Headings

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#863]
Do the following changes in
- caseStudies
  - [x] Expand Physical Constraints to the full wording
  - [x] Change Uncertainty to Uncert.
  - [x] Define Uncert. as Uncertainty in the text above the table
- Drasil
  - [x] Change TU to Uncert.
  - [x] Define Uncert. as Uncertainty in the text above the table
---

![cols](https://user-images.githubusercontent.com/35857611/42645854-1b7df0e8-85cd-11e8-94a3-9e82eebaa934.png)

**Comment by smiths** [comment]
Doing this exercise of comparing Drasil and caseStudies is very interesting.  You keep uncovering changes made by previous summer students that (as far as I can recall) I was unaware of.  The difference in Physical Cons is very likely just to make room for the heading Uncertainty.  TU is much shorter, so the full heading fits in Drasil.  I don't recall ever discussing TU.  I looked for an explanation in the paragraph above the table, but there is nothing there.  Searching for TU uncovers that it stands for Typical Uncertainty.  I don't actually like that the acronym is used, but never defined in the text of the document.  Moreover, it really isn't intended to be typical uncertainty.  The idea is that it is THE uncertainty that is being assumed for any value of the input.  Can you please do the following for both examples:

- expand Physical Constraints to the full wording
- Change TU/Uncertainty to Uncert.
- In the text above the table, define Uncert. as Uncertainty.

If in playing with the tables you have a different proposal, I'm sure that would also be fine.

**Comment by samm82** [comment]
So should TU be removed from the table of acronyms and abbreviations in #825? It isn't used anywhere else.

**Comment by smiths** [comment]
Yes.
