### ISSUE TITLE
Input Data Constraints Table | a and b vs. AR

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#865]
- [x] Switch "and" to "∧" in  Drasil (left) (#1336)
- [x] Switch the use of _a_ and _b_ to _AR_ in Drasil - fixed in smiths/caseStudies#129
- [x] Switch to "0 < b < a" in Drasil
- [x] Switch to "0 < b < a" in caseStudies

![ab/ar](https://user-images.githubusercontent.com/35857611/42646136-fcabd92c-85cd-11e8-9d53-968678ddacfe.png)

**Comment by smiths** [comment]
Thanks you for bringing up these differences.  Some of them are arbitrary choices, but we should still standardize if we can.  I suggest the following:

- use "∧" in Drasil
- use the Case study version with AR (ARmax makes more sense if there is an AR that also appears - we also use AR now (in the case study) throughout the SRS document)
- I like "0 < b < a" (I do not know how far we reached in Drasil for this, but our goal is to capture the knowledge that b is taken from the set of values between 0 and a (exclusive).  How we render this in the documentation (or in code) will depend on the rules for rendering, and possibly user preferences.)

**Comment by JacquesCarette** [comment]
So `0 < b < a` is 'encoded' using `RealRange` in Drasil (and then displayed properly). You don't encode it as it is displayed.

**Comment by samm82** [comment]
In a previous issue, I hardcoded the wedge (∧). Should I add an operator called `wedge` (similar to `` `sAnd` ``) that will add this wedge symbol?

**Comment by JacquesCarette** [comment]
So there really are two issues here:
1. the semantic 'and'
2. the display 'and' (which could be the word or the symbol, depending).

Because there is a choice on the display, I think we should make that somewhat parametric. On the semantic side, I do believe we should only have 'and'.

**Comment by samm82** [comment]
@JacquesCarette I'm confused about what you are saying. Should there be a `wedge` function or not?

**Comment by JacquesCarette** [comment]
There should be a `wedge` function, but it should only exist inside `drasil-printing` and not be externally visible.

**Comment by samm82** [comment]
In `drasil-printers`, there is a series of math operations, and one of them is:

https://github.com/JacquesCarette/Drasil/blob/59b5f43a7e1e76038dcf75f27531a040173184ba/code/drasil-printers/Language/Drasil/TeX/Print.hs#L158

https://github.com/JacquesCarette/Drasil/blob/59b5f43a7e1e76038dcf75f27531a040173184ba/code/drasil-printers/Language/Drasil/HTML/Print.hs#L203

Here is the definition of `RealInterval`:
https://github.com/JacquesCarette/Drasil/blob/59b5f43a7e1e76038dcf75f27531a040173184ba/code/drasil-lang/Language/Drasil/Space.hs#L39-L42

and the example in question:
https://github.com/JacquesCarette/Drasil/blob/59b5f43a7e1e76038dcf75f27531a040173184ba/code/drasil-example/Drasil/GlassBR/Unitals.hs#L74-L77

I think we should recursively define `RealInterval` to take a list of `RealInterval`s, so that multiple intervals can be joined with the wedge. I'm not exactly sure where the actual printing of this would need to be updated, but I'll keep looking.

**Comment by JacquesCarette** [comment]
`RealInterval` should stay as is, because that is really its semantics. What is actually the issue here is that in the original document, multiple constraints on *different* variables were being displayed on one line. We need to understand exactly what we're trying to say here to design the right structure. This needs discussion.

**Comment by samm82** [comment]
The status of this issue might have drifted a little - this is what the table looks like now:
![Input Data Constraints Table](https://user-images.githubusercontent.com/35857611/57139329-fed41a00-6d82-11e9-900a-e33db58f9f80.png)

Unless I'm mistaken, the physical constraint for _a_ should be "a > 0 ∧ a ≥ b". _a_ doesn't reference _AR_ anymore, since _AR_ has its own row.

**Comment by JacquesCarette** [comment]
Ok, good. So it is just a display issue - and can indeed be fixed.
