### ISSUE TITLE
Input Data Constraints Table | None vs --

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#867]
Change Drasil to produce "--" instead of "None"

(Related to #830)

![None/--](https://user-images.githubusercontent.com/35857611/42646363-bce00646-85ce-11e8-9386-a58f8f791f58.png)

**Comment by smiths** [comment]
Yes, the -- is better.  This is consistent with our discussion of unitless.  Please propagate this change.

**Comment by samm82** [comment]
Moved to #851
