### ISSUE TITLE
Add Capability for Additional Referencing Information in Drasil

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#874]
As discussed in #853, there should be functionality in Drasil to add additional information to references (ie. page numbers). Example: the following reference should be generated as "[astm2009, (pg. 1)]".

![add info ref](https://user-images.githubusercontent.com/35857611/42696679-f2ac9970-8686-11e8-82b5-857dd2dd9edb.png)

**Comment by samm82** [comment]
Should this be done with a `cite'`, `makeRef'`, etc. or by passing in a `Maybe String` with the extra information? @szymczdm @JacquesCarette

**Comment by szymczdm** [comment]
This seems like we need a more specialized way to create our citation references. As it stands we can create citations to specific pages/chapters/etc. in books, but we cannot create a reference to a specific subset of that.

Using customRef we can change the label that appears (ie. the `ShortName`), but I'm not sure how that will affect the formatting, and I don't believe it will have any affect on the LaTeX version.

**Comment by samm82** [comment]
I think that it should be added after the label, so that:
1) we can add more information than just page numbers
2) as it can then be added to the LaTeX
LaTeX has a nice way of adding this additional information by using `\cite[info]{citation}` that formats it like "[citation, info]"

**Comment by JacquesCarette** [comment]
I think we should take inspiration from LaTeX's \citep and \citet, which are even better than \cite. And we should be more 'semantic' about it (i.e. be explicit that it's page numbers, not something else; so not a `String`!].

**Comment by samm82** [comment]
One issue with enforcing that the additional information will be page numbers is that GlassBR references some equations from a source. I think we could implement a `makeCiteInfo` constructor that also takes a `Sentence` to be displayed, so we could input "pp. 1, 4-5, 7", "Eq. 4-5", or anything else. I don't think this information should be part of the link, just an extra bit of information to indicate where in the source the material is found. @JacquesCarette

**Comment by smiths** [comment]
@samm82, I still think @JacquesCarette is correct.  We want to be more semantic than just a string or sentence.  You are correct that there are cases other than a page number reference, which to me suggests that we need to have more categories than just page number.  We could provide an equation number, or a figure number, or whatever else comes up.  We just need for Drasil to know about that category.  The documentation can then follow whatever recipe is desired.  Maybe it will display eq 4, or Eq 4 or Equation 4.  We want to be able to change how it is displayed and keep that consistent.  If a person types it, we could get all 3 of the samples I just listed in the same document.

**Comment by samm82** [comment]
I came up with a helper function to parse a list of integers into a nice format (ie. [1, 4, 5, 6, 8, 9] -> "1, 4-6, and 8-9"). Would it be a hack to change the references field from `[Reference]` to `[Sentence]`? I haven't looked through the code fully, but it looks like for the most part, `Reference`s are converted to `Sentence`s at some point in the process, and having them being stored as `Sentence`s from the get-go would be a lot easier to process these lists of pages, equations, etc. @smiths @JacquesCarette

**Comment by smiths** [comment]
@JacquesCarette is the design expert, but your proposal sounds like a step backward in the design to me.  References can store information in a form that can be intelligently transformed to sentences, but I thought that once it was a sentence we can't really transform it any more.  If I understand correctly, we don't want `Sentence` until we are close to rendering the document.  @JacquesCarette will correct me if I'm wrong.  :smile:

**Comment by smiths** [comment]
@samm82, I really like the idea of parsing a list of integers into a nice format.  I just get the feeling that this should happen later in the transformation chain than you are currently thinking.  Again, I could easily be wrong.

**Comment by JacquesCarette** [comment]
Your instincts are right on this @smiths . We need a proper representation of things that are inside references.

**Comment by samm82** [comment]
@smiths @JacquesCarette 

This code:
`([makeCite astm2009, makeCiteInfo beasonEtAl1998 Equation [4, 5],
  makeCiteInfo campidelli Equation [14]])`

Now outputs this:
![addInfo](https://user-images.githubusercontent.com/35857611/58191867-74018380-7c8d-11e9-8c37-a0c6609dcca9.png)

The additional information is part of the link - is that OK? This also currently only shows up in the HTML, so I'll keep working on it.

**Comment by samm82** [comment]
UPDATE: The above code now generates this in the LaTeX:
![latexAddInfo](https://user-images.githubusercontent.com/35857611/58202679-2ba28f80-7ca6-11e9-9d4d-5f43e6e74a12.png)

and this in the HTML:
![htmlAddInfo](https://user-images.githubusercontent.com/35857611/58202708-39f0ab80-7ca6-11e9-961b-2bd2249cd06b.png)

The links work in both versions. I think the way these display is fine, but let me know if it should be formatted differently. @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
`drasil-printers` can depend on `drasil-data`, that's fine. This is likely to increase over time.

The output is good enough for now - it can be tweaked later if we so wish. The 'core' functionality is now properly implemented and that's what's most important.

**Comment by smiths** [comment]
I agree with the assessment of @JacquesCarette.
