### ISSUE TITLE
Intro Differences in Requirements Section

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#876]
- [x] Add the Drasil (left) Requirements intro to caseStudies
- [x] Add the caseStudies Functional Requirements intro to Drasil
- [x] ~~Update caseStudies for other examples~~ not doing this anymore

![req intros](https://user-images.githubusercontent.com/35857611/42702160-a87c59f2-8696-11e8-8a0b-616f4c400d3e.png)

- [x] Update casestudies Nonfunctional Requirement intro to match Drasil (including section title)

![non-func req](https://user-images.githubusercontent.com/35857611/42702228-e0ada538-8696-11e8-8c85-5b8364ab856e.png)

**Comment by smiths** [comment]
These also sound like great changes.  Please proceed.  Thank you for your thoroughness and attention to detail.

**Comment by samm82** [comment]
This change propagated into all other examples; should I update them in caseStudies as well? And should I make a new issue on that repo or just quickly fix it?

**Comment by smiths** [comment]
@samm82, you don't need to update the manual case studies.  I believe they have served their purpose.  Maintaining both the Drasil version and the case study version is becoming too onerous a task.

**Comment by samm82** [comment]
Consider this issue closed with the merge of `glassImprovements` (no PR to link to yet)
