### ISSUE TITLE
Ordering in Traceability Matrices and Graphs Section

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#883]
Data definitions and instance models should be switched in caseStudies to be consistent with Drasil (not shown for clarity - Drasil always puts instance models first). This might be arbitrary, and also occurs in the intro to traceability graphs (not shown).

![trace](https://user-images.githubusercontent.com/35857611/42703292-2c6b08b4-869a-11e8-8a0b-536292ce24b6.png)

**Comment by smiths** [comment]
Agreed.
