### ISSUE TITLE
Update Traceability Matrices

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#884]
Add DD10 and DD11 to Tracebility Matrices in:
- [ ] caseStudies
- [ ] Drasil (also add DD9)

Add UC1 and UC2 to Tracability Matrices in:
- [ ] caseStudies
- [ ] Drasil

![dds](https://user-images.githubusercontent.com/35857611/42703563-ece03e34-869a-11e8-9050-e705a7ec4800.png)

![ucs](https://user-images.githubusercontent.com/35857611/42703653-2a61be36-869b-11e8-95f8-2f82ab9b4354.png)

**Comment by smiths** [comment]
Great!  It will be very nice when these kind of additions are automated.

**Comment by samm82** [comment]
@smiths Should the traceability graphs be updated as well?

**Comment by samm82** [comment]
Also, I didn't include it, as the PDF cut it off, but the Matrices are very different in Drasil vs. caseStudies

|![Drasil1](https://user-images.githubusercontent.com/35857611/42894176-35bd5a5a-8a84-11e8-906a-faecf3073a31.png)|![caseStudies 1](https://user-images.githubusercontent.com/35857611/42894260-65995472-8a84-11e8-9db1-770e231bf36f.png)|
|:---:|:---:|
|_Drasil 1_|_caseStudies 1_|
|![Drasil 2](https://user-images.githubusercontent.com/35857611/42894402-c1b125a0-8a84-11e8-8549-7bc7b3ef8431.png)|![caseStudies 2](https://user-images.githubusercontent.com/35857611/42894437-dc80b22e-8a84-11e8-9e96-1e7f40abd145.png)|
|_Drasil 2_|_caseStudies 2_|

And I'm having a hard time figuring which points are correct (ie. in the first one, DD4 doesn't look related to IM1 **or** IM2, so I'm not sure if I'm reading them correctly).
Which one is correct/how can I proceed?

**Comment by smiths** [comment]
Throughout the case studies the traceability matrices and graphs are not done particularly well.  They are tedious to build manually and not all of the students understood exactly how to fill them in.  What we want is to capture the traceability information.  If something (a data definition, assumption etc) changes, what are the consequences of this change.  The best way I can think to deduce this information is to look at the write-up for the chunk that is being traced to.  Whatever chunks are mentioned in another chunk, those chunks are the dependencies.  Looking at IM1 (case study version), the only dependency I see is DD1.  Looking at IM2 (case study), the only dependencies I see are DD5 and DD6.  This is what I would use to fill in the traceability matrix; therefore, I agree that DD4 doesn't make any sense.

How automated is the traceability matrix in Drasil?  Ideally we should be able to deduce what parts of the document are being referenced and then put them in the traceability matrix.  The traceability matrix isn't really creating new information; it is just summarizing information that is already implied in the documentation.  The different view of this information is what is useful.

**Comment by JacquesCarette** [comment]
It is not at all automated -- this is something that @halonazhao should be able to tackle.

**Comment by smiths** [comment]
That sounds like a good idea.  This fits with the theme of @halonazhao MEng project.

**Comment by halonazhao** [comment]
This is another traceability matrix related issue. This issue can be closed now.
