### ISSUE TITLE
Changes to Table of Auxiliary Constants

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#886]
More explicit scientific notation should be used in:
- [x] caseStudies
- [ ] Drasil

Sections should be sorted by symbol in:
- [x] caseStudies
- [x] Drasil

![drasil pass the aux](https://user-images.githubusercontent.com/35857611/42704084-8f3385a0-869c-11e8-8ac1-367c6efe6caa.png)

**Comment by smiths** [comment]
I agree on both points.  The scientific notation problem is already noted in #325.  I'm not sure that this is a quick fix for Drasil.  For the case study version, please go ahead and fix it.  I'm not actually sure how the case study version was changed.  It was supposed to be done using the multiplication symbol.  

Hopefully the other fix (sorting) is easier.

**Comment by samm82** [comment]
Should this issue then be closed @smiths?

**Comment by smiths** [comment]
Yes, we can close this issue, since the problems with exponential notation are mentioned elsewhere.
