### ISSUE TITLE
Reference Sort in caseStudies

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#887]
I'm not sure if this is wanted, but caseStudies references could be sorted alphabetically to match Drasil

![ref sort](https://user-images.githubusercontent.com/35857611/42704158-c8f28a98-869c-11e8-8dd3-40591e123e23.png)

**Comment by smiths** [comment]
It probably doesn't matter that much, but it is better if the references are in the same order in both cases.  You'll have to look at the bibliography style to pick one that sorts the references alphabetically.  Feel free to change to any style that works.

**Comment by samm82** [comment]
Changing the bibliography style would also change the style of each reference (ie. not IEEE), so I think we might want to leave this, since it is fairly arbitrary.

**Comment by smiths** [comment]
In comparing the Drasil and Manual versions, the order of the citations is a greater distinction between them than the order of sorting.  However, I agree that it isn't a high priority to get them to match.  As long as both the Drasil and Manual versions have the same citations and handle referencing correctly, we are good.

**Comment by samm82** [comment]
In Drasil, Reference 4 (W. Lynn Beason et al) isn't used throughout the SRS, and doesn't appear in the caseStudies. Should I remove it, or is it there for when we fill in the source fields for the DDs?

**Comment by smiths** [comment]
Beason et al should have been included in the original case study.  I'm  not sure why it wasn't.  I've added it to the case study:

https://github.com/smiths/caseStudies/commit/dd80e264cd26bbe83051348c4918a139191705ba

Please update the Drasil version of GlassBR to reflect these changes.

**Comment by samm82** [comment]
@elwazana It's reference [4]

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, in the commit for caseStudies you link above you add a reference for an InstanceModel. In that case, should I remove the placeholder `fixme` for the `IM` table generation?

**Comment by smiths** [comment]
What fixme are we discussing for IM table generation?  The IMs should have a source field.  Don't they already?  I added a citation in my last commit to the case study, but there was already at least one source present before I added it.

**Comment by elwazana** [comment]
@smiths So the ASTM references weren't added from beforehand for either the data definitions or the InstanceModels when I noticed I added them. For the fixme the placeholder I'm referring to is the one we discussed in issue #890, it similar to the one that was in the data definitions source field.

**Comment by smiths** [comment]
Yes, please remove the fixme.  Ideally the Drasil version should match the case study.

I feel like this is becoming a chat between us, not an issue.  The title of this issue has little to do with the current discussion.  Please create new issues for new discussion points.

**Comment by elwazana** [comment]
@smiths Should this issue be closed? Or is it still ongoing?

**Comment by smiths** [comment]
Was the order of the references changed to match Drasil?  I don't see a link to a commit that makes this change.  Before closing an issue we should have a statement that resolves the issue.  Either we fix it, or determine that this isn't necessary.

**Comment by elwazana** [comment]
@smiths In the above discussion didn't you and @samm82 agree that the order was an arbitrary difference? 

So that the only change needed is to add Reference 4 (Beason et al) to case study (the commit linked to above) and to update Drasil to reflect those changes.

**Comment by smiths** [comment]
I wasn't sure that the decision converged, but I'm fine with leaving the order different.  

With respect to Reference 4, it does not appear that Drasil has been changed to include this reference.  Is your idea that this issue will be closed by closing #939?

**Comment by elwazana** [comment]
Yes, once #939 is completed Reference 4 should be appended along with references that should be in the source fields of the instance models. I'll add a checklist for the tasks needing to be completed in that issue to avoid this confusion.

**Comment by smiths** [comment]
Great, then you are correct that we can close this issue.
