### ISSUE TITLE
Differences in Appendix Figure Captions

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#888]
Last issue for this project (hopefully)! Hooray! 🎉 
- [x] "charge weight" should be capitalized to match Drasil (left)
- [x] Incorrect symbol used in Drasil (_m_ instead of _w_)

![image](https://user-images.githubusercontent.com/35857611/42704305-55d59a5e-869d-11e8-8d30-1a5910a844ec.png)

- [x] caseStudies AR should be capitalized and include the symbol to match Drasil
- [x] "(Function)" should be added to caseStudies
![image](https://user-images.githubusercontent.com/35857611/42704231-1b3a6a14-869d-11e8-8117-1f34a8e74703.png)

**Comment by smiths** [comment]
Yes, I agree.  Please make the proposed changes.
