### ISSUE TITLE
Source Field FIXME 

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#890]
As discussed in issue #824, information that needs to be appended to the Source field in Data Definitions cannot be done so as of now due to a "FIXME" placed in the generation of the DD tables with this commit:
https://github.com/JacquesCarette/Drasil/commit/f70bb0a32241506e0a1f69f18ca29e52bc9c4d63, which was a part of the yuzhi branch. 

The information that is missing is for DD1: Risk of failure and DD7: Dimensionless load, and it is a citation to:
![](https://user-images.githubusercontent.com/35268928/42698524-25a7deac-868c-11e8-8c9d-6eda7ff900c8.png)

With corresponding equation numbers to further trace the origins of the two Data Definitions (DD1: Eq. 14) (DD7: Eq. 7).

**Comment by halonazhao** [comment]
Hello @elwazana , "Fixme" is just a place holder. If you want to fill something in, feel free to change it back to `get Source`. Do you have something need to be done now? I mean the `citation` structure is already to be filled in?

**Comment by elwazana** [comment]
@halonazhao, @smiths wanted to create this issue and wait for this to be fixed before continuing with issue #824, but it seems like the FIXME isn't an actual issue that needs to be fixed so I'm closing this issue.

**Comment by smiths** [comment]
Great.  So now you can continue with the sub issue of #824?
