### ISSUE TITLE
Duplication of terms in the Table of Symbols for GlassBR

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#893]
This is a sub-issue originating from issue: #824 

![](https://user-images.githubusercontent.com/35857611/42783595-7bad847e-891a-11e8-8bfe-9512bb18cc99.png)

**Comment by elwazana** [comment]
@szymczdm @smiths Hello Dan and Dr. Smith, I was able to fix this issue. Dan was right about there being two separate chunks for `Stand off distance`. 
![image](https://user-images.githubusercontent.com/35268928/42837880-51a86fdc-89cd-11e8-83d0-b1ab4347d0f3.png)

One other change this caused was this used to be "from SD":
![image](https://user-images.githubusercontent.com/35268928/42838257-48ee6d64-89ce-11e8-95c7-a348acb84e59.png)

**Comment by halonazhao** [comment]
Hello @elwazana, 
do you know so far which SD definition should be removed?

**Comment by elwazana** [comment]
@halonazhao I've removed the `UnitaryChunk` SD, that one seemed to be used the least and was the one that was being placed after SD<sub>x</sub>, SD<sub>y</sub>, and SD<sub>z</sub> which was incorrect.

**Comment by halonazhao** [comment]
Alright, I did the same as you did. @elwazana Thanks!
