### ISSUE TITLE
Making Equations Referable

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#903]
The [addLabels](https://github.com/JacquesCarette/Drasil/compare/addLabels) branch contains the current work going into migrating from using `Contents` to `LabelledContent` (issues #695 and #629). All the `fixmelabel*`s have been removed from the logs when the implementation started using `LabelledContent` instead of `Contents` except for `fixmelabel3`, which is related to `EqnBlock`'s referencing method.
https://github.com/JacquesCarette/Drasil/blob/581b48a90cee885b8a0c5fb2fc1cd7427ebc000c/code/drasil-lang/Language/Drasil/Printing/Import.hs#L279-L301

I'm running into a problem because all the functions in [.../DocumentLanguage/Definitions.hs](https://github.com/JacquesCarette/Drasil/blob/addLabels/code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs) that make the fields for definitions and models produce a `ModRow`, which is defined as https://github.com/JacquesCarette/Drasil/blob/581b48a90cee885b8a0c5fb2fc1cd7427ebc000c/code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs#L92, which means not each field (i.e. Description, Notes, Source, etc.) of the TM, GD, DD, or IM is referable. 

Should `ModRow` be updated to `[(String, [LabelledContent])]` so that `lay'` for `LabelledContent` is used instead of the above-mentioned `Content`'s `lay`?  In yesterday's meeting it was mentioned that having extra information is better than having less, but is there a better way to reference equations without having to create numerous filler labels to get the referencing infrastructure to work?

Or should the definition kind of `EqnBlock` https://github.com/JacquesCarette/Drasil/blob/581b48a90cee885b8a0c5fb2fc1cd7427ebc000c/code/drasil-lang/Language/Drasil/Document.hs#L65 be updated to `EqnBlock Expr Label`, so the Label will be pulled from there instead of some "outer" type in the form of a `LabelledContent`? The only thing about this method is that for the equations themselves to be referable, `Contents` will have to become an instance of the classes `HasLabel`, `HasShortName`, and `Referable`, which is something that was decided as undesirable, so I feel that this would be going a step back, but can I get some feedback @JacquesCarette @szymczdm?

**Comment by niazim3** [comment]
Just noting here that replacing `"fixmelabel3"` with the current `RefAdd` from the `EqnBlock` will produce labels on the printing side of things, however, actually referencing them from Drasil will be a problem since `makeRef` won't work without `Contents` becoming an instance of the `HasShortName` and `Referable` classes mentioned above. We could potentially make `EqnBlock` the only kind of `Contents` that can be referenced as a `Contents` instead of `LabelledContent`, but semantically I think that doesn't make much sense.

**Comment by JacquesCarette** [comment]
Yes, `ModRow` should be changed to use `LabelledContent`.

Though I don't think that all pieces should **have** a label. I think we may be over-using things like `HasLabel` where we might only need `MayHaveLabel`, etc.

**Comment by niazim3** [comment]
This issue is now obsolete with the new design of `Content`, `UnlabelledContent`, and `LabelledContent` implemented in #962, `ModRow`s use `Contents` instead of `LabelledContent` to refrain from the overuse of labels (see https://github.com/JacquesCarette/Drasil/pull/962/files#diff-ce06d8e3fbb2528a353a1c50671fea39R79).
