### ISSUE TITLE
Broken Links to Instance Models in GlassBR

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#904]
In this Traceability matrix from Drasil (and probably elsewhere), the links to the IMs look like they should lead to Ts (ie. should be (IM:calOfDe) instead of (T:calOfDe)). The links are broken, but work when "T" is replaced with "IM".

![image](https://user-images.githubusercontent.com/35857611/42894817-f2060a9e-8a85-11e8-9aae-03bd984129fa.png)

**Comment by samm82** [comment]
@smiths @szymczdm @JacquesCarette Not sure who to @ for this one - there are a lot of comments saying that the current way this ^ is implemented is to be removed - will this be tackled via labels then?

**Comment by szymczdm** [comment]
Labels will definitely help, but I think there's a problem with how these tables are being generated in the first place. I'm fairly certain they're manually pieced together.

**Comment by samm82** [comment]
There is a lot of code for these matrices, but the code I found pertaining to this issue is here (608-609) with some context:
https://github.com/JacquesCarette/Drasil/blob/409f18a3729e44cc41e9e9efb5c1d5270d41d1e3/code/drasil-example/Drasil/GlassBR/Body.hs#L602-L624

`Theory` and `Data'` were both in the data type of `DType`, so I looked there and:

https://github.com/JacquesCarette/Drasil/blob/409f18a3729e44cc41e9e9efb5c1d5270d41d1e3/code/drasil-lang/Language/Drasil/Document.hs#L53-L63

Apparently `Theory` and `Data` are lined up to be removed and `Instance` doesn't take anything. Changing `Instance` to take a `RelationConcept`, then changing line 609 above to use `Instance` instead of `Theory` would fix it, but I'm not sure if this is a good idea given that we're trying to remove this implementation anyways.

**Comment by JacquesCarette** [comment]
Eventually this should all be automatically generated -- this is what @halonazhao is working on. All of those lines from `Body.hs` should disappear entirely.

**Comment by samm82** [comment]
Should I mark this as a duplicate and close it then? @JacquesCarette

**Comment by halonazhao** [comment]
Just checked all the links currently work well. And the traceability matrix can be automatically generated. So this issue can be closed.

One thing needs to be mention here. All the reference links now are made directly from chunk instead of its label.

**Comment by JacquesCarette** [comment]
Fantastic!
