### ISSUE TITLE
Fix Workaround from #897

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#905]
Find a proper solution for the workaround introduced in #897 where `stack` seems to not install newer binaries (despite claiming it is). This causes tests to (sometimes) be run on stale binaries.

Known workarounds:
* `--force-dirty` on `stack install`
* Bumping the version number

**Comment by JacquesCarette** [comment]
I've removed that `--force-dirty`. Bumping the version number is usually the correct solution, not a workaround.
