### ISSUE TITLE
SSP Mohr-Coulomb Shear Strength Theoretical Model Discrepancy

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#916]
The following shows up in the Drasil version of this theoretical model:
![image](https://user-images.githubusercontent.com/28247301/42956203-6083b486-8b4d-11e8-9088-61a66df958f7.png)

and this is the version in the CaseStudies repo:
![image](https://user-images.githubusercontent.com/28247301/42956128-31eb4102-8b4d-11e8-9dcc-739973252a56.png).
***
There are 2 main discrepancies:
1. **P** is used in the manual version the same places **τ** is used in the generated version. Just to preface my question, the two symbols are currently defined 
![image](https://user-images.githubusercontent.com/28247301/42956697-aaefede0-8b4e-11e8-9cc6-caf69891de3a.png) and ![image](https://user-images.githubusercontent.com/28247301/42956740-c07a2f2c-8b4e-11e8-900d-2f1d291c77f5.png). Looking at the discussion in #419, it seems that the Drasil version with **τ** is correct and case studies thus needs to be updated to use **τ** instead of **P**. @smiths, is this correct? (Edit: #348 is an issue that contains significant discussion related to this question.)

2. **tan(phi')=U<sub>s</sub>** in the case studies repo, however, a **U<sub>s</sub>** is not defined in the manual nor the generated table of symbols. Does this mean the **U<sub>s</sub>** is a typo in the manual version and should be changes to **U<sub>t</sub>** which is defined as 
![image](https://user-images.githubusercontent.com/28247301/42956511-22780718-8b4e-11e8-9d15-a9b1ec7f8205.png)?

**Comment by JacquesCarette** [comment]
Is this still current? @smiths I think you said that @bmaclach and you did a big review of SSP?

**Comment by bmaclach** [comment]
Based on the changes we made during our SSP revision, these inconsistencies are no longer present.

**Comment by smiths** [comment]
@bmaclach - you did a considerable amount of work on ssp.  Maybe we should add a chapter to your thesis on this topic.  Just kidding - your thesis is long enough!  :smile:
