### ISSUE TITLE
Update "Moment Equilibrium" General Definition to match manual version (SSP)

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#919]
This is the moment equilibrium general definition in Drasil: ![image](https://user-images.githubusercontent.com/28247301/42966617-c3f9188a-8b6b-11e8-8bab-79bbb3291a42.png) and the following is the one from the case studies repo (differences have been hightlighted): 
![image](https://user-images.githubusercontent.com/28247301/42966836-565bcd62-8b6c-11e8-8557-eccbf48c329c.png).
Since @smiths mentioned in #419 that the manual version has been corrected, the changes need to be propagated to Drasil's version of SSP.

**Comment by smiths** [comment]
Thank you for following up on this @niazim3.  I actually thought this had been done previously.  😄

**Comment by samm82** [comment]
Closed, since #1326 covers this discrepancy more in-depth.
