### ISSUE TITLE
Update "Hooke's Law 2D" general definition to match manual version (SSP)

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#920]
This is the current version of GD9 in Drasil:
![image](https://user-images.githubusercontent.com/28247301/42967574-ab58d740-8b6e-11e8-9852-ec01e602d362.png)

It was mentioned in #419 that the manual version of GD9 of SSP is correct (differences highlighted): 
![image](https://user-images.githubusercontent.com/28247301/42967541-90fe4f60-8b6e-11e8-8574-fac24bc36639.png)

Stable needs to be updated to match the manual version.

**Comment by smiths** [comment]
Agreed.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, I've investigated this issue for a bit and I believe there was a misunderstanding. I believe that the Drasil version is fine and that there was just a typo in GD9 of the manual. 

This is the table of symbols of the manual:
![image](https://user-images.githubusercontent.com/35268928/43409395-cbcc1e5c-93f1-11e8-9c67-4a72a6e192df.png)
![image](https://user-images.githubusercontent.com/35268928/43409413-d7cb1aa0-93f1-11e8-9de5-58d0db7a654e.png)

No `K`<sub>`t`</sub> or `p`<sub>`t`</sub> are defined in the maunal. 

I don't believe that Drasil needs to be fixed, just the typo in the manual version.

**Comment by smiths** [comment]
Sounds good.  Please fix the manual version.

**Comment by elwazana** [comment]
@smiths I've corrected the typo here:
https://github.com/smiths/caseStudies/commit/9a0705e98c71d61052a00b1cadda7fc446d37352
![image](https://user-images.githubusercontent.com/35268928/43412836-6768c0ea-93fc-11e8-838a-09313096aadc.png)

**Comment by smiths** [comment]
Great!
