### ISSUE TITLE
Make minor updates to SSP SRS to match manual version

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#921]
### Assumptions
- [x] add "[IM4]" reference to A2 to match manual: 
![image](https://user-images.githubusercontent.com/28247301/42953386-532e587c-8b48-11e8-86da-7af952a29abf.png) even if it is hardcoded in until labels are implemented successfully
- [x] ~~put "FS" in brackets for A6 to match manual:~~ outdated
![image](https://user-images.githubusercontent.com/28247301/42953423-69ac7ec6-8b48-11e8-8f6a-8e5fe184ce19.png)
- [x] ~~remove spaces between "stress - strain" in A7 to match manual:~~ outdated
![image](https://user-images.githubusercontent.com/28247301/42953452-78e5370c-8b48-11e8-8d90-b6a5a4217259.png)

### General Definitions
- [x] ~~GD5 needs the "x" in the description to be capitalized to match case-studies~~ outdated (Drasil vs manual:
![image](https://user-images.githubusercontent.com/28247301/42966488-47e00c90-8b6b-11e8-919f-a134e2ade972.png) vs 
![image](https://user-images.githubusercontent.com/28247301/42966473-40889b2e-8b6b-11e8-83f9-64775da40aed.png)
)

**Comment by smiths** [comment]
Very thorough.  Thank you.

**Comment by samm82** [comment]
This can be closed, as either the change has been completed or the affected text has been removed

**Comment by smiths** [comment]
Sounds good.  Thank you @samm82.
