### ISSUE TITLE
Symbol Sorting Is not Case Sensitive

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/Drasil#923]
Since symbol sorting is not case sensitive, so there may cause some unsure result. Say if list is given in order `q, Q`, the result would be `q, Q`. But if list is given as `Q, q`, the result would be `Q, q`. This shouldn't happen. The result is not supposed to be influenced by input order.

This needs to be further solved.

**Comment by JacquesCarette** [comment]
I think sorting should be case sensitive.

**Comment by halonazhao** [comment]
I have improved it to be case-sensitive. 5b6504a5003833114ff055fc4bfe4f00aba798f7
