### ISSUE TITLE
Migrate from using `QDefinition`s for Data Definitions to using `DataDefinition` data type

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#926]
Data definitions should be built using actual `DataDefinition`s instead of (what will eventually be) the simpler datatype `QDefinition`. In https://github.com/JacquesCarette/Drasil/commit/3b2993cfe177f88124d979fd0e6304ef27298bef#diff-d6f0b4483a86f614fa7fbae4e27fff46, `DataDefinition`s for GlassBR were created (this example specifically because the yuzhi branch had not been merged in by that time and it was meant for testing the data type).

#869 can be used as a guide on actually using the new lists of `DataDefinition`s (i.e. passing them into the `SystemInformation`). 

As mentioned in #747, the remaining examples should shift from using `QDefintiion`s to `DataDefinition`s. Please check off your task as it is completed.
- [x] SSP @niazim3
- [x] SWHS @elwazana 
- [x] NoPCM @elwazana 
- [x] GamePhysics @Mornix 
- [x] Tiny @elwazana 
---
- [x] Rename `mkDataDef` to `mkQD` or something similar, as it builds a `QDefinition`

@Mornix and @deviprasad135, if there are other issues that are higher priority, please feel free to re-assign  the examples to myself, @elwazana, or @samm82.

**Comment by niazim3** [comment]
Hi @Mornix, what is the status of this issue for GamePhysics?

**Comment by Mornix** [comment]
@niazim3 Totally slipped through the cracks. Should be up shortly.
