### ISSUE TITLE
Updating Tiny's "Data Definition" Implementation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#935]
[Tiny_log.log](https://github.com/JacquesCarette/Drasil/files/2220118/Tiny_log.log)
Since the merge of #930, there are discrepancies in the generated and stable versions.

Tiny's "Data Definitions" section looked like this before the use of section document language:  
![image](https://user-images.githubusercontent.com/28247301/43088687-c4de0b7c-8e70-11e8-9c27-44c06de5738c.png)

but now looks like the following: 
![image](https://user-images.githubusercontent.com/28247301/43088642-a7c01184-8e70-11e8-87c4-08998f925de2.png).

1. Can the SSD section and introduction remain since Data Definitions would go under that section in a  typical SRS? Or should Data Definitions remain a section on its own and a new solution be looked for since the [manual version in the CaseStudies repo](https://github.com/smiths/caseStudies/blob/master/CaseStudies/hghc/hghc_SRS.pdf) also has just a Data Definition section with no higher-level section? 
2. Should the Instance Models sentence be removed from `SCSSub` or an instance models section be added to this Tiny example?

**Comment by smiths** [comment]
Tiny isn't a real example, so we have some flexibility on what we can do with it.  I don't even think we should maintain the manual version of tiny.  We would just be making arbitrary decisions that we would later change to match the generated code.  

With respect to your specific question:

- I have no problem at all with the SSD section being added to tiny in the generated version.  At this time, I don't see any problem with extra boiler plate material.
- As far as the instance models go, I don't think we should mention them if there aren't any, and we definitely shouldn't be adding them to tiny.  Tiny won't be tiny if it has instance models.  😄 Can the code that creates this section only include a reference to instance models if they actually are part of the input?

Having said the above, if removing the text on instance models is onerous, we should make a low priority issue about this, but not bother fixing it at this time.  Tiny isn't a real example and we wouldn't want the needs of tiny to derail our other efforts.

**Comment by samm82** [comment]
So we should just ignore Tiny entirely for now?

**Comment by smiths** [comment]
If it is relatively easy to remove the text on the instance models, we should remove it.  Mentioning something that doesn't exist, isn't a good idea.  In the future there may be other examples without instance models.  If it isn't easy to remove the text, then I suggest that you create an issue (future enhancement) that automatically deduces the text for the document "roadmap" from the actual contents/recipe for the document.
