### ISSUE TITLE
Tiny_log is not empty, but Travis build did not fail

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#936]
Seems that merge of #930 results in non-empty logs for the Tiny example. For some reason though, the Travis build did not fail when the PR was opened. Why may this be the case?

(Issue #935 has been opened to deal with the contents of the logs.)

**Comment by JacquesCarette** [comment]
I'm guessing that some version number changed (or did not change), and/or a Makefile change made it so that the Travis build must have used an older version. I think this particular issue should be closed until it happens again.
