### ISSUE TITLE
Adding source field to Instance Models

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#939]
As discussed in #887, the `fixme` placeholder in the generation of the InstanceModel tables is being removed and for some instance models replaced with references to the original material.

**Comment by smiths** [comment]
Is this issue specific to a given case study, or does it apply to all of the examples?

**Comment by smiths** [comment]
In GlassBR (discussed in #887), all of the instance models have a source.

**Comment by elwazana** [comment]
- [ ] Append Reference 4 (Beason et al) from the manual into Drasil
- [ ] Propagate the appropriate reference in the source fields for the instance models seen here: 
https://github.com/smiths/caseStudies/commit/dd80e264cd26bbe83051348c4918a139191705ba

**Comment by smiths** [comment]
Looks good.

**Comment by elwazana** [comment]
@smiths These are the changes from the commit above:
![image](https://user-images.githubusercontent.com/35268928/43148548-8498ec4e-8f33-11e8-9533-ab90441e5e74.png)
![image](https://user-images.githubusercontent.com/35268928/43148596-9e13fbe6-8f33-11e8-8d8a-5f1ac0e5b20c.png)
![image](https://user-images.githubusercontent.com/35268928/43148624-ad068fa6-8f33-11e8-9946-5eb005a6ee42.png)
