### ISSUE TITLE
Printing rules for Expr multiplication and scientific notation.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/Drasil#941]
When we are printing out expressions involving multiplication we should follow a standard set of rules for explicitly showing the multiplication sign. We should decide on whether we want to use the dot, cross, or something else as the standard. I recommend showing the sign when:

- Multiplying anything by a number (ie. X\*2, 2\*2, etc.)
- Expressing scientific notation when not using E (essentially the same as above, since it's two numeric representations being multiplied together).

We also need to come up with (or find) a rule for how to determine when to automatically switch to scientific notation instead of showing all digits of a very large/small magnitude number. This also needs a standard presentation so we can have: n*10<sup>x</sup> or nE<sup>x</sup>, or some other variant.

@smiths and @JacquesCarette did I miss anything?

**Comment by JacquesCarette** [comment]
These probably should have been 2 issues - one for Expr multiplication, and one for scientific notation.  Who was going to do this?  I now forget that part...

**Comment by halonazhao** [comment]
**Rules for Multiplying:**
1. num `mul` symbol -> no `mul` symbol  eg. (2a) 
2. num `mul` num -> `mul` symbol (dot or star)  eg. (2*2 or 2 `dot`2) 
3. symbol `mul` num -> `mul` symbol (dot or star)   eg. (a*2 or a`dot`2)
   This rule can be improved to exchange the number and symbol to become `2a`
4. symbol `mul` symbol -> no `mul` symbol eg. (ab)
   This rule can be improved if the two symbols are the same, then (a*a) could be (a^2).

**Rules for large/small magnitude number:**
1. 1 < |number| < 1000 could be display directly eg. 369, 1200 should be "1.2`*`10^3"
   "exponent n is restricted to multiples of 3" 
   So for the decimal number apply the same rule. eg. 0.02, 0.002 should be "2`*`10^-3"
  Reference [Engineering notion](https://en.wikipedia.org/wiki/Scientific_notation)
2. "2`*`10^-3" can be represented as "2E^-3", but this is mostly used in Programming Languages.

Some comments on these rules?

**Comment by JacquesCarette** [comment]
I agree with the four rules of multiplying -- but not the 'improvement'. If someone enters a*a, they should get (a a). GIGO. [Garbage in, Garbage Out]

I also agree with the rules for numbers. You should include that link in the comments to the Haskell code as well.

**Comment by halonazhao** [comment]
Now we are considering using `Pow` to generate a scientific notation as a hack. But `Pow` is still valuable to generate scientific notion. Say if the number is `3*10^56` or `3*10^-56`, it's impossible that every time we type in those many zeros. So it would make sense to improve both `Pow` and `Int`, `Dbl` to auto-transfer to scientific notation. Int and double are straight forward. Would it be a good idea to improve `Pow` to do slight correction for scientific notation, like `300*10^4` to `3*10^6`?
@JacquesCarette

**Comment by smiths** [comment]
@halonazhao, I'm sure that @JacquesCarette is not recommending that someone type 56 zeros.  In Haskell (and any language I can think of), we can use scientific notation to enter large numbers.  Your examples would e written as 3E56 or 3E-56 (or with a lowercase e).  I'm sure that pow is needed for other purposes, but with scientific notation available, you don't need it to enter large numbers.  (Maybe I'm missing something?)

**Comment by halonazhao** [comment]
Wow. You are right. That didn't even come to my mind even one sec. Then I guess, the rest should be straightforward.
