### ISSUE TITLE
Should all sections use `LabelledContent`s instead of `Contents`?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#944]
In master, sections are built `[Contents] -> [Section] -> Section`: https://github.com/JacquesCarette/Drasil/blob/57041db81c6a9369096490eba94f8dc2b75cdcdb/code/drasil-docLang/Drasil/DocLang/SRS.hs#L39-L44.
With the creation of `LabelledContent` in the [addLabels branch](https://github.com/JacquesCarette/Drasil/tree/addLabels), **some** sections that contained `Contents` that should've been referencable were changed to  `[LabelledContent] -> [Section] -> Section`: https://github.com/JacquesCarette/Drasil/blob/3e2af27115c27ef28516f4a844bc4ff55b8543d4/code/drasil-docLang/Drasil/DocLang/SRS.hs#L81-L83.

@JacquesCarette @szymczdm Should the remaining `Section`s that are built in the "old" manner (i.e. using `Contents` instead of `LabelledContent`) be updated to take in `LabelledContent` even though the labels of such contents will usually just be `Nothing`?

I'm asking because making that update will allow for `SecCons` to only consist of either labelled contents or sections instead of its current definition https://github.com/JacquesCarette/Drasil/blob/3e2af27115c27ef28516f4a844bc4ff55b8543d4/code/drasil-lang/Language/Drasil/Document.hs#L100-L102, which will further allow a lot of duplication to reduce from the printing side of Drasil since `Con` is one less pattern to match and produce documentation for.

**Comment by niazim3** [comment]
In our meeting today, the following was discussed:
- `HasMaybeLabel` should be renamed to `MayHaveLabel`
- we need to create a `HasContents` class
- both LabelledContent and UnlabelledContent shouldn't have UIDs
- current `Contents` should become `RawContent`
- `UnlabelledContent` is another name for `RawContent`
- `LabelledContent` is a wrapper for `RawContent` and a `Label`
- `LabelledContent` should be an instance of `HasLabel`, `MayHaveLabel`, and `HasContents`
- `UnlabelledContent` should be an instance of `MayHaveLabel` and `HasContents`
- `Contents` will be a data type = either `UnlabelledContent` or `LabelledContent`
- `MayHaveLabel` should be a getter
- `HasLabel` should be a lens

*** 
I guess with regard to my question, in order to build a `Section`, we'd want to pass in `[HasContents] -> [Section] -> Section`.

@szymczdm @JacquesCarette If any of the points above are unclear/incorrect, can you please let me know? Otherwise, I think this issue can be closed since my question was answered and a design has  been discussed.

**Comment by szymczdm** [comment]
![img_20180724_154710](https://user-images.githubusercontent.com/235140/43177284-85f9d014-8f95-11e8-8476-a1bd56de94b8.jpg)

Just adding the blackboard state for posterity.

**Comment by JacquesCarette** [comment]
I think you are correct on all points (including your answer to your own question).
