### ISSUE TITLE
Review to ensure consistency across Manual and Drasil for GlassBR

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#948]
Changes done to the manual here: https://github.com/smiths/caseStudies/issues/132 should be in Drasil.

If not then these changes need to be propagated into Drasil. The changes are to the GlassBR example and deal with the units of various symbols such as `dmax`/`dmin` (mm -> m), and `q` (kPa -> Pa). Along with any conversion factors in the equations found in the tables.

**Comment by elwazana** [comment]
Occurrences in Drasil of incorrect units:
![image](https://user-images.githubusercontent.com/35268928/43164811-2cdab6f4-8f60-11e8-84c3-83e95118e406.png)

![image](https://user-images.githubusercontent.com/35268928/43164859-4f9d683a-8f60-11e8-9d7c-f5ea00a97d82.png)

![image](https://user-images.githubusercontent.com/35268928/43166732-5d439ebe-8f65-11e8-8380-2bc006df6fbb.png)

Fixes:
![image](https://user-images.githubusercontent.com/35268928/43164840-41eaa00e-8f60-11e8-83c4-d886b2c2626a.png)

![image](https://user-images.githubusercontent.com/35268928/43164899-6fec6faa-8f60-11e8-9f12-b39b4e2f2842.png)

![image](https://user-images.githubusercontent.com/35268928/43166757-74a4bb42-8f65-11e8-9d0a-9681e79f1d73.png)

There are more changes that can be found here: 791b33184742a58a4f83a0d9928239b644d9770e

**Comment by smiths** [comment]
Looks good.
