### ISSUE TITLE
Remove obsolete fields from `QDefinition`

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#973]
As mentioned in #747, the fields of `QDefinition`s with the comments next to them need to be removed. https://github.com/JacquesCarette/Drasil/blob/52ce04abb429590e4826627de25645296ad002e1/code/drasil-lang/Language/Drasil/Chunk/Eq.hs#L26-L35

**Comment by niazim3** [comment]
A lot of duplicate functions were also created when migrating from using `QDefinition`s to `DataDefinition`s that should be removed.

**Comment by JacquesCarette** [comment]
`_deri` was removed in 2ecc341f2.

**Comment by JacquesCarette** [comment]
_notes removed in 6f3688f3e.   Looks like `makeQField` in DocumentLanguage.Definitions might be obsolete.

**Comment by JacquesCarette** [comment]
_ref removed in 3323e69e6.

**Comment by JacquesCarette** [comment]
_lb removed in e4e7d120b. This doesn't quite remove all of the duplicate functions, so will not close until that is also done.

**Comment by JacquesCarette** [comment]
closed by dd4f5ad5a.
