### ISSUE TITLE
Distinguishing labels for Functional and Non-Functional Requirements

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#975]
With the new implementation of requirements as `ConceptInstance`s, instead of the old `ReChunk`, it is difficult to distinguish between Function/Non-Functional requirements. As such appending the correct prefix becomes difficult. The idea originated from issue: #970

**Comment by smiths** [comment]
Sounds good @samm82.

**Comment by Mornix** [comment]
Unless I’m misunderstanding, NFRs should be individually referable as they’re `ConceptInstance`s. Similarly, NFRs can be included in the traceability matrices by adding the `ConceptInstance`s to the `ChunkDB`. 

As for the 'R', that’s hardcoded at the example-level as part of the old traceability matrices. The automated traceability matrices are the very large ones. #1197 is outstanding and is posed to add “views” to the large traceability matrices to get smaller sunsets similar to the existing manual ones. Ideally when #1197 is closed, the manual matrices will be completely gone.

**Comment by samm82** [comment]
@Mornix Just confirmed that NFRs display correctly when referenced - this issue can be closed/address with #1197 then.
