### ISSUE TITLE
Remove incorrect prefix for ConceptInstance

### ISSUE THREAD

**Issue by elwazana** [JacquesCarette/Drasil#976]
As discussed in issue #970, there are new requirements in NoPCM that are defined as `ConceptInstance`. This brings up a problem when you try to reference these requirements, an incorrect IM prefix is appended to them:
![](https://user-images.githubusercontent.com/35268928/43646872-0a1ffe7a-9704-11e8-84bd-a345f865b23a.png)

This  is caused by `instace Referable ConceptInstance`:
![](https://user-images.githubusercontent.com/35268928/43646720-a8b655da-9703-11e8-8548-69faca21a761.png)
(The note that says this isn't used is incorrect)

The problem I've run into is that `rType` is expecting a `RefType` to be returned, and currently there is not pesudo `Blank` reftype. Should I add a "blank" `RefType` that would append no prefixes for references? 
@JacquesCarette?

I've tried to find other ways to remove the incorrect prefixes but with the way those prefixes are implemented something needs to be fed in.

Note: The incorrect prefix is only appended to the shortname the refAdd is unaffected, meaning the links themselves still function appropriately.

**Comment by JacquesCarette** [comment]
That `instance Referable ConceptInstance` is definitely the source of the bug.  For now, yes, add a `Blank`.

Once @Mornix 's work on `ConceptInstance` is further along, `rType` should be computable. `rType` will have to look at the specific `ConceptInstance` though.

**Comment by elwazana** [comment]
The `Blank` `RefType` has been added here: 32a7dede5ae069cb7ad873b88c1036d61843c4e8, along with the relevant stable updates.

**Comment by Mornix** [comment]
`RefProg` fixes this issue. Closing.
