### ISSUE TITLE
Remove use of `midRef`

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/Drasil#982]
(Moved from #963)

`midRef` was implemented and used in the addLabels branch for a reason that is now obsolete, but has been merged into master. Since it's essentially using `customRef` and `Label`s are now instances of `Referable` and `HasShortName`, `midRef` doesn't have any special purpose.

Therefore, `midRef` should be replaced with `makeRef` everywhere it's used.

**Comment by JacquesCarette** [comment]
closed with aabe5e5dc.
