### ISSUE TITLE
TeX Printer doesn't use ShortName

### ISSUE THREAD

**Issue by Mornix** [JacquesCarette/Drasil#984]
Through working on supporting deferred chunk lookups for `ShortName` (#562), I found the TeX backend doesn't use `ShortName` when printing references. 

Aside from not being consistent with the HTML, both in text (in certain situations) and for which part of the word/phrase is included in the link, this leads to two completely separate ways which names for references can be constructed. I know TeX gives labels "for free," but Drasil (at least at the moment) does not enforce that a `ShortName` should be consistent with the TeX representation. 

Below is a snippet from TeX's Print.hs, where the third argument to the `Ref` is the short name. 
```haskell
spec (Ref t@RT.Sect r _ _) = sref (show t) (pure $ text r)
spec (Ref t@(RT.Def _) r _ _)  = hyperref (show t) (pure $ text r)
spec (Ref RT.Mod r _ _)    = mref  (pure $ text r)
spec (Ref (RT.Req _) r _ _)= rref  (pure $ text r)
spec (Ref RT.Assump r _ _) = aref  (pure $ text r)
spec (Ref RT.LCh r _ _)     = lcref (pure $ text r)
spec (Ref RT.UnCh r _ _)     = ucref (pure $ text r)
spec (Ref RT.Cite r _ _)   = cite  (pure $ text r)
spec (Ref t r _ _)         = ref (show t) (pure $ text r)
```

As a workaround, I can add proper support for `Deferred` `RefType`'s although that feels like a slight step backwards.

**Comment by JacquesCarette** [comment]
Good catch. The TeX backed should be 'properly' fixed. It is Ok to do it incrementally (and easier too, so that each change in 'stable' is more easily traceable).

**Comment by szymczdm** [comment]
I believe this stems from the original Referencing implementation, where HTML was trying to mimic TeX. It should definitely be incrementally fixed

**Comment by JacquesCarette** [comment]
This is something that can, and should, be done incrementally.

**Comment by Mornix** [comment]
#1026 is (partially) related.

**Comment by Mornix** [comment]
`Ref2` takes care of this. #1026 is related but is only relevant to the removal of those functions. Closing.
