### ISSUE TITLE
Missing (?) GD12 in SSP

### ISSUE THREAD

**Issue by samm82** [JacquesCarette/Drasil#988]
The Data Definitions of SSP (shown) references GD12, but there are only 10 General Definitions in this example. Is this a mistake, or will there be more General Definitions added in the future?

![gd12](https://user-images.githubusercontent.com/35857611/43911306-2f6e5992-9bcd-11e8-9e32-cb781b9cf74e.png)

K<sub>bt</sub> is defined here, but not as a matrix in DD18.

![image](https://user-images.githubusercontent.com/35857611/43911538-bda4c6c4-9bcd-11e8-87e7-7974fd140bc9.png)

**Comment by smiths** [comment]
There are no plans to add more GDs to this document.  In fact, some of the material is more likely to be removed.  The rigid finite element sections should really be either removed, or fixed.  The theory is not currently documented correctly.

As far as the numbering goes, if they are generated automatically, then I would think re-running the generator would help.  If they are hard-coded in, we should remove the hard-coding.  Hard-coded numbers are a bad idea.

**Comment by samm82** [comment]
So should I just remove the sentence with GD12?

**Comment by smiths** [comment]
Yes.
